### ISSUE TITLE
Icons doesn't work properly on ST

### ISSUE THREAD

**Issue by enes4949** [jarun/nnn#1007]
- [x] Operating System: Arch Linux
- [x] Terminal Emulator: st
- [x] Shell: Bash, Zsh

#### Exact steps to reproduce the issue
Clone and install [my st fork](github.com/enes4949/st). Launch nnn with icon support.

Icons are cropped on my terminal.
![2021-05-14_13-58](https://user-images.githubusercontent.com/63241739/118261723-7fb26a00-b4a3-11eb-9edb-37b68a80e11a.png)

**Comment by luukvbaal** [comment]
Please look through the issue history, see #969.

**Comment by jarun** [comment]
@luukvbaal @KlzXS any ideas?

**Comment by luukvbaal** [comment]
About whether this can somehow be avoided in `nnn` without the `st` patch mentioned in #969, I'm not sure.

**Comment by luukvbaal** [comment]
I did notice the issue sometimes went away while working on my `print_details` fork. I think it had something to do with printing `ICON_PADDING_RIGHT` with or without certain `attrs`. Fixing it on `st` side with the patch mentioned in #969 should be the better option though.
