### ISSUE TITLE
Update selection file when file list updates

### ISSUE THREAD

**Issue by rieje** [jarun/nnn#1012]
I have a script that trashes a file selected by nnn using the selection file. I run it externally, and when I return to nnn, the file trashed still shows until I attempt to open it (should nnn have updated the file list automatically or is this by design?).

Anyway, once the file list is updated to reflect that the file was trashed, nnn still shows this file/directory as marked. This seems never useful or desirable, so perhaps nnn should update the nnn selection file when the file list is updated to remove all entries that are no longer in the file list? Otherwise, with the file still in selection, selecting any other file and performing actions on the selections will not be possible since it will be aborted because it is attempting to act on the trashed file and this is not possible.

**Comment by jarun** [comment]
Your plugin should [clear selection on exit](https://github.com/jarun/nnn/tree/master/plugins#send-data-to-nnn) and should _not_ [disable dir refresh on exit](https://github.com/jarun/nnn/tree/master/plugins#skip-directory-refresh-after-running-a-plugin).
