### ISSUE TITLE
Copier example for xclip ?

### ISSUE THREAD

**Issue by qutetemp** [jarun/nnn#102]
This should be easy peasy but I'm having some difficulties.
Shouldn't 

#!/bin/sh
echo -n $1 | xclip -r

just work ?
I'm on the latest commit as of now.

**Comment by qutetemp** [comment]
The default copier also doesn't seem to work (the one using xsel) and trying with the "no X" env variable shows that I need to set NNN_COPIER. I may have misunderstood tho.
What can I do to help ?

**Comment by jarun** [comment]
On the terminal, run:

    $ copier.sh 'https://github.com/jarun/nnn/issues/102#issuecomment-379855557'
then press <kbd>Ctrl-Shift-V</kbd>

The output should be:

    https://github.com/jarun/nnn/issues/102#issuecomment-379855557
If not, you have to setup your copier script correctly.

Here's what I have:

    export NNN_COPIER="/usr/local/bin/copier.sh"

> and trying with the "no X" env variable shows that I need to set NNN_COPIER
I don't understand. If you have `NNN_NO_X=1` set, you don't need the copier script.

**Comment by qutetemp** [comment]
>Goes beyond saying copier.sh should be in your PATH.
OHHH. I see I'm sorry.
I guess this issue is solved but is there a simple way I can get full paths for everything under the directory where I run vidir ?
