### ISSUE TITLE
Key remap

### ISSUE THREAD

**Issue by ThomasBucaioni** [jarun/nnn#1021]
Is it possible to remap the keys with a config file (my keyboard is Dvorak)?

**Comment by KlzXS** [comment]
All the keybinds are located in [src/nnn.h](https://github.com/jarun/nnn/blob/master/src/nnn.h). Update them to your liking and recompile.

`nnn` doesn't use any config files, all config is done at compile time.

**Comment by jarun** [comment]
Also, see option `-K`.

**Comment by ThomasBucaioni** [comment]
Cheers, having a look

**Comment by Kabouik** [comment]
Note that if you edit keybindings in `nnn.h` (which I do at every pull to disable <kbd>x</kbd> to delete), you'll have to edit the
keybinding descriptions (`?` screen in `nnn`) accordingly too.

**Comment by ThomasBucaioni** [comment]
@Kabouik Indeed, thank you for the warning
