### ISSUE TITLE
Persistent named sessions

### ISSUE THREAD

**Issue by mizlan** [jarun/nnn#1023]
**Is your feature request related to a problem? Please describe.**

Right now, you can either have a persistent default `@` session (`-S`), or non-persistent named sessions (`-s <name>`)

**Describe the solution you'd like**

I want the ability to persist named sessions. This would help where `nnn` is embedded in text editors, for example.

**Describe alternatives you've considered**

I have not considered alternatives to having persistent named sessions as a concept, but there are definitely some options to be weighed when considering how to implement this (details linked in issue below).

**Additional context**

Please view https://github.com/mcchrish/nnn.vim/issues/43#issuecomment-844600905 to understand the context of this request and the proposed solutions.

**Consider contributing**

I am more than eager to write this patch, but I need some pointers on how to proceed.

**Comment by mizlan** [comment]
Here's the deal. Currently, when both `-S` flag and `-s <name>` flag are passed, only the later one has any effect. This is because the value of `session` is overwritten during option parsing:

https://github.com/jarun/nnn/blob/36e1544b323e0ba4f5d81a7f5a840ad757fc952b/src/nnn.c#L7766-L7772

Also good to note is that `nnn` only checks if the session should be persistent when the program exits:

https://github.com/jarun/nnn/blob/36e1544b323e0ba4f5d81a7f5a840ad757fc952b/src/nnn.c#L7189-L7190

As a result, _if we wanted to_, we could have a named persistent session in the form of passing both flags in either order: `nnn -S -s <name>`.

**Comment by jarun** [comment]
I am already working on it. In the same line so we are good.

**Comment by mizlan** [comment]
The behavior isn't exactly as desired. There is still an error message when I try to create a session that is nonexistent (I would instead expect for it to be created).

**Comment by jarun** [comment]
It is created. The msg comes the first time you load it because it's non-existent.

**Comment by jarun** [comment]
Maybe we can get rid of it now that we know we will create it if it doesn't exist.

**Comment by mizlan** [comment]
Yeah, I was referring to the error message. I agree with removing it since `-s <name>` will always succeed, but its behavior may differ.

**Comment by jarun** [comment]
On second thoughts, I think we should have it to indicate that the session file doesn't exist.
It would be correct to indicate in cases where, say user had created the session earlier but somehow it was removed. He may want to be notified in that case. And it's also useful for us to debug later.

I am not sure why it's confusing. When you are creating the session for the first time, it doesn't exist and that's what the msg says. If you use option `-S` it will be created when you quit the program as documented.

**Comment by mizlan** [comment]
I see where you are coming from but I think there should be some method of disabling that, especially if the user is not directly controlling the session as in the case with nnn.vim. It would be odd for the user to see "failed!" or other messages when they expect it to be more discreet.

**Comment by Kabouik** [comment]
How about rephrasing the error so that it looks like a simple warning/feedback about the newly created session?

**Comment by mizlan** [comment]
Sure. My main concern is mostly the 1-second delay that occurs with the error message. So if that could be removed that would be much better already.

**Comment by jarun** [comment]
> My main concern is mostly the 1-second delay that occurs with the error message.

It's necessary information.

> How about rephrasing the error so that it looks like a simple warning/feedback about the newly created session?

I think it's just fine for a 1-time message. Let's not overthink. We can document if if we want. I do not want 3 people to spend time discussing it.

**Comment by mizlan** [comment]
I'll let you try it out after I'm done with the nnn.vim patch. I personally think its annoying, since a nice part of nnn is its fast startup time.

**Comment by jarun** [comment]
OK.

**Comment by jarun** [comment]
Closed at https://github.com/jarun/nnn/commit/54d760b9f533b26c36e915743fe521a05b72aa23.
