### ISSUE TITLE
Current version won't compile

### ISSUE THREAD

**Issue by leomayer** [jarun/nnn#1025]
- [x ] Operating System: OpenSuse
- [ ] Desktop Environment:
- [ ] Terminal Emulator:
- [ x ] Shell: fish 3.2.2
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [x ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

```
> git clone https://github.com/jarun/nnn.git   
> cd nnn
> sudo make O_NERD=1
cc -DNERD -std=c11 -Wall -Wextra -Wshadow -O3   -o nnn src/nnn.c -lreadline -lncurses
src/nnn.c:84:10: schwerwiegender Fehler: readline/history.h: Datei oder Verzeichnis nicht gefunden
   84 | #include <readline/history.h>
      |          ^~~~~~~~~~~~~~~~~~~~
Kompilierung beendet.
make: *** [Makefile:141: nnn] Fehler 1
```

Where to find `readline` dir?

**Comment by jarun** [comment]
You need to install the readline development files: https://github.com/jarun/nnn/wiki/Usage#dependencies

And if you can't, use the make option `O_NORL=1`: https://github.com/jarun/nnn/wiki/Developer-guides#make-options
