### ISSUE TITLE
icon not set 

### ISSUE THREAD

**Issue by mohammad5305** [jarun/nnn#1026]
hi i compile nnn with flag O_ICONS=1 but icon not set and nerdfont and awesomefont also installed I even change my terminal font and terminal  but same happend
termianl = st, konsole
font = nerd
distro = arch with i3wm
![image](https://user-images.githubusercontent.com/71145952/119682460-2578b800-be58-11eb-8839-04e6b5e8aed3.png)

**Comment by luukvbaal** [comment]
Looks like you're compiling with with `O_NOLC=1`, you can't do that if you wan't to use icons. See https://github.com/jarun/nnn/wiki/Developer-guides#compile-in-icons-in-terminal.

**Comment by luukvbaal** [comment]
Please confirm this was your issue. #1027 should prevent this situation from now on.

**Comment by luukvbaal** [comment]
Do icons work in your terminal outside of `nnn`? You say you're using a nerd font but are compiling with `O_ICONS=1`, you should compile with `O_NERD=1`. 

The only way I know your icons would look like that is if your compiling with both `O_NOLC=1` and `O_NERD/O_ICONS=1`. If that's not what's going on I'm afraid I don't know.

**Comment by jarun** [comment]
@mohammad5305 this appears to be a local issue. I'm afraid you'll have to debug it yourself or use `nnn` without icons (which is really not an issue because I see you have colors).

Also please ensure you have installed the icons in correctly e.g. following https://github.com/sebastiencs/icons-in-terminal#installation

I have `~/.fonts/icons-in-terminal.ttf`

and `~/.config/fontconfig/conf.d/30-icons.conf` has:

```
<?xml version='1.0'?>                                                                                             
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <alias>
  <family>No font found</family>
  <prefer>
   <family>icons-in-terminal</family>
  </prefer>
 </alias>
 <alias>
  <family>Monospace</family>
  <prefer>
   <family>icons-in-terminal</family>
  </prefer>
 </alias>
 <match target="font">
  <edit name="rgba" mode="assign">
   <const>rgb</const>
  </edit>
 </match>
 <dir>~/.fonts</dir>
</fontconfig>
```

I guess that's the best we can do for you.

**Comment by mohammad5305** [comment]
> Do icons work in your terminal outside of `nnn`? You say you're using a nerd font but are compiling with `O_ICONS=1`, you should compile with `O_NERD=1`.
> 
> The only way I know your icons would look like that is if you are compiling with both `O_NOLC=1` and `O_NERD/O_ICONS=1`. If that's not what's going on I'm afraid I don't know.

yeah icon show outside of nnn ,I try it too but not working
![image](https://user-images.githubusercontent.com/71145952/119819448-a346cd00-bf05-11eb-929b-5a807ad5d095.png)

**Comment by mohammad5305** [comment]
> @mohammad5305 this appears to be a local issue. I'm afraid you'll have to debug it yourself or use `nnn` without icons (which is really not an issue because I see you have colors).
> 
> Also please ensure you have installed the icons correctly e.g. following https://github.com/sebastiencs/icons-in-terminal#installation
> 
> I have `~/.fonts/icons-in-terminal.ttf`
> 
> and `~/.config/fontconfig/conf.d/30-icons.conf` has:
> 
> ```
> <?xml version='1.0'?>                                                                                             
> <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
> <fontconfig>
>  <alias>
>   <family>No font found</family>
>   <prefer>
>    <family>icons-in-terminal</family>
>   </prefer>
>  </alias>
>  <alias>
>   <family>Monospace</family>
>   <prefer>
>    <family>icons-in-terminal</family>
>   </prefer>
>  </alias>
>  <match target="font">
>   <edit name="rgba" mode="assign">
>    <const>rgb</const>
>   </edit>
>  </match>
>  <dir>~/.fonts</dir>
> </fontconfig>
> ```
> 
> I guess that's the best we can do for you.

i have to and added this my fontconfig but same happend 
![image](https://user-images.githubusercontent.com/71145952/119822137-8f509a80-bf08-11eb-83ff-f27749a01bb0.png)

**Comment by luukvbaal** [comment]
> yeah icon show outside of nnn ,I try it too but not working

Outisde of `nnn` but inside your terminal? 

Your images now show no icons at all; not the widechar -> char glyphs you were experiencing in your initial post. I.e. you must not be compiling in icons correctly or else there would be spacing in front of the file/dir names.

**Comment by mohammad5305** [comment]
> > yeah icon show outside of nnn ,I try it too but not working
> 
> Outisde of `nnn` but inside your terminal?
> 
> Your images now show no icons at all; not the widechar -> char glyphs you were experiencing in your initial post. Are you sure you're actually compiling in icons correctly. If nothing else there should at least be spacing in front of the file/dir names with icons compiled in.

inside of terminal I use nerdtree with icon in vim and show me the icon as well  and for showing widechar I accidentally compile with wrong flag I try with right flag too but not working 
![image](https://user-images.githubusercontent.com/71145952/119878014-ea9d7f80-bf3e-11eb-8ed3-8a79bb25b6a0.png)

**Comment by luukvbaal** [comment]
I don't see how this could happen except when compiling with both `O_NERD/O_ICONS` and `O_NOLC` (which is not possible anymore if you're on the latest commit).

Again, please make sure you're not including `O_NOLC` if you want icon support in `nnn`. If that's not what you're doing I'm also at a loss of why you would get those character instead of icons and I can't help you further.
