### ISSUE TITLE
can nnn do `cp file.txt new-filename.txt`?

### ISSUE THREAD

**Issue by ahillio** [jarun/nnn#1029]
I see that I can use `space` key to select a file, and then I can paste that file into a different directory by navigating there and doing `Ctrl p`.... but what if I want to copy the file to the same directory with a new name?  Is that possible?

Does nnn allow for `cp file.txt new-filename.txt`?

**Comment by jarun** [comment]
Relevant wiki section: https://github.com/jarun/nnn/wiki/Basic-use-cases#duplicate-file

Please read the wiki. It will take some time, but I can assure you, it's super-useful.
We spend a lot of time writing it and keeping it up-to-date. If users read it, the purpose will be met. :)

**Comment by KlzXS** [comment]
I think what you are asking is more along the lines of copy/move as. The keybind for that is `w`. After answering the prompt for cp/mv you will be greated by your `$EDITOR` to enter the new names.

**Comment by ahillio** [comment]
Thanks for the proper link!  I was reading https://github.com/jarun/nnn/wiki/Usage#keyboard-mouse and hadn't found the "basic usage" page.  Thanks for the `w` tip too!
