### ISSUE TITLE
[CRITICAL] RPM uninstall wipe root filesystem on openSUSE

### ISSUE THREAD

**Issue by Stig124** [jarun/nnn#1034]
Hello,

I installed nnn v4.0 using the github release RPM's for my opensuse tumbleweed machine [this one](https://github.com/jarun/nnn/releases/download/v4.0/nnn-4.0-1.opensuse.tumbleweed.x86_64.rpm), but I want to switch to auto updates using the opensuse repos, so I changed vendors and it tried to uninstalled the package.

BUT uinstalling it Icompletely **wipe** the root file system of the machine

I can find why,

```
- rpm -qi nnn-4.0-1.x86_64
Name        : nnn
Version     : 4.0
Release     : 1
Architecture: x86_64
Install Date: Fri 28 May 2021 01:53:46 CEST
Group       : other
Size        : 112871
License     : BSD 2-Clause
Signature   : (none)
Source RPM  : nnn-4.0-1.src.rpm
Build Date  : Tue 13 Apr 2021 13:19:31 CEST
Build Host  : 43528e776956
Packager    : Arun Prakash Jana <engineerarun@gmail.com>
URL         : https://github.com/jarun/nnn
Summary     : The unorthodox terminal file manager.
Description :

Distribution: (none)
```

```
- rpm -ql nnn-4.0-1.x86_64
/
/usr
/usr/bin
/usr/bin/nnn
/usr/share
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/nnn.1.gz
```

root shall **never** be a declared file in a spec file, same as `/usr/*`

I can fix the spec file if you want, but that is dangerous

**Comment by Stig124** [comment]
And this is not a isolated bug to my machine, just reproduced on official opensuse docker image

**Comment by jarun** [comment]
Can you check if this is coming from the Makefile? Doesn't look so to me.

In that case it is coming from packagecore which we use to package our resources.

@dlasalle can you please take a look at the earliest?

**Comment by jarun** [comment]
@Stig124 can you please audit the other packages for other OS-es? No need to install, just download an verify.

**Comment by Stig124** [comment]
Only openSUSE packages for some reasons are impacted

**Comment by Stig124** [comment]
> Can you check if this is coming from the Makefile? Doesn't look so to me.
> 
> In that case it is coming from packagecore which we use to package our resources.
> 
> @dlasalle can you please take a look at the earliest?

It is for sure not coming for the Makefile, no RPM spec is done there

**Comment by jarun** [comment]
TBH, I have concerns with [packagecore](https://github.com/BytePackager/packagecore) already. No one has looked into defects for months and there are no distro updates either.

@Stig124 can you think of any other way to generate these packages?

Also, I left some notes for you in the ToDo list regarding the arm and aarach64 packages. Have a look.

**Comment by Stig124** [comment]
> TBH, I have concerns with [packagecore](https://github.com/BytePackager/packagecore) already. No one has looked into defects for months and there are no distro updates either.
> 
> @Stig124 can you think of any other way to generate these packages?
> 
> Also, I left some notes for you in the ToDo list regarding the arm and aarach64 packages. Have a look.

Directing people to use openSUSE built packages would be the best thing, they're located [here](https://build.opensuse.org/package/show/utilities/nnn) and cover the whole openSUSE/SLE, and you can even build your own packages for a load of distributions there by just building a RPM specfile and a Debian control file

**Comment by jarun** [comment]
No, that's not the solution. Today we found this issue and I might have to drop generating the packages for SuSE. Our distro packaging is well maintained so no issue there. However, tomorrow we might find another issue on Ubuntu on packagecore. How will we mitigate that? Debian/Ubuntu are not the best players when it comes to software updates.

> There is no need actually, the openSUSE repo already build armv7 and arm64 (dynamically-linked) packages for openSUSE, it can be very easy to spin up a opensuse docker container, get the files, extract the executables and publish them

That would add a dependency on the OpenSuSE packaging timeline. I would prefer something independent and shipping with our release.

**Comment by Stig124** [comment]
In this case, I can maintain a OBS project that would build for every supported platform, each time a version ships

**Comment by Stig124** [comment]
The OBS can build for ![those distros](https://i.imgur.com/iM9pHzw.png)

**Comment by jarun** [comment]
That would be super-awesome!

**Comment by Stig124** [comment]
Ok, will do that

**Comment by jarun** [comment]
Can you add all available versions for the distros other than Arch, ScientificLinux and Uninvention?

**Comment by jarun** [comment]
I have also removed all auto-generated packages for SuSE till v3.0.

**Comment by Kabouik** [comment]
> The OBS can build for ![those distros](https://camo.githubusercontent.com/b7c3894cb65fc2e03208aca6daefefdae60e210e7bbf80c6bf79998aa3ecb42d/68747470733a2f2f692e696d6775722e636f6d2f694d3970487a772e706e67)

It could probably build for SailfishOS too with the same files I assume. I could try as I have an account on build.sailfishos.org which is also OBS, and have packaged nnn for this OS once (and then failed to keep it updated because I didn't automate things and nnn just evolves too fast for me to keep up).

**Comment by dlasalle** [comment]
@jarun It looks like this is the result of the updating the file list with rpmrebuild not behaving properly, I had never detected before as zypper would fail in removing `/` in the docker container, but return zero. I haven't had time to look at packagecore in a while, and I don't see that changing soon. Given the seriousness of this error, I think you should stop using it entirely (at the very least for all RPM builds). Sorry for this. I'm going to start pulling it from PyPI.

**Comment by jarun** [comment]
Thanks for the update @dlasalle! Yes, I have blocked building the RMPs for OpenSUSE.

**Comment by dlasalle** [comment]
@jarun  As redhat RPMs are built using the same script, I would also consider them all potentially unsafe, even though they don't appear to have this problem. I wasn't able to determine why this was happening with OpenSUSE RPMs, so it may be a matter of time for others. I've also yanked all releases on PyPI, and removed the files from the github repo to prevent anyone else from running into this issue.

As an aside, thank you using and supporting packagecore all of these years. It's sad for me to have to close it now, but given the risk of damaging user's systems with bad packages, I see no other choice. I'm truly sorry to have abandon you so abruptly like this.

@Stig124 Please accept my apologies for what happened when uninstalling the package.

**Comment by jarun** [comment]
@dlasalle can you give a rough estimate of the cost of maintaining packagecore? TBH, I've always thought it's a great piece of utility. I am considering funding it/looking for some maintainers it if possible.

**Comment by dilawar** [comment]
OBS beta now allows directly integration with gihtub/gitlab: https://openbuildservice.org/2021/05/31/scm-integration/

**Comment by jarun** [comment]
@Stig124 can you please check it out?

**Comment by jarun** [comment]
If you need me to set it up, please share the details in the nnn-devs room so I can use them to set it up.

**Comment by Stig124** [comment]
> @Stig124 can you please check it out?

I saw that, but this is not a great idea for now. This is a really early beta, 

> As you might notice, in this first beta, we are just triggering operations right after a new pull/merge request is created. What happens if a new commit is added to the pull/merge request or if someone force pushes some changes? We don’t handle this yet.

> Depending on the package you branch, it might build for more than one repository or architecture. Currently we will report the last build result that occurs.

I'll be more than happy to set it up when that will be a more matured integration

**Comment by Stig124** [comment]
> @jarun As redhat RPMs are built using the same script, I would also consider them all potentially unsafe, even though they don't appear to have this problem. I wasn't able to determine why this was happening with OpenSUSE RPMs, so it may be a matter of time for others. I've also yanked all releases on PyPI, and removed the files from the github repo to prevent anyone else from running into this issue.
> 
> As an aside, thank you using and supporting packagecore all of these years. It's sad for me to have to close it now, but given the risk of damaging user's systems with bad packages, I see no other choice. I'm truly sorry to have abandon you so abruptly like this.
> 
> @Stig124 Please accept my apologies for what happened when uninstalling the package.

This is not your fault
openSUSE pushing BTRFS (auto root FS snapshot at each package manager use) saved me everything, so all good

**Comment by Stig124** [comment]
I may have found the issue about packagecore @dlasalle,

In `rpm.py`line `190-191`
```python
specFile.write("%files\n")
specFile.write("/\n")
```

You can see a `/` before the `\n`, which is written to the spec file

**Comment by dilawar** [comment]
Doesn't packagecore uses rpmlint? On OBS, rpmlint warnings and errors are pretty exhaustive. Don't upload unless rpmlint clears the package.

**Comment by Stig124** [comment]
If what I found is the bug, it has been here since the birth of packagecore

**Comment by dlasalle** [comment]
@jarun While the actual maintenance work is pretty minimal, as this exemplifies much better testing is needed (including things like `rpmlint` as @dilawar says), in addition to re-writing the RPM generation scripts to be more robust. I think the work required to get it to a point where it could be used again, would similar to that of a rewrite, as there may be other serious issues or fragile code, and everything should be re-checked. For example for this file list code, I'm guessing I had assumed an incorrect file list cause the package to fail to install, due to conflicts. There may be other such bad assumptions within the code.

@Stig124 That '/' is supposed to get replaced in `__fixFiles()` function at https://github.com/BytePackager/packagecore/blob/29b5a5555c8b203a2f1812504d6a63cc1dc3bc23/packagecore/rpm.py#L59.
It's been few years since I looked at that code, and I think what happen is at the time I only support fedora, put this code in, saw it worked fine for fedora, and forgot about it. The way it is supposed to work is:
1. Generate a package whose list of files is `/` (since we don't know the contents of the package at this point).

2. Compare its of files and directories with that of the `filesystem` package, and remove all common directories (this should remove '/', '/usr/bin', etc.).

4. Use rpmrebuild to set the new list of files.

In hindsight, this was a very fragile and dangerous way of doing this. In suse, the comparison against the `filesystem` directories must fail, resulting in everything being listed including `/`.

**Comment by jarun** [comment]
@dlasalle as I understand your current commitments won't allow you to maintain this anymore. We are considering maintaining the project as it is a very useful independent way to package for Linux distros.

Just like you have explained your rationale behind this issue, we will need you guidance from time to time on the past considerations. In our discussions we found 2 areas where we need help immediately to have an idea of what we need to deal with:

- how to test the package when we add a new distro, or individual units in the code... for this particular issue, for example
- the procedure to add a new distro, obsolete older ones etc.

Would you be able to put us a documentation/Wiki to guide in those lines?

I was considering a call-out to the community to help maintain the project but now I believe the small `nnn` team is already capable enough to deal with this. I have some prior experience with this as well. If you look at advcpmv, it was abandoned at a point from where we brought it back to a well-maintained and updated code.

**Comment by dlasalle** [comment]
@jarun Sorry I keep disappearing on you, it's been tough to find time.

1.
Adding new distros could be done in the `packagecore/distributions.py` file. The format is:
```
"<distro name>": {
  "dockerImage": "<docker image on dockerhub>",
  "packageType": "<package manger",
  "formatString": "<format of package file name>"
}
```

So for example, to add `fedora34`:
```
"fedora33": {
  "dockerImage": "fedora:33",
  "packageType": "rpm-dnf",
  "formatString": "{name}-{version}-{release}.fc33.{arch}.rpm"
}
```

The real effort comes when a new package type needs to be created, or some special case needs to be handled. The packageType is used to create the "recipe" object:
https://github.com/BytePackager/packagecore/blob/29b5a5555c8b203a2f1812504d6a63cc1dc3bc23/packagecore/packager.py#L170

In these package types, "rpm.py", "dpkg.py" and "pkgbuild.py", is where all of the code really is. Essentially the just generate shell scripts from the user specified yaml file, and build packages inside of the docker containers for each repository.

2.
So far, I had been adding unit tests as `packagecore/*_test.py` and running them with pytest. See the travis-ci file: https://github.com/BytePackager/packagecore/blob/29b5a5555c8b203a2f1812504d6a63cc1dc3bc23/.travis.yml

I also think just as the phases for "prep", "build" "install" and "test" for each package are specified, there should also be an "uninstall" phase, that checks to make sure everything went well. You can see the "recipe" object being used here https://github.com/BytePackager/packagecore/blob/29b5a5555c8b203a2f1812504d6a63cc1dc3bc23/packagecore/packager.py#L102.

3.
To remove old distros, just delete their section from the `distributions.py` mentioned above.

If taking over the repo still sounds like something you would want to do, let me know, and I'll transfer the repository over to you.

Thanks,

Dominique

**Comment by jarun** [comment]
@dlasalle thanks a lot!

> If taking over the repo still sounds like something you would want to do, let me know, and I'll transfer the repository over to you.

I was discussing within the team and it seemed I'll need some time to get to it with my current commitments. However, I do have plans to resume it with a call-out to the community at some point. It would be great if you can transfer the repo. Thanks again!

**Comment by dilawar** [comment]
@dlasalle @jarun I did some work last weekend on it. I manage to add the `rpmlint` step after package is built. There are few fundamental issues that need solutions, for example: `%files` section in the spec file should be rewritten after the installation step. Currently it has `/`. I believe that was caused this issue. I am still learning the codebase and have been busy so I can't promise a timeline. But I am interested in reviving this project.

**Comment by jarun** [comment]
@dilawar That's great news! 👍
