### ISSUE TITLE
autosaving of named sessions

### ISSUE THREAD

**Issue by MarinPostma** [jarun/nnn#1039]
**Is your feature request related to a problem? Please describe.**

When using nnn.vim, I would like to have a nnn session per vim session. This allows me to work within multiple projects at the same time. It turns out that I have to manually save each session before I exit nnn.

**Describe the solution you'd like**

I would like nnn to be able to:
1. be launched from an unexisting session and create it on the fly (i.e `nnn -s mySession` create the mySession session if it doesn't exist
2. when I exit and launch the session again, I find the nnn in the state I left it before, without having to save the session each time I exit.

**Describe alternatives you've considered**

I considered using global session (default), but it does't mix well with working in multiple workspaces.

**Additional context**

na

**Consider contributing**

My C is a bit rusty, but with some guidance I could implement this feature.

Feel free to discuss in the ToDo list thread. We are more than happy to help.

**Comment by MarinPostma** [comment]
seems from https://github.com/mcchrish/nnn.vim/issues/43#issuecomment-844678831 that this is unwanted. Closing.

**Comment by luukvbaal** [comment]
I might have misunderstood you but I think this is the current behavior if you set `g:nnn#session = 'local'`. 

Just make sure you exit `nnn` cleanly and the session file should be created/updated when you exit `nnn` and deleted when you exit vim.

**Comment by MarinPostma** [comment]
yes, sorry I just found out that the version from the AUR i was using was not good (v4.0 ?!). I installed the git version and it now works.

**Comment by luukvbaal** [comment]
Yes, sorry. That feature will be part of v4.1, which is yet to be released.
