### ISSUE TITLE
Segmentation fault error when managing sessions

### ISSUE THREAD

**Issue by johnwuelk** [jarun/nnn#1041]
When saving or loading a session for example, nnn outputs "segmentation fault (core dumped)" and crashes/exits. This does not happen with older versions like f.i. nnn v3.7.

I tried to find the cause with strace, these are the last lines of strace before nnn exits:
48 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
349 +++ killed by SIGSEGV (core dumped) +++

I'm trying to use nnn as my main file manager due to its convenience with plugins and shortcuts.

**Comment by KlzXS** [comment]
Which version is this on? What are the exact sequences of keypresses to reproduce this issue?

The trace you shared seems to be from the signal handler calls. Not much can be gathered from that.

**Comment by jarun** [comment]
Can you please compile`nnn` with debugging enbaled (https://github.com/jarun/nnn/wiki/Developer-guides#debugging-nnn) and share the backtrace after hitting the crash from `gdb`?

**Comment by jarun** [comment]
More info: https://gist.github.com/jarun/ea47cc31f1b482d5586138472139d090

**Comment by jarun** [comment]
We did have changes in release 4.1 to support named persistent sessions.
Please share which program options you are using.
Also please check if the issue goes away if you remove the older saved sessions.

**Comment by jarun** [comment]
@johnwuelk in case you haven't noticed, we have made a release today. So if you are seeing this on the latest release, please act a bit faster and help us fix the issue so we can make a quick release before downstream packagers pick this up for packaging.

**Comment by johnwuelk** [comment]
Sorry for getting back late. The error still persists, here is what I did:
1. Remove nnn completely
2. git clone https://github.com/jarun/nnn.git
3. cd nnn
4. sudo make
5. ./nnn
6. hit 's' key key two times (sessions -> save session) 
7. type 'test' for session name
8. nnn exits with "Segmentation fault (core dumped)"
It failed on two different devices, Manjaro and Debian, same behavior.

**Comment by Stig124** [comment]
> Sorry for getting back late. The error still persists, here is what I did:
> 
>     1. Remove nnn completely
> 
>     2. git clone https://github.com/jarun/nnn.git
> 
>     3. cd nnn
> 
>     4. sudo make
> 
>     5. ./nnn
> 
>     6. hit 's' key key two times (sessions -> save session)
> 
>     7. type 'test' for session name
> 
>     8. nnn exits with "Segmentation fault (core dumped)"
>        It failed on two different devices, Manjaro and Debian, same behavior.

`sudo make`? This is not good, try without sudo

**Comment by johnwuelk** [comment]
Same behavior also without sudo (only make).

@jarun Here is the output of the nnndbg file:

ln __line__: VERSION=4.1
ln __line__: g_tmpfpath=/tmp
ln __line__: tmpfplen=5
ln __line__: home=/home/dojo
ln __line__: cfgpath=/home/dojo/.config
ln __line__: cfgpath=/home/dojo/.config/nnn
ln __line__: selpath=/home/dojo/.config/nnn/.selection
ln __line__: opener=xdg-open
ln __line__: getenv(envs[ENV_VISUAL])=vim
ln __line__: getenv(envs[ENV_EDITOR])=vim
ln __line__: editor=vim
ln __line__: pager=less
ln __line__: shell=/bin/bash
ln __line__: getenv("PWD")=/tmp/test/nnn
ln __line__: COLORS=256
ln __line__: COLOR_PAIRS=65536
ln __line__: __func__=dentfill
ln __line__: ts2.tv_nsec - ts1.tv_nsec=57895
ln __line__: __func__=redraw
ln __line__: path=/tmp/test/nnn
ln __line__: event->wd=0
ln __line__: event->mask=0
ln __line__: "inotify read done"=inotify read done
ln __line__: event->wd=0
ln __line__: event->mask=0
ln __line__: "inotify read done"=inotify read done

**Comment by johnwuelk** [comment]
> We did have changes in release 4.1 to support named persistent sessions.
> Please share which program options you are using.
> Also please check if the issue goes away if you remove the older saved sessions.

I use no program options, just "nnn". I also removed all saved sessions, compiled and ran it again which led to the same error.

**Comment by jarun** [comment]
I can repro it. Thanks!

**Comment by jarun** [comment]
Please confirm the patch works. Please explore the other session options also.

We'll make another release soon with some other fixes.

**Comment by johnwuelk** [comment]
It works now! Thanks for this quick patch. This even fixed a rendering issue I had with the fzcd plugin.
