### ISSUE TITLE
nnn -P not working 

### ISSUE THREAD

**Issue by ldelossa** [jarun/nnn#1045]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Fedora 34
- [x] Desktop Environment: Gnome 40
- [x] Terminal Emulator: Tilix
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: -P
- [ ] Configuration options set:
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I'm attempting to launch nnn directly into 'fzopen'. 

I noticed nnn has a "-P" flag which should accomplish his, however it does not for me. 

Am I correct in thinking that "nnn -P 'fzopen'" should open nnn directly into the FZF picker dialogue ?

**Comment by Stig124** [comment]
> #### Environment details (Put `x` in the checkbox along with the information)
> 
>     * [x]  Operating System: Fedora 34
> 
>     * [x]  Desktop Environment: Gnome 40
> 
>     * [x]  Terminal Emulator: Tilix
> 
>     * [x]  Shell: zsh
> 
>     * [ ]  Custom desktop opener (if applicable):
> 
>     * [x]  Program options used: -P
> 
>     * [ ]  Configuration options set:
> 
>     * [ ]  Issue exists on `nnn` master
> 
> 
> #### Exact steps to reproduce the issue
> 
> I'm attempting to launch nnn directly into 'fzopen'.
> 
> I noticed nnn has a "-P" flag which should accomplish his, however it does not for me.
> 
> Am I correct in thinking that "nnn -P 'fzopen'" should open nnn directly into the FZF picker dialogue ?

Hello, thanks for opening an issue, though we'll need a bit more insight at that. Can you please run the [debugging procedure](https://github.com/jarun/nnn/wiki/Developer-guides#debugging-nnn) and join the logfile after this please

**Comment by ldelossa** [comment]
Thanks @Stig124 

Since the output is so small, I'll paste the entire procedure:

```
~/git/c/nnn tags/v4.1
❯ make O_DEBUG=1
/usr/bin/clang -DDEBUG -g -std=c11 -Wall -Wextra -Wshadow -O3 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600   -o nnn src/nnn.c -lreadline -lncursesw -ltinfo  -lpthread

~/git/c/nnn tags/v4.1
❯ ./nnn -P 'fzopen'

~/git/c/nnn tags/v4.1
❯ cat /tmp/nnndbg 
ln __line__: VERSION=4.1
ln __line__: g_tmpfpath=/tmp
ln __line__: tmpfplen=5
ln __line__: home=/home/louis
ln __line__: cfgpath=/home/louis/.config
ln __line__: cfgpath=/home/louis/.config/nnn
ln __line__: selpath=/home/louis/.config/nnn/.selection
ln __line__: opener=xdg-open
ln __line__: getenv(envs[ENV_VISUAL])=(null)
ln __line__: getenv(envs[ENV_EDITOR])=vim
ln __line__: editor=vim
ln __line__: pager=less
ln __line__: shell=/bin/bash
ln __line__: getenv("PWD")=/home/louis/git/c/nnn
ln __line__: COLORS=256
ln __line__: COLOR_PAIRS=65536
ln __line__: __func__=dentfill
ln __line__: ts2.tv_nsec - ts1.tv_nsec=71726
ln __line__: __func__=redraw
ln __line__: path=/home/louis/git/c/nnn
ln __line__: event->wd=0
ln __line__: event->mask=0
ln __line__: "inotify read done"=inotify read done
```

As you can see, working off the 4.1 tag.

**Comment by Stig124** [comment]
Thanks

**Comment by luukvbaal** [comment]
The correct format is 

    nnn -P<plugin key>. 

I.e. the following will work:

    export NNN_PLUG="f:fzplug"
    nnn -Pf

**Comment by ldelossa** [comment]
Yup that worked, sorry I had assumed the key was the plugin name, not the configured shortcut key.
