### ISSUE TITLE
Find move destination with fzcd

### ISSUE THREAD

**Issue by binarious** [jarun/nnn#1057]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Linux Mint 20.1 Ulyssa
- [x] Desktop Environment: cinnamon-i3
- [x] Terminal Emulator: Alacritty
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: none
- [x] Configuration options set:
```
export NNN_PLUG='f:fzcd;m:nmount;x:_chmod +x $nnn;p:preview-tabbed'
export NNN_FIFO=/tmp/nnn.fifo
```
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
It's more a question than a bug, sorry. Discussions don't seem to be activated as an alternative.

I'm unable to select a downloaded file in `/tmp` and move that to a directory I want to search via `fzf` (via `fzcd`). 

~~`fzcd` doesn't provide directories unlike [ranger's command](https://github.com/ranger/ranger/wiki/Custom-Commands#fzf-integration) and~~ it also clears the current selection as described in the plugin file. Is there any way to achieve this workflow?

**Edit**: Found out that `fzf` can be configured via `FZF_DEFAULT_COMMAND` to use fd providing directories. Is there a way to preserve the nnn selection without modifying the plugin?

**Comment by jarun** [comment]
I think we can remove the selection file clearing logic. In the latest version we do not read from the selection file.

**Comment by jarun** [comment]
Fixed at d87414eb61c1349c9eb00ff5bdc9ae20fde1eddb. Please confirm.

BTW, it seems you already know which dirs to look for. In that case, you can generate a path-list file and use it.

**Comment by binarious** [comment]
@jarun Thanks for the quick response! I can confirm.

> you can generate a path-list file and use it

Can you elaborate on that?

**Comment by jarun** [comment]
`fzcd` is now more advanced to search multiple locations. It can read a list of paths from a path-list file and use them to search in `fzf`. And there are multiple ways to generate the path list file in `nnn`.

See https://github.com/jarun/nnn/blob/d87414eb61c1349c9eb00ff5bdc9ae20fde1eddb/plugins/fzcd#L3
