### ISSUE TITLE
Can't compile (fatal error: readline/history.h)

### ISSUE THREAD

**Issue by hrqmonteiro** [jarun/nnn#1059]
Trying to compile,  i get this:

 ```
cc  -std=c11 -Wall -Wextra -Wshadow -O3   -o nnn src/nnn.c -lreadline -lncurses -lpthread
src/nnn.c:86:10: fatal error: readline/history.h: No such file or directory
   86 | #include <readline/history.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:159: nnn] Erro 1
```

**Comment by Stig124** [comment]
You're missing dependencies here  
What distro are you running?

**Comment by hrqmonteiro** [comment]
I am on Void Linux, rolling release

Which dependencies could i be missing?

**Comment by luukvbaal** [comment]
I'm guessing you need https://github.com/void-linux/void-packages/blob/master/srcpkgs/readline-devel

**Comment by Stig124** [comment]
Readline dev headers in this case


You use Void Linux `glibc` or `musl`?

**Comment by Stig124** [comment]
> I'm guessing you need https://github.com/void-linux/void-packages/blob/master/srcpkgs/readline-devel

Yes exactly

**Comment by jarun** [comment]
Please follow the deps in the template: https://github.com/void-linux/void-packages/blob/master/srcpkgs/nnn/template

Closing.
