### ISSUE TITLE
Use standard libc functions

### ISSUE THREAD

**Issue by xbolva00** [jarun/nnn#106]
Hello,

As an improvement, why not to replace some of your own coded xfunctions with standard functions from libc?

**Comment by jarun** [comment]
I don't see an issue with the x_ functions. do you see any?

**Comment by jarun** [comment]
There are several benefits of having our own functions:

- we can link statically and avoid indirect jumps in dynamic linking. It also keeps the binary size less. Note: LTO is not widely non-portable.
- we know what we are doing. the dependencies are kept very few intentionally. `nnn` can be linked to any C library.
- `nnn` uses O3 optimization and can make use of the quad instructions. external lib binaries may or may not have this level of optimization enabled.
- there are cases we may never encounter (e.g., some NULL checks) and we omit such defensive code. We are not claiming we have standard APIs which can be used in any other project.

So yes, as long as you don't find any glaring issue with the implementation (which, if found, we will fix ;)), we would like to keep the current code as it is.

**Comment by xbolva00** [comment]
I believe that majority of strlen implementations are faster than yours :)

**Comment by jarun** [comment]
Very much possible. :)

**Comment by jarun** [comment]
Yes, sure!

**Comment by jarun** [comment]
In fact, apple's x86 implementation is really cool:

https://gist.github.com/dchest/77178

**Comment by xbolva00** [comment]
Yes :D 

Musl one is cool magic too
http://git.musl-libc.org/cgit/musl/tree/src/string/strlen.c

**Comment by jarun** [comment]
While we are at it, how about xstrcmp()?

The others look fine to me given the implementation/usecase.

**Comment by xbolva00** [comment]
Yes, xstrcmp -> strcmp would be part of patch too.

**Comment by jarun** [comment]
Nice! So I will wait for the patch replacing xstrlen() and xstrcmp().

**Comment by jarun** [comment]
Just for the record, please note the pre and post strip size of the binary in the PR. I see a 32 byte increase.

**Comment by xbolva00** [comment]
Thanks.

Yesterday I was playing with codebase and I replaced xstrlcpy with:

xstrlcpy(char *dest, const char *src, size_t n)
{
	if (!n)
		return 0;

	strncpy(dest, src, n);
	dest[n-1] = '\0';
	return strlen(dest) + 1;
}


I didnot any measures what it is better,  nnn worked fine with this replacement. :) 


p.s: you can strip debug symbols in release build if size increase is a problem :)

**Comment by xbolva00** [comment]
You can get a bit better performance using likely/unlikely hints.

**Comment by jarun** [comment]
Branch prediction falls under micro-optimization and likely/unlikely are GCC specific - https://stackoverflow.com/a/109732/3161329.

**Comment by jarun** [comment]
If you are interested, can you try replacing nftw() with fts() and see if there's any performance improvement? `du` mode is something I would very much like to boost the performance of.

**Comment by jarun** [comment]
OK, leave it. There are issues - http://selinux.tycho.nsa.narkive.com/itYCfuBB/bug-libselinux-use-nftw-instead-of-fts

Maybe the reason I used nftw in the first place.

**Comment by xbolva00** [comment]
"Branch prediction falls under micro-optimization and likely/unlikely are GCC specific."

Works on Clang too. We can ifdef it in a macro. I dont consider this as a small, micro optimization, sometimes it can help a lot. It is cheap to do anyway, I can send a initial patch if you want.

**Comment by xbolva00** [comment]
As I am lookit at your code, we would not get some benefits here.

But linux kernel uses as a lot. Branch predictor misses are expensive, but if we know what we are doing, we know our code, branches are faster than branchless conditions using cmov.

http://250bpm.com/blog:6
https://kernelnewbies.org/FAQ/LikelyUnlikely
and many other articles..
