### ISSUE TITLE
Plugins do not install

### ISSUE THREAD

**Issue by stubkan** [jarun/nnn#1060]
Plugins do not install.

- [x] Operating System: Ubuntu 
- [X] Desktop Environment: Cinnamon 20.04
- [x] Terminal Emulator: Guake or Terminal
- [ ] Shell: 
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Followed install instructions on the plugin wiki, which has this result;

![image](https://user-images.githubusercontent.com/34361592/121069322-4086e880-c7c5-11eb-869f-dc9199a1f688.png)

It creates in the present folder, a nnn-.tar.gz file which is empty with 9 bytes, and each attempt also creates a new plugins-??????????.tar.gz file which are 115 bytes big and also empty.  (????????? = a number sequence)

I have tried to see if I satisfy dependencies, by double checking they are all installed.  They appear to be.  nnn itself runs without issue, but I would very much like plugins to be available.  I don't know how to investigate what is going wrong.

There are no files present in the .config/nnn or .config/nnn/plugin folders

**Comment by 0xACE** [comment]
[![wisdom_of_the_ancients](https://user-images.githubusercontent.com/1482942/121094207-cadb4680-c7dd-11eb-9d38-b7184f449836.png)](https://xkcd.com/979/)
