### ISSUE TITLE
[tmux] preview not working

### ISSUE THREAD

**Issue by ThomasBucaioni** [jarun/nnn#1062]
Within Tmux, a panel opens when triggering the preview but it only shows binary info on the file. Any idea how to have the picture, or if it's possible?

**Comment by luukvbaal** [comment]
Have you looket at the dependencies?

**Comment by ThomasBucaioni** [comment]
Nope... The terminal is Kitty, where should I look at?

**Comment by luukvbaal** [comment]
You shouldn't use `tmux` in `kitty`. Image previews in `kitty` don't need any dependencies.

**Comment by luukvbaal** [comment]
The dependencies are listed as comments in `preview-tui`.

**Comment by ThomasBucaioni** [comment]
It was to answer a question on Reddit, if you would like to add further comments there: https://www.reddit.com/r/KittyTerminal/comments/l2je2r/guide_nnn_preview_plugin/
