### ISSUE TITLE
Preview-tui not showing directories and files correctly

### ISSUE THREAD

**Issue by etrigan63** [jarun/nnn#1069]
#### Environment details (Put `x` in the checkbox along with the information)

- [X ] Operating System: ArcoLinux
- [ X Desktop Environment: bspwm
- [X ] Terminal Emulator: kitty
- [X ] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ X] Configuration options set: 
export NNN_PLUG='[:preview-tui;'
export NNN_OPTS="eaEox"

- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Open preview-tui using Alt-[ or ;[ while hovering over a file or directory
Files look like this:
![image](https://user-images.githubusercontent.com/7347264/121765314-ec0ea080-cb17-11eb-8479-3c65d4b71475.png)
Directories look like this:
![image](https://user-images.githubusercontent.com/7347264/121765324-0779ab80-cb18-11eb-8c2a-d9e526dac566.png)
Font is Fira Code Nerd Font.
Images work correctly:
![image](https://user-images.githubusercontent.com/7347264/121765346-3abc3a80-cb18-11eb-83a8-0dac1c0b95d4.png)

**Comment by jarun** [comment]
PAGER is not interpreting ASCII color codes. Here's what I have:

```
$ echo $PAGER
less -Ri
```

Look up the options in the man page.

**Comment by larrybotha** [comment]
For anyone else experiencing this, and to add some keywords for issue search (`ESC`, `ESC[`), my `$PAGER` was just set to `less`.

I'm not sure exactly where the `$PAGER` variable is set, but setting it to `less -R`, as @jarun mentioned resolves the rendering due to escape ANSI color escape sequences:

```
#!/usr/bin/env sh

# custom nnn configs, e.g. in ~/.config/nnn/my-custom-config.sh

# fix preview-tui not rendering correctly
export PAGER="less -R"

# other NNN env vars
```
