### ISSUE TITLE
Extract archives to a subdirectory or PWD depending on whether the archive contains multiple top-level entries

### ISSUE THREAD

**Issue by ouuan** [jarun/nnn#1076]
**Is your feature request related to a problem? Please describe.**

When I extract an archive, I usually expect its contents to be extracted to a single directory, so I sometimes need to extract it into a subdirectory instead of in the PWD. But this is only needed when the archive contains more than one top-level entry. If there's only a single top-level entry in the archive, it's fine to extract it to PWD.

e256353fbfc4e7718ce7c85bbb218f16d60f9de1 enables "extract to", but it always prompts for a path. If I want to use the mechanism described above, I need to ls it first to manually see whether it contains a single top-level entry or multiple.

**Describe the solution you'd like**

If an archive contains a single top-level entry, don't prompt for a path but extract it to PWD instead; otherwise, use the behavior of e256353fbfc4e7718ce7c85bbb218f16d60f9de1.

In addition to this, I'd also like to have the name of the archive (possibly with the archive extensions removed) as the default path for "extract to", since it's less likely that one wants to extract an archive to PWD with the multiple-top-level-entries detecting mechanism.

**Describe alternatives you've considered**

Manually check or always extract to a new directory.

**Consider contributing**

Please consider contributing the feature back to `nnn`.

Feel free to discuss in the ToDo list thread. We are more than happy to help.

**Comment by jarun** [comment]
> If I want to use the mechanism described above, I need to ls it first to manually see whether it contains a single top-level entry or multiple.

Yes, that's the way it is. I don't think there's any tool that provides the depth directly. So user has to list and take a call.

>  I'd also like to have the name of the archive (possibly with the archive extensions removed) as the default path for "extract to"

Now the filename will be shown in the prompt and the user can edit it.

**Comment by ouuan** [comment]
I just realized that removing the extension in the default path is not optional, because it conflicts with the archive itself.

**Comment by ouuan** [comment]
> Yes, that's the way it is. I don't think there's any tool that provides the depth directly. So user has to list and take a call.

The GUI file manager Dolphin can do this well, though I'm not sure how it works.

It's OK if you don't want to support this feature right now, but I don't think this issue should be closed without the request being resolved.

**Comment by jarun** [comment]
> I don't think this issue should be closed without the request being resolved.

I don't see a point in having micro-features which don't add any significant value.

On a different note, when you raise a defect on a project requesting a feature, you'll have to leave that at the project maintainer's discretion irrespective of your personal opinion. In this case I have a clear picture how many people contribute to `nnn` regularly and how many line items which I left open were actually addressed by someone else.

I am open to this - if you ever find a way without the overhead of _unpacking the archive first_, raise a PR. That's another reason I don't want to do this.

In general, I don't download random archives from the internet and when I download one, I have an idea whether it will have a single file at the top level or more. When in doubt, I wanted to extract it to a new dir without listing it, hence I added this feature.

> The GUI file manager Dolphin can do this well, though I'm not sure how it works.

`nnn` never claimed it will support everything that every other file manager does. :)

**Comment by ouuan** [comment]
> On a different note, when you raise a defect on a project requesting a feature, you'll have to leave that at the project maintainer's discretion irrespective of your personal opinion. In this case I have a clear picture how many people contribute to `nnn` regularly and how many line items which I left open were actually addressed by someone.

Sorry, I didn't make myself clear. In fact, I'm OK with this issue being closed. What really made me confused was the "Fix #1076" in the commit message. I took it for granted that the request was accepted when I saw the "Fix #1076", and was disappointed when I discovered that this request was actually rejected rather than fixed.

**Comment by jarun** [comment]
Hence the commit message: `Fix #1076: show file name in archive extract prompt`

**Comment by ouuan** [comment]
Not related to the request, just an alternative solution in case someone finds this thread in the future and want a solution:

`ark -ab` can extract files and automatically create the subdirectory on-demand as described above. So I end up writing a tiny plugin `ark -ab "$1"` which does the job. This also solves the problem that `nnn` only supports `atool`, `bsdtar`, `zip` and `tar`.

Ark is a GUI app, though. With the `-b` option it usually behaves like a CLI app, but in situations like file conflicts, it will launch a GUI prompt. I'm not sure if there are CLI apps that also do the job.

**Comment by jarun** [comment]
> This also solves the problem that nnn only supports atool, bsdtar, zip and tar.
> Ark is a GUI app, though. With the -b option it usually behaves like a CLI app, but in situations like file conflicts, it will launch a GUI prompt. I'm not sure if there are CLI apps that also do the job.

Is `ark` available outside KDE?

**Comment by ouuan** [comment]
> Is `ark` available outside KDE?

You need to install a bunch of dependencies if you don't use other KDE apps, but Plasma is not required.

**Comment by jarun** [comment]
I think `atool` provides the behaviour you are looking for by default: https://linux.die.net/man/1/atool

I saw the need because i use `bsdtar`.

**Comment by ouuan** [comment]
> I think `atool` provides the behaviour you are looking for by default: [linux.die.net/man/1/atool](https://linux.die.net/man/1/atool)
> 
> I saw the need because i use `bsdtar`.

Oh, I just discovered that I didn't have atool installed.

**Comment by ouuan** [comment]
It seems that installing `atool` is the actual best solution :sweat_smile:

**Comment by jarun** [comment]
Yes, and I have to do this specifically for the other tools.

**Comment by ouuan** [comment]
> I just realized that removing the extension in the default path is not optional, because it conflicts with the archive itself.

This is not solved yet. The extension should be removed in the default path, or alternatively 9bd16ed837f31775f6dc1e5e9595e079cbb72608 should be reverted. It's annoying to have an invalid value as the default.

**Comment by jarun** [comment]
> The extension in the default path should be removed
> It's annoying to have an invalid value as the default.

Explain the first point. What's invalid?

**Comment by jarun** [comment]
Also, if we skip the workflow for atool, we can't create the smart context for atool. How does `nnn` kow atool has created a new dir or extracted in the same dir?

**Comment by ouuan** [comment]
> Explain the first point. What's invalid?

"because it conflicts with the archive itself"

**Comment by ouuan** [comment]
> Also, if we skip the workflow for atool, we can't create the smart context for atool. How does `nnn` kow atool has created a new dir or extracted in the same dir?

I've no idea of a perfect solution, but I personally think it's just fine to stay in the current context.

**Comment by jarun** [comment]
> "because it conflicts with the archive itself"

That doesn't make it invalid. It tells the user he can press backspaces and have the desired directory name.

> I've no idea of a perfect solution, but I personally think it's just fine to stay in the current context.

What we have is fine. We need a small change - I will make the change to provide the default as `.` when `atool` is detected and can just press `Enter` and move on. Note a new context is not opened when the files are extracted in the current dir so you get exactly the behaviour you were looking for with `atool`.

**Comment by ouuan** [comment]
> That doesn't make it invalid. It tells the user he can press backspaces and have the desired directory name.

Then what's invalid :thinking: Any default value could be deleted by the user.

Can't we remove the extension automatically?

**Comment by jarun** [comment]
I have already mentioned in this thread why it's ambiguous and not possible without having a dictionary. I don't want that overhead.

**Comment by ouuan** [comment]
> I have already mentioned in this thread why it's ambiguous and not possible without having a dictionary.

Sorry, but I don't know what you are referring to. Could you kindly point out where did you mention this?

**Comment by jarun** [comment]
> I have already mentioned in this thread why it's ambiguous and not possible without having a dictionary.

I think I missed posting it. Archive names like source code can have `.` in them. And archive extensions are poorly designed in that the extension can have multiple tokens. So without having a reference dictionary of all possible extensions (hence increasing memory consumption) it's not possible to get the filename.

> Then what's invalid thinking Any default value could be deleted by the user.

Showing a path "sdgshg" for an archive named "archive.tgz" is invalid. We are showing the archive name, the user can easily press some backspaces and get the path from it. It's not that a user extracts an archive every minute while he is using `nnn`. So let's be practical. And `nnn`  is not really a utility that spoonfeeds users.
