### ISSUE TITLE
Applying the git patches fails with

### ISSUE THREAD

**Issue by CantoroMC** [jarun/nnn#1077]
src/nnn.c: In function ‘dentfill’:
src/nnn.c:5464:61: error: ‘DIR_OR_LINK_TO_DIR’ undeclared (first use in this function)
 5464 |                                         if ((dentp->flags & DIR_OR_LINK_TO_DIR) ?(is_prefix(git_statuses.statuses[i].path, dentpath, namebuflen) &&
      |                                                             ^~~~~~~~~~~~~~~~~~
src/nnn.c:5464:61: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:159: nnn] Error 1

**Comment by jarun** [comment]
Thanks for the note. We'll fix it. At the same time we don't support patching master. So next time you see this please leave a comment in the ToDo list.

**Comment by CantoroMC** [comment]
Sorry to bother, what does it mean that you don't support patching master?

**Comment by jarun** [comment]
Quoting from the patch documentation: _The patches will be adapted on each release when necessary (v4.1 onwards)._

So intermediate changes may break them.

**Comment by CantoroMC** [comment]
Ok, thanks for the response.
