### ISSUE TITLE
fzf open only fuzzy searches file names

### ISSUE THREAD

**Issue by ldelossa** [jarun/nnn#1079]
Currently when using fzfopen plugin the fuzzy searching only works on the base filename. Fuzzy searching against any strings in the path does not work. 

for example with the path "/mycode/package1/file1.ext" searching for "package1" produces no results. 

This is not how fzf works on the CLI when ran indepedently. 

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Fedora
- [x] Desktop Environment: Gnome
- [x] Terminal Emulator: tilix
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable):
- [x] Program options used: nnn -Po (o is my fzfopen key)
- [x] Configuration options set:
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Use fzfopen plugin with nnn and search for a file by typing in that file's containing directory.

**Comment by jarun** [comment]
Plugins are indicative. We can't address every user's preferences. So, please modify with preferred fzf options and use.

**Comment by ldelossa** [comment]
Just a heads up, latest MASTER pull of plugins actually fixes this issue. 
https://github.com/jarun/nnn/commit/8fc18fb9d66316710b8d9c960b12a4c521d1684e

any suggested way of keeping our plugin dirs update to date with changes ?

**Comment by luukvbaal** [comment]
[`getplugs`](https://github.com/jarun/nnn/blob/master/plugins/getplugs)`master` can be used to update/merge plugins from the master branch.

**Comment by jarun** [comment]
Note that plugins in master are not guaranteed to be in a working condition due to intermediate changes, plugin spec changes etc. I think there's no issue with this one, but please don't make it a habit to sync from master.
