### ISSUE TITLE
fzopen preview file

### ISSUE THREAD

**Issue by ldelossa** [jarun/nnn#1080]
**Is your feature request related to a problem? Please describe.**

Not a problem.

**Describe the solution you'd like**

The fzopen script can include a --preview flag to provide a file preview natively. 

**Describe alternatives you've considered**

Just a nice to have.

**Additional context**

screenshot attached

**Consider contributing**

I am down to contribute this solution, I'm just openning this ticket to gauge whether this is something NNN users would like or not. I'm totally cool with just leaving it on my host system as well.

Feel free to discuss in the ToDo list thread. We are more than happy to help

![nnn](https://user-images.githubusercontent.com/5642902/122775476-2bf02900-d278-11eb-8c98-8f70400ba0d2.png)

**Comment by jarun** [comment]
Plugins are indicative because all user preferences cannot be addressed.

Please modify them as you prefer and use. Also, please do not open a defect for every plugin option you want added or removed, use the ToDo list.
