### ISSUE TITLE
nnn-musl-static locale (sort) support?

### ISSUE THREAD

**Issue by beaglesnuf** [jarun/nnn#1081]
First off, kudos to nnn + musl + netbsd-curses support. I only needed to add terminfo information to netbsd-curses and everything came together. Only issue is that sort order no longer takes into account locale. It is as if NOLC=1 had been passed as build option. Is this a limitation imposed by netbsd-curses or musl or nnn? Sorting is as expected with the standard, dynamically linked build. 

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Debian sid
- [x] Desktop Environment: sway
- [x] Terminal Emulator: alacritty
- [x] Shell: mksh/bash
- [x] Custom desktop opener (if applicable): nuke
- [x] Program options used: default per existing script
- [x] Configuration options set: default per existing script
- [x] Issue exists on `nnn` master: yes (d1df934)

#### Exact steps to reproduce the issue

Build `nnn-musl-static` as described in musl-static-ubuntu.sh

**Comment by jarun** [comment]
> I only needed to add terminfo information to netbsd-curses and everything came together.

Unrelated - can you please explain what you meant by that? Please share the steps.

musl has open issues with locale support: https://wiki.musl-libc.org/open-issues.html

Also see:

- https://github.com/rilian-la-te/musl-locales
- https://grrr.tech/posts/2020/add-locales-to-alpine-linux-docker-image/

**Comment by beaglesnuf** [comment]
Added a small snippet in the script:

```
 # Get netbsd-curses
 [ ! -d "./netbsd-curses" ] && git clone https://github.com/sabotage-linux/netbsd-curses
@@ -36,6 +36,12 @@
 # Get the last known working version
 git checkout v0.3.2
 
+# Add terminfo to netbsd-curses
+if [ ! -d "../musl-fts" ]; then 
+    infocmp $TERM >> terminfo/terminfo
+    patch -Np1 -i ../../nnn-netbsd-genterms.patch
+fi
+
```
Where the terminfo definitions of  the current TERM are added to the terminfo definitions file before the patch adjusts which TERMs will be compiled in:

``--- a/libterminfo/genterms
+++ b/libterminfo/genterms
@@ -41,18 +41,7 @@
 xterm
 linux
 xterm-256color
-ansi
-dumb
-vt100
-screen
-screen-256color
-tmux-256color
-rxvt-unicode
-rxvt-unicode-256color
-st-256color
-dvtm
-dvtm-256color
-fbpad-256
+alacritty
 "
 
 ${TOOL_TIC} -Sx ${TERMINFO} ${TERMLIST}
``
Limiting TERMs to only those I actually use saved ~20K.

**Comment by jarun** [comment]
Many thanks for the tip!
