### ISSUE TITLE
broken line prefix in detail mode

### ISSUE THREAD

**Issue by 4nd3r** [jarun/nnn#1085]
first bad commit: 0691c4fb47fa35fcd72a97da31e93cc9d7799c3d 

building without `O_ICONS` or `O_NERD`.

good:

![image](https://user-images.githubusercontent.com/7166727/123601445-5c980b80-d800-11eb-8b04-8ab73d1ce28a.png)

bad:

![image](https://user-images.githubusercontent.com/7166727/123601549-78031680-d800-11eb-9d99-acc574d1102d.png)

**Comment by luukvbaal** [comment]
Not broken. This was intentionally changed to a reverse block for visibility reasons.
I'm not a big fan either but you'll have to live with it or change it back and compile yourself.
