### ISSUE TITLE
Cant show free/used disk usage

### ISSUE THREAD

**Issue by stubkan** [jarun/nnn#1096]
#### Environment details (Put `x` in the checkbox along with the information)

- [ ] Operating System: 
- [ ] Desktop Environment:
- [ ] Terminal Emulator:
- [ ] Shell:
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I am trying to find out how to display free disk space and disk space, etc while using nnn ...

I apologize if this is already outlined in documentation but after searching for some time, I cannot find it.  I looked on google results, issue reports and wiki documentation.  I only found this one mention below ;

![image](https://user-images.githubusercontent.com/34361592/124531672-e9495780-de06-11eb-93ea-24c8bc8d7909.png)

The help screen does not appear to have this functionality in it, so I don't know where it is.

Ideally I would like it to be part of the panel screen, part of the the bottom info lines.

**Comment by jarun** [comment]
Can you share a screenshot of your help screen?

**Comment by stubkan** [comment]
I looked again and discovered I could scroll the help screen and found the disk usage down there.  Sorry.

So it is in there after all.  It's a little complicated to go find it though, it'd be nice if there was a feature for having it displayed on the main panel.

**Comment by jarun** [comment]
Try: <kbd>^T-d</kbd> to enter disk usage mode.
