### ISSUE TITLE
nuke: expansion of $VISUAL variable

### ISSUE THREAD

**Issue by basbebe** [jarun/nnn#1097]
I'm having a problem with nuke and I can't figure out why (probably because I'm not an expert with bourne shell and it's string expansions (?).

My `$VISUAL` variable consists of two words:
```sh
VISUAL=kcr edit
```

nuke uses it as follows:
```sh

[…]

EDITOR="${VISUAL:-${EDITOR:-vi}}"

[…]

        text/* | */xml)
            "$EDITOR" "${FPATH}"
            exit 0;;

[…]

```

No I'm getting errors like whit when I want to edit a text file:

```console
/Users/bastian/.config/nnn/plugins/nuke: line 448: kcr edit: command not found
```

using `kak` as a visual editor works.
using <kbd>e</kbd> works with `kcr edit` set as `$EDITOR`.

`$PATH` is not an issue here.
I already tried around with various combinations of quotes and curly braces but I wasn't succesful.

(Im using [`kak`](https://github.com/mawww/kakoune) as an editor, `kcr edit` comes from [kakoune.cr](https://github.com/alexherbo2/kakoune.cr))

**Comment by 0xACE** [comment]
> My `$VISUAL` variable consists of two words:

![cap](https://user-images.githubusercontent.com/1482942/124581699-d784a600-de40-11eb-86c4-05ff83e180f1.png)

------

(assuming `~/bin` is in your `$PATH`)
```
cat <<EOF > "$HOME/bin/kcr-edit"
#!/usr/bin/env sh
kcr edit "$@"
EOF
chmod +x ~/bin/kcr-edit
export VISIUAL=kcr-edit
```
![cap](https://user-images.githubusercontent.com/1482942/124582138-44983b80-de41-11eb-8579-322b9d132372.png)

**Comment by basbebe** [comment]
> > My `$VISUAL` variable consists of two words:
> 
> 
> 
> ![cap](https://user-images.githubusercontent.com/1482942/124581699-d784a600-de40-11eb-86c4-05ff83e180f1.png)
> 

I know, I know

It's a pragmatic workaround but I thought there was something about nuke's code which I could look at since I don't have any problems with it anywhere else (including nnn).

**Comment by jarun** [comment]
@luukvbaal any quick way to handle this case in `nuke`?

**Comment by luukvbaal** [comment]
Best way to handle it is like @0xACE suggested or just directly replace `EDITOR` with `kcr edit` in `nuke`.

**Comment by jarun** [comment]
Closing as we have shared some solutions for this. Plugins are indicative so it's expected users would have to adapt them.
