### ISSUE TITLE
Clear statusbar selection.

### ISSUE THREAD

**Issue by CantoroMC** [jarun/nnn#1098]
I hope to be able to explain myself.
If you select some items, the statusbar will inform you that you have some selected items and the number of items selected(that's good), but then if you deselect all of the items the statusbar will still show the "selection mode" symbols.
I don't know if it is a bug or the intended behaviour, if so sorry to waste your time.

**Comment by jarun** [comment]
Currently we do not clear the selection mode even when number of selected files becomes 0. This saves some extra processing. Do you see any issues with that?

**Comment by jarun** [comment]
I have made the change to clear the status when the last selected file is also deselected.

@KlzXS this overlaps with your PR. Please have a look.

**Comment by CantoroMC** [comment]
@jarun I hadn't any issue with that but it seems counter-intuitive to me.

**Comment by jarun** [comment]
Understood. It was a leftover from the legacy mechanism of selection.

Please confirm it works as expected.

**Comment by CantoroMC** [comment]
Just tried, it works as expected.
Thanks again and good evening.
