### ISSUE TITLE
Tree view

### ISSUE THREAD

**Issue by nezartarbin** [jarun/nnn#1099]
I love nnn, but I am wondering if it is possible to have a directory tree type of view? Basically, if a directory contains sub-directories, I would be able to expand a sub-directory and see its contents and children, but I would still be in the parent directory's "view" and see its other children. A nested tree view. I included a photo below as an example. If this is out of scope for nnn, I'll understand, but if it is already a feature it would be great! Thanks :)

![image](https://user-images.githubusercontent.com/41840738/125009107-e41c2080-e031-11eb-81db-b35c5092ea23.png)

**Comment by jarun** [comment]
First, please do not litter projects with essay-like issue subject lines.

Secondly, no there is no tree view planned. A persistent view is in progress here: https://github.com/mcchrish/nnn.vim/pull/103. Feel free to contribute.
