### ISSUE TITLE
Could you add Chinese support?

### ISSUE THREAD

**Issue by wugq** [jarun/nnn#11]
Hi Jarun,

I found this project thru [reddit](https://www.reddit.com/r/linux/comments/6566o6/nnn_free_fast_friendly_file_browser/) , and I like the user interface and short cuts.

But the Chinese file name does not display correctly. After googling, I made some changes to the files and it works. However my solution is to replace curses with ncursesw in Makefile which may bring the change to the overall design.

The changes I made to support Chinese in my computer were:

-  Makefile
```
-LDLIBS = -lcurses
+LDLIBS = -lncursesw
```
- nnn.c
move below line 'setlocale(LC_ALL, "") '  before 'initscr()'

Thank you for this great project!
wugq

**Comment by jarun** [comment]
> move below line 'setlocale(LC_ALL, "") ' before 'initscr()'

For me (I have en_US.UTF-8), commit https://github.com/jarun/nnn/commit/eb053063c21e914057b8f7584e791f62bd3dc0eb worked.

Anyway, I'm trying to roll a patch for you to test. I need to do some tests myself. Around half an hour please...

**Comment by wugq** [comment]
I'm running Debian Stable, my local is en_US.UTF-8
```
wugq@x220:~/test$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
wugq@x220:~/test$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie

```

The some Chinese fonts can be displayed, but the support is not fully.


![2017-04-16-133450_935x279_scrot](https://cloud.githubusercontent.com/assets/491405/25069097/064e15e0-22aa-11e7-9729-284799558167.png)
![2017-04-16-133737_811x161_scrot](https://cloud.githubusercontent.com/assets/491405/25069096/05b081e0-22aa-11e7-986c-5db88897fa72.png)


Thank you!

**Comment by jarun** [comment]
Please test with https://github.com/jarun/nnn/commit/1e574af2de49939d00bbae6171954a3da2a77dd6

Issue:

- libncursesw is missing on OS X: https://travis-ci.org/jarun/nnn/jobs/222494996
@zmwangx do we need additional instructions to install libncursesw on OS X?

**Comment by wugq** [comment]
The display of Chinese is correct!

Thank you!

![2017-04-16-134622_411x199_scrot](https://cloud.githubusercontent.com/assets/491405/25069141/29770abc-22ab-11e7-941e-abd6fe1c84ec.png)

**Comment by jarun** [comment]
But we have other problems... :)

**Comment by zmwangx** [comment]
macOS system libcurses from ncurses 5.4 supports wide characters perfectly here.
Meanwhile, I am able to reproduce the issue on Debian Jessie with 2d7b575c8257fbc25f9959701ebebeb26f100036.

It is possible to use ncurses 6.0 from Homebrew instead, which does come with libncursesw, but I don't see the need, and it raises the bar of compilation on macOS significantly. While I understand your reluctance, I'd say a uname test in the Makefile is the best compromise here.

**Comment by jarun** [comment]
Yes, some googling gives me a similar idea... Can you please raise a PR tested on OS X? I will check it out on Ubuntu and merge it.

**Comment by jarun** [comment]
Fixed at https://github.com/jarun/nnn/commit/0cc59f742c67f70ad339b93f7332839211cd07f3. Thanks @wugq for sharing your findings and making the process quicker!

**Comment by jarun** [comment]
@zmwangx can you please re-test this? It's been sometime and I've made lots of changes here and there. Just to confirm... whenever you get the time.

**Comment by zmwangx** [comment]
@jarun Just tested master and I don't see any problem.

**Comment by jarun** [comment]
:+1:
