### ISSUE TITLE
Navigation by Pasting path

### ISSUE THREAD

**Issue by Hukuta** [jarun/nnn#1100]
Is there any way to navigate by simple pasting path into the terminal in already opened nnn instance?
I have multiple tabs opened and i want to navigate in one of them to a long path, copied from other app. 

I have tried this way, but it works not like i expected:
  ```]```
  ```cd my_path```
```Enter```

**Comment by jarun** [comment]
There's a hacky way, please visit the wiki. However, we don't want users to type and cd so their is no support in the program for this. You may want to check mc which jas this.

**Comment by toddyamakawa** [comment]
I use a plugin for that:
https://github.com/toddyamakawa/bin/blob/7a8075797cab058adfd91d51dbe3242d9fe1483e/%2Cnnn#L35

Plugin:
https://github.com/toddyamakawa/bin/blob/master/nnn-cd-clipboard

**Comment by jarun** [comment]
The wiki section I was referring to: https://github.com/jarun/nnn/wiki/Basic-use-cases#sync-subshell-pwd
