### ISSUE TITLE
best way to prevent accidental "move to waste" by hitting x

### ISSUE THREAD

**Issue by engrka** [jarun/nnn#1101]
I'm always a bit worried accidentally hitting x and moving a file to wastebasket while not noticing it. Switching to deletion without moving to wastebasket, which till trigger a prompt, isn't an option either.
Should I just change the hotkeys to something more specific than simply hitting "x" ? Are there any suggestions?
Thanks for the great software.

**Comment by jarun** [comment]
We can add a prompt but many users don't like additional steps in straight workflows.
However, I can understand that pressing `x` can go unnoticed. I am adding a prompt to confirm trashing.

**Comment by jarun** [comment]
Please test and confirm the fix works as expected.

**Comment by Kabouik** [comment]
This is something I asked a couple years ago and @jarun indeed replied that many users wouldn't like that, so I ended up just patching `nnn.c` and `nnn.h` every time I `git clone` to remove the corresponding code and update the help screen so that just `X` is mentioned.

**Comment by jarun** [comment]
Yes, this is for both `x` and `^x`.

**Comment by engrka** [comment]
Works as expected on first basic tests. I'll do some more testing in the next days and report if there are any issues. Thank you.

**Comment by oscarpax** [comment]
How about `x` with prompt and `^x` with no prompt? I'd prefer that..

**Comment by jarun** [comment]
Sorry, it's a genuine guard and safe. No plans to change anything in the workflow.

**Comment by oscarpax** [comment]
That's fine, thank you for very useful software!
