### ISSUE TITLE
zstd

### ISSUE THREAD

**Issue by syntezoid** [jarun/nnn#1105]
**Is your feature request related to a problem? Please describe.**
I can't open .zst .tar.zst archives.
I am currently using Zstandard for archiving files, but the distribution I am using, Arch, provides applications in the .tar.zst archive format and I need to check their contents or extract them.

**Describe the solution you'd like**
Add somehow Zstandard, but I'm not sure how. As I see atool and bsdtar doesn't support .zst. I found patool as a more recent incarnation of atool, but it doesn't support Zstandard either.

**Describe alternatives you've considered**
If not via atool, patool, bsdtar is some nnn plugin that already does this?

**Additional context**

**Consider contributing**

Please consider contributing the feature back to `nnn`.

Feel free to discuss in the ToDo list thread. We are more than happy to help.

**Comment by jarun** [comment]
> Add somehow Zstandard, but I'm not sure how. As I see atool and bsdtar doesn't support .zst. I found patool as a more recent incarnation of atool, but it doesn't support Zstandard either.

Doesn't look like Zstandard is widely adopted yet. `nnn` uses `atool`/`bsdtar` internally so we can't do much natively. However, you can always write 2 plugins - one to archive and one to extract zst and assign 2 keybinds to them if that format is so important to you. I think you can also merge them into 1 i.e. if the file extension has .zst extract instead of archiving,

**Comment by eugene55** [comment]
I don't like to comment on closed issues but Arch's bsdtar in fact supports zst format. To support it from nnn side though, you just have to configure NNN_ARCHIVE environment variable to include zst extension to the list. After that zst will be treat as any other archive.

**Comment by jarun** [comment]
Link please.

**Comment by eugene55** [comment]
https://man.archlinux.org/man/bsdtar.1

**Comment by jarun** [comment]
It appears the FreeBSD version does too - https://www.freebsd.org/cgi/man.cgi?query=bsdtar&sektion=1&format=html

**Comment by Stig124** [comment]
Debian does too  (but Ubuntu doesn't):

https://manpages.debian.org/buster/libarchive-tools/bsdtar.1.en.html
