### ISSUE TITLE
tmux nested shell handling

### ISSUE THREAD

**Issue by seroam** [jarun/nnn#1107]
**Is your feature request related to a problem? Please describe.**

The [tmux configuration section](https://github.com/jarun/nnn/wiki/Troubleshooting#tmux-configuration) on the wiki suggests using this function to start nnn in tmux:

```bash
n ()
{
    # use option -a for previews
    tmux new-session nnn -a $@
}
```

When trying to start nnn this way from a tmux session, this fails with error `sessions should be nested with care, unset $TMUX to force`.

**Describe the solution you'd like**

Add the following handling to the example code on the wiki:

```bash
if [ -n "$TMUX" ]; then
    nnn -a $@
else
    tmux new-session nnn -a $@
fi
```

**Describe alternatives you've considered**

None, this seems to work.

**Comment by jarun** [comment]
I'll update this.

**Comment by jarun** [comment]
Done! Thanks for reporting the issue.
