### ISSUE TITLE
[imgview] mkdir: cannot create directory '.nthumbs': File exists

### ISSUE THREAD

**Issue by dror-weiss** [jarun/nnn#1108]
#### Environment details

- [x] Operating System: ubuntu 18.04 bionic
- [] Desktop Environment:
- [x] Terminal Emulator: iTerm
- [x] Shell: zsh
- [] Custom desktop opener (if applicable):
- [x] Program options used: nnn -e
- [x] Configuration options set: 
   export NNN_PLUG='i:imgview'
   export NNN_FIFO="/tmp/nnn.fifo"
- [] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
0. Install imgview dependencies.
1. cd ~
2. git clone https://github.com/jarun/nnn && cd nnn && make install
3. mkdir -p ~/.config/nnn/plugins
4. curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh

I saw that there were changes made to the plugin and I'm seeing a different behavior when installing the between the latest release of the plugins to the master:
- On the latest release I get the `mkdir: cannot create directory '.nthumbs': File exists` message, and 
- On master I don't get anything, the plugin just won't start.

**Comment by jarun** [comment]
@luukvbaal please take a look.

**Comment by luukvbaal** [comment]
Is the master version you're trying executable?
What image viewer are you using?

**Comment by dror-weiss** [comment]
@luukvbaal , when running `getplugs` there is a `master` argument to install the master version's plugins also without argument to grab the latest release.

I'm trying to run with `sxiv`.

**Comment by luukvbaal** [comment]
> @luukvbaal , when running `getplugs` there is a `master` argument

I know... if that's how you're getting the `master` version then that's fine.

`master` version works fine for me though with `sxiv` so idk why it "won't start"  for you hence why I wanted to make sure it was executable.

Can you remove stdout/err redirection and see if that gives you anything?

**Comment by dror-weiss** [comment]
I did what you suggested and found out I had a back x11 setup, fixing that everything works like a charm.
**Thank you** for your help!
