### ISSUE TITLE
Segfault if dir set from plugin is not absolute (sanitize plugin cd input)

### ISSUE THREAD

**Issue by pvx-** [jarun/nnn#1110]
#### Environment details

- [x] Operating System: Linux
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. Create a plugin with one line `printf "%s" "0caaa" > "$NNN_PIPE"` (instead of `aaa` can be any string *not* starting with '/')
2. Run this plugin
3. nnn segfaults

Of course plugin authors should take care not to send invalid paths, but a simple typo in plugin should not be able to segfault nnn itself :).

Also I suggest to strip '/' if it is the last path character, because if you set `/var/` as path, going into 'www' results in `/var//www` as current path, which can have unwanted consequences - for example selection marks not being shown (since filenames don't match anymore). Ideally any repeated /'s should be replaced by one, but that is probably not needed; having a path with '/' at the end can easily happen if plugin author doesn't know about this issue.

**Comment by jarun** [comment]
Please confirm if the fix works as expected.

**Comment by jarun** [comment]
Get master for the test.

**Comment by pvx-** [comment]
Everything I tested works OK now, thanks for a quick fix :).
