### ISSUE TITLE
Confirmation of #1064

### ISSUE THREAD

**Issue by kevinsjoberg** [jarun/nnn#1113]
@jarun I just wanted to confirm #1064 is solved. Your GitHub bot locked the previous issue, so I had no way of answering you.

<img width="727" alt="Screenshot 2021-07-24 at 09 16 10" src="https://user-images.githubusercontent.com/503025/126860765-d687b3f2-8208-426b-895e-a5d21346f67f.png">

Feel free to close this one at your disposal. 🙂

**Comment by jarun** [comment]
Thanks for the confirmation!

You can always use the rolling ToDo list to contact the team.
