### ISSUE TITLE
File not trashed after confirming

### ISSUE THREAD

**Issue by nathanielevan** [jarun/nnn#1115]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Arch Linux
- [x] Desktop Environment: dwm
- [x] Terminal Emulator: st
- [x] Shell: zsh 5.8
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: eo
- [x] Configuration options set: NNN_TRASH=1
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. Press `x` to delete a file
2. Confirm by pressing `x` again, or Enter
3. File still exists

Additional information:
* The trash command itself works when run directly in the terminal
* Using NNN_TRASH=0, the confirmation succeeds and the file is entirely deleted

**Comment by jarun** [comment]
Last line here: https://github.com/jarun/nnn/wiki/concepts#prompts
