### ISSUE TITLE
nnn visually hangs when searching again without redrawing

### ISSUE THREAD

**Issue by N-R-K** [jarun/nnn#1117]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Gentoo
- [x] Desktop Environment: none (dwm)
- [x] Terminal Emulator: st and xterm
- [x] Shell: zsh v5.8
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: reproducable on vanilla
- [x] Configuration options set: reproducable on vanilla
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. Search for a string ``/foo`` and then escape ``esc``
2. Without redrawing, start searching (for something which exists the the dir but not on the current filter) again ``/bar``

Pressing ``esc`` again gets it out of the hanged state.

P.S. v4.1.1 does not have this problem.

**Comment by jarun** [comment]
Did you read the release notes?

    ignore last pressed filter character when no matches

Pressing Esc does not clear a filter (read the docs). So _searching for something which exists the the dir but not on the current filter_ will not change anything in the view and you won't see anything typed because there is no match (the char is ignored).

**Comment by jarun** [comment]
This is a change in behaviour. Now that you know it, live with it. It's better than typing characters even when there is not match.

**Comment by N-R-K** [comment]
> This is a change in behaviour.

Hmm, I see. The experience here is a bit jarring. But if it's intended then I guess there's nothing to be done here.

**Comment by 0xACE** [comment]
> It's better than typing characters even when there is not match.

![cap](https://user-images.githubusercontent.com/1482942/127306577-4aca9f18-00cd-4236-8284-ce2f2c7d0159.png)
_`Personal` build to the left. `Master` to the right._

trying to find a binary with `pdf` and `zip` in the file name.

Left hand side immediately tells me it doesnt exist.

Right hand side tells me to look through the list eventually realising that my key strokes were not accepted.

I'm not sure I agree with this behaviour... I mean on the right side i typed `/pdf^[/zip` and i would expect to hit backspace 3 times, but the UI is in a different state than my mental state...

Only benefit I see in `master`'s current behaviour is in `type-to-nav` mode where you no longer have to erase on non-matches

_Alas: I'm not saying revert it. I just want to mention that it feels like it is a deviation from the norms of UX_

**Comment by jarun** [comment]
@0xACE you type and you don't see anything typed. Doesn't that indicate something went wrong?

I can revert this back. However, just confirm if you think it's difficult to get accustomed to the behaviour.

**Comment by jarun** [comment]
Or do you think it's better to have it only if type-to-nav mode is on? I would prefer to keep it consistent.

**Comment by jarun** [comment]
I think we should revert it... I can see why it won't feel natural to users.

**Comment by N-R-K** [comment]
> you type and you don't see anything typed

I don't think people are staring at the bottom bar while searching/typing (I don't, and I'd assume most keyboard driven users are no different), so seeing the list clear up is a more natural and *conventional* behavior for when there is no match.

As for ``type-to-nav`` mode, I don't use it often to have any strong opinion on what the behavior there should be.

**Comment by jarun** [comment]
> I don't think people are staring at the bottom bar while searching/typing (I don't, and I'd assume most keyboard driven users are no different)

And _you_ don't see that the list isn't changing?

**Comment by N-R-K** [comment]
> And _you_ don't see that the list isn't changing?

Sure, but its not a conventional behaviour making the experience jarring.

Anyhow, I have the commit (https://github.com/jarun/nnn/commit/3ef50f06f86a962b465d50b7ffb6909436b69685) reverted on my system, so this is no longer going to be an issue for me.

**Comment by jarun** [comment]
I have reverted this as well. This does disrupt the workflow for the uninitiated.
