### ISSUE TITLE
Open in $EDITOR not working

### ISSUE THREAD

**Issue by giodamelio** [jarun/nnn#112]
First off I want to say I _love_ `nnn` and use it all the time on my Linux box. Super handy.

More recently I have been using a Mac at work and I have been unable to get the `e` keybinding to work. It just does nothing no matter what filetype or editor I use.

I have tried `emacsclient` (the normal on my Linux box), but I have also tried `vim`, `nvim` and straight up `vi` (although I think that might just be a symlink to `vim` on my Mac).

I looked for cli flag/compile option for verbose logging and I couldn't find any. Any advice on how to debug this further?

**Comment by jarun** [comment]
To compile in debug mode, run:

`make debug`

The debug log would be in: `/tmp/nnndbg`

**Comment by jarun** [comment]
Try setting:

    export VISUAL=vim
In case the shortcut `vi` is not available on your system.

The order is:
First preference: `VISUAL`
2nd pref: `EDITOR`
Fallback: `vi`

**Comment by giodamelio** [comment]
Oh, that did it. I didn't know it would check `$VISUAL`, and I had a invalid value there.

Thanks so much for the help!

**Comment by giodamelio** [comment]
There is probably no way to configure that is there? I like having my `$VISUAL` set as GUI Emacs, but would prefer `nnn` to open my `$EDITOR` (console Vim) for quick edits.

I can always run a patched version, but would you consider a patch that allows that configuration?

**Comment by giodamelio** [comment]
For Googlers/future me, [here is a patch](https://gist.github.com/giodamelio/bd7dcd855d49b6916a75b0596f288469) to remove all support for the `$VISUAL` environment variable.

You can also add this block to the 1.8 version of the homebrew formula (with `brew edit nnn`) to install it easily.

```ruby
  patch do
    url "https://gist.github.com/giodamelio/bd7dcd855d49b6916a75b0596f288469/raw/bb1d2e511f448e294450af954b33327a88e27742/no-visual-1.8.patch"
    sha256 "87982e1fef51eed44447a0f7975727170eff349d70724da0a0877156808f4016"
  end
```

**Comment by jarun** [comment]
Earlier the support was available only for EDITOR, then VISUAL was added due to an issue raised.

The issue was from Klemens Nanni who reviewed the `nnn` port to openBSD:

```
Hey,

starting with reviewing the nnn port for OpenBSD, I noticed that VISUAL
is completely ignored. I don't have a diff for you (yet), sorry; and as
I don't use Github, here's a mail with some trivia about both variables
snatched from ksh(1):

EDITOR     If the VISUAL parameter is not set, this parameter controls
           the command-line editing mode for interactive shells.  See the
           VISUAL parameter below for how this works.
           Note: traditionally, EDITOR was used to specify the name of an
           (old-style) line editor, such as ed(1), and VISUAL was used to
           specify a (new-style) screen editor, such as vi(1).  Hence if
           VISUAL is set, it overrides EDITOR.

VISUAL     If set, this parameter controls the command-line editing mode
           for interactive shells.  If the last component of the path
           specified in this parameter contains the string “vi”, “emacs”,
           or “gmacs”, the vi(1), emacs, or gmacs (Gosling emacs) editing
           mode is enabled, respectively.  See also the EDITOR parameter,
           above.

I have VISUAL set but not EDITOR. FWIW, other file browsers such as
rover do honor VISUAL (already).

Kind regards,
Klemens
```

You can still use EDITOR if you unset the env variable VISUAL.

**Comment by giodamelio** [comment]
Thanks, it is good to keep things consistant. I guess I can just wrap it in a shell script to unset `$VISUAL` for `nnn` specifically.
