### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by akimdi** [jarun/nnn#1120]
How do I run graphical applications? The new version broke everything. It used to be like this
```export NNN_PLUG=g:-_|gimp $nnn```

**Comment by akimdi** [comment]
```export NNN_PLUG='g:-_&gimp $nnn'``` This is not working for me

**Comment by jarun** [comment]
'export NNN_PLUG='g:-!&gimp $nnn'

`_` is not used anymore.

**Comment by akimdi** [comment]
Thank you!
