### ISSUE TITLE
When using the persistent session flag on launch (-S), the rollover at the edges ceases to function

### ISSUE THREAD

**Issue by charbelnicolas** [jarun/nnn#1123]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Arch Linux
- [x] Desktop Environment: Awesome WM
- [x] Terminal Emulator: Kitty
- [x] Shell: Bash
- [x] Program options used: nnn -JHSdxu
- [x] Configuration options set: export NNN_PLUG='c:fzcd'
- [ ] Issue exists on `nnn` master: I would say so, I don't know.

#### Exact steps to reproduce the issue

Launch nnn with the -S (persistent session) flag and try to roll over at the edges and it won't work, then launch nnn without any flags and it will roll over at the edges.

**Comment by jarun** [comment]
It happens because rollover option is also saved along with the session.

**Comment by jarun** [comment]
Though we could move it, I would leave it at that. The idea of storing sessions is to start with a known environment. Users shouldn't have to remember each option.
