### ISSUE TITLE
Video and PDF previews on preview-tui doesn't work

### ISSUE THREAD

**Issue by hrqmonteiro** [jarun/nnn#1128]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Void Linux
- [X] Desktop Environment: AwesomeWM
- [X] Terminal Emulator: Kitty
- [X] Shell: Fish
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Just open nnn with the preview-tui plugin and the previews doesn't work.

I have all the dependencies (ffmpegthumbnailer) and poppler (pdftoppm) installed, and the video and pdf previews does't work.

**Comment by luukvbaal** [comment]
Are the previews generated? Check `"${NNN_PREVIEWDIR:-$TMPDIR/nnn/previews}"
` or `/tmp/nnn/previews`.
Does regular image preview work?

**Comment by luukvbaal** [comment]
Also make sure you follow the instructions and have `allow_remote_control` and `listen_on` set in kitty.conf.
Can't help if you don't respond...
