### ISSUE TITLE
Can't run "batch rename" when $EDITOR is set to vscode (usr/bin/code)

### ISSUE THREAD

**Issue by denik1981** [jarun/nnn#1134]
#### Environment details (Put `x` in the checkbox along with the information)

- [x ] Operating System: LinuxOS 5.11.0-25-generic #27~20.04.1-Ubuntu
- [x ] Desktop Environment: XDG_CURRENT_DESKTOP
- [x] Terminal Emulator: xterm-256color
- [x] Shell:/bin/bash
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: 'nnn -de'
- [x] Configuration options set: 'export EDITOR=/usr/bin/code'
- [] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. Set EDITOR to /usr/bin/code or whatever path you have located the vscode executable.
2. Open nnn.
3. Select some files for batch renaming them.
4. Press 'r' to execute the renamer.

The problem is that despite the renamer is aware of VSCODE being the prefered EDITOR, it sends and EMPTY file (wihouth the files being selected) on a temp directory named with the .nnn prefix plus a 6 letter hash (eg .nnnYHjhyZ). 

I checked that the command runs without any issue when using the default nnn editor. 
I'm not sure if this is related to VSCODE or to any GUI editor.

**Comment by jarun** [comment]
What is your `$VISUAL`? Are you using detached edits?

**Comment by jarun** [comment]
I am able to use mousepad. So no issues with GUI programs in general. Can you try with a regular GUI editor?

**Comment by jarun** [comment]
Also, do you have plugins installed?

**Comment by 0xACE** [comment]
I can replicate. Seems like `code` is the problem.

`nnn` waits for the `$EDITOR` to finish running and then returning execution to `nnn`.

But: when you spawn `code` it practically uses some IPC to another instance of `code` and then it closes. Also for w/e reason `code` spawns as a child of `init` rather than w/e process spawned it, I wont delve deeper into this.

**Comment by luukvbaal** [comment]
`EDITOR="code -w"` seems to work.

**Comment by 0xACE** [comment]
> `EDITOR="code -w"` seems to work.

Also beware of the potentiall issues with setting `EDITOR="code -w"` it probably more portable to introduce your own script `code-blocking`:
```
#!/usr/bin/env sh
code -w "$@"
```

and use `EDITOR=code-blocking`

**Comment by jarun** [comment]
I am closing this.

Sorry, we can't document code-specific behaviour. But I'll add a generic note that the instance of the editor must wait for the editing to complete.
