### ISSUE TITLE
Problems with special characters like äüö etc

### ISSUE THREAD

**Issue by dinotheextinct** [jarun/nnn#1139]
Hello, I hope this issue is actually nnn related, but it only happens for me with said program.
How the folder and contents look with **nnn**
![image](https://user-images.githubusercontent.com/32158581/130347208-98453ff8-7fd0-486c-b81c-156a5b131ed4.png)
How it looks in dolphin
![image](https://user-images.githubusercontent.com/32158581/130347241-5922e0d3-4937-43b9-b280-07805f2af14b.png)

Its kind of weird because the names change also according to what you highlighted before, hard to explain I will try to provide a video if this info isn`t enough.

**Comment by jarun** [comment]
Either your nnn binary is not compiled with ncursesw OR you are using the make option `-O_NOLC=1`.

**Comment by dinotheextinct** [comment]
I used the package delivered with opensuse:
![image](https://user-images.githubusercontent.com/32158581/130347659-9a1a80f0-bdcd-4e6e-ba3a-c0341fbb860a.png)
So I need to compile it myself to remedy the issue? Sorry not very technical or experienced.

**Comment by jarun** [comment]
What's the output of `ldd $(which nnn)`?

For example in my case it shows libncursesw:

```
$ ldd $(which nnn)       
	linux-vdso.so.1 (0x00007ffc81b81000)
	libreadline.so.8 => /lib/x86_64-linux-gnu/libreadline.so.8 (0x00007fe8ea2e5000)
	libncursesw.so.6 => /lib/x86_64-linux-gnu/libncursesw.so.6 (0x00007fe8ea2ab000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007fe8ea27b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe8ea258000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe8ea066000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe8ea060000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe8ea377000)
```

@Stig124 can you please have a look?

**Comment by dinotheextinct** [comment]
![image](https://user-images.githubusercontent.com/32158581/130347813-e71c3e85-ca84-451e-abce-19f83accb610.png)

**Comment by jarun** [comment]
Ok, the binary is linked to libncursesw. Not sure if the package is built with `NORL`.

I created a dir structure with `äüö` on UBuntu (my custom build) and I can see everything fine:

![](https://imgur.com/R04ivLS.png)

**Comment by jarun** [comment]
@Stig124 in the [PKGBUILD](https://build.opensuse.org/package/view_file/home:stig124:nnn/nnn/PKGBUILD?expand=1) I see:

    depends=('readline' 'ncurses')

should it be:

    depends=('readline' 'ncursesw')

**Comment by jarun** [comment]
@dinotheextinct in the meantime, can you try the static binary available with the last release?

Or, if you are adventurous,

1. Clone this repo.
2. Run `make strip` // you may have to install gcc, make etc.
3. Run `./nnn` and see if you still see the problem.

**Comment by dinotheextinct** [comment]
I can try to check the static binary later.

**Comment by Stig124** [comment]
> @Stig124 in the [PKGBUILD](https://build.opensuse.org/package/view_file/home:stig124:nnn/nnn/PKGBUILD?expand=1) I see:
> 
> ```
> depends=('readline' 'ncurses')
> ```
> 
> should it be:
> 
> ```
> depends=('readline' 'ncursesw')
> ```
> 
> instead?
> 
> I am not sure though, because I see `ldd` lists ncursesw. Please have a look.

ncursesw is not a thing in Arch, for openSUSE might be a thing that I need to test, but have no time rn

@dinotheextinct try using the upstream repo instead of the openSUSE one [link](https://software.opensuse.org//download.html?project=home%3Astig124%3Annn&package=nnn)

**Comment by CantoroMC** [comment]
The ArchLinux pkg ncurses provide also `usr/lib/libncursesw.so`

   |\_
  /o \\
 (_. ||
  /__\\
 )___( 

I have found this nice knight ascii art on the web, you may like to add it in front of the new nnn ascii art

**Comment by jarun** [comment]
I think we should have:

```
  |\_
  /o \\
 (_. ||
  /_3\\
  )n__(
```

**Comment by jarun** [comment]
Settled for

```
  |V\_
  /. \\
 (.~; ||
   /__3\
  (__n_))
```

**Comment by dinotheextinct** [comment]
> > @Stig124 in the [PKGBUILD](https://build.opensuse.org/package/view_file/home:stig124:nnn/nnn/PKGBUILD?expand=1) I see:
> > ```
> > depends=('readline' 'ncurses')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > should it be:
> > ```
> > depends=('readline' 'ncursesw')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > instead?
> > I am not sure though, because I see `ldd` lists ncursesw. Please have a look.
> 
> ncursesw is not a thing in Arch, for openSUSE might be a thing that I need to test, but have no time rn
> 
> @dinotheextinct try using the upstream repo instead of the openSUSE one [link](https://software.opensuse.org//download.html?project=home%3Astig124%3Annn&package=nnn)

![image](https://user-images.githubusercontent.com/32158581/130657476-c7f9d4ac-9e72-45ac-ad9e-df0944f640bf.png)
Getting the following error when using your link

**Comment by jarun** [comment]
@dinotheextinct which release are you on? SLE/Tumbleweed/Leap?

I will download and share the package with you.

**Comment by jarun** [comment]
If you see https://github.com/jarun/nnn/issues/1145#issuecomment-907606940 when the user changed the locale to `en_US`, the characters were not visible. Can you check if it's a locale issue for you as well?

**Comment by dinotheextinct** [comment]
`locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_DE.UTF-8
LC_CTYPE="en_DE.UTF-8"
LC_NUMERIC="en_DE.UTF-8"
LC_TIME="en_DE.UTF-8"
LC_COLLATE="en_DE.UTF-8"
LC_MONETARY="en_DE.UTF-8"
LC_MESSAGES="en_DE.UTF-8"
LC_PAPER="en_DE.UTF-8"
LC_NAME="en_DE.UTF-8"
LC_ADDRESS="en_DE.UTF-8"
LC_TELEPHONE="en_DE.UTF-8"
LC_MEASUREMENT="en_DE.UTF-8"
LC_IDENTIFICATION="en_DE.UTF-8"
LC_ALL=`

I guess first three rows dont look good. ^^;

**Comment by dinotheextinct** [comment]
Jesus christ, I think I fixed it, I deleted: ~/.config/plasma-localerc

![image](https://user-images.githubusercontent.com/32158581/131221886-8bb52cee-a48a-4802-adc9-2d4acdc5495c.png)

Beautiful. Thanks for all the help guys and for this great software, much love!

**Comment by jarun** [comment]
Glad to know this is fixed!
