### ISSUE TITLE
quoting does not handle all cases

### ISSUE THREAD

**Issue by Enlik** [jarun/nnn#114]
Quoting changes something like `like'this` to `'like'this'` which is not a properly quoted file name. To keep it simple, it should probably change this to `'like'\''this'`.

```sh
$ echo 'like'\''this'
like'this
```

**Comment by jarun** [comment]
> To keep it simple

I am aware of this and left it intentionally as a caveat. Parsing the full name of the file and unquoting everything is not that simple when Unicode is considered. An additional buffer would also be required. I will leave this as it is.

**Comment by Enlik** [comment]
You may want to reconsider it still given that it opens up path of shell injections (and its nasty implications: data loss, data safety...) and fix it, remove the functionality, document the limitation in a very visible way for the unaware (i.e. most users) or reject file names you don't support.

**Comment by jarun** [comment]
Notes:

`nnn` doesn't invoke a new shell. It uses `execlp` to run the script. Where do you see the issue with shell injection?

Also, the usecase in this scenario is the user copies a file from the filesystem. If you have downloaded a file on your filesystem with a creepy command, you are already compromised.

**Comment by Enlik** [comment]
> I will document this scenario. Thanks for reporting.

Thanks.

> Where do you see the issue with shell injection?

It's not necessarily (I haven't checked) nnn itself, but how the copied string is then used.
From the manual:

> NNN_QUOTE_ON: wrap copied paths within single quotes. Useful for pasting names in the shell.

Files with `'` aren't that uncommon. Example what happens when they're "pasted in the shell":

```sh
$ touch "X Y's album.ogg"
$ NNN_COPIER=~/copier.sh NNN_QUOTE_ON=1 nnn
# copied the name with ctrl-k, exited nnn
# ls + ctrl-shift-v + ctrl-d:
$ ls '/tmp/X Y's album.ogg'
> bash: unexpected EOF while looking for matching `''
bash: syntax error: unexpected end of file
```

So it's more that the function doesn't work as expected rather than a security issue (it's more a data safety thing if you're unlucky).

**Comment by Enlik** [comment]
It was all probably fixed after chaning to `\0`. Thanks much!
