### ISSUE TITLE
How to get rid of -i flag for rm while deleting files?

### ISSUE THREAD

**Issue by ftpd** [jarun/nnn#1140]
So, when I hit x in nnn, I'm asked for confirmation if I really want to delete - which is fine. The problem is: after confirming my action, rm -i seems to be invoked, so I have to confirm twice. I could live with this for files, but rm -ri of a directory, especially including git repo with tons of files in .git subdir it just pain in the ass.

I haven't found answer in the docs - sorry if it's there and I missed it.

**Comment by jarun** [comment]
At the following prompt, press `y`:

    rm -rf hovered? [Esc cancels]

**Comment by ftpd** [comment]
Oh but I do. It invokes rm -i anyway.

**Comment by jarun** [comment]
No problem! All binary questions in `nnn` accept y/n.

**Comment by ftpd** [comment]
Any chance to set Enter as a 'y' response equivalent? It's just quicker.

**Comment by jarun** [comment]
No. You will get accustomed in a few days.

**Comment by ftpd** [comment]
Hope so. Thanks for blazing fast response!
