### ISSUE TITLE
Support: How to use the B key.

### ISSUE THREAD

**Issue by CantoroMC** [jarun/nnn#1142]
How can i reach the directory added with the B key.
I know they are stored as symlinks in `${XDG_CONFIG_HOME}/nnn/bookmars/` but once stored how can i easily/rapidly access them?

**Comment by jarun** [comment]
<kbd>b</kbd> followed by <kbd>Enter</kbd>.

You can ask questions in the ToDo list.

**Comment by CantoroMC** [comment]
Ok, sorry i was afraid of spamming it.

**Comment by jarun** [comment]
It's absolutely fine! :+1:
