### ISSUE TITLE
How to specify sort by file name?

### ISSUE THREAD

**Issue by XhstormR** [jarun/nnn#1145]
The sort option in the help does not know the specific meaning:
```
 -T key  sort order [a/d/e/r/s/t/v]
```

**Comment by jarun** [comment]
You'll know if you press <kbd>^T</kbd> at runtime.

I've also added a footnote here: https://github.com/jarun/nnn/wiki/Usage#program-options

**Comment by XhstormR** [comment]
I tried it, and it seems that the default is to sort by file name, but there seems to be a problem with some file name sorting.

nnn default sort:
![image](https://user-images.githubusercontent.com/10527522/131212445-a5d8dec7-a2a0-4285-bb9e-2b0de43e1fd4.png)

exa sort:
![image](https://user-images.githubusercontent.com/10527522/131212483-d6ca6e31-3464-40a1-a73f-c4595202fa31.png)

output:
```
user@c02ft5jdmd6m:~/Downloads/bb
 ❯ l
.rw-r--r--@ 5.7M user staff 2021-08-21 18:35  Arianne - 来吧，甜蜜的死亡 (M-10 Director’s Edit. Version).m4a
.rw-r--r--@ 1.8M user staff 2021-08-24 18:06  Knell Anwyll - Get Ghosted.m4a
.rw-r--r--@ 4.6M user staff 2021-08-21 18:38  arlie Ray - 来吧，甜蜜的死亡.m4a
.rw-r--r--@ 3.9M user staff 2021-08-24 08:26  宇多田光 - Beautiful World.m4a
.rw-r--r--@ 3.1M user staff 2021-08-28 15:58  宇多田光 - One Last Kiss.m4a
.rw-r--r--@ 3.4M user staff 2021-08-24 10:42  宇多田光 - 桜流し.m4a
.rw-r--r--@ 2.9M user staff 2021-08-24 14:40  鷺巣詩郎 - EM20#070720.m4a
```

**Comment by jarun** [comment]
What you show is Hebrew to me.

We use `strcoll()` internally.

What's your locale?

**Comment by jarun** [comment]
It shows correctly on my system:

![](https://github.com/jarun/nnn/wiki/Usage#program-options)

My locale output:

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_IN.UTF-8
LC_TIME=en_IN.UTF-8
LC_COLLATE=en_IN.UTF-8
LC_MONETARY=en_IN.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_IN.UTF-8
LC_NAME=en_IN.UTF-8
LC_ADDRESS=en_IN.UTF-8
LC_TELEPHONE=en_IN.UTF-8
LC_MEASUREMENT=en_IN.UTF-8
LC_IDENTIFICATION=en_IN.UTF-8
LC_ALL=
```

**Comment by jarun** [comment]
BTW, which tool are you using to annotate the images?

**Comment by XhstormR** [comment]
I use this https://www.snipaste.com/

Before I used zh_CN.UTF-8, now I changed to en_US.UTF-8, but the sorting result has not changed.

![image](https://user-images.githubusercontent.com/10527522/131214700-ad0db3aa-3a73-4d99-98fe-6fe0d9817dbc.png)

![image](https://user-images.githubusercontent.com/10527522/131214798-653efc3a-8ff9-47a7-842c-ea9ea20ed470.png)

Then I changed it to en_IN.UTF-8, and there was a problem with the display. According to the size of the comparison file, the sorting result changed and the order was correct.

![image](https://user-images.githubusercontent.com/10527522/131215025-cba27d04-e8af-4b17-9b66-ea6338952f6f.png)

**Comment by jarun** [comment]
What's your OS and nnn version?

**Comment by jarun** [comment]
I tried with both musl and gcc. Unable to replicate your issue.

**Comment by jarun** [comment]
As you'll see in the earlier image I shared, I for me those unidentified characters show as squares.

**Comment by jarun** [comment]
I am on ubuntu 20.04, nnn master, xfce4-terminal.

**Comment by XhstormR** [comment]
After I changed to C, the display is correct:

![image](https://user-images.githubusercontent.com/10527522/131215859-14abe5b6-c240-417e-aaa8-3031ef01c0a1.png)

nnn 4.2, macOS 11.5

**Comment by jarun** [comment]
Thanks for the confirmation.
