### ISSUE TITLE
Emit OSC-7 escape when changing directory

### ISSUE THREAD

**Issue by dnkl** [jarun/nnn#1147]
Originally reported here: https://codeberg.org/dnkl/foot/issues/696; some users expect the terminal's builtin "spawn a new window" feature to open the new terminal window in nnn's current directory.

This works "automagically" on some terminals (which most likely dig through `/proc` to find out the current CWD of the leaf child process).

Others implement OSC-7, and escape that let's the application control which directory the terminal should consider to be the "current" one. Shells are often configured to emit this as part of rendering their prompts.

OSC-7 is pretty simple; just URL encode the directory and write `\033]7;file://$HOSTNAME$CWD\033\\` (for example, `\033]7;file://mini.la.casa/home/user/foobar\033\\`). See e.g. https://codeberg.org/dnkl/foot/wiki#user-content-how-to-configure-my-shell-to-emit-the-osc-7-escape-sequence for a shell implementation. It is also documented here: https://iterm2.com/documentation-escape- codes.html.

It is implemented by at least VTE terminals, iTerm2 and foot.

Note that well behaving terminals ignore unrecognized OSC sequences, meaning it should be safe to emit OSC-7 unconditionally.

Note: avoid using `localhost` as hostname. The terminal matches the hostname to be able to ignore OSC-7 escapes from remote hosts (e.g. SSH).

Is it a "standardized" escape? It's not a VT escape, and not part of ECMA-48. So no, in that sense it's not standardized. There's an open issue over at [terminal-wg](https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/20), and one unmerged [PR](https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/7) (unmerged due to too much bikeshedding). With that, I fully understand if this is a feature you want to pass :)

**Comment by jarun** [comment]
The code should go here:

https://github.com/jarun/nnn/blob/c9746904825e05b3feb429ac753139fb915d612a/src/nnn.c#L6503

Please share the exact printf() OR raise a PR. I don't own macOS so I can't test it.

**Comment by dnkl** [comment]
Thanks! I'll see what I can do about opening a PR.

>  I don't own macOS so I can't test it.

FWIW you don't need macOS. It's also supported by libvte, and while I don't know if **all** VTE-based terminals therefore automatically support it, gnome-terminal should (not asking you to implement it though - just an FYI).

**Comment by jarun** [comment]
I am on Xubuntu and tried with xfce4-terminal and it didn't work somehow. Can't really spend time on something that someone else already knows how to implement and test easily.
