### ISSUE TITLE
batch rename files

### ISSUE THREAD

**Issue by ixzh** [jarun/nnn#1149]
hi,

when I try to batch rename, tmp file becomes something like:
```
1 ./Rafael Kubelik - Complete HMV Recordings (13CD) [2014]  FLAC
2 ./Telegram Desktop
3 ./temp
```
I don't recall there are leading numerators and path-like `./` there...is it considered a new feature...How can I disable it?  I just want the orignal names show.

- [x] Operating System: Voidlinux
- [x] Desktop Environment:xmonad
- [x] Terminal Emulator:Alacritty
- [x] Shell:Bash
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: -egx
- [ ] Configuration options set:
- [ ] Issue exists on `nnn` master

**Comment by KlzXS** [comment]
This is a relatively new feature. It is a custom batch rename plugin that is invoked automatically if available instead of the builtin batch rename.

To disable it remove or rename the `.nmv` plugin.

**Comment by ixzh** [comment]
thanks renamed .nmv solved the problem. there is another renamer plugin for the same purpose? where can I find documents on this?
