### ISSUE TITLE
because of NNN_PLUG my nnn does not open

### ISSUE THREAD

**Issue by mohammad5305** [jarun/nnn#1150]
![image](https://user-images.githubusercontent.com/71145952/131341658-5024f610-06f1-4a62-b492-bf5e2d89e838.png)
when I add NNN_PLUG my nnn does not open and say NNN_PLUG
I also try bash but nothing change same happened
I use zsh with st terminal 
distro  : archlinux
wm : i3

**Comment by jarun** [comment]
Add : after the keys p, m and b.
