### ISSUE TITLE
Tmux split-pane in dwm

### ISSUE THREAD

**Issue by N214** [jarun/nnn#1151]
Hello, I have made the change for split-pane in tmux follwing the instructions here
https://github.com/jarun/nnn/wiki/Basic-use-cases#detached-text

But the side pane just blink and it disappears :/ 
Someone can help me? I use dwm, a tiling window manager

**Comment by jarun** [comment]
It's a tmux split issue, so you should ask the tmux devs first.

However, @luukvbaal @leovilok @0xACE any ideas?

**Comment by pvx-** [comment]
This has probably nothing to do with nnn (or dwm, hi fellow dwm user ;), I remember this as well when I first tried split in tmux - when the command ends, the pane is closed as well. You can try it in pure shell

```
tmux split-window -h vim
```
opens vim and closes the pane after closing it

```
tmux split-window -h sleep 1
```
opens the pane for one second and closes it. So if you want to use it just for some output, I suggest using `less` or ending with `read` to wait for user input before closing.

**Comment by jarun** [comment]
@pvx- please feel free to update the wiki.

**Comment by N214** [comment]
Thanks @pvx-  and @jarun 
You guys pointed me in the right direction, I solved my issue. 

I forgot that I'm using neovim by default there're it is normal that it does not work. 
Just replace vim by nvim.
