### ISSUE TITLE
Highlighting broken

### ISSUE THREAD

**Issue by jasoneveleth** [jarun/nnn#1152]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: macOS BigSur 11.5.1
- [x] Desktop Environment: macOS
- [x] Terminal Emulator: kitty
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable):
- [x] Program options used: '-d'
- [x] Configuration options set:
```bash
$ env | rg -i nnn
NNN_BMS=o:~/notes;c:~/.config
NNN_PLUG=n:-_fzfnotes*;v:-_nvim*
NNN_OPTS=e
NNN_COLORS=4512
```
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Compile from master. Run it with 'nnn -d' and the highlighting for the current file only applies to the name and the first column or the line, not on the file details. 

https://imgur.com/a/Cq3kmjd

I think this is related to another problem that I'm having which is the selection '+' sign is still highlighted when moving to another file.

https://imgur.com/a/DBKpICX

I have tried this using other shells (bash and fish). No luck. The same problem seems to happen. I've tried tinkering with the TERM env variable. It doesn't seem to change anything. I tried different terminals (Terminal.app and Alacritty). Neither changed anything. I tried with the default font. That didn't change anything. I also have an arch install (with an identical Alacritty config, and dwm). So I tried running nnn there and nothing changed. I also tried using a tty on that machine and it didn't make a difference.

I don't understand what the issue could be. I'm probably overlooking something dumb but I'm not sure what the problem could be.

Thank you for your time.

**Comment by KlzXS** [comment]
There is no issue. These are the new defaults.

If you want to change it back look into `printent()` and the use of `A_REVERSE`.
