### ISSUE TITLE
Rename list does not include hidden files

### ISSUE THREAD

**Issue by menkaur** [jarun/nnn#1153]
#### Environment details (Put `x` in the checkbox along with the information)

- [ ] Operating System:
Pop!_OS 21.04
- [ ] Desktop Environment:
Gnome
- [ ] Terminal Emulator:
alacritty
- [ ] Shell:
fish
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. Toggle hidden files on with . (dot)
2. Press r to rename
3. Hidden files will not be in the list

**Comment by KlzXS** [comment]
Are you using the plugin batch rename (`.nmv`) on by default if you downloaded the plugin or the builtin batch rename?

You can tell which one it is if it has numbers before the filenames.

**Comment by menkaur** [comment]
I see numbers before the filenames

**Comment by KlzXS** [comment]
I see. I'll dig into this more tomorrow.

@jarun do we have a system in place for passing an env variable to a child process? I don't remember something like that. We need to set `INCLUDE_HIDDEN=1` for `.nmv`.

**Comment by KlzXS** [comment]
That's right but it would be nice to keep the behavior consistent as the builtin shows hidden files, I think.

But you can run a command as a plugin. You can pass the env variable there. Right?

@menkaur I think you'll just have to employ something like that. Adding passing of env would be of no benefit except for this.

**Comment by jarun** [comment]
Yes, there are several ways to do this. You can also show an _optional_ prompt asking whether to include hidden or not.

**Comment by menkaur** [comment]
A+R works, but it's workaround. I think that having the same list in batch rename as you see on the screen is expected behavior. Also, I just checked, if you filter file list and than press R, you see all visible files

If having this behavior is too much work, second best option would be to have R always show full file/directory list, including hidden files

**Comment by jarun** [comment]
> A+R works, but it's workaround

Take it anyway you want, but we won't pass an extra param for one plugin. It's better to decouple the plugin to work independently.

@KlzXS see if we can introduce the prompt in the plugin. make the prompt optional as well. If user needs, she can enable the prompt.

**Comment by jarun** [comment]
Please test with commit 49be2cfcd19e800f69f2aa4e371db2bb13fc6a7c and confirm this works as expected.
