### ISSUE TITLE
When TERM environment variable is rxvt-unicode icons don't show

### ISSUE THREAD

**Issue by onlyvip** [jarun/nnn#1154]
I have compiled nnn from source using the NERD_O=1 flag. My primary terminal emulator is urxvt. For urxvt to work properly I need to set TERM variable as rxvt-unicode. However if nnn is opened in urxvt then there are no icons however if I use xterm-256color then I can have icons in nnn when opened in urxvt. My question is what is the main problem when I set rxvt-unicode and try in urxvt? 
Any help or redirection to appropriate channel is appreciated

P.s. I have installed it via MPR in debian bullseye. For any further information that I might have missed please ask as you may want to know

**Comment by jarun** [comment]
How many color codes does rxvt-unicode use? We show icons only in 256-color mode.

**Comment by jarun** [comment]
You can enable [debugging](https://github.com/jarun/nnn/wiki/Developer-guides#debugging-nnn) and find it in the logs.

**Comment by onlyvip** [comment]
> How many color codes does rxvt-unicode use? We show icons only in 256-color mode.

Ok I have used --enable-everything to compile it I'll check if 256 colour flag gets enabled as default in that case

**Comment by jarun** [comment]
I see the following with "rxvt-unicode":

```
 14 ln 2103: COLORS=88
 15 ln 2104: COLOR_PAIRS=510
```

With "screen-256color":

```
 14 ln 2103: COLORS=256
 15 ln 2104: COLOR_PAIRS=510
```

We dn;t show the icons of new new colorscheme if COLORS is below 256. Hence you are seeing this.

**Comment by jarun** [comment]
Documentation: https://github.com/jarun/nnn/wiki/Advanced-use-cases#file-icons

**Comment by onlyvip** [comment]
> I see the following with "rxvt-unicode":
> 
> ```
>  14 ln 2103: COLORS=88
>  15 ln 2104: COLOR_PAIRS=510
> ```
> 
> With "screen-256color":
> 
> ```
>  14 ln 2103: COLORS=256
>  15 ln 2104: COLOR_PAIRS=510
> ```
> 
> We dn;t show the icons of new new colorscheme if COLORS is below 256. Hence you are seeing this.

How did you find these values?

**Comment by jarun** [comment]
From the debug logs.

**Comment by onlyvip** [comment]
Yes this indeed was the problem. 😌
I got it solved by adding the following line to my .Xresources file
`URxvt.termname:     rxvt-unicode`

**Comment by jarun** [comment]
:+1:
