### ISSUE TITLE
Preview window in focus rather than nnn window

### ISSUE THREAD

**Issue by AndreasAZiegler** [jarun/nnn#1158]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Arch Linux
- [x] Desktop Environment: dwm
- [x] Terminal Emulator: st
- [x] Shell: fish
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: ```nnn -a```
- [x] Configuration options set: ```set -x NNN_FIFO /tmp/nnn.fifo set -x NNN_PLUG 'p:preview-tabbed'```
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

When I open the preview plugin with ```;p``` a new terminal opens with the preview. The problem is that the preview window becomes the active window in dwm and I have to manually go (back) to the nnn window. I'm coming from ```ranger``` where I was used to having the preview window within the same window.

**Comment by luukvbaal** [comment]
Use `preview-tui` with either `tmux` or `kitty` instead and you will previews more akin to what you're used to.
