### ISSUE TITLE
Preset ^ to regex filter

### ISSUE THREAD

**Issue by recallthis** [jarun/nnn#1161]
When using navigate-to-type in regex mode, the alphabetic order of folder names seems like the quickest and easiest way to make selections. 

So I tend to want to type ^d ^b ^c (for example) to navigate all the time.

A prefix ^ to the regex filter would speed this up immensely.

**Comment by jarun** [comment]
Sorry, we cant add personal preferences to generic search tokens. Some other user may not want it. You have an empty field for regex like in every other software.
