### ISSUE TITLE
cannot access `$nnn` when executing command as plugin

### ISSUE THREAD

**Issue by akrifari** [jarun/nnn#1162]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: `arch linux 5.13.13-arch1-1`
- [x] Desktop Environment: `i3 version 4.19.1`
- [x] Terminal Emulator: `alacritty 0.9.0`
- [x] Shell: `zsh 5.8 (x86_64-pc-linux-gnu)`
- [x] Custom desktop opener (if applicable): `nuke`
- [x] Configuration options set:

```sh
NNN_OPENER=$HOME/.config/nnn/plugins/nuke
NNN_OPTS="dex"
NNN_COLORS="4321"
NNN_PLUG_DEFAULT='f:fzopen;v:imgview;g:getplugs;c:diffs;d:dragdrop'
NNN_PLUG_INLINE='x:!chmod u+x $nnn;t:-!tree -a $nnn;u:!unlink $nnn'
NNN_PLUG="$NNN_PLUG_DEFAULT;$NNN_PLUG_INLINE"
NNN_BMS='h:~;p:~/Pictures;b:~/.local/bin'
NNN_FCOLORS='c1030402006006f7c6d6ab01'
NNN_TRASH=1
```

- [x] Issue exists on `nnn` master

#### Description

I had been tinkering with my plugins definitions, trying to splitting up into different environment variables (`NNN_PLUG_DEFAULT` and `NNN_PLUG_INLINE`) and combined those things together into `NNN_PLUG` as documented in [plugins/README.md#configuration](https://github.com/jarun/nnn/blob/e7aec90889a3e9fbf23962468701766fc2bd5429/plugins/README.md#configuration) and [plugins/README.md#running-command-as-plugin](https://github.com/jarun/nnn/blob/e7aec90889a3e9fbf23962468701766fc2bd5429/plugins/README.md#running-commands-as-plugin). It had been working smoothly until I upgraded to e7aec90889a3e9fbf23962468701766fc2bd5429. I needed to downgrade to d34741107ac0691e92b28462db5b9ea49e475e70 in order to be able to run. I suspect this was introduced in fa7cef2df75c940994f4a700b317645034864b26. I wonder, is fa7cef2df75c940994f4a700b317645034864b26 still work in progress or am I missing something? Let me know if you need any additional information.

#### Exact steps to reproduce the issue

1. Create shell script file
2. Press <kbd>;x</kbd> to run `chmod` inline plugin
3. `chmod: cannot access '$nnn': No such file or directory`

**Comment by jarun** [comment]
I think the plugins can access. However, commands run as plugin can't.

**Comment by akrifari** [comment]
Yeah, it is.

Here is the recording:

https://user-images.githubusercontent.com/33394747/132697963-4aa43692-c0cd-4a80-9179-f8805bde5ab3.mp4

**Comment by jarun** [comment]
Please test and confirm the patch.

**Comment by akrifari** [comment]
Thank you so much! It works perfectly :+1:

**Comment by jarun** [comment]
:+1:
