### ISSUE TITLE
[QUESTION] Option to not close nnn on Escape?

### ISSUE THREAD

**Issue by jaredreardon** [jarun/nnn#1163]
Hi, I had no idea where to ask this and if this is not an acceptable way to ask just let me know and I'll close this promptly but I just had a question about whether it was possible to make it so nnn doesn't close when you click Escape twice? Currently if I have it open in my wm and I double tap Escape the whole program will close which I, personally, dislike. Any flag I can use to stop this or something simple I can edit in the source? If anyone has any help I'd appreciate it a lot, and again if this is an inappropriate place to ask questions just inform me and I'll get rid of this asap. Thanks! :)

**Comment by jarun** [comment]
> I double tap Escape

Why would you double tap Esc? This was added on user request to make quitting nnn easy. We are not going to change it or add a flag to disable it.
