### ISSUE TITLE
Project Drawer and dual pane setup

### ISSUE THREAD

**Issue by Trid-collab** [jarun/nnn#1165]
I am new to nnn. I am quite liking it . However I am unable to set up the project drawer option or the dual pane option with the subdirectory tree as shown in some of your demos on the site. Is it enabled by default . Is it something I am missing or do I need to configure something separately.

**Comment by jarun** [comment]
What is project drawer? Can you point to the image?

Dual pane docs: https://github.com/jarun/nnn/wiki/Concepts#dual-pane

**Comment by Trid-collab** [comment]
This is the one I am referring to.
https://asciinema.org/a/329162?loop=1&autoplay=1&size=medium

**Comment by luukvbaal** [comment]
That gif is showing the plugin [`preview-tui`](https://github.com/jarun/nnn/blob/master/plugins/preview-tui). Keep in mind that you need to use either `tmux` or `kitty` to have the dual pane setup, please read the docs.

**Comment by jarun** [comment]
Closing as the question is answered.
