### ISSUE TITLE
trash on macOS

### ISSUE THREAD

**Issue by screendriver** [jarun/nnn#1168]
**Is your feature request related to a problem? Please describe.**

At the moment trashing files is support with `trash-cli` and `gio trash` via the environment variable `NNN_TRASH`. Unfortunately these tools are not working on `macOS`. On macOS one of the recommended tools is [trash](https://hasseg.org/trash/).

**Describe the solution you'd like**

It would be great if I can specify [trash](https://hasseg.org/trash/) when deleting files.

**Describe alternatives you've considered**

I also tried to set an alias like `alias trash-cli=trash` but it does not work.

**Comment by jarun** [comment]
Please raise the PR.

**Comment by N-R-K** [comment]
> I also tried to set an alias like `alias trash-cli=trash` but it does not work.

Aliases are for the interactive shell, it doesn't normally work outside of it. You can use wrapper shell script for this instead.

```sh
#!/bin/sh

trash "$@"
```

name this script `trash-cli` and put it in your PATH.

**Comment by dhruvmanila** [comment]
Actually, you should name the script `trash-put` because that's the command (comes with `trash-cli`) which is being used: https://github.com/jarun/nnn/blob/master/src/nnn.c#L585

**Comment by screendriver** [comment]
Awesome! Thank you for your help 👍

**Comment by N-R-K** [comment]
You can now set `$NNN_TRASH` to a custom command and use whatever trashing utility you prefer. See the [wiki](https://github.com/jarun/nnn/wiki/Usage#configuration) and manpage for more info.
