### ISSUE TITLE
discoverable commands menu

### ISSUE THREAD

**Issue by select** [jarun/nnn#117]
I really like nnn but I just can't remember the shortcuts. It would be really nice if there would be a menu that you can switch on and off where you can discover all nnn commands. Maybe also tab through like in the zsh. Another idea would be a searchable menu like in Sublime with Ctrl+Shift+P where you can fuzzy find all the commands.
 
Just and idea, what do you think?

**Comment by jarun** [comment]
> I really like nnn but I just can't remember the shortcuts.

Neither can I! ;) Press `?` anytime and you'll find all the shortcuts listed.
