### ISSUE TITLE
Plugin preview-tui preview picture extension add .png extension

### ISSUE THREAD

**Issue by XhstormR** [jarun/nnn#1176]
Currently preview-tui supports only .jpg extension for previewing pictures.

**Comment by luukvbaal** [comment]
Previews for image extensions other than `.jpg` would have worked if you have `convert`(ImageMagick) installed.
`.jpg.` was chosen as target extension to convert to as it is rendered faster.

The fact that `preview-tui` was only previewing `.jpg` without ImageMagick was unintended though, thanks for pointing it out.
