### ISSUE TITLE
[zsh]: cd on quit doesn't work

### ISSUE THREAD

**Issue by PrayagS** [jarun/nnn#1181]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Garuda Linux (Arch)
- [x] Desktop Environment: i3wm
- [x] Terminal Emulator: alacritty
- [x] Shell: zsh

I copied the quitcd function from the repo and pasted it in a script. I also added the options and env vars I use. The contents of that script are as follows:

```sh
n ()
{
    # Block nesting of nnn in subshells
    if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
        echo "nnn is already running"
        return
    fi

    # The default behaviour is to cd on quit (nnn checks if NNN_TMPFILE is set)
    # To cd on quit only on ^G, remove the "export" as in:
    # NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    # export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    export NNN_TMPFILE="$HOME/.config/nnn/.lastd"

    STUDY_PATH="/mnt/DATA/Study/Monsoon_2021"

    NNN_BMS="1:$STUDY_PATH/CSE524;2:$STUDY_PATH/CSE525;3:$STUDY_PATH/CSE527;4:$STUDY_PATH/CSE540;5:$STUDY_PATH/JAP111;"
    export NNN_BMS

    NNN_PLUG="z:autojump;d:dragdrop;c:fzcd;f:fzopen;p:preview-tabbed;"
    export NNN_PLUG

    export NNN_OPTS="aAdexDHU"
    export NNN_TRASH="1"
    nnn "$@"

    if [ -f "$NNN_TMPFILE" ]; then
        . "$NNN_TMPFILE"
        rm -f "$NNN_TMPFILE" > /dev/null
    fi
}
```

#### Exact steps to reproduce the issue

Pressing `^G` does quit nnn and record the last directory in the `.lastd` file. I commented the `rm` command and did observe that the last directory was being saved in that text file. I even sourced the file manually by running `. "$NNN_TMPFILE"` and the shell successfully manages to cd to that directory. But in its current form, the script is not working at all. The file is updated and removed but the cd on quit never happens.

Any issues that I can't see here? I tried debugging the shell function as suggested in other similar issues but now I'm confused. Any help will be appreciated.

Thanks in advance!

**Comment by N-R-K** [comment]
> I copied the quitcd function from the repo and pasted it in a script.

Did you `source` this script into your `.zshrc` ? A script cannot change the working directory of your current shell.

**Comment by PrayagS** [comment]
Rookie mistake on my side. Thanks for your quick help @N-R-K
