### ISSUE TITLE
Please add the ability to display custom text

### ISSUE THREAD

**Issue by ManInTheSuit** [jarun/nnn#1185]
**Is your feature request related to a problem? Please describe.**

I sometimes forget about e.g. various shortcuts. I'd like to make my nnn more user-friendly, e.g. show which button to press for which functionality (e.g. "press ; for plugins" at the bottom of the screen, add description to various bookmarks-practically solved through symlink bookmarks I think, etc.).

**Describe the solution you'd like**

Ability to add custom, user-defined text to the bottom of the screen, depending on the context. Ideally it would maybe support markdown, but custom coloring and font size would be good enough to start with. Maybe even support piping outputs of scripts (e.g. constantly show current time).

**Describe alternatives you've considered**

I have no idea, maybe there are some? Couldn't find any.

**Comment by jarun** [comment]
There won't be any change in this area. I would suggest you pick up a more friendly file manager. There are tons of them.

**Comment by N-R-K** [comment]
Pressing <kbd>?</kbd> shows all keybindings, plugins and (env) bookmarks.
