### ISSUE TITLE
. in the type-to-nav mode swithes `show hidden` instead of navigating

### ISSUE THREAD

**Issue by Glavnokoman** [jarun/nnn#1187]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: arch linux
- [x] Desktop Environment: kde
- [x] Terminal Emulator: kitty
- [x] Shell: bash
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: -AQn
- [ ] Configuration options set:
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue:
Type  `.` in any directory in type-to-nav mode with empty filter, see the show hidden files mode switching. 
Desired behaviour: filter files starting with `.`

**Comment by N-R-K** [comment]
This isn't exactly a "bug", the behavior is documented. Check the "FILTERS" section on the manpage.

**Comment by N-R-K** [comment]
Under regex mode you can use `\.` to get around this. Not sure if there's a way to do that under normal filter mode.

**Comment by Glavnokoman** [comment]
> This isn't exactly a "bug", the behavior is documented. Check the "FILTERS" section on the manpage.

Ah, good to know. Thanks!
