### ISSUE TITLE
icons mess up after changing terminal font

### ISSUE THREAD

**Issue by ixzh** [jarun/nnn#1197]
#### Environment details (Put `x` in the checkbox along with the information)
```
_ \______ -     os     Void Linux
| \  ___  \ |    kernel 5.13.19_1
| | /   \ | |    pkgs   862
| | \___/ | |    memory 1901M / 3838M
| \______ \_|    de     xmonad
 -_______\       shell  bash
                     terminal alacritty
```
- [x] Program options used: `-adDegQUx`
- [ ] Configuration options set:
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Icons look right, if terminal font is not set:
![image](https://user-images.githubusercontent.com/14981695/137537074-74999245-d88b-42be-89de-8f15df005274.png)

Icons look awry when terminal font set to `Sarasa Term SC`: 
![image](https://user-images.githubusercontent.com/14981695/137536859-8409a512-274d-469d-ade8-f8e1b5032053.png)

**Comment by jarun** [comment]
And does it work with other utilities?

**Comment by jarun** [comment]
Please run `./print_icons.sh` and confirm if the issue exists with the changed fonts.

**Comment by jarun** [comment]
This is out of nnn. Please raise a defect on the icons-in-terminal project.

**Comment by ixzh** [comment]
noted Thanks!!!
