### ISSUE TITLE
Copying image to clipboard

### ISSUE THREAD

**Issue by gevhaz** [jarun/nnn#1199]
I just started using nnn and was wondering if it's possible to copy an image to the clipboard. In KDE Dolphin, I'd just do ctrl+c when an image is selected and can then paste the actual image into e.g. chat applications (the path gets pasted as well, but this is not actually what I want).

Is it possible to copy an image to the clipboard with nnn, or are there plugins for it? Otherwise consider this a feature request.

**Comment by gevhaz** [comment]
Thanks for the reply! It works :) 

Just to be sure what I'm doing, what is the $nnn variable here? and the ":-" in "png:-"?

**Comment by luukvbaal** [comment]
See https://github.com/jarun/nnn/tree/master/plugins#running-commands-as-plugin.
`$nnn` gets expanded to the hovered file, can't find the docs for that however.

**Comment by jarun** [comment]
BTW, this is a cool example to add to the plugins doc.
