### ISSUE TITLE
Loose my .zshrc config when exiting nnn?

### ISSUE THREAD

**Issue by mariush2** [jarun/nnn#120]
Hi!

When I use nnn to navigate and exit using `Q, !`, I end up 'loosing' my alias and stuff. This is probably just me being stupid, any ideas on how to fix this? (Running OS X and oh-my-zshell).

Thanks in advance.

**Comment by jarun** [comment]
You don't need to press `!`. It's either capital `Q` or `^G`.

Anyway, i don't have OS X so can't try it out right now.

@zmwangx could you help here? (whenever you have the time)

**Comment by mariush2** [comment]
This just seems to set my `NNN_TMPFILE` and doesn't exit nnn. I might have configured it wrong? I just ran `brew install nnn` to install it.

**Comment by zmwangx** [comment]
> I end up 'loosing' my alias and stuff.

I guess you mean "losing"... "My alias and stuff" is really vague, need a lot more details, i.e., exactly what alias is "lost", exactly what command works before but not after, what "stuff" is.

> This just seems to set my NNN_TMPFILE and doesn't exit nnn.

That additional information seems in direct contradiction with the previous "I end up 'loosing' my alias and stuff."

**Comment by zmwangx** [comment]
First, 'loose' doesn't make sense. You keep using the wrong word, in quotes... Not sure why you insist on doing that.

Secondly, I recommend to see what's exactly executed by zsh by running

```zsh
setopt xtrace; nnn (or whatever command you launch nnn with here); unsetopt xtrace
```

I seriously doubt sourcing a file with the content `cd "directory"` can clobber your alias. There's a chance you have a weird path and `nnn` isn't quoting that properly (I didn't audit the code), but the chance of that clobbering an alias without you intentionally constructing the path is smaller than being hit by lightning.

**Comment by mariush2** [comment]
Here is a screenshot of what is happening to clarify.

<img width="682" alt="screenshot 2018-10-26 at 20 35 17" src="https://user-images.githubusercontent.com/24507952/47585873-e19b3a80-d95e-11e8-9a65-4ba72ed005cc.png">

Here I ran `nnn` and move to the directory I wanted `~/Dropbox/ntnu-bit/høst-18/IT1901/03/gruppe3`, hit `Q` then hit `!` (both in nnn, obv) and exited to the directory. As you can see I then tried running `gits` again it did not work.

**Comment by mariush2** [comment]
> Here I ran `nnn` and move to [...]
>
To clarify further, by move I mean using the arrow-keys inside `nnn`

**Comment by zmwangx** [comment]
`!` doesn't `cd`. There's nothing an external command can do that makes your shell change your directory without you explicitly asking your shell to do something. `!` is for spawning a subshell, and it does NOT exit `nnn`. Your use of `Q` is also completely pointless in this case.

Now, again I didn't read the code, but most likely the spawned subshell is not a login shell, so stuff in `.zprofile` is not loaded. See `man 1 zsh`.

It's arguable whether the spawned shell should be a login shell, but I'd say non-login shell is the right choice here. If you want your stuff in every interactive session, use rc, not profile.

If what you actually want is cd on quit, pretty please RTFA. https://github.com/jarun/nnn#cd-on-quit

**Comment by jarun** [comment]
Closing the issue. Please go through the documentation for correct usage of the utility.
