### ISSUE TITLE
Create link with any name

### ISSUE THREAD

**Issue by dgcom** [jarun/nnn#1201]
Current implementation of 'n'ew -> 's'ym/'h'ard function only allows creation of links with the same name as source or adding some prefix.

Would be great to be able to create link with any name, not just prefixed one.
Possible implementation - allow entering new name after `@` character (when it is in position 1 indicating no prefix).
It should also be possible to escape `@` character as first symbol of the name... 

Workaround is to rename link after creation.

Also... Current documentation states that prompt is for `suffix` and actual prompt is for `prefix`:

Basic use case](https://github.com/jarun/nnn/wiki/Basic-use-cases) wiki states:
`enter the link suffix (or @ for no suffix)`
Actual application prompt:
`link prefix [@ for none]:`

**Comment by jarun** [comment]
> Looks like feature restriction on main executable does not lend itself to a slightly more complex prompts :)

Because the program is not just about 1 complex prompt. :)

**Comment by dgcom** [comment]
Well, my use case was to quickly create a symlink to a single file with completely different name. None of batch or multi-selection functionality was needed. It should be easy to prompt for new name if only one item being linked - however this will require changing prompt order in nnn.
Not sure why this is not a feature - its a basic functionality and I need this more often thank linking set of files at once. 
I see why this does not fit current core functionality - it is not possible to copy/move single file with new name, link is follows this restriction.
If nnn would be designed to cover most basic functionality available in the prompt, speeding up this kind operations, then it would be more complex than it is now.
