### ISSUE TITLE
Preview Not Working with tmux next 3.4

### ISSUE THREAD

**Issue by levone1** [jarun/nnn#1206]
Running nnn in tmux on SailfishOS; nnn is latest, built from source, and tmux is v. 3.4 next.  Have been using with tmux 3.2, and previewer (tui) working fine, but now nothing - attempting to call preview causes a quick flash of the screen, and back to file list.

FIFO set, and all dependencies installed, plus some optionals...

Not sure if it's just the tmux version, or if there's anything I can do to test/troubleshoot ...

edit - switched to tmux 3.2a to test, and still not working.  Seems to behave a little more normally now, showing "fifo not set" error when I start nnn without fifo, (wasn't doing that with 3.4), but still won't go into preview mode.  Not sure where to look for problem...

imgview plugin working fine...

Thanks

**Comment by levone1** [comment]
N-R-K - thank you. That's what I was wondering.
jarun - I assumed this had something to do with mu setup, since I had it working before. I just wasn't sure where to start trying to figure it oit...

Thanks

**Comment by jarun** [comment]
No problem!

**Comment by levone1** [comment]
So I was able to suppress things like 

"unable to open /tmp/nnn-preview-tui-pagerpid no such file or directory"

with some exports, and what I now ger is

"Bridge.exe not found..."

**Comment by luukvbaal** [comment]
What do you mean you were able to suppress with some exports? Can you try to get rid of all the tmpfile variables i.e. `FIFOPID PREVIEWPID CURSEL FIFO_UEBERZUG` and hardcode to some location in your home folder instead?

Bridge.exe not found is expected when you remove error redirection but will not affect successful operation of the script.

**Comment by levone1** [comment]
So that's pretty much what I did - first I went through variables and unset anything to do with nnn or fifo, etc., then when I go the error, e.g., "unable to open /tmp/nnn-preview-tui-pagerpid no such file or directory", I woul export, e.g., "NNN_PREVIEW_TUI=~/nnnpreviewtui", and same for fifo, after that, there were no more errors about "no such file..." - just the Bridge.exe error, but still no preview ...

**Comment by luukvbaal** [comment]
Still have no idea what would cause this sorry, besides not being in `tmux`...

**Comment by levone1** [comment]
Thanks.  I have a feeling it may have to do with my current SF setup, (also having issue with nnn preview in my Linux container, which has worked fine before).  I'm always messing with things, so not unusual to run into these things...  I'll probably clean-flash at some point, and try from there.  I bet it will work fine.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
