### ISSUE TITLE
definition of auto-advance / auto-select / rollover at edges

### ISSUE THREAD

**Issue by ixzh** [jarun/nnn#1209]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: void
- [x] Desktop Environment: xmonad wm
- [x] Terminal Emulator: alacritty
- [x] Shell: bash
- [x] Custom desktop opener (if applicable): na
- [x] Program options used:  `-adDegQUx`
- [x] Configuration options set: 
```
NNN_COLORS: #0a1b2c3di
NNN_FCOLORS: c1e2272e006033f7c6d6abc4
NNN_MCLICK: ^R
NNN_ARCHIVE: \.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$
SELECTION FILE: /home/bo/.config/nnn/.selection
```
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. in a folder, type `/` to filter
2. the only filtered folder is not auto `cd` into

and the `+` toggle(`SHIFT` + `=` key?) has no effect.

and the roll over the edge, how does it work? as currently all long names are cut off on the right edge with or without the -R flag. Does this feature mean to reflow text if string doesn't fit in 1 line? 

Thanks

**Comment by ixzh** [comment]
I was confused by a few terms: type-to-nav (`ctrl+n` toggle), auto-advance (`+` toggle) and auto-select when type-to-nav (`-A` flag) and auto-proceed on select (`-J` flag).

So by default, I will need to toggle on the type-to-nav in nnn, and it will auto-select and auto-advance unless `-A` and `-J` flags at starting up?

**Comment by ixzh** [comment]
and `auto-advance` and `auto-proceed` then same thing?  `-J` is startup disabled status? and `+` is the in-app toggle?

**Comment by jarun** [comment]
Yes.

**Comment by jarun** [comment]
I think + is to auto-advance on open.
