### ISSUE TITLE
batch rename find/fd files

### ISSUE THREAD

**Issue by ixzh** [jarun/nnn#1214]
**Is your feature request related to a problem? Please describe.**

`fd pdf ~/Downloads -0 | nnn` can be used to show and open files, but batch rename `r` doesn't work.

**Describe the solution you'd like**

Would it be possible to make  `r` operate on symlink list to rename target files? seems to be  a natural extension of the `r` function.

**Comment by jarun** [comment]
Press `Left` on the symlink and it will take you to the target file. Then rename it.

**Comment by ixzh** [comment]
> Press `Left` on the symlink and it will take you to the target file. Then rename it.

That's for an individual file. I'm asking about the `r` batch rename. Will amend the description.

**Comment by jarun** [comment]
While it's a regular use case for you, implementing it is roundabout - we have to find each target, add to a new buffer and then rename. Sorry, there is no ROI for us here.

**Comment by ixzh** [comment]
Thanks anyway!

**Comment by N-R-K** [comment]
@ixzh this use-case maybe better solved by some dedicated batch-ranamer script/program. There are quite a lot out there, although I haven't used any.

**Comment by ixzh** [comment]
> @ixzh this use-case maybe better solved by some dedicated batch-ranamer script/program. There are quite a lot out there, although I haven't used any.

you mean in the plugin listing? Or where can I find? I'm using the default .mcp I think.

**Comment by N-R-K** [comment]
> you mean in the plugin listing?

No, independent ones.

> Or where can I find?

You can try searching for "batch renamer" in github. As I've said, I don't use any so I can't recommend one.

**Comment by ixzh** [comment]
> > you mean in the plugin listing?
> 
> No, independent ones.
> 
> > Or where can I find?
> 
> You can try searching for "batch renamer" in github. As I've said, I don't use any so I can't recommend one.

Ok, thank you! I will try to figure out a way.

**Comment by jarun** [comment]
On second thoughts, @KlzXS do you think we can extend the batchrename script to rename the files in the current directory but apply to the symlink targets? We can see if we can figure a way to indicate to the script if this is a case of a listed directory.

**Comment by jarun** [comment]
If someone else wants to give it a try, we will need to rename the target for the symlink in plugin `.nmv` rather than the file itself to achieve this.

The main program can set an env var before calling `.nmv` to indicate that the current directory is in listing mode.

**Comment by KlzXS** [comment]
We can do that. Make `.nmv` resolve symlinks if. Suggest a name for the env variable.

**Comment by jarun** [comment]
`$NNN_LIST`

**Comment by jarun** [comment]
Resolved at commit 470c777f2d50f21f817b89129c0ee89b8a3b3a35.

@ixzh please confirm the fix.

**Comment by jarun** [comment]
Please test with commit eb769c0de5d762280b2bd973e3024890c884a58e as I have made a minor modification.

**Comment by ixzh** [comment]
I put 3 files in the following:
![image](https://user-images.githubusercontent.com/14981695/140024094-f24280e7-0e13-4b43-87e1-7e18dc882b6b.png)

and start nnn using:`fd . ~/Downloads/Telegram\ Desktop/ -0 | nnn`
![image](https://user-images.githubusercontent.com/14981695/140024160-ae8f208f-1076-4177-b846-a319f2944ce4.png)

and `r` batch rename by prepending a number:
![image](https://user-images.githubusercontent.com/14981695/140024292-0da21f38-2c60-4127-8b3e-8d1852d1a04f.png)
![image](https://user-images.githubusercontent.com/14981695/140024346-ae604bde-b767-4e62-b151-7f08dc4e476b.png)

and `:wq`:
![image](https://user-images.githubusercontent.com/14981695/140024430-904fd732-0f58-4c8b-a763-762112a3c190.png)

pressing `q`, and the target files are gone.
![image](https://user-images.githubusercontent.com/14981695/140024519-542b0b04-1e3e-42ca-a522-bf971d4ea5fe.png)


Another issue:
the getplugs plugin seems to download an outdated zip, which always overwrite the latest git version.

**Comment by KlzXS** [comment]
> the getplugs plugin seems to download an outdated zip

By default it downloads a zip that goes with the version of nnn. To download from master run it as `getplugs master`.

**Comment by ixzh** [comment]
> > the getplugs plugin seems to download an outdated zip
> 
> By default it downloads a zip that goes with the version of nnn. To download from master run it as `getplugs master`.

I see. I'll amend my plugin command. Thanks!

**Comment by KlzXS** [comment]
I can see where the problem is. For now use it only with selection.

**Comment by ixzh** [comment]
hey 
since commit #1508874, .nmv seems not to work:
![image](https://user-images.githubusercontent.com/14981695/140863380-22e31c19-5900-4241-bf71-1e2996c49592.png)

**Comment by jarun** [comment]
@KlzXS can you please take a look?

**Comment by KlzXS** [comment]
See #1232. I hope this ends the whole saga.

**Comment by ixzh** [comment]
thank you! it works.
