### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [jarun/nnn#122]
[An extra null pointer check is not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") in [the function “dentfill”](https://github.com/jarun/nnn/blob/c5a841f507b18045adabdaac16211fa191868a38/nnn.c#L2163 "Update candidate: dentfill()").

**Comment by jarun** [comment]
I removed it anyway, saves me a check. ;)

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/jarun/nnn/commit/134ee92f43029ac3c5dad630e48d6eb160e6a52e "Deletion of a redundant check").

**Comment by jarun** [comment]
No problem! :dancing_men:
