### ISSUE TITLE
nnn:27: maximum nested function level reached; increase FUNCNEST?

### ISSUE THREAD

**Issue by aryadovoy** [jarun/nnn#1222]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Fedora Linux 35
- [x] Desktop Environment: KDE Plasma 5.22.5
- [x] Terminal Emulator: st
- [x] Shell: zsh 5.8
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used: 
- [x] Configuration options set: cdroQx
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I've got this message after updating `.zshrc`.
![image](https://user-images.githubusercontent.com/26593349/140613039-852ed8ce-2b47-47b4-a9ca-f6a2d86da499.png)

But `N` is working fine.

```bash
alias n='nnn -cdroQx'
alias N='sudo -E nnn -cdHroQx'

# nnn

nnn ()
{
    # Block nesting of nnn in subshells
    if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
        echo "nnn is already running"
        return
    fi

    export NNN_OPENER=/home/aryadovoy/.config/nnn/plugins/nuke
    export NNN_COLORS='3214'
    BLK="0B" CHR="0B" DIR="04" EXE="06" REG="00" HARDLINK="06" SYMLINK="06" MISSING="00" ORPHAN="09" FIFO="06" SOCK="0B" OTHER="06"
    export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"

    export NNN_USE_EDITOR=1
    export TERMINAL='st'
    export NNN_FIFO=/tmp/nnn.fifo

    export NNN_TRASH=1

    export NNN_TMPFILE="$HOME/.config/nnn/.lastd"

    nnn "$@"

    if [ -f "$NNN_TMPFILE" ]; then
        . "$NNN_TMPFILE"
        rm -f "$NNN_TMPFILE" > /dev/null
    fi
}
```

**Comment by N-R-K** [comment]
The problem here is that your function is named `nnn` , it's basically calling itself over and over again. Either use a different name for the function or call `nnn` by path inside the function.

```diff
-    nnn "$@"
+    /full/path/to/nnn "$@"
```
