### ISSUE TITLE
option to disable - line wrap for preview-tui

### ISSUE THREAD

**Issue by JoseConseco** [jarun/nnn#1225]
**Is your feature request related to a problem? Please describe.**

I wish I could disable line wrapping when previewing text files. I tried to add `--wrap=never` - for bat in  preview-tui plugin - but it did not had any effect (when running bat manually from command line - wrap=never works ok). 
![image](https://user-images.githubusercontent.com/13521338/140798000-b85c7f31-7930-47ec-8dfc-16cc86b50843.png)

**Describe the solution you'd like**

Disable line wrap in text files. 

**Describe alternatives you've considered**

I tired to manually add  `--wrap=never`  to preview-tui fil.e. It wont do anything.  settings --color=never works though, so I'm sure it is correct place to add wrap parameter.
![image](https://user-images.githubusercontent.com/13521338/140797560-d05f0715-ede7-41c1-bf8c-d997f45c822a.png)

**Comment by 0xACE** [comment]
More likely than not, there is either a environment issue or it's not running the script.

Easiest if you check the commandline and insert an `env >/tmp/envdump` in there just to see if there is an environmental factor invovled.

Anyhow, this problem isn't exactly related to `nnn`.

**Comment by luukvbaal** [comment]
This happens because the command run in `fifo_pager` is displayed by `PAGER="${PAGER:-bat --wrap=never}"`.

If you want to disable line wrapping you need to set your PAGER to `bat --wrap=never`.

**Comment by luukvbaal** [comment]
Might be a better default for a preview pane but not sure if it's worth changing.

**Comment by JoseConseco** [comment]
I tried to add -S to less, in pager - and every occurrence of less in preview-tui. And add  --wrap=never to every occurrence of bat, but I got no luck - lines are still wrapped. My  env: 
![image](https://user-images.githubusercontent.com/13521338/140895699-81244061-3a55-42c3-a8f1-bdb8584fddcd.png)

But I think 'less' arguments from  preview-tui should override the env  args, right?   Its weird that disabling colors using bat args worked ok, but disabling line wrap arg wont.

**Comment by luukvbaal** [comment]
The only change that is required is setting `PAGER` to `less -S` (either in your environment for general use or at the top of preview-tui`). There is no need to "change every occurrence` of `bat` and `less` in `preview-tui`.

Your problem is that your env contains `PAGER=less` which will cause `PAGER="${PAGER:-less -SP?n -R}"` to evaluate to `less` not to the string after `:-`.

> Its weird that disabling colors using bat args worked ok, but disabling line wrap arg wont.

The line wrap argument for `bat` affects the paging mode but because `--paging=never`, this argument has no effect.
