### ISSUE TITLE
Kitty preview image dimension is cut in half

### ISSUE THREAD

**Issue by ahloiscreamo** [jarun/nnn#1228]
Hello,
i'm reporting a possibly bug on kitty icat 

- [x ] Operating System: `Linux artix 5.14.16-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 03 Nov 2021 07:49:34 +0000 x86_64 GNU/Linux`
- [x ] Desktop Environment:
`i3 version 4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors`
- [x ] Terminal Emulator:`kitty 0.23.1 created by Kovid Goyal`
- [x ] Shell:`fish, version 3.3.1`
- [x ] Program options used:`nnn -r -e -x -C`
- [x ] Configuration options set: via config.fish
```
#NNN
export NNN_FIFO="/tmp/nnn.fifo nnn"
export NNN_OPENER="xdg-open"
export NNN_OPENER_DETACH=1
export EDITOR="nvim"
export NNN_EDITOR="/usr/bin/nvim"
export NNN_VISUAL="nvim"
export NNN_COLORS="453"
export NNN_FCOLORS="0B0B04060006060009060B06"
export NNN_BMS='m:/media;g:/gallery;d:~/Downloads;p:~/Pictures;t:~/Documents;f:~/Desktop'
export NNN_PLUG='j:autojump;p:preview-tui;l:launch;r:renamer;w:wallpaper;o:organize;x:xdgdefault'                  

#Bat
export BAT_THEME="Nord"

#Alias
alias nnn="nnn -r -e -x -C" 
alias icat="kitty +kitten icat"
```
- [x] Issue exists on  `nnn 4.3-1`

#### Exact steps to reproduce the issue

Launch nnn, activate preview-tui and see the image loaded but the dimension is wrong, sometimes the dimension is small, sometimes it cut half on terminal especially when the image is landscape.

However i did not track on when this behavior  happen in the first place, because i usually view images by opening straight with sxiv.
so i don't know on which version it started to happen. All the preview script are updated to the latest version.

video for references -

windowed terminal

https://user-images.githubusercontent.com/9318372/141144988-959957aa-0996-4bbe-a246-8a3da9649018.mp4

full-screen terminal

https://user-images.githubusercontent.com/9318372/141145790-74a20fc3-7312-4f1f-893b-ac5646976b9c.mp4

So that is the behavior.
if i want to change the preview using ueberzug, can you guide me on which line of the terminal-tui to edit?
Thanks~

**Comment by luukvbaal** [comment]
You shouldn't be required to edit anything in preview-tui to use ueberzug. Just run `tmux` inside kitty and preview-tui should use ueberzug.

However I'm now seeing similar issue with tmux/ueberzug. `stty size`/`tput cols`/`tput lines` all return an empty string. It seems `preview-tui` is no longer running inside a tty somehow. I'll try to investigate or pinpoint the offending commit it there has been a regression.

**Comment by ahloiscreamo** [comment]
Thank you very much, i will wait for the update!

**Comment by luukvbaal** [comment]
I can't find any commit that works properly on my current system.

I know `ncurses` has released a new version recently, perhaps there has been a change/regression there regarding `tput cols/rows`? @jarun @KlzXS Otherwise I have no idea.

**Comment by luukvbaal** [comment]
I actually had to go all the way back to before https://github.com/jarun/nnn/commit/b97e2d02ea92c390977a94810b3f0afc076b81a3#diff-54a92244e225af094208f1f95c565b7ecf05d6f2da7f19971bbb67848c155563.

I very much doubt that I never noticed this issue if it has been present since then though. I wonder if the `ncurses` angle has any merit or if I (or anyone else) really never noticed it since April.

**Comment by luukvbaal** [comment]
Is it possible that somehow `ncurses` or whoever is responsible for it stopped passing terminal size to sub-processes with a recent release? Do you know @jarun? I'm not familiar with ncurses. 

That would explain the issue, I really can't believe that image previews have been broken since https://github.com/jarun/nnn/commit/b97e2d02ea92c390977a94810b3f0afc076b81a3 but perhaps I'm going crazy.

**Comment by luukvbaal** [comment]
I can confirm that I don't see any issues on `ncurses-6.2`. Are you on `ncurses-6.3` as well @ahloiscreamo?

**Comment by luukvbaal** [comment]
No idea if we should report this to the ncurses project, or if we should change preview-tui to be non-forking again.

**Comment by ahloiscreamo** [comment]
@luukvbaal Hello yes mine is `ncurses 6.3-1` too,

**Comment by luukvbaal** [comment]
https://github.com/jarun/nnn/pull/1231 should fix the issue.

**Comment by ahloiscreamo** [comment]
@luukvbaal  That was fast, thanks for your great work, i'll test and update the new build soon, was going to bed.
Goodnight!

**Comment by luukvbaal** [comment]
The underlying issue is that `echo "$(tty)"`(`tty` cmd in a subshell)returns `not a tty` on `ncurses-6.3` whereas it returns the tty device of the main shell on `6.2`. 

Idk what is the proper behavior.

**Comment by jarun** [comment]
@luukvbaal I never came across such a change.

**Comment by luukvbaal** [comment]
Yeah I can't find anything regarding it either but all I know is that on 6.2 `tput` reports the correct terminal size in preview-tui while on 6.3 it reports some default vaule of 80, 24.

**Comment by N-R-K** [comment]
Might be worth reporting to the ncurses mailing list.

**Comment by luukvbaal** [comment]
Yeah I did.

**Comment by ahloiscreamo** [comment]
Hello!
i just test the updated script.

Kitty with tmux behave well fine

https://user-images.githubusercontent.com/9318372/141286859-f91908b4-d15c-447c-a85a-d48cd5291075.mp4

kitty with icat makes the image on the center (windowed kitty), which i can accept that, its well behave on fullscreen.


https://user-images.githubusercontent.com/9318372/141287246-e6ffd626-7e7c-46c7-80ff-9e87e1dcaae8.mp4



https://user-images.githubusercontent.com/9318372/141287270-222b223e-f7f1-4a4e-a138-e14c67520111.mp4

thanks for the fix, i will closed the issue as it solve my issues.

**Comment by luukvbaal** [comment]
Couldn't reproduce the icat issue @ahloiscreamo but you could check if it is fixed for you on https://github.com/jarun/nnn/pull/1234.
