### ISSUE TITLE
Compile Error on Raspberry Pi 3B Plus

### ISSUE THREAD

**Issue by asparatu** [jarun/nnn#1233]
When I try to compile nnn on Raspberry Pi, I receive compile error. After, it is done compiling the icons do not display. I have the new Github repo, not the stable version.

#### Update
I downloaded version 4.3 and I receive the same compile error.

#### Error Message
`src/nnn.c: In function ‘invertselbuf’:
 src/nnn.c:1728:44: warning: operand of ?: changes signedness from ‘int’ to ‘uint_t’ {aka ‘unsigned int’} due to unsignedness of 
 other operand [-Wsign-compare]
 endpos = (i + 1 == nmarked ? selbufpos : marked[i + 1].startpos - pselbuf);
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

#### Environment details
- [x] Operating System: Linux 5.10.63-v7+ #1459 SMP Wed Oct 6 16:41:10 BST 2021 armv7l GNU/Linux
- [x] Shell: bash
- [x] Gcc Version:  gcc (Raspbian 8.3.0-6+rpi1) 8.3.0

#### Exact steps to reproduce the issue
![image](https://user-images.githubusercontent.com/3848896/141236531-dbdec05e-5bdb-4a32-81e9-91316d626d20.png)
![image](https://user-images.githubusercontent.com/3848896/141236425-32d30fae-571b-4bc3-8200-979900796486.png)

Both compiled versions product the error and no icons displayed
![image](https://user-images.githubusercontent.com/3848896/141236312-bdfa577c-7c00-4841-9b28-09a5d2c189f6.png)

I just ran make at the command line and gave me the same error.
![image](https://user-images.githubusercontent.com/3848896/141237098-a872ae8f-1bd0-4193-a8e1-60b1107fe1b0.png)

**Comment by KlzXS** [comment]
Here is the wiki entry on icons: https://github.com/jarun/nnn/wiki/Advanced-use-cases#file-icons. You can pick either `O_ICONS` or `O_NERD`. You can't use them both.

Make sure that you have the proper patches fonts installed and that the terminal is set to use them. Also make sure to check wether your terminal is capable or rendering the glyphs at all.

**Comment by KlzXS** [comment]
The warning (it's not actually an error), while interesting, has nothing to do with icons. It has to do with inverting selection. You can ignore it for now, but report if you experience any issues with that feature if you use it.

**Comment by KlzXS** [comment]
I just now noticed that you're sshing into your pi from powershell.  

I'm not sure you can use icons-in-terminal. Checkout Nerd fonts to see if they have instructions for installing on Windows.

The problem is purely on the Windows' side.
