### ISSUE TITLE
Can't get file icons to work

### ISSUE THREAD

**Issue by amanjitsk** [jarun/nnn#1238]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Ubuntu 20.04
- [x] Desktop Environment: `bspwm`
- [x] Terminal Emulator: `kitty` (and `st`)
- [x] Shell: `zsh`
- [x] Custom desktop opener (if applicable): `nuke`
- [x] Program options used:
```bash
export NNN_ARCHIVE="\\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$"
export NNN_OPTS="cCdEfHorQSUx"
export NNN_OPENER="$XDG_CONFIG_HOME"/nnn/plugins/nuke
export NNN_TRASH=1
export NNN_COLORS="42564256"
BLK="0B" CHR="0B" DIR="04" EXE="06" REG="00" HARDLINK="06" SYMLINK="06" MISSING="00" ORPHAN="09" FIFO="06" SOCK="0B" OTHER="06"
export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
export NNN_HELP="neofetch"
export NNN_LOCKER="vlock"
export NNN_FIFO="$XDG_RUNTIME_DIR/nnn.fifo"
export NNN_SEL="$XDG_CONFIG_HOME/nnn/selection"
```
- [x] Configuration options set: `export NNN_OPTS="cCdEfHorQSUx"`
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I have been trying to get the icons to work for a long time, but haven't been
able to do so. I have tried both approaches, the `icons-in-terminal` (tested
the installation using the `print_icons.sh` script provided, and it displays
the icons correctly on kitty) and the nerdfonts approach (using `Iosevka` and
`FiraCode` both). I am not sure what I am missing, or if its just a simple
environment variable, but both approaches fail to display any icons. This is
what it looks like with the `O_NERD=1` compile option (on `kitty` with `Iosevka
Nerd Font`, set using
```conf
font_family      Iosevka Medium Nerd Font Complete
bold_font        Iosevka Bold Nerd Font Complete
italic_font      Iosevka Italic Nerd Font Complete
bold_italic_font Iosevka Bold Italic Nerd Font Complete
```
). I am also fairly certain both `kitty` and `st` have truecolor support.
![image](https://user-images.githubusercontent.com/12499495/141700671-0f17403e-bc18-4e4a-af4e-a5f15ead4acc.png)
Thanks,
Amanjit

**Comment by N-R-K** [comment]
I think it's due to `C` in your `$NNN_OPTS`. Try with that removed.

**Comment by amanjitsk** [comment]
Oh that was indeed it. Thanks for that quick response!
It would be nice to document this somewhere if not already there.

**Comment by N-R-K** [comment]
It's documented here https://github.com/jarun/nnn/wiki/Advanced-use-cases#file-icons
> Note that your $TERM must support 256 colors for the icons to show.

`-C` turns on 8 colors mode, so icons won't work.

**Comment by amanjitsk** [comment]
Ah that was subtle, I see. Thanks!
