### ISSUE TITLE
homebrew install on macos 10.14.6  - can't find `misc' dir

### ISSUE THREAD

**Issue by srustamo** [jarun/nnn#1242]
#### Environment details (Put `x` in the checkbox along with the information)

- [ x] Operating System: macOS 10.14.6 
- [ x] Desktop Environment: none
- [ x] Terminal Emulator: kitty
- [ x] Shell: zsh
- [ x] Custom desktop opener (if applicable): none
- [ x] Program options used: default
- [ x] Configuration options set: none
- [  ] Issue exists on `nnn` master 

#### Exact steps to reproduce the issue

I'm trying to locate configure cd-on-quit as described here:
https://github.com/jarun/nnn/wiki/Basic-use-cases#configure-cd-on-quit

However, homebrew nnn install does not have misc dir. 
<img width="481" alt="image" src="https://user-images.githubusercontent.com/749813/143028193-066c4fd8-63c1-4404-832a-5c23044b9ad3.png">

**Comment by jarun** [comment]
It is linked to a directory in the repo: https://github.com/jarun/nnn/tree/master/misc/quitcd

**Comment by N-R-K** [comment]
What's inside share and etc ? Each package-manager/distro have their own policy on where to install docs or examples. I'm not familiar with homebrew but it's possible that they've included the example in either share/ or etc/

**Comment by N-R-K** [comment]
Also it's just an example. You can copy the relevant config from online and paste it on your shell rc.

**Comment by srustamo** [comment]
I greped the nnn install dir, none of the subdirs contain the subject
flies.

**Comment by N-R-K** [comment]
If homebrew has a policy of installing docs/examples but it's not doing so for nnn, then you should file a bug report on homebrew's issue tracker.

**Comment by jarun** [comment]
I don't think the misc directory is installed. Please get it from the project repo. It's an example script. Not intended for installation as well.
