### ISSUE TITLE
batch rename on MacOS iterm2 Error

### ISSUE THREAD

**Issue by ixzh** [jarun/nnn#1246]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: MacOS
- [x] Terminal Emulator: iTerm2
- [ ] Desktop Environment:
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
use `r` to batch rename, and it fails with the following error:
```
sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range
sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range
sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range
sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range
sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range
sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range
sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range
sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range
sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range
sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range
sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range
sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range
sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range
sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range
/Users/void/.config/nnn/plugins/.nmv: unknown item number 4
/Users/void/.config/nnn/plugins/.nmv: unknown item number 5
/Users/void/.config/nnn/plugins/.nmv: unknown item number 6
/Users/void/.config/nnn/plugins/.nmv: unknown item number 7
/Users/void/.config/nnn/plugins/.nmv: unknown item number 8
/Users/void/.config/nnn/plugins/.nmv: unknown item number 9
/Users/void/.config/nnn/plugins/.nmv: unknown item number 10
/Users/void/.config/nnn/plugins/.nmv: unknown item number 11
/Users/void/.config/nnn/plugins/.nmv: unknown item number 12
/Users/void/.config/nnn/plugins/.nmv: unknown item number 13
/Users/void/.config/nnn/plugins/.nmv: unknown item number 14
/Users/void/.config/nnn/plugins/.nmv: unknown item number 15
rm: : No such file or directory
rm: : No such file or directory
rm: : No such file or directory
rm: : No such file or directory
rm: : No such file or directory
rm: : No such file or directory
rm: : No such file or directory
rm: : No such file or directory
rm: : No such file or directory
rm: : No such file or directory
rm: : No such file or directory
rm: : No such file or directory
```

**Comment by jarun** [comment]
Do you have GNU sed installed?
Did this work before and happens only with latest 4.4 release?

@KlzXS

**Comment by ixzh** [comment]
Hi, 
I notice the default sed is shipped with MacOS(/usr/bin) and homebrew has a gnu-sed named gsed(/opt/homebrew/bin/gsed). 

I will need to find a way to switch sed to gnu version then. Thanks !!!

**Comment by N-R-K** [comment]
If `.nmv` needs gsed then we should make it a mandatory dep there as well.
I think it's better for the script to output some helpful error msg like "GNU sed is required", users should be more easily able to troubleshoot that way and would prevent future duplicate bug reports.

**Comment by 0xACE** [comment]
> rm: : No such file or directory
> rm: : No such file or directory
> rm: : No such file or directory
> rm: : No such file or directory
> rm: : No such file or directory
> rm: : No such file or directory
> rm: : No such file or directory
> rm: : No such file or directory
> rm: : No such file or directory
> rm: : No such file or directory
> rm: : No such file or directory
> rm: : No such file or directory

**yikes**

unchecked file operations are potential disasters waiting to happen, like that `steam` accident that deleted users entire `$HOME` directory, because of:

somwhere in the code `$STEAMROOT` wasn't getting set and `rm -rf "$STEAMROOT/"*` was parsed as `rm -rf /*`

https://github.com/valvesoftware/steam-for-linux/issues/3671

**Comment by 0xACE** [comment]
Also I guess our bash scripts from now on should at least use `set -eax` or w/e is considered to be safe.

**Comment by jarun** [comment]
@N-R-K many of our plugins use `sed`. Can you please audit which ones may require GNU sed?

**Comment by N-R-K** [comment]
I can grep through them and check for GNU-sed related flags. But verifying if the the regex used is POSIX or not will be pain.

**Comment by N-R-K** [comment]
Non-POSIX flags:
* `dups` , `xdgdefault` are using `-E`
* `dragdrop` is using `-z`

Other than these, `fixname` seems to be using some regex/command which I'm not entirely sure if posix or not. Seems to work fine with the `--posix` flag so I'm assuming it's fine.

**Comment by jarun** [comment]
Thanks!  Is there a way to get rid of `-E`?

**Comment by KlzXS** [comment]
> Thanks! Is there a way to get rid of -E?

Yes there is. I'll do it.

> Other than these, fixname seems to be using some regex/command which I'm not entirely sure if posix or not

I think you are refering to the part that replaces all newlines in a filename with "_ ". That should be fine.

**Comment by N-R-K** [comment]
> sed: 1: "s|^./Gavriel Lipkind &  ...": RE error: invalid character range

Looking back, are we actually requiring GNU-sed or is this due to unsanitized string being treated as regex?

**Comment by KlzXS** [comment]
Oh, you mean the filname might contain something like "[a-9]"? You are right, that would be a problem. There is no way we are sanitizing such input.

Making it not require GNU extensions is not a bad thing anyway.

**Comment by ixzh** [comment]
> the filname might contain something like "[a-9]"
I deleted the folder already...but I was sure it was not working when I tried to substitute strings like `(2009)[SACD][Hi-Res]` using a regex patern `%s/\v\[.+\]//g` or `%s/\v\(.+\)//g`
