### ISSUE TITLE
Sxiv script

### ISSUE THREAD

**Issue by hoaxdream** [jarun/nnn#1249]
hi, i just came back to linux and i have my dotfiles working before and i have this simple script to use with nnn that open all images in the directory in thumbnail mode with sxiv.

` #!/bin/sh
sxiv -t * > /dev/null 2>&1 &
`
and i have this on profile
`export NNN_PLUG='o:_sxivpic $nnn*'`

but now it's not working, please help. thank you.

**Comment by jarun** [comment]
NNN_PLUG spec has changed. See plugins docs.
