### ISSUE TITLE
A way to see file/directory owner

### ISSUE THREAD

**Issue by alandiwix** [jarun/nnn#1250]
Is there currently any way to see owner of file/directory? I believe there was, but can't find it now. Permissions without uid/username mean really little. I've seen some reasoning regarding username & groupname take more memory to look them up, but isn't just uid/gid cheap?

If there is no, that would be a feature request.

**Comment by N-R-K** [comment]
The `-U` flag is probably what you're looking for.

**Comment by alandiwix** [comment]
Isn't it more expensive than uid:gid?

**Comment by luukvbaal** [comment]
There is little difference in the memory cost between uid:gid vs user:group since we use a oneshot cache to lookup the user:group; it is not stored.

I think the performance difference is negligible which is why we show the user:group which imo is much more useful than uid:guid.

I think the main reason why we don't show it in the detail view is because it adds 2 new variable width columns which doesn't work well with the default implementation. 

There is also the [namefirst](../tree/master/patches/namefirst/mainline.diff) patch that does print the user:group information in the detail view and takes into account all the variable widths.

**Comment by jarun** [comment]
We have multiple ways to get this information already. Closing the issue.

**Comment by 4l1fe** [comment]
> The `-U` flag is probably what you're looking for.

Where is this flag ?
```
❯ n -h
usage: nnn [OPTIONS] [PATH]

The unorthodox terminal file manager.

positional args:
  PATH   start dir/file [default: .]

optional args:
 -a      auto NNN_FIFO
 -A      no dir auto-select
 -b key  open bookmark key (trumps -s/S)
 -c      cli-only NNN_OPENER (trumps -e)
 -C      8-color scheme
 -d      detail mode
 -D      dirs in context color
 -e      text in $VISUAL/$EDITOR/vi
 -E      internal edits in EDITOR
 -F val  fifo mode [0:preview 1:explore]
 -g      regex filters
 -H      show hidden files
 -i      show current file info
 -J      no auto-proceed on select
 -K      detect key collision
 -l val  set scroll lines
 -n      type-to-nav mode
 -o      open files only on Enter
 -p file selection file [-:stdout]
 -P key  run plugin key
 -Q      no quit confirmation
 -r      use advcpmv patched cp, mv
 -R      no rollover at edges
 -s name load session by name
 -S      persistent session
 -t secs timeout to lock
 -T key  sort order [a/d/e/r/s/t/v]
 -u      use selection (no prompt)
 -V      show version
 -x      notis, selection sync, xterm title
 -h      show help

```

**Comment by 4l1fe** [comment]
> We have multiple ways to get this information already. Closing the issue.

Could you give a link to any? I also search for a way to display **owner, group, others**

**Comment by N-R-K** [comment]
@4l1fe what version are you using? Also if you compiled from source then ensure that `O_NOUG` is set to 0 in the Makefile.

https://github.com/jarun/nnn/blob/e44f8d3fccf16103a5b546a8c888ea799735ed4d/Makefile#L27

**Comment by 4l1fe** [comment]
> @4l1fe what version are you using? Also if you compiled from source then ensure that `O_NOUG` is set to 0 in the Makefile.
> 
> https://github.com/jarun/nnn/blob/e44f8d3fccf16103a5b546a8c888ea799735ed4d/Makefile#L27

```
❯ n -V
4.4
```
It's the static binary file. Should i compile it myself to enable the feature?

**Comment by 4l1fe** [comment]
Btw, the option only displays this info on the status bar, but i'd like to see it on each file line. So it's not what i'm looking for :disappointed:

**Comment by luukvbaal** [comment]
> but i'd like to see it on each file line.

The namefirst patch mentioned earlier in this thread provides that functionality. Compile with `O_NAMEFIRST=1` and enable detail mode (`d`), to check this out.

Otherwise, a plugin that runs something like `ls -l` is your next best option.

**Comment by 4l1fe** [comment]
> > but i'd like to see it on each file line.
> 
> The namefirst patch mentioned earlier in this thread provides that functionality. Compile with `O_NAMEFIRST=1` and enable detail mode (`d`), to check this out.
> 
> Otherwise, a plugin that runs something like `ls -l` is your next best option.

Great, much obliged.
