### ISSUE TITLE
Create addtoplaylist plugin

### ISSUE THREAD

**Issue by DRogueRonin** [jarun/nnn#1251]
Relevant issue: https://github.com/jarun/nnn/issues/866

Since it was mentioned here: https://github.com/jarun/nnn/issues/866#issuecomment-792276021

and described here: https://github.com/jarun/nnn/issues/866#issuecomment-792255362

I noticed that with my installation of mpv I could do the same without `umpv`, so there's no need for the extra step of getting and adding `umpv` to the `$PATH`.

I changed the player calling part to
```
cat $selection | xargs -0 mpv --player-operation-mode=pseudo-gui >/dev/null 2>&1 &
```

to get the same feel of opening single files per mpv when just hitting enter on a file.
The process is moved to the background with the appended `&`.

The only problem I have is that I have to quit out of `nnn` before closing the terminal or the mpv background process gets terminated as well.

I checked the `nuke` code, but I don't know what `nuke` does differently that you don't have to quit the `nnn` session first.

**Comment by jarun** [comment]
> I have to quit out of nnn before closing the terminal or the mpv background process gets terminated as well.

@0xACE any ideas in this?

**Comment by 0xACE** [comment]
Am I having a deja vu? I'm 100% sure I wrote a response to this post. I guess I didn't send my reply as I didn't want to take responsibility as the more thought I put into it.

#770 and #449 maybe relevant in terms of ownership of the process? How'd you get `enter` key to run `cat $selection | xargs -0 mpv --player-operation-mode=pseudo-gui >/dev/null 2>&1 &` ?

Also I doubt `mpv` does the same thing as `umpv`, unless they've added a new feature...

**Comment by DRogueRonin** [comment]
> #770 and #449 maybe relevant in terms of ownership of the process

Thanks, I'll look into that.

> How'd you get `enter` key to run

I guess my phrashing wasn't super spot-on.
What I meant was that when I just hit enter on the audio file, `mpv` with `pseudo-gui` set is run.
I wanted to replicate that with the plugin, that's all.
I'm calling the plugin on the selection to run the code, like normal.
I was checking here for inspiration and insight: https://github.com/jarun/nnn/blob/master/plugins/nuke#L116
I can't find where `nuke` is adding the `--player-operation-mode=pseudo-gui` parameter.

> Also I doubt `mpv` does the same thing as `umpv`, unless they've added a new feature

At least that's how `mpv` is behaving for me right now.
Maybe there's something going on with my configuration, but I thought I had all the default settings.

**Comment by DRogueRonin** [comment]
> I don't know what you are pursuing here

I guess I just wanted to add to the existing discussion, because for me the script works without adding `umpv`.
And then I stumbled upon the small problems above, including that `nnn` seems to open `mpv` with gui on my system for some reason and I just assumed that's the default lol

> If you got disgusted by my extra dependency

I wouldn't say I got disgusted 😆 
I just thought if it's working all the same without the extra dependency and save a few lines, why not

Thanks for your insights!

**Comment by 0xACE** [comment]
> I just thought if it's working all the same without the extra dependency and save a few lines, why not

Then what is the exact script you are running? So that a dev may try it out and see if we can reproduce the problem on our machines.

**Comment by DRogueRonin** [comment]
Of course, here is the script that I'm using right now:

```bash
#!/usr/bin/env bash

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
if [ -s "$selection "]; then
  nohup cat $selection | xargs -0 mpv --player-operation-mode=pseudo-gui > /dev/null 2>&1 &
else
  nohup mpv "$nnn" --player-operation-mode=pseudo-gui > /dev/null 2>&1 &
fi
```

The prepended `nohup` is something I noticed `nuke` is using when opening video files and I just tested it. This way you don't have to quit `nnn` before closing the terminal and the process keeps running.

When I first wrote the issue and tested it, it actually was just:

```bash
selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
cat $selection | xargs -0 mpv --player-operation-mode=pseudo-gui >/dev/null 2>&1 &
```

I installed `mpv` and `nnn` via pacman. I didn't change any configuration for both,
except for `nnn` of course where I set `export NNN_PLUG="p:addtoplaylist"`.

So I'm still assuming that `nnn` opening `mpv` with the gui on audio files when hitting `<Enter>`  is the default here, hence why I added that to the script, to be consistent with any expectations one could have.

**Comment by jarun** [comment]
@DRogueRonin sorry, I don't think we can help you further with this. Please continue your experiments and see if you can write a plugin that works without the issue you see.

I think there's an easy workaround - you can easily write a plugin that converts a selection to a playlist file and load that playlist in `mpv`.

**Comment by jarun** [comment]
> you can easily write a plugin that converts a selection to a playlist file

You don't need a plugin for this either. Just select some files, press <kbd>E</kbd> to edit the list in your editor and save it.

**Comment by badxnach** [comment]
This is the plugin I wrote for pushing a selection to mpv. It has an option to edit the temporal playlist file if I want to change the order of the files in it.


IFS=$'\n'
selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

if [ ! -s "$selection" ]; then
    printf "\n---No file selected "
    read
    exit
fi

arr=$(tr '\0' '\n' < "$selection")
printf "$arr">/tmp/tmpplaylist.m3u

printf "Edit Playlist (y/n) "
read -n1 editing

if [ $editing == "y" ]; then
    $EDITOR /tmp/tmpplaylist.m3u
fi

mpv --hwdec=auto --playlist=/tmp/tmpplaylist.m3u

if [ -p "$NNN_PIPE" ]; then
    printf "-" > "$NNN_PIPE"
fi
