### ISSUE TITLE
SFTP plugin for nnn?

### ISSUE THREAD

**Issue by usonianhorizon** [jarun/nnn#1253]
A feature I am seeking is to be able to interact with my SFTP server from within my TUI interface, especially when I have a lot of select/copy/move/mkdir actions to do.  Does anything like that exist for nnn?  Or is there a workaround that I have overlooked?

advTHANKSance.

**Comment by 0xACE** [comment]
Hello.

On linux if you have `sshfs` installed, `nnn` is capable of using `sshfs` to mount a remote server. I guess you invoke it with `c` and then it will mount the remote host at `~/.config/nnn/mounts/`

**Comment by usonianhorizon** [comment]
Thank you! I'll give that a try.

**Comment by usonianhorizon** [comment]
With FreeBSD 13, I had to use the following in order to make it work:

**Comment by usonianhorizon** [comment]
With FreeBSD 13, I had to use the following:

`export NNN_SSHFS="sudo sshfs -o allow_other"`

and when asked for `host[:dir] >` inside NNN, put in `<user>@<host>`

After which, I was asked for the local `sudo` password 3(!) times before being asked for the remote password by the sftp store.

I'm uncertain, as of yet, as to how to streamline this, but it does work and so it unifies my file explorer workflow.  I was looking at `termscp`, but wanted to keep my sftp requirements within NNN.

Thank you.

**Comment by 0xACE** [comment]
I'm unfamiliar with if FreeBSD does things different

My build has been diverged from `master` for many years now but i use this:

`.bashrc`
```bash
export NNN_SSHFS="sshfs -o follow_symlinks"
```

and `~/.ssh/config`

```
Host remotemachine
    HostName 169.0.0.1
    User remoteusername
    IdentityFile ~/.keychain/remotemachine-key
```

and in `nnn` i just `c` and type `remotemachine` and its prompting for that key password. the reason it asks for the password 3 times is most likely that you are writing the wrong password 3 times... also afaik `sshfs` should be able to run without the need of `sudo`

All of these things are related to `sshfs`, once you can run `sshfs remotemachine:/ /tmp/temporarymount` we can start trying it out in `nnn`. This is basically what `nnn` is doing, you have to fix your own config.

**Comment by usonianhorizon** [comment]
You are right: I do need to resolve sshfs from the command line because the command fails as regular user in exactly the same way.

The requirement for 3xpassword is consistent behaviour even on the command line, and is not mistyping.  It certainly is weird, and before I wrote it I was doubting it myself, and so made sure I wasn't making an obvious typo.  All references to sshfs point to being able to use as regular user, but I am being required to run with sudo even on the command line.

I should add that the remote username is *not* the same as my local username, and in fact the remote username doesn't exist on my local machine.  I wonder if that is part/all of the problem?

**Comment by usonianhorizon** [comment]
BTW, this is the error returned on the command line (as well as NNN) to the `sshfs` command:

`mount_fusefs: /dev/fuse on ~/.config/nnn/mounts/<mountpoint>: Operation not permitted`

Anyway, once connected I can happily `nnn` my way around, which is what I was looking for a solution to.

**Comment by jarun** [comment]
> Operation not permitted

This seems to be more of a local config issue. Maybe you need to enable non-admin users to do sshfs. Please check the config options.
