### ISSUE TITLE
Binary files coping into external program

### ISSUE THREAD

**Issue by timsofteng** [jarun/nnn#1254]
**Is your feature request related to a problem? Please describe.**

I want to pick files from nnn (e.g some photos) and paste it into external program (e.g discord chat). Current realization with `-x` doesn't provide this feature.

**Describe the solution you'd like**

It would be nice to have option to send selected files into global clipboard binary

**Additional context**

I'm using Linux, wayland.

**Comment by luukvbaal** [comment]
Check [here](https://github.com/jarun/nnn/tree/master/plugins#some-useful-key-command-examples) for an example of how to copy an image to clipboard. Other filetypes might be possible as well but I haven't looked into it.

**Comment by jarun** [comment]
Closing as there is a way to do this. Also, not directly an `nnn` issue.
