### ISSUE TITLE
Hide `preview-tui` plugin when editing a file

### ISSUE THREAD

**Issue by UtkarshVerma** [jarun/nnn#1256]
**Is your feature request related to a problem? Please describe.**

I am planning to use `preview-tui` plugin permanently. However, one issue I'm facing is the fact that the preview pane doesn't close even if I go to edit a file.

**Describe the solution you'd like**
When the user wants to edit a file(in vim), the preview pane should be hidden until nnn gains control of the terminal again.

>  Also, before exiting, `nnn` should close the preview pane itself as `tmux` closing the unclosed preview pane looks sloppy.

**Describe alternatives you've considered**
Maybe give the users an option to configure what happens when an edit/open action is invoked through *edit hooks*.

**Additional context**
![image](https://user-images.githubusercontent.com/31820255/146020667-c1a3d692-6ee7-4e49-8cad-d5380e06806b.png)

**Comment by luukvbaal** [comment]
> I _think_ the [restorepreview](https://github.com/jarun/nnn/tree/master/patches#list-of-patches) patch does what you're asking for.

Yeah it does.

> Also, before exiting, `nnn` should close the preview pane itself as `tmux` closing the unclosed preview pane looks sloppy.

What do you mean by this?

**Comment by UtkarshVerma** [comment]
Thanks for the quick reply. I tried the `restorepreview` patch but I still don't see any difference. Is there any way I can verify if it's working. I can confirm that the patch got applied during `make`.

![image](https://user-images.githubusercontent.com/31820255/146025551-f87e4e4a-ac58-418c-ac7b-378c727ba5be.png)


Regarding the other thing, when I close `nnn`, it exits first and the preview-pane exits just after that. This results in the terminal being blank for a short duration and it doesn't look good.
It's not a show-stopper but from UX point of view, things like this annoy me.

**Comment by luukvbaal** [comment]
Well, the patch writes `"close\n"` to the fifo path when editing a file. If you have the latest version of `preview-tui`, it will listen for this "opcode" and exit.

I agree it would be better in terms of UX but I doubt @jarun will welcome the required logic overhaul to the plugin system for such a use case.

**Comment by UtkarshVerma** [comment]
Apparently, the patch was working, well kind of.
The preview pane is properly hidden if I edit a Makefile or LICENSE file. But for some reason, it doesn't go away for Markdown or python files. Could you please let me know how I can get this to work.

**Comment by luukvbaal** [comment]
Is that screenshot with the patch applied? It looks like the preview pane is actually closed but vim is not resized. This could be due to the issue described in https://github.com/jarun/nnn/pull/1174. You could try increasing this sleep even further and see if it fixes it.

**Comment by luukvbaal** [comment]
https://github.com/neovim/neovim/issues/15044 https://github.com/neovim/neovim/issues/11330 these seem to be a relevant neovim issues. Perhaps we can get rid of the sleep when those issues are resolved.

**Comment by UtkarshVerma** [comment]
> [neovim/neovim#15044](https://github.com/neovim/neovim/issues/15044) [neovim/neovim#11330](https://github.com/neovim/neovim/issues/11330) these seem to be relevant neovim issues. Perhaps we can get rid of the sleep when those issues are resolved.
> 
> Edit: the suggested autocmd also seems to work fine for me without sleeping:
> 
> ```viml
> autocmd VimEnter * :silent exec "!kill -s WINCH $PPID"
> ```

This works well. Thanks

**Comment by UtkarshVerma** [comment]
@luukvbaal How do I hide the preview pane when I open a subshell? I tried sending the WINCH signal from within the subshell to $PPID, but it doesn't work.

**Comment by luukvbaal** [comment]
The patch is responsible for closing/opening the preview, sending WINCH won't do anything by itself. 

I guess it makes sense to also close/restore the preview-pane for subshell. I'll check if it isn't too much of a hassle to add to the patch.

**Comment by UtkarshVerma** [comment]
Thanks. Please ping me on updates.
