### ISSUE TITLE
GIF preview not working for `preview-tui`

### ISSUE THREAD

**Issue by UtkarshVerma** [jarun/nnn#1260]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Void Linux
- [x] Desktop Environment: None (dwm)
- [x] Terminal Emulator: st
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable): None
- [x] Program options used: -e -P p (preview-tui)
- [ ] Configuration options set:
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. Browse to a gif.
2. Expect the preview to be drawn, but nothing happens

#### Observations
I tried reading the `preview-tui` script and can ensure that the gif is converted to a sequence of images in `/tmp/nnn/previews`, however the processed jpeg images fail to display for some reason without any error. It's not an issue with `ueberzug` because I can preview JPEGs and PNGs just fine.

Here's the behaviour:
![preview-tui-bug](https://user-images.githubusercontent.com/31820255/146501188-77c8ebfa-309f-4486-b3ab-94a0d3f8fcca.gif)

**Comment by luukvbaal** [comment]
Could you share a gif that doesn't work for you? Works fine on my end.

**Comment by UtkarshVerma** [comment]
I tested again with different gifs and weirdly enough, these gifs are properly previewed. 
https://sample-videos.com/download-sample-gif-image.php

The GIFs which are having issues are ones which I got from GarticPhone. They open up fine on `sxiv` but preview fails on `nnn` for some reason. Here is a sample GIF which doesn't work for me.

https://user-images.githubusercontent.com/31820255/146652323-66f22645-2439-4028-abcf-c6288e59a3f6.gif

**Comment by UtkarshVerma** [comment]
I found the bug! The preview doesn't handles spaces within folders properly.

![image](https://user-images.githubusercontent.com/31820255/146652541-00222548-f7aa-472c-b142-0d801cd8993c.png)

I changed my folder name from `Gartic Phone` to `Gartic` and it started previewing properly. This is reproducible.

**Comment by luukvbaal** [comment]
Thanks for finding the bug, #1263 should fix it. Please confirm.

**Comment by UtkarshVerma** [comment]
Thanks for the quick fix.
