### ISSUE TITLE
Cant get preview and image preview to work on Mac Os 

### ISSUE THREAD

**Issue by ZeroPie** [jarun/nnn#1262]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: macOS Monterrey
- [ ] Desktop Environment:
- [x] Terminal Emulator: iterm2
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Hi i want to get either viu or uberzug working in the preview pane, but i cannot even get the preview pane to open.
Plugins and live preview don't do anything when i toggle them.

zshrc
`
export NNN_COLORS='1234'
export NNN_PLUG='f:finder;o:fzopen;p:mocplay;d:diffs;t:imgthumb;v:imgview'
export NNN_FIFO="/tmp/nnn.fifo"
`

when i press ; and v nothing happens
![Screenshot 2021-12-17 at 19 14 50](https://user-images.githubusercontent.com/8741666/146624034-d5d168a0-4a1e-4ecd-a761-bc68d9b78adf.png)

compiling from source with icons doesn't work either.

**Comment by jarun** [comment]
imgview doesn't support `uberzug`. Does `viu` work for you independently?

Can you add a print in the `imgview` plugin to confirm if it's invoked at all? After you try to run the plugin, press `!` to go to the shell and see if the print is present.

**Comment by N-R-K** [comment]
Just to be clear, you're asking for "previews", right? If that's the case then you might be looking at the wrong plugin. Plugin for previews are `preview-tui` and `preview-tabbed`.

**Comment by ZeroPie** [comment]
@jarun thanks! 

You are right, uberzug is not compatible. Noted.
`viu` does work for me independently, the issue is fixed.
As @N-R-K noticed, i was simply using the wrong plugin! 
i added preview-tabbed and it is working now, really cool since it uses iterm2 tmux pane manager without one having to open a tmux session.

Thanks a lot.
