### ISSUE TITLE
nnn -x does not copy anything to the clipboard

### ISSUE THREAD

**Issue by danielittlewood0** [jarun/nnn#1265]
Hi - I suspect I am simply doing something wrong. The -x option for nnn does not seem to work at all for me.

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Gentoo linux
- [x] Desktop Environment: dwm
- [x] Terminal Emulator: st
- [x] Shell: bash
- [x] Custom desktop opener (if applicable): xdg-open
- [x] Program options used: -x
- [x] Configuration options set: 
```
NNN_USE_EDITOR=1
DISABLE_FILE_OPEN_ON_NAV=1
```
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I did an example - opening nnn in my home directory, and highlighting three files before quitting nnn. The debug log is attached. While nnn is running the file `$XDG_CONFIG_HOME/nnn/.selection` has the correct contents. But at no point are the contents of my clipboard changed.

[nnndbg_example.txt](https://github.com/jarun/nnn/files/7741047/nnndbg_example.txt)

**Comment by jarun** [comment]
Have you installed the plugins?

**Comment by danielittlewood0** [comment]
Oh :( I didn't realise the plugins were a prerequisite for this feature! It does work after running the install script. Happy to close.
