### ISSUE TITLE
Using `nnn` as a note-editor

### ISSUE THREAD

**Issue by UtkarshVerma** [jarun/nnn#1266]
Navigation and preview is really  concise in `nnn` which would make it a great note-taking TUI application. Being new to `nnn`, I wish to know how to do the following:

- Tell `nnn` not to let the user navigate up a directory. For example, allowing the user to only see contents inside `~/notes`.
- Create and rename files with a default extension. All my notes will be markdown.

**Comment by N-R-K** [comment]
> * Tell `nnn` not to let the user navigate up a directory. For example, allowing the user to only see contents inside `~/notes`.

I don't think this is possible. You can however start nnn in a given directory by specifying it in argument `nnn ~/notes`

**Comment by jarun** [comment]
This is the best you can have: https://github.com/jarun/nnn/wiki/Basic-use-cases#synced-quick-notes
