### ISSUE TITLE
Toggle auto-advance not working / confusing documentation

### ISSUE THREAD

**Issue by PatrickF1** [jarun/nnn#1268]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: macOS 12.0.1
- [ ] Desktop Environment: 
- [x] Terminal Emulator: iTerm2
- [ ] Shell: tested on bash, zsh, and fish
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set: -n
- [ ] Plugins are installed: fzcd
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Problem 1: + doesn't seem to change the behavior of type-to-nav
1. Execute nnn -n
2. Type to confirm directories auto-opened once unique match found
3. Escape and hit +
4. Directories are still auto-opening once unique match found

Based on https://github.com/jarun/nnn/issues/1209, I was expecting + to stop directories from auto-opening once unique match found.

Problem 2: no clarification on the meaning of auto-advance, auto-proceed, and auto-select.
These terms can all be found by grepping auto- in the manpage. They all sound very similar and yet they are mentioned without any explanation of what they do or how they are different. I also checked the readme, GitHub issues and the GitHub Wiki and still couldn't find anything. I would suggest adding some clarification in the manpages. e.g. for `-J` I'd rewrite it to `automatically advance cursor after making a selection`
Btw, having problem 1 still leaves me confused about the difference between auto-select and auto-proceed. Could you explain the difference please?

**Comment by N-R-K** [comment]
> Directories are still auto-opening once unique match found

You can use the `-A` flag to disable auto opening in type-to-nav mode.

> for `-J` I'd rewrite it to `automatically advance cursor after making a selection`

That's a good suggestion, would be an improvement over the current description.

> Btw, having problem 1 still leaves me confused about the difference between auto-select and auto-proceed. Could you explain the difference please?

`auto-proceed` seems to be the `-J` flag, which simply moves the cursor to next entry after making a selection. I don't remember what `auto-select` and `auto-advance` are off the top of my head.

**Comment by PatrickF1** [comment]
Thanks @N-R-K! So what is `+` supposed to do then?

**Comment by jarun** [comment]
@PatrickF1 `+` auto-advances to the next file when you open a file.

The _auto-advance_ and _auto-proceed_ terms mean the same and are based on the context. `-J` disables auto-proceed on selection, `+` enables auto-proceed on opening a file.

_Auto-select_ is for directories in type-to-nav mode. Maybe _auto-enter_ is a better term.

**Comment by jarun** [comment]
Documentation fixed in PR #1270.

**Comment by PatrickF1** [comment]
> @PatrickF1 + auto-advances to the next file when you open a file.

Ohhh gotcha. Interesting! Glad we fixed the docs.
