### ISSUE TITLE
Copying target of symlink?

### ISSUE THREAD

**Issue by usonianhorizon** [jarun/nnn#1273]
Is there a way of copying the target of a symlink rather than the symlink itself?  My use case is that I have a directory with mixed symlinks and files, which need to be copied to a UFD formatted as FAT32.  Both 'p' and 'w' commands fail for me, and I wonder if there is a technique that I am missing?

advTHANKSance.

**Comment by N-R-K** [comment]
I can't think of anything obvious of the top of my head, but I remember @KlzXS recently added ability to rename symlink target in the batch rename plugin https://github.com/jarun/nnn/issues/1214.

You might be able to use that for *moving* the symlink target, don't think it supports *copying* though.

**Comment by jarun** [comment]
None other that the one @N-R-K mentioned. No plans to do so either. You can easily have a pluhin that does that for a selection.

**Comment by N-R-K** [comment]
You might be able to create a "new" plugin by copying `.nmv` over and simply changing all the `mv` commands inside the script to `cp`.

Completely untested. DO NOT try this on any important files unless you're comfortable with shell scripting.
