### ISSUE TITLE
. should not toggle hidden files when in type-to-nav filter mode

### ISSUE THREAD

**Issue by PatrickF1** [jarun/nnn#1274]
**Is your feature request related to a problem? Please describe.**

In filter mode, typing the character of almost all other navigation and actions--e.g. space, `k`, `j`, `h`, `l`, `q`, `a`, `e`, `s`--results in the context filtering by that character instead of performing the action of that character. For example, most notably, typing space does not select but filters by space. However, typing `.` results in the toggling of hidden directories. This, IMO, is bad UX because
1) it is inconsistent with how all other navigation and action characters are treated in filter mode
2) people often want to filter by `.`off the bat in order to filter only hidden files
3) it is currently impossible to type something like `.config` into the filter

**Describe the solution you'd like**

When filtering mode, typing `.` should translate to filtering by `.`, not toggling the visibility of hidden directories.

**Comment by N-R-K** [comment]
Duplicate of https://github.com/jarun/nnn/issues/991 and https://github.com/jarun/nnn/issues/1187

You can use `\.` in regex mode. Though having some way to type literals like `.` in filter mode could be useful as well.

**Comment by PatrickF1** [comment]
Sorry for creating a duplicate! I should have searched harder / read the man page more thoroughly. I see in the other issues the suggestion was turned down. Would just like to point out that the prevalence of these issues might be a sign of bad UX. But either way, I still love nnn. Thank you everyone for maintaining it! I hope I am not coming across impolite or ungrateful--just trying to improve this because I love it.

**Comment by jarun** [comment]
Note that special interpretations are done only in _type-to-nav_ mode to speed up the process. A regular filter doesn't interpret these. And it's documented very clearly here: https://github.com/jarun/nnn/wiki/concepts#filters

**Comment by PatrickF1** [comment]
I see. Thanks for pointing that out and sorry I didn't read the docs closely enough. In that case, I'd like to make the point that type-to-nav's filter mode being different than normal mode's filter mode is counterintuitive. Also this makes type-to-nav less useful for me. But I understand you must've had your reasons for doing it this way and it'd be a big change, so just some food for thought!

**Comment by jarun** [comment]
It's muscle memory after you use the mode for a few days.
