### ISSUE TITLE
^ under the context and v above the file info

### ISSUE THREAD

**Issue by yymelau** [jarun/nnn#1278]
Hi, just started using nnn, it is lighting fast, really love it, thank you so much for all the efforts.

A minor problem, what do `^` under the context label (top of the picture) and `v` above the file info (bottom of picture) mean? 

I am just trying basic commands, and suddenly those symbols appeared, which were not there before. Any information about what did I do wrong or how to get rid of those?  Thank you!

![problem](https://user-images.githubusercontent.com/80661835/147546692-4096a77e-0956-43ef-855c-1179dc2d9e28.png)

**Comment by N-R-K** [comment]
It's just the scroll indicator. Funny timing, someone else mentioned this just yesterday: https://github.com/jarun/nnn/issues/1219#issuecomment-1001357368

**Comment by yymelau** [comment]
Hi, just let you know that, if I open a dir with many files, in another context, say `context 2`,
indicator `v` works as intended, but indicator `^` still (seems always) appears below `context 1`.

Also, I would also like to know if there is way to disable this "show-scroll-indicator-feature"?
