### ISSUE TITLE
DIR colour always seems to be bitwise OR'd with 0b1000?

### ISSUE THREAD

**Issue by usonianhorizon** [jarun/nnn#1279]
I've just spent some time trying to align my nnn colour scheme with my terminal (st) colour scheme.  It would appear no matter what I do, for DIR colour, I am only getting the bright ones, i.e., 08-0f; if specifying 00-07 the behaviour seems to be that the colour is OR'd with 0b1000.

Am I am dreaming?

I have noticed this with only DIR colours, but haven't tested extensively with all of the other elements of NNN_FCOLORS.

Ref: https://github.com/jarun/nnn/wiki/Themes

PS: I should have included the sample:

```
BLK="0b" CHR="0b" DIR="01" EXE="0d" REG="5e" HARDLINK="0c" SYMLINK="0c" MISSING="04" ORPHAN="04" FIFO="06" SOCK="0B" OTHER="06"
export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
```

**Comment by jarun** [comment]
Yes, that is correct. Dir colors are shown in bright:

https://github.com/jarun/nnn/blob/2eadf35fa0278cf007323e02dab70f1fd8552df9/src/nnn.c#L4113

You can disable bold text in the terminal (if it supports that) or just remove that line and compile the code. Another option is to use option `-C` to use the old color scheme.
