### ISSUE TITLE
BLK_SHIFT may be wrong in some platforms

### ISSUE THREAD

**Issue by fengyichui** [jarun/nnn#128]
In *sys/stat.h*, the macro `S_BLKSIZE` is the size of a block and its value not always 512 (eg: 1024 in Cygwin).
So the better way is to use `S_BLKSIZE`  instead of `BLK_SHIFT`.

**Comment by jarun** [comment]
Fixed at #128.

**Comment by jarun** [comment]
@fengyichui would you be interested in adding the package `nnn` to Cygwin?

Packaging docs: https://cygwin.com/packaging-contributors-guide.html
