### ISSUE TITLE
The instructions on "Configure cd on quit" are inaccurate

### ISSUE THREAD

**Issue by Pound-Hash** [jarun/nnn#1280]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Arch Linux x86_64
- [x] Desktop Environment: Sway 1.6.1
- [x] Terminal Emulator: Alacritty 0.9.0
- [x] Shell: fish 3.3.1
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Plugins are installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
In the `nnn` [README](https://github.com/jarun/nnn), step 3 of the **Quickstart** says to "_Configure cd on quit_."

The instructions to do that state,

> Pick the appropriate file for your shell from misc/quitcd and add the contents to your shell's rc file. You'll need to spawn a new shell for the change to take effect. You should start nnn as n (or your preferred function name/alias).
> ...
> To cd on quit always, export the environment variable NNN_TMPFILE set to your preferred file path.

On my system, `nnn` _cds on quit_, but I don't have any file from `misc/quitcd` and I haven't set `NNN_TMPFILE`. I do have the `n.fish` function though, and that's how I start `nnn`. So it seems we don't need to follow the instructions to get this working.

**Comment by jarun** [comment]
The function sets all of these inside. Current dir changes inside a function do not reflect outside.
