### ISSUE TITLE
Creating symlink with single selection drops to `[path/]name` prompt rather than `link prefix [@ for none]:` prompt

### ISSUE THREAD

**Issue by usonianhorizon** [jarun/nnn#1282]
I'm uncertain whether this is the intended behaviour, but it seems counterintuitive to me.  When I wish to create a symlink, regardless of how many files are selected, it seems that a consistent prompt is desirable.  With the `[path/]name` prompt one doesn't know to enter `@` for _no prefix_.  One might just be inclined to enter `.` for current path, which then (understandably) results in `entry exists`.

Would it not be appropriate to have line 7538:

`7538    messages[nselected <= 1?MSG_NEW_PATH:MSG_LINK_PREFIX]);`

read:

`7538    messages[nselected == 0?MSG_NEW_PATH:MSG_LINK_PREFIX]);`

I was really confused for a long while as I was expecting the revised prompt with the `@` recommendation until I started poking around in the code, which, of course, is just the type of rabbit hole programmers are susceptible to :).

Regards.

PS: I should have added that under FreeBSD 13.0, the installed pkg is at `4.2` which is where I got my muscle memory on expected behaviour.  When I tried to compile `4.4` from source I ran into this change of behaviour, which has confounded me all this morning.

**Comment by N-R-K** [comment]
This was changed due to: https://github.com/jarun/nnn/issues/1201
And while I see your point of view, I personally agree with the current design. It makes more sense to allow users to pick the name of the symlink if there's only 1 target. For multiple targets that cannot be done.

**Comment by usonianhorizon** [comment]
Thanks for the quick clarification.

Would it make sense to modify the prompt by concatenating `[@ for none]` for the single selection case?  If it is, I still don't know what would be an efficient way of doing that since the application of `messages[MSG_NEW_PATH]` is likely overloaded. 

Regards.

**Comment by usonianhorizon** [comment]
Okay, I have made a few small changes that solve my problem, but I don't know how to submit a candidate patch for evaluation.  it involves the addition of a couple of lines and modifying a single line in nnn.c:

`639  #define MSG_SNGL_TARGET  43`

`685  |   "[path/]name [@ for none]: ",`

(Line no. adjusted for insertion at line 639)

and modifying original line 3716 to:

`3718 |   if (choice == 'c' || ((nselected == 1) && (prefix[0] != '\0'))) {`

Would this be an acceptable change for upstream?  In my basic testing it covers both the case where you might want to specify the target, and if you simply want to enter `@` to indicate use the same file name as source.

Regards.

**Comment by jarun** [comment]
We can't keep making changes for prompts. Use and understand.

**Comment by usonianhorizon** [comment]
@jarun I completely understand the comment about modifying code just for the prompts, but my observed behaviour is that without the change to line 3709, even entering the usual `@` doesn't seem to work, i.e., there is no easy way to simply create a symlink for a single selection without having to type in the name of the target.  Am I missing something?

**Comment by N-R-K** [comment]
`@` is only applicable for multiple selection now. For single selection the "prefix" notion no longer exists, manually typing the name is necessary.
