### ISSUE TITLE
[preview-tui] add option for pdf text preview

### ISSUE THREAD

**Issue by sweenu** [jarun/nnn#1283]
Pdf image previews are a good thing with a terminal that supports graphics, but with half-blocks it's not as useful as you cannot read the pdf.

Therefore, it'd be a good thing to have an option to use `pdftotext` and preview the text of the pdf instead of the pdf itself.

**Comment by luukvbaal** [comment]
Be aware that the `ueberzug` option for preview-tui works regardless of whether your terminal supports graphics and displays the images in original quality. Closing as per #1284.
