### ISSUE TITLE
Restorepreview not working on subshell exit

### ISSUE THREAD

**Issue by UtkarshVerma** [jarun/nnn#1285]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Arch Linux
- [x] Desktop Environment: None
- [x] Terminal Emulator: st
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ x] Plugins are installed: Preview-tui
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. Start a subshell
2. Exit the subshell
3. Expect the preview to be restored.

This is the bug in action:
https://user-images.githubusercontent.com/31820255/148434846-08087554-61dd-4e38-8bce-af3862382ce8.mp4

**Comment by luukvbaal** [comment]
Can´t reproduce on maste and have no Idea why it wouldn´t work.

In the original PR you said it worked fine https://github.com/jarun/nnn/pull/1257#issuecomment-993787850. What changed?

**Comment by luukvbaal** [comment]
Have you changed `preview-tui` plugin name? The patch is hard coded to check for a plugin named `preview-tui`.

**Comment by jarun** [comment]
Closing the issue as no response.

**Comment by UtkarshVerma** [comment]
Sorry for the late response. This got off my mind.

> Can't reproduce on master and have no Idea why it wouldn´t work.
> 
> In the original PR you said it worked fine [#1257 (comment)](https://github.com/jarun/nnn/pull/1257#issuecomment-993787850). What changed?

I didn't test it thoroughly that time I guess. The plugin name is indeed `preview-tui`. I can still reproduce this on master.
1. Unset all NNN_* env vars
2. make O_NERD=1 O_RESTOREPREVIEW=1
3. NNN_PLUG="p:preview-tui" ./nnn -a
4. Open preview tui pane
5. Open subshell
6. Close subshell
7. Preview pane won't be restored and pressing `p` displays "failed!" at the bottom.

**Comment by luukvbaal** [comment]
Works as expected on my end with your reproduction steps.

Not sure what it could be, sorry.

**Comment by 0xACE** [comment]
output of
```
strings -a nnn | grep preview-tui
```
?

**Comment by UtkarshVerma** [comment]
This is what I get
![image](https://user-images.githubusercontent.com/31820255/149344195-4d364b65-3138-4ff3-a504-858ad90e53bb.png)

**Comment by UtkarshVerma** [comment]
Sorry for the trouble. It was a mistake on my end. I had a misconfigured "cd on exit" in my `.zshrc`. Restorepreview works just fine.
