### ISSUE TITLE
Current position reset after batch rename

### ISSUE THREAD

**Issue by menkaur** [jarun/nnn#1286]
#### Environment details (Put `x` in the checkbox along with the information)

- [ ] Operating System:
pop os
- [ ] Desktop Environment:
xmonad
- [ ] Terminal Emulator:
alacritty
- [ ] Shell:
fish
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Plugins are installed
- [ x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. Go to directory with bunch of files
2. Move cursor to file number 5
3. Press r to batch rename
4. Rename window will open and cursor will move back to line 0
5. Move cursor to file 5 again
6. Change a file name and close the rename window
7. The cursor position will be reset to 0

Desired behavior: cursor should not reset position after rename and be at the same position in batch rename view as it is in the navigation view

**Comment by N-R-K** [comment]
Batch rename simply opens in your `$EDITOR`. In order for the cursor the be at the same position as nnn, nnn will need to somehow tell that to the text editor. I don't think there's any universal way to communicate that which will work under all text editor.

**Comment by KlzXS** [comment]
> be at the same position in batch rename view as it is in the navigation view

As @N-R-K mentioned there is no way to support this feature across all editors out there.  There is nothing we can do about that. If your favorite editor supports what you are looking for it should be fairly easy to modify the code for your perticular case.

> cursor should not reset position after rename

Here is the problem with that.
Say you hovered over a file that got renamed. Where does nnn position the cursor?

* Over the same file with the new name which is now on a different row. Is that what most people would expect? What if it got moved outside the directory? While not in the name, you _can_ move files with batch rename.
* Over the same row. I think this is what you want, but will it make sense to others? And what if you moved some files into other directories and now that row is out of bounds?

As you can see there is no "obvious" place to put the cursor after an operation that can change the directory layout. And the safe thing is to place it at the top.
