### ISSUE TITLE
Render preview-tui correctly using kitty

### ISSUE THREAD

**Issue by fev4** [jarun/nnn#1293]
This is my `kitty.conf`
```
allow_remote_control    yes
listen_on               unix:@kitty
```

This is the config for `nnn` in `.zshrc`:
```
alias l="n -aeE"

export NNN_BMS="d:$HOME/Documents/;p:$HOME/projects/;D:$HOME/Downloads/"
export NNN_TMPFILE=${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastcd
export NNN_PLUG="j:autojump;c:fzcd;o:fzopen;d:dragdrop;p:preview-tui;f:fzplug;"
export NNN_FIFO=/tmp/nnn.fifo

source ~/projects/cmdline/nnn/misc/quitcd/quitcd.bash_zsh
``` 

But when I preview the output looks like this:
![Selection_364](https://user-images.githubusercontent.com/16828078/150697973-d8116c8b-6112-40fb-9cee-6a3ba4d4c7c1.png)

Basically it's not showing up correctly, the output is not rendering correctly.

What could I try to fix this? Any comment is appreciated

Additional environment context:
- Operating System: Manjaro i3 (Arch)
- Desktop Environment: i3
- Terminal Emulator: kitty
- Shell: zsh
- Program options used: -aeE
- Plugins are installed: yes
- Issue exists on `nnn` master: yes

**Comment by luukvbaal** [comment]
https://github.com/jarun/nnn/issues/1069

**Comment by fev4** [comment]
That's awesome. Thanks a ton
