### ISSUE TITLE
Support any of all trash cli [MacOS]

### ISSUE THREAD

**Issue by kuntau** [jarun/nnn#1296]
**Is your feature request related to a problem? Please describe.**

`NNN_TRASH=1` failed silently if I have different [`trash`](https://hasseg.org/trash/) binary. I think all the trash app use the same command `trash <file>`, so I'm not sure why it failed.

Also [dependencies wiki](https://github.com/jarun/nnn/wiki/Usage#dependencies) also not so clear which trash command it support since all of them have are `trash` and cli app

**Describe the solution you'd like**

Accept any of the `trash` binary

**Describe alternatives you've considered**

No other alternative since only one `trash` binary can be installed.

**Additional context**

Using [homebrew](https://brew.sh/), MacOS have at least 3 app for trash.

1. [trash](https://hasseg.org/trash/)
2. [macos-trash](https://github.com/sindresorhus/macos-trash)
3. [trash-cli](https://github.com/andreafrancia/trash-cli)

Personally I use the first option since that's what I've installed for years. It would be nice if `nnn` could support all of them.

Thank you.

**Comment by N-R-K** [comment]
> Also [dependencies wiki](https://github.com/jarun/nnn/wiki/Usage#dependencies) also not so clear which trash command it support since all of them have are `trash` and cli app

It's specifically talking about trash-cli, the 3rd one in your list.

> It would be nice if nnn could support all of them.

Not sure if anyone here is using mac, so feel free to open the PR.

Related issue: https://github.com/jarun/nnn/issues/1168

**Comment by jarun** [comment]
@kuntau nnn doesn't offer abundant options. trash-cli is a very good choice. Of it doesn't support some specific feature you are looking for, contact the maintainers. If they don't add it, we can consider an alternative for macOS.
