### ISSUE TITLE
Icon on desktop file should be absolute path

### ISSUE THREAD

**Issue by CrossNox** [jarun/nnn#1297]
I just found the instructions [for installing the .desktop file](https://github.com/jarun/nnn/wiki/Advanced-use-cases#desktop-integration). However, the icon shown on rofi is not the cute horsey, but rather a folder with "nnn" written on it.

I think [this line](https://github.com/jarun/nnn/blob/e67587204b8ee41766ad8339e73305f3a234a413/misc/desktop/nnn.desktop#L7) should be changed to:

```
Icon=/usr/local/share/icons/hicolor/64x64/apps/nnn.png
```

Or at least, that got it working for me. Before opening a PR I wanted a second look/opinion on this.

**Comment by N-R-K** [comment]
I don't think that's correct, users may install with other prefix, `make PREFIX=/usr`.

What's most likely happening is that `/usr/local/...` is probably not looked into by default and my guess would be that you need to set some XDG env var telling it to.

**Comment by N-R-K** [comment]
What's your `$XDG_DATA_DIRS` set to?

[The spec](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html) says it should default to `/usr/local/share/:/usr/share/` if unset or empty, so not sure why it's not working for you.

**Comment by CrossNox** [comment]
```bash
$echo $XDG_DATA_DIRS
/home/nox/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
```

I installed `nnn` through

```bash
make O_NERD=1
mv nnn $HOME/.local/bin/
sudo make install-desktop
```

If that's relevant

**Comment by CrossNox** [comment]
Found the issue, totally unrelated to nnn. Thanks!
