### ISSUE TITLE
Homebrew "tap" to Homebrew migration

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#13]
I installed nnn using the Hombrew tap:

`brew install jarun/nnn/nnn`

Now the tap is removed, and I can't install nnn from mainline Homebrew.

@zmwangx

**Comment by jarun** [comment]
Please run the following commands:

```
brew untap jarun/nnn
brew uninstall nnn
brew install nnn
```

**Comment by zmwangx** [comment]
`brew update` if install fails. For most users, a `brew update` is performed automatically when `brew install` is run.
