### ISSUE TITLE
Wiki improvement suggestion: cp mv progress for Linux

### ISSUE THREAD

**Issue by Yutsuten** [jarun/nnn#1301]
[Advanced use cases#cp mv progress](https://github.com/jarun/nnn/wiki/Advanced-use-cases#cp-mv-progress)

It took me some time to understand the meaning of this:

> Use the relevant program option to show the progress of the operations.

For a long time I just copied avdcpmv-patched binaries into my PATH and was expecting it to work, but it wasn't. Being straightforward, the sentence above didn't mean anything to me. Maybe it is just me.

Anyway, I think it would be better to change to something like:

> Also you must start nnn with the option `-r` to show the progress of the operations.

Thanks for creating nnn. This tool is awesome. :+1:

**Comment by jarun** [comment]
Fixed the wiki. Thanks!
