### ISSUE TITLE
8627: Permission Denied

### ISSUE THREAD

**Issue by pedrovivash** [jarun/nnn#1303]
**This post is stupid.** It's fixed with a restart, but I'm going to call it out just in case...

- [x] Operating System: _arch_
- [x] Desktop Environment: _none_
- [x] Terminal Emulator: _alacritty_
- [x] Shell: _fish_
- [x] Custom desktop opener (if applicable): _none_
- [x] Program options used: _the "n.fish" script. Some colors._
- [x] Configuration options set: _yes_
- [x] Plugins are installed: _none_
- [x] Issue exists on `nnn` master: **_?_**

#### Exact steps to reproduce the issue

1.  Login from TTY, run sway, open alacritty. I run a startup script for updates and patches...
2.  12 hours later.
2.  Run nnn or n. Receive Error:
3.  8627: Permission Denied
4.  Change to root
5.  Everything works as expected
6.  Return to unprivileged userspace. Try again with bash. Nope.
7.  Download x86_64 static binary "Tequila"
8.  Nope.

I'm not sure at all what it could be. I can say that I was up late 3 nights ago and in the middle of using nnn as root I switched to an unprivileged user and I noticed the error. I never had this issue before then.

Unrelated, but I did rebuild my OS in the interim, which I do sort of weekly.  However, I don't suspect that it's something to do with a change to the latest release of nnn... as the static bin is from November and I've been using the arch package just fine...

#### And then it was fixed

As IT Crowd taught me... 

1.  Restarted. Tried nnn from TTY as non-root and root. All good.
2.  _Ran sway and an XDG error came up. _
3.  WTF'd and logged out, logged back in. Ran sway. Good.
4.  Open alacritty, test nnn as root and non-root before and after startup script.
5.  Everything is back to normal.

I have no idea what I did in the last uptime of my system other than checking my email and updating the background opacity on alacritty (I know. It's pretty though.)

Now the saucy bits:

1.  I don't have this particular unprivileged user's home folder in /home. I read in another post this may be an issue with snap packages. User folders outside of where they should be will cause permissions issues with installs. Howsoever, I installed nnn as I always do, via pacman.
2.  Adjustments to gshadow and group were made, but nothing seemed to kick nnn back to life.
3.  I also tried to chmod and chown the permission for this particular non-root user. Didn't work either.

#### Why post?

Looking at previous bugs, I don't see anything like what I came across personally so I felt like I had to track/post the error. I like this program. I assume other people do.

_I guess my main question is, why is my using nnn changing the way other programs act in sequence with it and vice versa?_

Maybe in the previous uptime, I somehow messed up my permissions for the local user, right? But in that instance, I tried every other app I have installed and none of them misbehaved. Since I don't _actually_ have a clue how nnn does what it does, or specifically how it interacts with xdg, I was a little concerned that the issue may be symptomatic of a bigger incompatibility that I, personally, need to patch for.

Can we close this now? Yeah. Some thoughts would still be great. Thanks.

**Comment by N-R-K** [comment]
Can you post all of your `$NNN_*` env vars?

**Comment by pedrovivash** [comment]
> Can you post all of your `$NNN_*` env vars?
> 
> ```
> $ env | grep "NNN_*"
> ```

NNN_TRASH=1
NNN=FIFO=/tmp/nnn.fifo
NNN_COLORS=2136

**Comment by N-R-K** [comment]
What's your `/tmp` permissions? Also do you still have the problem? If so, try running with `$NNN_FIFO` unset. I suspect your `/tmp` permissions was the issue, and nnn wasn't able to create `/tmp/nnn.fifo`.

**Comment by jarun** [comment]
@N-R-K it seems he doesn't have the issue anymore and he is unable to repro it as well.
I would say let's defer till we have a sure way to repro this. Closing accordingly.

**Comment by N-R-K** [comment]
Just leaving this here: trying to set NNN_FIFO to somewhere nnn doesn't have write permission results in the `permission denied` error message as well.

```console
[nrk ~]% NNN_FIFO=/root/nnn.fifo nnn
8633: Permission denied
```

So his `/tmp` permission somehow getting messed up seems to be most plausible situation.
