### ISSUE TITLE
Dragon (drag-drop) --and-exit flag

### ISSUE THREAD

**Issue by timsofteng** [jarun/nnn#1304]
Hello. How can I add --and-exit flag to existed `dragon` drag-n-drop plugin implementation?

**Comment by jarun** [comment]
What is this option supposed to do?

@0xACE

**Comment by N-R-K** [comment]
> Hello. How can I add --and-exit flag to existed `dragon` drag-n-drop plugin implementation?

look for all the `$dnd` variable and add it after that.

> What is this option supposed to do?

Auto exit dragon after a successful drop, iirc.

**Comment by timsofteng** [comment]
> What is this option supposed to do?
> 
> @0xACE

Exit dragon after successful action

**Comment by N-R-K** [comment]
Hmm, forgot about this issue. I can open a PR for it tomorrow. Instead of hardcoding the flag we can use an env var and use `--and-exit` as a fallback/default if the env var is unset.

Also one more thing, to avoid name conflict some distros renamed dragon to `dragon-drop` , https://github.com/mwh/dragon/issues/17#issuecomment-889878960 . We might want to take that into consideration as well.

**Comment by 0xACE** [comment]
Sry I need to arrange for github notifications to reach me without requiring me to access my own computer...

I dont see the point of going through additional modifications for the plugins. Imho `plugins/` is just a "inspiration template". I understand why the `preview` stuff are given attention, but they others may as well just be demos with sensible defaults...

Regarding all these hacks and what not: if you really want to serve beginners just add a `plugins/.pluginrc` where our `demo-scripts` source `.pluginrc` for setup, this allows for a version-persisting `.pluginrc` that survives `fetch-new-plugins` or w/e we call it.

Idk, it's just a thought...

**Comment by jarun** [comment]
@0xACE the problem is not too many users are familiar with dragon but they would love the functionality... specially users migrating from gui-land. So probably we can relax a bit on configuration as long as we keep sane defaults.

**Comment by N-R-K** [comment]
`.pluginrc` idea is interesting and could fix these configuration problem in the long run.

---

Anyhow, the dragdrop plugin is doing more than what I expected, there's also some drop/curl related things going on there. I don't think it makes sense to blindly add `--and-exit` everywhere, neither does it make sense to have some env var that's applied everywhere blindly.

So in this case I think it's best to just let users configure things themselves.

**Comment by jarun** [comment]
In that case, please add some indicative notes of the option based on this discussion. Top of the plugin file.

**Comment by N-R-K** [comment]
> In that case, please add some indicative notes of the option based on this discussion. Top of the plugin file.

Not entirely sure how to word it tbh, suggestions welcome.

```diff
diff --git a/plugins/dragdrop b/plugins/dragdrop
index 6ecb5c8..81facb4 100755
--- a/plugins/dragdrop
+++ b/plugins/dragdrop
@@ -10,6 +10,8 @@
 #      Some web-based files will be downloaded to current dir
 #      with curl and it may overwrite some existing files
 #   2. The user has to mm to clear nnn's selection first
+#   3. To avoid name-conflict, certain distros have renamed dragon.
+#      Thus we're using variable $dnd instead of directly calling dragon.
 #
 # Shell: POSIX compliant
 # Author: 0xACE
@@ -19,6 +21,8 @@ resp=f
 all=
 if type dragon-drag-and-drop >/dev/null 2>&1; then
     dnd="dragon-drag-and-drop"
+if type dragon-drop >/dev/null 2>&1; then
+    dnd="dragon-drop"
 else
     dnd="dragon"
 fi
```

**Comment by jarun** [comment]
I think we can remove 3 and just use the code.

**Comment by jarun** [comment]
As I understand PR #1313 fixes this.
