### ISSUE TITLE
Missing status info in empty directory

### ISSUE THREAD

**Issue by sylphenix** [jarun/nnn#1309]
- [x] Operating System: debian 11
- [x] Desktop Environment: i3wm
- [x] Terminal Emulator: xfce4-terminal
- [x] Shell: bash
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master

1. The status informations are missing when I enter an empty directory.
![misingInfo](https://user-images.githubusercontent.com/59789740/154393121-40e0e894-d75e-4dd6-a2e6-651397bd598f.jpg)

2. It is convenient to clear selection by double press 'm' key. But it doesn't work in empty directory.

===

**Comment by jarun** [comment]
Yes, the idea was not to do additional processing in empty directories and exit early.
No plans to change that.
