### ISSUE TITLE
How can I disable the middle mouse button in nnn?

### ISSUE THREAD

**Issue by sylphenix** [jarun/nnn#1311]
It looks that nnn will follow the text in the PRIMARY selection as keyboard action sequence, when I press the middle mouse button. It makes things uncontrollable even dangerous. If my last text selection start with "xy", when I accidentally press the middle mouse button in nnn, it will delete the current entry directly! Can I just disable the middle mouse button in nnn?

**Comment by KlzXS** [comment]
Middle mouse is bound to a user defined value (see https://github.com/jarun/nnn/wiki/Usage#keyboard-mouse). Check to see if you have `NNN_MCLICK` set.

**Comment by sylphenix** [comment]
> Middle mouse is bound to a user defined value (see https://github.com/jarun/nnn/wiki/Usage#keyboard-mouse). Check to see if you have `NNN_MCLICK` set.

Thanks. I have tried that just now. I found this problem just occur with xfce4-terminal, and NNN_MCLICK doesn't work with xfce4-terminal.
