### ISSUE TITLE
Unable to activate filter when list is empty

### ISSUE THREAD

**Issue by gzagatti** [jarun/nnn#1312]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Ubuntu 20.04
- [x] Desktop Environment: ubuntu:GNOME
- [x] Terminal Emulator: kitty and alacritty
- [x] Shell: zsh and bash
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: filter
- [ ] Configuration options set:
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Start a search with `/` untill you reach an empty list (ie. no matches, see image below). Press `ESC` to exit filter mode. After exiting filter mode on an empty list it won't be possible to activate filter mode again by pressing `/`. It is then necessary to clear the filter with `^L` to start a new search.

Sometimes, I will search for a path and end up typing something that drops me into an empty list. By then I will have pressed `ESC` and will not be able to come back to the search. Ideally, I would like to press `/` to activate the search again, delete the few extra characters that led to the empty list and find a match again. This is sometimes easier than re-starting the search.

![image](https://user-images.githubusercontent.com/11043156/154491016-7e2db750-34aa-47a3-a08f-d440a32d6f13.png)

**Comment by N-R-K** [comment]
> Unable to activate filter when list is empty

I think this behaviour is intended and was introduced in https://github.com/jarun/nnn/commit/d40dbfd69ab074ae4ff4815ceacb8d437b6f6b84 .

I personally have the commit reverted on my local build. But even if you revert it, reactivating filter will just give you an empty filter with an empty list. So you'll have to <kbd>ctrl+l</kbd> and start over anyways.

**Comment by jarun** [comment]
Even if you activate the filter it won't help because we don't reload dir on pressing `/`.
I think when you are typing in filter prompt and the dir becomes empty, the best way to get everything back is to keep `Bksp` pressed. I mean I don;t understand why one would see that there are no results and still come out of the filter mode.

Anyway, I can't think of a simpler alternative in this flow and would leave it be.

**Comment by gzagatti** [comment]
Thanks. I updated the patch and got the behavior I wanted.

Ideally, I would not exit the filter prompt when the list is empty. But the reality is that my reflex is sometimes to press `Esc` in order to go through the result list as quick as possible. If there is a typo or something, it is too late to press `Bksp` because I have already existed the list. If I want to return to the list, I would rather press `/` again and delete everything with `Bksp`, then press `CTRL+L`, then `/` and then start typing again.

It is a bit like when designing a road. Engineers need to take into account the brake reaction time to determine where to place signs in the road.

**Comment by jarun** [comment]
I see what you are saying. You are not able to enable the filer key even when there are entries in the directory. Yes, we need to fix this. I am thinking of a way to differentiate between the cases where there are entries vs where the directory is really empty.

**Comment by jarun** [comment]
Reverted the change. Couldn't come up with a reliable alternative. Thanks for reporting the issue.
