### ISSUE TITLE
Allow passing multiple PATH arguments for `nnn` to open in each context. 

### ISSUE THREAD

**Issue by mamg22** [jarun/nnn#1316]
**Is your feature request related to a problem? Please describe.**

Currently, `nnn` allows the user to pass a `PATH` argument to set as directory/file for the first context, but there's no way to set the starting directory/file for the other contexts.

**Describe the solution you'd like**

Make `nnn` use positional arguments up to the maximum number of contexts to set up initial contexts, instead of just the first one:

```console
$ nnn somedir
Opens nnn as usual, with somedir as initial directory for context 1
$ nnn somedir otherdir
Opens nnn with somedir in context 1 and otherdir in context 2
$ nnn dir1 dir2 dir3 dir4
Opens dir1 in CTX1, dir2 in CTX2, dir3 in CTX3 and so on
```

**Describe alternatives you've considered**

I've considered creating some kind of session template, which is modified by a wrapper script and then loaded by `nnn`, but this seems too hacky and fragile to me.

**Comment by jarun** [comment]
No plans. Use bookmarks if you do that often. Thanks!

**Comment by mamg22** [comment]
I see, thanks anyway. btw, thanks for creating `nnn` and also `buku`, amazing and useful pieces of software :-)
