### ISSUE TITLE
Question: how to enable mouse clicks?

### ISSUE THREAD

**Issue by reportaman** [jarun/nnn#1317]
- Operating system and version: macOS 12.1
- Terminal emulator and version: iTerm2
- Locale: en_US.UTF-8

Mouse clicks don't work... My ``$TERM`` inside tmux is ``tmux-256color``, outside tmux is ``xterm-256color``. Both the terminfos have  ``kmous=\E[<``.

**Comment by N-R-K** [comment]
> Ranger version/commit: ranger 1.9.3

Ranger? Are you sure you're in the right issue tracker?

**Comment by reportaman** [comment]
Removed that line, sorry for confusion. Am in the right place, I want mouse clicks in  nnn running in tmux to work.

**Comment by N-R-K** [comment]
If you're environment is setup properly, mouse should work without needing to do anything. A couple possible reasons why it's not working, I can think of:

* Did you build nnn with mouse support enabled? It should be enabled by default but some packager might disable it. Try to compile from source and see it that works.
* What ncurses version are you using?
* You say you're terminal is iTerm but $TERM is `xterm-256color`, is that what iTerm typically defaults to or are you setting `$TERM` manually somewhere?

Also is mouse click working *outside* of tmux or is it not working anywhere?

**Comment by reportaman** [comment]
@N-R-K Thanks, compiling it from source makes the mouse work!!! Someone needs to update the home-brew ``nnn``, as I used ``brew install nnn`` and that didn't enable mouse. Now I need to figure the correct flags for configuration as nnn doesn't pickup neovim as the editor even if I do ``>>VISUAL=nvim EDITOR=nvim nnn``.

**Comment by N-R-K** [comment]
Try `nnn -e`, also check out the manpage. all the flags are listed there. As for homebrew, I think that's out of our control, you'll have to raise an issue on their repo.
