### ISSUE TITLE
Terminal Width and Horizontal Scrolling

### ISSUE THREAD

**Issue by gzagatti** [jarun/nnn#1319]
**Is your feature request related to a problem? Please describe.**

When the terminal width is too small compared to the file name, it is not possible to read the end of the file name. This is particularly important when files differ only according to their extension, eg. `foo.txt` and `foo.py`.

I usually face this problem when using `NnnExplorer` in neovim which opens a small vertical window for browsing files.

**Describe the solution you'd like**

It would be great to have a key that allowed the user to scroll left and right, much like in Vim. Alternatively, a key like `$` could just show the end of the file names.

**Describe alternatives you've considered**

Increasing the terminal width and when in Neovim increasing the window size. However, in Neovim it can be annoying to do that because I use `nnn` as a distraction-free file picker.

**Consider contributing**

Would the API allow for an extension that includes horizontal scrolling? Would that be something easy to implement?

**Comment by jarun** [comment]
@luukvbaal @N-R-K any ideas?

**Comment by N-R-K** [comment]
What do other FMs do in this situation? For example ranger, nerdtree etc.

Maybe just a keybinding which toggle showing the first/last part of the filename would be enough for this problem.

**Comment by jarun** [comment]
I really don't think it's a problem. We have the light mode with a single column that just shows the filename. It can be toggled using `d`. The extension is shown at the statusbar.

**Comment by gzagatti** [comment]
Just to illustrate my point. Here is what a Downloads folder could look like when opening `nnn` from Neovim with the `nnn.nvim` plugin via the `NnnExplorer` command. I believe the screenshot uses the light mode.

![image](https://user-images.githubusercontent.com/11043156/156479102-6e50b675-f6f3-4786-9489-561f3a2cbf1e.png)

There are two problems here:

1. The status bar is not fully visible, thus it is not possible to read the extension name. This is partly offset by the use of icon.
2. Some file names are too long and there is not even an indication that they are cut too short. For instance, the file `Attachments Rejected ` actually has a very long name `Attachments-Rejected Drafts for Submission.zip`. However because the file is broken right in the space character, I am not able to tell that this file has a longer name. A solution might be to rename files with short names. But this is not practical all the time.

If it would be possible to (1) indicate that a file is longer than shown and (2) allow the user to scroll horizontally, both problems would be solved. Perhaps this could be an optional feature. What do you think? Is it even possible for `nnn` to tell the width of the terminal? If so, I think it would be possible to implement such solution.

**Comment by jarun** [comment]
I think you can set the % of the total width for the explorer window/buffer. Please see the nnn.vim docs.

Also, did you try pressing `f` on the file? That the best I can offer at the moment.

Also, if this is really a problem, try the floating window which is wider.

**Comment by gzagatti** [comment]
I'm aware about adjusting the total width, but it's not practical in this case as I like to use `NnnExplorer` as an unobstrusive file drawer.

I use the floating window via `NnnPicker` when I need to immerse myself into the file system and look for files with previews, etc. So it does not quite fit the same purpose.

For now, I'll just use the `f` command, as it partly solves the issue. However, it would still not be possible to have a glance of all the files suffix in this manner.

If you want to try horizontal scrolling and see how it feels like, it is supported in `netrw` and `NERDtree`.

**Comment by jarun** [comment]
I can understand how it would be implemented. What you don't understand is - it's a lot of change and it takes time. We don't have that. Why don't you give it a try yourself?

**Comment by jarun** [comment]
I would suggest you stick to a tool that suits your needs.

**Comment by jarun** [comment]
Sure, feel free to reach out for any questions on implementation.

**Comment by N-R-K** [comment]
@gzagatti Scrolling is going to be tricky to implement (I presume). But this trivial patch should give you the last part of the filename.

```diff
diff --git a/src/nnn.c b/src/nnn.c
index 051905a..1360497 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -4198,10 +4198,12 @@ static void printent(const struct entry *ent, uint_t namecols, bool sel)
 	if (!ind)
 		++namecols;
 
+	size_t n = ent->nlen - 1;
+	n = n > namecols ? n - namecols : 0;
 #ifndef NOLC
-	addwstr(unescape(ent->name, namecols));
+	addwstr(unescape(ent->name+n, namecols));
 #else
-	addstr(unescape(ent->name, MIN(namecols, ent->nlen) + 1));
+	addstr(unescape(ent->name+n, MIN(namecols, ent->nlen) + 1));
 #endif
 
 	if (attrs)
```
