### ISSUE TITLE
[Preview-Tui] WSL2 preview window closes in less than 1 second

### ISSUE THREAD

**Issue by kalekume** [jarun/nnn#1320]
#### Environment details (Put `x` in the checkbox along with the information)

- [X] Operating System: W10
- [X] Desktop Environment: WSL2 - AlmaLinux 8.5
- [X] Terminal Emulator: winterm
- [X] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [X] Program options used: 
export NNN_FIFO=/tmp/nnn.fifo
export USE_PISTOL=1
export NNN_PLUG='f:finder;d:diffs;p:preview-tui;t:treeview'
export PAGER="less -RF"
export NNN_BMS="h:$HOME;c:/mnt/c;k:/k8s;p:/mnt/p"
export NNN_OPTS="aeQ"
- [ ] Configuration options set:
- [X] Plugins are installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

When I press the P key (preview-tui shorcut) the preview window is displayed very briefly (a few milliseconds) and then closes.  I have enabled the trace in the plugin by adding this command at the beginning of the plugin: set -x && exec 2>>/tmp/preview-tui.trace 

Pistol or bat works properly out of nnn. I have tried with bash instead of zsh, or not using pistol but I always have the same result, the window closes after a very short time.

[preview-tui.trace.txt](https://github.com/jarun/nnn/files/8205786/preview-tui.trace.txt)

![screenshoot](https://user-images.githubusercontent.com/63711967/157232164-39d882a0-f168-4df0-b0e2-50573ce38cdd.png)

**Comment by jarun** [comment]
We have several issues where we have seen the flicker due to keybinds or the FIFO not setup correctly. Please check the earlier defects and see if they solve the issue.

@luukvbaal @N-R-K

**Comment by kalekume** [comment]
Hi Jaraun,

thank you for your time.

Keybinds seem to be correct, I have deleted the rest of the keybinds assigned to plugins and assigned a new key only to preview-tui. The problem persists. I also started nnn with the -P option with the same result.

To configure the NNN_FIFO I followed the guide in Live-previews wiki: (echo $NNN_FIFO /tmp/nnn.fifo)
In the preview-tui.trace.txt file you can find more information. 

I really don't know where the problem could be. I have read the documentation in detail several times.

**Comment by N-R-K** [comment]
@kalekume try removing some/all of the stderr redirections (`2>/dev/null`) on the plugin. See if that catches anything interesting.

**Comment by luukvbaal** [comment]
Is your `preview-tui` executable?

**Comment by kalekume** [comment]
I just removed all stderr redirects (2>/dev/null) but no luck, no error message appears.

I have tried to rename the script from preview-tui to preview-tui2, but when I run it I get this error. Does this make sense?

![image](https://user-images.githubusercontent.com/63711967/157314990-f020be2d-e87b-41ec-8f25-3919e8c276e3.png)

**Comment by kalekume** [comment]
> Is your `preview-tui` executable?

yes.
I have no problem with same plugin unter WSL-Ubuntu 20.04 . I don't know why it doesn't work on AlmaLinux (distribution like rhel 8.5 or centos)

**Comment by kalekume** [comment]
the preview is displayed for a very short time

https://user-images.githubusercontent.com/63711967/157319958-48e7b458-8ac6-4f48-b743-f378901889aa.mp4

**Comment by luukvbaal** [comment]
I have no idea what would cause that sorry. The fact that it works under a different WSL distribution tells you that it is an environment issue. Try to match to the environment that works is all I can tell you.

**Comment by N-R-K** [comment]
> I just removed all stderr redirects (2>/dev/null) but no luck, no error message appears.

Are you sure; Could you add `set -x && exec 2>>/tmp/preview-tui.trace` and attach logfile again? We can maybe make some guess depending on where the script is exiting.

But yeah, as @luukvbaal pointed out; this smells like an environment related issue.

**Comment by kalekume** [comment]
I just found the problem, in WSL the script only works in the default distribution.

**Comment by jarun** [comment]
Thanks for sharing the info. Closing the issue with the above comment.
