### ISSUE TITLE
Bind additional mouse buttons

### ISSUE THREAD

**Issue by Grawp** [jarun/nnn#1322]
I do not use mouse often with nnn but when I do I miss functioning Back button.
It would be nice if additional mouse buttons (beside the basic three) could be bound to some actions in nnn.

Or if custom mouse bindings are not worthy of being added to nnn could we at least get functioning Back button? Basically every mouse except the most cheap ones has had Back button for at least a decade.

Thanks.

**Comment by jarun** [comment]
Do all mouses jave rhis button?

**Comment by luukvbaal** [comment]
Not all but I would say it is quite common. I think there is merit in mapping it to `SEL_CDLAST`.

**Comment by KlzXS** [comment]
I believe mouse back and forward are usually refered to as left and right scroll click. I think that most mice besides the cheapest office ones have that functionality, though most of the time I find those buttons hard to press.

**Comment by luukvbaal** [comment]
I'm not sure ncurses handles them though.

**Comment by KlzXS** [comment]
I don't think so either. Does ncurses support the extra function keys (F13 and onward)? If it does then maybe something like that can be hacked up on the user configuration side.

**Comment by N-R-K** [comment]
> I think that most mice besides the cheapest office ones have that functionality

if we're talking about "side-buttons", then in my experience even a lot of dirt cheap office mice have them now. They're typically bound to forward and backward in history in web browsers, so they can be handy at times.

> Doesn't seem like ncurses handles them though.

It's probably more related to how terminals handle keypress-es.

**Comment by KlzXS** [comment]
No, not the button on the side which you would press with your thumb. But button for which you tilt the scroll wheel. Are side buttons that common these days?

**Comment by N-R-K** [comment]
> But button for which you tilt the scroll wheel.

You mean pressing the middle button itself? Don't we already have an env var for it, `NNN_MCLICK` or are we talking about something else?

> Are side buttons that common these days?

They seem to be, I've seen them on even some cheap $2 chinise/taiwanise mices.

**Comment by KlzXS** [comment]
Like this: https://youtu.be/LfPJr3sPMR8
The wheel sits on top of 3 buttons.

**Comment by N-R-K** [comment]
> Like this: https://youtu.be/LfPJr3sPMR8

AHH, I see. Honestly the first time I'm seeing this.

**Comment by Grawp** [comment]
Just to clean up a potential misunderstanding: I'm not talking about side scrolling buttons.
Side scrolling buttons (basically pushing scroll wheel to one or other side) are (from my perspective) hugely impractical for going back and forth in history or folder structure, but most importantly I haven't seem them bound to such action by default anywhere.

I'm talking about those two thumb buttons almost every mouse seems to have and works in all webbrowsers and some filebrowsers across all platforms. In the video @KlzXS posted you can see those two thumb buttons.

I though that it is completely common but it's possible that I'm living in a particular sociotechnical bubble: All my friends and colleagues have those two mouse buttons and use them as far as I know.
Those buttons allows you to quickly go back (or up) without your hand leaving the mouse and switching back to keyboard.

Of course one really want to use keyboard most of the time with nnn but when one choose to use mouse I though it should work the same way all webbrowser works.. i.e. having functioning back and forth thumb buttons or at least the back button.

But I undestand that this is probably hugely subjective and perhaps may not be of worth to most of nnn users.

**Comment by pvx-** [comment]
I don't think there is a standard way to detect extra mouse buttons in console. You can configure mouse button actions in [st terminal](https://st.suckless.org) (including sending key(s) for buttonX click), maybe some other terminals allow this as well.

Also have a look at `imwheel`, it might enough for what you need (make button clicks in terminal window send keypress events).

**Comment by 0xACE** [comment]
My server's harddisk seem to have broken down so i can't access a full build atm, but i run something like this in my personal branch:

```
@@ -6733,15 +6204,20 @@ nochange:
                                goto nochange;

                        /* Handle clicking on a context at the top */
-                       if (event.bstate == BUTTON1_PRESSED && event.y == 0) {
+                       if ((event.bstate == BUTTON1_PRESSED && event.y == 0)
+                           || (sel == SEL_CLICK && event.bstate == BUTTON3_PRESSED)) {
                                /* Get context from: "[1 2 3 4]..." */
                                r = event.x >> 1;

                                /* If clicked after contexts, go to parent */
-                               if (r >= CTX_MAX)
+                               if ((r >= MIN(CTX_MAX_SEEN+1,CTX_MAX)) || (event.bstate == BUTTON3_PRESSED))
                                        sel = SEL_BACK;

```

iirc it's enough to let you use `right-click` to go up a directory, and it suffices for my needs...

a vanilla terminal is unlikely to support mouse4/5 (back/forth) so unless you do your own patching you wont get support for this...

**Comment by jarun** [comment]
Yes, licking on location to go back is very handy. Closing this defect with the code from @0xACE and the current keybind.
