### ISSUE TITLE
NNN preview-tui on Windows Terminal not working

### ISSUE THREAD

**Issue by desaixie** [jarun/nnn#1323]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Windows 11 WSL2 Ubuntu 20.04
- [ ] Desktop Environment:
- [x] Terminal Emulator: Windows Terminal 1.11.3471.0 and Windows Terminal Preview 1.13.10395.0
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [x] Configuration options set: NNN_PLUG='j:jump;p:preview-tui;i:imgview;l:!ls'; NNN_FIFO="/tmp/nnn.fifo"
- [x] Plugins are installed: all plugins
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Just started to use nnn. I have got plugins imgview and !ls work. Both jump and preview-tui only blink the terminal and do nothing. For preview-tui, if I start nnn inside tmux, preview-tui will work by showing the preview in a new pane.

**Comment by luukvbaal** [comment]
Make sure you have the latest version of `preview-tui`. Latest release (which is installed by `getplugs` unless `master` is specified), does not include the native windows terminal split support.

Are you saying when running inside tmux it will open a new WT pane, or a tmux tab instead of split? Not sure why either of those would happen tbh.

**Comment by desaixie** [comment]
With the latest version of `preview-tui` copied and pasted directly from this github repo, preview-tui is able to open a new WT pane and show previews inside it without tmux. However, directory preview is showing `ESC[01;34m` and `ESC[00m` before and after directory names. See example below. It seems to be because "[bash believes the prompt is longer than it actually is](https://unix.stackexchange.com/a/105974)". I am not sure how to fix this. Also, I have installed viu, but image preview inside preview-tui is not working, i.e. the preview is blank when an image is selected.

ESC[01;34m.ESC[00m
├── ESC[01;34m__pycache__ESC[00m/
│   ├── FullVggCompositionNet.cpython-37.pyc
│   ├── SiameseNet.cpython-37.pyc
│   └── __init__.cpython-37.pyc
├── FullVggCompositionNet.py
├── SiameseNet.py
└── __init__.py
(END)

**Comment by luukvbaal** [comment]
> However, directory preview is showing ESC[01;34m and ESC[00m before and after directory names

Searching the issue tracker should have lead you to https://github.com/jarun/nnn/issues/1069.

Don't quite remember which image preview options work on windows  but `viu`/`catimg` should work afaik, can't check at the moment (QuickLook is the only option that will give you original quality previews).
