### ISSUE TITLE
After exiting type-to-nav to enter it again hotkey must be pressed twice

### ISSUE THREAD

**Issue by Trismegistos84** [jarun/nnn#1324]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: MacOS Monterey
- [ ] Desktop Environment:
- [x] Terminal Emulator: Terminal
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: -QA
- [ ] Configuration options set:
- [ ] Plugins are installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. launch nnn
2. press ctrl-n to activate type-to-nav
3. input some directory name and press enter
4. press escape to exit type-to-nav

Now, if you try to enter type-to-nav mode again by pressing ctrl-n it won't work. You need to press ctrl-n twice.

**Comment by N-R-K** [comment]
> press escape to exit type-to-nav

Pressing escape doesn't "exit" type-to-nav mode, it just temporarily disables it. Once you enter another directory, type-to-nav will be auto restored.

Weather this is intended behavior or not, I'm not entirely sure. @jarun

**Comment by jarun** [comment]
This is the intended behaviour. Pressing `Esc` doesn't toggle type-to-nav mode. You have to press `^N` to toggle it.

**Comment by Trismegistos84** [comment]
That key sequence is very inconsequential first you enter nav mode with ctrl-n then you pause with each and then you resume with /. It would be consistent to resume it with same combination that starts it in first place.

**Comment by jarun** [comment]
I think you have missed the _toggle_ part.
