### ISSUE TITLE
how to show the overall size of the directory and all its contects?

### ISSUE THREAD

**Issue by AstroShen** [jarun/nnn#1325]
**Is your feature request related to a problem? Please describe.**

The size along with the directory is 4K all the time, which is of no use. People want to know the size of contents in the directory.

**Describe the solution you'd like**

When i have to know the size of directories, i have to `du -h -max-depth=1`.

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Consider contributing**

Please consider contributing the feature back to `nnn`.

Feel free to discuss in the ToDo list thread. We are more than happy to help.

**Comment by jarun** [comment]
nnn has du mode.
