### ISSUE TITLE
iterm2 "preview-tui" text color display error

### ISSUE THREAD

**Issue by JavaHello** [jarun/nnn#1326]
- [x] Operating System: Mac OS 12.3
- [ ] Desktop Environment:
- [x] Terminal Emulator: iterm2
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:

- [x] Configuration options set:
     ```sh
    # nnn
    export NNN_FIFO=/tmp/nnn.fifo
    export NNN_PLUG='p:preview-tui'
    export BAT_THEME=gruvbox-dark
    ```
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master

<img width="1673" alt="截屏2022-03-19 19 47 09" src="https://user-images.githubusercontent.com/24937965/159120138-8b3a0746-d667-419a-8026-b8e3d0e81522.png">

**Comment by luukvbaal** [comment]
Please see the relevant existing issues... https://github.com/jarun/nnn/issues/1069
