### ISSUE TITLE
Non-blocking actions?

### ISSUE THREAD

**Issue by starptr** [jarun/nnn#1328]
**Is your feature request related to a problem? Please describe.**

When deleting a file (for example), the tui visually hops over to the parent terminal until the deletion finishes and then hops back into the tui.

**Describe the solution you'd like**

Deleting a file shouldn't block the tui, i.e. I should still be able to do things in the tui while a file is being deleted.

**Describe alternatives you've considered**

The built-in windows explorer doesn't block and shows a progress bar pop-up while a file is deleted. The explorer window itself remains responsive.

**Additional context**

**Consider contributing**

Please consider contributing the feature back to `nnn`.

Feel free to discuss in the ToDo list thread. We are more than happy to help.

**Comment by jarun** [comment]
Even on the core-2 dou I am using now, deletion is not that bad and/or we don't keep deleting huge number of files at once.

What you are requesting is a lot of work with the need to have multiple threads working in parallel. We don't have the bandwidth.
