### ISSUE TITLE
Make file icons respect XDG user directories

### ISSUE THREAD

**Issue by emjayb** [jarun/nnn#1332]
Problem: After compiling `nnn` with `make O_NERD=1`, my self-defined XDG user directories appear as normal folders. For example, I defined `XDG_DOWNLOADS_DIR = $HOME/dl` (instead of the default `$HOME/Downloads`), but my `$HOME/dl` folder does not appear with a downloads icon. However, my "music" folder has a musical note in the folder icon.

Expected behaviour: `nnn` folder icons show also user-defined XDG user directories with special folder icons.

Possible solution: As many other filemanagers do, `nnn` could check XDG user directories (e.g. by querying `$XDG_CONFIG_HOME/user-dirs.dirs` or via the command `xdg-user-dir`) for special folder icons. The currently hard-coded folder names can be used as a fallback.

**Comment by jarun** [comment]
It's kind of hard-coded as you mentioned. You can set the directory name and the preferred icon here: https://github.com/jarun/nnn/blob/0a7742089a6ca3f832b4a63ae5d54a1b0962c9b3/src/icons.h#L65.
