### ISSUE TITLE
Open all files selected

### ISSUE THREAD

**Issue by muppi090909** [jarun/nnn#1333]
When working with many files or when you want to look at multiple files it is extremely tedious to open each one.

So is it currently possible or could the feature be added, which allows you to open all files selected by default and only open the one under cursor as a fallback?

I have considered making custom keybinds but there does not seem to be any variant *under the enum* for this.

**Possible ways to add this**

1. Add a variant under the actions enum
2. if this action is recieved then collect a list/vector of all selections
3. iterate over the selections and do something like xdg-open on these files
4. if not recieved but a open request was given then just open the file under cursor

**Comment by 0xACE** [comment]
something tells me you could just aswell make a script for this

**Comment by N-R-K** [comment]
Not sure if this is going to happen or not. If there's multiple files, how do we know what's the correct way to open it? Do we just give the program all the files as arguments in onde command: `opener file1 file2 file3 ...` or do we call the program for each file?

You suggested the latter, but this is pretty dangerous. For example if you have 100 images selected and invoke xdg-open on all of the selection separately, you might as well end up with 100 different image viewer window depending on what image viewer you're using.

---

On my system I use a custom opener via `$NNN_OPENER` and check for selection on images (that's the only thing where I need to open multiple files at once). So you can do something like this on your opener:

```sh
if [ -s "$NNN_SEL" ] && is_img "$1"; then # selection available and it's an image
  xargs -0 swallow nsxiv -s d -a < "$NNN_SEL"
else
  $opener "$1"
fi
```

The snippet above is edited a tad bit for clarity, but hopefully you get the idea.

**Comment by muppi090909** [comment]
> something tells me you could just aswell make a script for this
Do you mean an opener as @N-R-K has suggested or as a plugin?

**Comment by muppi090909** [comment]
>Not sure if this is going to happen or not. If there's multiple files, how do we know what's the correct way to open it? Do we >just give the program all the files as arguments in one command: opener file1 file2 file3 ... or do we call the program for each >file?

the correct way to open it doesnt matter as they would all be open in the end anyway.

>You suggested the latter, but this is pretty dangerous. For example if you have 100 images selected and invoke xdg-open on >all of the selection separately, you might as well end up with 100 different image viewer window depending on what image >viewer you're using.

That is the users choice to make. depending upon how they want to open it as suggested. They can open one-by-one or select them and open them all at once.

**Comment by muppi090909** [comment]
> Maybe we can have a script to do this?

If we do make a script for this then it should be added to the wiki. *basically how to write an opener*

**Comment by jarun** [comment]
> the correct way to open it doesn't matter as they would all be open in the end anyway.

No it's not a simple one-liner. Many programs don't accept multiple file-names as input.

Also, it really doesn't work for CLI things. As we do not know, whether we need to open a cli or a gui program, how do we ensure that we do not end up opening mpv multiple times with multiple files? There is no generalized approach.

> If we do make a script for this then it should be added to the wiki. basically how to write an opener

[nuke](https://github.com/jarun/nnn/blob/master/plugins/nuke)

How to access selection - [cmusq](https://github.com/jarun/nnn/blob/master/plugins/cmusq)

**Comment by muppi090909** [comment]
>No it's not a simple one-liner. Many programs don't accept multiple file-names as input.

>Also, it really doesn't work for CLI things. As we do not know, whether we need to open a cli or a gui program, how do we> ensure that we do not end up opening mpv multiple times with multiple files? There is no generalized approach.

unlike nuke instead use xdg-open which would capture *most* applications

**Comment by N-R-K** [comment]
> unlike nuke instead use xdg-open which would capture _most_ applications

nuke uses `xdg-open` as a fallback.

https://github.com/jarun/nnn/blob/0a7742089a6ca3f832b4a63ae5d54a1b0962c9b3/plugins/nuke#L495-L499

The problem here isn't which program to use, the problem is how to pass multiple files to that program.

> the correct way to open it doesn't matter as they would all be open in the end anyway.

It does matter, we don't want open up hundreds of windows and have people open bug reports complaining about that.

If you want to deal with multiple files, you'll just have to write a custom opener to deal with it correctly for your application of choice.

**Comment by jarun** [comment]
Guys, I am working on a plugin that would provide a flexible solution.

**Comment by N-R-K** [comment]
> this but not sure why the multiple select doesnt work. any pointers?

Three possible reasons I can think of:

1. Your variables such as `$file` and `$sel` aren't properly quoted. So it won't work on paths with spaces in them.
2. `$sel` is not correct if $NNN_SEL is defined. [This is how it should be done](https://github.com/jarun/nnn/blob/0a7742089a6ca3f832b4a63ae5d54a1b0962c9b3/plugins/dragdrop#L17).
3. `#!/bin/sh` `read` cannot deal with null separated items. You'll need to use either bash with `read -d $'\0'` or `xargs -0`

3 is most likely what's going on.

**Comment by jarun** [comment]
I wanted it to be POSIX, so this is what I have:

```sh
#!/usr/bin/env sh

# Description: open files in nuke one by one or in oneshot
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

sel=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
nuke="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/plugins/nuke"                                                             
XDG=0

printf "open [A]ll? "
read -r all 

openfile() {
    if [ "$XDG" -ne 0 ]; then
        xdg-open "$1"
    else
        "$nuke" "$1"
    fi  
}

if [ -s "$sel" ]; then
    files=$(tr '\0' '\n' < "$sel")

    for entry in $files; do
        openfile "$entry"
        if [ "$all" != "A" ]; then
            printf "open [n]ext? "
            read -r input
            if [ "$input" != "n" ]; then
                break
            fi
        fi
    done
fi

# Clear selection
if [ -s "$sel" ] && [ -p "$NNN_PIPE" ]; then
    printf "-" > "$NNN_PIPE"
fi
```

I want the user to confirm opening the next file, so either open all files one by one without confirmation OR press `n` each time to open the next.
Also, it can open both in `nuke` as well as the default desktop opener.
The capital `A` to open All is to really ensure the user wants to open 10 files at once.

Only issue I see is - filenames with spaces. Any idea how to fix that?

**Comment by N-R-K** [comment]
> Only issue I see is - filenames with spaces. Any idea how to fix that?

Maybe replace the for loop with a while read ?

```diff
-  files=$(tr '\0' '\n' < "$sel")
-  for entry in $files; do
+  tr '\0' '\n' < "$sel" | while IFS= read -r entry; do
```

**Comment by muppi090909** [comment]
Also after editing and cutting a bunch of things I dont need. I have come to
```
#!/usr/bin/env sh

# Description: open files with xdg-open
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana 
# Modified: Ishaan Subramanya

sel=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

openfile() {
    xdg-open "$1" &
}

if [ -s "$sel" ]; then
    files=$(tr '\0' '\n' < "$sel")

    for entry in $files; do
        openfile "$entry"
    done
fi
xdg-open "$1" &
# Clear selection
if [ -s "$sel" ] && [ -p "$NNN_PIPE" ]; then
    printf "-" > "$NNN_PIPE"
fi
```
It works flawlessly. Great job

**Comment by jarun** [comment]
Good to know it works for you. We are trying to work out something generic. Plugins are supposed to be examples that users can modify and use.

**Comment by muppi090909** [comment]
Also I just noticed that NNN_PIPE is not set can you tell me how to set NNN_PIPE?

**Comment by N-R-K** [comment]
> It opens the file under cursor. opens **one** selected file and the one under the cursor.

Most likely due to this: https://github.com/jarun/nnn/issues/1219#issuecomment-988453046

> Also I just noticed that NNN_PIPE is not set can you tell me how to set NNN_PIPE?

Are you using your script as a plugin or $NNN_OPENER ? NNN_OPENER doesn't get NNN_PIPE.

---

@jarun this dummy script seems to be working fine for me. The `echo` was needed for the same reason in here: https://github.com/jarun/nnn/issues/1219#issuecomment-988453046

```sh
if [ -s "$sel" ]; then
    { tr '\0' '\n' < "$sel" && echo; } | while IFS= read -r entry; do
        printf "filename: %s\n" "$entry"
    done
fi
```

**Comment by jarun** [comment]
I see the same issue with bash as well.

**Comment by muppi090909** [comment]
> Are you using your script as a plugin or $NNN_OPENER ? NNN_OPENER doesn't get NNN_PIPE.

Ah, yes right. I am using it as an opener.

**Comment by jarun** [comment]
Came up with this:

```bash
#!/usr/bin/env bash

# Description: open files in nuke one by one or in oneshot
# Uses nuke by default, set XDG=1 to use xdg-open
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

sel=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
nuke="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/plugins/nuke"
XDG=0

printf "open [A]ll? "
read -r all 

openfile() {
    if [ "$XDG" -ne 0 ]; then
        xdg-open "$1"
    else
        "$nuke" "$1"
    fi  
}

if [ -s "$sel" ]; then
    targets=()
    while IFS= read -r -d '' entry || [ -n "$entry" ]; do
        targets+=( "$entry" )
    done < "$sel"                                                                                                     
fi

for entry in "${targets[@]}"; do
    openfile "$entry"
    if [ "$all" != "A" ]; then
        printf "open [n]ext? "
        read -r input
        if [ "$input" != "n" ]; then
            break
        fi  
    fi
done

# Clear selection
if [ -s "$sel" ] && [ -p "$NNN_PIPE" ]; then
    printf "-" > "$NNN_PIPE"
fi
```
Needs some more fine-tuning but basic functionality works.

**Comment by muppi090909** [comment]
This suggestion has not been thought about much but it seems sensible.

Suggestion 1

I think as we have seen in the current conversation, it is difficult to debug openers and so I think that a way to debug should be added to debug openers *similar to the one in preview-tui*

Suggestion 2

If suggestion 1 eventually doesn't yield any help for this then I think an entry for how to write a basic opener should be added to the wiki and similar to the useful recipes in the end of the plugins similar useful recipes should be added *to the wiki*.

**Comment by jarun** [comment]
@muppi090909 we do not have infinite time to spend on trivial stuff. Go and read nuke and figure out how to write a basic opener. We do not have time to educate people in writing scripts.

**Comment by KlzXS** [comment]
> I would really love to avoid bash for this simple a script.

@jarun `xargs` can handle the case for opening all files easily. If you want confirmation before each individual file you could do something like `xargs -0 -I{} sh -c 'printf "Open \"%s\"?" "{}"; read -r resp </dev/tty; [ "$resp" = "y" ] && xdg-open "{}"'` keeping in mind you might need to start xdg-open in the background, I'm making no guarantees right now that this works.

@muppi090909 There is no guide for writing an opener. An opener should take a path, or in your case paths, and depending on the type of files/dirs that are passed to it determine which programs to invoke. How you do the determining and invoking is something only you can know since ultimately you are the one that knows the use case.

If what @jarun has written doesn't work for you or is removed for any reason try to write a plugin for the specific use case you need this feature for. You can always generalize it later. And keep in mind that it doesn't need to be a shell script. It might be easier to do all the processing in an actual programming language.

**Comment by jarun** [comment]
I have added further improvements in commit 44f234a536527e4ad50701929c68767feed57d2d.

**Comment by jarun** [comment]
Commit 47bc9de9a9903e72415e9b00db8d9bc08962f1de.

Now the user can use `openall` to open hovered file when nothing is selected.
