### ISSUE TITLE
flatten the file tree

### ISSUE THREAD

**Issue by Randalix** [jarun/nnn#1334]
I would like to "flatten the file tree" - Ignoring folder sturcture and just working on files.
Would be great if I could do that with:
`find . -type f -print0 | nnn`
Instead the folders are still shown.
If possible nnn should only list folder structures if they are piped to it.
But maybe a script/plugin could work too.

**Comment by jarun** [comment]
I think you are looking for `fzf`.

**Comment by Randalix** [comment]
Thanks for you reply.
I've solved the issue by piping to vim and constructing the command there.

**Comment by muppi090909** [comment]
Also adding another fix you could use the [finder](https://github.com/jarun/nnn/blob/master/plugins/finder) plugin which provides an interface for the ```find``` command in nnn
