### ISSUE TITLE
Is there a way to disable contexts ?

### ISSUE THREAD

**Issue by cancercufasole** [jarun/nnn#134]

**Comment by jarun** [comment]
LOL! People had been running after me for contexts!

No, there's no way to disable them. If you don't use contexts you wouldn't even notice them.

**Comment by cancercufasole** [comment]
dude, they're like right there at the left of the current path, how can you even not notice them

**Comment by jarun** [comment]
I am not adding flag checks to toy around with non-issues like printing (or not) 10 characters extra.

**Comment by cancercufasole** [comment]
How about if I make a feature request ? would that smooth things out ?
