### ISSUE TITLE
[Question] How to integrate vim terminal? Not floaterm's wrapper 

### ISSUE THREAD

**Issue by jqhr** [jarun/nnn#1343]
I like nnn and vim.When I use nnn in vim's terminal, I want to use nnn's environment such as $nnn or $d1, but in vim, it was none.
For example, I use nnn to cd some path, and I want to open an new terminal in this path. Floaterm's wrapper cannot solute it.I want an solution to integrate vim terminal.
I find [tmux](https://github.com/jarun/nnn/wiki/Troubleshooting#new-windowpane-using-cwd),  it is useful for me

**Comment by jarun** [comment]
I am not sure if that can be done without having a parent child relationship between nnn and vim.
I the best possible integration is the nnn.vim plugin.

**Comment by jqhr** [comment]
No, I have tried nnn.vim plugin. It has to many bug and does't have $nnn environment variable in vim.

**Comment by jarun** [comment]
No, we don't have any other options available for you. You can hack the code and export what you need.
