### ISSUE TITLE
Human readable sizes on ARM

### ISSUE THREAD

**Issue by BrainMaestro** [jarun/nnn#135]
Hi! Thanks for the amazing file manager. It got me to eventually dump ranger. 

I compiled the latest release `v2.1` on my raspberry pi 3, and it works great. Except that it does not work correctly when it encounters files above 2GB. This seems to point to some sort of overflow. Seems like `nnn` only supports 64 bit? The OS for this particular raspberry pi is 32 bit. Is this something that can be handled? If not, you can go ahead and close this. Thanks!

**Comment by jarun** [comment]
Please take a look at https://github.com/jarun/nnn/issues/42.

I believe we need a similar patch for 32-bit ARM. Can you please send a PR?

**Comment by jarun** [comment]
i have added a patch to handle this. Please test on latest master and confirm.

**Comment by BrainMaestro** [comment]
I was just about to make a very similar PR. Anyway, thanks! It works. I appreciate the quick response.
Quick question though, `__arm__` will not be defined for 64-bit ARM right?

**Comment by jarun** [comment]
Thanks for confirming. Nope, `__arm__` is for the 32-bit variant.
