### ISSUE TITLE
[FR] Document the -T option better + sort inside the filemanager

### ISSUE THREAD

**Issue by raffaem** [jarun/nnn#1352]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Fedora Workstation 35
- [X] Desktop Environment: GNOME 41.5
- [X] Terminal Emulator: kitty
- [X] Shell: bash
- [ ] Custom desktop opener (if applicable):
- [X] Program options used: -n
- [ ] Configuration options set:
- [X] Plugins are installed
- [X] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I was looking for natural sorting inside nnn. I found [this issue](https://github.com/jarun/nnn/issues/190), in which it was implemented with the `-n` option.

I tried to start nnn with the -n option but it didn't work as expected.

I looked up the man page, and it looks like it got re-mapped to `-T v` sometime later on. 

But I have difficulty in understanding the different sort options:
```
     -T key
             sort order
             keys: 'a'u / 'd'u / 'e'xtension / 'r'everse / 's'ize / 't'ime / 'v'ersion
             capitalize to reverse (except 'r')
```

while I figure that `s` orders by increasing file size (?) and `t` by increasing time (? also, creation time? mod time?), and `v` is the natural sorting I need (I always called it "natural" sorting), I have no idea what `a`, `d` and `e` do.

Also, I think sort order should be changed inside the file manager, not by an option outside of it (if that makes sense).

**Comment by jarun** [comment]
au and du stand for apparent usage and disk usage. They are pretty standard terms. Please google.
e is to sort by extension. Please have a directory with files having different extensions and try it.
The time type (creation, modification change) can be changed with the key `T`.

You can change the sort order inside the file manager as well.

**Comment by raffaem** [comment]
ok, thanks.

Would it be really difficult to put "du=disk usage" and "au=apparent usage" for those of us not familiar with these standard terms? :(
