### ISSUE TITLE
Entering a bookmarks should enter the real folder, not .config/nnn

### ISSUE THREAD

**Issue by raffaem** [jarun/nnn#1353]
**Is your feature request related to a problem? Please describe.**

I bookmarked a subfolder `A/B/C` using the `B` keybinding.

When I enter that folder using the bookmark menu `b`, the bar on the top actually shows `./config/nn/bookmarks/NAME`, where `NAME` is the name I chose for my bookmark.

If I want to go up to the parent folder, I can't, because if I press `h` if will go to `./config/nn/bookmarks` not to `A/B`

**Describe the solution you'd like**

Show `A/B/C` on the top bar

**Describe alternatives you've considered**

Going manually to the folder

Making the bookmark to the parent folder

**Comment by jarun** [comment]
The implementation uses symlinks. The workflow you asked will break symlink navigation in general.

To achieve what you are asking for use the default method to create bookmarks i.e. define `NNN_BMS` in your shell's rc file.

**Comment by jarun** [comment]
@raffaem this is fixed at commit 3a50be93fdcedfbc166f8be403a39d76afbeffbc.

**Comment by raffaem** [comment]
> @raffaem this is fixed at commit [3a50be9](https://github.com/jarun/nnn/commit/3a50be93fdcedfbc166f8be403a39d76afbeffbc).

oh so it got modified. Thank you
