### ISSUE TITLE
Fix wiki link

### ISSUE THREAD

**Issue by rtix** [jarun/nnn#1354]
#### Issue
`instructions` link in [wiki/Advanced-use-cases#custom-keybinds](https://github.com/jarun/nnn/wiki/Advanced-use-cases#custom-keybinds) leads to non-existing [nnn#from-source](https://github.com/jarun/nnn#from-source)
#### Fix
Probably should lead to [wiki/Usage#from-source](https://github.com/jarun/nnn/wiki/Usage#from-source)

**Comment by N-R-K** [comment]
Fixed, thanks for reporting.
