### ISSUE TITLE
nnn-nerd-font static not working in 2 of 3 cases.   

### ISSUE THREAD

**Issue by altimmons** [jarun/nnn#1357]
#### Environment details (Put `x` in the checkbox along with the information)

- [ x] Operating System:  Slackware
- [ X] Desktop Environment: None- SSH from Windows
- [X] Terminal Emulator: Windows Terminal 
- [ X] Shell: ZSH
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Plugins are installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Using the *Precompiled NNN-nerd-static* and fwiw Icon Static, dont use nerdfonts or show the icons as expected.  Its the same outcome as issue #1026.  I was hoping to see this resolved.  

I am using NerdFonts.  They appropriately display on other applications- ColorLS and LSD for instance.  

I am not sure why these aren't working.  This particular machine isnt set to do compilation but I will try it on another.

Ok, I quickly tried it on a WSL instance.  It worked correctly in one perfectly.  In another that also utilizes the same setup, it does not work- I dont even get the Wide Char symbol.

Perhaps there is a term attribute that needs to be set.  Or some other TTY setting the application neeeds to make to indicate wide chars are forthcoming.  Its also odd the 3rd ignores it altogether

The latter 2 are Debian based,  all 3 have no GUI and only SSH or WSL access.  But have demonstrated working NerdFont Support

**Comment by N-R-K** [comment]
Are the icons simply not appearing or do you see garbage printed like #1026 ?

If it's the former then you need to ensure your terminal supports 256colors and has the proper terminfo entry.

**Comment by altimmons** [comment]
In  one case I see thr ~W, Where its attempting to show icons.  In another I see nothing at all (normal nnn)  and in a third it works. Also Could you make the instruictions more clear on how to get a side preview pane working.  I mostly want text files on the right hand side like in some pics.  And I cant get the .lastd logic to work.  I am very familiar with Linux.  But I struggle with these.Andy Sent from Mail for Windows From: N-R-KSent: Friday, May 6, 2022 2:45 PMTo: jarun/nnnCc: Andy Timmons; AuthorSubject: Re: [jarun/nnn] nnn-nerd-font static not working in 2 of 3 cases. (Issue #1357) Are the icons simply not appearing or do you see garbage printed like #1026 ?If it's the former then you need to ensure your terminal supports 256colors and has the proper terminfo entry.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by N-R-K** [comment]
> In  one case I see thr ~W, Where its attempting to show icons.

Not sure about this one.

> In another I see nothing at all (normal nnn)

Post the output of `echo $TERM`. Also what happens if you run `TERM=xterm-256color nnn` ?

**Comment by luukvbaal** [comment]
You probably mean the plugin `preview-tui` which provides file previews(and a sort of dual pane view with the right settings).

The dual pane setup requires either tmux or kitty terminal as mentioned in the plugin docs:
https://github.com/jarun/nnn/blob/4ddd048febef9e9098c8f5a19837a38c776b538b/plugins/preview-tui#L8

**Comment by N-R-K** [comment]
> In another I see nothing at all (normal nnn)

Can you try on a different terminal? If ncurses isn't able to detect that Windows Terminal supports 256 colors then icons won't work. Not much we can do here.

You need to make sure whatever configuration needs to be done on windows to make ncurses work properly is done. Specifically, look up anything related to `terminfo (5)`.

**Comment by jarun** [comment]
Try ConEmu or Putty (for WSL).

**Comment by altimmons** [comment]
WSL Works fine.  Its Slackware that doesnt.

**Comment by jarun** [comment]
Try the latest Emoji support if that's available on Slackware.

**Comment by jarun** [comment]
One of the the main reasons I wanted to have the support for Emojis in was the issues with the icons. I was using icons-in-terminal but I remember it was trouble setting up the first time. And nerd-fonts seems even more complicated to me as it's font-specific. So if Emojis work for you, don't even bother spending time on icons.

**Comment by jarun** [comment]
What are the program options you use? And please share a screenshot as well.

**Comment by jarun** [comment]
Closing this. No headway really.
