### ISSUE TITLE
Batch rename should use VISUAL instead of EDITOR

### ISSUE THREAD

**Issue by raffaem** [jarun/nnn#1358]
When you press `r` to batch rename, `nnn` seems to start the program in `$EDITOR`.

But `$EDITOR` may be set to `ed` or other line-based editor, and it will not receive the correct input.

`nnn` should look for `$VISUAL` first, and only if it is not defined roll back to `$EDITOR`.

As described for example [here](https://bash.cyberciti.biz/guide/$VISUAL_vs._$EDITOR_variable_%E2%80%93_what_is_the_difference%3F): "Almost all modern apps or bash would look for VISUAL first and then EDITOR".

**Comment by KlzXS** [comment]
I just tried it out and I see no issues there. What do you mean by "it will not receive the correct input"? It is reading what you wrote in the text file. If you enter nonsense it will execute the nonsense.

Obviously no one uses `ed` these days or knows how to use it, but that's a separate issue.

> As described for example [here](https://bash.cyberciti.biz/guide/$VISUAL_vs._$EDITOR_variable_%E2%80%93_what_is_the_difference%3F): "Almost all modern apps or bash would look for VISUAL first and then EDITOR".

Now, I'm not opposed to adding extra checks for `$VISUAL`, but I'd like a source for this claim. The website you linked seems to be dead. Its homepage last mentions 2017 and the owners personal webpage no longer exists.

**Comment by KlzXS** [comment]
Actually no. I _am_ opposed to checking for `$VISUAL`. As its name suggests it should store a visual editor. These days that can often be a GUI editor such as gvim, gedit, kate, even vscode. 

The problem I see is when you would `ssh` into a machine remotely as a user that has `$VISUAL` set to a graphical program or even run directly in tty. ssh/tty can't launch such a program and you'd have to unset the variable for that instance, which I would call rather annoying. And checking to see if the current environment is capable of launching a GUI program is rather beyond the scope of a _terminal file manager_.

**Comment by raffaem** [comment]
Well git-commit gives an higher priority to `$VISUAL` than to `$EDITOR` ([source](https://git-scm.com/docs/git-commit#_environment_and_configuration_variables)), wouldn't they have the same problem?

Other than that POSIX still defines the following editors:
```

**Comment by jarun** [comment]
Please use EDITOR. This is too trivial to configure at userland than pushing it to the application.
