### ISSUE TITLE
preview-tui requires KITTY_LISTEN_ON, but this is undocumented

### ISSUE THREAD

**Issue by raffaem** [jarun/nnn#1359]
When I activate `preview-tui` in my kitty terminal, it throws me the error:
```
$KITTY_LISTEN_ON not set!
Please read Usage in preview-tui.
```
Where is the "Usage" of preview-tui?

Because the [doc of the file itself](https://github.com/jarun/nnn/blob/master/plugins/preview-tui) doesn't tell me which value I should set for this variable, nor I could find anything in the wiki.

**Comment by N-R-K** [comment]
Seems documented to me
https://github.com/jarun/nnn/blob/4ddd048febef9e9098c8f5a19837a38c776b538b/plugins/preview-tui#L10

**Comment by raffaem** [comment]
Is `listen_on` the same as `KITTY_LISTEN_ON`? because the latter looked like an environmental variable.

If it is, then it doesn't work.

I have the following in my `kitty.conf`:
```
# For nnn preview-tui plugib
# see: https://github.com/jarun/nnn/blob/master/plugins/preview-tui
allow_remote_control yes
listen_on "unix:$TMPDIR/kitty"
enabled_layouts all
```

**Comment by raffaem** [comment]
ok I figured it out

1. You don't need the `"` in the `listen_on` directive
2. `TMPDIR` was actually undefined :)
3. CTRL+SHIFT+F5 won't work to refresh kitty configuration. You have to restart kitty

The KITTY_LISTEN_ON is indeed an environmental variable, but is created by kitty based on the config

**Comment by cain-dev** [comment]
Could you help me make this work please?  the way this documentation is written doesn't make any sense to me

**Comment by raffaem** [comment]
You have to put something like that in your `kitty.conf`:
```
# For nnn preview-tui plugib
# see: https://github.com/jarun/nnn/blob/master/plugins/preview-tui
allow_remote_control yes
listen_on unix:/tmp/kitty
enabled_layouts all
```
(notice the lack of quotes on `listen_on` contrary to what the doc says) and then restarts kitty.

**Comment by cain-dev** [comment]
my config:
allow_remote_control yes
listen_on unix:/tmp/kitty
enabled_layouts all

still not working, this is supposed to show images just like ranger? can you post a screenshot please?

**Comment by raffaem** [comment]
@cain-dev did you activate the plugin?

Type
```
export NNN_PLUG=p:preview-tui
```

in bash, call `nnn`, and then press `;` followed by `p`

**Comment by cain-dev** [comment]
yes

**Comment by N-R-K** [comment]
Saying "it doesn't work" is not useful information at all. If you want to be helped you need to provide proper information about your configuration and describe what *does* happen.

**Comment by cain-dev** [comment]
> Saying "it doesn't work" is not useful information at all. If you want to be helped you need to provide proper information about your configuration and describe what _does_ happen.

Ok, i was asking for his configuration to try it myself but lemme describe then

Running Arch on Wayland Session, Kitty Terminal and nnn

my environment:
export NNN_PLUG='f:finder;o:fzopen;p:preview-tui;d:diffs;t:nmount;v:imgview'
export NNN_FIFO='/tmp/nnn.fifo'

my kitty config:
allow_remote_control yes
listen_on unix:/tmp/kitty
enabled_layouts all

if i press ; and then p, the column shows, i can see previews for folders, text files, compressed files, but png just don't show on preview and jpg and video thumbnails show something like " ---- binary file ---- Jpeg image data, jfif standard...."

i have imv, mpv and ffmpegthumbnailer installed, do i need something else?

**Comment by N-R-K** [comment]
kitty has it's own image preview so i don't think you'd need to install anything else. try enabling the debug log and attach the log file.

https://github.com/jarun/nnn/blob/f6783c2065d9a584e67c2005718671fedeacbca6/plugins/preview-tui#L82

**Comment by luukvbaal** [comment]
ImageMagick is an optional dependency for the preview-tui script(and is mentioned). However, it seems to be a required dependency for the kitty icat script.

The kitty option is indeed not the fastest way to preview images, ueberzug is noticeably faster but is not available for wayland afaik.

**Comment by cain-dev** [comment]
"However, it seems to be a required dependency for the kitty icat script."
that's the problem then, this isn't on the documentation

Is there any way to speed up this process? Does creating a cache directory make any difference? If so how can i do that? I don't want to abandon the idea of ​​using nnn yet

**Comment by luukvbaal** [comment]
It's part of the kitty documentation.

    # Consider setting NNN_PREVIEWDIR to $XDG_CACHE_HOME/nnn/previews if you want to keep previews on disk between reboots

Follow this to keep a persistent cache which should speed up previews...

**Comment by cain-dev** [comment]
ok, lemme try

**Comment by cain-dev** [comment]
i have set export NNN_PREVIEWDIR='/home/cain/.cache/nnn/previews/' for envvars but no difference, do i need to do something else? edit something on the preview-tui? 

Is there any way to lower the quality of the preview images?

**Comment by luukvbaal** [comment]
```sh
NNN_PREVIEWWIDTH="${NNN_PREVIEWWIDTH:-1920}"
NNN_PREVIEWHEIGHT="${NNN_PREVIEWHEIGHT:-1080}"
```

You can set these. This should improve performance after the previews have been generated and cached by ImageMagick. But will likely increase the delay for new images.

**Comment by cain-dev** [comment]
tried, but at least for me it does not seems to work for .jpg, video thumbnails and pdf files

**Comment by raffaem** [comment]
Now it doesn't work for me again.

it shows images as binary files.

I have ImageMagick installed, both 7.0 (in `magick`) and 6.9 (in `convert`)
