### ISSUE TITLE
nnn prompts not functioning correctly on macOS

### ISSUE THREAD

**Issue by maximilianschmitt** [jarun/nnn#136]
Hi, I'm checking out nnn and on first impression it looks really awesome! :)

On macOS I'm having some issues when there is a prompt open to either change directory (`c`) or create a new file/dir (`n`):

- Backspace does not work
- ^-w to delete word backwords does not work
- ^-c does not exit the prompt
- No tab-completion for `c`

I've tested this on macOS Mojave with iTerm2 nightly with nnn running in tmux or directly in bash. I've also tested with the native macOS terminal and the same issues are present there.

My nnn **version is 2.0**

**Comment by jarun** [comment]
> Backspace does not work

This was fixed on master last night. The <kbd>Del</kbd> key was not being handled. You'll have to wait till the next release or you can just cook master.

> `^-w` to delete word backwords does not work

> `^-c` does not exit the prompt

The  [documented shortcuts](https://github.com/jarun/nnn#work-faster-at-rename-prompt) are implemented, but not all of the bash prompt shortcuts. No plans either.

> No tab-completion for `c`

> My nnn version is 2.0

The `chdir` prompt has been retired in version 2.1 which was released yesterday.
