### ISSUE TITLE
preview-tui and preview-tabbed not working on MacOS

### ISSUE THREAD

**Issue by EdLeafe** [jarun/nnn#1360]
Warning: I just installed nnn a few days ago, so super-n00b user.

OS: Monterey 12.3.1 on an MacBookPro 2019.

I have these two lines in my `.bash_profile`, and have confirmed that they exist as env vars:
```
export export NNN_PLUG='f:finder;o:fzopen;p:mocplay;d:diffs;t:preview-tabbed;v:imgview;p:preview-tui'
export NNN_FIFO='/tmp/nnn.fifo'
```
The plugins have been installed into `~/.config/nnn/plugins/`

When I run nnn it works fine, but when I press `;` then `p`, all I get is a quick flicker but no preview. I'm running in iTerm.

Reading the plugin source I saw that `tmux` was the preferred way to show the preview, so I tried running under tmux, but no change.

What should I look at to figure out what is wrong in my setup? nnn looks great, but the preview feature will really make a difference for me.

**Comment by EdLeafe** [comment]
I did try `-a`, but it didn't change anything. Same with `-e`. So now I just run plain ol' `nnn`.

**Comment by N-R-K** [comment]
Try enabling debug log, it should create a log file under `/tmp`.

https://github.com/jarun/nnn/blob/c23125ba500e468225727f6d0c096460aa023838/plugins/preview-tui#L82

**Comment by N-R-K** [comment]
Oh wait, you have duplicated `p` in your NNN_PLUG.

```
export export NNN_PLUG='f:finder;o:fzopen;p:mocplay;d:diffs;t:preview-tabbed;v:imgview;p:preview-tui'
```

Fix that and try again.

**Comment by EdLeafe** [comment]
Doh!

Yup, that was it. Thanks for the second set of eyes.
