### ISSUE TITLE
How to copy absolute path?

### ISSUE THREAD

**Issue by cgebbe** [jarun/nnn#1368]
Sorry for the super simple question, but how do I copy the absolute path of the currently selected element?  (using nnn v3.0)

Couldn't find anything in the help menu "?" or https://github.com/jarun/nnn/wiki , but instead only old threads with outdated links such as https://github.com/jarun/nnn/issues/592

**Comment by jarun** [comment]
You can still use the option `-x` to copy the path of the selected file to clipboard. You need to have the plugins installed.

You can also list the selection using the key <kbd>E</kbd> and copy from there.

**Comment by cgebbe** [comment]
Thank you for the quick answer! 

It honestly took me 30min to understand that `-x` is not a keyboard shortcut AFTER opening nnn, but instead you need to open nnn like `nnn -x`. And then selecting with e.g. spacebar automatically copies path to clipboard. Not to complain, but to help other unfortunate souls like me.

**Comment by lawnowner** [comment]
@cgebbe To help other unfortunate souls like you, you can raise PRs to this project for new features (or bug fixes) or documentation improvements, or host a set of nnn plugins in your own repo. nnn is feature-complete, but new plugins can be added unless they are trivial I think.

The path of the current entry is already available on the command line in a subshell or in plugins with the variables `$PWD`, `$nnn`, `$1`, `$2`, and also from inside nnn with `E` or `r` after selecting the entry. And, you can also use a simple plugin to copy the path:
```
# Copy the path of the current entry to the clipboard.
[ -n "$1" ] && printf '%s' "$2/$1" | xclip -sel c

# Copy NL-delimited paths of selected entries to the clipboard.
trap '[ -p "$NNN_PIPE" ] && printf "-" > "$NNN_PIPE"' EXIT
sel=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
[ -s "$sel" ] && tr '\0' '\n' < "$sel" | xclip -sel c

# Copy the base name of the current entry to the clipboard.
[ -n "$1" ] && printf '%s' "$1" | xclip -sel c

# Copy the dir name of the current entry to the clipboard.
[ -n "$2" ] && printf '%s' "$2" | xclip -sel c
```
