### ISSUE TITLE
Symlink destination key mapping / Bookmarks system rework

### ISSUE THREAD

**Issue by ggustafsson** [jarun/nnn#1369]
**Is your feature request related to a problem? Please describe.**

The symlink bookmarks system is very clever but I want to end up at the symlinks real destination instead of `~/.config/nnn/bookmarks/x`.

**Describe the solution you'd like**

Key mapping to open destination or bookmarks file instead of symlinks. The latter is more work but also more user-friendly, I have no need for a key mapping like this outside of the bookmarks context.

**Describe alternatives you've considered**

This kinda breaks bookmarks for me so I will continue use something else outside of `nnn`. A little bit unfortunate to not be able to replace everything with `nnn` 😉

**Comment by N-R-K** [comment]
> Key mapping to open destination

Sounds like you want to use `$NNN_BMS` instead then. https://github.com/jarun/nnn/wiki/Basic-use-cases#environment-variable-nnn_bms

**Comment by ggustafsson** [comment]
I've looked at `NNN_BMS` now and while it would indeed get me to the right destination in the end it is not a perfect solution in my case. Both ways have their use cases and the non-NNN_BMS alternative is the way to go for me.

But yeah since there are two alternative ways to work with bookmarks I have rethought this and ended up with the conclusion that a way to open up any symlinks real destination is the best solution. Is this possible already?

**Comment by N-R-K** [comment]
You can use the following patch, which I use on my local build. 

```diff
diff --git a/src/nnn.c b/src/nnn.c
index 492541b..526ae89 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -6905,7 +6905,8 @@ nochange:
 			}
 
 			pent = &pdents[cur];
-			mkpath(path, pent->name, newpath);
+			if (!realpath(pent->name, newpath))
+				mkpath(path, pent->name, newpath);
 			DPRINTF_S(newpath);
 
 			/* Visit directory */
```

This however causes some jarring UX when moving into a regular symlink directory. For example, if you're at `/x/y` and go into `/x/y/z` which is a symlink to `/a/b/c`, then going back with <kbd>h</kbd> will take you to `/a/b` rather than `/x/y`.

**Comment by lawnowner** [comment]
The real path of a bookmarked directory may be necessary; one may want to copy the path of a file under the bookmarked directory, or run a plugin that needs the nnn's exported variables to be the real path of the files. But the builtin bookmark system doesn't treat bookmark symlinks differently, which should be expected. A simple plugin that follows symlinks/hardlinks, or a more complicated standalone bookmark plugin that stores its bookmarks can be used:

```
# Changes the directory to the target if the current entry is a symlink.
[ -L "$1" ] && [ -p "$NNN_PIPE" ] && printf '%s' "0c$(readlink -n "$1")" > "$NNN_PIPE"

# Lists all hardlinks if the current entry is a hardlink.
if [ "$(stat -c '%h' -- "$1")" -gt 1 ] && [ -p "$NNN_PIPE" ]; then
  printf "%s" "+l" > "$NNN_PIPE"
  eval 'find / -xdev -samefile $1 -print0 2> /dev/null' > "$NNN_PIPE"
fi
```

**Comment by jarun** [comment]
This should work as you expect it to.

**Comment by ggustafsson** [comment]
@N-R-K Nice, but this would reverse the problem for me. Possibly even more inconvenient :upside_down_face:

@lawnowner Thanks for the tips! I will play around with both external bookmarks plugin and open plugin to see what sticks... :thumbsup:

@jarun Is this `n_` naming workaround confined to the bookmarks directory or is it global? :thinking:

**Comment by jarun** [comment]
Global. I don't see an issue with that.

**Comment by ggustafsson** [comment]
I don't think this is a good idea. Personally I don't often create symlinks namned `n_x` but I might and others might too. This is a bit weird and unexpected.

In addition to that it is not the most elegant solution to my little quirk either. I would much rather change the behaviour for all symlinks under `~/.config/nnn/bookmarks`. I can see that maybe not everyone would appreciate that though so I guess this would have to be a on/off setting or simply just a local patch on my end. I’m totally fine with dealing with this on my end through a patch or plugin instead.

**Comment by jarun** [comment]
> I don't think this is a good idea. Personally I don't often create symlinks namned n_x but I might and others might too. This is a bit weird and unexpected.

@ggustafsson I do see a blatant lack of appreciation for what I provided there spending my free time. Unfortunately I have a thing for these kind of single-minded conversations.

**Comment by jarun** [comment]
I intended to unlock the conversation. The issue is resolved.

**Comment by ggustafsson** [comment]
A little FYI to all readers... I didn't mean to come off they way I did. Me and Arun have cleared the air about it so all is good!

Regarding the latest patch it looks really great! I haven't tried it yet but I'm excited about it. I hope everyone else agrees. Thanks Arun! And thanks everone else for the good tips!
