### ISSUE TITLE
fish shell equivalent?

### ISSUE THREAD

**Issue by bobblkabb** [jarun/nnn#1370]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: void linux
- [x] Desktop Environment: wayfire
- [x] Terminal Emulator: foot 
- [x] Shell: fish shell
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [x] Plugins are installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

How do I get the nnn-preview working in fish shell?
[https://github.com/jarun/nnn/wiki/Live-previews](url)

**Comment by jarun** [comment]
Not sure why it wouldn't work. Do you mean you want the plugin to be written in fish script?

**Comment by bobblkabb** [comment]
I have to put the code into my config.fish file and some things work different in fish.

**Comment by luukvbaal** [comment]
The only think that you would potentially put into your config.fish file are the nnn environment variables required to setup the plugin.

I have no idea how those are defined in fish but if you need help with that you should look elsewhere... If that's not what you need help with please describe exactly what it is that you're running into when trying to setup the plugin.

**Comment by jarun** [comment]
Closing the issue as you should be aware of the shell you use.

**Comment by bobblkabb** [comment]
Then I have misunderstood the instructions. Where do I have to store the preview and setup commands?
