### ISSUE TITLE
nnn ignores $VISUAL , $EDITOR environment variables when set by .bashrc (always falls back on vi)

### ISSUE THREAD

**Issue by Tzatzikiiii** [jarun/nnn#1383]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Void Linux 5.15.41
- [x] Desktop Environment: i3-gaps
- [x] Terminal Emulator: st
- [x] Shell: bash
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: -Ee
- [ ] Configuration options set:
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. add the following lines to ~/.bashrc
`export $VISUAL="/usr/bin/vim"`
`export $EDITOR="/usr/bin/vim"`
2. reboot
3. (both variables show up via printenv and echo)
4. launch nnn `nnn -Ee`
5. try to edit a file with keyboard shortcut "E", observe vi instead of the chosen editor

However, manually exporting the variables in bash seems to work perfectly fine. It's annoying though since it's not temporary, of course.

(I'm still sort of new to Linux as a whole so I don't know if this has to do directly with nnn)

**Comment by luukvbaal** [comment]
If those are your actual exports you need to get rid of the `$` in front of `VISUAL` and `EDITOR`.

**Comment by Tzatzikiiii** [comment]
> If those are your actual exports you need to get rid of the `$` in front of `VISUAL` and `EDITOR`. But you say the variables show up so idk.

I did the exports without the '$' and just misspelled it above. BUT: i found the real reason it didn't work. An alias I have been using to start nnn was set without the program options, it just launched nnn without any options.... Silly little mistake

Please excuse the bug report and thanks for the help!
