### ISSUE TITLE
Vundle plugin install method

### ISSUE THREAD

**Issue by nickelchen** [jarun/nnn#139]
Hi, Would like to know how to install nnn's vim script via  [Vundle plugin manager.](https://github.com/VundleVim/Vundle.vim)
I tried to add this to `~/.vim/vimrc`
```
Plugin 'jarun/nnn', {'rtp': 'scripts/vim-plugin/'}
```
but with no luck.

Thank you.

**Comment by jarun** [comment]
@nickelchen please confirm if it works and close the defect if it does. Thanks!

**Comment by nickelchen** [comment]
@jarun @mcchrish Yes `nnn` has loaded and `:NnnPicker` is available in vim, issue closed. thanks.
