### ISSUE TITLE
preview-tui showing color codes instead of actual colors when using bat

### ISSUE THREAD

**Issue by risingtiger** [jarun/nnn#1390]
I am using preview-tui, which is working great. Its configured with kitty terminal on mac. I'm seeing image previews just fine. code files like .ts, .cpp etc WERE previewing just fine. But after installing the bat package I'n now seeing code file previews that show the ACTUAL color code instead of coloring the text. 

Here's a snippet of what's being shown:

 20 ESC[35mexportESC[0m ESC[35masyncESC[0m ESC[35mfunctionESC[0m ESC[34mReviewRunItESC[0m() 
  21 {
  22     ESC[35mletESC[0m catspers           ESC[35m=ESC[0m ESC[34mGetCatsESC[0m(ACCOUNT.PERS);
  23     ESC[35mletESC[0m catsrtm            ESC[35m=ESC[0m ESC[34mGetCatsESC[0m(ACCOUNT.RTM);
  24     ESC[35mletESC[0m catsall            ESC[35m=ESC[0m catspers.ESC[36mconcatESC[0m(catsrtm);

As you can see, its the color codes themselves that bat inserts into the stream.

Any ideas?

p.s. running the bat command in the kitty terminal shows the colorized preview of code files just fine

**Comment by ggustafsson** [comment]
Have you set the `PAGER` variable to anything? If so then `preview-tui` will not override it and you might be missing the `-R` flag for `less`.

https://github.com/jarun/nnn/blob/46a5092eee736c9edf4283dd20303f2d7d5c98b6/plugins/preview-tui#L88

```
-R or --RAW-CONTROL-CHARS
  Like -r, but only ANSI "color" escape sequences and OSC 8 hyperlink sequences are output in "raw" form.  Unlike -r, the screen appearance is maintained correctly, provided that
  there are no escape sequences in the file other than these types of escape sequences.  Color escape sequences are only supported when the color is changed within one line, not
  across lines.  In other words, the beginning of each line is assumed to be normal (non-colored), regardless of any escape sequences in previous lines.  For the purpose of keeping
  track of screen appearance, these escape sequences are assumed to not move the cursor.
```

**Comment by risingtiger** [comment]
I held off responding until I had a more concrete answer as to why the problem is fixed, but alas I don't. It is fixed for me and it had something to do with removing O My Zsh from my system. With that active, the problem persisted, with it gone, it vanished. I'm still digging through the exact reason as time permits

**Comment by luukvbaal** [comment]
Like @ggustafsson said, likely OMZsh exports the `PAGER` environment variable without the `-R` flag. This results in `preview-tui` using the predefined `PAGER` value when using OMZsh, as opposed to the `preview-tui` default when not using OMZsh.

Confirm this by typing `echo $PAGER` in either environment, and export `PAGER` yourself overwriting the OMZsh value if you want to keep using OMZsh.

**Comment by risingtiger** [comment]
That's it. Looks like OMZ is f**ing with the PAGER var. Good reason to leave O my zsh and not look back
