### ISSUE TITLE
Error when extract zip

### ISSUE THREAD

**Issue by vanarok** [jarun/nnn#1393]
- [ ] Operating System: Arch Linux
- [ ] Desktop Environment: Sway
- [ ] Terminal Emulator: Kitty
- [ ] Shell: zsh
- [ ] Custom desktop opener (if applicable):x
- [ ] Program options used:x
- [ ] Configuration options set:
``` 
export NNN_ARCHIVE="\\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$"
```
- [ ] Plugins are installed: x
- [ ] Issue exists on `nnn` master: x

#### Exact steps to reproduce the issue
1. Open zip
2. Press "x"
![2022-06-08T14:35:33,280959890+04:00](https://user-images.githubusercontent.com/6105977/172597066-47e2c3e6-e444-4d18-bd7e-b21190e6ed4b.png)

**Comment by jarun** [comment]
You do not have the deps installed. To use xdg-open use the "default" option when prompted.
