### ISSUE TITLE
Prepopulate prompt when archiving selection.

### ISSUE THREAD

**Issue by eNV25** [jarun/nnn#1395]
**Is your feature request related to a problem? Please describe.**

When you select a few files and then press `z` to archive them, the archive name input prompt is empty.

When you archive the current file, it is not empty.

**Describe the solution you'd like**

Prepopulate the archive name prompt with the current directory's name.

**Describe alternatives you've considered**

keep current behaviour

**Additional context**

**Consider contributing**

I am not sure of the correct way to get cwd in nnn code.

**Comment by jarun** [comment]
> Prepopulate the archive name prompt with the current directory's name.

What happens when you are under `/`?

**Comment by eNV25** [comment]
I think we should leave it to the user too. That's why the prompt is appropriate.

But it should be pre-populated with some useful value that you can change.

Also most archivers support adding files to an existing archive, we could do that as well.
