### ISSUE TITLE
display problem after quitting shell mode in Kitty

### ISSUE THREAD

**Issue by ixzh** [jarun/nnn#1397]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: MacOs
- [ ] Desktop Environment:
- [ ] Terminal Emulator:
- [x] Shell: Kitty
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Plugins are installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
enter `!` and quit `ctrl+d` shell mode, the display is not rendered properly like below:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/14981695/172987510-9fa200f6-fa4f-44aa-8a57-5be5a1d0972d.png">

should I report to Kitty as no such problem with ITerm2 or Alacritty.

**Comment by ggustafsson** [comment]
"should I report to Kitty as no such problem with ITerm2 or Alacritty."
Yes. nnn v4.5 + master works fine with latest Terminal.app too.

**Comment by jarun** [comment]
Doesn't look like our issue since other terminals work fine.
