### ISSUE TITLE
Browser MIME Problem

### ISSUE THREAD

**Issue by SushiWaUmai** [jarun/nnn#1399]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Arch Linux
- [x] Desktop Environment: dwm
- [x] Terminal Emulator: st
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Plugins are installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
When I try to open nnn via a web browser (pressing ctrl+o), it opens up a different file browser instead of nnn.

Also running this command gave me the correct output.
```bash
> xdg-mime query default inode/directory
nnn.desktop
```

Tested on Firefox, Brave (Chrome)

**Comment by jarun** [comment]
Please refer to https://github.com/jarun/nnn/wiki/Advanced-use-cases#browser-integration which is for Chromium.

**Comment by SushiWaUmai** [comment]
Whoops, seems like I missed something in the docs. Sorry for mistaking it as a bug.
I just read the wiki, this looks really hacky, is this really the only way you can enable this feature?

**Comment by jarun** [comment]
I personally use the terminal for most of my use cases.
