### ISSUE TITLE
Running inside docker container

### ISSUE THREAD

**Issue by shvchk** [jarun/nnn#1407]
Ok, this is probably some strange use case, but still : )

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Ubuntu 22.04, Debian 11
- [x] Desktop Environment: none
- [x] Terminal Emulator: konsole, kitty, xterm
- [x] Shell: bash
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: none
- [x] Configuration options set: none
- [x] Plugins are installed: none
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
- Create temp container (will be deleted after exit): `docker run --rm -it ubuntu:22.04` or `docker run --rm -it debian:11-slim`
- Inside container:
  - `apt update && apt install -y nnn`
  - `nnn`
  - No nnn interface, just blank screen with bash prompt
  - You can enter commands, but input is invisible, output somewhat works: `echo 1`
  - `Ctrl + D` or type `exit` to exit docker container
- Also, your terminal now behaves strange: mouse clicks or using mousewheel print characters to command prompt, so you have to kill terminal window / tab

**Comment by jarun** [comment]
Sorry. This is untested and unsupported. You are on your own.

**Comment by N-R-K** [comment]
A workaround for this was added to the wiki: https://github.com/jarun/nnn/wiki/Troubleshooting#running-inside-docker-containers
