### ISSUE TITLE
command not found for custom alias in plugin script

### ISSUE THREAD

**Issue by shuizhongyueming** [jarun/nnn#1410]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: macOS Monterey
- [ ] Desktop Environment:
- [x] Terminal Emulator: iTerm2
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [x] Configuration options set: $NNN_TMPFILE $NNN_PLUG $NNN_FIFO
- [x] Plugins are installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I want to change the `autojump` to make it work for [z.lua](https://github.com/skywind3000/z.lua)

Here is the plugin content:
```shell
#!/usr/bin/env sh


if [ ! -p "$NNN_PIPE" ]; then
    printf 'ERROR: NNN_PIPE is not set!'
    read -r _
    exit 2
fi

printf "jump to : "
read -r line
odir="$(z -I ${line})"
printf "%s" "0c$odir" > "$NNN_PIPE"
```
And this is my `nnn` config in `~/.zshrc`

```shell
export NNN_FIFO="/tmp/nnn.fifo"
export NNN_PLUG="p:preview-tui;t:preview-tabbed;z:autojump"
export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"


function n ()
{
    # Block nesting of nnn in subshells
    if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
        echo "nnn is already running"
        return
    fi

    # The behaviour is set to cd on quit (nnn checks if NNN_TMPFILE is set)
    # If NNN_TMPFILE is set to a custom path, it must be exported for nnn to
    # see. To cd on quit only on ^G, remove the "export" and make sure not to
    # use a custom path, i.e. set NNN_TMPFILE *exactly* as follows:
    #     NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

     nnn "$@"

    if [ -f "$NNN_TMPFILE" ]; then
            . "$NNN_TMPFILE"
            rm -f "$NNN_TMPFILE" > /dev/null
    fi
}

```

I can excute `odir="$(z -I ${line})"` in shell directly.

But when the `autojump` plugin called by `nnn`, it will throw an error: `z: command not found`.

If I change the comand in the quote to some other alias defined in my `~/.zshrc`, the alias is also not found.

Did I do something wrong in this?

**Comment by 0xACE** [comment]
why block nesting of nnn?

I have no idea of what you're doing but the hint is in the error message:

```
z: command not found
```

`nnn` isn't aware of any aliases, it's executing processes. You could put a `z` in your `PATH`

```
#!/usr/bin/env sh
/foo/bar/z.lua "$@"
```

**Comment by N-R-K** [comment]
Aliases are for interactive shell sessions and are not executable by other processes. This is not an `nnn` issue but simply how aliases work.

```sh
odir="$(z -I ${line})"
```

Change this line to call `z` executable directly, e.g `odir="$(/full/path/to/z.lua ...)"`.

**Comment by shuizhongyueming** [comment]
the `z.lua` is init with command:
```shell
eval "$(lua $(brew --prefix z.lua)/share/z.lua/z.lua --init zsh enhanced once echo fzf)"
```
in my `~/.zshrc`

Inner the `z.lua` script, it is defined a function `_zlua`, and command `z` is an alias of function `_zlua`.

I can use `z` or `_zlua` directly in shell, but can not use it in `nnn`'s plugin script.

And because `_zlua` is just a function, so it has no executable full path.

I have also test other alias defined in my `~/.zshrc`, they also **not found** in `nnn`'s plugin script

```
$ type z
z is an alias for _zlua
 $ type _zlua
_zlua is a shell function from /Users/dingmenglan/.zshrc
```

**Comment by N-R-K** [comment]
> I can use `z` or `_zlua` directly in shell, but can not use it in `nnn`'s plugin script.

It's not *just* `nnn`'s plugin script, they cannot be used in *any* script since they are shell alias and/of function.

You can maybe try to `source` the function into the script, but I'm not sure how `_zlua` is setup so don't know if it'll work or not.

**Comment by shuizhongyueming** [comment]
@N-R-K Thank you for the explanation, I did not know this before

I find another way to use `z.lua` in script, so I make some update to `autojump`，and I tested it in my compute. 

Here is the pull request #1414
