### ISSUE TITLE
Question: Change keysbinds WITHOUT recompiling

### ISSUE THREAD

**Issue by Quantlyx** [jarun/nnn#1422]
**Is your feature request related to a problem? Please describe.**

Is it possible to change keybindings (e.g ^g) without the need to compile it?

**Describe the solution you'd like**

If not alr there a keybind config.

**Comment by jarun** [comment]
No.

**Comment by Quantlyx** [comment]
> No.
So you are saying there is currently no option to edit the keybinds.
Or no as in: not gonna get implemented?

**Comment by jarun** [comment]
There's no option and there's no plan.

**Comment by Quantlyx** [comment]
Ok thank you!
