### ISSUE TITLE
Zathura inside the preview-tabbed doen't shows the epub it only shows pdfs

### ISSUE THREAD

**Issue by TheSafdarAwan** [jarun/nnn#1424]
#### Exact steps to reproduce the issue
Distro: Manjaro i3 community
Terminal: Alacritty i am using tmux
Shell: zsh
nnn version: nnn-nerd 4.5 
zathura: zathura 0.4.9
girara 0.3.7 (runtime: 0.3.7)
(plugin) ps (0.2.7) (/usr/lib/zathura/libps.so)
(plugin) pdf-mupdf (0.3.8) (/usr/lib/zathura/libpdf-mupdf.so)

i am heaving issue viewing the epub prviews in preview-tabbed in zathura it shows the pdfs perfectly i have installed the pdf extension for the zathura from arch community repo but does not shows the epub's previews

If i use zathura without the nnn preview-tabbed plugin it previews the epub book i dont think the problem is with zathura

**Comment by jarun** [comment]
`preview-tabbed` does not have support for epub files. Please modify the script (follow pdf handling) to handle epubs using zathura and it would work for you.

Plugins are indicative. Users may have to make minor changes to adapt to their use case.
