### ISSUE TITLE
Incorrect handling files with names that begin with a dash

### ISSUE THREAD

**Issue by 3JlOy-PYCCKUi** [jarun/nnn#1425]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: `Arch Linux`
- [x] Desktop Environment: `bspwm 0.9.10`
- [x] Terminal Emulator: `kitty 0.25.2`
- [x] Shell: `fish 3.4.1`
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [x] Configuration options set: 
`NNN_FIFO=/tmp/nnn.fifo`
`NNN_OPTS=dceoiU`
`NNN_ARCHIVE=\.(7z|bz2|gz|tar|xz|txz|tgz|zip)$`
`NNN_PLUG=z:autojump;d:dragdrop;f:fixname;c:fzcd;o:nuke;p:fzplug;g:organize;i:preview-tui;e:suedit;`
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. Create or rename any file, adding - in the beginning of the filename, for example `-930919.jpg`
2. Open nnn and navigate to that file, instead of filetype you will see error message.
3. Try to use `organize` or `dragdrop` or `wallpaper` plugin
	`organize` plugin will work for every file in dir, except for `-930919.jpg`
	`dragdrop` plugin doesn't work with this file
	`wallpaper` plugin also doesn't work with this file

**Comment by jarun** [comment]
I am not sure why you must have `-` in the filename. Please refer to https://www.cs.ait.ac.th/~on/O/oreilly/unix/upt/ch23_14.htm

And if you really want it, please raise a PR with the option `--` added. `man rm` has an example for you.
