### ISSUE TITLE
Sixel image previews using chafa?

### ISSUE THREAD

**Issue by UtkarshVerma** [jarun/nnn#1427]
Hi, I was just wondering if it would be possible to preview sixel images in the terminal using a tool like chafa. Because the current image previewer relies on tmux which doesn't support sixel. And over on the wayland side, ueberzug doesn't work.

**Comment by 0xACE** [comment]
The preview tools are just simple scripts, that you can replace yourself.

If you have a terminal multiplexer that supports `sixel` images, go ahead and adjust it.

Personally I only use the `tabbed-preview` for graphic related previews, and it works fine on my local machine

**Comment by jarun** [comment]
Please add it to your favourite preview plugin.
