### ISSUE TITLE
Unable to handle unicode character as keybinding

### ISSUE THREAD

**Issue by varuld** [jarun/nnn#1428]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Ubuntu 18.04
- [ ] Desktop Environment:
- [ ] Terminal Emulator:
- [ ] Shell:
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. In 'src/nnn.h' change keybind mapping;
"
      { 'l',            SEL_NAV_IN }
"
to;
"
     { 'æ',            SEL_NAV_IN }
"
2. run 'make', this will properly result in a compiler warning of 
"
src/nnn.h:139:4: warning: multi-character character constant [-Wmultichar]
  { 'æ',            SEL_NAV_IN },
"
3. run 'nnn -K',  results in segfault and 
4. key presses of 'æ' are not recognized in program

potential fix of including "<uchar.h>" in 'src/nnn.h' for unicode compatibility tried along with using unicode notation to represent the 'æ' e.g. 'U+00E6'.
Neither fixed to problem.
Tested on both version 4.5 and master.

**Comment by jarun** [comment]
I think we need to replace the `getch()` with `get_wch()`.

**Comment by jarun** [comment]
Please try with master and confirm if it works as expected.

**Comment by varuld** [comment]
> Please try with master and confirm if it works as expected.

I have now tried it and sadly the issue persists.

**Comment by varuld** [comment]
Further note:

I have tested the `{ L'æ', SEL_NAV_IN }` trick with version 4.5 and while it does not seg fault on `nnn -K` runs, it does not register the key press.

**Comment by jarun** [comment]
Sorry, I don't have a keybaord with Unicode and can't do much here. Probably try to debug the issue.

Obvious questions:

- what is the width of the character
- does any Unicode character work?

**Comment by N-R-K** [comment]
`sizeof` gives size in bytes, not bits. Besides it's not possible to have any type with less than 8 bits since C standard mandates *at least* 8 bit wide bytes.

**Comment by jarun** [comment]
I think he meant 4 bytes and 8 bytes.

With ncurses, it will not be possible to use 8 byte unicode keybinds. Thanks!

**Comment by jarun** [comment]
It is possible as per this thread: https://stackoverflow.com/questions/39090850/reading-ncurses-stdin-in-utf-8

However, I am not inclined to make any further changes. Thanks!
