### ISSUE TITLE
MAC issue: cp, mv, rm don't work - xargs: illegal option -- d

### ISSUE THREAD

**Issue by kjnez** [jarun/nnn#143]
`xargs:
 illegal option -- d
 usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
              [-L number] [-n number [-x]] [-P maxprocs] [-s size]
              [utility [argument ...]]
`
The above happens when I try to copy, move or delete a file. I'm using version 2.1 installed on a mac using Homebrew.

**Comment by jarun** [comment]
The code was tested on Ubuntu where options `-a` and `-d` are available: http://manpages.ubuntu.com/manpages/bionic/man1/xargs.1.html

But I see they are not on OS X: https://ss64.com/osx/xargs.html

I think we need to do the following here:

- Have a check for __APPLE__ and it's defined
  - `remove -d`
  - use cat to pipe our file

Would it be possible for you to send in a patch?

**Comment by zmwangx** [comment]
I'm afraid looking at immediate surrounding code doesn't give me an idea of what the code is doing (e.g., I'm not sure what this `g_cppath` is, and why both `-0` and `-d '\n'` are used, which are ostensibly conflicting), so it's hard for me to cook up a patch quickly.

In general, using coreutils or GNU's utilities as basis for cross-platform code is a very bad idea because they have a lot more options (I love coreutils, but still). Better look at FreeBSD/OpenBSD too, or even stick to POSIX. Here are my scripts for opening FreeBSD/OpenBSD/POSIX man pages:

`freebsdman`:

```sh
#!/usr/bin/env bash
if [[ "$1" == [12345678] ]]; then
    section=$1
    shift
fi

for topic; do
    open "https://www.freebsd.org/cgi/man.cgi?query=$topic${section:+&sektion=$section}"
done
```

https://www.freebsd.org/cgi/man.cgi?query=xargs

`openbsdman`:

```sh
#!/usr/bin/env bash
if [[ "$1" == [12345678] ]]; then
    section=$1
    shift
fi

for topic; do
    if [[ -n $section ]]; then
        open "http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man$section/$topic.$section"
    else
        open "http://www.openbsd.org/cgi-bin/man.cgi?query=$topic"
    fi
done
```

https://man.openbsd.org/xargs

`posixman`:

```sh
#!/usr/bin/env bash
for utility; do
    open "http://pubs.opengroup.org/onlinepubs/9699919799/utilities/$utility.html"
done
```

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/xargs.html

**Comment by jarun** [comment]
My problem is I don't own a Mac to test the patch. Anyway, I will have to wait till someone can send in a tested one.

For reference:

`g_cppath`: path to the file which has the list of (absolute paths of) selected files. The file paths are separated by newlines.

 `-0 and -d '\n'`: your code would be independent of the current one, so you can use whiever options you need (or not)

**Comment by jarun** [comment]
The file is delimited by EOF, if that's what you are asking.

The file is not written to every time a selection is made. The data is stored in an internal buffer and the final output is written to the file. This was done to reduce fs IOs.

Anyway, it's not a bother for now. I would have to wait for someone with a setup ready and willing to pitch in. Unfortunately (and it may sound strange to you) I don't have an extra minute to spare on anything non-urgent other than family at this time.

**Comment by zmwangx** [comment]
> The file is delimited by EOF

Not sure what you mean by that, EOF is not a character...

> The file is not written to every time a selection is made. The data is stored in an internal buffer and the final output is written to the file. This was done to reduce fs IOs.

That doesn't sound incompatible with NUL-delimitation?

> I don't have an extra minute to spare

No problem, fixing bugs on an open source project is not your job...

**Comment by jarun** [comment]
> Not sure what you mean by that, EOF is not a character...

What I meant is the file it terminated correctly but the filenames are separated by newlines.

> That doesn't sound incompatible with NUL-delimitation?

It's possible. I will test with a filename having newline in it and check this out.

> No problem, fixing bugs on an open source project is not your job...

True.

**Comment by zmwangx** [comment]
> filenames are separated by newlines.

Okay, yeah, that's an antipattern because paths could contain newlines. Should be NUL-delimited.

Consider three files, `foo`, `bar`, and `$'foo\nbar'`. Write `$'foo\nbar'`, use LF as delimiter, remove — bam, `foo` and `bar` are gone.

**Comment by jarun** [comment]
Yes, the issue exists. I have checked it out.

I would have to think of something that works with the system clipboard and doesn't write each file path to the copy file on every select.

I see the following on Ubuntu:

file:///home/vaio/GitHub/abc%0Adef

So they are actually encoding the filename. That can be done. And we would not have to write it to the file everytime.

**Comment by zmwangx** [comment]
I grokked the code a bit, and now I see what you're doing, and I sort of see what your dilemma is. Are you worried about having NUL's in the middle of your buffer? Those makes your buffer invalid as C-strings, sure, but they don't really affect your fwrite, so I don't see the problem of replacing LF with NUL. I mean, this is totally fine:

```c
#include <stdio.h>

int main(int argc, char **argv) {
  char buf[] = "abc\0def";
  FILE *fp = fopen("tmp.txt", "w");
  fwrite(buf, 1, sizeof(buf), fp);
  return 0;
}
```

**Comment by zmwangx** [comment]
The NUL character. `'\0'`.

**Comment by jarun** [comment]
OK, I'll have to see the compatibility with X clipboard and our read selection from buffer logic would change too.

The reason I am worried about the separator is I see separate filepaths in separate lines when I select multiple in a gui file manager and copy in a text editor.

**Comment by zmwangx** [comment]
Okay I'm not sure why a GUI file manager is involved, I only read a bit of the code around select keywords. You obviously know the code and I don't, so I'll restrict my comments on a very specific concern: if you want to use xargs robustly, you have to 0-delimit paths.

I don't know X clipboard at all, but my macOS clipboard can hold multiple objects — plain text, rich text, image, etc. (sort of like multipart); an xargs-compatible text buffer / plain text file clearly isn't as powerful. The best it can do is to 0-delimit. Of course, you can go into fancy serialization territory too, but that's probably unnecessary.

**Comment by jarun** [comment]
when you copy multiple files in finder and copy in a regular gui editor, do you see filepaths in distinct lines?

**Comment by zmwangx** [comment]
- `touch foo bar $'foo\nbar'`.
- Copy the three files from Finder.
- Paste into TextEdit:

  ```
  bar
  foo
  foo?bar
  ```

- Paste into terminal:

  ```
  /private/tmp/test/bar /private/tmp/test/foo /private/tmp/test/foo\
  bar
  ```

**Comment by jarun** [comment]
Seems like the clipboards work differently on different platforms.

1. I will see if the Unicode thing works

2. If it doesn't I will remove the copy to clipboard feature.

**Comment by jarun** [comment]
Oh no, it's the same buffer interpreted differently by different apps.

**Comment by zmwangx** [comment]
Oh, you're talking about copying to clipboard. That can be fuzzy, being LF-delimited is totally fine there. But input into xargs cannot, it must be 0-delimited.

I don't think you can mimic true copy to clipboard in a proper GUI application. On macOS for instance, you need AppKit for that, not something you can do from C.[1] Outside macOS, X clipboard definitely can be manipulated from C, but X is not the only window system.

[1] https://developer.apple.com/documentation/appkit/nspasteboard

**Comment by jarun** [comment]
This is how we do it:

https://github.com/jarun/nnn#to-clipboard

**Comment by jarun** [comment]
So I am just trying to mimic the thing we do in `googler` where we pass the string to `xsel`, `pbcopy` etc.

**Comment by jarun** [comment]
@kjnez @zmwangx can you please confirm if the latest master works on Mac?

**Comment by zmwangx** [comment]
No. A couple of problems:

1. `rm -Ir`: you're explicitly asking for interactive confirmation when running rm from xargs, where stdin is consumed, so that shouldn't work anywhere, not just on macOS.

2. `cp --preserve=all`: that's coreutils only.

3. `mv -t`: that's coreutils only.

Please check FreeBSD man pages, e.g. https://www.freebsd.org/cgi/man.cgi?query=mv.

**Comment by zmwangx** [comment]
Re stdin consumed in xargs invocation: I think you probably have to implement the confirmation prompts natively rather than rely on third-party ones.

**Comment by zmwangx** [comment]
By the way, an largely unrelated thought: rather than writing the `.nnncp` file to home directory (some of us consider dotfiles a pollution) or $TMPDIR (wholly insecure), have you considered writing to something like `XDG_RUNTIME_DIR` [1], e.g., under `/var/run`?

[1] https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by zmwangx** [comment]
(The previous comment is a stretch, maybe just ignore it.)

**Comment by jarun** [comment]
Please test latest master. This seems to work on Ubuntu.

**Comment by jarun** [comment]
... where the `-a` option to xargs is available.

**Comment by jarun** [comment]
I think the best way forward to keep these calls within platform-specific macros. The lastest set I pushed works fine on Ubuntu and the stdin issue is not seen because xargs ahs an option to read in a file.

**Comment by jarun** [comment]
See if you can pull up something on Mac. Use `__APPLE__` to have distinct cmd strings for Mac.

**Comment by jarun** [comment]
No problem!

**Comment by jarun** [comment]
At 361c18064e26fa3028dda81258acb4ed5aa7c486:

- xargs uses the option `-o` to open input (interactive mode works now)
- `rm -Ir` is changed to `rm -ir` (`-I` is not available on OS X)
- `cp --preserve=all` is changed to `cp -p` (available everywhere, also`-r` changed to `-R`)

The only thing that remains is the `-t` option for `cp` and `mv`.

**Comment by kjnez** [comment]
@jarun  Yes, it works now. I think you have solved the problem.

**Comment by jarun** [comment]
Thanks for confirming @kjnez!

**Comment by detunized** [comment]
Sorry, I disappeared. I confirm that it works now on macOS. Good job, guys. Thanks.
