### ISSUE TITLE
[question] nuke file path

### ISSUE THREAD

**Issue by avlap** [jarun/nnn#1433]
I can get nuke to work with a custom extension, but to make launcher application needs a filepath. FPATH seems to only contain the file itself (without PWD). I do this now with:

file_path="$PWD/$FPATH"

in handle_extension()

nohup my_app "${file_path}" >/dev/null 2>&1 &

I've nuke in my PATH and I've set:
export NNN_OPENER=nuke in ~/.bash_profile

Nuke works now with the custom extension outside nnn, but not in nnn. 

In nnn, the file is opened with nvim instead (which might be the fallback to xdg-open).

**Comment by jarun** [comment]
Please refer to: https://github.com/jarun/nnn/tree/master/plugins#access-level-of-plugins

I tried moving `nuke` to `$PATH` and it worked for me with default applications.
I think you need to mode `my_app` to `$PATH`.

Anyway, it appears to be a local environment issue. Please debug yourself.

**Comment by avlap** [comment]
This was not needed: file_path="$PWD/$FPATH"

The issue was with the env variables. Nice application, thanks.

**Comment by jarun** [comment]
Good to know you figured it out!

**Comment by avlap** [comment]
I was looking for a good file manager, looked at Ranger, LF etc. Ranger is easier to use from start. The NNN documentation is a bit overwhelming, which drifted me away from NNN at first. The thing I like about NNN now is that it has a clean view, just one column. Two columns is giving my eyes to much information. Conceptually I like how NNN uses other available tools as much as possible. I also was also looking to a good plugin system, comparing the cli file managers. That's another reason why I like NNN, makes sense how it uses shell scripts, which also can be used outside NNN. I don't know C, was thinking about looking at Go for learning, but this application makes me wonder how it works. Named pipe files / fifo are blocking right? Hm how does that work? Maybe I should start looking at the code and see if I can learn some C. I'm aware of the suckless.org way of doing things, but using env variables for config, is totally new concept to me. Hm I'll think about if I like it or not. ;)

**Comment by jarun** [comment]
👍
