### ISSUE TITLE
maybe this is not a bug, but..

### ISSUE THREAD

**Issue by n1rdeks** [jarun/nnn#1434]
I use Rxvt-unicode (24bit color), Gentoo, Bash, DWM and NNN.

NNN not open any console scripts (for example, notify-send for Dunst) on L or Return.
Images, edit files ($EDITOR) work fine.

How fix this? (I read Wiki, but...)

P.S. export NNN_OPENER=/home/bestuserreallytrustme/.config/nnn/plugins/nuke
     and run nnn -c just open script in editor (nvim)

**Comment by N-R-K** [comment]
Not really sure what you mean. Try to provide some examples.

**Comment by jarun** [comment]
It is working as expected. `nnn` doesn't run executables by default.

**Comment by n1rdeks** [comment]
Thanks for your fast answer, Jarun. 
Ok, default behavior - not run exec/bin
Please help me, how enable this option? Maybe some plugin? Give me any info... I read Wiki, watch videos. If I press 'o'  and run script - all fine. But I want press RET (nnn have option, where disable 'l' button for run) for running bin files (default bin opened in editor).

P.S. Sorry for my Eng...

**Comment by jarun** [comment]
It's not available as a safety measure against users running binary executables by mistake.

**Comment by n1rdeks** [comment]
Thanks. Nice. Well, just need a some habit for this? So long time I use MC...

**Comment by jarun** [comment]
`nnn` is quite different from anything else. Otherwise, we wouldn't need tow rite it. ;)
