### ISSUE TITLE
Firefox integration

### ISSUE THREAD

**Issue by kukushkawi** [jarun/nnn#1441]
Hello. First of all thanks for your file manager, it's instantly became my favourite one. But there's one question i have: how to integrate nnn in Firefox? I've seen chromium integration, but not for Firefox or it's not possible?

**Comment by N-R-K** [comment]
The imposter trick which works on chromium doesn't work on firefox.

> or it's not possible?

It *shouldn't* be impossible, since KDE file picker works on firefox. But we're not aware of how to do it with nnn.

**Comment by luukvbaal** [comment]
Oh right never got around to updating the wiki. It is possible with https://github.com/GermainZ/xdg-desktop-portal-termfilechooser, I'll add it later.

**Comment by luukvbaal** [comment]
Please check if https://github.com/jarun/nnn/wiki/Advanced-use-cases#firefox works for you. I don't quite remember all the steps required to get it to work.

**Comment by jarun** [comment]
Closing the issue as we don't really have a lot to share here other than what's already documented.
