### ISSUE TITLE
Preselect Files e.g from mpv

### ISSUE THREAD

**Issue by Randalix** [jarun/nnn#1442]
It would be nice if I could preselect files before I open nnn and still get the + in front of the files.

e.g. I have this litte mpv lua script wich is passing the current file to the nnn selection.
```
function select()
    local path = mp.get_property("path") or ""
    mp.osd_message("nnn select\n" ..  path, 3)
    local home = os.getenv( "HOME" )
    local file = io.open(home .. "/.config/nnn/.selection", "a")
    file:write(path .. "\0")
    file:close()

end
mp.add_key_binding(nil, "select", select)
```
If I then open nnn I can move the selected files or do what ever I like with it. Only the visual indicator +  is missing.

Is there some trick to add the + ? If not is this something that could be implemented?
I hope I'm not missing something.

**Comment by jarun** [comment]
No way to do this. Thanks!
