### ISSUE TITLE
Any way to combine "start nnn within tmux" and "quitcd" properly??

### ISSUE THREAD

**Issue by amalgame21** [jarun/nnn#1446]
Since I prefer using `preview-tui` with `tmux` which only open a new pane instead of new terminal 
so I want to combine usage of `tmux` and `quitcd`

in the wiki, it mentioned that I can start `nnn` within `tmux` with this function:
```
n ()
{
    if [ -n "$TMUX" ]; then
        nnn -a $@
    else
        tmux new-session nnn -a $@
    fi
}
```
I modified the `nnn` above to `nn`, and modified the function name of `quitcd`  from `n()` to `nn()`
then I can use `n` to call `tmux` ,which in turn call `quitcd` script properly.

However, when I press `^G` to quit `nnn` program
it also quit `tmux` and return to the directory where I started `tmux`, which break the function of `quitcd`.
Are there any way to keep the directory after leaving tmux? Thanks.

**Comment by jarun** [comment]
I use the following and it works:

```sh
n ()
{
    if [[ "${NNNLVL:-0}" -ge 1 ]]; then
        echo "nnn is already running"
        return
    fi  

    export NNN_TMPFILE=${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd
    export LD_LIBRARY_PATH=/opt/nnn-libs

    # Unmask ^Q (if required, see `stty -a`) to Quit nnn
    stty start undef
    stty stop undef

    #if [ -n "$TMUX" ]; then
    #    \nnn -cdDEnQru "$@"
    #else
        tmux -u new-session nnn -acdDEnQru "$@"
    #fi 

    if [ -f $NNN_TMPFILE ]; then
        . $NNN_TMPFILE
        rm $NNN_TMPFILE
    fi  
}
```

Please debug local environment issues yourself.

**Comment by jarun** [comment]
Also, read the relevant documentation: https://github.com/jarun/nnn/wiki/Basic-use-cases#configure-cd-on-quit

**Comment by amalgame21** [comment]
> I use the following and it works:
> 
> ```shell
> n ()
> {
>     if [[ "${NNNLVL:-0}" -ge 1 ]]; then
>         echo "nnn is already running"
>         return
>     fi  
> 
>     export NNN_TMPFILE=${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd
>     export LD_LIBRARY_PATH=/opt/nnn-libs
> 
>     # Unmask ^Q (if required, see `stty -a`) to Quit nnn
>     stty start undef
>     stty stop undef
> 
>     #if [ -n "$TMUX" ]; then
>     #    \nnn -cdDEnQru "$@"
>     #else
>         tmux -u new-session nnn -acdDEnQru "$@"
>     #fi 
> 
>     if [ -f $NNN_TMPFILE ]; then
>         . $NNN_TMPFILE
>         rm $NNN_TMPFILE
>     fi  
> }
> ```
> 
> Please debug local environment issues yourself.

It works perfectly!!!! THANKS!!!

Just find out the type-to-nav mode  (-n) in your script, seems interesting!
Still al lot of new thing to explore!

**Comment by jarun** [comment]
Awesome!
