### ISSUE TITLE
Some icon colors are not following color scheme

### ISSUE THREAD

**Issue by UtkarshVerma** [jarun/nnn#1447]
I have the following configuration for colors:

```sh
export NNN_COLORS="1234"
export NNN_FCOLORS="030304020007060801050500"
```

But I don't understand why vim and lua files have icons which are colored from outside my colorsheme. It has bad contrast, hence this issue.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/31820255/182019173-3a6eeba1-4566-4084-8a9b-7ea211fecd3c.png)

I use the Monokai colorscheme which looks like this:

![image](https://user-images.githubusercontent.com/31820255/182019271-e3e5e7d7-39f3-41dd-bdd6-395ebf716cdc.png)

**Comment by jarun** [comment]
That's a random colorsheme. Feel free to work on colors - https://github.com/jarun/nnn/wiki/Themes

**Comment by UtkarshVerma** [comment]
> That's a random colorsheme. Feel free to work on colors - https://github.com/jarun/nnn/wiki/Themes

@jarun 

I used the exact same config, but still the lua and vim **icons** are fetching colors from somewhere else.

![image](https://user-images.githubusercontent.com/31820255/182020875-adcf61d5-346d-4aa7-a48d-b1e5bdb56ba8.png)


This is what I used for FCOLORS.
```sh
BLK="0B" CHR="0B" DIR="04" EXE="06" REG="00" HARDLINK="06" SYMLINK="06" MISSING="00" ORPHAN="09" FIFO="06" SOCK="0B" OTHER="06"
export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
```

**Comment by N-R-K** [comment]
> but still the lua and vim icons are fetching colors from somewhere else.

I'm pretty sure that icon colors are hardcoded in `src/icons.h`. Have a look in there.

**Comment by N-R-K** [comment]
And yes, I agree that the current lua color has bad contrast. I removed the `COLOR_LUA` and use `COLOR_FSHARP` for my local build.

```diff
-	{"lua",        ICON_EXT_LUA,        COLOR_LUA},
+	{"lua",        ICON_EXT_LUA,        COLOR_FSHARP},
```
