### ISSUE TITLE
Sometime type-to-nav mode cannot be toggled properly by ^N

### ISSUE THREAD

**Issue by amalgame21** [jarun/nnn#1449]
Most of the time when I open nnn in the `~` directory, and press `^N` to toggle type-to-nav mode, it cannot be toggled in a few keypress (maybe the first 1-3 time would fail).
I have to keep pressing `^N` multiple time and suddenly it can toggle properly.

This problem is mainly in `~` directory, maybe because a lot of directories, files and symlinks are in there.
Other directory also have this problem, but it is very rare.

So I decided to record the screen to demonstrate what is going on, which further amplify the problem a lot.

![screen-trim2](https://user-images.githubusercontent.com/93383215/182169796-7dd297cb-90e6-4f63-8745-c6cbfb64fbd7.gif)

I was recording the screen with ffmpeg and store it in `~` directory as screen.mkv. 
Below are the descriptions of the above gif:

1. When I was recording,  I cannot use `^N` to toggle type-to-nav anymore. Instead, it keeps refreshing the screen but nothing happened.

2. Then I press `k` and `l` to enter the empty `Public` directory. When I was in the directory, the first 3 `^N` keypress is not working, but suddenly it is working to toggle the type-to-nav mode.

3. When I go back to the `~` directory by pressing `h`, `^N` was not working anymore. When I keep pressing `^N`,the screen only keep refreshing.

This is tested with nnn-4.6 from official arch linux repository with no modification.

**Comment by jarun** [comment]
What terminal are you using? Please check if the terminal has any binding for `^N`?

**Comment by amalgame21** [comment]
> What terminal are you using? Please check if the terminal has any binding for `^N`.

The gif was recorded with xterm.
I tried alacritty and xfce4-terminal with same result.
Seems all have no keybinding for `^N`
I tried both zsh and bash to launch nnn with same result.

**Comment by jarun** [comment]
I guess commit 12b5416b2c87427100979b00e6d30ff674d3c4a0 introduces this.

**Comment by jarun** [comment]
Please try with master.

**Comment by amalgame21** [comment]
> Please try with master.

seems working fine now!!!

**Comment by jarun** [comment]
Thank you fore reporting the issue!
