### ISSUE TITLE
Pressing Alt+Esc key in filter prompt will quit nnn immediately, instead of exit filter prompt and refresh dir

### ISSUE THREAD

**Issue by amalgame21** [jarun/nnn#1452]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: arch linux, openbsd
- [x] Desktop Environment: i3
- [x] Terminal Emulator: xfce4-terminal, alacritty, tmux
- [x] Shell: zsh, bash, ksh
- [x] Custom desktop opener (if applicable): nuke?
- [x] Program options used: none
- [ ] Configuration options set: 
- [x] Plugins are installed: all standard plugin
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Pressing `Alt+Esc` key in filter prompt will quit `nnn` immediately like pressing `^Q` key, instead of exit filter prompt and refresh dir as described in the manual page.

**Comment by N-R-K** [comment]
Seems like intended behavior to me.

```
FILTER & PROMPT
            /  Filter                 ^N  Toggle type-to-nav
          Esc  Exit prompt            ^L  Toggle last filter
            .  Toggle hidden     Alt+Esc  Unfilter, quit context
```

Pressing `?` should show you the list of default keybindings.

**Comment by amalgame21** [comment]
> Seems like intended behavior to me.
> 
> ```
> FILTER & PROMPT
>             /  Filter                 ^N  Toggle type-to-nav
>           Esc  Exit prompt            ^L  Toggle last filter
>             .  Toggle hidden     Alt+Esc  Unfilter, quit context
> ```
> 
> Pressing `?` should show you the list of default keybindings.

Thanks for clarification!

I open this issue because I saw this in the manual page:

```
Special keys at filter prompt:
-------- + ---------------------------------------
  Key    |                Function
-------- + ---------------------------------------
 ^char   | Usual keybind functionality
 Esc     | Exit filter prompt but skip dir refresh
 Alt+Esc | Exit filter prompt and refresh dir
-------- + ---------------------------------------
```
^char seems also working in filter prompt
So I assume the `Alt+Esc` was somehow duplicated with `^Q` by mistake.

And I looked at the changelog, you are right.
The `Exit filter prompt and refresh dir` function was added in v3.3
and changed to same behaviour as ` ^Q` in 4.1, but don't know why.

#### v3.3 changelog
```
- key Alt+Esc to clear filter prompt and redraw
```

#### v4.1 changelog:
```
- Alt+Esc to quit context from filter prompt
```

I can not see any other keybindings have the function of `Exit filter prompt and refresh dir` now as in v3.3.
Have to press `^L` to clear filer and then press `Esc` to escape filter mode. But it is still fine.

Maybe the manual page need update for this change?

Thank you!!

**Comment by N-R-K** [comment]
> Maybe the manual page need update for this change?

You're right. It does.
