### ISSUE TITLE
Support for mobaxterm

### ISSUE THREAD

**Issue by krishnakumarg1984** [jarun/nnn#146]
Hi,

On my personal laptop running Linux, I use `nnn` and absolutely love it.

I would like to simply use this for my work machine too on which the only OS is Windows 10. I am not permitted to install any other OS. Furthermore, I do not have admin access to install software for my machine at work, which means installing `WSL` is a no-go.

As a workaround to use the awesome `unix-y` tools, I use the __portable__ version of [`mobaxterm`](https://mobaxterm.mobatek.net/) which is an all-encompassing solution, consisting of a X11 server, tabbed SSH client, network tools and much more. For a local terminal session, `putty` is used as the moba terminal and has 256 color support and a whole host of other immensely useful features. Several `coreutils`  and other GNU software are pre-installed (eg. `cat`, `ls`, `less`, `which`, `grep` etc.). One can also directly call any windows executable present in the windows path directly from mobaxterm command line. 

Now, for the `unix-y` software not pre-installed, there is a convenient package manager. For example to install a specialised package not commonly seen in base installs, such as the  MUA `mutt`, one can simply type `apt-get install mutt` (just like Debian/Ubuntu).  The package manager downloads all dependencies and installs `mutt` ready to go! Similarly, other modern software such as `neovim` etc. are all available through this path.  I think that the `apt-get` command is just a wrapper around `apt-cyg` which is for fetching packages from the `cygwin` package repository. There is also a GUI package management tool which uses the aforementioned scripts as the backend.

May I request to include `nnn` for `mobaxterm`?

**Comment by jarun** [comment]
I believe you'll have to make the request to the mobaxterm team?

**Comment by krishnakumarg1984** [comment]
@jarun  Arun, I think you have to provide a cygwin package as part of your release process

**Comment by jarun** [comment]
I use PackageCore and that doesn't generate one. See if you can raise a PR.

**Comment by jarun** [comment]
>  I think that the apt-get command is just a wrapper around apt-cyg which is for fetching packages from the cygwin package repository.

This should be coming from the cygwin package repo, right? Generally someone related to the project would package a utility and add maintain it in the default repos. I don't understand your request why `nnn` must provide the package.

Also, AFAIK, `nnn` can be compiled just fine in the Cygwin environment. You can do that.

**Comment by jarun** [comment]
Support for the Cygwin env is available in the code.

**Comment by krishnakumarg1984** [comment]
@jarun I had never read about PackageCore and now reading about it quickly, I understand it is a python package for building for various distros. 

Similarly for cygwin there is an automated tool/framework can `cygport` that can easily build from your source http://www.cygwin.com/packaging-contributors-guide.html#making_srcpackage

If it is any consolation/encouragement for you to consider this, I was able to successfully build `nnn` from source within the `mobaxterm` by using Cygwin's `gcc 7.3` on your `makefile`. It created an `nnn.exe` which could now be run from both `cmd.exe` as well as `mobaxterm`. I have now added it to my user  `PATH` in windows (which doesn't require admin rights).

Clearly, using `cygports` has an additional advantage of upgrades etc. without the end user recompiling sources for a future release.

Also, the success that I had with this quick experiment got me thinking. Can you probably not provide a `nnn.exe` native windows executable directly and probably set up CI using `appveyor` or Travis? this native single executable file can be run both on `mobaxterm`, `powershell` or `cmd.exe` without the need of any admin rights.

**Comment by jarun** [comment]
Sorry, I do not have the time to spare on that.

The support for Cygwin is rudimentary. I know `cygstart` works but nothing else has been certified. I do not use it myself. Why would I consider packaging it for that platform?

I do use `nnn` on the Linux subsystem for Windows.

**Comment by krishnakumarg1984** [comment]
Yes. For those who can install `WSL` what you propose is indeed the best option. Installing `WSL` is clearly intrusive and can't be done without admin rights. Period. 

Instead of closing this, could you consider adding a label such as `help-wanted` so that an interested member of the community could consider improving the `cygwin` support (as you already say current support level is rudimentary)

**Comment by jarun** [comment]
> Instead of closing this, could you consider adding a label such as help-wanted so that an interested member of the community could consider improving the cygwin support (as you already say current support level is rudimentary)

Definitely, I will add it to the ToDo list. You might have missed this note in the introduction section:

_Missing a feature? Want to contribute? Head to the rolling ToDo list._

I prefer feature requests going there instead of having open defects for features which are not available.

**Comment by krishnakumarg1984** [comment]
@jarun  indeed I missed the `ToDo` note in your `README.md`. Apologies.

**Comment by jarun** [comment]
I have added it referred to this issue. To help out, could you test `nnn` and make a list of things which do not work on Cygwin? Don't have to be a complete list but at least indicative. For example, I don't think cp, mv, rm would work. If someone picks it up that would help.

**Comment by krishnakumarg1984** [comment]
@jarun  absolutely. will do that.

**Comment by krishnakumarg1984** [comment]
Upon testing, `cp`, `rm`, `mv` all worked. One thing that didn't work was `copy to clipboard`. Though I tried installing `xclip` and `xsel`, it didn't work. Can you maybe look into it.

Yes. I can submit the package to cygwin repos, but I'd like the process to be automatic. I am still reading up on Cygwin to figure out how to do this.

**Comment by jarun** [comment]
Which utility is used to copy to the clipboard on cygwin?

**Comment by jarun** [comment]
For the time being, I am thinking of having a wiki page on how to compile, install etc. `nnn` on cygwin. On Termux we have an official package so not much to document.

If we can figure out the clipboard copy stuff we can document the necessary steps and make a release this weekend. It's a short span since the last but there are some hurting issues on OS X where we have many users so we need a release with the fixes as soon as possible.

**Comment by jarun** [comment]
Instructions for Cygwin are linked from the homepage now. I have verified copying to windows clipboard works.
