### ISSUE TITLE
[question] Any ways to use sftp on nnn in android termux without root?

### ISSUE THREAD

**Issue by amalgame21** [jarun/nnn#1462]
Just a minor question.
Are there any ways to use sftp on android nnn in termux?
I tested sshfs on termux, it is not working because it require root privilege.
Rclone on termux also not work, seems require fusermount, which also require root.
I am not familiar with rclone, are there any way to use rclone without fusermount to do it?

**Comment by jarun** [comment]
My Android device is not rooted. Probably check with Termux.
