### ISSUE TITLE
Match colors of `ls`

### ISSUE THREAD

**Issue by smeikx** [jarun/nnn#1463]
**Is your feature request related to a problem? Please describe.**

The colors of `ls` and `nnn` do not match, which creates a kind of dissonance.

**Describe the solution you’d like**

`nnn` could read `LS_COLORS` to set foreground color, background color and even attributes (bold, underscore, reverse, …).

**Describe alternatives you’ve considered**

Maybe a script could generate `NNN_FCOLORS` from `LS_COLORS`. This would not consider attributes, though (because `NNN_FCOLORS` only allows specifying colors).

**Additional context**

I have found [this comment](https://github.com/jarun/nnn/issues/798#issuecomment-731752668) regarding `LS_COLORS`:

> I know there are solutions like that (e.g. LS_COLORS) but we haven't adopted them in nnn.

Is there a specific reason for not adopting `LS_COLORS`?

**Comment by jarun** [comment]
`nnn` and `ls` are different. If `ls` suits your needs, use `ls`.
