### ISSUE TITLE
Chromium File Picker

### ISSUE THREAD

**Issue by Carlisle96** [jarun/nnn#1465]
- [X] Operating System: Fedora
- [X] Desktop Environment: XMonad
- [X] Terminal Emulator: Kitty
- [X] Shell: Zsh
- [   ] Custom desktop opener (if applicable):
- [   ] Program options used:
- [   ] Configuration options set:
- [X] Plugins are installed
- [X] Issue exists on `nnn` master

I followed the wiki article:

1. Created kdialog in .local/bin - which is detected and runs fine from within the terminal
2. Run with XDG_CURRENT_DESKTOP=KDE chromium-browser --password-store=basic "$@" form within the terminal
3. Go to Test Website - I still get the gtk picker

(a) Also tried installing kdialog package - still get the gtk picker
(b) Running newest version of chromium 103

**Comment by luukvbaal** [comment]
Did you adapt the script to your own personal terminal? Does the command that launches nnn inside kdialog work on its own?

**Comment by Carlisle96** [comment]
I am planning to adapt the script to my own personal terminal, but for testing purposes i just didn't change it at all and installed st on my machine. As described in 1. It works on its own when i just launch it from anywhere in the terminal typing kdialog - so .local/bin is in my PATH for sure.

**Comment by luukvbaal** [comment]
Hard to tell what the issue is then. It should work, I just tested with latest chromium. The problem is in your environment. Do you have xdg-desktop-portal installed?? I came across this [post]( https://www.reddit.com/r/openSUSE/comments/pjuf27/leap_fix_gtk_file_dialog_in_recent_version_of/), it can mess up the kdialog spoof.

**Comment by Carlisle96** [comment]
I had xdg-desktop-portal installed and also now tried with installing xdg-desktop-portal-kde both with no success.
Is there a community where I can find help setting it up correctly ?

**Comment by luukvbaal** [comment]
I doubt it, it's hard to debug environment issues remotely. Have you tried uninstalling xdg-desktop-portal? Or at least disabling the service.

**Comment by Carlisle96** [comment]
Thank you a lot for your support --removing xdg-desktop-portal ( without kde ) worked. It would be good to add it to the documentation that xdg-desktop-portal can interfere with kdialog or is there a way to use the new xdg-desktop-portal way with nnn?

xdg-desktop-portal is a requirement for flatpak which i need for another program

**Comment by Carlisle96** [comment]
Is there a global way of using nnn as your file selctor in all programs ?

**Comment by N-R-K** [comment]
> Is there a global way of using nnn as your file selctor in all programs ?

Not sure if such a thing/protocol exists. Though it'd be good if it does, since it'd solve ALL the gtk filepicker issues.

**Comment by Carlisle96** [comment]
I found this: https://github.com/jarun/nnn/issues/1348#issuecomment-1167878034
Which might work with something like https://github.com/emersion/xdg-desktop-portal-wlr 

I am not really that experienced in all these things but i will try my best to understand / get it working

**Comment by Carlisle96** [comment]
I have figured it out how to change the filePicker in all applications:

1. Need to have `xdg-desktop-portal package` installed
2. Build https://github.com/GermainZ/xdg-desktop-portal-termfilechooser from source
3. . Put Files in correct locations:
- org.freedesktop.impl.portal.desktop.termfilechooser.service to /usr/share/dbus-1/services/
- xdg-desktop-portal-termfilechooser.service to /etc/systemd/system/
- termfilechooser.portal to /usr/share/xdg-desktop-portal/portals
- xdg-desktop-portal-termfilechooser binary to ~/.local/bin
- contrib/config.sample as ~/.config/xdg-desktop-portal-termfilechooser/config
- ranger-wrapper.sh to ~/.config/xdg-desktop-portal-termfilechooser/
4. Update paths in those files to point to their counterparts
5. export `GTK_USE_PORTAL=1` and `XDG_CURRENT_DESKTOP=i3` ( i3 needs to be in the list of the portal file ) for example in ~/.profile
6. Reboot and it should work

Now only the ranger wrapper file was given. Could you provide a nnn-wrapper.sh counterpart ?

**Comment by luukvbaal** [comment]
> I have figured it out how to change the filePicker in all applications:

The problem is not all programs adopt the xdg-desktop-portal standard. But yeah, configuring the termfilechooser portal will cover all those that do.

**Comment by amalgame21** [comment]
> I have figured it out how to change the filePicker in all applications:
> 
>     1. Need to have `xdg-desktop-portal` package installed
> 
>     2. Build https://github.com/GermainZ/xdg-desktop-portal-termfilechooser from source
> 
>     3. . Put Files in correct locations:
> 
> 
>     * org.freedesktop.impl.portal.desktop.termfilechooser.service to /usr/share/dbus-1/services/
> 
>     * xdg-desktop-portal-termfilechooser.service to /etc/systemd/system/
> 
>     * termfilechooser.portal to /usr/share/xdg-desktop-portal/portals
> 
>     * xdg-desktop-portal-termfilechooser binary to ~/.local/bin
> 
>     * contrib/config.sample as ~/.config/xdg-desktop-portal-termfilechooser/config
> 
>     * ranger-wrapper.sh to ~/.config/xdg-desktop-portal-termfilechooser/
> 
> 
>     4. Update paths in those files to point to their counterparts
> 
>     5. export `GTK_USE_PORTAL=1` and `XDG_CURRENT_DESKTOP=i3` ( i3 needs to be in the list of the portal file ) for example in ~/.profile
> 
>     6. Reboot and it should work

Some tips for Arch users.
`xdg-desktop-portal-termfilechooser-git` in AUR works just fine, though some of the binary was installed in /usr/lib.
The problem is that the package manager will ask for installing other `xdg-desktop-portal-impl`, like kde/gnome/gtk/etc.
Have to choose and install one of them to proceed.
After installed , need to delete them (e.g. `xdg-desktop-portal-kde`), leaving `xdg-desktop-portal-termfilechooser-git` the only remaining `xdg-desktop-portal-impl`
Then reboot. reboot is necessary.
Then it should work.
