### ISSUE TITLE
Question: Multilingual use

### ISSUE THREAD

**Issue by kukushkawi** [jarun/nnn#1467]
Hello again! I'm using ukrainian very often, because it's my native language and, of course, i have to always switch languages to use any bindings in NNN. Can i do something with it or maybe you can provide me information how to fix it? 
I've read documentation about bindings and there was "collisions" so i assume that i can't write alternative keys for every binding?
Thanks in advance.

**Comment by jarun** [comment]
You can change the keybinds in `nnn.h` file. Procedure:

- change the keys
- compile `nnn`
- run `./nnn -K`

**Comment by kukushkawi** [comment]
> You can change the keybinds in `nnn.h` file.
> 
> Procedure to detect collision:
> 
>     * change the keys
> 
>     * compile `nnn`
> 
>     * run `./nnn -K`

Thanks for replay. I can set two different keys in `nnn.h`, right?

**Comment by jarun** [comment]
You can set as many as you want.

**Comment by kukushkawi** [comment]
Thanks a lot. Will try to get it working for me.
