### ISSUE TITLE
picker mode -p - selection occasionally disappeared/reset

### ISSUE THREAD

**Issue by amalgame21** [jarun/nnn#1468]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Arch
- [x] Desktop Environment: i3
- [x] Terminal Emulator: alacritty
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: -p -
- [ ] Configuration options set:
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

download nnn by `git clone 'https://github.com/jarun/nnn'`
`cd nnn`
`make`

run command `./nnn -p - ~` start the picker mode in home directory
press 5 `space` to select 5 folder/files
wait for several seconds
the selection sometimes automatically disappeared/reset, need to select them again
after selecting again, may auto reset after several second again and again, or may not.

This bug have high change happen in home directory, which have a lot of folder, files and symlinks.
Other folder may have the same issue, but much lower chance.

Tested several version 
Seems this issue started from v4.3
 v4.2 does not have this issue.

**Comment by jarun** [comment]
Do you understand what the picker mode is? Do you understand what passing `-` means?
Please do not waste our time with non-issues.

**Comment by jarun** [comment]
When you pass `-`, `nnn` just uses the internal buffer and it is cleared on a change in directory.
The mode is for quickly picking files, not to keep open for long.
