### ISSUE TITLE
[Question] How can I pick the files with your ffnnn script in firefox if the program keep dis-seleteing for me?

### ISSUE THREAD

**Issue by amalgame21** [jarun/nnn#1469]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Arch
- [x] Desktop Environment: i3
- [x] Terminal Emulator: alacritty
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Install `nnn` master
Install `xdg-desktop-portal-termfilechooser`, configured it to use `ffnnn` as described in wiki.
Use the `ffnnn` script for firefox as described in wiki.
In the "Upload file" operation, select files with `space`
Files were dis-selected by the program.

![screen-trim-crop](https://user-images.githubusercontent.com/93383215/186457074-f095f342-aefc-4cdf-aae0-4c0d96456015.gif)

Description of above gif: mouse click on "browse" , and then type the keystrokes shown on the gif.

I misinterpreted the issue in #1468. Sorry my bad, wasted your time.

If your program is designed to work like this, or I made some mistakes that I did not know, please let me know how to make the selection permanent, thanks.

**Comment by N-R-K** [comment]
It works fine on my machine :tm:

It seems to me that something might be wrong with your selection file. Post output of the following command:

```console
$ env | grep "^NNN"
```

**Comment by luukvbaal** [comment]
Don't see the issue with in firefox with termfilechooser, no idea what could cause it either...

**Comment by amalgame21** [comment]
`env | grep "^NNN"` output:
```
NNN_FIFO=/tmp/nnn.fifo
NNN_OPENER=/home/user/.config/nnn/plugins/nuke
```

Tried put them in either ~/.zshrc or ~/.profile, also the same.


P.S. `nnn -p -` also NOT working fine for me "sometimes" as `ffnnn`.
Both `nnn -p -` and `ffnnn` (the gif) not 100% chance dis-select automatically itself, maybe like (3/10) chance.

**Comment by amalgame21** [comment]
Just figured out the cause of the issue.
It have something to do with how the `polybar` was launched by `i3`
Very strange.

Changing this line in `i3` config to launch `polybar` 
From this:
```
exec_always --no-startup-id ~/.config/polybar/launch.sh
```
To this:
```
exec_always --no-startup-id nohup ~/.config/polybar/launch.sh >/dev/null 2>&1 &
```
Then restart i3, solve the `nnn -p -` issue. WTF

`launch.sh` is nothing special, just 3 lines
```
killall -q polybar
polybar example
echo "Bars launched..."
```

No idea why this affect the `nnn` behaviour in this way.
Just keep commenting out the i3 config to test, and this seems the line cause the problem.

**Comment by jarun** [comment]
Instead of `nnn -p -` use an output file and then read that one.
