### ISSUE TITLE
nnn editor doesnt work on linux or unix

### ISSUE THREAD

**Issue by NapoleonWils0n** [jarun/nnn#147]
Hi 
ive been trying for past day to get nnn to work
but it doesnt work with the EDITOR or VISUAL enviornmental variables on linux or unix in ~/.bashrc

i have tried using export NNN_USE_EDITOR=1 but that doesnt work
also it doesnt work with xdg-open either

i have emacsclient -t set as my editor variable in ~/.bashrc

i have also created a emacsclient.desktop file in ~/.local/share/applications 
and set the mimeinfo.cache to use the emacsclient.desktop file and used update-desktop-database

when i run xdg-open somefile.txt it opens with emacsclient

but when i try and open the file using nnn it doesnt open 

tested using freebsd 11.2 and ubuntu 18.04

shame because its a nice app and much faster than ranger
but not being able to specify the applications used to open files is a deal breaker

**Comment by jarun** [comment]
Instead of `emacsclient -t` can you set `vim` and see if it works?

**Comment by jarun** [comment]
Or just `emacs`?

**Comment by NapoleonWils0n** [comment]
HI Mate

yes changing the editor to vim works

`export EDITOR="/usr/bin/vim`

and using /usr/bin/emacs works

i also tried changing EDITOR from 

`export EDITOR="/usr/bin/emacsclient -t"`

to 

`export EDITOR="/usr/bin/emacsclient"`

and that works, so it must the -t option that causes the issue

ill try on freebsd and see if removing the -t option works

**Comment by NapoleonWils0n** [comment]
i just tried on freebsd 11.2 and removing the -t option from the editor variable
and it opens in emacs and not in the terminal

on ubuntu 18.04 removing the -t option from editor the file will open with emacsclient in the terminal
but its really flaky if you open another terminal it then opens with the pager

also if i add

NNN_USE_EDITOR=1

nothing happens when you try and open the file

**Comment by jarun** [comment]
As long as you don't add `NNN_USE_EDITOR=1`, `nnn` will use the default opener, so that's the behaviour you see.

When you use `NNN_USE_EDITOR=1`, set EDITOR (or VISUAL if it's set) to just `emacs` and see how it goes.

**Comment by NapoleonWils0n** [comment]
if i change the editor variable to 

`export EDITOR="/usr/bin/emacs`

and add

`export NNN_USE_EDITOR`

the file opens in emacs
but the problem is it then takes several seconds to open another instance of emacs

and also if you run emacs server to use emacsclient,
you then get an error because emacs is already running

which is why i use emacsclient with the -t option to connect to the emacs server and open the file in the terminal

if i remove

`export NNN_USE_EDITOR`

the file then opens in the pager

even if i set up an emacsclient.desktop file and use mimeinfo.cache in ~/.local/share/applications
and dont use NNN_USE_EDITOR nnn doesnt use xdg-open to open the file

if i run 

`xdg-open file.txt`

the file opens with emacsclient

**Comment by jarun** [comment]
I have added an entry in the ToDo list to parse the EDITOR/VISUAL string and pass the params to exec properly. That's the issue here.

**Comment by NapoleonWils0n** [comment]
ranger works with the editor variable set to emacsclient -t

but nnn doesnt, and also nnn doesnt seem to use xdg setting from ~/.local/share/applications
i guess it only reads the .desktop files and mimeinfo.cache from /usr/share/applications

**Comment by NapoleonWils0n** [comment]
i wonder if its the space or the -t option in the editor variable thats the issue
the path is in double quotes, you cant omit the double quotes in ~/.bashrc round the emacsclient -t
because it throws an error

its also strange that it opens in the pager if i omit NNN_USE_EDITOR
and doesnt seem to use local xdg settings

**Comment by jarun** [comment]
Yes we need to parse the string `emacsclient -t`.

`nnn` uses `xdg-open` if `NNN_USE_EDITOR` is not set.

**Comment by NapoleonWils0n** [comment]
does nnn only look in /usr/share/applications for .desktop files and mimeinfo.cache
because if you changing settings there they may be overwritten after a file update

nnn doesnt seem to read settings from ~/.local/share/applications

when you try and open the file nothing happens even though xdg-open file.txt works properly

**Comment by jarun** [comment]
> when you try and open the file nothing happens even though xdg-open file.txt works properly

what are your settings?

**Comment by jarun** [comment]
Please test with master with the following settings:

    export NNN_USE_EDITOR=1
    export EDITOR="emacsclient -t"

And no, `nnn` does not read any files from anywhere. It just calls if `xdg-open` if `NNN_USE_EDITOR` is not set.

And on BSD, `xdg-open` is not installed by default. You have to install it manually.
