### ISSUE TITLE
Cycling contexts using `(Shift + ) Tab`

### ISSUE THREAD

**Issue by amanjitsk** [jarun/nnn#1471]
**Is your feature request related to a problem? Please describe.**

When pressing `Shift + Tab`, it opens a new context instead of cycling through
the currently open/active contexts in reverse. It only starts cycling in reverse when
all possible contexts are activated/opened.

**Describe the solution you'd like**

I think it would be better if `Shift + Tab` worked just like `Tab` in that it cycles
through currently open contexts in reverse (instead of activating/opening
new contexts till there are none left, after which it then cycles in reverse).

It feels a bit weird when having 5 open contexts for example (in a 8 context build),
to have `Shift + Tab` open more contexts, instead of just reverse cycling through the
5 open contexts. 

On a similar note, it would be nice to have a keybind to jump to the previously active
context. This isn't that important when using few contexts, but in a 8-context build,
again, it might make it easier to switch back and forth between current and last context,
instead of having to press the context number. Perhaps something like `^` for this?

Again, I think these features might only be worthwhile when using 8-contexts, so
feel free to close it if it doesn't seem that useful. But I certainly think it would help!

Best,
Amanjit

**Comment by jarun** [comment]
From help page:

    (Sh)Tab  Cycle/new context

Till you have 4 tabs, `Sh+TAB` will create a new context. once all 4 are created, it will reverse cycle.
`TAB` always cycles.

**Comment by jarun** [comment]
If you are using 8 contexts, hack the code to reverse cycle with `Sh-TAB`.

**Comment by amalgame21** [comment]
Just an nnn user come across attempting to hack the code.
I am not a developer.
Below is a patch for `nnn-4.6` to disable "`Sh-Tab` create new tab" function
Actually just comment out three lines in `nnn.c` with `//`
If the patch does not work, you may manually comment out that three line in `nnn.c` and build it.
Again, I am not a developer, not guarantee work fine, may break something.

```
diff -rua nnn-4.6/src/nnn.c nnn-4.6.new/src/nnn.c
--- nnn-4.6/src/nnn.c
+++ nnn-4.6.new/src/nnn.c
@@ -6024,9 +6024,10 @@
 				r = (r + 1) & ~CTX_MAX;
 			while (!g_ctx[r].c_cfg.ctxactive);
 		else {
-			do /* Attempt to create a new context */
-				r = (r + 1) & ~CTX_MAX;
-			while (g_ctx[r].c_cfg.ctxactive && (r != cfg.curctx));
+//    /* Uncomment below three lines to retrive "(Sh)Tab create new tab when not all contexts are active" functionality */
+//			do /* Attempt to create a new context */
+//				r = (r + 1) & ~CTX_MAX;
+//			while (g_ctx[r].c_cfg.ctxactive && (r != cfg.curctx));
 
 			if (r == cfg.curctx) /* If all contexts are active, reverse cycle */
 				do
```
