### ISSUE TITLE
[Support] key strokes for plugins

### ISSUE THREAD

**Issue by Piscium** [jarun/nnn#1473]
I have recently started using nnn with its 'preview-tui' plugin. I am loving it. Thanks a lot for making it available.

I have a question. If I press Page Up or Page Down, that key stroke is grabbed by nnn itself rather than the plugin. Is there a way to send a key stroke to the plugin so that for example I could page up/down the page in the preview plugin? I looked in the source code for that plugin and in the man page and could not find anything, though it is such an obvious thing that I may have missed it.

On a more general theme, it makes little sense to me to ask a support question in a Github issue. I looked for a place to ask support questions, such as in Reddit, but could find none. I wonder if there are plans to have something like that, such as a subreddit or mailing list or in groups.io, or whatever? If so then it could be mentioned in the nnn readme or wiki to lead people to it.

**Comment by luukvbaal** [comment]
Just switch to the preview pane(method depends on previewer used, for tmux the default is <kbd>Ctrl+b n</kbd>) and depending on the pager you will be able to scroll up or down.

Yes we don't have a dedicated support channel, the ToDo issue can be used to ask questions also.

**Comment by Piscium** [comment]
> Just switch to the preview pane(method depends on previewer used, for tmux the default is Ctrl+b n) and depending on the pager you will be able to scroll up or down.

Thanks, yes, so obvious as I had initially said it could be! I guess I am used to ranger that is why it did not occur to me.
 
> Yes we don't have a dedicated support channel, the ToDo issue can be used to ask questions also.

Thanks. I will use the todo list next time. What about then renaming it as 'ToDo list and support questions' to guide people to it?

I will close the issue now.
