### ISSUE TITLE
Add du-style file size usage visualisation 

### ISSUE THREAD

**Issue by chir4gm** [jarun/nnn#1474]
I think it would be cool if a user can bind a key like `d` and then have `du` run recursively for their current folder. 
Then, size of their files and directories would be displayed along their names, very much like how `ncdu` works.

However, this way they would also be able to use NNN to select and delete their big files if they are trying to do some regular
file maintenance, not to mention how they could use this information in conjunction with other plugins. 

I would like to give this a shot. Could I get any pointers to what to look out for, and how to go about this? Also, is there any way to implement this as a plugin? I don't really see how.

**Comment by N-R-K** [comment]
I think what you're looking for already exists. Try running `nnn -Td`.

**Comment by amalgame21** [comment]
reference:
https://github.com/jarun/nnn/wiki/Usage

```
Sort keys can be a/d/e/r/s/t/v (see program option -T). Capitalize to reverse (except r). Path must be absolute.
```

Press ? in nnn to see the keybinds in your installed version.

you can see

```
t ^T  Sort toggles 
```

so in nnn, press `t` / `^T` and then press `d` will sort all the files and folders with du style.

**Comment by jarun** [comment]
Closing as this is already available.
Please read the documentation before raising bugs.

**Comment by chir4gm** [comment]
@jarun My apologies! I tried googling around, but I should have read the documentation more carefully!
