### ISSUE TITLE
Video Preview (Not Thumbnail)

### ISSUE THREAD

**Issue by levone1** [jarun/nnn#1475]
**Is your feature request related to a problem? Please describe.**
no

A clear and concise description of what the problem is.

**Describe the solution you'd like**

In all of my testing/trials of many cli tools, only one I've found that will actually play a video when previewing, as opposed to just a thumbnail.  The tool is Hunter - https://crates.io/crates/hunter - and it is deprecated.  It runs media files from it's own media program, (hunter-media).  

Maybe I'm missing something, but I haven't found any others.  Overall, nnn is superior to any others...  Any chance of adding that?  I wonder if you could just add hunter-media as a media player option, and take on maintenance, or fork, or...?

**Describe alternatives you've considered**
I considered making an attempt at modding the preview script, but it's a bit over my head...

**Additional context**

Thanks

**Consider contributing**

Please consider contributing the feature back to `nnn`.

Feel free to discuss in the ToDo list thread. We are more than happy to help.

**Comment by jarun** [comment]
No plans. Thanks!

**Comment by 0xACE** [comment]
> I considered making an attempt at modding the preview script, but it's a bit over my head...

try harder

**Comment by N-R-K** [comment]
[preview-tabbed](https://github.com/jarun/nnn/blob/master/plugins/preview-tabbed) already does video preview with mpv.

**Comment by levone1** [comment]
> [preview-tabbed](https://github.com/jarun/nnn/blob/master/plugins/preview-tabbed) already does video preview with mpv.
> 
> Also if you're planning on watching the video, why not open it on an actual video player? For _preview_ purposes, a thumbnail is more than enough.

Sometimes, the preview is just a blurry blob, so can't even tell what it is...
