### ISSUE TITLE
When run in docker exits immediately and breaks tty

### ISSUE THREAD

**Issue by ignat** [jarun/nnn#1476]
#### Environment details (Put `x` in the checkbox along with the information)

- [ x] Operating System: Linux
- [ x] Desktop Environment: Docker
- [ x] Terminal Emulator: xterm
- [ x] Shell: ash
- [ x] Custom desktop opener (if applicable):
- [ x] Program options used: default
- [ x] Configuration options set: default
- [ x] Plugins are installed
- [ x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
In the docker environment it is a common case when the shell runs with PID=1. And so the following code at https://github.com/jarun/nnn/blob/v4.6/src/nnn.c#L6692
```c
if (getppid() == 1)
    _exit(EXIT_FAILURE);
```
is executed. What causes the application to exit immediately and break the terminal (tty).

Steps to reproduce:
```sh
docker run -it --rm alpine:edge ash
ps ax
apk add nnn
nnn
```

**Comment by KlzXS** [comment]
I'm afraid there isn't anything we can do about this. Checking for 1 from `getppid()` is the only way we can check for the parent process (shell in normal use) exiting. You'll have to play around with docker if you want to get it to work.

Also when the parent process exits we take it that the shell has also exited so there is no need to clean up the tty.

**Comment by ignat** [comment]
The problem is that getppid doesn't guarantee to return 1 for the terminated parent process. If you read the documentation for getppid you will see that it can be 0 or other value >1 in different systems.

The only way to check for the terminated parent process is to save getppid value at the start and then see if it changes later. If it changes then we can say that it has terminated.

Comparing getppid to 1 is wrong and it won't work in many systems, not only in docker.

**Comment by KlzXS** [comment]
> The problem is that getppid doesn't guarantee to return 1 for the terminated parent process.

If the parent process gets killed the child will get inherited by init, which _is_ PID 1. That is what we are trying to catch. That is what happens during regular use when you close a terminal.

Also `getppid()` can't really return 0. No real process has PID 0. It's a reserved thing.

This issue was already reported once (#1407). Not much has changed since then.

**Comment by N-R-K** [comment]
>  save getppid value at the start 

That's not possible I believe. We don't have control over "the start", lots of other things have to happen before execution enters `main()`.

> Comparing getppid to 1 is wrong and it won't work in many systems, not only in docker.

Could you give some examples of such systems?

**Comment by pvx-** [comment]
> > Comparing getppid to 1 is wrong and it won't work in many systems, not only in docker.
> 
> Could you give some examples of such systems?

On Linux you can set you own "reaper" pid with PR_SET_CHILD_SUBREAPER (see for example https://unix.stackexchange.com/questions/149319/new-parent-process-when-the-parent-process-dies ), but it is quite niche IMHO.

Those affected can remove the check from their own source - if you run everything in tmux/screen (like me ;) you probably don't need it anyway.

**Comment by N-R-K** [comment]
Added a workaround to the wiki (thanks to @averms): https://github.com/jarun/nnn/wiki/Troubleshooting#running-inside-docker-containers
