### ISSUE TITLE
Pressing r to rename files opens an empty file in nvim

### ISSUE THREAD

**Issue by indeedwatson** [jarun/nnn#1477]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: arch
- [x] Desktop Environment: bspwm
- [x] Terminal Emulator: alacritty
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Pressing `r` opens an empty temp file on nvim. Writing and saving on it yields no changes.

I've also tried using the renamer plugin, and that one doesn't even launch. I've looked for issues and documentation but I can't find anything relevant to this behavior.

**Comment by indeedwatson** [comment]
I figured out the cause, it's the wrapper script suggested here: https://github.com/jarun/nnn/wiki/Basic-use-cases#detached-text

but adapted to alacritty: `alacritty -e nvim "$1" &`

any ideas how to make the renamer work with alacritty?

**Comment by N-R-K** [comment]
Do you actually need that wrapper script? As far as I see, it's for tmux/xfce-terminal users. Shouldn't `xdg-open` open `nvim` (assuming it's the default text opener) in a new window already?

**Comment by N-R-K** [comment]
> I have tried `alacritty -e "nvim \"$*\""` but if I do that the nvim window just closes instantly.

Try removing the inner quote. The following works for me (on both XTerm and ST):

```console
$ VISUAL="st -e vim" nnn
```

But anyhow, this seems like an environment issue rather than defect in `nnn`. So closing.

**Comment by indeedwatson** [comment]
> Try removing the outer quote (e.g `alacritty -e nvim "$@"`).

That worked, thanks.

**Comment by indeedwatson** [comment]
> > I have tried `alacritty -e "nvim \"$*\""` but if I do that the nvim window just closes instantly.
> 
> Try removing the outer quote (e.g `alacritty -e nvim "$@"`). The following works for me (on both XTerm and ST):
> 
> ```
> $ VISUAL="st -e vim" nnn
> ```
> 
> But anyhow, this seems like an environment issue rather than defect in `nnn`. So closing.

Both these workarounds spawn a new window, and indeed fix the renaming issue, but they render the nnn unusable, it turns into a terminal. The ewrap script I use keeps the nnn active and usable.

Whether it's a bug or an environment issue, the problem spawns from nnn's own documentation. If the documentation is wrong or incomplete, something should be changed.

**Comment by indeedwatson** [comment]
> Try option `-E`. Also, the documentation is for `xfce4-terminal` and an example. We can't test and document every terminal under the sun for a free project. Suit yourself. If you find a way share with us and we can add to documentation.

I understand that, but Alacritty is one of the most popular terminals out there. That actually worked, Thanks!

**Comment by N-R-K** [comment]
> Both the workarounds you listed result in the original nnn instance being unusable until the editor window is closed. It does fix the renaming issue, but the point is to keep the original window usable.

Running the terminal in the background should give you what you want: `alakritty -e nvim "$1" &`.

> I don't understand why you're so eager to close an issue that is not solved.

You're still free to converse in the thread. We typically don't keep environmental issues open.
