### ISSUE TITLE
How to get nnn starting work directory in plugin?

### ISSUE THREAD

**Issue by theowenyoung** [jarun/nnn#1478]
If I have a plugin named `test`

Now I started `nnn` in `~/project1`

```bash
NNN_PLUG='t:test' nnn
```

Then I navigated to `~/project1/dir1/example.md`

How I can get `nnn` work directory which is `~/project1`?

I tried to `printenv` in my plugin, I can only get these:

```bash
nnn=example.md
PWD=/Users/username/project1/dir1
f1=/Users/username/project1/dir1/example.md
```

so how can I get the nnn started directory?

**Comment by theowenyoung** [comment]
Yes, I tried to get the starting directory .

I use nnn as file navigation for development projects,  use [kakoune](https://github.com/mawww/kakoune) as my text editor. The starting directory is considered my kakoune editor session name.

I set `VISUAL="kakproject"`, witch is a shell script by myself.

`kakproject` need the session name(starting directory name) to open the file in the tmux split window.

I finally use `STARTED="$PWD"` to run `nnn`, then my `VISUAL` can get that environment variable `STARTED`   

So, basically, my workflow now is like this:

1. `cd ~/project1`
2. run `p`, this will open 2 split window in tmux
3. when I press `enter` in text file, the file will be opened in the right window.

I don't know if it's a classical use case in `nnn`. I'll post my shell script here:

`/bin/p`

```bash
#!/bin/bash
set -e;
kak -clear
session_name="$(basename `PWD`)"
is_session_exist=$(kak -l | grep $session_name || echo "")
if [[ -z "${is_session_exist}" ]]; then
    # Create new kakoune daemon for current dir
    kak -d -s $session_name &
fi
# start a new kakoune client in a new 80% pane
tmux split-window -d -h -l 80% -c '#{pane_current_path}' "kak -c $session_name $@"
# start nnn in current pane with -e edit mode
STARTED="$PWD" VISUAL="kakproject" NNN_OPTS="e" nnn
```

here is my `kakproject` code:

```bash
#!/bin/bash
# get file path from nnn
file_path=$1

# clear dead session for kak
kak -clear
# current working directory
# STARTED is set by k
cwd=${STARTED:-$PWD}
# get session name, which is the current directory
session_name=$(basename $cwd)
is_session_exist=$(kak -l | grep $session_name || echo "")
if [[ -z "${is_session_exist}" ]]; then
    # Create new kakoune daemon for current dir
    kak -d -s $session_name &
    sleep 0.01
fi
# open file in kak with client0 , witch is the default client
echo "evaluate-commands -client client0 edit ${file_path}" | kak -p $session_name
# focus on the editor pane
tmux selectp -R
```

**Comment by N-R-K** [comment]
I have this as a dummy plugin:

```sh
#!/bin/sh

echo "$START_DIR"
```

And then I run `nnn` like this: `START_DIR="$PWD" nnn`. If I run the dummy plugin, it echos `$START_DIR` fine.

If this is how you invoke `nnn`: `STARTED="$PWD" VISUAL="kakproject" NNN_OPTS="e" nnn` then all the plugins should be able to inherit the `$STARTED` env var.

**Comment by theowenyoung** [comment]
yeah, it works, but I didn't know I could do this when I released this issue, and then I thought of this way to do it, so I posted it in case others need it too.

In fact, I think this scenario is 80% of my scenarios with using nnn, so it's nice if nnn can support this feature
