### ISSUE TITLE
[Feature request] Keep selected count visible in status bar during action confirmation, e.g. deleting files.

### ISSUE THREAD

**Issue by amalgame21** [jarun/nnn#1479]
Very minor feature request here.

Since nnn allow selecting items in different directories, deleting files before confirming selected count is crucial to me to avoid deleting wrong items.

After selected files for deletion, pressing `x` `s` will go to `rm -rf selection?` dialog.
In this dialog, no selected number is shown.
Have to press `esc` to see the selected number to confirm correct number of file to be deleted, and then press `x` `s` `y` again to delete those file.

If selected count is shown in the `rm -rf selection` dialog. May prevent some extra keypresses. 
I tried changing my personal behavior to focus on the selection before pressing `x`, but failed. I found it not very intuitive.

**Comment by luukvbaal** [comment]
I like it, implemented in #1480. Let's see what @jarun thinks.

**Comment by amalgame21** [comment]
Thanks luukvbaal and jarun !!!!!
