### ISSUE TITLE
Provide native windows binary

### ISSUE THREAD

**Issue by krishnakumarg1984** [jarun/nnn#148]
A similar CLI file manager, `lf` (see https://github.com/gokcehan/lf) provides a native windows binary as a single executable file (`lf.exe)

`lf` is written in `go`, whereas `nnn` is written in `C`, both of which are highly portable. 

Can you consider adding a windows binary as part of your GitHub assets for subsequent tagged releases?

**Comment by jarun** [comment]
`nnn` depends on `ncurses` which is not available natively on Windows.

**Comment by krishnakumarg1984** [comment]
@jarun sorry to bother with this same story again. I could get a `nnn.exe` through compilation in a cygwin environment. This `nnn.exe` is working in `cmd.exe`. Is there a chance you could go through that route and provide a windows binary for future GitHub releases?

**Comment by jarun** [comment]
When you say _native windows binary_ that means something that runs directly on Windows, not inside the Cygwin env.

**Comment by krishnakumarg1984** [comment]
@jarun  that's what I meant. The compilation inside `mobaxteelrm` produced `nnn.exe`. I can double-check, but I think this worked on the standard `cmd.exe`.

 Sorry for the naive question, but is `ncurses` a run-time requirement or simply needed at compile-time?

**Comment by jarun** [comment]
>  is ncurses a run-time requirement or simply needed at compile-time?

We link dynamically.

**Comment by krishnakumarg1984** [comment]
@jarun forgive me. Indeed, this only works inside `mobaxterm`.  When I try it with `powershell` or `cmd.exe`, I get a dialog box popping up and telling me:

> The code execution cannot proceed because `cygncursesw-10.dll` was not found. Reinstalling the program may fix this problem.

So, the question boils down to "Doesn't using `nnn` like this  inside `cygwin` hamper performance, which was after all one of the biggest victories of the project?".  

* Would you recommend this for `Windows` use, considering that both `lf` and `vifm` provide portable windows binaries.

* Is there anything that you might consider to make the project truly cross-platform, whilst still retaining performance?

**Comment by jarun** [comment]
No, I don't have any remote intention of supporting `nnn` natively on Windows.

**Comment by krishnakumarg1984** [comment]
But will `nnn` in cygwin be faster than native `lf` and `vifm`?
