### ISSUE TITLE
about color

### ISSUE THREAD

**Issue by n1rdeks** [jarun/nnn#1483]
I want see a colored some filetypes (or create plugin for that) - archives, video and music, images etc.  
Maybe with dircolors settings...

I read sources and found this construction - patterns, blah-blah, "\\.(bz|bz2|gz|tar|taz|tbz|tbz2|tgz|z|zip)$".
and u used  S_IFREG...

Maybe NNN check file types? (I am a noob on C)

this colored LS:
![2022-09-08-231633_1920x1080_scrot](https://user-images.githubusercontent.com/63796667/189217479-ee59b296-cb9e-4613-af96-f6c9c93848cc.png)

and this NNN: (so boring, or I used so long colored LS output, who knows) 
![2022-09-08-231742_1920x1080_scrot](https://user-images.githubusercontent.com/63796667/189217597-a9b1936a-fafe-4f70-85a0-97c0c7fc1736.png)

my config:
```
export NNN_OPTS="r"
export NNN_ARCHIVE="\\.(7z|bz2|gz|tar|tgz|zip)$"
export NNN_COLORS='#55555555'
export NNN_FCOLORS='c1e2272e006033f7c6d6abc4'
```

P.S. sorry for my Eng.

**Comment by jarun** [comment]
Please use icons: https://github.com/jarun/nnn/wiki/Advanced-use-cases#file-icons

Emojis appear to be the simplest if your terminal supports.
