### ISSUE TITLE
[preview-tui] `catimg` not previewing png file

### ISSUE THREAD

**Issue by latipun7** [jarun/nnn#1484]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: `Arch Linux ARM aarch64`
- [ ] Desktop Environment:
- [x] Terminal Emulator: `tmux 3.3a`
- [x] Shell: `zsh 5.9 (aarch64-unknown-linux-gnu)`
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: `NNN_OPTS=aeEUHx`
- [ ] Configuration options set:
- [x] Plugins are installed
- [ ] Issue exists on `preview-tui` master: 
- [x] `nnn version 4.6`

#### Exact steps to reproduce the issue

https://user-images.githubusercontent.com/20012970/189341861-5669fea7-d824-4b1a-b93d-d638e002e6a8.mp4

I'm not using desktop environment, using tmux and image preview with catimg. But nnn preview-tui didn't show `*.png` image even tho catimg supporting `.png`, so catimg png files manually do works.

Please tell me if you need more info. Thank you for your support 🙏

**Comment by jarun** [comment]
@luukvbaal or @N-R-K can any of you check if `handle_mime()` is working correctly for PNG with `catimg`? Probably `geenrate_preview` is called for PNG.

**Comment by amalgame21** [comment]
`preview-tui` plugin up-to-date??
The script updated last month, before that have the same behaviour like this.

**Comment by latipun7** [comment]
> `preview-tui` plugin up-to-date??

I'm pretty sure it is updated. I update plugins with `getplugs`

**Comment by amalgame21** [comment]
Oh, I dunno they have a plugin to do this.
Just give it a try.
After looked into the code, seems `getplugs` only get the plugins according to your installed version, unless you pass argument `master` to the plugin manually in the command line.
I run `nnn-4.6`, and run the plugin normally (by pressing `;` `ENTER` , search for `getplugs` and `Enter`)
Cannot get the master branch plugins.

**Comment by latipun7** [comment]
Tried to update like this:
```sh
sh -c "$(curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs)" master
```
the bug still arround.

**Comment by N-R-K** [comment]
I don't see anything obviously wrong in the preview-tui code.

Also @latipun7 your video filename has "WindowsTerminal" in it. If you're using WSL or a VM then those are information which you should provide in the bug report.

**Comment by luukvbaal** [comment]
This bug should indeed be fixed on master: https://github.com/jarun/nnn/pull/1456.

> Tried to update like this:
> 
> ```shell
> sh -c "$(curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs)" master
> ```
> 
> the bug still arround.

This does not get you the version of the plugin from master, the `master` argument is not passed to the script. Please just run `./getplugs master` or download the latest version of `preview-tui` from github directly(as running `getplugs master` is not recommended/supported by @jarun.

**Comment by latipun7** [comment]
> This does not get you the version of the plugin from master, the `master` argument is not passed to the script. 

ah right, dumb me, thanks, it should be:
```sh
sh -c "$(curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs)" -- master
```

> as running `getplugs master` is not recommended/supported by @jarun.

why?

Anyway, thanks for your support. This is clearly me. The bug does go away in current master.
