### ISSUE TITLE
chksum plugin does not work on macOS

### ISSUE THREAD

**Issue by screendriver** [jarun/nnn#1486]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: macOS 12.6
- [ ] Desktop Environment:
- [x] Terminal Emulator: [kitty](https://sw.kovidgoyal.net/kitty/)
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

- select a file in `nnn`
- open the `chksum` plugin
- select for example `md5`
- the written checksum file is empty because I'm getting the error `find: md5sum: No such file or directory`

I think the issue is that [chksum](https://github.com/jarun/nnn/blob/master/plugins/chksum) is expecting `${chks}sum` on the system. Like for example `md5sum`. But on macOS the command is `md5` without the `sum`. The same for `sha256`. On macOS it is `shasum -a 256 /path/to/file` and not `sha256sum`.

**Comment by 0xACE** [comment]
it must have taken you more time to write this issue than patch it and submit a PR...

**Comment by screendriver** [comment]
> But it must have taken you more time to write this detailed issue than patching chksum

Yes but only if you know how to

- script properly in a shell
- distinguish between different platforms **or** make a conditional branch depending on if an executable is available or not (what is the best approach for `nnn` plugins?)
- test the change on different platforms manually (I just have macOS and could break Linux environments)
- write automated tests for that change (does `nnn` have tests for the plugins? I did not found anything regarding this)

So in the end it took me less time to open an issue and ask for help 🙂

**Comment by jarun** [comment]
@KlzXS @N-R-K @luukvbaal can any of you have a look please?

**Comment by KlzXS** [comment]
Well if all that's needed for macOS is the removal of `sum` from the name of the command then we can simply test for the presence of both `X` and `Xsum` and run the one present.

How does this hold up for BSDs and other things we run on? I can almost say I remember that this was mentioned once before, but I'm not sure.

**Comment by jarun** [comment]
@screendriver please refer to https://github.com/jarun/nnn/blob/master/plugins/.ntfy to find the correct command and use it.

Post user input, maybe just make the `sum` part and variable string and make it empty if the command is without `sum`.

**Comment by jarun** [comment]
Raise the PR when things are tested. ;)

**Comment by screendriver** [comment]
> Well if all that's needed for macOS is the removal of sum from the name of the command

Unfortunately it is not as easy. As I wrote in the issue description this only applies to `md5`. On macOS the command would be `md5 -q` (-q for quiet to just print out the hash. Otherwise it would print something like `MD5 (autojump) = f8a6f410df6569f0c20ecfea26154e03`).

But for `sha256` it would be `shasum -a 256` and not `sha256sum`.  So as I understood the script correctly it saves the string `sha256` in a variable `chsum_resp`.  So on my machine I would need to check if it's `md5` and then replace `md5sum` with `md5 -q` but when it is `sha256` we would even further need some kind of string manipulation to extract the number `256` out of the string `sha256` and append it to the command `shasum -a`. To make it even worse for `sha1` the command on macOS is simply `shasum` without any number.

**Comment by jarun** [comment]
detect is the os is macOS and add a completely different path for macOS on user input.

**Comment by screendriver** [comment]
Closed until I create the pull request 🙂

**Comment by jarun** [comment]
I think you can install the GNU packages from Homebrew - `brew install md5sha1sum`.

**Comment by jarun** [comment]
Added the notes at commit 0907895865f632876dfc478fe0c50811724009a2.

**Comment by screendriver** [comment]
Thanks for the hint to `brew install md5sha1sum` but this only installs `md5sum`. `sha256sum` and so on would be still missing. **But** I figured out that everything is included when installing `coreutils` 🙂 

So doing a `brew install coreutils` will install everything that is needed to get it working. I created a pull request https://github.com/jarun/nnn/pull/1494 that mentions that.
