### ISSUE TITLE
[QUESTION] Default plugin path? Default opener?

### ISSUE THREAD

**Issue by vanfanel** [jarun/nnn#1487]
Hi,

According to the documentation, plugins are installed in `~/.config/nnn/plugins`, but after copying them over to that directory, I still have to do:

`export NNN_OPENER=~/.config/nnn/plugins/nuke`

...Unless I have nuke on a dir that is in the `$PATH`, of course.

Up to that point, I understand it all.

But:
1) If the plugins are installed to ~/.config/nnn/plugins, isn't there a way to tell nnn that they are there? That way, it should be possible to simply do:
`export NNN_OPENER=nuke`
**As things are, I would have to copy all the plugins to a directory in the path (because a plugin can use other plugins!), and having ~/.config/nnn/plugins in the path is very strange...**

2) Is there a way to tell nnn that nuke is the default opener without having to export anything? Like a commandline parameter or something like that. Looked at the manpage but I can't see a way to do it.

Thanks

**Comment by vanfanel** [comment]
> That's because `NNN_OPENER` can be any arbitrary binary, it doesn't have to be a "plugin".
> 
> > I would have to copy all the plugins to a directory in the path (because a plugin can use other plugins!
> 
> I don't think that's necessary. What makes you think it is?

The fact that one plugin may need other plugins. Isn't that true that nuke can use other plugins?

**Comment by N-R-K** [comment]
> The fact that one plugin may need other plugins. Isn't that true that nuke can use other plugins?

`nuke` updates the `$PATH` accordingly. So there's no reason you need to do anything like copying plugins to another directory.

https://github.com/jarun/nnn/blob/f6edcc41b90f9c6b79d190599465bbb4ce837a7c/plugins/nuke#L74

**Comment by N-R-K** [comment]
> Is there a way to tell nnn that nuke is the default opener without having to export anything? Like a commandline parameter or something like that.

You can run `nnn` like the following:

```console
$ NNN_OPENER="your/custom/opener" nnn
```

**Comment by vanfanel** [comment]
> > The fact that one plugin may need other plugins. Isn't that true that nuke can use other plugins?
> 
> `nuke` updates the `$PATH` accordingly. So there's no reason you need to do anything like copying plugins to another directory.
> 
> https://github.com/jarun/nnn/blob/f6edcc41b90f9c6b79d190599465bbb4ce837a7c/plugins/nuke#L74

So, what I currently do is:
-Copy `plugins/nuke` to `/usr/local/bin/nuke`
-Copy all the other plugins to `~/.config/nnn/plugins`
-Add `export NNN_OPENER=nuke` in `.bashrc`

Is that right? It works, but I want to know if you see something strange there.

**Comment by N-R-K** [comment]
Yes, it looks fine. I don't see any issues with it.

**Comment by vanfanel** [comment]
> Yes, it looks fine. I don't see any issues with it.

Great, thanks for taking the time to read my questions and answer! :)
