### ISSUE TITLE
[QUESTION] Avoid nnn to explore outside $HOME

### ISSUE THREAD

**Issue by vanfanel** [jarun/nnn#1488]
Hi,

For security reasons (think systems where kids will be the main users...), is it possible to tell nnn to stay inside $HOME and don't go over it?
As in, it can explore dirs under $HOME, but not the root dir, etc...

**Comment by N-R-K** [comment]
Shouldn't you configure this in your user's permission ? `nnn` won't be able to open any folder/file which the current user doesn't have permission for.

```console
$  nnn /root/home
8576: Permission denied
```

**Comment by vanfanel** [comment]
> Shouldn't you configure this in your user's permission ? `nnn` won't be able to open any folder/file which the current user doesn't have permission for.
> 
> ```
> $  nnn /root/home
> 8576: Permission denied
> ```

You are right, but I build small systems that only have root user and don't need an init system, the system boots with a minimal script instead.

**Comment by amalgame21** [comment]
Maybe you need chroot jail instead?

**Comment by jarun** [comment]
It was a feature in `noice`. I have intentionally removed it. File permissions should do.
