### ISSUE TITLE
[Question] In-app help (?, question mark) not working on Ubuntu 22.04 through ssh

### ISSUE THREAD

**Issue by jiawen** [jarun/nnn#1489]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Ubuntu Server 22.04 arm64
- [x] Desktop Environment: None, Ubuntu Server
- [x] Terminal Emulator: iTerm2 ssh to Ubuntu remote. `echo $TERM` shows `xterm-256color`.
- [x] Shell: bash
- [x] Custom desktop opener (if applicable): None
- [x] Program options used: Nothing
- [x] Configuration options set: Nothing
- [x] Plugins are installed: None
- [x] Issue exists on `nnn` master: No

#### Exact steps to reproduce the issue

On Mac client:
`ssh my_server.lan`

On `my_server` server:
```
$ nnn -V
4.3

# Run nnn as normal.
$ nnn

# Press ? to bring up help
# (Nothing happens)
```

I'm reasonably good at digging into UNIX internals but have limited experience with terminal esoterica. I haven't the slightest idea how to debug why `nnn` isn't responding to `?`. I can clearly send `?` in other apps (bash command line, vim, etc), but on `nnn`, it doesn't bring up the help menu.

The help menu works fine on my Mac client running the same version (4.3).

**Comment by 0xACE** [comment]
iirc help is displayed via `PAGER`, your env might need fixing, search the old issues and you'll find your solution

**Comment by jiawen** [comment]
That did it, thanks!

For the record: my server was a "minimal" install and didn't come with `less`. Installing `less` and setting `export PAGER=less` in `.bashrc` fixed it.
