### ISSUE TITLE
[question] Any way to set the mount point other than ```~/.config/nnn/mounts``` ???

### ISSUE THREAD

**Issue by amalgame21** [jarun/nnn#1495]
like ```/mnt``` or ```~/.local/share/nnn``` or something else?

**Comment by jarun** [comment]
Follow `TOK_MNT` in the code and adapt.

**Comment by jarun** [comment]
If you have a problem navigating to it frequently, use a bookmark. I set:

`n:~/.config/nnn` in `NNN_BMS`.

**Comment by jarun** [comment]
Second option: remove `mounts` and create a symbolic link to the desired mount directory as `mounts`. It should work as long as you have permissions.

**Comment by jarun** [comment]
Updated the wiki with the same information.

**Comment by amalgame21** [comment]
The symbolic link thing perfectly do the trick, thanks for your advice Jarun!!!

**Comment by amalgame21** [comment]
I also already set ```m:~/.config/nnn/mounts``` in ```NNN_BMS``` for the quick access and quick dismount by `u`.
