### ISSUE TITLE
[question] How to use manpage when using locally built nnn?

### ISSUE THREAD

**Issue by rensftw** [jarun/nnn#1496]
I noticed that when I compile `nnn` locally, I lose have access to the manpage.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/22574186/192109775-8bf29c08-feb0-48f3-9a5d-ab466f10cda8.png">

For more context: I have checked out the `nnn` repo and build `nnn` with `make O_NERD=1`.
I often refer to the manpage and it would be awesome to get it back. 
Is there a way to get it back?

#### Environment details (Put `x` in the checkbox along with the information)
- [x] Operating System: macOS 12.6 (Monterey)
- [x] Desktop Environment: 
- [x] Terminal Emulator: iTerm + tmux
- [x] Shell: `zsh 5.8.1 (x86_64-apple-darwin21.0)`
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: `NNN_OPTS='AedHJr'`
- [ ] Configuration options set:
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

**Comment by N-R-K** [comment]
Does `sudo make install` not work? It should install the manpage as well.

If not, then you need to probably mess around with `$MANPATH`.

**Comment by N-R-K** [comment]
`make install` is a *very* common way of installing software when building from source. But nevertheless, it's documented on the wiki in the ["build from source" section](https://github.com/jarun/nnn/wiki/Usage#from-source).
