### ISSUE TITLE
Trash confirmation does not show correct number of selected files for `x2sel`

### ISSUE THREAD

**Issue by amanjitsk** [jarun/nnn#1498]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Ubuntu 22.04
- [x] Desktop Environment: bspwm
- [x] Terminal Emulator: st/kitty
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable): `nuke`
- [x] Program options used: `export NNN_OPTS="cBdEfHorQSUx"`
- [x] Configuration options set: ...
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Use the `x2sel` plugin (or manually append to the selection file) to copy some
files into nnn selection. When pressing `x`, followed by `s` (for selection),
the prompt displays `trash selected 0? `, instead of the correct number of
files in selection. Probably an easy fix; just wanted to point it out!

**Comment by jarun** [comment]
@luukvbaal @N-R-K this is coming from #1480. I don't think there's a simple way to show the count.

**Comment by luukvbaal** [comment]
No we would have to count the number of lines in selfile if it has been edited by a plugin or manually. Could opt to do that(count the lines) if `nselected == 0` in `cpmvrm_selection()`,

**Comment by luukvbaal** [comment]
Actually, `nselected` may still be outdated even if it is not 0. The following diff would work:

```diff
diff --git a/src/nnn.c b/src/nnn.c
index f1b19dae..8762b299 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -1423,9 +1423,26 @@ static void xdelay(useconds_t delay)
 	usleep(delay);
 }
 
+static uint_t lines_in_file(int fd, char *buf, size_t buflen)
+{
+	ssize_t len;
+	uint_t count = 0;
+
+	while ((len = read(fd, buf, buflen)) > 0)
+		while (len)
+			count += (buf[--len] == '\n');
+
+	/* For all use cases 0 linecount is considered as error */
+	return ((len < 0) ? 0 : count);
+}
+
 static char confirm_force(bool selection)
 {
 	char str[64];
+	char buf[PATH_MAX];
+
+	int fd = open(selpath, O_RDONLY);
+	nselected = lines_in_file(fd, buf, PATH_MAX);
 
 	snprintf(str, 64, messages[MSG_FORCE_RM],
 		 g_state.trash ? utils[UTIL_GIO_TRASH] + 4 : utils[UTIL_RM_RF],
@@ -2477,19 +2494,6 @@ static void xrmfromsel(char *path, char *fpath)
 #endif
 }
 
-static uint_t lines_in_file(int fd, char *buf, size_t buflen)
-{
-	ssize_t len;
-	uint_t count = 0;
-
-	while ((len = read(fd, buf, buflen)) > 0)
-		while (len)
-			count += (buf[--len] == '\n');
-
-	/* For all use cases 0 linecount is considered as error */
-	return ((len < 0) ? 0 : count);
-}
-
 static bool cpmv_rename(int choice, const char *path)
 {
 	int fd;
```

**Comment by jarun** [comment]
> Actually, nselected may still be outdated even if it is not 0. The following patch would work

Yes, but after an operation we clear it. So as long as we don't show it during the operation (which actually triggers the new read of the file) we are good.

I understand the patch, but I am not willing to do a file read just for this.

**Comment by amalgame21** [comment]
I think one way to prevent frequent file read for this is to use another separated ```.selection``` file ONLY for manual manipulation, say ```.selection-manual```, and ask for which selfile to use ONLY ```.selection-manual``` exist.
But it seems very demanding and may need a lot of rewrite and new logic.

Sad to see this great feature only live for 20 days and it is going away.

**Comment by jarun** [comment]
@luukvbaal I am OK to add this to the patch framework. Move lines_in_file() permanently above confirm_force() for fewer diff.
