### ISSUE TITLE
nnn doesn't obey NNN_USE_EDITOR

### ISSUE THREAD

**Issue by serverhiccups** [jarun/nnn#150]
Hi everyone,
I'm sort of new to contributing to projects like these so sorry if I missed something, but, I'm having some problems with getting my files to open in the correct editor.

My problem is that even when NNN_USE_EDITOR is set to 1 (I tried `set -Ux NNN_USE_EDITOR 1` in fish and `export NNN_USE_EDITOR=1` in bash) some files still use `open`. Specifically `.cpp`, `.md` and other files have no problem opening in `$EDITOR` (vim) but when trying to open a `.js` file it opens in Sublime Text (My default GUI editor).
I tried using the file command to investigate but both `.md` and `.js` files return the same thing. (`index.js: text/plain; charset=us-ascii`).

Any help with this would be appreciated.

OS: macOS 10.14
Shell: `fish`
nnn version: 2.0 installed from homebrew

**Comment by jarun** [comment]
What is the output of `file -bi filename.js`?

**Comment by jarun** [comment]
I have added `js` to the mix.

**Comment by serverhiccups** [comment]
I'm not sure if this is still useful but the output is `regular file`.

**Comment by jarun** [comment]
You redacted this:

    I'm not sure if this is still useful but the output is regular file.
That's why it's not detected correctly. What is the output of `file -bi` for md and cpp?

**Comment by serverhiccups** [comment]
Sorry, I redacted it because I didn't think that it would be very useful. The output for both `.cpp` and `.md` files is still regular file.
Re: config file, I'm not sure, I guess you're right as it would be duplicating functionality already in `file`.

**Comment by jarun** [comment]
Great! Does `file -bI filename` show the mime as `text/...`. Please tech with different file types to confirm this.

If it does, I will pass different args for Linux and OS X and it would be the correct fix.

**Comment by jarun** [comment]
I have made the change to pass `-I` at 8aa72a40a3021508888441b60dd6f324eefe76ee. Thanks for providing all the info.

Please test it out!

**Comment by jarun** [comment]
Removed JS from mime list at d8df13f665b035cad0cceee48f388f4a9b03b9f2.

**Comment by serverhiccups** [comment]
I just built and tested it and it works great! Thanks for taking the time to fix this.

**Comment by jarun** [comment]
No problem! Have fun!

BTW, I don't own a Mac and occasionally I need someone to help me out with insights for any issue reported on Mac.

Would you be interested in joining the project as a collaborator?

**Comment by jarun** [comment]
What is the output of `file json_file`?

**Comment by dv-blk** [comment]
`package.json: JSON data`

**Comment by jarun** [comment]
Sorry, if on Mac, try: `file -bI json_file`, else `file -bi json_file`.

If it still shows the same, the program is behaving correctly. We look for the pattern `text1. E.g.:

    text/x-c; charset=utf-8

**Comment by dv-blk** [comment]
Thanks, I'm actually on linux. Here's the output of those commands.

`file -bI package.json`
``` 
file: invalid option -- 'I'
Usage: file [-bcCdEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding]
            [--mime-type] [-e <testname>] [-F <separator>]  [-f <namefile>]
            [-m <magicfiles>] [-P <parameter=value>] <file> ...
       file -C [-m <magicfiles>]
       file [--help]
```
`file -bi package.json`
```
application/json; charset=us-ascii
```
`file -v`
```
file-5.35
magic file from /usr/share/file/misc/magic
```

**Comment by jarun** [comment]
Thanks, as I explained, we check the output of `file -bi` and if it isn't starting with `text/` we try `xdg-open`.

if you check the original issue, the `file` output was `text/plain; charset=us-ascii`, so `nnn` chooses the text editor. But in your case, it is `application/json` so `xdg-open` is invoked.

**Comment by dv-blk** [comment]
Okay. `application/json` is the common content type of this file, so I've just set xdg-open to use my editor to open this filetype. Thanks again!
