### ISSUE TITLE
Entering directories with many directories inside is very slow with gitstatus patch

### ISSUE THREAD

**Issue by freddylist** [jarun/nnn#1500]
#### Environment details

- [x] Operating System: Void Linux
- [x] Desktop Environment: n/a
- [x] Terminal Emulator: Alacritty
- [x] Shell: Bash
- [x] Custom desktop opener (if applicable): n/a
- [x] Program options used: O_GITSTATUS
- [x] Configuration options set: none
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. Build `nnn` with the `gitstatus` patch.
2. Clone a repository with lots of directories, e.g. [void-linux/void-packages](https://github.com/void-linux/void-packages).
3. Try to use `nnn` in the cloned repository and be annoyed that entering the `srcpkgs/` directory takes ~10 seconds.

---

The `srcpkgs/` directory has 10k+ directories inside it. Entering it without the `gitstatus` patch is instantaneous.

<strike>My C debugging skills are extremely limited, so I probably have no idea what I'm talking about, but it seems to me that the performance hit comes from doing a linear search for what the status of each directory is.</strike> I'm probably wrong here.

I know it says [here](https://github.com/void-linux/void-packages.git) that you don't "optimize handling 10k+ entries in a dir", but I thought that this performance hit should be considered a bug since entering the large directory is instantaneous without the patch.

Logs: [nnndbg](https://github.com/jarun/nnn/files/9690057/nnn.log) (it was too long to include here)

**Comment by KlzXS** [comment]
We do support large directories fairly well I'd say. Even  for 100k files.

But this is a custom patch. While we tend not to accept garbage code even for patches, but their performance in not the highest priority.

If you have a suggestion for improved performance it would be best to submit a PR.

**Comment by luukvbaal** [comment]
It already hangs on the git status command the patch uses to filter out dotfiles when `cfg.showhidden` is false. This was a performance consideration for the `dentfill()` loop but it seems the git status command itself is very slow this way for large directories. I'm sure the performance of the status matching in `dentfill()` could be improved as well but that's not the issue here. I'll see if I can find a different way to filter out dotfiles.

**Comment by freddylist** [comment]
> We do support large directories fairly well I'd say. Even for 100k files.

Yes, `nnn` does support large directories very well without the `gitstatus` patch.

> But this is a custom patch. While we tend not to accept garbage code even for patches, but their performance in not the highest priority.

Understandable!

> If you have a suggestion for improved performance it would be best to submit a PR.

The main reason I submitted an issue instead of a PR is that whatever solution I propose is likely to be garbage - I have a very limited experience of programming in C. That said, I can make an attempt, I just don't want to waste anyone's time.

**Comment by luukvbaal** [comment]
@freddylist should be fixed in https://github.com/jarun/nnn/pull/1501.
