### ISSUE TITLE
Hardlink Creation

### ISSUE THREAD

**Issue by SturmB** [jarun/nnn#1505]
This isn't so much a bug report as a plea for some documentation for how to create hard links.

I have tried selecting a file in one context using <SPACE>, then switching to another context and navigating to the destination directory. Then I press `n` and choose `h` for "hard link." It then asks for `[path/]name`.

Well, I want the name to be the same, and I'm already _in_ the destination directory, so I'm not sure what I should put here. If I just hit <ENTER> again, it cancels the operation. If I enter `@`, then it names the new hardlink "@".

What should I do to make a hardlink of a file with the same name but in a different directory?

**Comment by jarun** [comment]
Rename later. The use case is not possible for batch rename so we left it at that.

**Comment by SturmB** [comment]
I'm not trying to do a batch operation; I just want to make a hard link of a single file. I get that using [SPACE] to pre-select files for an operation _is_ a batch operation, so what's another method for hard-linking a single file?

**Comment by N-R-K** [comment]
Duplicate of #1282

> so what's another method for hard-linking a single file?

You could just use a plugin that creates the symlink/hardlink and then clears the selection.

But given how many people are requesting this feature, maybe it makes sense to allow `@` in single file mode as well.

**Comment by pvx-** [comment]
+1 I can't remember the last time I created more than one link at once. I would personally prefer prefill of file basename (for signle file), but even `@` would be enough most cases.

**Comment by N-R-K** [comment]
> I would personally prefer prefill of file basename

This seems to work.

```diff
diff --git a/src/nnn.c b/src/nnn.c
index 787787b3..f13961f2 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -7530,7 +7530,7 @@ nochange:
 				if (r == 'f' || r == 'd')
 					tmp = xreadline(NULL, messages[MSG_NEW_PATH]);
 				else if (r == 's' || r == 'h')
-					tmp = xreadline(NULL,
+					tmp = xreadline(nselected == 1 ? xbasename(pselbuf) : NULL,
 						messages[nselected <= 1?MSG_NEW_PATH:MSG_LINK_PREFIX]);
 				else
 					tmp = NULL;
```

**Comment by jarun** [comment]
Can you try the patch in the same directory where the source file is? What's the behaviour?

**Comment by jarun** [comment]
And what happens when you press Enter?

**Comment by N-R-K** [comment]
> And what happens when you press Enter?

With the same name it fails and shows the message "entry exists". After changing the name to something else it works just fine.
