### ISSUE TITLE
Run executable file by click

### ISSUE THREAD

**Issue by s0i37** [jarun/nnn#1508]
Hello.
I am looking for convenient tools for using console in my mobile phone. `mc` is good one, but print many trash and also has terrible second bar.
`nnn` seems good, but I want run any executable files (sh,py) by simple finger click.

**Comment by N-R-K** [comment]
You can use a custom opener to do it if you want, see this thread for related discussion https://github.com/jarun/nnn/issues/1481

**Comment by s0i37** [comment]
Very strange way.
I don't understand if I can open folder by click, why I need to change some plugin for opening/running file.

**Comment by jarun** [comment]
Opening works as it should, execution doesn't. You can simply patch the code to run executables in `SEL_OPEN` handling.

**Comment by jarun** [comment]
In fact, random files opening on a tap is dangerous on handhelds.

**Comment by N-R-K** [comment]
> I want run any executable files (sh,py) by simple finger click.

100% of the time I'm opening a `sh` file is because I want to open it in a text editor to edit it, not because I want to run it.

**Comment by s0i37** [comment]
Me too. When I work on PC.
But virtual keyboard on mobile phones is disaster!
I fully accept a risk, because I am planing to work with `nnn` only on my sh/py-scripts.

**Comment by jarun** [comment]
Add the .sh extension check along with text file check.
