### ISSUE TITLE
Missing cygwin package

### ISSUE THREAD

**Issue by monkeysuffrage** [jarun/nnn#151]
Hi,
You mentioned cygwin but I don't see it in the installer packages and installation instructions for cygwin are missing. I could try building from source but that has never worked for me before.

**Comment by jarun** [comment]
Yes, you need to build form source. You need libncursesw10. Can you try to compile from source and provide the compilation steps? I can update in the docs.

**Comment by monkeysuffrage** [comment]
Thanks Arun,
I was able to build it with:
apt-cyg install libncurses-devel
make
make install

**Comment by jarun** [comment]
not libncursesw-devel?

**Comment by monkeysuffrage** [comment]
No, that was the only -devel package there.

**Comment by jarun** [comment]
@krishnakumarg1984 can you confirm with which library you compiled? You mentioned `libncursesw10` [here](https://github.com/jarun/nnn/issues/144#issuecomment-442211974). We also prefer the `w` variant.

**Comment by jarun** [comment]
@monkeysuffrage it seem the lib is available: http://ftp.gnome.org/mirror/cygwin/x86_64/release/ncurses/libncursesw10/

can you check how to install it and share the compilation steps?

**Comment by monkeysuffrage** [comment]
Oh yes, apparently that one was already installed.
Anyway for me it was installing the -devel package that did the trick.

**Comment by jarun** [comment]
Thanks for the info. I am closing the defect.

**Comment by jarun** [comment]
@monkeysuffrage would you be interested in adding the package `nnn` to Cygwin?

Packaging docs: https://cygwin.com/packaging-contributors-guide.html

**Comment by jarun** [comment]
`nnn` is now available on Cygwin: https://www.cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Fnnn%2Fnnn-4.6-1&grep=nnn
