### ISSUE TITLE
nnn path bar abbreviates path display too aggressively

### ISSUE THREAD

**Issue by arrrlaska** [jarun/nnn#1513]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Manjaro 22.0.0 / Linux 5.19.0-3-rt10-MANJARO
- [x] Desktop Environment: i3-gaps
- [x] Terminal Emulator: xfce4-terminal
- [x] Shell: bash 5.1.016
- [x] Custom desktop opener (if applicable): xdg-open
- [x] Program options used: NNN_OPTS=ArEex
- [x] Configuration options set: NNN_COLORS='#0a1b2c3d;1234';NNN_TRASH=2;NNN_OPENER=xdg-open
- [x] Plugins are installed - no plugins
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. Go to a directory where the $PATH is fairly long
2. Shrink the size of the terminal window
3. Observe the way the path gets shrunk aggressively, rather than progressively.

#### Description of issue
When using nnn, if there's enough space in the terminal, the path bar will display the entire current $PATH, but if not, the paths get abbreviated like "/home/auser/some/long/path" to "/h/a/s/l/path"

The issue I'm having is that it abbreviates *too* aggressively when it could get by with showing more information about the relative path without abbreviating everything but the last element of the path. 

#### Example
In this example, the directory "/tmp/alpha/bravo/charlie/delta-echo/foxtrot/golf-hotel-india-juliet-kilo/lima" gets abbreviated to simply "/t/a/b/c/d/f/g/lima" where there probably would've been room for something like "/tmp/alpha/bravo/charlie/d…/foxtrot/g…/lima" (using ellipsis characters, rather than three periods to save space).

(You can't tell from the asciinema, but I'm resizing the terminal window to trigger the shortening of the PATH display:
https://asciinema.org/a/AipWZGDMWtHTZjsHct9U09wRZ

#### Possible fix
An algorithm that gets triggered when there isn't enough room to display the full path which abbreviates the longest path element (such as "golf-hotel-india-juliet-kilo/lima" in the example above) first (exempting the last two elements) until there's enough room to display the path

**Comment by jarun** [comment]
Sorry, no plans to spend time on cosmetic and unavoidable issues.

**Comment by jarun** [comment]
Use a bigger terminal.

**Comment by jarun** [comment]
Otherwise, there's an option `-x` to show the path in the terminal status bar. That's the best we can provide.

**Comment by amalgame21** [comment]
Maybe instead of the current directory, you would see the full path of the hovered item by pressing `f`.
