### ISSUE TITLE
[Question] How to run commandline programs from nnn?

### ISSUE THREAD

**Issue by vanfanel** [jarun/nnn#1514]
Hello!

I have been using nnn for a while now, and I have became used to navigating and running my executable files with it.
Since nnn intentionally doesn't run executables directly, I "invented" a new extension called .run. I add it to my executable shell scripts, and use NUKE to execute these .run files by adding the extension to the NUKE plugin like this:
```
## Run files
        run)
            /usr/bin/sh "${FPATH}"
            exit 0;;
```
So far so good, but programs that run in command line (like frotz, nethack, etc.. for example) don't run like this: it seems that nnn takes over the terminal and won't move from there :D

Any know solution so nnn lets these run? Looked in the docs, high and low, and couldn't find an answer.

Thanks!

**Comment by jarun** [comment]
`nuke` supports cli programs natively. Please check how it is called.

**Comment by jarun** [comment]
@N-R-K @luukvbaal any help is appreciated.

**Comment by jarun** [comment]
You can try to source instead of spwaning a new shell:

    source "${FPATH}"

**Comment by vanfanel** [comment]
@jarun The `source "${FPATH}"` solution sounded great, but sadly it doesn't work at all, even with .run files that work well with `/usr/bin/sh "${FPATH}"`

**Comment by jarun** [comment]
I tried it and it's working for me.

Change in `nuke`:

```
        run)                                                                                                          
            /usr/bin/sh "${FPATH}"                                                                                    
            exit 1;;
```
Contents of my executable file `ls.run`:

```
#!/usr/bin/sh

ls
read -r _
```

When I run I get:

```
Desktop  Documents  Downloads  github  ls.run  Music  Pictures  Public  snap  Templates  Videos
```

**Comment by jarun** [comment]
I am using the `bash` shell.

**Comment by jarun** [comment]
`nethack` works too. So I am not sure what the issue in your environment is. Make sure the `.run` files are executable.

**Comment by vanfanel** [comment]
I have also built latest stable version (nnn-4.6) in Ubuntu current stable version (22.04) and I get the same results.

**Comment by vanfanel** [comment]
I should add I normally build nnn with this:

`CFLAGS="-march=native -mtune=native" make O_NORL=1 O_NERD=1 -j4`

but I have also tried to simply do
`make -j4`

**Comment by jarun** [comment]
Did you make the files you run executable?

**Comment by vanfanel** [comment]
Yes, I did `ls.run` executable with chmod +x `ls.run`.
As I said, `ls.run` runs perfectly from plain BASH.

**Comment by jarun** [comment]
Then I'm out of ideas.

**Comment by N-R-K** [comment]
What happens if you replace `/usr/bin/sh "${FPATH}"` with `exec "${FPATH}"` ?

**Comment by jarun** [comment]
Is it possible that your program is exiting?

Can you add a `read -r _` at the end of your .run file and see if it waits for input?

**Comment by vanfanel** [comment]
> Is it possible that your program is exiting?
> 
> Can you add a `read -r _` at the end of your .run file and see if it waits for input?

I already did that: my program is exactly your ls.run:
```

#!/usr/bin/sh

ls
read -r _

```
