### ISSUE TITLE
Display glitch for `json` files for some terminal emulator with `O_NERD` enabled

### ISSUE THREAD

**Issue by amalgame21** [jarun/nnn#1515]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: EndeavourOS
- [x] Desktop Environment: i3
- [x] Terminal Emulator: sakura, xfce4-terminal
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: -A
- [ ] Configuration options set:
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

The display glitch for `json` file only apply to the name start with number, say `1234abcd.json`
Normally, it should display [ `icon` ,  `1234abcd.json` ]
However it now display [ `1234` , `icon` , `abcd.json` ]
I tested with `xfce4-terminal` and `sakura` terminal, both have this issue.
`alacritty` is fine.

Also `xfce4-terminal` display `json` with wrong icon.
I don't know this have something to do with `nnn` or not.

xfce4-terminal:
![xfce4-terminal-trim](https://user-images.githubusercontent.com/93383215/200391929-5d0cc35a-3404-4ca0-ab47-46027f3a6833.png)

sakura:
![sakura-trim](https://user-images.githubusercontent.com/93383215/200391958-0ce55ed8-488b-47c3-bc34-c33252a2d5c7.png)

alacritty (works properly):
![alacritty-trim](https://user-images.githubusercontent.com/93383215/200391878-5a6e20fc-42d7-4c78-a3cf-19822c043a76.png)

**Comment by N-R-K** [comment]
Works fine on XTerm and ST as well. Think it might be a bug on the terminal emulator side. Try running the following:

```console
$ printf '%s\n' 'ﬥ 123asd.json'
```

If that bugs out for you as well, then it's almost certainly a problem with the terminal emulator.

**Comment by amalgame21** [comment]
> Works fine on XTerm and ST as well. Think it might be a bug on the terminal emulator side. Try running the following:
> 
> ```
> $ printf '%s\n' 'ﬥ 123asd.json'
> ```
> 
> If that bugs out for you as well, then it's almost certainly a problem with the terminal emulator.

Same result, XTerm and ST works fine. It is surly not a problem with nnn.
I want to point out that, even in firefox and chromium, they cannot even display your reply properly.
So I really do not know what causing this.

firefox:
![firefox-trim](https://user-images.githubusercontent.com/93383215/200567539-13c55f2f-39ae-42d5-81b6-b243a622dd3d.jpg)

chromium:
![chromium-trim](https://user-images.githubusercontent.com/93383215/200567579-bf43fa81-eb52-4cf2-bdbf-d99d6a685d7a.jpg)

**Comment by N-R-K** [comment]
Because the icons in nerd font aren't standard. They won't render properly on non-nerd fonts (try and force your browser to use a nerd-font and it should render fine).

In any case, closing since it's not an nnn issue.
