### ISSUE TITLE
Cannot open files with NNN_OPENER="gio open"

### ISSUE THREAD

**Issue by dimitris-triantafyllidis** [jarun/nnn#1517]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Arch Linux
- [x] Desktop Environment: i3-wm
- [x] Terminal Emulator: kitty
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable): No
- [x] Program options used: None
- [x] Configuration options set: NNN_OPENER="gio open"
- [x] Plugins are installed: No
- [x] Issue exists on `nnn` master: Did not try master

#### Exact steps to reproduce the issue
1. Start with a default configuration for nnn
2. Open a shell
3. `export NNN_OPENER="gio open"`
4. Run `nnn`
5. Try to open a file using the right arrow
6. Nothing happens

I am not even sure this is an actual bug. Maybe a binary is required whereas I am passing a binary along with a command to that binary, and just making a one line wrapper works anyway, but I figured I should make a report.

**Comment by jarun** [comment]
`NNN_OPENER` doesn't work that way.

You should read the documentation: https://github.com/jarun/nnn/wiki

**Comment by dimitris-triantafyllidis** [comment]
I couldn't make sense of the documentation.

With "c" added to NNN_OPTS, both xdg-open and gio open work, but xdg-open now blocks nnn as it does if I launch it directly from the terminal.

This is in the v1 release notes by the way:

> Set NNN_OPENER to let a desktop opener handle it all. E.g.:
> export NNN_OPENER=xdg-open
> export NNN_OPENER="gio open"
> export NNN_OPENER=gvfs-open

**Comment by jarun** [comment]
`NNN_OPENER` should be a file now. Not a command.
