### ISSUE TITLE
Cannot see NERD fonts

### ISSUE THREAD

**Issue by raffaem** [jarun/nnn#1518]
I have the same problem as #1026

I use kitty with nerd fonts.
The fonts are correctly installed as I can see the icons in the terminal:
![image](https://user-images.githubusercontent.com/54762742/201516300-e7684be7-1855-4bce-bdde-cb8c47b8e2f7.png)

I compiled nnn with O_NERD=1. However, here is what I see:
![image](https://user-images.githubusercontent.com/54762742/201516366-5a90e7cc-321f-48cd-9755-45f1c3813e42.png)

**Comment by N-R-K** [comment]
What's the primary font set on your terminal ? It needs to be a nerd font.

**Comment by raffaem** [comment]
@N-R-K Thank you. I was going to post.

> Also what locale are you using? Post the output of locale.

That was exactly the problem.

I did `fc-match "FiraCode Nerd Font"` and got a warning about the locale (evidently I had misspelled during installation).

I edited `/etc/locale.conf` to fix the misspelling, run `locale-gen`, rebooted, and now we are fine :)

I will put a warning in the wiki.

**Comment by raffaem** [comment]
Nervermind, the wiki is closed

**Comment by N-R-K** [comment]
I've added a note on it: https://github.com/jarun/nnn/wiki/Troubleshooting#icons-not-working-properly
