### ISSUE TITLE
How to get the two-column view shown at the top of the README?

### ISSUE THREAD

**Issue by zxti** [jarun/nnn#1520]
Hopefully super quick question - how do I get the two-column view shown here?

https://i.imgur.com/kOld6HT.gif

I searched all through the man pages and wiki, but couldn't figure out what exactly I'm looking for. Tried panes, panels, columns, etc.

**Comment by jarun** [comment]
https://github.com/jarun/nnn/wiki/concepts#dual-pane

**Comment by luukvbaal** [comment]
The dual pane comes from the `preview-tui` plugin.

**Comment by jarun** [comment]
@luukvbaal is right!

**Comment by zxti** [comment]
Hey, sorry I'm still pretty confused. I had seen that specific section, but it didn't look relevant:

- This doesn't seem to be the same thing since the wiki screenshot just starts a second pane that is completely unrelated? Rather than what's shown in the gif, where the second pane is always showing the contents of the selection in the left.
- It just shows a screenshot, but I don't know what I'm supposed to *do*...
- It gives examples of something seemingly unrelated called dvtm, unless...are we supposed to run multiple nnn in different terminals and they talk to each other? That...might be a bit too far beyond my skill level.

**Comment by jarun** [comment]
Please refer to the answer from @luukvbaal.
