### ISSUE TITLE
Feature: toggle option for "show current file information in info bar"

### ISSUE THREAD

**Issue by uffejakobsen** [jarun/nnn#1522]
It would be nice if an option to toggle (-i) "show current file information in info bar"

Usage scenario:

Running nnn with option -i on a local file system is really nice
But when you suddenly connect to a remote (sshfs) it gets really slow
In such scenarios it would be nice with a way to disable the -i option in a running nnn session

**Comment by jarun** [comment]
Unfortunately, we have run out of reasonable keys.
Please patch the code yourself. It's a minor change.

**Comment by uffejakobsen** [comment]
> Unfortunately, we have run out of reasonable keys.

As far as I can see the `i` key is unused - or ?

**Comment by jarun** [comment]
You haven't used the _type-to-nav_ mode yet, have you?

**Comment by uffejakobsen** [comment]
Well I mostly use mostly - but there may be parts of type-to-nav that I'm unaware of - as the creator you are the expert ;-)

Are you saying that `i` is already used ?

I've consulted the wiki (https://github.com/jarun/nnn/wiki/Usage#keyboard-mouse)

and even the linked cheat sheet (http://vgx.fr/nnn-cheatsheet.svg)

None of the above shows `i` as allocated - but I may be wrong...

**Comment by luukvbaal** [comment]
I think @uffejakobsen was suggesting a command line option `-i` rather than a keybind <kbd>i</kbd> to toggle at runtime.

**Comment by jarun** [comment]
The command-line `-i` is to enable file information.

` -i      show current file info`

**Comment by luukvbaal** [comment]
Right, I misread anyway, they did suggest a keybind. Disregard.

**Comment by jarun** [comment]
It's OK. ;)

**Comment by uffejakobsen** [comment]
So to recap - `nnn` is not out of key combinations - you just don't want to use a key for info-toggle.

The strength about `nnn` is that it is available on most systems - and it behaves the same on those systems... 

IMHO - having to maintain own brews of `nnn` - results in`nnn` loosing its point/advantage... 

Sounds as if you are concerned about running out of keycombinations - if that is the case - then a config screen where options could be toggled on/off may be a solution - just a suggestion
