### ISSUE TITLE
Only command line utils?

### ISSUE THREAD

**Issue by 875d** [jarun/nnn#1524]
I don't understand why [the wiki](https://github.com/jarun/nnn/wiki/Advanced-use-cases#cli-only-opener) says that the opener should invoke only CLI utils.

I've set it to `mimeo`, which can and do invoke GUI utils, and it is working perfectly fine.

**Comment by N-R-K** [comment]
It's not saying that the opener should invoke only CLI utils; it's saying that *if* your opener invokes only cli utils then you can pass the `-c` flag to nnn.

**Comment by 875d** [comment]
that section is unclear.

What is the advantage of passing `-c` to `nnn`?

I did it and my opener is calling GUI applications without problems.

It should be rephrased like "you can use any opener you want. if your opener calls only CLI applications, you can call `nnn` with the `-c` flag in order to [SPELL ADVANTAGE HERE]".

You think that everyone who doesn't understand is a rookie. it is never your fault.

**Comment by jarun** [comment]
No it has problems with certain GUI tools e.g. which log. It's just that you are not using one of those. Please follow the instructions.

**Comment by jarun** [comment]
If it's working for you, keep using.

**Comment by 875d** [comment]
I don't understand.

`nnn` works always, but `nnn -c` has problems with certain GUI tools?

Then why I should want to call `nnn -c` at all? Why not always call the version that works always?

There are no instructions to be followed. It just says "if it calls only CLI tools, use -c".

**Comment by jarun** [comment]
> nnn works always

No. It has problems with certain GUI tools which leave logs behind.

> Then why I should want to call nnn -c at all?

To use `nnn` with an opener that invokes cli tools only.

**Comment by 875d** [comment]
> To use nnn with an opener that invokes cli tools only.

And if I have an opener that invokes cli tools only, why I should use `nnn -c` instead of `nnn`?

**Comment by N-R-K** [comment]
There's some behavior differences when `-c` flag is used vs when it's not. It changes the spawned processes' stdin/stdout and changes weather nnn waits for the process to complete or not or something along those lines - though I don't remember the exact details. Will update the wiki once I figure it out.

**Comment by jarun** [comment]
I don't think we need to provide those details in the wiki. If someone is really interested, she can look into the code. Following a program option is not that difficult.

**Comment by 875d** [comment]
> I don't think we need to provide those details in the wiki. If someone is really interested, she can look into the code. Following a program option is not that difficult.

So we don't have the checks for the noobs, and we also don't have the docs for the pros.

When was the last time you had to dive in the source code to figure out what a command line switch is doing exactly?

**Comment by jarun** [comment]
We have explained what it is for:

    -c      cli-only NNN_OPENER

How it is done is in the code.
