### ISSUE TITLE
No errors if NNN_OPENER does not exist

### ISSUE THREAD

**Issue by 875d** [jarun/nnn#1525]
If `NNN_OPENER` points to a non-existing file, `nnn` doesn't throw any error.

I think an error should be thrown instead.

**Comment by jarun** [comment]
It's optional. System default is default and listed in wiki.

**Comment by 875d** [comment]
I don't understand the answer.

I know it's optional. But if you set it to a non-existing file, when you try to open a file nothing happens and you don't know why.

Instead I think it should throw an error.

**Comment by 875d** [comment]
And should check for the return code of the opener in any way (e.g. the opener does not have a mapping for that mimetype and returns an error).

**Comment by N-R-K** [comment]
Could probably do this:

```diff
diff --git a/src/nnn.c b/src/nnn.c
index e19cbe3f..3943e5b5 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -2345,6 +2345,7 @@ static int spawn(char *file, char *arg1, char *arg2, char *arg3, ushort_t flag)
 		}
 
 		execvp(*argv, argv);
+		fprintf(stderr, "%s: %s\n", *argv, strerror(errno));
 		_exit(EXIT_SUCCESS);
 	} else {
 		retstatus = join(pid, flag);
```

But you're not going to see the error msg until you exit/halt `nnn` since it's going to `stderr`.

**Comment by jarun** [comment]
OK, I got it now.

As @N-R-K pointed out you won't see the error immediately if we add the above one.

And I am not OK with adding a check at startup for novice user mistake. If files are not opening for you, the first thing you would check is the opener.
