### ISSUE TITLE
What does `e` open?

### ISSUE THREAD

**Issue by 875d** [jarun/nnn#1526]
I have both `VISUAL` and `EDITOR` set to nvim, but when I press `e` `nnn` opens its own editor. I don't know if it's `vi` or something?

In the wiki there is not written how to change the editor, if I'm not mistaken.

**Comment by 875d** [comment]
It looks like it's ignoring my env vars and always open in vi.

Even with `-e` and `-E` command line switches.

```
 -e      text in $VISUAL/$EDITOR/vi
 -E      internal edits in EDITOR
```

Also I have no idea what "text in $VISUAL" means. It puts the string "text" in the environment variable "$VISUAL"?

And what is an "internal edit"?

**Comment by N-R-K** [comment]
> I have both `VISUAL` and `EDITOR` set to nvim, but when I press `e` `nnn` opens its own editor.
> It looks like it's ignoring my env vars and always open in vi.

Shouldn't happen, how are you opening `nnn` exactly, are you sure it's inheriting the env vars?

> And what is an "internal edit"?

`nnn` may open up some temp file for editing, for example batch rename - I think it's referring to that.

**Comment by 875d** [comment]
My shell didn't export VISUAL and EDITOR to child processes.

Fixed now.

The documentation of this software is very cryptic.

"-e      text in $VISUAL/$EDITOR/vi"

-> "open text files in $VISUAL/$EDITOR/vi, instead of [PUT HERE WHAT HAPPENS WITHOUT THAT SWITCH]

**Comment by N-R-K** [comment]
Nothing special happens without the switch - the file gets passed to the default opener regardless of the type of the file.
