### ISSUE TITLE
How do I got to `,`?

### ISSUE THREAD

**Issue by 875d** [jarun/nnn#1527]
Since there is no "Discussion" tab, I ask here.

The doc says:
> B (,)  Book(mark)

It does not say what `,` does.

The [wiki](https://github.com/jarun/nnn/wiki/Usage#keyboard-mouse) says that `,` "marks a location in-memory" (footnote 2), and "pin CWD" (graphical map).

Despite the nice pun of having the (mark) of bookmarks corresponding to (,), I find it very confusing, since for the other keybindings, a space separate different keybindings of the same exact action, while here the action is different.

Then, how do I cd to the location marked by `,`? Where can I find this information in the doc and/or in the wiki?

**Comment by luukvbaal** [comment]
> The doc says:

>    B (,) Book(mark)

Read one column further:

    B (,)  Book(mark)           b ^/  Select bookmark

<kbd>B,</kbd> will bring you to the marked location.

**Comment by 875d** [comment]
Oh ok

**Comment by 875d** [comment]
I don't understand what's long/difficult with "`,` -> bookmark the current working directory in the `,` placeholder"

**Comment by jarun** [comment]
Space problem. Just try and learn.
