### ISSUE TITLE
nnn quits immediately if NNN_PLUG contains spaces

### ISSUE THREAD

**Issue by 875d** [jarun/nnn#1528]
#### Environment details (Put `x` in the checkbox along with the information)

- [X] Operating System: Arch Linux
- [X] Desktop Environment: Hyperland
- [X] Terminal Emulator: kitty
- [X] Shell: fish
- [X] Custom desktop opener (if applicable): mimeo
- [X] Program options used: none
- [X] Configuration options set:
```
alias nnn nnn_cd_on_quit
set -xg NNN_TRASH 1
set -xg NNN_FIFO /tmp/nnn.fifo
set -xg NNN_OPENER mimeo
```
- [X] Plugins are installed
- [X] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. Export `NNN_PLUG` to `p:preview-tui; d:dragdrop;`
2. Open `nnn`. It will print `NNN_PLUG` in the terminal and quit
3. Change `NNN_PLUG` to `p:preview-tui;d:dragdrop;`
4. Now it works

**Comment by jarun** [comment]
It's working as it is coded to. Please follow the examples.
The list is semicolon separated, not semicolon and space separated.

I can understand your enthusiasm in finding a new tool and trying to figure out loopholes.
Unfortunately, we do not have unlimited bandwidth to provide free service.

**Comment by 875d** [comment]
I disagree.

First, the wiki should specify to not put spaces after the semicolons (I understand that you can say "why we shouldn't specify also to not put @, è, %, or any other character after the semicolon? Put the space is more "intuitive" and provides for cleaner command, and you somehow "expect" it to work).

Second, and most importantly, nnn should print an error message, like "Invalid NNN_PLUG". And not just print "NNN_PLUG", it means nothing.

Useful error messages are very important.

**Comment by jarun** [comment]
It shows `NNN_PLUG` and exits which means the variable needs attention.

**Comment by jarun** [comment]
All list-type config options in `nnn` use `;` as the separator.
