### ISSUE TITLE
Updating plugin skip user question due to improper piping into bash

### ISSUE THREAD

**Issue by 875d** [jarun/nnn#1529]
#### Environment details (Put `x` in the checkbox along with the information)

- [X] Operating System: Arch Linux
- [X] Desktop Environment: Hyperland
- [X] Terminal Emulator: kitty
- [X] Shell: fish
- [X] Custom desktop opener (if applicable): mimeo
- [X] Program options used: none
- [X] Configuration options set:
```
alias nnn nnn_cd_on_quit
set -xg NNN_TRASH 1
set -xg NNN_FIFO /tmp/nnn.fifo
set -xg NNN_OPENER mimeo
```
- [X] Plugins are installed
- [X] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
0. Have a plugin to be updated. This requires old version of a plugin in `~/.config/nnn/plugins`
1. Run the command [here](https://github.com/jarun/nnn/tree/master/plugins#installation) 
```
curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh`
```
2. bash will ask what to do with the plugins that need an update, but move on to the next plugin without waiting for user input.
```
$ curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh
Plugin ./chksum already exists and is different.
Keep (k), merge (m), overwrite (o) [default: k]? Plugin ./imgview already exists and is different.
Keep (k), merge (m), overwrite (o) [default: k]? Plugin ./preview-tabbed already exists and is different.
Keep (k), merge (m), overwrite (o) [default: k]? Plugin ./preview-tui already exists and is different.
Keep (k), merge (m), overwrite (o) [default: k]? Plugin ./upload already exists and is different.
Keep (k), merge (m), overwrite (o) [default: k]? Plugin ./wallpaper already exists and is different.
Keep (k), merge (m), overwrite (o) [default: k]?
```
This is due to improper piping into bash. See [here](https://unix.stackexchange.com/questions/180383/piping-a-script-with-read-to-bash).

Solution: Change the command [here](https://github.com/jarun/nnn/tree/master/plugins#installation) to:
```
bash -c "$(wget -O - https://raw.githubusercontent.com/jarun
/nnn/master/plugins/getplugs)"
```

**Comment by jarun** [comment]
Please try and share a solution with `sh` and `curl`.

**Comment by 875d** [comment]
This seems to work:

```
sh -c "$(curl -Ls https://raw.githubusercontent.com/jarun/nn
n/master/plugins/getplugs)"
```

**Comment by jarun** [comment]
Thank you! Updated the docs.
