### ISSUE TITLE
disk usage mode with depth option ?

### ISSUE THREAD

**Issue by edi9999** [jarun/nnn#153]
I was currently using ncdu for disk usage analysis. 

In ncdu, after the scan is done, all information about each subfolders is retrieved from the beginning, thus, if I navigate between folders, I don't have to wait for the view to load.

With `nnn -S` , it seems that only 1 level of depth is loaded, so that I have to wait a bit everytime I move between folders, which I find quite annoying.

I think it would be better to either : 

1. Always preload disk usage of subfolders in the background, so that when you are in a view, if I hit enter to go into that directory, there is some chance that the analysis on that subfolder is already done.

2. Provide an option to say that I wish to preanalyze the full tree, not just at depth 1. Maybe with nnn -S --full-scan ?

What do you think ?

**Comment by edi9999** [comment]
What is slow is also just going up one directory, it seems that it tries to recalc the size even when I go up one dir, which I personally don't care about if I have to choose between this and speed.

**Comment by jarun** [comment]
if you have a modern L1/L2 cache, this would never go into the disk for the second rescan (if the contents don't change too much):

```
  ## Fired `nnn` in my home dir.
     - all cached, no major page faults
  
  ~$ /usr/bin/time -v nnn
  	Command being timed: "nnn"
  	User time (seconds): 0.00
  	System time (seconds): 0.00
  	Percent of CPU this job got: 0%
  	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:03.77
  	Average shared text size (kbytes): 0
  	Average unshared data size (kbytes): 0
  	Average stack size (kbytes): 0
  	Average total size (kbytes): 0
  	Maximum resident set size (kbytes): 3400
  	Average resident set size (kbytes): 0
  	Major (requiring I/O) page faults: 0
  	Minor (reclaiming a frame) page faults: 274
  	Voluntary context switches: 6
  	Involuntary context switches: 1
  	Swaps: 0
  	File system inputs: 0
  	File system outputs: 0
  	Socket messages sent: 0
  	Socket messages received: 0
  	Signals delivered: 0
  	Page size (bytes): 4096
  	Exit status: 0
  ~$
  
  ## Fired `nnn` on an external disk root in du mode, went into a subdir, came back to root.
     - no major page faults
     - File system inputs: 14680
     - 220 KB cached extra
  
  ~$ /usr/bin/time -v nnn -S /media/vaio/49462fdf-010c-40cc-89db-ef125e7dae99/tmp/
  	Command being timed: "nnn -S /media/vaio/49462fdf-010c-40cc-89db-ef125e7dae99/tmp/"
  	User time (seconds): 0.02
  	System time (seconds): 0.27
  	Percent of CPU this job got: 3%
  	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:08.30
  	Average shared text size (kbytes): 0
  	Average unshared data size (kbytes): 0
  	Average stack size (kbytes): 0
  	Average total size (kbytes): 0
  	Maximum resident set size (kbytes): 3620
  	Average resident set size (kbytes): 0
  	Major (requiring I/O) page faults: 0
  	Minor (reclaiming a frame) page faults: 337
  	Voluntary context switches: 576
  	Involuntary context switches: 2
  	Swaps: 0
  	File system inputs: 14680
  	File system outputs: 0
  	Socket messages sent: 0
  	Socket messages received: 0
  	Signals delivered: 0
  	Page size (bytes): 4096
  	Exit status: 0
  ~$
  
  ## Fired `nnn` again (around 2 mins later, I was formatting the above text) on the external disk root in du mode.
     - File system inputs: 0
  
  ** So even between 2 distinct instances of nnn, _all_ the data fetched in the first instance remained cached.
  
  ~$ /usr/bin/time -v nnn -S /media/vaio/49462fdf-010c-40cc-89db-ef125e7dae99/tmp/
  	Command being timed: "nnn -S /media/vaio/49462fdf-010c-40cc-89db-ef125e7dae99/tmp/"
  	User time (seconds): 0.00
  	System time (seconds): 0.01
  	Percent of CPU this job got: 0%
  	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.31
  	Average shared text size (kbytes): 0
  	Average unshared data size (kbytes): 0
  	Average stack size (kbytes): 0
  	Average total size (kbytes): 0
  	Maximum resident set size (kbytes): 3616
  	Average resident set size (kbytes): 0
  	Major (requiring I/O) page faults: 0
  	Minor (reclaiming a frame) page faults: 329
  	Voluntary context switches: 5
  	Involuntary context switches: 0
  	Swaps: 0
  	File system inputs: 0
  	File system outputs: 0
  	Socket messages sent: 0
  	Socket messages received: 0
  	Signals delivered: 0
  	Page size (bytes): 4096
  	Exit status: 0
  ~$
```

The second time it's almost instant for me.

To store level-based info, we need to store much more info and hence consume more memory. And also, we will lose any changes on a storage where content is changing dynamically.

So we will not have a static snapshot of du of a tree. if that's your use case, you should stick to ncdu, which is indeed a good utility.

**Comment by jarun** [comment]
Some additional notes:

> Provide an option to say that I wish to preanalyze the full tree, not just at depth 1. Maybe with nnn -S --full-scan ?

The behaviour is documented here (and linked from the README) [last but one point]: https://github.com/jarun/nnn/wiki/nnn-design-considerations
so i am not sure why anyone would expect anything else.

> What is slow is also just going up one directory, it seems that it tries to recalc the size even when I go up one dir, which I personally don't care about if I have to choose between this and speed.

You press `^J` to toggle the mode and move up. This is consistent with the behaviour - as it is not a one-time static snapshot, the recalc would happen on every traversal.
