### ISSUE TITLE
[Question] How to avoid coming back to the shell?

### ISSUE THREAD

**Issue by 875d** [jarun/nnn#1530]
I've made the following plugin:
```
s:-!echo $PWD/$nnn|wl-copy*
```
the "problem" is that, when I call it, it briefly goes back to the shell, and then to `nnn` again, and the screen flickers.

Is it possible to avoid for it to go back to the shell? Like running it in the background?

**Comment by jarun** [comment]
I don't think piping is possible in a plugin.

There are options to wait for a plugin: https://github.com/jarun/nnn/tree/master/plugins#running-commands-as-plugin-

**Comment by jarun** [comment]
You can add the whole command in a script and call the script from the plugin.
