### ISSUE TITLE
Opening a file doesn't work

### ISSUE THREAD

**Issue by raffaem** [jarun/nnn#1534]
Hi!

I use mimeo as my opener. I set it up to open `application/x-ipynb+json` with a certain script.

It works correctly from the command line, but when I try to open this mimetype in nnn, nothing happens.

How can I find out the problem?

**Comment by jarun** [comment]
`mimeo` is not supported as opener. See https://github.com/jarun/nnn/wiki/Usage#dependencies

Which DE and OS-es use it?

**Comment by raffaem** [comment]
it works if I call `nnn` with `nnn -c`
