### ISSUE TITLE
Environment variables not respected unless set in invocation command

### ISSUE THREAD

**Issue by raj-magesh** [jarun/nnn#1536]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Arch Linux
- [x] Desktop Environment: None (qtile as a Wayland compositor)
- [x] Terminal Emulator: kitty
- [x] Shell: fish
- [x] Custom desktop opener (if applicable): N/A
- [x] Program options used: N/A
- [x] Configuration options set: NNN_PLUG
- [x] Plugins are installed
- [x] Issue exists on `nnn` master (nnn-nerd from the AUR)

#### Exact steps to reproduce the issue

1. Open shell (with environment variable NNN_PLUG="p:preview-tui" set). Verify with `echo`.
2. Run `nnn`. Hit `p`, but no valid keys appear.
3. Run `NNN_PLUG=$NNN_PLUG nnn`. Everything works well.

This issue held for all environment variables and also occurred in bash (though my default shell is fish). Anything obvious I might be missing?

**Comment by jarun** [comment]
This is a local issue. Maybe the file is not sourced.

Try `export` follwed by `nnn` and verify.

**Comment by N-R-K** [comment]
> Anything obvious I might be missing?

Ensure you're actually exporting the env var.
