### ISSUE TITLE
What is the syntax for regex?

### ISSUE THREAD

**Issue by 875d** [jarun/nnn#1538]
The `-g` switches is documented as "use regex filters instead of substring match".

What is the syntax used for regex?

**Comment by N-R-K** [comment]
What do you mean by "syntax used for regex" ? Are you asking which regex flavor nnn uses or what?

**Comment by 875d** [comment]
> What do you mean by "syntax used for regex" ? Are you asking which regex flavor nnn uses or what?

Yes.

grep supports 3 different regex flavors.

I tried to use PCRE's "\d" with nnn to match a sigit but that won't work.

**Comment by N-R-K** [comment]
> I tried to use PCRE's "\d" with nnn to match a digit but that won't work.

Try compiling with `O_PCRE=1` which will use the pcre library. Otherwise it uses POSIX `regex.h` header - but the behavior might depend on libc. Some libc might support extensions.
