### ISSUE TITLE
Nested tmux session broke image preview using ueberzug

### ISSUE THREAD

**Issue by zzLinus** [jarun/nnn#1541]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Garuda Linux
- [x] Desktop Environment: DWM
- [x] Terminal Emulator: alacritty
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [x] Program options used:
- [x] Configuration options set:
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

The thing is that i ditch ranger and try to switch to nnn recently and i am getting used to it and it's a good replacement for ranger,and i am trying to fit nnn in to my work flow,so i try this [nnn.nvim](https://github.com/luukvbaal/nnn.nvim) vim plugin 
,it use `tmux new-session nnn -P<plugin-key>` to open tmux inside the picker float term window and can be used to open preview-tui inside the floating window,if i open a tmux session and open vim call this plugin,it will create a nested tmux session and the image preview is not showing,but if i open vim without tmux session and call the plugin, it show the image.

I tried `TMUX='' tmux new-session nnn -a -Pp` in shell and the nested tmux session not showing image either,so i think i should put this issue here.Is there any way to fix this,thank!

not nested
![tmux_notnested](https://user-images.githubusercontent.com/86963903/206989043-b4ea6a28-a595-4096-b795-3848e57f1292.png)

nested 
![tmux_nested](https://user-images.githubusercontent.com/86963903/206989084-434c360e-3882-4769-af14-928b4ae89b56.png)

**Comment by zzLinus** [comment]
If i omit `tmux new-session` the preview section will not appear in the float window,it's recommend by the nnn.nvim to do so.

![preview section](https://user-images.githubusercontent.com/86963903/207035024-583100ac-80b4-4704-abea-4678a79ded66.png)

**Comment by luukvbaal** [comment]
Right. Yeah I wrote the recommendation but I never considered the nested case. I'll see if something can be done about it.

**Comment by zzLinus** [comment]
Oh!I haven't realized the nnn.nvim is your repo😆Thanks!

**Comment by luukvbaal** [comment]
> I tried `TMUX='' tmux new-session nnn -a -Pp`

I would expect it to work with that command. I can't tell what's preventing ueberzug from drawing the images, the ueberzug tail is started normally by preview-tui.

**Comment by N-R-K** [comment]
Offtopic, but what font is that, if you don't mind me asking? @zzLinus

**Comment by zzLinus** [comment]
> Offtopic, but what font is that, if you don't mind me asking? @zzLinus
JetBrainsMono Nerd Font,you can find it from [here](https://www.nerdfonts.com/font-downloads)😉

**Comment by zzLinus** [comment]
> > I tried `TMUX='' tmux new-session nnn -a -Pp`
> 
> I would expect it to work with that command. I can't tell what's preventing ueberzug from drawing the images, the ueberzug tail is started normally by preview-tui.

Yeah,my first thought is the neovim float term issue,and i tired to use a common terminal emulator like alacritty/st,but i didn't shows the image too,i think i maybe putting this issue in the wrong place,it's more like a ueberzug-tmux specific issue

**Comment by luukvbaal** [comment]
I don't see how tmux could interfere with ueberzug tbh, it should bypass it completely. Ueberzug must not be receiving the draw instructions, but I don't see how.

**Comment by zzLinus** [comment]
I just find out ueberzug maintainer delete the repo😣,so said to see FOSS maintainer give up to their project due to peoples don't respect the work piss them off.....I am considering change my terminal to kitty or find another preview software,because i don't think ueberzug have a reliable fork

**Comment by luukvbaal** [comment]
Yeah it's unfortunate, tmux + ueberzug is still noticeably faster than kitty for me.

**Comment by zzLinus** [comment]
![test](https://user-images.githubusercontent.com/86963903/207180554-302fb29a-fe0b-4cbb-bed4-c8efe086a93d.png)

I tried make a simple .sh like
``` bash
ueberzug layer --parser bash 0< <(
    declare -Ap add_command=([action]="add" [identifier]="example0" [x]="0" [y]="8" [path]="/home/zzlinus/Meme.png")
    sleep 5
    declare -Ap remove_command=([action]="remove" [identifier]="example0")
    sleep 5
)
```
and run it under nested tmux,it's not showing the image
I don't think it's preview-tui's issue 🤔

**Comment by luukvbaal** [comment]
Yeah I also confirmed the ueberzug FIFO is being written to normally by preview-tui. I guess ueberzug fails to identify the child window correctly in a nested tmux session.
