### ISSUE TITLE
No icons when starting inside screen 

### ISSUE THREAD

**Issue by arisolt** [jarun/nnn#1544]
Hi, 

nnn is compiled with O_NERD=1. In a new terminal window, starting nnn displays icons correclty. However, when starting nnn from within a `screen` window, the icons aren't visible. Also, no colours are being used. Any idea why?

On the other hand, running the following test for 256-colour support from within a `screen` window, works as expected.
`curl -s https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/e50a28ec54188d2413518788de6c6367ffcea4f7/print256colours.sh | bash`

So my `screen` has support for 256 colours. Not sure if that would affect the icons, tho.

**Comment by N-R-K** [comment]
Ensure your `$TERM` variable is set correctly.

**Comment by arisolt** [comment]
> Ensure your `$TERM` variable is set correctly.

Thank you. This does indeed enable both colors and icons. The solution for `screen` is to add the following line in `~/.screenrc` (create it if it doesn't exist):
```
term screen-256color
```
To confirm, from within a `screen` window type `echo $TERM`.
