### ISSUE TITLE
Screen flash when paste or move

### ISSUE THREAD

**Issue by beautiful-boyyy** [jarun/nnn#1548]
![output](https://user-images.githubusercontent.com/66351806/209460720-daec50bf-59ac-4412-bc8a-716755beb94f.gif)

**Comment by 0xACE** [comment]
Not a bug, `nnn` launches `cp` or `mv` which what you are seeing, if you move a larger file to an external partition, you should see that `nnn` freezes in that state even longer

**Comment by beautiful-boyyy** [comment]
> Not a bug, `nnn` launches `cp` or `mv` which is what you are seeing, if you move a larger file to an external partition you should see that `nnn` freezes in that state even longer

Is there a way to make these opt silent?

**Comment by 0xACE** [comment]
I guess you could patch the `nnn` source on your own, alternatively write script that handles these longer operations.

`nnn` does not provide built-in support for this feature.

You could bring it up over at #1545 but chances are that it will not be supported in the `master` branch
