### ISSUE TITLE
Split $NNN_PLUG into multiple lines method?

### ISSUE THREAD

**Issue by rieje** [jarun/nnn#1549]
I know you can split `$NNN_PLUG` like this:

    NNN_PLUG_DEFAULT='f:fzopen;v:imgview;g:getplugs;c:diffs;d:dragdrop'
    NNN_PLUG_INLINE='x:!chmod u+x $nnn;t:-!tree -a $nnn;u:!unlink $nnn'
    NNN_PLUG="$NNN_PLUG_DEFAULT;$NNN_PLUG_INLINE"

but it's still not as readable as something like this:
  
    # my $NNN_PLUG is much longer
    export NNN_PLUG="\
    a:-!mpv --vid=no --term-osd-bar '$nnn'*;\
    d:-!|du-all '$nnn';\
    e:-!&losslesscut '$nnn';\
    i:-!|mediainfo '$nnn'"

The latter easily shows what keybindings are defined and therefore what keybindings are free for adding plugins.

But I'm not sure why it doesn't work--the value of `$NNN_PLUG` is in double quotes for `;\` to split the lines, so I add single quotes around `$nnn` to prevent it from expanding in the double quotes. This is in bash. Is there something I'm missing for the shell or does nnn not support this? Thanks.

**Comment by jarun** [comment]
Sorry, no bandwidth to work on shell quirks anymore.

**Comment by KlzXS** [comment]
@rieje `nnn` expects `:` right after a binding and the binding to be the first character of the string (overall and after each `;`). You can't have newline characters as you've shown.

You can create a new script to manage your bindings and convert them into the format we expect if you want to have an overview of unused bindings.

**Comment by lawnowner** [comment]
@rieje `\` has the special meaning for the shell as the escape character when it is either unquoted or in double quotes, and only when followed by one of the characters ``\ $ ` ! " NL``. If you want to type your variable assignment like that, escape the NL outside quotes:

    export NNN_PLUG=\
    'a:aplug;'\
    'b:bplug;'\
    'z:zplug;'

**Comment by rieje** [comment]
@lawnowner Works perfect, thank you!
