### ISSUE TITLE
Joystick support using UDEV or SDL2?

### ISSUE THREAD

**Issue by vanfanel** [jarun/nnn#1550]
**Describe the solution you'd like**

Could joystick usage for file browsing be added? Using udev or SDL2 would be good options, as none of them depend specifically on a graphics server.

**Additional context**

I find myself more and more setting NNN on my family & friends Raspberry Pi systems to save them from using commands for launching native and emulated games on a Wayland enviroment.
Letting people using joystick with NNN would eliminate the need for a keyboard attached to the system.

**Comment by jarun** [comment]
No plans, thanks. Just too many keybinds.
