### ISSUE TITLE
Notification system for plugins

### ISSUE THREAD

**Issue by raffaem** [jarun/nnn#1552]
Currently plugins have various ways to have switch on notification.

Most of them have code you need to comment out if you want notification. `kdeconnect` has an internal variable you need to set to 1.

I think this should be governed centrally by the `-x` command line switch.

nnn should send the `NNN_OPTS` env variable to the sub-shell that run the plugins, or ad-hoc create one by merging the command line switches if the user is using command line switches rather than the environment variable.

The plugins can then check the exported `NNN_OPTS` environment variable and look for the `x` flag.

**Comment by N-R-K** [comment]
Most of the plugins available in this repo are more closer to examples than being fully-featured. So we probably don't want to over-complicate things for cosmetic purposes.

**Comment by jarun** [comment]
Yes, plugins are indicative. We try to stay away from GUI deps as much as possible.
