### ISSUE TITLE
nnn config as on the demo gif

### ISSUE THREAD

**Issue by webcaptcha** [jarun/nnn#1556]
Hi. I'm getting known with nnn and for some reason hard to find config files as start up point. No sub-reddit no popular repo with config.

Is it a way I can get config that was use to record a demo on the main page of the repo?

**Comment by KlzXS** [comment]
@luukvbaal as far as I can see the demo was yours. Do you have anything you are willing to share?

@webcaptcha there are no config files. It's all source code modification, custom/modified plugins and maybe some .bashrc aliases or some such. If you want custom colors, icons and other cosmetics refer to the [wiki](https://github.com/jarun/nnn/wiki) on how to get started.

**Comment by N-R-K** [comment]
> Is it a way I can get config that was use to record a demo on the main page of the repo?

The demo was using the `preview-tui` plugin (with tmux) AFAIK.

**Comment by jarun** [comment]
@webcaptcha please don't raise issues for `how to do` questions. Use the discussion threads.
