### ISSUE TITLE
preview-tabbed focus doesn't work on Wayland

### ISSUE THREAD

**Issue by aryadovoy** [jarun/nnn#1558]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Fedora Linux 37 (KDE Plasma) x86_64
- [x] Desktop Environment: Plasma 5.26.4
- [x] Terminal Emulator: alacritty
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable): nuke
- [x] Program options used: CdroQxU
- [x] Configuration options set: `NNN_FIFO=/tmp/nnn.fifo`
- [x] Plugins are installed: all
- [x] Issue exists on `nnn` master: yes

#### Exact steps to reproduce the issue

Installed `xdotool` but it works strange and focus are not working. Think that it's secure issue of Wayland, but not sure.
@leovilok, what do you think?

This's output of `xdotool windowactivate "$MAINWINDOW"`:

```shell
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x0
  Serial number of failed request:  26
  Current serial number in output stream:  26
```

**Comment by jarun** [comment]
Also adding @N-R-K and @luukvbaal.

**Comment by aryadovoy** [comment]
And have found that [this feature](https://github.com/jarun/nnn/wiki/Concepts#file-paths-in-selection-to-system-clipboard) doesn't work too. Suppose that it should be bonded to [wl-clipboard](https://github.com/bugaevc/wl-clipboard)

**Comment by leovilok** [comment]
@aryadovoy you're right: a lot of `xdotool` features are made impossible on wayland for security reasons.

We only use `xdotool` to make sure the right window is focused, so the plugin *might* work without it. But I suspect that `tabbed` won't work on wayland either, as embedding a window in another window shouldn't happen in Wayland.

**Comment by leovilok** [comment]
I tried it on Wayland (sway WV), without the `xdotool` lines: it completely freezes and lock my wayland session.

I tried `tabbed` itself (embedding `urxvt`): surprisingly, it almost works, but I still get a lot of freezes.

I don't know how it would behave on other wayland compositor (I don't know if their `xwayland` implementation is different), but I think it's safe to say that none of this is supported on Wayland.

I guess we could make it explicit in the plugin comment header, we could even abort on wayland session detection, if we want to avoid annoying freezes.

**Comment by leovilok** [comment]
> And have found that [this feature](https://github.com/jarun/nnn/wiki/Concepts#file-paths-in-selection-to-system-clipboard) doesn't work too. Suppose that it should be bonded to [wl-clipboard](https://github.com/bugaevc/wl-clipboard)

This is not related to `preview-tabbed`, and `wl-copy` support is supposedly built in, see https://github.com/jarun/nnn/blob/master/plugins/.cbcp#L29

**Comment by N-R-K** [comment]
> Also adding @N-R-K and @luukvbaal.

I can't really help here since I gave up on wayland long ago due to how (intentionally) crippled it's design is (and I'm trying to be nice here). Just exiting early (#1559) looks fine to me.
