### ISSUE TITLE
Entering a directory while in select mode turns it off

### ISSUE THREAD

**Issue by mcchrish** [jarun/nnn#156]
So selecting multiple files from several directories doesn't work.

**Comment by jarun** [comment]
That's not supported in 'nnn'.

**Comment by mcchrish** [comment]
I see. I don't use it a lot, but could be handy when trying to load related files from different directories into the buffer.

**Comment by jarun** [comment]
I would think about it.

**Comment by jarun** [comment]
I have added the support. Check it out!

**Comment by ln-nl** [comment]
@jarun Seems like indication with '+' does not survive changing directory

**Comment by jarun** [comment]
That's right. Because there's no simple way to retain all the filenames which are copied and match those while loading the files of a new directory. It kills the performance.
