### ISSUE TITLE
Option to Sort by Modification Time in addition to Creation Time

### ISSUE THREAD

**Issue by hasnolen** [jarun/nnn#1560]
**Is your feature request related to a problem? Please describe.**

I was hoping to easily select all files I'd recently AirDropped into my `~/Downloads` folder. However, AirDrop apparently preserved the **creation** time of the files, but not the **modification time** of the files. 

Happily, the ones I just AirDropped were then visible as highlighted. **However**, these were _not_ all at the top when reverse-sorting by time `nnn -T t`, meaning I had to hunt for them one-by-one.

**Describe the solution you'd like**

An option, `nnn -t m`  which sorts by _modification_ time, or at least whatever criteria is used for highlighting here:
https://github.com/jarun/nnn/blob/master/src/nnn.c#L5799-L5800

(looks like modification time _or_ creation time). 

**Describe alternatives you've considered**
Unfortunately, AirDrop chooses the file name, and it's impossible to use a folder other than `~/Downloads` for AirDrop receipts, so the images I moved will inevitably be dispersed among my other random downloads. A workaround _could_ be to force all my browsers to use a different downloads directory, but that would be a pain and also require changing some other helper scripts I set up to manage the `~/Downloads` folder.

**Comment by N-R-K** [comment]
I'm pretty sure that `nnn` defaults to modification time when sorting. You can verify it easily:

```console
$ touch $(seq 0 3)
$ nnn -Tt
$ touch 2
$ nnn -Tt
```

The code snippet you linked has nothing to do with sorting, it's for detecting "young" files.

**Comment by N-R-K** [comment]
Okay, I already see the mistake: `nnn -t T` that's not the correct flag `-t` is for timeout. For sorting you need `-T` and the argument should be `-t`.

**Comment by N-R-K** [comment]
@jarun opinion on using something like `strtol` instead of `atoi` for user supplied numbers so we can detect errors and raise a warning for invalid arguments?

https://github.com/jarun/nnn/blob/2b6fb3f388552338b6d45e69b2da5e6959ea8058/src/nnn.c#L8532-L8535

**Comment by hasnolen** [comment]
> Okay, I already see the mistake: `nnn -t T` that's not the correct flag `-t` is for timeout. For sorting you need `-T` and the argument should be `t`.

Oops, actually I am using `nnn -T t`, and I just misremembered.

> The code snippet you linked has nothing to do with sorting, it's for detecting "young" files.

I know. What it **does** have to do with, as I said, though, was: 

> whatever criteria is used for **highlighting** here:
https://github.com/jarun/nnn/blob/master/src/nnn.c#L5799-L5800

**Comment by hasnolen** [comment]
> I'm pretty sure that nnn defaults to modification time when sorting. 

Yes, this is correct and so the premise of this issue is probably moot. Let me open a new ticket for cleanliness.

**Comment by jarun** [comment]
@N-R-K I don't want to add cosmetic logic. Just because a user can't pass flags correctly (which he may fix in 3/4 attempts), I don't want to make a change to an otherwise stable code.
