### ISSUE TITLE
Inconsistent highlighting vs. sorting of recently modified/changed files. 

### ISSUE THREAD

**Issue by hasnolen** [jarun/nnn#1562]
#### Environment details 

- [x] Operating System:  macOS 13.0 22A380 arm6
- [x] Desktop Environment: Aqua
- [x] Terminal Emulator: iTerm2 Build 3.4.19
- [x] Shell: `zsh 5.8.1 (x86_64-apple-darwin22.0)`
- [x] Program options used:
```bash
n () {
        if [ -n "$NNNLVL" ] && [ "${NNNLVL:-0}" -ge 1 ]
        then
                echo "nnn is already running"
                return
        fi
        export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
        export NNN_PLUG='g:! greadlink -f $nnn | tr -d "\n" | pbcopy*'
        nnn -T t -d -x "$@"
        if [ -f "$NNN_TMPFILE" ]
        then
                . "$NNN_TMPFILE"
                rm -i -f "$NNN_TMPFILE" > /dev/null
        fi
}
```

- [x] Configuration options set:
`make -B O_NERD=1 O_NOMOUSE=1 O_GITSTATUS=1`

- [x] Plugins are installed
```bash
autojump
bookmarks
boom
bulknew
cdpath
chksum
cleanfilename
diffs
dragdrop
dups
finder
fzcd
fzfasd
fzhist
fzopen
fzz
getplugs
gpgd
gpge
gutenread
hexview
imgresize
imgthumb
imgur
imgview
ipinfo
kdeconnect
launch
mediainf
mimelist
moclyrics
mocplay
mp3conv
mtpmount
nbak
nmount
nuke
oldbigfile
organize
pdfread
pdfview
picker
preview-tabbed
preview-tui
preview-tui-ext
pskill
renamer
ringtone
rsynccp
splitjoin
suedit
togglex
treeview
uidgid
upgrade
upload
vidthumb
wall
x2sel
```

- [x] Issue exists on `nnn` master:  as of `2b6fb3f3`

- [x] Additional env properties

```bash
❯ gtouch --version
touch (GNU coreutils) 9.1 

❯ gstat --version
stat (GNU coreutils) 9.1
```

#### Exact steps to reproduce the issue

```bash
$ gtouch test
# make file appear modified more than 300 seconds ago (highlighting threshold)
$ gtouch -d "Sat, 07 Jan 2023 13:18:28 -0800" test
# create helper
$ n () {
        if [ -n "$NNNLVL" ] && [ "${NNNLVL:-0}" -ge 1 ]
        then
                echo "nnn is already running"
                return
        fi
        export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
        export NNN_PLUG='g:! greadlink -f $nnn | tr -d "\n" | pbcopy*'
        nnn -T t -d -x "$@"
        if [ -f "$NNN_TMPFILE" ]
        then
                . "$NNN_TMPFILE"
                rm -i -f "$NNN_TMPFILE" > /dev/null
        fi
}

$ n
```

witness: the file `test`'s timestamp is highlighted, even though the most "recent" (by sorting) is _not_
<img width="541" alt="image" src="https://user-images.githubusercontent.com/95154022/211451559-44c47a9f-6fc1-48c9-a379-75449b6e3e32.png">

See https://github.com/jarun/nnn/issues/1560#issuecomment-1376633114  for more context.

**Comment by hasnolen** [comment]
Ok, I think I see what _might_ be a related phenomenon: there's a concept of both "Changed" _and_ "Modified" which are (somehow) considered to be different properties of a file (??). 

When doing `gtouch -d`, it does not touch the "Changed" timestamp:
```bash
❯ gstat test
  File: test
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 1,18    Inode: 105544825   Links: 1
Access: (0644/-rw-r--r--)  Uid: (  501/isaacjoseph)   Gid: (   20/   staff)
Access: 2023-01-07 13:18:28.000000000 -0800
Modify: 2023-01-07 13:18:28.000000000 -0800
Change: 2023-01-09 19:04:44.194594091 -0800  # NOTE: STILL RECENT
 Birth: 2023-01-07 13:18:28.000000000 -0800 
```

**Comment by hasnolen** [comment]
Oh I see, looks like `"Change"` is for changes [to the _metadata_ of the file](https://unix.stackexchange.com/questions/2464/timestamp-modification-time-and-created-time-of-a-file), which apparently _are_  being picked up by highlight but not by sorting?

**Comment by hasnolen** [comment]
Ok, `ls` has the `-c` flag: 

> ```bash
>        -c     with -lt: sort by, and show, ctime (time of last modification of
>               file status information); with -l: show ctime and sort by name;
>               otherwise: sort by ctime, newest first 
> ```

sucht hat `ls -clt`'s ordering is consistent with the highlighting. This bug could be construed as a feature request for `ctime` ordering, but I think it's arguably better construed as a bug for highlighting.

**Comment by jarun** [comment]
The sort order `t` is by default for modification time.
You can change it to access time or change time at runtime using the key `T`.

However, this has no bearing with the newer files for which timestamps are highlighted. A highlight in the timestamp means the file is either created OR modified within a certain threshold (5 minutes). So you can't have the highlighted files sorted by both modification or creation time with a single sort order. There is nothing to be confused here.
