### ISSUE TITLE
implementing a plugin

### ISSUE THREAD

**Issue by ghistes** [jarun/nnn#1564]
Hi,

it is unclear to me how a plugin-script  can get the directory of the hovered file.

I have tried with a script that simply outputs all arguments to a temp-file and configured it as a plugin via NNN_PLUG='n:!/path/to/script $nnn*'.

When configured like this the script receives exactly one argument - the filename (not the full path) of the file that nnn had selected when the plugin was started (i.e. the $nnn argument). Nothing else gets passed.

My question (as the documentation talks about the directory-name being passed as an argument):

Do I have to setup the plugin differently or what is the way for a plugin to get the full path of the hovered file?

Sorry for probably just not understanding the documentation...

**Comment by N-R-K** [comment]
> I have tried with a script that simply outputs all arguments to a temp-file and configured it as a plugin via NNN_PLUG='n:!/path/to/script $nnn*'.

The `!` command is for running a command as a plugin. If you're trying to run a script then you shouldn't set it. Use this: `NNN_PLUG='n:script'` and put `script` in the appropriate directory (~/.config/nnn/plugins).

**Comment by jarun** [comment]
@ghistes please ask questions in discussion threads.
