### ISSUE TITLE
Nothing happens when pressing help key (big terminal, less pager with -F option)

### ISSUE THREAD

**Issue by matclab** [jarun/nnn#157]
Pressing `?`  (`SHIFT+,`) or `D` does nothing.

**Comment by jarun** [comment]
fr == french?

**Comment by jarun** [comment]
And which shortcut is `SHIFT+,`?

**Comment by jarun** [comment]
I don't know French so you'll have to help yourself here. Compile `nnn` in debug mode (`make debug`) and the keycode will be printed here: github.com/jarun/nnn/blob/master/src/nnn.c#L1051

The ascii code of `?` shouldn't change but see what you find for these keys.

**Comment by matclab** [comment]
Ok. In fact it works when my terminal (tilix) is not full screen.
So it is not a problem of the key but a problem of integration between nnn, the terminal and the pager…

I tried with xterm and I have the same problem.

Pressing `?` I sometime see the help flashing very briefly.

**Comment by jarun** [comment]
Awesome! Many thanks!

**Comment by jarun** [comment]
@matclab I have added support for 1 env var combination for PAGER, LESS and SHELL on latest master.

So now (on fish shell) I can run:

    env PAGER='less -FSRXIj.2' nnn

**Comment by ahmedelgabri** [comment]
I have the same issue, I tried both [`kitty`](https://github.com/kovidgoyal/kitty) & [`alacritty`](https://github.com/jwilm/alacritty) & my `$PAGER` is set to `less` only. I'm running macOS Mojave 10.14.2

**Comment by jarun** [comment]
Please try master.
Also, if it doesn't work please try to debug yourself. Debugging local env specific issues is too taxing for the bandwidth we have. Thanks for your understanding.

**Comment by jarun** [comment]
Use the debug build 'make debug'

add logs. the debug log filr would be in /tmp/nnndbg

**Comment by ahmedelgabri** [comment]
One thing I forgot to mention, that when I quit `nnn` after trying `?` multiple times, is that the help is already printed `n` times in the commandline. Where `n` is the number of times I clicked `?` inside `nnn`.

Anyway that's what I did to debug, not sure if I missed anything.

### Steps:

- `make debug`
- Open `nnn` 
- type `?` to get `help` _(2-3 times)_
- quit

#### logfile

```
dents=0x7fb94c95a200
pnamebuf=0x7fb94d000000
ts2.tv_nsec - ts1.tv_nsec=421000
fname=
cur=0
path=/private/tmp/nnn
c=-1
cur=0
path=/private/tmp/nnn
c=63
ts2.tv_nsec - ts1.tv_nsec=227000
fname=nnn.dSYM
cur=0
path=/private/tmp/nnn
c=63
ts2.tv_nsec - ts1.tv_nsec=181000
fname=nnn.dSYM
cur=0
path=/private/tmp/nnn
c=63
ts2.tv_nsec - ts1.tv_nsec=124000
fname=nnn.dSYM
cur=0
path=/private/tmp/nnn
c=63
ts2.tv_nsec - ts1.tv_nsec=121000
fname=nnn.dSYM
cur=0
path=/private/tmp/nnn
c=-1
cur=0
path=/private/tmp/nnn
c=113
```

**Comment by fintelkai** [comment]
FWIW, I encountered the same problem. In my environment setup, I had the `less` options set as `LESS=-iRFXMx4`. It's the `F` that creates the problem with displaying the help from `nnn`. I just got rid of it and now I see the help (instead of it just showing up in my scroll history after quitting `nnn`).

**Comment by ahmedelgabri** [comment]
@fintelkai just tried & I confirm that it fixed the issue. Thanks!

**Comment by jarun** [comment]
So 2 years passed and I missed this! I will add this in the troubleshooting section of the Wiki!

Thanks @fintelkai for following up!

**Comment by jarun** [comment]
Ahh OK. I see I chose to ignore as I suspected local environment issues. Anyway, I will add this in the Wiki.
