### ISSUE TITLE
chksum incorrect return

### ISSUE THREAD

**Issue by 875d** [jarun/nnn#1572]
When trying to verify a `md5` file with `chksum`:

```
/home/[USERNAME]/.config/nnn/plugins/chksum: line 64: return: can only `return' from a function or sourced script
```

We probably need `exit` instead

**Comment by N-R-K** [comment]
What's your `sh` shell? I'm using `dash` and it seems to work fine. Not saying we shouldn't change to `exit`, but I'm just curious.

**Comment by 875d** [comment]
```
❯ /usr/bin/sh --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```

**Comment by N-R-K** [comment]
Hmm, yeah. I can reproduce it on bash:

```
[nnn nrk]~> bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
```

**Comment by 875d** [comment]
> Hmm, yeah. I can reproduce it on bash:
> 
> ```
> [nnn nrk]~> bash --version
> GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
> ```

You know POSIX sh.

So either fix it or report to GNU bash.

**Comment by N-R-K** [comment]
> You know POSIX sh.

I don't. Only bits and pieces, so I don't know if it's a valid shell code or not.

**Comment by KlzXS** [comment]
From what I can see `return` is part of POSIX. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#return

To me `checksum_type()` definitely looks like a function. I don't know why it would complain about this.

**Comment by N-R-K** [comment]
That return isn't part of `checksum_type()`.

**Comment by 875d** [comment]
> checksum_type()



> From what I can see `return` is part of POSIX. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#return
> 
> To me `checksum_type()` definitely looks like a function. I don't know why it would complain about this.

The `return` it complains about is not inside `checksum_type()`

**Comment by 875d** [comment]
@N-R-K don't you have write access?

**Comment by KlzXS** [comment]
Oh, my bad. Then that's why. It must be inside of a function or "dot script".

**Comment by N-R-K** [comment]
Jarun typically does the merging. I don't know what the policy is towards collaborators directly pushing into `master` but I'd rather not do that unless I've been given explicit permissions.

**Comment by KlzXS** [comment]
I found it. See (#)552 for the rationale behind opening PRs for anything and everything, it's at the end.
