### ISSUE TITLE
sort order differs from ls

### ISSUE THREAD

**Issue by elandorr** [jarun/nnn#1577]
nnn 4.7

Reading issues on this tracker, I saw people use the C locale to get a more usable sort order. I need a character that is always on top. As the C collation apparently sorts by ASCII code, I expected `!` to serve this purpose. On windows, `_` is common.

```
LC_COLLATE=en_US.UTF-8
ls -l
'!'
 _
 1
 10
 11
 12
 2
 3
 a1
 a10
 a11
 a12
 a2
 a3
```

```
LC_COLLATE=C
ls -l
'!'
 1
 10
 11
 12
 2
 3
 _
 a1
 a10
 a11
 a12
 a2
 a3
```

`nnn` ignores it all:

```
LC_COLLATE=en_US.UTF-8
1/
2/
3/
10/
11/
12/
!/
_/
a1/
a10/
a11/
a12/
a2/
a3/
```

```
LC_COLLATE=C
1/
2/
3/
10/
11/
12/
!/
_/
a1/
a10/
a11/
a12/
a2/
a3/
```

`nnn` is run via

```
n is a function
n () 
{ 
    if [[ "${NNNLVL:-0}" -ge 1 ]]; then
        echo "nnn is already running";
        return;
    fi;
    NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd";
    \nnn -A "$@";
    if [ -f "$NNN_TMPFILE" ]; then
        . "$NNN_TMPFILE";
        rm -f "$NNN_TMPFILE" > /dev/null;
    fi
}
```

What's going on?

My 'ideal' sort order would be the ls with en_US.UTF-8, but with natural numerics (1 2 3 10 11, possibly a1 a2 a3 a10 a11)

Thanks!

**Comment by N-R-K** [comment]
`nnn` uses natural sort and numeric names being on top is also intended behavior:

https://github.com/jarun/nnn/blob/d0631707fc490cc9beb6a51f3c0342d2dc613b15/README.md?plain=1#L73-L75

**Comment by elandorr** [comment]
So all of these issues are outdated? https://github.com/jarun/nnn/issues/203 etc

**Comment by N-R-K** [comment]
> So all of these issues are outdated? https://github.com/jarun/nnn/issues/203 etc

Perhaps. I don't know what `nnn` did 3~4 years ago - but as of now: numeric values will always be prioritized - which is a feature (but it seems to be a feature that you don't want).

If you comment out these two lines, I think you'll get the behavior that you're looking for:

```diff
diff --git a/src/nnn.c b/src/nnn.c
index d8d98d8b..659648a4 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -2797,14 +2797,6 @@ static int xstricmp(const char * const s1, const char * const s2)
 			if (v1 > v2)
 				return 1;
 		}
-
-		/* Only first string non-numeric */
-		if (s1 == p1)
-			return 1;
-
-		/* Only second string non-numeric */
-		if (s2 == p2)
-			return -1;
 	}
 
 	/* Handle 1. all non-numeric and 2. both same numeric value cases */
```

**Comment by elandorr** [comment]
Thank you for checking. I'd rather stick with upstream, because the list of configs/patches things to maintain is already extensive. Adding one small fix inevitably leads to having to study nnn too.

If locale really is not used anymore, we should fix the wiki.

I've added a hidden file. They behave oddly as well.

https://github.com/jarun/nnn/wiki/Basic-use-cases#hidden-files-on-top

With en_US.UTF-8:
```
1/
2/
3/
10/
11/
12/
!/
_/
a1/
a10/
a11/
a12/
a2/
a3/
.foo/
f1
f10
f2
.h1
.h2
```

With C:
```
1/
2/
3/
10/
11/
12/
!/
.foo/
_/
a1/
a10/
a11/
a12/
a2/
a3/
.h1
.h2
f1
f10
f2
```
So locale does still have an effect. And the .foo dir is in no man's land.

**Comment by N-R-K** [comment]
> If locale really is not used anymore, we should fix the wiki.

Locales are still used as a fallback, but the specific wiki section you mentioned indeed seems to be outdated. Thanks for reporting, I've [removed it](https://github.com/jarun/nnn/wiki/Basic-use-cases/_compare/9c2a45e6ee9c148d68bcbc73e4424ef5a856cde1...170f071bf63c9e6c66d639919c7260d8750a4a0c) from the wiki.

**Comment by jarun** [comment]
Marking closed.

**Comment by elandorr** [comment]
Not sure why you'd call this 'completed'. It's still unclear what the current situation is.

Behavior is affected by locale in an unclear manner, the deleted wiki entry has no follow-up, etc.

**Comment by jarun** [comment]
We don't have time to change the way things are today. `nnn` uses a way that depends on locale and we never had `ls` in mind for sorting.

**Comment by N-R-K** [comment]
> What is the way things are, though?

It works as stated in the README.

1. Numerics have higher priority
2. But if neither of the operands have numerics then they're compared according to locale.

**Comment by elandorr** [comment]
The [README](https://github.com/jarun/nnn/blob/3739aab578318bbc373e1def2303a0af04e0b081/README.md) doesn't mention locale, but thanks for clarifying.
