### ISSUE TITLE
Documentation for plugins in wiki

### ISSUE THREAD

**Issue by 875d** [jarun/nnn#1582]
Currently the documentation for the software is spread in different places.

I think `plugins/README.md` should be merged in the wiki.

At the very least, the wiki should point to it.

Also in
> To assign keys to arbitrary non-background cli commands and invoke like plugins, add ! (underscore) before the command.

`underscore` should be `exclamation mark`

**Comment by jarun** [comment]
Removed the _underscore_.
Linked the plugins page here: https://github.com/jarun/nnn/wiki/Usage#plugins

**Comment by 875d** [comment]
Thank.

Also "Get, Set, Go!" should be "Usage".
