### ISSUE TITLE
Leader Key on Mac OS

### ISSUE THREAD

**Issue by InfiniteStyles** [jarun/nnn#159]
I can't seem to get the leader key working on Mac OS Mojave using Iterm2. Any ideas?
Appreciate any help. I really like this tool.

**Comment by jarun** [comment]
There are 2 different keys for leader key: ``` and `^/`. Do none work for you?

**Comment by jarun** [comment]
@kjnez do you see this issue as well?

**Comment by kjnez** [comment]
I never used it before :(

But if I type in ` or ^/ in the terminal and press 2 or 3, the highlight changes accordingly.

**Comment by jarun** [comment]
Yes, it's working for you. So @InfiniteStyles is probably having a local env issue which he might have to figure out himself.

**Comment by InfiniteStyles** [comment]
@jarun It's strange, because actually leader key + [1-4] is working to switch the context, yet, for example, leader key + G (^G) or any of the other (^H,^Q,^M) keys aren't working. Any thoughts?

**Comment by InfiniteStyles** [comment]
Nevermind, got it all working 🙂. Thanks.

**Comment by jarun** [comment]
Can you explain the problem here for our records? There help later users and for reference.

**Comment by InfiniteStyles** [comment]
I guess my issue now is specifically with '^G' (cntr+G) on mac, not quitting and changing to the directory and instead saying 'SET NNN_TMPFILE' at the bottom.
Previously I thought ^ stood for _Leader Key_ because of the close resemblance.

**Comment by jarun** [comment]
> Can you explain the problem here for our records?

I was referring to the original issue

> I guess my issue now is specifically with '^G' (cntr+G) on mac

It's explained [here](github.com/jarun/nnn#cd-on-quit) and people are using it without any issues on Mac so I guess it works fine. Please follow the steps verbatim.
