### ISSUE TITLE
mpv sixel/kitty support for preview

### ISSUE THREAD

**Issue by mia-0** [jarun/nnn#1590]
So I don’t use nnn but I’ve added kitty support to mpv a while ago and I’m using it in a [TUI moderation app for my file hoster 0x0.st](https://git.0x0.st/mia/0x0/src/branch/master#moderation-ui), so I thought you might be interested in this as an alternative to XEmbed.

In short, with the “buffered” options of its sixel/kitty video outputs, mpv can run “embedded” in other TUI applications to provide video previews. In my app, I’m also using it for images, whether from files or in-memory streams (such as PDF previews from MuPDF). It works well over SSH (provided there is enough network bandwidth—`ssh -C` helps) and does not require synchronization of terminal output (since its writes are atomic).

**Comment by N-R-K** [comment]
As far as I see, [preview-tui](https://github.com/jarun/nnn/blob/master/plugins/preview-tui#L10) already supports kitty (but I don't see mpv mentioned anywhere). So my understanding is that you're asking to embed an mpv instance inside kitty to do the previews, is that correct?

In any case, this is going to be @luukvbaal's call.

**Comment by mia-0** [comment]
Yeah, somewhat analogous to the XEmbed approach in preview-tabbed. So mpv does the rendering and you just tell it where, relative to the terminal window. It could replace image viewers and e.g. calls to ffmpegthumbnailer.

**Comment by luukvbaal** [comment]
I won't be looking into this as I'm not a kitty user but a PR is welcome AFAIC. I guess https://github.com/mpv-player/mpv/commit/874e28f4a41a916bb567a882063dd2589e9234e1 can be used for reference.

**Comment by mia-0** [comment]
It also supports sixels and there’s almost no difference between the two as far as usage goes (see e.g. [here](https://git.0x0.st/mia/0x0/src/branch/master/modui/mpvwidget.py)).

**Comment by kuntau** [comment]
Ah... this requires `mpv v0.36`, no wonder I got error no kitty vo. Latest release still v0.35

**Comment by mia-0** [comment]
Right, I forgot that wasn’t actually in any release yet. I’m on a distro that packages git snapshot (as per upstream recommendation)…

**Comment by jarun** [comment]
I have added this to the tracker as no one is free to pick this up at the moment.
Closing accordingly.
