### ISSUE TITLE
Mishandling of entries that start with `~`

### ISSUE THREAD

**Issue by KlzXS** [jarun/nnn#1596]
#### Environment details (Put `x` in the checkbox along with the information)

- [ ] Operating System:
- [ ] Desktop Environment:
- [ ] Terminal Emulator:
- [ ] Shell:
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. Create a file/directory that starts with `~` outside `nnn` since it can't create such a file.
2. `nnn` is not able to interact with it. You can't open, copy, move, rename or remove it.

Files that simply contain, but don't start with `~` are handled as expected.

First noticed on WSL, confirmed on an actual Linux system by @N-R-K.

**Comment by jarun** [comment]
I think it's just dangerous to attempt to create it. Tried the following in bash, and those are not created:

```
vaio@vaio:~/github/nnn/src$ mkdir ~
mkdir: cannot create directory ‘/home/vaio’: File exists
vaio@vaio:~/github/nnn/src$ touch ~
vaio@vaio:~/github/nnn/src$ ls -a
.   .clang-tidy  icons-generated-emoji.h  icons-hash.c    icons-in-terminal.h  nnn.h
..  dbg.h        icons.h                  icons-hash-gen  nnn.c                qsort.h
```

**Comment by jarun** [comment]
IMO we should just document and move on.

**Comment by KlzXS** [comment]
Because that's not how you create such a directory. Try `mkdir "~"`, `mkdir ~dir` should work fine.

But that's not the real issue here. I accidentally created such a directory through incorrect usage of some command, but how it came to be is not important either. And I'm pretty sure there are programs which intentionally create such files.

We should support dealing with this, not necessarily creating them, I don't really care about that, but handling existing ones. This is obviously a bug with `nnn`. 

I remember you once told me to correct some `sed` script to "support" filenames with `\n`. If we are gonna do that we should actually support `~`, a much saner character for filenames IMO.

Obviously this is not a priority. We can leave it for a while.

**Comment by jarun** [comment]
OK. Maybe `abspath()` needs to handle this correctly.

**Comment by jarun** [comment]
OK. There may be more places to change.

**Comment by KlzXS** [comment]
If no one is interested in this I'll take a look at it, just not this weekend. It should be a relatively simple fix.

**Comment by N-R-K** [comment]
> OK. There may be more places to change.

I think there's about 3~5 places that needs correction. I can probably take a look at it tomorrow.

**Comment by N-R-K** [comment]
OK, I think the following patch should do the job. However, I didn't test it extensively. And since it messes with finicky path related code:

## :warning: USE WITH CAUTION :warning: 

```diff
diff --git a/src/nnn.c b/src/nnn.c
index 5944e65a..78fb223f 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -1125,6 +1125,11 @@ static inline bool getutil(char *util)
 	return spawn("which", util, NULL, NULL, F_NORMAL | F_NOTRACE) == 0;
 }
 
+static inline bool tilde_is_home(const char *s)
+{
+	return s[0] == '~' && (s[1] == '\0' || s[1] == '/');
+}
+
 /*
  * Updates out with "dir/name or "/name"
  * Returns the number of bytes copied including the terminating NULL byte
@@ -1135,16 +1140,10 @@ static size_t mkpath(const char *dir, const char *name, char *out)
 {
 	size_t len = 0;
 
-	if (name[0] == '~') { //NOLINT
+	if (tilde_is_home(name)) { //NOLINT
 		len = xstrsncpy(out, home, PATH_MAX);
 		if (!name[1])
 			return len;
-
-		if (name[1] != '/') {
-			out[0] = '\0';
-			return 0;
-		}
-
 		--len;
 		++name;
 	} else if (name[0] != '/') { // NOLINT
@@ -1211,7 +1210,7 @@ static char *abspath(const char *filepath, char *cwd, char *buf)
 	if (!path)
 		return NULL;
 
-	if (path[0] == '~') {
+	if (tilde_is_home(path)) {
 		cwd = home;
 		++path;
 		if (*path == '/')
@@ -1331,7 +1330,7 @@ static void xterm_cfg(char *path)
 
 static void convert_tilde(const char *path, char *buf)
 {
-	if (path[0] == '~') {
+	if (tilde_is_home(path)) {
 		ssize_t len = xstrlen(home);
 		ssize_t loclen = xstrlen(path);
 
@@ -2763,7 +2762,7 @@ static void write_lastdir(const char *curpath, const char *outfile)
 		convert_tilde(outfile, g_buf);
 
 	int fd = open(outfile
-			? (outfile[0] == '~' ? g_buf : outfile)
+			? (tilde_is_home(outfile) ? g_buf : outfile)
 			: cfgpath, O_CREAT | O_WRONLY | O_TRUNC, S_IWUSR | S_IRUSR);
 
 	if (fd != -1) {
@@ -3833,7 +3832,7 @@ static char *get_kv_val(kv *kvarr, char *buf, int key, uchar_t max, uchar_t id)
 
 			val = bmstr + kvarr[r].off;
 			convert_tilde(val, g_buf);
-			return abspath(((val[0] == '~') ? g_buf : val), NULL, buf);
+			return abspath((tilde_is_home(val) ? g_buf : val), NULL, buf);
 		}
 	}
 
@@ -8288,7 +8287,7 @@ static bool setup_config(void)
 	/* Set up configuration file paths */
 	if (xdgcfg && xdgcfg[0]) {
 		DPRINTF_S(xdgcfg);
-		if (xdgcfg[0] == '~') {
+		if (tilde_is_home(xdgcfg)) {
 			r = xstrsncpy(g_buf, home, PATH_MAX);
 			xstrsncpy(g_buf + r - 1, xdgcfg + 1, PATH_MAX);
 			xdgcfg = g_buf;
```

@KlzXS Does it look OK? Anything I might have missed?

**Comment by KlzXS** [comment]
This so far looks OK. I'll take a closer look at these changes and any potential missed spots when I get a chance. Though if you searched for `~` through the file you should have caught everything.

Is everything you ever pass to `tilde_is_home()` guaranteed not `NULL`? I guess since they were previously index into.
