### ISSUE TITLE
Auto close Tmux preview-tui after opening highlighted file for editing.

### ISSUE THREAD

**Issue by GNOMES** [jarun/nnn#1599]
I have noticed that preview-tui tmux splits do not auto close after opening file for editing. This leaves me with a split editing the file in my editor, and another that is still showing the nnn preview. 

**Describe the solution you'd like**

Would be nice to not have to manually close the preview split.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by luukvbaal** [comment]
The [restorepreview](https://github.com/jarun/nnn/blob/master/patches/restorepreview/mainline.diff) patch does this.
