### ISSUE TITLE
Vim not used for preview

### ISSUE THREAD

**Issue by mcp292** [jarun/nnn#1601]
[preview-tabbed](https://github.com/jarun/nnn/blob/master/plugins/preview-tabbed) lists Vim as a dependency but opens `nuke` with embedded `vi` for `.txt` files. Is there a way to have it use Vim as I have configured it and as I see it when issuing `vim` from the commandline normally?

#### Environment details (Put `x` in the checkbox along with the information)

- [ x ] Operating System: Arch Linux
- [ x ] Desktop Environment: dwm
- [ x ] Terminal Emulator: st
- [ x ] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ x ] Program options used: None (`nnn`).
- [ x ] Configuration options set:
    ```sh
    export NNN_FIFO=/tmp/nnn.fifo
    export NNN_PLUG='f:finder;o:fzopen;p:mocq;d:diffs;t:nmount;v:preview-tabbed'
    ```
- [ x ] Plugins are installed
- [ x ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. `nnn dir`.
2.  `;v`.
3. Hover over any `.txt`.

**Comment by jarun** [comment]
See the below line:

    PAGER=${PAGER:-"vim -R"}

Set your PAGER to vim.

**Comment by jarun** [comment]
Please ask questions under Discussions.

**Comment by mcp292** [comment]
> Please ask questions under Discussions.

Will do! Thanks for the response.
