### ISSUE TITLE
Add Clipboard support to cbcp plugin

### ISSUE THREAD

**Issue by Slackadays** [jarun/nnn#1609]
**Is your feature request related to a problem? Please describe.**

In the [cbcp plugin](https://github.com/jarun/nnn/blob/master/plugins/.cbcp), support for various systems is provided depending on what's available. However, my cross-platform project [Clipboard](https://github.com/Slackadays/Clipboard) would also work great in that plugin and would help make nnn even more cross-platform.

**Describe the solution you'd like**

Add a case for Clipboard detection and utilization along with the other choices in cbcp.

**Describe alternatives you've considered**

Have users use Clipboard manually by invoking it by itself from the command line.

**Additional context**

Other terminal file managers like clifm have already added Clipboard support in their copy/paste plugins along with all the other platform-specific options out there.

**Consider contributing**

If nobody else is interested, I could add this plugin addition myself.

**Comment by jarun** [comment]
Please raise a PR. And why is this an issue and not a discussion?

**Comment by Slackadays** [comment]
The issue template never claimed I should make a discussion post instead, so I thought an issue would be most appropriate.

**Comment by jarun** [comment]
OK. Fixed that now. :)

**Comment by jarun** [comment]
The readme has it though: https://github.com/jarun/nnn#developers
