### ISSUE TITLE
Split Window

### ISSUE THREAD

**Issue by kazoompa** [jarun/nnn#161]
Hi,

Can you split the window into independent sub-windows similar to [Terminator](https://gnometerminator.blogspot.com/p/introduction.html)? If not, are you planning to support it?

As someone who works on Linux and develops servers and needs to run and survey several at the same time, multiple windows into one terminal is very useful.

Best,

**Comment by jarun** [comment]
Hi @kazoompa, no plans to support split windows unless someone is willing to raise a PR. Also note that there are several solutions which do this already e.g. tmux/GNU screen/terminator/tilix/byobu etc.
