### ISSUE TITLE
preview-tui uses xterm to preview files in wezterm

### ISSUE THREAD

**Issue by sbstratos79** [jarun/nnn#1611]
- [x] Operating System: EndeavourOS
- [x] Desktop Environment: KDE
- [x] Terminal Emulator: wezterm
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: None
- [x] Configuration options set: `NNN_PLUG_DEFAULT='f:finder;c:fzcd;1:ipinfo;p:preview-tui;o:fzz;b:nbak;n:fixname;d:dragdrop;k:kdeconnect;i:imgview;x:xdgdefault'
NNN_PLUG="$NNN_PLUG_DEFAULT"
export NNN_SPLIT='v'
export NNN_PLUG
export NNN_TERMINAL='wezterm'
export NNN_ICONLOOKUP=1
export NNN_PISTOL=1
export NNN_FIFO=/tmp/nnn.fifo nnn
export PAGER='less -P?n -R'
export VISUAL='nvim'
export NNN_PREVIEWIMGPROG='ueberzug'
BLK="0B" CHR="0B" DIR="04" EXE="06" REG="00" HARDLINK="06" SYMLINK="06" MISSING="00" ORPHAN="09" FIFO="06" SOCK="0B" OTHER="06"
export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
`
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
- Run nnn in wezterm.
- Open preview-tui with `;p`. 
- The preview is opened in an xterm window instead of a native split pane.
- The issue exists in master and here's the [nnndbg](https://github.com/jarun/nnn/files/10979857/nnndbg.txt) file from the debug version. 
- EDIT: Forgot to mention that preview-tui works properly in kitty and tmux. (although, I couldn't get image preview to work with tmux.)

**Comment by luukvbaal** [comment]
I don't think the wezterm changes are part of the latest release.
Make sure you get the latest `preview-tui` by running `getplugs master` or downloading it directly from github.

**Comment by sbstratos79** [comment]
Thanks! This fixed the issue.
