### ISSUE TITLE
cd on quit not working

### ISSUE THREAD

**Issue by wybert** [jarun/nnn#1612]
ctrl + g doesn't return the shell with the current director of nnn enter in my mac m1.
I tested on bash and fish shell. Do I need configure something to make it work?

**Comment by 0xACE** [comment]
this is documented somewhere in a readme or the wiki... did you ask a question without searching first?

**Comment by N-R-K** [comment]
Ensure you have your shellrc set up properly: https://github.com/jarun/nnn/wiki/Basic-use-cases#configure-cd-on-quit and make sure to launch `nnn` via the proper wrapper function for cd on quit to work.

**Comment by wybert** [comment]
Hi, I have read the link you provided, I am asking because it should work as the default setting and I think it means to do so but not in my case. Once I install the nnn, it should have this behavior.  cd on quit is of the most common use case when I use the TUI file manager.

**Comment by N-R-K** [comment]
> I am asking because it should work as the default setting

A child process cannot change the working directory of a parent process. So this is not something that can *ever* work "by default" out of box.

> and I think it means to do so but not in my case

Nope, it requires set up as described in the wiki, for reasons explained above.

**Comment by wybert** [comment]
I switch from ranger, in ranger you could use shift + s to quick cd to the current directory, but it seems ranger doesn't quit at the same time and you could return back using ctrl + d.

**Comment by jarun** [comment]
nnn is not ranger (which is also a very good FM).

**Comment by luukvbaal** [comment]
For what it's worth, sounds like the ranger feature @wybert is describing
is dropping to a shell rather than cd on quit. Nnn also supports this with <kbd>!</kbd> or <kbd>Ctrl-]</kbd>...
