### ISSUE TITLE
Plugin `preview-tui` failed to launch in `tmux` while hovering on files with special characters in the filename.

### ISSUE THREAD

**Issue by amalgame21** [jarun/nnn#1614]
Since commit 80c0774, then preview cannot be launched while hovering on files with `space` , open or close bracket `(` `)` in the filename.

**Comment by amanjitsk** [comment]
Just wanted to add that this only happens when starting `preview-tui` when hovered on such a file. If it starts as normal, then hovering over such a file still works as expected. With `kitty`, it does not even work if the hovered file is in a directory with spaces in its name (even if the hovered file does not) - this second variant of this bug does not happen in `tmux` for example. The first variant can be fixed on line 532 by
```
toggle_preview "'$1'" &
```
but this doesn't explain why the bug exists in the first place, and seems like it should be unnecessary because everything is double quoted anyway. Similarly, for the kitty bug, on line 173
```
--cwd "'$PWD'" ...
```
but once again, this shouldn't be needed with the double quotes.

**Comment by jarun** [comment]
@luukvbaal can you please have a look?

**Comment by amalgame21** [comment]
Sorry I did not mentioned that I was using `nnn` inside `tmux`, since I alias it long time ago and treat it as standard ,I just forgot I was using `tmux`.
What I described above only for `tmux` case. Outside `tmux`, the `preview-tui` works perfectly.

Now also tested with no other NNN env (only `NNN_PLUG='p:preview-tui'` and `export NNN_PLUG`) and launching `nnn` with `-a`, also not work inside `tmux`. 

I will also look into it later.

**Comment by amalgame21** [comment]
This is the output when I launch the `preview-tui` plugin for file `~/test/a b c (.mp4`

```bash
/home/amalgame/.config/nnn/plugins/preview-tui: eval: line 170: syntax error near unexpected token `('
/home/amalgame/.config/nnn/plugins/preview-tui: eval: line 170: `tmux split-window -e 'PWD=/home/amalgame/test' -e 'PATH=/home/amalgame/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/home/amalgame/.antigen/bundles/romkatv/powerlevel10k:/home/amalgame/.antigen/bundles/zsh-users/zsh-syntax-highlighting:/home/amalgame/.antigen/bundles/zsh-users/zsh-autosuggestions' -e 'PREVIEW_MODE=/home/amalgame/test' -e 'NNN_FIFO=/tmp/nnn-fifo.40156' -e 'NNN_SCOPE=0' -e 'NNN_PISTOL=0' -e 'NNN_ICONLOOKUP=0' -e 'NNN_PAGER=less -P?n -R' -e 'NNN_BATTHEME=ansi' -e 'NNN_BATSTYLE=numbers,header-filesize,grid' -e 'NNN_PREVIEWWIDTH=1920' -e 'NNN_PREVIEWHEIGHT=1080' -e 'NNN_PREVIEWDIR=/tmp/nnn/previews' -e 'NNN_PREVIEWIMGPROG=' -e 'FIFOPID=/tmp/nnn-preview-tui-fifopid.40156' -e 'FIFOPATH=/tmp/nnn-preview-tui-fifo.40156' -e 'PREVIEWPID=/tmp/nnn-preview-tui-previewpid.40156' -e 'CURSEL=/tmp/nnn-preview-tui-selection.40156' -e 'FIFO_UEBERZUG=/tmp/nnn-preview-tui-ueberzug-fifo.40156' -e 'POSOFFSET=/tmp/nnn-preview-tui-posoffset' -e 'NNN_SPLIT=v' -e 'NNN_TERMINAL=tmux' -dh -p50 /home/amalgame/.config/nnn/plugins/preview-tui a b c (.mp4 1'
```

This output seems came from this line:
https://github.com/jarun/nnn/blob/c4678e311641d328cd127a5f83f7f566aeda09d2/plugins/preview-tui#L168

Seems the "$1" part in this line is not properly quoted somehow? (maybe because of `eval` ? I don't know)

Changing this line `"$1"` into `"'$1'"` is working for me:
https://github.com/jarun/nnn/blob/c4678e311641d328cd127a5f83f7f566aeda09d2/plugins/preview-tui#L216

But I do not know if this is a proper fix even for other terminal like kitty.

**Comment by N-R-K** [comment]
> Changing this line `"$1"` into `"'$1'"` is working for me:

Now try with a file with `'` in the name :)

**Comment by amalgame21** [comment]
> Now try with a file with `'` in the name :)

Sad....
Now I am using `/home/amalgame/test/testfile-';&\"(\)(\'\\&\;t.txt`  (only filename have special characters) and `/home/amalgame/test/testfolder-';&\"(\)(\'\\&\;t/testfile-';&\"(\)(\'\\&\;t.txt` (folder name and filename also contain special characters) for testing.

For the first one (only filename have special characters), in the `eval tmux window-split` line, replace `"$1"` with `$(printf '%q' "$1")` seems working, but still did not know if it is proper way to do it.

For the second one (folder name also containing special characters), in `ENVVARS` variable, I deleted 1 lines [`PWD=$PWD`] and then move the `PREVIEW_MODE=$2` line outside the `ENVVAR`. Add two lines  near `ENVVAR` [`ENVPWD=$(printf '%q' "PWD=$PWD")` and `ENVPREVIEW_MODE=$(printf '%q' "PREVIEW_MODE=$2")`], and then replace the `eval tmux window-split` line with:

```bash
eval tmux split-window -e $ENVPWD -e $ENVPREVIEW_MODE "$ENVSTRING" -d"$split" -p"$NNN_SPLITSIZE" "$0" "$(printf '%q' "$1")" 1 ;;
```

Now everything seems working (on my system).

For kitty I think it can be modified in similar way to do it (if the `printf '%q'` thing work for those system).

But I am not sure if the `printf "%q"` thing is good for this since I just found it by google somewhere. I don't know whether it is GNU extension and portable or not. If that is OK I can make a PR.

**Comment by N-R-K** [comment]
`%q` isn't POSIX, and it doesn't seem like [openbsd printf(1)](https://man.openbsd.org/man1/printf.1) provides `%q` either.

But I'm not aware of any posix compliant way to shell escape a string. So I'd say `printf %q` should be fine - it's certainly better than executing random commands (eg. guess what happens if someone names a file `file$(rm -fr $HOME/*)` :grimacing:)
