### ISSUE TITLE
`quitcd` not running properly in folders with name containing `\\` or ending with `\`

### ISSUE THREAD

**Issue by amalgame21** [jarun/nnn#1615]
To reproduce:
1. Use this script https://github.com/jarun/nnn/blob/master/misc/quitcd/quitcd.bash_zsh 
2. Create folder `tes\\t` and `test\`
3. Running `n` in terminal, in folder `tes\\t`, press `^G` with output `/home/amalgame/.config/nnn/.lastd:cd:1: no such file or directory: /home/amalgame/tes\t`
4. Running `n` in terminal, in folder `test\`, press `^G` with output `/home/amalgame/.config/nnn/.lastd:1: unmatched "`

**Comment by N-R-K** [comment]
It's due to this:

https://github.com/jarun/nnn/blob/c4678e311641d328cd127a5f83f7f566aeda09d2/src/nnn.c#L2783

Just wrapping something in quotes isn't enough, we'll have to either:

1. Do proper shell escaping
2. Change it to `dprintf(fd, "%s", curpath);` and then adjust the shell quit-cd functions to do the `cd` manually.

2 seems like a better idea.

**Comment by N-R-K** [comment]
Very lightly tested, but I think this should probably work:

```diff
diff --git a/src/nnn.c b/src/nnn.c
index 0e41cd1f..a4caf91a 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -2761,6 +2761,39 @@ static void archive_selection(const char *cmd, const char *archive)
 	free(buf);
 }
 
+static char *shell_escape(const char *s)
+{
+	size_t n = strlen(s), w = 0;
+
+	if (s == g_buf) {
+		DPRINTF_S("s == g_buf");
+		return NULL;
+	}
+
+	g_buf[w++] = '\''; /* begin single quote */
+	for (size_t r = 0; r < n; ++r) {
+		/* potentially too big: 4 for the single quote case, 2 from
+		 * outside the loop */
+		if (w + 6 >= sizeof g_buf)
+			return NULL;
+
+		switch (s[r]) {
+		case '\'':
+			g_buf[w++] = '\''; /* end single quote */
+			g_buf[w++] = '\\'; /* put \' so it's treated as literal single quote */
+			g_buf[w++] = '\'';
+			g_buf[w++] = '\''; /* start single quoting again */
+			break;
+		default:
+			g_buf[w++] = s[r];
+			break;
+		}
+	}
+	g_buf[w++] = '\''; /* end single quote */
+	g_buf[w++] = '\0'; /* nul terminator */
+	return g_buf;
+}
+
 static void write_lastdir(const char *curpath, const char *outfile)
 {
 	if (!outfile)
@@ -2772,8 +2805,9 @@ static void write_lastdir(const char *curpath, const char *outfile)
 			? (outfile[0] == '~' ? g_buf : outfile)
 			: cfgpath, O_CREAT | O_WRONLY | O_TRUNC, S_IWUSR | S_IRUSR);
 
-	if (fd != -1) {
-		dprintf(fd, "cd \"%s\"", curpath);
+	char *escaped;
+	if (fd != -1 && (escaped = shell_escape(curpath)) != NULL) {
+		dprintf(fd, "cd %s", escaped);
 		close(fd);
 	}
 }
```

**Comment by N-R-K** [comment]
Also, please be very careful when testing these type of weird path bugs. Preferably test under a chroot.

**Comment by jarun** [comment]
Guys, we had to fix th `~` issue because it's a well-known shortcut. `$(rm -rf $HOME/*)` isn't.

If someone is having files with those names in their system, then it's already compromised.

@amalgame21 change the names of those reverse-engineered file names just to trick the code and things should be fine.

**Comment by N-R-K** [comment]
> If someone is having files with those names in their system, then it's already compromised.

That was just an example. Currently, if a file contains _any_ of these characters: `"`, `$`, `$(` `(` `\` then it would fail to work. Double quote `"` and parenthesis `(` for example are common enough filenames.

The `shell_escape()` function above should fix the issue and it's not too much hassle, so I think we should just fix it and be done with it.

**Comment by amalgame21** [comment]
> Guys, we had to fix the `~` issue because it's a well-known shortcut. `$(rm -rf $HOME/*)` isn't.
> 
> If someone is having files with those names in their system, then it's already compromised.
> 
> @amalgame21 change the names of those reverse-engineered file names just to trick the code and things should be fine.

lol I wish I had the skill to "reverse-engineer" your code. I am not a programmer neither.
I was just help debugging the `preview-tui` plugin in #1614 using  the filename and folder name with random keystroke, since wrapping in single quote is not enough to escape (not reverse-engineering `preview-tui` either), and accidentally found out `quitcd` also cannot work properly in the folder, that's it.

Normally I would not use those folder name, but I think this bug is worth reporting since this is a file manager: an application to manage files, although I think this is just a minor issue. If you think it is also just a minor thing you may ignore this thread.

But I wonder why there are no built-in tools or libraries etc. in the C language for programmer to particularly escape character in the filename, and you guys have to do it by yourself (which may not guarantee 100% work).

**Comment by jarun** [comment]
OK. Let's have it in. 👍

**Comment by amalgame21** [comment]
Thank you jarun!
