### ISSUE TITLE
`preview-tui` on Windows Terminal breaks after switching preview twice

### ISSUE THREAD

**Issue by KRACK-BIT** [jarun/nnn#1618]
I am currently trying to set up the `preview-tui` plugin for Windows Terminal (WSL2), as well as using QuickLook.

However, whilst I have gotten Windows terminal to split and render an initial preview, it freezes and will not work, even for basic previews like listing files.

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Windows with an Ubuntu WSL2 instance
- [ ] Desktop Environment: N/A
- [x] Terminal Emulator: `Windows Terminal`
- [x] Shell: `zsh`
- [ ] Custom desktop opener (if applicable): 
- [ ] Program options used:
- [x] Configuration options set:
  - ```sh
    export NNN_COLORS='4321'
    export NNN_FCOLORS="0B0B04060006060009060B06"
    export NNN_OPTS="Hc"
    export NNN_PLUG='p:preview-tui;d:diffs;f:fzcd;r:fixname;w:wallpaper;n:nuke;u:getplugs' # ;i:imgview;j:jump ;l:!ls
    export NNN_FIFO=/tmp/nnn.fifo
    export NNN_ICONLOOKUP=1
    export NNN_OPENER=$XDG_CONFIG_HOME/nnn/plugins/nuke
    ```
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Mock file system setup
```
nnn_test
├── A
│   ├── a1
│   ├── a2
│   └── a3
├── B
│   ├── b1
│   ├── b2
│   └── b3
└── C
    ├── c1
    └── c2
```
- Works for first preview: ![image](https://user-images.githubusercontent.com/46194176/227791445-cacbb17d-a9a8-4ea9-b5bf-d2035dd9aff6.png)
- Works for second preview: ![image](https://user-images.githubusercontent.com/46194176/227791475-abf5d9e5-46af-4dfa-830f-354ed292845c.png)
- Fails for third preview - other screen has frozen, and will now no longer work: ![image](https://user-images.githubusercontent.com/46194176/227791500-986c85d4-4962-481b-aedf-656e14df3482.png)
- Moreover, exiting `nnn` now does not terminate the preview window; it is frozen, and needs to be manually killed ![image](https://user-images.githubusercontent.com/46194176/227791573-42803ae8-13e0-48c9-99c6-545e5588b70a.png)

**Comment by luukvbaal** [comment]
Can't reproduce on master. It's hard to debug these kind of environment issues remotely. Please try to figure it out yourself and feel free to report back if you have more information.
