### ISSUE TITLE
preview-tui + iconlookup don't work on macOS

### ISSUE THREAD

**Issue by acidghost** [jarun/nnn#1620]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: macOS 13.3 (Apple Silicon)
- [ ] Desktop Environment:
- [x] Terminal Emulator: Alacritty 0.12.0
- [x] Shell: login shell zsh 5.9 (x86_64-apple-darwin22.0), sh is GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: acdxQ
- [x] Configuration options set:
```
export NNN_OPTS="acdxQ"
export NNN_OPENER="$NNN_PLUGINS_PATH/nuke"
export NNN_PLUG="p:preview-tui"
export NNN_COLORS="#b1b1b1b1;5555"
export ICONLOOKUP=1
```
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Just open the preview and get:
```
ls: unrecognized option `--group-directories-first'
usage: ls [-@ABCFGHILOPRSTUWabcdefghiklmnopqrstuvwxy1%,] [--color=when] [-D format] [file ...]


awk: syntax error at source line 28
 context is
            >>>  icons["directory"][ <<< 1] = ""; icons["directory"][2] = color_default
awk: illegal statement at source line 28
awk: illegal statement at source line 28
        missing ]
```

The problem is that the default shell for macOS is an ancient bash version and `ls` does not support `--group-directories-first`. I don't think that this flag is POSIX-compliant (see https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ls.html).

I cannot replace bash with a newer version as it would probably break something.

**Comment by luukvbaal** [comment]
Please install GNU coreutils (`brew install coreutils` I think).

**Comment by acidghost** [comment]
Then you should not claim that the script is POSIX...

**Comment by acidghost** [comment]
Also, the flag does not seem to be required for functionality and it just re-orders the output. This could be implemented as optional (default to use the flag).

Can you please re-open and (maybe) change the label to "enhancement"?

**Comment by luukvbaal** [comment]
The whole point of iconlookup is to make the preview look the same as nnn, which groups directories first by default, I guess GNU ls should be a dependency then. It is optional, you are free to remove the flag yourself.

**Comment by jarun** [comment]
All plugins are indicative and users are supposed to modify them to adapt to their setup.
We don't claim they would work everywhere.

**Comment by acidghost** [comment]
I'm not complaining :) I'm new to nnn and I understand maintaining my fork of the default plugins. I was just pointing out that the script claims to be POSIX but it's not.

**Comment by jarun** [comment]
The comment:

    Shell: POSIX compliant
is about the script syntax and the shell, not necessarily the utilities it invokes.
