### ISSUE TITLE
preview-tui blink on Void+sway

### ISSUE THREAD

**Issue by NathNLM** [jarun/nnn#1622]
Good morning, sorry to ask this even though there are plenty solved issues around this plugin and plenty documentation aswell, but I've been trying for days to set preview-tui on my system with 0 success so far, getting only a blink of the second terminal window when I launch preview-tui from shortcut or a terminal with a no-FIFO error if I launch it as "nnn -P p" (with p being my NNN_PLUG assigned key for preview-tui). I have all the obrigatory dependencies both for nnn and preview-tui installed and already made all the plugins executable, also I've alread tried:

1 - Eiher setting NNN_FIFO manually or automatically with -a (and even both at the same time);

2 - Running nnn inside Tmux (which I don't even plan using in the end, I want it to open on a separate footclient window);

3 - Removing all the 2>/dev/null flags (I get

"/home/nlm/.config/nnn/plugins/preview-tui: 97: [: Illegal number: fifo" if NNN_FIFO is set to /tmp/nnn.fifo which disappears if i unset NNN_FIFO and run nnn with the -a flag, 

"No FIFO available! ($NNN_FIFO=' ')" if I launch nnn with the -a flag, 

and "QuickLook.exe: not found
Bridge.exe: not found" as expected because I'm on Linux);

4 - Running nnn in foot instead of footclient (with the appropriate $TERMINAL and $NNN_TERMINAL variables, $TERM is the same for both)

I've also tried a lot of random changes on preview-tui (that I now reverted re-downloading the plugin) with no luck aswell, I believe this may be a sway/Wayland or a Void/SystemD-less problem but looking at the code it seems like it should run normally, so having exhausted my Linux/coding knowledge I'm here asking for help if possible. 

#### Environment details (Put `x` in the checkbox along with the information)

- [X] Operating System: Void Linux x86_64 6.1.21_1
- [X] Desktop Environment: sway (with XDG_CURRENT_DESKTOP=Unity on .bashrc)
- [X] Terminal Emulator: footclient
- [X] Shell: bash
- [x] Custom desktop opener (if applicable): none
- [x] Program options used: -aP p
- [x] Configuration options set: NNN_TERMINAL=footclient  NNN_PLUG='p:preview-tui;v:imgview'
both with and without NNN_FIFO='/tmp/nnn.fifo'
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

- Install plugins from getplugs (or from the curl command on nnn/plugins/README.md) and chmod them to executable
- Assign preview-tui a key with NNN_PLUG and a FIFO path with either NNN_FIFO or -a argument (tried both)
- Launch nnn
- Press ;corresponding key or alt+corresponding key, or launch nnn with a -P corresponding key flag
- Get flashed

**Comment by NathNLM** [comment]
UPDATE: I manage to figure out that the nnn-fifo.# preview-tui searches doesn't match the nnn-fifo.# file nnn -a creates (by 1), so thats probably why it can't pick up auto FIFO. still, even with a static FIFO it just blinks with the "Illegal number: fifo" error, so still no luck.

I've also tried manually setting the NNN_FIFO variable on the preview-tui script with NNN_FIFO=/tmp/nnn-fifo.(('expr $PPID - 1')) to see if they match but it just blinks too.

**Comment by jarun** [comment]
Remove `-a` if you are using a static FIFO.
The configuration is here: https://github.com/jarun/nnn/wiki/Live-previews#set-up-nnn_fifo

Ensure you install the latest plugins manually with master.

There are issues earlier logged earlier about preview-tui blinking.
Check those out - https://github.com/jarun/nnn/issues?q=is%3Aissue+is%3Aclosed+blink

On top of that, we can't help much with local issues.
