### ISSUE TITLE
One problem...

### ISSUE THREAD

**Issue by EddieHozan** [jarun/nnn#163]
I'm pretty sure that the terminal itself is the fastest file manager for the terminal. Can you explain what you mean? Say: "the fastest file manager with an easy-to-use UI" or something along those lines.

**Comment by jarun** [comment]
> I'm pretty sure that the terminal itself is the fastest file manager for the terminal.

So you think typing `rm Downloads1` -> `Enter` is faster than `^X`-`y`. Who am I to contradict that?

**Comment by EddieHozan** [comment]
think so.
