### ISSUE TITLE
Iconlookup plugin does not support Nerd Fonts v3.0.0

### ISSUE THREAD

**Issue by acidghost** [jarun/nnn#1634]
Some icons do not display properly with Nerd Fonts v3.0.0 (https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0).

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: macOS
- [ ] Desktop Environment:
- [x] Terminal Emulator: Alacritty
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: acdQ
- [ ] Configuration options set:
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
E.g. `tree | .iconlookup`

**Comment by jarun** [comment]
If they were working before and failing now, please inform the maintainers of the font.

**Comment by luukvbaal** [comment]
Problem is not exclusive to `.iconlookup`. `icons.h` will need to be updated as well...

**Comment by luukvbaal** [comment]
They made a breaking change in the codepoints for a lot of icons we used...

**Comment by acidghost** [comment]
Yes, @luukvbaal is right. Please don't rush to close issues w/o asking for feedback by the author...

**Comment by jarun** [comment]
@acidghost there's something called backward compatibility. If older things are broken with a new release, what does that tell about reliability of the package?

Probably you should not rush to raise issues on the wrong packages on finding things broken while trying a brand new package?

**Comment by acidghost** [comment]
It's such a pain to report issues to this repository.

I appreciate the quickness but this is way too quick to be reasonable. I wonder how many people stopped reporting legitimate issues here just because the owner has an attitude...

**Comment by jarun** [comment]
No, you raised a defect on the wrong package. That's exactly the problem.

**Comment by luukvbaal** [comment]
It's @jarun's prerogative to close issues (the ToDo list is used for discussion).
However judging by nerd-font's release notes it seems a deliberate break of backwards compatibility that I doubt they will revert.
We would need a new set of glyphs in `icon.h` accompanied with a new `make` flag to support nerd-font v3, or drop support for v2...

**Comment by jarun** [comment]
@luukvbaal how about dropping support for Nerd Fonts? I find Emoji support stabler and consistent across distros.

**Comment by jarun** [comment]
Let's move over to discussions, now we have a topic.
