### ISSUE TITLE
Regular files creation not honoring umask

### ISSUE THREAD

**Issue by leo-arch** [jarun/nnn#1654]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Archlinux
- [x] Desktop Environment: None
- [x] Terminal Emulator: xterm
- [x] Shell: bash
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: vanilla
- [ ] Configuration options set:
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1.
```sh
umask 0027
nnn
```
2. Now just create a regular file. The file is created with permissions `0600` instead of `0640` (as implied by the umask value set above).

#### Some context

The problematic line is `nnn.c:4684`, which reads:

```c
int fd = open(path, O_CREAT | O_TRUNC, S_IWUSR | S_IRUSR); /* Forced create mode for files */
```
If changed to this:

```c
mode_t mode = S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH; /* 0666 */
int fd = open(path, O_CREAT | O_TRUNC, mode);
```

the issue is gone and the umask value is respected.

I know, the comment says to _force_ the file mode to `S_IWUSR | S_IRUSR`. However, _directories_ creation does respect umask (besides the fact that respecting umask is a quite standard practice). So, I'm not sure the current behavior is actually intended (haven't found anything regarding this issue in the docs either).

Two more things concerning this line:

1. **open**(2) specifies that:

> The argument _flags_ must include one of the following access modes: O_RDONLY, O_WRONLY, or O_RDWR.  These request  opening  the  file  read-only, write-only, or read/write, respectively.

But the current code does not specify any of them.

2. Since, as specified by **open**(2), O_TRUNC has meaning only provided either O_RDWR or O_WRONLY is set (which is not the case), is it really playing any role here? On the other side, if one of these access modes were actually set, would you really want to truncate the file to zero length in case it already exists?

If any of the above applies, I suggest this code:

```c
mode_t mode = S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH; /* 0666 */
int fd = open(path, O_WRONLY | O_CREAT | O_EXCL, mode);
```

**Comment by jarun** [comment]
As far as I remember, it was that way before, honoring umask. And then came the angle of secure programming.

https://github.com/eclipse-theia/theia/issues/9564

This is not going to change because umask settings vary from system to sytem.

**Comment by leo-arch** [comment]
Thanks for you reply @jarun! A totally valid viewpoint, no doubt. Just out of curiosity: should we apply the same principle to directories creation?

**Comment by N-R-K** [comment]
We should probably still add `O_WRONLY` to avoid undefined behaviour.

**Comment by jarun** [comment]
Yes, please ahead and add sensible masks. For directories (which are containers) the masks are linked to operations like opening, viewing the contents etc. too. As long any files created within are secure, that should suffice.
