### ISSUE TITLE
nnn needs an awesome video

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#167]
The current one is dated and doesn't demo the latest features of `nnn`.

It would be great if someone can make a video demonstrating the latest interesting features in action. Please take a look at the features section and ToDo list.

We would be glad to help with anything. Credits would be duly noted.

**Comment by Kallinteris-Andreas** [comment]
https://www.youtube.com/watch?v=U2n5aGqou9E

**Comment by jarun** [comment]
Thank you so much! I'ld set it at the project page.

**Comment by jarun** [comment]
Done! Let me know if you like any changes to the credits, or add any copyright notice etc.
