### ISSUE TITLE
Bad PGP signature on nnn v4.8

### ISSUE THREAD

**Issue by arafel** [jarun/nnn#1670]
Hi

The PGP signature on the latest tarball seems to be bad. :-( Did you generate it yourself, or does it come from a GitHub action or something?

$ gpg --verify nnn-4.8.tar.gz.sig nnn-v4.8.tar.gz
gpg: Signature made Thu 13 Apr 2023 14:18:11 BST
gpg:                using RSA key E0B84447CD884CBB13E3266E4A865183AF6C5631
gpg: BAD signature from "Arun Prakash Jana <[engineerarun@gmail.com](mailto:engineerarun@gmail.com)>" [unknown]
$ sha256sum nnn*
65ffcee8b627ef58d27f86b717902e1fe81c51a347e0044cf8897d3e745f0b58  nnn-4.8.tar.gz.sig
7027f830329ff3451b844d1f5fbeb1d866bed1af6f24a360d5c51888cb1ae8f0  nnn-v4.8.tar.gz

Thanks
Paul
[nnn-4.8.tar.gz.zip](https://github.com/jarun/nnn/files/11733771/nnn-4.8.tar.gz.zip)

**Comment by jarun** [comment]
I lost my earlier key as the system got wiped. So I generated a new one before releasing 4.8.

The only issue reported was: https://github.com/jarun/nnn/discussions/1629

I checked my system and the only key reported to be present is `E0B84447CD884CBB13E3266E4A865183AF6C5631`.

**Comment by jarun** [comment]
I can lookup the key correctly as well:

```
$ gpg -v --recv-keys E0B84447CD884CBB13E3266E4A865183AF6C5631
gpg: data source: https://keys.openpgp.org:443
gpg: armor header: Comment: E0B8 4447 CD88 4CBB 13E3  266E 4A86 5183 AF6C 5631
gpg: armor header: Comment: Arun Prakash Jana <engineerarun@gmail.com>
gpg: pub  rsa4096/4A865183AF6C5631 2023-04-13  Arun Prakash Jana <engineerarun@gmail.com>
gpg: key 4A865183AF6C5631: "Arun Prakash Jana <engineerarun@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```
