### ISSUE TITLE
Missing large file support for older toolchains

### ISSUE THREAD

**Issue by hgy59** [jarun/nnn#1678]
nnn requires the option `_FILE_OFFSET_BITS==64` on 32 bit archs to handle Large files (> 4GB).

This is forced for 32-bit arm and x86 archs in nnn.c by 
```
#if defined(__arm__) || defined(__i386__)
#define _FILE_OFFSET_BITS 64 /* Support large files on 32-bit */
#endif
```

This was introduced in #42 and fixed for 32-bit arm with #135

Since `nnn.c` depends on included `fts.h` I get a comiler error for the current version (4.8) with older toolchains:
```
<fts.h> cannot be used with -D_FILE_OFFSET_BITS==64
```

I can remove the the definition of `_FILE_OFFSET_BITS 64`  to build nnn successfully with these toolchains, but than it will lack to display large files correctly.

Is it possible to build nnn without the dependency of `fts.h` to fix this?
i.e. I am searching for a solution to build nnn without multithreading support that was introduced with nnn v4.1.

**Comment by N-R-K** [comment]
This is a bug in glibc, from `man 3 fts`:

```
BUGS
       Before  glibc  2.23,  all  of  the  APIs described in this man page are not safe when compiling a program using the LFS APIs
       (e.g., when compiling with -D_FILE_OFFSET_BITS=64).
```

I don't think we have any plans to workaround libc bugs which have long been fixed (glibc 2.23 was released in 2016). But if you really want to use such old toolchains, maybe projects like [fts-standalone](https://github.com/pullmoll/musl-fts) interests you.

- - -

Also, I think we should remove those ifdefs and define `_FILE_OFFSET_BITS 64` unconditionally.
