### ISSUE TITLE
Can you not check in a terminal if option is `-v`?

### ISSUE THREAD

**Issue by fcying** [jarun/nnn#168]
nnn is very easy to use. I want it to upgrade automatically.

I detect the version number and then automatically upgrade, but there have a problem

```
cur_ver=`/usr/bin/nnn -v`         # stdin or stdout is not a tty

new_ver=`curl -s "https://github.com/jarun/nnn/releases/latest" | grep -Eo "[0-9]+\.[0-9]+"`
```

**Comment by jarun** [comment]
Please test with master.

**Comment by fcying** [comment]
It can work now, tks

**Comment by jarun** [comment]
Added https://github.com/jarun/nnn/blob/master/scripts/user-scripts/upgrade.sh.
