### ISSUE TITLE
*-generated-* files do not exist (compile with NERD)

### ISSUE THREAD

**Issue by robrobbins** [jarun/nnn#1681]
#### Environment details (Put `x` in the checkbox along with the information)

- [x ] Operating System: Ubuntu Jammy
- [ ] Desktop Environment:
- [ x] Terminal Emulator: term, iterm, blink
- [ x] Shell: bash
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ x] Configuration options set: O_NERD=1
- [ ] Plugins are installed
- [ x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
sudo make install strip O_NERD=1

the makfile errors trying to include `icons-generated-nerd.h` — there is only `icons.h` in the src/ dir. will try changing the name in the makefile, or, is there an extra step to generate those files? I don’t see anything in the makefile to do it

**Comment by N-R-K** [comment]
It's working fine on my end on nnn's `master` branch.

Which version of nnn are you using? Also show the entire output of `make`.

P.S: that `strip` isn't doing anything useful for you. It will strip *after* the installation. You should use `make strip install` instead (notice strip is *before* install).

**Comment by robrobbins** [comment]
was a red herring. found a missing package.
