### ISSUE TITLE
`preview-tui` does not open in `wezterm` when using `wezterm start` with `--class` flag to launch `nnn`

### ISSUE THREAD

**Issue by Anomalocaridid** [jarun/nnn#1682]
When I launch a `wezterm` instance running `nnn` with `wezterm start --class=nnn -- nnn` and then try to launch the `preview-tui` plugin, it does not open a pane. If I run `nnn` directly or omit the `--class` flag, it works as expected. No other plugins appear to be affected.

This appears to still occur in the latest revision as of the time of my writing this.

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: NixOS unstable
- [x] Desktop Environment: Hyprland
- [x] Terminal Emulator: WezTerm
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable): nuke
- [x] Program options used: BcDEirx
- [x] Configuration options set
    - NNN_OPTS = `"BcDEirx"`
    - NNN_OPENER = `"$HOME/.config/nnn/plugins/nuke"`
    - GUI = `1`
    - NNN_FIFO = `"/tmp/nnn.fifo"`
    - NNN_COLORS = `"#1909c9d02e0d2cff"`
    - NNN_ARCHIVE = `"\\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$"`
    - NNN_ICONLOOKUP = `1`
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. Assign a key to `preview-tui`
2. Run `wezterm start --class=nnn -- nnn`
3. Try to activate `preview-tui` with the keybind.
4. Nothing should happen.
5. Close `nnn`
6. Run `wezterm start -- nnn`
7. Try to activate `preview-tui` again
8. It should open a pane and show a preview as expected.

**Comment by jarun** [comment]
@N-R-K @luukvbaal any ideas?

**Comment by N-R-K** [comment]
Sorry, I don't use wezterm.

@Anomalocaridid you'll need to either wait for Luuk to take a look or try to debug this yourself in the meantime.

**Comment by Anomalocaridid** [comment]
Understandable

**Comment by quantonganh** [comment]
I cannot reproduce:

<img width="1200" alt="Screen Shot 2023-08-05 at 22 09 17" src="https://github.com/jarun/nnn/assets/1568504/cdd4f10e-9dc2-403e-9da8-3768dbb81869">

**Comment by Anomalocaridid** [comment]
@quantonganh What OS and nnn settings are you using? If it's any different from my setup in my initial post, I'd like to know so I can try to further narrow down the cause of my problem.

**Comment by Anomalocaridid** [comment]
Actually, never mind. I just checked and I think a recent update fixed it. I suspect I was mistaken that this was a problem with `nnn` and was probably caused by `wezterm` as far as I understand. I sincerely apologize for this.

**Comment by quantonganh** [comment]
> @quantonganh What OS and nnn settings are you using?

I'm using macOS and pretty same configuration options as you:

```
export NNN_OPTS="BcDEirx"
export NNN_OPENER="$HOME/.config/nnn/plugins/nuke"
export NNN_FIFO="/tmp/nnn.fifo"
export NNN_FCOLORS="AAAAE631BBBBCCCCDDDD9999"
export NNN_PLUG='p:preview-tui'
```

> I just checked and I think a recent update fixed it. I suspect I was mistaken that this was a problem with nnn and was probably caused by wezterm as far as I understand.

May I know exactly what the problem was and which commit fixed it?

**Comment by Anomalocaridid** [comment]
> May I know exactly what the problem was and which commit fixed it?

@quantonganh I should have phrased that more precisely. I meant that running an update on my system recently fixed it.

Unfortunately, I am not sure what exactly caused the problem or what fixed it. All I know is that it most likely wasn't nnn because that hasn't had an update since I had this problem but wezterm has. So it seems like wezterm was the real culprit. And it's entirely my fault for not catching that before making an issue and wasting others' time.
