### ISSUE TITLE
Install error "curses.h: No such file or directory"

### ISSUE THREAD

**Issue by ccrptl** [jarun/nnn#17]
cc -O3 -march=native -Wall -Wextra -Wno-unused-parameter  -o nnn nnn.c  -lcurses
nnn.c:8:20: fatal error: curses.h: No such file or directory
compilation terminated.
Makefile:22: recipe for target 'nnn' failed
make: *** [nnn] Error 1

**Comment by jarun** [comment]
distro?

Do you have libncursesw dev package installed? On Ubuntu, run:

`sudo apt install libncursesw-dev`

**Comment by jarun** [comment]
I've updated the README with sample instructions for Ubuntu.
