### ISSUE TITLE
Bookmark key only lists `,` when using symlinked bookmarks and marked directories

### ISSUE THREAD

**Issue by screendriver** [jarun/nnn#1707]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: macOS Ventura
- [x] Desktop Environment: Aqua
- [x] Terminal Emulator: kitty
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: none
- [x] Configuration options set: none
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

- navigate to directory `A`
- press `B` to create a symlinked bookmark
- navigate to directory `B`
- press `B` to create a symlinked bookmark
- press `b` to see the list of symlinked bookmarks (`~/.config/nnn/bookmarks` is shown)
- exit the directory and navigate to directory `C`
- press `,` to mark a directory
- now press `b`. Instead of seeing the list of symlinked bookmarks **and** the marked directory I'm only able to see the `keys: ,`. So I'm not able to navigate to the symlinked bookmarks anymore.

**Comment by lawnowner** [comment]
[Press `Enter`](https://github.com/jarun/nnn/wiki/Basic-use-cases#:~:text=Enter).

**Comment by screendriver** [comment]
🤦 

**Thank you**! The prompt `keys: ,` was/is not really intuitive on the first sight.
