### ISSUE TITLE
Different color for video files (.mkv)

### ISSUE THREAD

**Issue by qazip** [jarun/nnn#171]
So, nnn has different colors for folders, but it would also be nice if it had different coloring for videos, namely, .mkv. I guess the same could be said for image files.

**Comment by jarun** [comment]
I am pretty sure you understand why folders were chosen to be in different color.

`nnn` is not for fancy stuff. There are tons of file managers where you can get colors for every different file type. Try those.

**Comment by jarun** [comment]
More details: https://github.com/jarun/nnn/wiki/nnn-design-considerations

**Comment by qazip** [comment]
I wouldn't call different coloring to be something "fancy", but alright, fair enough. Thank you.
