### ISSUE TITLE
Some Glyph icons not appearing in WSL windows terminal

### ISSUE THREAD

**Issue by jabarragann** [jarun/nnn#1715]
Hi there,

I recently migrated to use Windows Terminal as my day-to-day terminal emulator. I only run an instance of WSL2 with Ubuntu 20.04, where I have installed nnn version  4.8. I have compiled nnn with Icon support and added a Nerd font to my terminal.  I am using Hack Nerd Font.

When running nnn, I am missing a few icons, e.g., the download folder, Makefile, License, see image below.

In the image below, I am showing the same folder in my WSL Ubuntu instance viewed from Windows Terminal and Terminator.

![image](https://github.com/jarun/nnn/assets/22458204/59586316-9a48-4a00-84d4-f00c0f48e7dc)

Finally, I did test to see if Windows Terminal was able to display some of the missing icons.

![image](https://github.com/jarun/nnn/assets/22458204/5677ffce-55ed-440b-9afa-a2c778d3e58d)

Any solution on how to get the missing icons?

#### Environment details (Put `x` in the checkbox along with the information)

- [X] Operating System:
- [X] Desktop Environment:
- [X] Terminal Emulator:
- [X] Shell:
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master

**Comment by jabarragann** [comment]
I forgot to mention that I use Bash.

**Comment by N-R-K** [comment]
Maybe relevant https://github.com/jarun/nnn/wiki/Troubleshooting#misaligned-size-column

**Comment by jabarragann** [comment]
Thanks for the suggestion @N-R-K . Unfortunately, the proposed solution did not work. I went through the troubleshooting guide, and I think my problem is a little bit different from the things mentioned there.

**Comment by jabarragann** [comment]
Ohh, I just realized that upgrading to nnn v4.9 Elixir fixed the problem. Thanks @jarun 

I am closing the issue with this.
