### ISSUE TITLE
glitch when toggling full-screen in i3

### ISSUE THREAD

**Issue by SumOfAllN00bs** [jarun/nnn#173]
Came here from Luke Smith's video.
My setup:
distro/linux = 4.19.8-2-MANJARO x86_64
wm = i3wm
terminal = st
shell = zsh + oh-my-zsh

Description:
unusable glitch mess when going full-screen after opening help.

Steps:
Using Luke Smith's LARBS created key combination (with MOD in this context meaning capslock)
press MOD+r (opens nnn)
Before screenshot:
![2018-12-23-040752_1366x768_scrot](https://user-images.githubusercontent.com/10123239/50375850-327e9500-0669-11e9-926d-41781259c6e2.png)
press ? (opens nnn's help page)
press MOD+f (makes window fullscreen)
(view no longer shows help page but the directory shown in before screenshot *only full-screen now)
press j and k keys alternately (to navigate up and down)
After screenshot:
![2018-12-23-040840_1366x768_scrot](https://user-images.githubusercontent.com/10123239/50375886-b9337200-0669-11e9-882d-2f288c23050d.png)

Don't know if I'm in help or directory and after pushing various key combos to exit nnn I see no evidence of exiting but the behaviour changes from some kind of navigation to some kind of insert mode. So I'm left with just killing the window in order to not do the damage I assume I'm about to do.

**Comment by jarun** [comment]
I don't use i3wm so not sure what's going wrong. I'll see if I can replicate this on xfce4. On travel, so need 4 to 5 days to revert back. Thanks!

**Comment by jarun** [comment]
Please test the fix on master and confirm.

**Comment by jarun** [comment]
No problem!

Wish you a Merry Christmas and a Very Happy New Year!

**Comment by SumOfAllN00bs** [comment]
Merry Christmas and a Happy New Year to you too. :)
