### ISSUE TITLE
preview-tui plugin in kitty crashes after second window resize

### ISSUE THREAD

**Issue by azuline** [jarun/nnn#1731]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Linux
- [x] Desktop Environment: none+i3
- [x] Terminal Emulator: kitty
- [x] Shell: fish
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: adERx
- [x] Configuration options set: unsure which are relevant, my configuration is here https://github.com/azuline/nixos/blob/master/home/nnn/default.nix
- [x] Plugins are installed: preview-tui, fzopen, imgview, playdir (custom plugin)
- [ ] Issue exists on `nnn` master: Unsure, I'm on 4.8 but have the latest plugins

#### Exact steps to reproduce the issue

1. Execute preview-tui plugin in kitty.
2. Resize terminal once. Everything should be fine.
3. Resize terminal again. The preview window exits.

I've poked through the plugin code, but I'm not sure what's causing this issue. That this only happens on the second resize, and not on the first, breaking my intuition a little bit. I'm not familiar with the actions kitty takes when resizing the window (does it send signals to running processes?).

Recording:

https://github.com/jarun/nnn/assets/51880422/c574bdc6-6eda-48f8-a0bd-3480ed75d4e6

I'm happy to put up a pull request if I can understand what the cause is!

**Comment by luukvbaal** [comment]
Looks like this broke in https://github.com/jarun/nnn/pull/1630, it's not just kitty either.
I'll try to investigate.

**Comment by luukvbaal** [comment]
Not exactly sure what's going on. I suspect it's just the move from POSIX sh to bash that's causing this. Not anything to do with the different way we're handling environment variables since that PR.

Even with an empty WINCH handler, `preview-tui` closes after the second resize.
