### ISSUE TITLE
nnn hangs after opening a shell

### ISSUE THREAD

**Issue by peri4n** [jarun/nnn#174]
Hi folks,
I just need some clarification: 

When I exit the shell I opened using nnn (using `!`) the shell hangs and I can't do anything. Is this expexted behaviour? I just find it a little odd.

Best regards and a merry Christmas ;)

**Comment by jarun** [comment]
Shouldn't happen.
What's your $SHELL?

**Comment by jarun** [comment]
I can't reproduce this issue. We need more info to proceed. Please respond back if you have more info.

**Comment by peri4n** [comment]
I use `zsh` as a shell and `st` as a terminal. I the meanwhile, I managed to solve it by updating my terminfo. 

Now, nnn gets send to background when I open a shell and I can bring back `nnn` with `fg`. This looks much more like a behaviour one could expect.

**Comment by jarun** [comment]
The shell is spawned from `nnn`. If you quit the shell, `nnn` should come back to foreground.

**Comment by peri4n** [comment]
In my case it doesn't. nnn is suspended and I can't exit the shell becaush zsh warns me that I have suspended jobs. I'll see what I can do.

**Comment by jarun** [comment]
What's the output of `echo $SHELL`?

**Comment by peri4n** [comment]
`/bin/zsh`

**Comment by jarun** [comment]
OK, I don't see this with my rudimentary setup. Try the following:

1. Remove nnn related config from .zshrc and try

2. Use a rudimentary zsh config and see if it still hangs

**Comment by peri4n** [comment]
I don't have any NNN related configs in my zshrc but changing to a default zsh config helped. So I guess I have to go over my ZSH options to see what breaks it. I'll return as soon as I have more information.

Thanks btw for the great support.

**Comment by jarun** [comment]
No problem!
