### ISSUE TITLE
Opening a text file with option `-c` results in corrupted screen with Neovim

### ISSUE THREAD

**Issue by itaranto** [jarun/nnn#1740]
By just setting `NNN_OPTS=c`, if I open a text file with *Enter* then the terminal screen gets "corrupted" (see below).

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Arch Linux
- [x] Desktop Environment: Sway
- [x] Terminal Emulator: Alacritty
- [x] Shell: fish
- [ ] Custom desktop opener (if applicable): None (`NNN_OPENER` not set)
- [] Program options used:
- [x] Configuration options set: `NNN_OPTS=cdouU` and `NNN_OPTS=c`
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master (`3176eaa8`)

#### Exact steps to reproduce the issue

- Make sure Neovim (`neovim.desktop`) is the default application for `text/plain`.
- Open `nnn` from the terminal
- Open a text file using *Enter* (not *e*)
- Let the file be opened by Neovim
-  The input keys seem to be picked by both applications: `nvim` and `nnn` at the same time, resulting in a corrupted screen.  See the attached video.

https://github.com/jarun/nnn/assets/11463919/fd529782-30f3-4734-8c70-3a693900cb10

[nnndbg.log](https://github.com/jarun/nnn/files/12755480/nnndbg.log)

I also tried with Neovim' s vanilla settings and the issue remains the same.

**Comment by jarun** [comment]
The option `-c` is to manually set a cli-only opener, e.g. I have the following:

    NNN_OPENER: /home/vaio/.config/nnn/plugins/nuke
