### ISSUE TITLE
Leader keys not working on i3 wm, Fedora

### ISSUE THREAD

**Issue by olablt** [jarun/nnn#175]
Hello

Please advice how to debug my problem - leader keys are not working for me. I have set these env variables:

```
export NNN_BMS="d:~/Downloads;p:/home/nemo/Projects;D:~/Documents/"
export NNN_USE_EDITOR=1
export NNN_DE_FILE_MANAGER=krusader # open with the o key
export DISABLE_FILE_OPEN_ON_NAV=1
```

When I press <kbd>`</kbd>, <kbd>d</kbd> or <kbd>^/</kbd>, <kbd>d</kbd> I expect to go to my Downloads folder, but nnn just hides the time column.

**Comment by olablt** [comment]
it was 1.9. After compiling the master the problem is gone.

Is it possible to remap the leader?

**Comment by jarun** [comment]
> it was 1.9. After compiling the master the problem is gone.

Awesome!

> Is it possible to remap the leader?

Not without recompiling. You can change the mappings in nnn.h. However, we won't be able to support any customization. If you check the help screen (`?`) you would know why. ;)
