### ISSUE TITLE
User / group option not working.

### ISSUE THREAD

**Issue by kuntau** [jarun/nnn#1764]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Ubuntu Server & Big Sur
- [x] Desktop Environment: -
- [x] Terminal Emulator: Kitty & Wezterm
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [x] Configuration options set: `NNN_OPTS='acdEHFrxQU'`
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Just open nnn, there's no user/group info shown

<img width="397" alt="Screenshot 2023-11-19 at 11 01 48 AM" src="https://github.com/jarun/nnn/assets/327489/11554f9d-401a-4a25-bb54-5bf054daa1c6">

**Comment by jarun** [comment]
It's by design. Retrieving the user and group info increases the memory usage significantly. The information for the currently hovered file is shown on the status bar:

https://github.com/jarun/nnn/wiki/Developer-guides#compile-out-user-group-details-in-status-bar
