### ISSUE TITLE
Fluid exist from navigate-as-you-type mode

### ISSUE THREAD

**Issue by bbtdev** [jarun/nnn#177]
I am huge fan of navigate-as-you-type, I use nnn with -i exclusively.
I love the fact that some key shortcuts have a Ctrl alternative, for example C-] I can spawn shell in dir without exiting 'navigate-as-you-type', makes everything more "fluid".

But 2 things:
- to exit 'as you type' mode I have to press "Esc" twice, any plans to make it exit by pressing once?
- ^Q does not work for me, so I can't quit nnn directly from 'as you type' mode. Is this a bug or it's just me? On bash, after I press C-v to see the keys being sent, if I press C-q I get "^Q" so I should not have any issues.

Thank you so much for your effort.

**Comment by bbtdev** [comment]
I see.
^Q does not work. Will investigate and maybe I will open another issue. 
Thank you

**Comment by Enlik** [comment]
I'd like to join this request.

Use case is using keys like 'p' on a file after using a filter, but it applies to the navigate-as-you-type mode as well.

1. Press /.
2. Type something to navigate to wanted file.
3. Now to use a binding without ctrl, it's needed to quit the mode. `^L' is not okay as it resets the selected file. `^T` suggested above is not okay as it switches the mode (as of version 2.x?) which is an unwanted side effect (so to quit the filter, one needs to press `^T` twice to switch the mode back). Pressing `^N` then `^P` (go down, go up) works but that's two bindings to press - it doesn't feel comfortable.

**Comment by jarun** [comment]
@Enlik 

>  Pressing ^N then ^P (go down, go up) works but that's two bindings to press

You can always use up/down arrows.

For the original issue, `^Q` should work. Does it not work for you as well?

I am aware that non-^ keybinds have this extra step in the _nav_as_you_type_ mode. You can either add a character to the filter or as a command. And I can't add a ^ keybind for every key in `nnn`.

You have to prioritize on what you do more. In my case, I edit files in the EDITOR (which is vim) and I press <kbd>Enter</kbd>. Works perfectly for me in the filter mode. If you prefer to use the PAGER, switch your EDITOR and PAGER and press <kbd>Enter</kbd> so the file is paged.

**Comment by Enlik** [comment]
`^Q` works for me after starting nnn with and without `-i`, so that's not a problem for me.

The problem with Enter is that it uses xdg-open if the file in question seems to be a text file, and in my case it leads to things like libreoffice writer being opened for a simple text file… Yes it's a problem with my environment, anyway I avoid pressing Enter for this reason. (Yes, I have NNN_USE_EDITOR=1.)

**Comment by Enlik** [comment]
"uses xdg-open if the file in question seems to be a text file" - actually, when it *doesn't* seem to be a text file. Empty file is an example.

**Comment by Enlik** [comment]
Empty test file case is weird, so there's something more intersting: a tar.gz file. Enter somewhat rightfully opens it in a gui archiver, but when I'm on the console I prefer to use cli commands, such as `less` that is able to list archive contents. And I don't know if xdg-open is able to detect this, without wrappers at least.

**Comment by jarun** [comment]
`xdg-open` doesn't and shouldn't because it's meant for X primarily. For handling archives you have keybinds in `nnn`. And at any time you can use Open with (`^O`).

**Comment by Enlik** [comment]
Yes, Open with is what I often end up using, too.

Anyway, just something to consider: a key binding with ctrl that passes through the next one, or disables nav-as-you-type and filters until next key, with usage like this (assume I have a filter active and want to open a file with pager - `p`):

`^V p`

anyway, that's just an idea, good or bad. Thanks for the discussion!

**Comment by Enlik** [comment]
Hah actually `^v` (and at least some of the other unused bindings too) *happen to* reset the filter nicely.

**Comment by Enlik** [comment]
Nice non-unused one (so less chance for conflict with a future version) is `^u`. @bbtdev I guess it can improve your experience too.

**Comment by jarun** [comment]
Try `^Esc`. Works for me.

I will use `^V` to run custom scripts. It's used more frequently than I thought after the script dir support. ;)

**Comment by jarun** [comment]
Guys, `Esc` is a dedicated key to clear the prompt. Read the docs so I don't have to scratch my head every time. ;)

**Comment by Enlik** [comment]
There are two problems with Esc.

1. (Just a bit annoying) there's a delay after pressing it until it has the effect. It's a common problem with Esc in terminals, however vim manages to make it instant.
2. (This is a deal breaker) at least in my case, Esc can switch the selected file to another one:
  - press /
  - type abc, have abc file selected
  - press Esc - abc is still selected (good!)
  - press / again
  - search for def
  - press Esc
  - notice that some other file is selected

**Comment by jarun** [comment]
It would be great if you can debug this.

**Comment by jarun** [comment]
Fixed at https://github.com/jarun/nnn/commit/72e305759e66cbd6d7e6aa139e93ff5980c66cad.

**Comment by Enlik** [comment]
Pretty cool, also with reducing delay after Esc!
