### ISSUE TITLE
Can't get jump to command or autojump plugin to work

### ISSUE THREAD

**Issue by slferris** [jarun/nnn#1772]
#### Environment details (Put `x` in the checkbox along with the information)

- [x ] Operating System: macOS Sonoma 14.1.1
- [ x] Desktop Environment: Mac mini M2 with Studio Display
- [ ] Terminal Emulator: iTerm2
- [ x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used: j:autojump
- [ ] Configuration options set:
- [ x] Plugins are installed including autojump
- [x ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
I type capital J to get "jump to" command line. Command line says "jump (+n/-n/n):" I assume that means enter a pathname, although the +n and -n are not clear to me. I enter a relative or absolute pathname, such as /Users/<my account name>. Nothing happens. So I try invoking the plugin autojump. This takes me to iTerm2. The command line there reads "jump to:' I type an absolute path. iTerm2 takes me back to nnn to the point where I started, not to the point I want to jump to.

**Comment by slferris** [comment]
I notice that homebrew has an autojump binary. Could that be causing some confusion for nnn autojump?

**Comment by 7ocb** [comment]
@slferris I think that "jump to" is "jump to entry number N", so if you want to jump to entry number 100 in listing you do "jump to" and enter 100. If you want to jump 100 items forward, do "+100", and "-100" if 100 items backwards. May be useful in case of really long listings, I guess.

[autojump](https://github.com/wting/autojump) I think is some kind of "shortcutting cd" not the "cd by full path".

The functionality you are searching can be achieved with plugin like mentioned in [this comment](https://github.com/jarun/nnn/issues/1758#issuecomment-1810211494) I think.

**Comment by jarun** [comment]
@7ocb your explanation of "jump to" is correct.
