### ISSUE TITLE
U+E5FF /  / question mark box

### ISSUE THREAD

**Issue by mustafa0x** [jarun/nnn#1777]
![image](https://github.com/jarun/nnn/assets/1473102/b3587e82-e024-4853-a16b-41b1f6a209c6)

Seems like it's from here.

https://github.com/jarun/nnn/blob/f2a909dafddaa1f8ed2541fbd5873015c9a4710b/src/icons.h#L51-L53

#### Environment details (Put `x` in the checkbox along with the information)

- [ ] Operating System: Mac
- [ ] Desktop Environment:
- [ ] Terminal Emulator:
- [ ] Shell:
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Plugins are installed
- [ ] Issue exists on `nnn` master

**Comment by N-R-K** [comment]
You didn't specify which icons you are using or which font or which terminal etc. Please follow the steps in the wiki and make sure your environment is properly configured https://github.com/jarun/nnn/wiki/Advanced-use-cases#file-icons

**Comment by mustafa0x** [comment]
Thanks @N-R-K!

I just installed with brew. I'm on the latest version.

https://github.com/jarun/nnn/wiki/Advanced-use-cases#file-icons says:

> They are turned off by default and are not provided in the default distribution to avoid shipping third party resources.

Which is interesting. Not sure how they got turned on.

**Comment by mustafa0x** [comment]
Quite odd indeed; thanks for the help @N-R-K.
