### ISSUE TITLE
NNN_TRASH_CUSTOM  setting not working

### ISSUE THREAD

**Issue by slferris** [jarun/nnn#1780]
I am using NNN on macOS Sonoma with zsh and Oh-My-Zsh.

When I invoke export NNN_TRASH=1 to use trash-cli to export deleted files, trash-cli puts the deleted files in ~/.local/share/Trash/files. I want them sent to my Desktop Trash at  ~/.Trash. I don't want to have to look for trashed files in two places. I have placed export NNN_TRASH_CUSTOM="$HOME/.Trash" in my .zshrc config file, but trash-cli still ignores it and sends deleted files to ~/.local/share/Trash/files. I have also created a symlink from the latter to ~/.Trash, but it doesn't quite work the way I would like.

How can I get trash-cli to put files deleted in NNN into my Desktop Trash, just like any other files I trash?

**Comment by 7ocb** [comment]
@slferris I don't think `nnn` uses `NNN_TRASH_CUSTOM` environment variable at all. 

It looks like `~/.local/share/Trash/files` is the default place where `trash-cli` puts deleted files. Also I think `nnn` is not resposible for behavior of `trash-cli`, `nnn` just invokes it for files to be deleted.

**Comment by jarun** [comment]
There's only one config `NNN_TRASH` and we support `gio trash` or `trash-cli`.
Please find more details in the wiki: https://github.com/jarun/nnn/wiki/Usage

**Comment by slferris** [comment]
Sure. Nobody would expect nnn to be responsible for where trash_cli puts deleted files. My question is is there a good work-around to effectively move the files into Desktop Trash?

**Comment by N-R-K** [comment]
> My question is is there a good work-around to effectively move the files into Desktop Trash?

I don't think any of the maintainers here uses macos, so we wouldn't be able to help you here. But I see that there was an answer provided [here](https://github.com/andreafrancia/trash-cli/issues/323#issuecomment-1848924141).

If you (or anyone) can come up with a good solution that doesn't require hardcoded binary path then feel free to send a pull request.
