### ISSUE TITLE
preview-tabbed - zathura not focusing

### ISSUE THREAD

**Issue by MaMiMa81** [jarun/nnn#1793]
Using preview-tabbed works as expected, as it always did, apart from zathura.
The preview window is launched with zathura on the workspace in the WM and the associated file changes with navigation through files in the file manager pane however the file is not displayed with zathura until I manually focus the plugin window i.e. with the curser or even by manually invoking:

        xdotool windowactivate "$XID"

This has recently started happening and all other file-types are still displayed as before with their various opening applications as navigation is traversed through the file manager without issue.

Both zathura and my WM, spectrwm, have received updates recently but it appears just specific to the plugin interaction with zathura.
I'm using the latest nnn version and the most recent set of plugins.

### EDIT:
Indeed it is due to the zathura upgrade that preview_tabbed pdf functionality has ceased working correctly.
I earlier downgraded zathura from 0.5.4 to 0.5.2 but I failed to downgraded the dependency girara from 0.4.1 to 0.4.0 and
conscequently I still encountered the issue described above but after downgrading both zathura and girara the correct functionality of preview_tabbed is restored.

It appears that the issue is with the latest upgrade of zathura (with girara of course) and tabbed:

[https://git.pwmt.org/pwmt/zathura/-/issues/388](url)

            running zathura with tabbed causes default binds to break

Apologies for not being more thorough initially but this may highlight this issue if anyone experiences it.
I shall leave this issue open until the developer decides to close it if appropriate.

**Comment by N-R-K** [comment]
I'm not on latest zathura so can't reproduce.

> https://git.pwmt.org/pwmt/zathura/-/issues/388

Looks like it's a zathura issue and not a problem with the `preview-tabbed` script. If there's a known workaround then feel free to share.

**Comment by jarun** [comment]
Closing since there's no response.

**Comment by MaMiMa81** [comment]
> I'm not on latest zathura so can't reproduce.
> 
> > https://git.pwmt.org/pwmt/zathura/-/issues/388
> 
> Looks like it's a zathura issue and not a problem with the `preview-tabbed` script. If there's a known workaround then feel free to share.

The workaround currently for me is I am still using zathura v. 0.5.2 with girara v. 0.4.0 & zathura-pdf-poppler v. 0.3.1 - not really satisfactory as new versions of zathura, girara & zathura-pdf-poppler are released.

**Comment by MaMiMa81** [comment]
#https://github.com/pwmt/girara/issues/49#issuecomment-2478686982

**Comment by MaMiMa81** [comment]
https://github.com/pwmt/girara/issues/49

**Comment by MaMiMa81** [comment]
Further to my previous - I've done some playing around & found away to make zathura work with tabbed under nnn preview-tabbed plugin by doing a xdotool dance, highlighted in **bold** below in the plugin.
 It's a bit ugly but it works (for me anyway) - the sleeps are to allow focus - probably due to my tired old CPU and also I couldn't get the `--sync`option under xdotool to work.

Any comments or improvements feel free to chime in.

HTH


`preview-tabbed`

149         MIME="$(file -bL --mime-type "$FILE")"
**150         winclass="$(xdotool search --class tabbed)"**
151 
152         case "$MIME" in
153             video/* )
154                 if type mpv >/dev/null 2>&1 ; then
155                     mpv --force-window=immediate --loop-file --wid="$XID" "$FILE" &
156                 else
157                     term_nuke "$XID" "$FILE"
158                 fi
159                 ;;


175             application/pdf)
176                 if type zathura >/dev/null 2>&1 ; then
177                     zathura -e "$XID" "$FILE" &
**178                     sleep 0.5
179                     xdotool windowactivate "$winclass"
180                     sleep 0.2
181                     xdotool key super+shift+k**
182                 else
183                     term_nuke "$XID" "$FILE"
184                 fi
185                 ;;
