### ISSUE TITLE
Nerd fonts cause misaligned columns in detail mode with names first

### ISSUE THREAD

**Issue by erhhung** [jarun/nnn#1802]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: macOS Sonoma 14.2.1
- [ ] Desktop Environment:
- [x] Terminal Emulator: iTerm2 3.4.23
- [x] Terminal Font: DroidSansM Nerd Font Regular 16, no ligatures
- [x] Shell: Bash 5.2.26
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: `NNN_OPTS=acdeoEHQR`
- [ ] Configuration options set:
- [x] Plugins are installed: `NNN_PLUG=v:-preview-tui;y:-cbcopy-mac`
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. Create a build with Nerd Fonts and name first options enabled:
  `make clean; make O_NERD=1 O_NAMEFIRST=1; ./nnn`

  <img width="467" alt="image" src="https://github.com/jarun/nnn/assets/5808864/48cd4cd6-de12-4be5-bde9-7bd894b1c5d5">

2. Press `d` to hide the detail columns:

  <img width="297" alt="image" src="https://github.com/jarun/nnn/assets/5808864/1445bf76-7aca-4316-a3d7-865690506509">

  Notice that the **file size column has not been properly cleared**.

3. If, instead, build without either above options, columns are aligned:

  `make clean; make O_NERD=1; ./nnn`

  <img width="465" alt="image" src="https://github.com/jarun/nnn/assets/5808864/27e944d1-c496-4437-b84e-c6715ce0b53f">

  `make clean; make O_NAMEFIRST=1; ./nnn`

  <img width="426" alt="image" src="https://github.com/jarun/nnn/assets/5808864/c03e427d-e9a8-4822-b79b-2b8b5a296be4">

#### Other observations

1. Changing the terminal font in iTerm to other Nerd fonts made no difference.
2. I'm aware that some Nerd font glyphs yield double the character widths even though they visually take up only a single cell, but I'm not sure if there's a consistent way to account for that during rendering of the columns.

**Comment by luukvbaal** [comment]
I vaguely remember a similar issue, either from myself or by another user on the issue tracker. But I can't reproduce this locally on master so it seems to be a platform/font/terminal issue.

**Comment by N-R-K** [comment]
Likely cause by macos `wcswidth` returning 2 width for some icons: https://github.com/jarun/nnn/issues/1692#issuecomment-1637153406

**Comment by luukvbaal** [comment]
Thanks. I suppose updating the namefirst patch to use the added macro might fix this then.

**Comment by N-R-K** [comment]
> Only thing I can think of to work around this would be to hardcode the wcswidth for the offending icons.

There was also this patch (https://github.com/jarun/nnn/pull/1694) which fixed the issue by clearing the whole screen IIRC. It "worked" but had pretty bad performance impact though. Maybe this gives you some ideas.

**Comment by KlzXS** [comment]
Added to Tracker. Closing here.

Since day 1 there have been problems with alignment with icons. This is an old issue and seems deeply connected to the way terminals render characters. In all this time no one has been able to either solve the issue universally or provide proof that it can't be done. We'll just leave it there in case someone want to give it another shot.
