### ISSUE TITLE
nnn compiled with nerdfonts not displaying correctly in WSL

### ISSUE THREAD

**Issue by wlxer** [jarun/nnn#1807]
Hi, I installed ubuntu version 20.04 on windows 11pro using wsl2. And ready to use ubuntu20.04 through windows terminal. My bash version is 5.0.17. Recently I wanted to install nnn with nerdfont in ubuntu. so I executed the following command under $home directory:
```
git clone --depth 1 https://github.com/jarun/nnn
cd nnn
sudo make O_NERD=1
sudo cp nnn /usr/bin
```
The whole compiling process was smooth. 
<img width="532" alt="image" src="https://github.com/jarun/nnn/assets/33346174/16ec8d11-ac45-4235-9614-3bf0f9d80e92">
By executing the already compiled file ‘./nnn’, it is also able to display icon for folders and such:
<img width="441" alt="image" src="https://github.com/jarun/nnn/assets/33346174/386c256d-b6b2-419f-99af-114d3701f7ad">

But I found that the icon didn't appear when I direcly use the command 'nnn':
<img width="361" alt="image" src="https://github.com/jarun/nnn/assets/33346174/71aad778-b5ef-4c2d-9ea1-e4b281d2754e">
 
By the way, I have installed the following four mesloLG NF mono FONT in my Windows11
<img width="527" alt="image" src="https://github.com/jarun/nnn/assets/33346174/909e45e6-116f-4b30-ac3c-18df37222823">
and modified the relative setting.json file of windows terminal:
<img width="388" alt="image" src="https://github.com/jarun/nnn/assets/33346174/ad562696-f80e-4a98-a9af-53d4c07ffe4a">
The display of fonts is really not a problem, but I do still have problems with displaying the icon using nnn, which makes me confused.

--- PLEASE DELETE THIS LINE AND EVERYTHING ABOVE ---

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: windows11pro 22H2 and WSL2 with Ubuntu 20.04
- [ ] Desktop Environment:
- [x] Terminal Emulator: windows terminal
- [x] Shell: bash 5.0.17
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: O_NERD = 1
- [ ] Configuration options set:
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master

**Comment by N-R-K** [comment]
> But I found that the icon didn't appear when I direcly use the command 'nnn':

Post the output of `which nnn`. It's likely invoking the old binary and not the new one.

>sudo make O_NERD=1

You shouldn't need `sudo` for compiling. It's only needed for `install`.

>sudo cp nnn /usr/bin

Why not use `sudo make install` instead of manually copying?

**Comment by wlxer** [comment]
> > But I found that the icon didn't appear when I direcly use the command 'nnn':
> 
> Post the output of `which nnn`. It's likely invoking the old binary and not the new one.
> 
`which nnn` turns out to be:
<img width="426" alt="image" src="https://github.com/jarun/nnn/assets/33346174/46636748-ccc8-464c-af4a-dcc7dd04bd54">

> > sudo make O_NERD=1
> 
> You shouldn't need `sudo` for compiling. It's only needed for `install`.
> 
> > sudo cp nnn /usr/bin
> 
> Why not use `sudo make install` instead of manually copying?

I figured out what the problem was, it was indeed that the nnn packages that had been installed by ‘apt-get install’ before were not removed correctly. Thanks for your comments! I will close this issue.
