### ISSUE TITLE
NNN broken on master

### ISSUE THREAD

**Issue by amanjitsk** [jarun/nnn#1810]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Ubuntu 22.04
- [x] Desktop Environment: bspwm
- [x] Terminal Emulator: kitty/st/wezterm
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable): nuke
- [x] Program options used: `"cBdEfHorQSUx"`
- [x] Configuration options set:

    ```sh
    export NNN_ARCHIVE="\\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip|zst)$"
    export NNN_OPTS="cBdEfHorQSUx"
    export NNN_OPENER="$XDG_CONFIG_HOME"/nnn/plugins/nuke
    export NNN_TRASH=1
    export NNN_PREFER_SELECTION=1
    export NNN_COLORS="42564256"

    BLK="0B" CHR="0B" DIR="04" EXE="06" REG="00" HARDLINK="06" SYMLINK="06" MISSING="00" ORPHAN="09" FIFO="06" SOCK="0B" OTHER="06"
    export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
    export NNN_HELP="pfetch"
    export NNN_LOCKER="vlock"
    export NNN_FIFO="$XDG_RUNTIME_DIR/nnn.fifo"
    export NNN_SEL="$XDG_CONFIG_HOME/nnn/selection"
    ```
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Compiling with `make O_PCRE=1 O_CKBOARD=1 O_CTX8=1 O_NERD=1 O_GITSTATUS=1 strip install` breaks nnn on master. In particular, 8 contexts are not available (only 4 are), and if nnn is launched without an argument, it crashes due to segmentation fault (i.e. `nnn .` works, but `nnn` does not). Something went severely wrong in the last 3 commits.

**Comment by jarun** [comment]
> Something went severely wrong in the last 3 commits.

Please confirm which one.

**Comment by N-R-K** [comment]
Works okay on my end. Try and see if you can reproduce with a clean config without any options or not. Also make sure you have a clean build to rule out any weird build issues (e.g run `make clean` before compiling).

**Comment by amanjitsk** [comment]
Whoops, my bad. It was indeed running `make clean` before re-building. Thanks!
