### ISSUE TITLE
Raspberry Pi: nnn Illegal instruction

### ISSUE THREAD

**Issue by optio50** [jarun/nnn#182]
armhf architecture
tried the deb file from debian sid and also tried compiling from source from this git.
same result on each.
Illegal instruction

Details:
kernel 4.14.81+
Rasppberry pi Zero W
OS DietPi

**Comment by szlin** [comment]
Hi  @jarun @optio50 

I have tested nnn 2.2-1 package in **native armhf device - Cortex A15 (kernel 4.14.44)** and **qemu armhf environment (kernel 4.18.6).**

**Both of them work well.**

Currently, the Debian armhf port requires at least an Armv7 CPU. However, Rasppberry pi Zero uses Armv6 CPU. That means you should use armel instead of armhf with nnn or use custom kernel [1].

[1] https://wiki.debian.org/RaspberryPi

In native armhf device:

> root@arm:/home/debian# cat /etc/debian_version
> buster/sid
> 
> root@arm:/home/debian#  file /usr/bin/nnn
> /usr/bin/nnn: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=77425b6293dfca9687536a973fc5a75195b65184, stripped
> 
> root@arm:/home/debian# nnn -h
> usage: nnn [-b key] [-C] [-e] [-i] [-l]
>            [-p file] [-S] [-v] [-h] [PATH]
> 
> The missing terminal file manager for X.
> 
> positional args:
>   PATH   start dir [default: current dir]
> 
> optional args:
>  -b key  bookmark key to open
>  -C      disable directory color
>  -e      use exiftool instead of mediainfo
>  -i      start in navigate-as-you-type mode
>  -l      start in light mode
>  -p file copy selection to file (stdout if '-')
>  -S      start in disk usage analyser mode
>  -v      show program version
>  -h      show this help
> 
> Version: 2.2
> License: BSD 2-Clause
> Webpage: https://github.com/jarun/nnn

In qemu armhf environment:

> root@szlin-TW:/# cat /etc/debian_version
> buster/sid

> root@szlin-TW:/# file /usr/bin/nnn
> /usr/bin/nnn: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=77425b6293dfca9687536a973fc5a75195b65184, stripped

> root@szlin-TW:/# nnn -h
> usage: nnn [-b key] [-C] [-e] [-i] [-l]
>            [-p file] [-S] [-v] [-h] [PATH]
> 
> The missing terminal file manager for X.
> 
> positional args:
>   PATH   start dir [default: current dir]
> 
> optional args:
>  -b key  bookmark key to open
>  -C      disable directory color
>  -e      use exiftool instead of mediainfo
>  -i      start in navigate-as-you-type mode
>  -l      start in light mode
>  -p file copy selection to file (stdout if '-')
>  -S      start in disk usage analyser mode
>  -v      show program version
>  -h      show this help
> 
> Version: 2.2
> License: BSD 2-Clause
> Webpage: https://github.com/jarun/nnn
>

**Comment by jarun** [comment]
Thanks a lot for the analysis @szlin!

@optio50 please try with the above config and toolset.

**Comment by jarun** [comment]
Closing the issue as there's no response.
