### ISSUE TITLE
mv: unrecognized option '--cp'

### ISSUE THREAD

**Issue by c79cea05** [jarun/nnn#1822]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Slackware
- [ ] Desktop Environment:
- [ ] Terminal Emulator:
- [ ] Shell:
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
$ mkdir -p /tmp/nnn_bug/{a,b}
$ touch /tmp/nnn_bug/a/c
$ nnn /tmp/nnn_bug
press + h j l v

git bisect shows that commit b392dd372342edbd80bb05c9fffeea47da11d95a is the cause.

**Comment by N-R-K** [comment]
Does https://github.com/jarun/nnn/pull/1821 fix your issue?

**Comment by c79cea05** [comment]
> Does #1821 fix your issue?

Yes
