### ISSUE TITLE
Icons does not work when NNN is opened with -C option

### ISSUE THREAD

**Issue by MathevsBatista** [jarun/nnn#1823]
- Operating System: Artix
- Desktop Environment: Hyprland
- Terminal Emulator: Kitty
- Shell: Bash
- Program options used: -C
- Configuration options set: O_NERD=1
- Plugins are installed: No
- Issue exists on `nnn` master: Yes

#### Exact steps to reproduce the issue

1. Install nerdfont Jetbrains Nerd Font Mono and config the terminal to use it.
2. Install nnn with O_NERD=1 option.
3. Open nnn without -C option to see icons working (proves that icons work with jetbrains nerd font mono).
![image](https://github.com/jarun/nnn/assets/43383727/8c59eb74-7cdd-42bf-a24b-3e0425a6b195)
4. Now open it with -C option, icons do not work.
![image](https://github.com/jarun/nnn/assets/43383727/cb91c3c4-8a22-45ca-9a1b-ee9bebd55ee2)

**Comment by jarun** [comment]
This works as designed. Icons are not shown in 8-color mode.

**Comment by jarun** [comment]
You should read the documentation first - https://github.com/jarun/nnn/wiki/Advanced-use-cases#file-icons

_Note that your $TERM must support 256 colors for the icons to show._

**Comment by MathevsBatista** [comment]
Wait, I have a question, kitty does support 256 colors, this means that the theme should be 256 colors to make icons work? When I read that in the wiki I had thought that it was all ok!

**Comment by N-R-K** [comment]
> kitty does support 256 colors

`-C` enables 8 color mode. And so that disables 256 color output along with emojies. I've updated the wiki to make it more clear.

**Comment by MathevsBatista** [comment]
Thanks!
