### ISSUE TITLE
preview-tui: mpv

### ISSUE THREAD

**Issue by h14turkiye** [jarun/nnn#1825]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Linux Mint Cinnamon
- [x] Desktop Environment: X11
- [x] Terminal Emulator: kitty
- [x] Shell: bash
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: -deioa
- [] Configuration options set:
- [x] Plugins are installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I have nnn 4.8, saw that mpv is on 4.9, just copied the preview-tui file, installed mpv via flatpak made an alias for it "mpv". 
When I use the plugin only a black screen appears, when I remove the --no-audio, audio plays so the video plays but there is no vision...

Running kitty and using mpv command inside works.

**Comment by jarun** [comment]
@luukvbaal please have a look.

**Comment by duong-db** [comment]
@h14turkiye In the terminal, try to open a video inside ```Kitty``` and verify if it works:
```bash
$ mpv --vo=kitty <your_video_file>
```
I caught this error:
```bash
 (+) Video --vid=1 (*) (h264 1920x1080 29.970fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
[vo] Video output kitty not found!
Error opening/initializing the selected video_out (--vo) device.
Video: no video
```
It seems that there was a problem with the `video output (--vo)` configuration of  `mpv`. However, by setting `--vo=tct`, the video played normally but resulted in a very low resolution.

**My possible solution.**
 
![Screenshot from 2024-02-21 23 09 59](https://github.com/jarun/nnn/assets/137669565/386b9f63-0476-4f10-b799-3f712a8aebac)

Download the [timg](https://github.com/hzeller/timg?tab=readme-ov-file#installation) package and replace the line 468 in your `preview-tui` configuration file with: 
```bash
timg -p kitty --center "$3" &
```
Now, the video previewing function in `nnn` works.  (You may need to modify some other small details in the code to make it more consistent)

**Comment by h14turkiye** [comment]
> @h14turkiye In the terminal, try to open a video inside `Kitty` and verify if it works:
> 
> ```shell
> $ mpv --vo=kitty <your_video_file>
> ```
> 
> I caught this error:
> 
> ```shell
>  (+) Video --vid=1 (*) (h264 1920x1080 29.970fps)
>  (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
> [vo] Video output kitty not found!
> Error opening/initializing the selected video_out (--vo) device.
> Video: no video
> ```
> 
> It seems that there was a problem with the `video output (--vo)` configuration of `mpv`. However, by setting `--vo=tct`, the video played normally but resulted in a very low resolution.
> 
> **EDIT.** I realized that my problem was caused by the old version of `mpv` package in the Ubuntu repo (0.34 vs 0.37-newest). However, the following solution may suit anyone who want to use `timg` as the video output backend for `kitty` instead of `mpv`.
> 
> **A possible solution.**
> 
> ![Screenshot from 2024-02-21 23 09 59](https://private-user-images.githubusercontent.com/137669565/306693096-386b9f63-0476-4f10-b799-3f712a8aebac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NTAzMjMsIm5iZiI6MTcwODU1MDAyMywicGF0aCI6Ii8xMzc2Njk1NjUvMzA2NjkzMDk2LTM4NmI5ZjYzLTA0NzYtNGYxMC1iNzk5LTNmNzEyYThhZWJhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQyMTEzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzcwMmJlODRmNWRiMmNlZjYyODgyZDczNWU2MzQxOGMwNTNmMGM1MTRhMjJlZTY5OTlkNzY5ZjRiZjVkMWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u2lcvc_WWOWi5zdEf8SyJY8unZrUv1ZxdwgLr5wLg_I)
> 
> Download the [timg](https://github.com/hzeller/timg?tab=readme-ov-file#installation) package and replace the line 468 in your `preview-tui` configuration file with:
> 
> ```shell
> timg -p kitty --center "$3" &
> ```
> 
> Now, the video previewing function in `nnn` works. (You may need to modify some other small details in the code to make it more consistent)

I downloaded flatpak version mpv, which is 0.37 and did work with kitty but not with nnn. timg produced same thing, working with kitty but not with nnn. Both also work within a split window when used in kitty but not with nnn.

I use kitty nnn -deioa to launch nnn

**Comment by duong-db** [comment]
@h14turkiye How did you get the ```preview-tui``` config file? You may have an older version of ```preview-tui``` if you follow [this](https://github.com/jarun/nnn/blob/master/plugins/README.md#installation) installation instruction as reported [here](https://github.com/jarun/nnn/issues/1746#issuecomment-1762008116). It is recommended to download it manually and make the file executable.

**Comment by h14turkiye** [comment]
> @h14turkiye How did you get the `preview-tui` config file? You may have an older version of `preview-tui` if you follow [this](https://github.com/jarun/nnn/blob/master/plugins/README.md#installation) installation instruction as reported [here](https://github.com/jarun/nnn/issues/1746#issuecomment-1762008116). It is recommended to download it manually and make the file executable.

Because the file did not have preview-video section, I just copy pasted the file from the github.

**Comment by h14turkiye** [comment]
I just upgraded to 4.9 via [here](https://packages.debian.org/trixie/nnn), and ran the installation instruction again. It still doesn't provide the latest version of preview-tui.

**Comment by duong-db** [comment]
> I just upgraded to 4.9 via [here](https://packages.debian.org/trixie/nnn), and ran the installation instruction again. It still doesn't provide the latest version of preview-tui.

Does `preview-tui`  work with `.gif` files in your `kitty`?

**Comment by h14turkiye** [comment]
> > I just upgraded to 4.9 via [here](https://packages.debian.org/trixie/nnn), and ran the installation instruction again. It still doesn't provide the latest version of preview-tui.
> 
> Does `preview-tui` work with `.gif` files in your `kitty`?

Nope.

**Comment by duong-db** [comment]
> > 
> > 
> > Does `preview-tui` work with `.gif` files in your `kitty`?
> 
> Nope.

@h14turkiye Remove mpv and check it again. 

If it works, it indicates that mpv was likely causing this issue. By default, `icat` (kitty) is responsible for previewing .gif files. When having mpv installed, kitty will use mpv to preview both gifs and videos instead.

**Comment by h14turkiye** [comment]
> > > Does `preview-tui` work with `.gif` files in your `kitty`?
> > 
> > 
> > Nope.
> 
> @h14turkiye Remove mpv and check it again.
> 
> If it works, it indicates that mpv was likely causing this issue. By default, `icat` (kitty) is responsible for previewing .gif files. When having mpv installed, kitty will use mpv to preview both gifs and videos instead.

After deleting mpv, I checked the gifs and it didn't work. I tried snap(I really prefer flatpak) and the video and gif worked for me. 
Flatpak version of mpv is bugged.

**Comment by N-R-K** [comment]
@luukvbaal Maybe the `exists mpv` checks should be replaced to actually check if the requested vo exists or not since `kitty/sixel` are optional and can be complied out. Or the mpv version might be outdated.
