### ISSUE TITLE
Syntax error with prescribed split-pane script

### ISSUE THREAD

**Issue by slferris** [jarun/nnn#1826]
#### Environment details (Put `x` in the checkbox along with the information)

- [ x] Operating System: macOS 14.3.1
- [x] Desktop Environment: Mac-mini M2
- [ x] Terminal Emulator: iTerm2
- [x ] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used: -RaUi
- [ ] Configuration options set:  
- [x ] Plugins are installed 
- [ x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I'm trying to create an "ewrap" script to enable split-pane feature in nnn. I copied it from your nnn repos, but when I try to create a script, I get a syntax error: Expected "," or "]" but found """.  Here is the script as I copied it:

#!/usr/bin/env sh

if [ -n "$TMUX" ] ; then
    # tmux session running
    tmux split-window -h "vim \"$*\" "
else
    # Remove option --tab for new window
    xfce4-terminal --tab -e "vim \"$*\" "
fi

**Comment by slferris** [comment]
￼

**Comment by N-R-K** [comment]
> I am not able to edit the text document in vim

You need to actually start providing more info if you want any help. Just saying "doesn't work" provides zero information for us to try to figure out what might be going wrong.

And for the record, I can edit just fine with vim on the newly created tmux split.

**Comment by slferris** [comment]
Sorry I annoyed you. Thanks for your response.

**Comment by KlzXS** [comment]
It's been 3 weeks and no new info.

> Here is the unobstructed view of the script.

I can't even see what's posted here:
![image](https://github.com/jarun/nnn/assets/25376866/640f0dd4-ee8d-427d-81f6-783e29dee92b)

I'm closing this and if you still have problems with this post full script and error messages and we'll revisit it.
