### ISSUE TITLE
Great project, any way to pick a file or directory and pass to stdout ??

### ISSUE THREAD

**Issue by skywind3000** [jarun/nnn#183]
Previously, I use fzf to pick up a file, like:

```
cd "$(find ... | fzf)"
```

It is very handy to use fzf to generate a parameter for a command, fzf will use the standard output to display the result. 

But as fuzzyfinders require me to remember the file/dir name (or a part of it), in other words, they can only be used in old familiar projects. And useless in any new project or when user forget file names.

nnn is another file picker, but when I use nnn, I must stay in nnn, and execute command from nnn. Because I can't just do all the things in nnn, most of work need to be done in command line. 

Can I just use nnn to choose a file/dir and provide the chosen path as a parameter of other commands ??

eg, if I input the command below in command line:

```bash
head -20 "$(nnn)"
```

I can select a file in nnn, if I press ENTER, nnn quits and output the chosen filename to stdout. (TUI can be rendered to stderr, just like what fzf dose). or ESC to quit and output nothing. 

to be more specific, I can write a bash function in my `.bashrc` as:

```bash
function nhead() {
    local output="$(nnn)"
    if [ -n "$output" ]; then
        head -20 "$output"
    fi
}
```

other examples:

```
cd "$(nnn --dir-only)"
hexdump "$(nnn)"
tar -zvxf "$(nnn)"
```

If it is possible, I can be more productive then ever.

**Comment by jarun** [comment]
Yep! Use:

    nnn -p -
For a single file, press `Enter` on the file. For multiple, use `^Y`-`^K`-`^Y` and press `q` to quit.

Sample output:

```
~$ nnn -p -
/home/vaio/bookmarks.db⏎

~$ nnn -p -
/home/vaio/bookmarks.db
/home/vaio/form15G_GH00717534.pdf
/home/vaio/form15G_GH00755946.pdf
/home/vaio/sample_bookmarks.zip
/home/vaio/sample_bookmarks.zip
```

**Comment by jarun** [comment]
There's one possible solution, `nnn` can redirect the output to a file. So you can:

    nnn -p list
and the names would be in list. To get the file paths, follow the instructions here to set up and set up an alias: https://github.com/jarun/nnn#get-selection-manually

**Comment by skywind3000** [comment]
It helps.
but why fzf can be used in the pipe ??

**Comment by skywind3000** [comment]
If stdout is not a tty, can nnn just use stderr to render TUI ??

**Comment by jarun** [comment]
`nnn` explicitly checks that stdin and stdout are tty and not pipes.

The behaviour of `nnn` is similar to vim. There are probably third-party solutions to fake the sdtin/stdout which may work but it's beyond the scope of the program.

You will find more explanation here:

https://stackoverflow.com/questions/21448452/why-more-command-cannot-read-stdin-but-from-piped-stdin

**Comment by jarun** [comment]
I played around a bit and here's what you want:

```
~$ cat script 
#!/bin/bash

nnn -p file
cat file
~$ cd (./script)
~/sample_bookmarks
$
```

I selected the directory `sample_bookmarks` using `^K`.

**Comment by jarun** [comment]
For the case where you need newline-spearated lists:

```
~$ cat script 
#!/bin/bash

nnn -p /tmp/nnnselection
> /tmp/outlist
while read -d $'\0' line ; do
    echo $line >> /tmp/outlist
done < /tmp/nnnselection
echo $line >> /tmp/outlist
cat /tmp/outlist
~$ ls -l (./script)
-rw-rw-r-- 1 vaio vaio 207872 Jan  2 00:31 /home/vaio/bookmarks.db
-rw-rw-r-- 1 vaio vaio     27 Jan  3 20:49 /home/vaio/file
-rw-rw-r-- 1 vaio vaio  10293 Dec 10 22:22 /home/vaio/form15G_GH00717534.pdf
-rw-rw-r-- 1 vaio vaio  10583 Dec 17 08:43 /home/vaio/form15G_GH00755946.pdf
~$
```

**Comment by skywind3000** [comment]
The script doesn't work for me:

![error](https://user-images.githubusercontent.com/3035071/50646834-15738b80-0fb2-11e9-92ad-e104f73f7e54.png)

**Comment by jarun** [comment]
Ahh, I use fish shell. If you are on bash, you have to use:

    ls -l `./script`

**Comment by jarun** [comment]
If you save `script` in your `PATH`, on bash you can use:

    cd `script`
and

    ls -l `script`

**Comment by jarun** [comment]
You can probably name the file `script` as `picker`. More appropriate for your use case.

**Comment by skywind3000** [comment]
It says "stdin or stdout is not a tty"

**Comment by jarun** [comment]
Here's my output from `bash`:

```
vaio @ tux  ~
└─ $ ▶ cat /usr/local/bin/picker 
#!/bin/bash

nnn -p /tmp/nnnselection
> /tmp/outlist
while read -d $'\0' line ; do
    echo $line >> /tmp/outlist
done < /tmp/nnnselection
echo $line >> /tmp/outlist
cat /tmp/outlist
vaio @ tux  ~
└─ $ ▶ ls -l `picker`
-rw-rw-r-- 1 vaio vaio 207872 Jan  2 00:31 /home/vaio/bookmarks.db
-rw-rw-r-- 1 vaio vaio     27 Jan  3 20:49 /home/vaio/file
-rw-rw-r-- 1 vaio vaio  10293 Dec 10 22:22 /home/vaio/form15G_GH00717534.pdf
-rw-rw-r-- 1 vaio vaio  10583 Dec 17 08:43 /home/vaio/form15G_GH00755946.pdf
```

I believe the issue you are seeing is a local issue which is hard for me to debug.

**Comment by jarun** [comment]
More details from my env if that helps:

```
~/G/nnn$ bash --version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
~/G/nnn$ uname -a
Linux tux 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

I am on Ubuntu 18.04.1, amd64.

**Comment by jarun** [comment]
Also, please use the version above. The `ls -l` example works for `cd` case too.

**Comment by jarun** [comment]
OK, hold on. I think I missed a step.

**Comment by jarun** [comment]
This needed changes in the source as well. The change is at commit 3cbb7dc5dfcbd79b672859959f3e6c6f264df0ec. You need to get the latest master.

Now `ls -l `nnn -p -` should also work. Though I would prefer the picker mode.

**Comment by jarun** [comment]
A simplified `picker` script: https://github.com/jarun/nnn/blob/master/scripts/user-scripts/picker.sh

**Comment by skywind3000** [comment]
thank you, picker script works very well.

there is one thing I have to mention, when I use:

```bash
cd `script`
```

to change directory, I have to press space on the selected directory and then press `q` to quit nnn.

Can I use ENTER to select a directory (like selecting a file) and quit immediately ??

I'd like to alias it to `ncd` command, it would be a used very frequently. Pressing ENTER once is more
productive than pressing SPACE and q.

**Comment by jarun** [comment]
You have to understand the concept of selections in `nnn` - https://github.com/jarun/nnn#selection

The picker picks the selection.

If I make `Enter` _pick_ the directory, it doesn't work very well with vim, where the primary use case is to open text files in vim. Yes, we can add hacks and make it _sophisticated_, but I would prefer users to understand how selections work.

**Comment by skywind3000** [comment]
yeah, I have read the documentation, is it possible to introduce a new key which allows me press and quit immediately ??

**Comment by skywind3000** [comment]
Yes, I understand, open source project, you owe me nothing. I just want nnn better.

There is already a plugin for zsh:
https://github.com/Vifon/deer

Which can be used like:

```bash
cd <curses> (ALT+k)
```

and it displays the file browser, after choosing, the command was completed as:

```bash
cd {chosen path} <curses>
```

Like a CTRL+T in fzf. but it only works in zsh and is very slow.

**Comment by jarun** [comment]
I meant it when I said _please feel free to fork the project and have your own_. You can have a wrapper around `nnn` (similar to the ad-hoc script for `^G` and achieve this with `^G`). In fact, I believe you don't even need to fork the project, a little modification of the script I shared should suffice.

**Comment by jarun** [comment]
I have documented the current behaviour here: https://github.com/jarun/nnn#file-picker

There is a way to select directories using selection, may not be to your exact liking.

The feature you ask is in direct contradiction with how the vim plugin works today and will not be supported.

**Comment by jarun** [comment]
@skywind3000 file picker mode is available in `nnn` now.

**Comment by skywind3000** [comment]
amazing，any doc for that ？

**Comment by jarun** [comment]
It's here: https://github.com/jarun/nnn/wiki/Basic-use-cases#file-picker
