### ISSUE TITLE
NNN_COPIER

### ISSUE THREAD

**Issue by ZakharEl** [jarun/nnn#184]

**Comment by ZakharEl** [comment]
The exported NNN_COPIER no longer executes.

**Comment by jarun** [comment]
We use a fixed file now (one configuration less). Please refer to: https://github.com/jarun/nnn#selection

**Comment by pat-s** [comment]
On macOS, I've set `NNN_COPIER` pointing to the "copier" script but without success.
Manually executing the script works.
Script is executable.

Any idea what I might be missing?

**Comment by jarun** [comment]
I don't have a Mac. We'll have to  wait for someone who can reproduce. Did you give the absolute path?

**Comment by jarun** [comment]
@pat-s is this resolved?

**Comment by pat-s** [comment]
Oh yes! Just realized the `-x` option. Love it. Just hitting space and its in the clipboard.

**Comment by jarun** [comment]
Awesome! Glad to know you like it!
