### ISSUE TITLE
tabs content colorization is not working (zsh+tmux)

### ISSUE THREAD

**Issue by Kerosin3** [jarun/nnn#1847]
- [x] Operating System: Debuan 12
- [x] Desktop Environment: Gnome
- [x] Terminal Emulator: kitty - screen-256color + tmux
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Hello!
I have not a very big bug, but rather annoying malfunctioning of nnn with tmux, I suppose.
It seems like NNN_COLORS is working, but only for tabs serial numbers:
 `export NNN_COLORS='2143`
 initial nnn call shows:
 
![image](https://github.com/jarun/nnn/assets/39679124/92ae26de-4e52-441e-b323-673040244373)

when I press 2,3,4.. etc is see tabs color is changing:
![image](https://github.com/jarun/nnn/assets/39679124/a710201e-57a1-4aaa-99be-f42e49ee2bf7)
![image](https://github.com/jarun/nnn/assets/39679124/b3d2e610-66ee-4b2c-95b0-d15fa524bde2)
![image](https://github.com/jarun/nnn/assets/39679124/83c178d0-deab-4a52-b605-3564ee03f58b)

Here is see that:
1. Tab's number colors are change their colors only when I change tab.
2. Tab's content colors is not changing.

The most important for me is that is **I can't differentiate tabs by their content color, so I have to look 
on to tab number every time, that is annoying**.

I tried to google and tweaking some settings in zsh and tmux env, with no result.
Can you suggest me what I could do in order to fix  this absence of tab colorization content ?

**Comment by N-R-K** [comment]
I think what you're looking for is the `-C` flag. It will make the directory color follow the context color. But keep in mind this will also disable 256colors and icons.

**Comment by Kerosin3** [comment]
> I think what you're looking for is the `-C` flag. It will make the directory color follow the context color. But keep in mind this will also disable 256colors and icons.

Oh, yeah, that works. 
Any thoughts about more colors and working icons? Where the problem may resides?

**Comment by jarun** [comment]
No plans for adding new colors and icons.
