### ISSUE TITLE
preview-tui does not work with tmux 3.4

### ISSUE THREAD

**Issue by ListeriaM** [jarun/nnn#1848]
#### Environment details

- [x] Operating System: Arch Linux
- [ ] Desktop Environment:
- [x] Terminal Emulator: st + tmux 3.4
- [ ] Shell:
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: `-Pp`
- [ ] Configuration options set:
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

```sh
NNN_PLUG='p:-preview-tui' tmux new-session nnn -Pp
```
you should get a "size missing" error from tmux.

#### The problem

The `-p` option to split-window was [deprecated in tmux version 3.1](https://github.com/tmux/tmux/blob/master/CHANGES#L776) in favor of `-l ...%` (maybe irrelevant).
It was [broken in 3.4](https://github.com/tmux/tmux/issues/3836#issuecomment-1941577645), which I suspect is a bug since [they're changing it for 3.5](https://github.com/tmux/tmux/commit/bd29a48b56ae649d425fd6939d60f75d79d767da).

**Comment by luukvbaal** [comment]
https://github.com/jarun/nnn/issues/1812#issuecomment-1950853068
