### ISSUE TITLE
will crash when filter with chinese

### ISSUE THREAD

**Issue by shuizhongyueming** [jarun/nnn#185]
## Environment

My system is: macOS Mojave 10.14.2
nnn version: 2.2
Input Software: `简体双拼` in macOS (for input Chinese)

## Action

1. enter `/` to start filter some file

2. switch to `简体双拼` and type `前端` as a filter string. At this time, this string is not in the nnn's input, but in the Input Software. Then click `Enter` or `Space` keyboard to insert it to the nnn' input

<img width="503" alt="default" src="https://user-images.githubusercontent.com/2059860/50679300-dd198f00-103d-11e9-94da-aa8e7b4be8fb.png">

3. nnn crashed with: `/[1]    72798 segmentation fault  nnn`

<img width="568" alt="default" src="https://user-images.githubusercontent.com/2059860/50679347-04705c00-103e-11e9-960c-70b09da64e6f.png">

## Conclusion

I have also try copy/paste some Chinese word to the filter, the nnn also crashed like above

So, maybe it's not the problem of the Input Software, but the filter can't support the search of the CJK words

This software is really useful, and hope for some help

**Comment by jarun** [comment]
I will see if I can reproduce this using copy-paste.

**Comment by jarun** [comment]
Should be fixed now. Please test with latest master and confirm.

**Comment by shuizhongyueming** [comment]
thank you

**Comment by jarun** [comment]
Thanks for reporting the issue!
