### ISSUE TITLE
Files created with `n`, `f` have incorrect permissions

### ISSUE THREAD

**Issue by cor** [jarun/nnn#1853]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: NixOS
- [x] Desktop Environment: none
- [x] Terminal Emulator: Ghostty
- [x] Shell: Zsh
- [x] Custom desktop opener (if applicable): none
- [x] Program options used: none
- [x] Configuration options set: `NNN_TRASH = "1";`
- [ ] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Creating a file with `touch` yields the following permissions:
```
48/57 2024-03-19 14:55 -rw-r--r-- 0B .txt
```

Crating a file by opening `nnn`, pressing `n`, `f`, yields the following permissions:
```
46/57 2024-03-19 14:56 -rw------- 0B .txt
```

**Comment by N-R-K** [comment]
This is intentional, I think: https://github.com/jarun/nnn/issues/1654

**Comment by cor** [comment]
> This is intentional, I think: #1654

If it is, then how do I configure which umask `nnn` uses when creating files? Can't find an option to configure that in the docs.

**Comment by jarun** [comment]
Please use your local patch. We can't go back on this one.

**Comment by cor** [comment]
> Please use your local patch.

What do you mean by this?

**Comment by KlzXS** [comment]
@cor he means keep maintaining it as a local patch for yourself. We won't be implementing this.
