### ISSUE TITLE
preview-tui with wezterm: No FIFO available! ($NNN_FIFO='') 

### ISSUE THREAD

**Issue by qrockz** [jarun/nnn#1859]
- [x] Operating System: Ubuntu 23.10
- [x] Desktop Environment: i3
- [x] Terminal Emulator: wezterm 20240203-110809-5046fc22 
- [x] Shell: GNU bash, version 5.2.15
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [x] Plugins are installed

.bshrc
```
export NNN_PLUG='i:imgview;o:preview-tui;p:preview-tabbed'
export NNN_FIFO="/tmp/nnn.fifo"
```
in preview-tui I've changed
```
 wezterm cli split-pane --cwd "$PWD" $split --percent "$NNN_SPLITSIZE" "$0" "$1" >/dev/null
 wezterm cli activate-pane-direction Prev ;;
```
to 
```
flatpak run org.wezfurlong.wezterm cli split-pane --cwd "$PWD" $split --percent "$NNN_SPLITSIZE" "$0" "$1" >/dev/null
flatpak run org.wezfurlong.wezterm cli activate-pane-direction Prev ;;

```
because im running wezterm with flatpak.

Invoking preview-tui in nnn results in an Error
![wez](https://github.com/jarun/nnn/assets/56853194/5b0aed1d-2265-404a-aa4e-134f04c6cea4)

Even when starting nnn with -a option. (NNN_FIFO is set in .bashrc as you can see above)

Running preview-tui with kitty works on my system but unfortunately not with wezterm.

**Comment by luukvbaal** [comment]
Environment issue likely caused by flatpak then. Not familiar with flatpak but I suppose it has some way to pass along env...

**Comment by qrockz** [comment]
@luukvbaal running wezterm as **AppImage** works :confused:
