### ISSUE TITLE
Sorting bug, different behavior for t and ^T

### ISSUE THREAD

**Issue by lifeformg** [jarun/nnn#1870]
When t+t is pressed, files are sorted by time, and the status shows "M".
When t+T is pressed, files are sorted in reverse order by file name, and the status shows "R".
When ^T+t is pressed, files are sorted by time, and the status shows "M".
When ^T+T is pressed, files are sorted in reverse order by time, and the status displays "MR".
The wiki shows that t and ^T should have the same behavior, but it seems that only the behavior of ^T is correct (if I want to sort in reverse order by time).

**Comment by N-R-K** [comment]
> The wiki shows that t and ^T should have the same behavior

They do have the same behavior on my end. Please provide the information the issue report template asks for, including the `nnn` version you're using.

**Comment by jarun** [comment]
> When t+T is pressed, files are sorted in reverse order by file name, and the status shows "R".

I my case `t+T` shows "MR", as expected. Don't see any issues here.

Please provide the steps to reproduce the issue and I will reopen the issue.

Make sure the directory doesn't have a predefined sort order.
