### ISSUE TITLE
The first letter of the file is not correct after change dir

### ISSUE THREAD

**Issue by XhstormR** [jarun/nnn#1878]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: MacOS
- [x] Desktop Environment: Darwin 23.4.0 x86_64 i386
- [x] Terminal Emulator: alacritty
- [x] Shell: fishshell, version 3.7.1
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: `-adexoiUH -Te -Pp`
- [ ] Configuration options set:
- [x] Plugins are installed: `export NNN_PLUG='p:preview-tui;o:fzopen;c:fzcd;z:autojump;x:!chmod +x $nnn*;'`
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

nnn 4.9 installed from brew. When I cd to another folder, the first letter of the file name is not correct. The first letter of the file displays the first letter of the previous file in the same position. When I move the cursor to this file, the file name becomes correct. You can watch the video for details, this can be reproduced stably.

https://github.com/jarun/nnn/assets/10527522/253469e3-11a8-4dfe-8d9a-534c3ac20e25

**Comment by jarun** [comment]
Could be a icons related issue. See #1802.

**Comment by jarun** [comment]
Closing since there is no response in a month. Appears to be an environmental issue.
