### ISSUE TITLE
nnn crashes on remote server when home folder only contains hidden files/folders

### ISSUE THREAD

**Issue by romanw** [jarun/nnn#188]
Environment
====

Server runs Archlinux
Client runs Archlinux
**nnn** version: 2.2
openssh version: 7.9p1

Steps
====

The following steps can be used to reproduce the issue...

1. Install **nnn** on the server
1. Create a user on the server and make sure its home folder only contains hidden (dot) files/folders.
1. On the client, open a terminal and ssh into the created user account on the server
1. In the ssh session type `nnn`:leftwards_arrow_with_hook: to launch **nnn** on the server
   1. **nnn** should display header and footer and no content
   1. footer should state `0 items`
1. On the client, open a second terminal and ssh into the created user account on the server
1. At this point, **nnn** seg faults in the first terminal.

Workarounds
====

So far I've found the following workarounds to get around the issue...

1. Create a non-hidden file/folder in the home folder
1. After launching **nnn**, go up a folder, then return to the home folder

However, it would be nice if this issue could be fixed.

**Comment by jarun** [comment]
Good find! I'll check this.

**Comment by jarun** [comment]
Would it be possible for you to share debug logs?

To compile `nnn` with debugging enabled, run: `make debug`.

**Comment by jarun** [comment]
in fact, it would be great if you can start the debug `nnn` in gdb:

```
gdb -q ./nnn
(gdb) run
```

When it crashes: `bt full` and share the backtrace.

**Comment by jarun** [comment]
I tried to reproduce this but couldn't. The above details would help.

**Comment by jarun** [comment]
Splendid! Please test with latest master and confirm if it works. :+1:

**Comment by romanw** [comment]
Tested with latest master and can no longer reproduce my issue.  Thanks!

**Comment by jarun** [comment]
Thanks for confirming!
