### ISSUE TITLE
[bash] nnn can't return after executing command (] key) if invoked from a `bind -x` keybinding.

### ISSUE THREAD

**Issue by magpie514** [jarun/nnn#1884]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Ubuntu 23.10 (amd64)
- [x] Desktop Environment: Plasma 5
- [x] Terminal Emulator: Konsole 23.08.3
- [x] Shell: bash 5.2.15
- [x] Custom desktop opener (if applicable): N/A
- [x] Program options used: none
- [x] Configuration options set:
```bash
export NNN_COLORS='1324'
export NNN_FCOLORS='0000030A0000060805000009'
```
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. ` bind -x ' "\eo":"nnn" ' ` (for example)
2. Press alt+o to run nnn
3. Press `]` to open the command prompt
4. Run a command such as `git pull`
5. After command is finished, it'll get stuck and unable to return.
6. Process has to be killed by external means (kill, pkill, GUI task managers, closing the tab, etc)

#### Additional notes
I have nnn compiled with this script:
```bash
cd ~/Repositories/nnn
git fetch origin && git reset --hard origin/master && git clean -ffdx
make O_STATIC=1 O_NORL=1 O_EMOJI=1 strip
sudo cp ./nnn /usr/local/bin/nnn
```
- GCC version: gcc (Ubuntu 13.2.0-4ubuntu3) 13.2.0
- No additional patches or modifications to nnn's source.
- It does work with `bind '"\eo":"nnn\n"'` but this requires the prompt to be fully cleared and is added to history.

**Comment by N-R-K** [comment]
> After command is finished, it'll get stuck and unable to return.

Ctrl+c worked for me.

**Comment by magpie514** [comment]
Tried ctrl+c as one of the first things, it doesn't work for me. Neither does ctrl+z or other control keys.

**Comment by N-R-K** [comment]
This seems to be a issue with `bash bind`: https://stackoverflow.com/questions/16928761/why-will-a-script-not-accept-input-on-stdin-when-invoked-from-bashs-bind

Not sure if there's anything to be done on nnn's side.

**Comment by magpie514** [comment]
Good find. Yeah seems it's not nnn's fault, better close this one.
Thanks for your assistance!
