### ISSUE TITLE
Numeric sort

### ISSUE THREAD

**Issue by asadsalman** [jarun/nnn#190]
I see the numeric sort feature listed but can't figure out how to trigger it. Any help would be great!
Great tool! Absolute time saver!

**Comment by jarun** [comment]
It's enable by default. Navigate to `/proc`.

**Comment by asadsalman** [comment]
Works in `/proc`, nowhere else:
![screenshot from 2019-01-14 04-42-32](https://user-images.githubusercontent.com/8086397/51105609-7885cf00-17b7-11e9-8cc8-500fc4c5a938.png)
![screenshot from 2019-01-14 04-42-47](https://user-images.githubusercontent.com/8086397/51105610-7885cf00-17b7-11e9-90e9-5e5a000f143e.png)

**Comment by asadsalman** [comment]
`proc` sorted perfectly though:
![screenshot from 2019-01-14 04-48-16](https://user-images.githubusercontent.com/8086397/51105696-b71b8980-17b7-11e9-908e-3ac917683790.png)

**Comment by jarun** [comment]
It's because `_18` is not numeric because of the `_`.

**Comment by jarun** [comment]
So for non-numeric cases the general alphabetic comparison is used.

**Comment by asadsalman** [comment]
Oh, I figured it'd be consistent with `ls -1v`

**Comment by jarun** [comment]
It's not. Also:

```
$ /bin/ls -1v
0
00
0aa
01
1
02
10
11
101
111
111a
123
1111
A
Abc
B
Def
Test
a
aaa
abc
b
def
test
' 111'
' Abc'
' abc'
'  abc'
'(abc'
'( abc'
+
+1
+B
+b
++
++1
++b
-
-0
-00
-1
-2
-B
-a
-aa
-b
-bb
--
--1
--b
'[abc'
'{ abc'
```

**Comment by jarun** [comment]
Another note:

1. on Linux, the natural/version sort uses `strverscmp`: http://man7.org/linux/man-pages/man3/strverscmp.3.html

However, as you'll see this is under `_GNU_SOURCE` (GNU-specific).

OS X doesn't even have that option in `ls`: https://ss64.com/osx/ls.html

With `nnn`, we try to adhere to POSIX as far as possible. So the current algorithm is kind of a middle ground.

BTW, I have updated the algorithm last night and now it doesn't call `strcoll` and uses basic logic & maths to do the comparison without involving major computation.

**Comment by jarun** [comment]
Note 2: It also places capitals on top.

**Comment by jarun** [comment]
@asadsalman on public demand, version sort is now supported. :+1:

**Comment by asadsalman** [comment]
Woot 🙌
