### ISSUE TITLE
how to remove cp/mv confirmation prompt while copying/moving files/folders

### ISSUE THREAD

**Issue by kingsmanvn1x32** [jarun/nnn#1916]
Similar to issue  #1140 but for cp/mv.
I think having a prompt for that action session is okay as done with `rm`.
I haven't found answer in the docs - sorry if it's there and I missed it.

**Comment by KlzXS** [comment]
If I understood you question correctly you want to skip the interactive prompt for cp/mv just as you can skip it for rm.

Currently there is no builtin option for that. There is no option to overwrite all.

**Comment by amitzionii** [comment]
I don't know how recommended it is. If you are really eager, the following patch will cause `cp` and `mv` to not prompt for confirmation in case of overwriting.
https://github.com/jarun/nnn/compare/master...amitzionii:nnn:patch-1

**Comment by jarun** [comment]
Sorry no option is available and no plans to do so. It's a trivial change to do so. Please patch the code locally.
