### ISSUE TITLE
Scripts, completions, and `make install`

### ISSUE THREAD

**Issue by sjmulder** [jarun/nnn#192]
I'd think `make install` should install the shell completions, nlay, and maybe natool. What's your opinion of this? Would you accept a PR to make it so?

**Comment by jarun** [comment]
`nlay` is not a required component anymore. The install location of shell completion depends on the shell and varies from distro to distro. We prefer to keep the installation silent too.

Also, `nnn` has very few options. Perhaps I would depreciate the completion scripts some fine day.

**Comment by sjmulder** [comment]
Fair enough, and with that in mind I'll refrain from adding them to the pkgsrc package too.

**Comment by jarun** [comment]
Yes, please don't. Someone might not have fish, someone might want fish and zsh but has bash. You'll have to be interactive... that kills the fun in automation. ;)
