### ISSUE TITLE
preview-tui: `create pane failed: -l invalid`

### ISSUE THREAD

**Issue by Haawron** [jarun/nnn#1925]
I got this unprecedented error message when enabling `perview-tui` plugin on zsh+tmux environment.

```
create pane failed: -l invalid
```
Interestingly, this issue can be completely resolved by removing a single `%` character from [this line](https://github.com/jarun/nnn/blob/14fef0323dffefac8d6358f5991fdb63a4355915/plugins/preview-tui#L185).

However, I'm not sure if this behavior is due to the way I'm using nnn.

I'm sharing this in case anyone else runs into the same problem and needs a quick fix.

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Ubuntu 20.04 LTS
- [x] Desktop Environment: On a remote server
- [x] Terminal Emulator: tmux
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable): nuke
- [x] Program options used: `-acdeU`
- [x] Configuration options set: Specified below
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

Configuration options 
```shell
export NNN_PLUG='j:autojump;p:preview-tui;t:preview-tabbed;i:imgview;v:vidthumb;o:fzopen'
export NNN_OPENER="$HOME/.config/nnn/plugins/nuke"
export NNN_FIFO="/tmp/nnn.fifo"
```

**Comment by jarun** [comment]
@luukvbaal or @N-R-K can you please have a look?

**Comment by N-R-K** [comment]
I can't reproduce it. What's your tmux, zsh and nnn/preview-tui version?

**Comment by N-R-K** [comment]
Also, you should not set the `-a` option and `$NNN_FIFO` both. They are mutually exclusive.

**Comment by jarun** [comment]
Closing this since there is no response.
