### ISSUE TITLE
Detail view sometimes highlights all files (not just last 5 min)

### ISSUE THREAD

**Issue by martinus** [jarun/nnn#1927]
I'm using currently latest master 14fef032. When using nnn with detail view, as far as I understand it should only highlight the files that are < 5 minutes old. But sometimes (not always) it highlights all files:

![image](https://github.com/user-attachments/assets/8ef76dd7-0a05-467d-bd87-08b8bdb40bb3)

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Fedora Linux 40, kernel  6.10.7-200.fc40.x86_64
- [x] Desktop Environment: KDE
- [x] Terminal Emulator: foot
- [x] Shell: fish
- [x] Custom desktop opener (if applicable):
- [x] Program options used: `VISUAL=nvim nnn -ed`
- [x] Configuration options set: none
- [x] Plugins are installed: yes, not used
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. start `VISUAL=nvim nnn -ed`
2. go to directory

**Comment by N-R-K** [comment]
> as I understand it should only highlight the files that are < 5 minutes old.

It applies to files that were created *or modified* within the last 5 mins. Are you sure those files haven't been modified (i.e have their `mtime` updated) recently?

**Comment by martinus** [comment]
I'm pretty sure they were not modified, when I run `ls -l --time=mtime` (which should be the default anyways) it shows the same times. I believe it might have something to do with the modification time of the parent directory, when that was modified recently I get this behavior that everything inside looks recently modified even when it isn't

**Comment by jarun** [comment]
> I believe it might have something to do with the modification time of the parent directory

I tried renaming a parent dir and checked the files within. Didn't see the issue.

**Comment by martinus** [comment]
I cant properly reproduce it unfortunately, most of the time it's working correctly. I couldn't narrow it down yet to when this really happens

**Comment by jarun** [comment]
Closing for now. Please reopen if you find a sure way of reproducing the issue.
