### ISSUE TITLE
change DIR for .nnn dot files

### ISSUE THREAD

**Issue by wltprgm** [jarun/nnn#193]
https://github.com/jarun/nnn#selection

Anyway to change the DIR for temporary .nnn dot files? I can't find any environment variables for it

prefer it to be in /tmp

**Comment by jarun** [comment]
Sorry, no customization allowed for this.

**Comment by wltprgm** [comment]
May I know why? Is it difficult to implement or it slows down the program?

Since it defaults to $HOME, $TMPDIR or /tmp, why it's in this order by the way?

It looks like your decision is somehow similar to File-roller

https://bugs.launchpad.net/ubuntu/+source/file-roller/+bug/245716

No offense.

**Comment by jarun** [comment]
It's better to use user-local directories to avoid race conditions on multi-user systems. In fact, the original location was /tmp and it was changed to the current order due to an issue report somewhere.

**Comment by jarun** [comment]
Same thing, right?

**Comment by jarun** [comment]
We don't use DIR in the program. It's just used as an example.

**Comment by jarun** [comment]
In the current implementation, I am using just 564 bytes to store this. As soon as I expose it, I will have to use 4KB. I'll skip this.
