### ISSUE TITLE
Suckless terminal in ewrap

### ISSUE THREAD

**Issue by kovmir** [jarun/nnn#1934]
My `ewrap`:

```bash
#!/usr/bin/env sh

if [ -n "$TMUX" ] ; then
    tmux split-window -h "$EDITOR \"$*\""
else
    st "nvim \"$*\""
fi
```

If I open `nnn` in `st` without `tmux` and try to open a plain-text file, I get `child exited with status 1`. It works if I use `xterm -e` in place of `st` in `ewrap`. Why does it not work with `st`?

**Comment by N-R-K** [comment]
The arguments must be separate for `st`. The following works for me:

```sh
st -e vim "$@"
```

**Comment by kovmir** [comment]
Ah, it should be `"$EDITOR" "$@"` not `"$EDITOR $@"`. The editor and the arguments must not be a single string.
