### ISSUE TITLE
prompt not able to export variale

### ISSUE THREAD

**Issue by Giessen** [jarun/nnn#1944]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: WSL2
- [ ] Desktop Environment:
- [x] Terminal Emulator: Windows Terminal
- [x] Shell: ZSH
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set: 
- [x] Plugins are installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. nnn
2. press ] to fire prompt
3. type this: export a=0, press ENTER
4. type this: echo $a, press ENTER
Current Result: nothing happens.

Any ideas, Thanks.

**Comment by N-R-K** [comment]
This is expected. Each command is run in a separate shell invocation. And so no state is retained between commands. Use <kbd>!</kbd> if you need a proper shell session.
