### ISSUE TITLE
find doesn't exit early in fzopen if NNN_FIFO exists

### ISSUE THREAD

**Issue by babbaj** [jarun/nnn#1947]
When nnn is run with the fifo enabled and I try to use fzopen in a directory with a large number of children, fzopen will hang for a while until `find` finishes listing every file. If I run the same command that fzopen runs in a normal shell the whole command stops as soon as I press enter. This problem doesn't seem to be specific to `find` or `fzf` and the same problem seems to happen if anything that takes a while to pipe a bunch of data is piped into a command that quickly exits (even tested with `true`).

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: NixOS unstable (24.11.20241102)
- [x] Desktop Environment: KDE
- [x] Terminal Emulator: Kitty
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used: none
- [x] Configuration options set: NNN_FIFO=/tmp/nnn.fifo
- [x] Plugins are installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
- run nnn with NNN_FIFO set or with -a
- go to `/`
- run fzopen
- immediately press enter

**Comment by jarun** [comment]
This appears to be the expected behaviour. The input is deferred till the tools involved in the pipe complete.
No plans to change this.

**Comment by babbaj** [comment]
You're right that nnn is supposed to wait until the script complete but for some reason the shell that nnn creates isn't behaving correctly. If I run the exact same command that fzopen runs in a normal shell it returns instantly but when run inside the shell that nnn creates there's a big delay. I'm not sure what's going on but I'm certain that the shell nnn is running is behaving differently than my normal interactive shell.

**Comment by babbaj** [comment]
I figured out that if I make fzopen run `trap` it prints `trap -- '' PIPE` meaning that something is telling the script to ignore `SIGPIPE`. Interestingly if I change the shebang to use zsh `trap` prints nothing and `find` respects `SIGPIPE`  and behaves as it should.

**Comment by babbaj** [comment]
I think that is most likely coming from here https://github.com/jarun/nnn/blob/877d7c06876287930e03e232dd0b0167cadd9abd/src/nnn.c#L9013
