### ISSUE TITLE
home/fine key on rename file

### ISSUE THREAD

**Issue by drazde** [jarun/nnn#195]
When rename a file, use home key to go to the first char and fine to go to the last one

**Comment by jarun** [comment]
Please use `^A` and `^E` for first and last. No plans to support any other keys in this scenario.

**Comment by drazde** [comment]
> Please use `^A` and `^E` for first and last. No plans to support any other keys in this scenario.

Ok, I didn't know that keys

**Comment by jarun** [comment]
They are documented in the how to wiki page.
