### ISSUE TITLE
session restore (s r) crash

### ISSUE THREAD

**Issue by doremiyeon** [jarun/nnn#1968]
https://github.com/jarun/nnn/blob/5e5a17f9548f3267b94263c6ac6466456d6c3d06/src/nnn.c#L4546

when attempting to restore a session by hitting 's r', _sname_ is **NULL** here. should probably check for that and write @\0 to _curssn_.

**Comment by jarun** [comment]
Raise a PR please.

**Comment by doremiyeon** [comment]
#1969 here you go, sorry.
