### ISSUE TITLE
[bug] Negative values in disk usage mode

### ISSUE THREAD

**Issue by zaza42** [jarun/nnn#20]
> Aug 18 13:24 2015 -1996095/ iphone/
   Apr 01 21:11 2017  522.66M/ music/
   Jul 03 18:08 2012 -1666539/ movies/
   Feb 14 12:10 2017 -1369174/ scene/
   Jun 29 14:56 2016   1.944G/ Project/
   Apr 16 10:51 2017   1.618G/ video/

**Comment by shaggytwodope** [comment]
It would most likely help if you share what the folder sizes should be. So a relation to the values can be found. And very useful to know the version you are currently using.

**Comment by jarun** [comment]
Yep, we need more details. I'm guessing it's a overflow. Also, what's the OS?  32/64-bit?

**Comment by jarun** [comment]
Are iphone/, movies/ and scene/ mounted on the same disk?

**Comment by jarun** [comment]
Can you please test https://github.com/jarun/nnn/commit/b730c116d6eca260ae9138b1d9613eb9f336c46b and let us know if it works?

**Comment by jarun** [comment]
Closing the issue as we can't do anything further without more information. If you have any more details, please leave a note.

**Comment by jarun** [comment]
This was reported a long time ago but this may be related to #42 which is fixed now.

**Comment by zaza42** [comment]
Ok, it seems to be ok now. Thx!
