### ISSUE TITLE
Can't use "run a command" 

### ISSUE THREAD

**Issue by juacq97** [jarun/nnn#200]
If I press Control + Shift + S, or Control + S to enter a command the program freezes, stops responding completely and I have to close the terminal. I use alacritty, but I tried with termite and it happened the same.

**Comment by jarun** [comment]
> I have downloaded throught my package manager

Please try the master branch.

**Comment by juacq97** [comment]
I uninstalled the version of the manjaro repos, I cloned master and compiled nnn but I still can not execute commands.

**Comment by jarun** [comment]
OK, I guess I'll have to try it on Manjaro.

What is the output of `echo $SHELL` for you?

**Comment by jarun** [comment]
This should be fixed now. Note that <kbd>^P</kbd> is the new key to show the command prompt.

On Manjaro, pressing `^S` issues an unhandled signal. Instead of overriding it, I used an available keybind.

Thanks for the issue report.

**Comment by jarun** [comment]
@juacq97 you can now use `^S` in `nnn`. See the troubleshooting guide here: https://github.com/jarun/nnn/wiki/Troubleshooting#broken-control-keybind
