### ISSUE TITLE
How do I select files one by one for copying/moving

### ISSUE THREAD

**Issue by enanajmain** [jarun/nnn#201]
I know about `⎵ , ^K` to copy entry path of the currently selected file, and `^Y` for toggling selection. But is there a way I can add to already selected files? For example, I want to copy 2 files, one at the top of the list, the other at the bottom. How would I select these files together for copying?

**Comment by jarun** [comment]
You can't. The order is decided by the order of copying.

**Comment by jarun** [comment]
Now I think I don't understand the question. Let's say you want to copy 2 files - `CHANGELOG` and `LICENSE`, in the same order. Here are 2 workflows:

1. Continuous files:

- Press <kbd>^Y<kbd> on file `CHANGELOG`
- Press <kbd>^Y<kbd> on file `LICENSE`

They are copied in the same order:

```
$ ls -l (ncp)
-rw-rw-r-- 1 vaio vaio 10959 Jan 29 00:33 /home/vaio/GitHub/nnn/CHANGELOG
-rw-rw-r-- 1 vaio vaio  1472 Jan 29 00:33 /home/vaio/GitHub/nnn/LICENSE
```

2. The files are not continuous. So you have to cherry-pick:

- Press <kbd>^Y<kbd> on file `CHANGELOG`
- Press <kbd>^K<kbd> on file `CHANGELOG`
- Press <kbd>^K<kbd> on file `LICENSE`
- Press <kbd>^Y<kbd> on file `LICENSE`

They are copied in the same order:

```
$ ls -l (ncp)
-rw-rw-r-- 1 vaio vaio 10959 Jan 29 00:33 /home/vaio/GitHub/nnn/CHANGELOG
-rw-rw-r-- 1 vaio vaio  1472 Jan 29 00:33 /home/vaio/GitHub/nnn/LICENSE
```

**Comment by kxzaon** [comment]
What I want (and enanajmain too... I think), it's select several files that aren't the following or the previous.

> -rw-r--r--    1 kxzaon   kxzaon        1449 Jan 24 20:35 firefox-bin.sig
-rw-r--r--    1 kxzaon   kxzaon        1449 Jan 24 20:35 firefox.sig
drwxr-sr-x    2 kxzaon   kxzaon        4096 Jan 29 21:21 fonts
**drwxr-sr-x    3 kxzaon   kxzaon        4096 Jan 29 21:21 gmp-clearkey**
**drwxr-sr-x    2 kxzaon   kxzaon        4096 Jan 29 21:21 gtk2**
drwxr-sr-x    2 kxzaon   kxzaon        4096 Jan 29 21:21 icons
-rw-r--r--    1 kxzaon   kxzaon         899 Jan 24 20:27 libfreeblpriv3.chk
-rwxr-xr-x    1 kxzaon   kxzaon      748248 Jan 24 20:27 libfreeblpriv3.so
**-rwxr-xr-x    1 kxzaon   kxzaon       43480 Jan 24 20:27 liblgpllibs.so**
**-rwxr-xr-x    1 kxzaon   kxzaon     2220664 Jan 24 20:27 libmozavcodec.so**
**-rwxr-xr-x    1 kxzaon   kxzaon      220280 Jan 24 20:27 libmozavutil.so**
**-rwxr-xr-x    1 kxzaon   kxzaon       14488 Jan 24 20:27 libmozgtk.so**
-rwxr-xr-x    1 kxzaon   kxzaon      105560 Jan 24 20:27 libmozsandbox.so
-rwxr-xr-x    1 kxzaon   kxzaon     1571816 Jan 24 20:27 libmozsqlite3.so
-rwxr-xr-x    1 kxzaon   kxzaon       18504 Jan 24 20:27 libmozwayland.so
-rwxr-xr-x    1 kxzaon   kxzaon      256176 Jan 24 20:27 libnspr4.so
-rwxr-xr-x    1 kxzaon   kxzaon      739520 Jan 24 20:27 libnss3.so
-rwxr-xr-x    1 kxzaon   kxzaon      466592 Jan 24 20:27 libnssckbi.so
-rw-r--r--    1 kxzaon   kxzaon         899 Jan 24 20:27 libnssdbm3.chk
-rwxr-xr-x    1 kxzaon   kxzaon      154936 Jan 24 20:27 libnssdbm3.so
-rwxr-xr-x    1 kxzaon   kxzaon      200040 Jan 24 20:27 libnssutil3.so
-rwxr-xr-x    1 kxzaon   kxzaon       23000 Jan 24 20:27 libplc4.so
-rwxr-xr-x    1 kxzaon   kxzaon       18816 Jan 24 20:27 libplds4.so
**-rwxr-xr-x    1 kxzaon   kxzaon      172224 Jan 24 20:27 libsmime3.so**
-rw-r--r--    1 kxzaon   kxzaon         899 Jan 24 20:27 libsoftokn3.chk
-rwxr-xr-x    1 kxzaon   kxzaon      328008 Jan 24 20:27 libsoftokn3.so
-rwxr-xr-x    1 kxzaon   kxzaon      398000 Jan 24 20:27 libssl3.so
**-rwxr-xr-x    1 kxzaon   kxzaon   119516824 Jan 24 20:27 libxul.so
-rw-r--r--    1 kxzaon   kxzaon        1449 Jan 24 20:35 libxul.so.sig
-rwxr-xr-x    1 kxzaon   kxzaon      830496 Jan 24 20:27 minidump-analyzer
-rw-r--r--    1 kxzaon   kxzaon    17322711 Jan 24 20:27 omni.ja**

I want to move the files in bold in once to a subdir. I don't care about the order of the selected files. Are we agree that it's not possible at the moment ?

**Comment by jarun** [comment]
This is doable from the beginning:

- Press <kbd>^Y</kbd> to enter selection mode
- Cherry pick the files by pressing <kbd>Space</kbd> or <kbd>^K</kbd> on each
- Press <kbd>^Y</kbd> to exit selection mode

Your files are now copied. This is documented. Read the documentation here: https://github.com/jarun/nnn#selection

**Comment by enanajmain** [comment]
@jarun,
Well, my question was off base, sorry. But what if I want to select a whole bunch of continuous files and add one file that is not continuous to that list?

For example
```
File1
File2
File3
File4
File5
```

What do I do if I want to select File1, 2,3 and File5?

**Comment by jarun** [comment]
You have to cherry pick one by one. There's no other way.

**Comment by laggardkernel** [comment]
@jarun `^Y` suspends `nnn` process on my side. I've tried terminals like iTerm, Terminal, kitty. Shells like BASH, ZSH are also tested. I can't use `^Y` to toggle selection mode.

**Comment by jarun** [comment]
You are probably seeing this: https://github.com/jarun/nnn#bsd-terminal-issue

On master you have <kbd>K</kbd> as additional selection toggle key.

**Comment by laggardkernel** [comment]
@jarun Thanks for your help. I didn't read the `README.md` throughly. Sorry to have bothered you. 😳

**Comment by jarun** [comment]
No problem!

**Comment by jarun** [comment]
@3N4N @kxzaon @laggardkernel selecting continuous and non-continuous files together will be implemented in the next release.
