### ISSUE TITLE
debian dependencies

### ISSUE THREAD

**Issue by Boruch-Baum** [jarun/nnn#205]
I submitted a bug report against debian for the way they are packaging this repository. If you have an opinion that you want to share there, the url is 

    https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921480

You can add to that thread by sending email to:

    921480@bugs.debian.org

**Comment by jarun** [comment]
Adding @szlin who maintains the package on Debian.

**Comment by jarun** [comment]
The packages are not libs, so they are optional. `nnn` can work without them as well.

In my opinion _recommends_ would be a good section for the optional deps.

**Comment by szlin** [comment]
Hi @jarun 

I'm on Chinese New Year holidays until next Monday, so I will add these optional packages next week.

> In my opinion _recommends_ would be a good section for the optional deps.

The APT mechanism in Debian installs recommended packages as default, so I would like to suggest to use _Suggests_ instead.

> Recommends
> Package A recommends Package B, if the package maintainer judges that most users would not want A without also having the functionality provided by B.
> 
> Suggests
> Package A suggests Package B if B contains files that are related to (and usually enhance) the functionality of A.

**Comment by jarun** [comment]
> The APT mechanism in Debian installs recommended packages as default, so I would like to suggest to use Suggests instead.

We are good with _suggests_!

**Comment by jarun** [comment]
Enjoy your holidays @szlin!

**Comment by szlin** [comment]
@jarun Thank you and happy Chinese New Year to you!

Wishing you good health and great fortune in the year of Pig [1]
[1] https://chinesenewyear.net/zodiac/pig/

**Comment by jarun** [comment]
Thanks Lin! :dancer:

**Comment by szlin** [comment]
Hi @jarun , I would like to ask that are there any minimal version requirements in below?

1. mediainfo or exiftool
2. atool or patool
3. vidir (moreutils)
4. vlock
5. file
6. lftp
7. findutils
8. xdg-open (xdg-utils)

**Comment by jarun** [comment]
None that I know of. :+1:

**Comment by szlin** [comment]
@jarun @Boruch-Baum  I've uploaded new version of nnn with suggests field. This issue should be closed now.

**Comment by jarun** [comment]
thank you!
