### ISSUE TITLE
How to select one file? 

### ISSUE THREAD

**Issue by daniel-vera-g** [jarun/nnn#207]
As far as I've understood, you use `Y` oder `^Y` to select files or directories and the `P` to copy or `V` to move.

But How do I copy or move only **one** file or folder? Have I missed something?

**Comment by jarun** [comment]
Just <kbd>^K</kbd> or space bar.

**Comment by daniel-vera-g** [comment]
> Just ^K or space bar.

THX, that was a fast response!

Nevertheless, I think that `^K  Copy entry path` is a little bit abstract description of what it does. Maybe it can be renamed or maybe I'am not as used to that definition :P .

**Comment by jarun** [comment]
You are right! _Select_ entry path should be the correct description.

**Comment by jarun** [comment]
or just _Select entry_. Given selection understands only absolute paths.

**Comment by daniel-vera-g** [comment]
Select entry is understandable! 🔝
