### ISSUE TITLE
Support for Mime/Devicons and fixing some cosmetic behavior.

### ISSUE THREAD

**Issue by ahloiscreamo** [jarun/nnn#208]
Hi,
Recently i switch to use nnn (coming from ranger) and it have been a positive experience.
Nnn is so fast, simple and smooth. I use with few addition scripts and i have to say it was the best term based file manager around.
But there are some area that i wish that i can see developed for nnn
These are not trivial at all, but if someone could provide the support for it ,it would be awesome.

1. Add support for Mime/Devicons .I used to have this [plugin](https://github.com/alexanderjeurissen/ranger_devicons) in ranger, 

![screenshot from 2019-02-11 23-58-22](https://user-images.githubusercontent.com/9318372/52575443-2b9a2480-2e59-11e9-984d-aee4c4c8de4b.png)

while at first i have it for the 'coolness' then i realized that it help a lot to be able to differentiate between different file format in a directory. So happy if this could be implemented.

2.Some cosmetic change on directory list.
By default, nnn show the full title for the file/mime names.
Sometimes when i browse, it become hard to select which file ( i use detail view by default because i don't feel the need to see the date on the file list) especially when the title is long.

![screenshot from 2019-02-12 00-19-41](https://user-images.githubusercontent.com/9318372/52576907-00fd9b00-2e5c-11e9-9e9a-8eef919e709d.png)

The view become kind of messy so i think nnn should put a rule if the filename is long then just put ~ as examples (ranger does this)
Normally a user have more than 1 window running on screen especially us the wm tiling community for sakes, so i think nnn should really implement this as  it will look cleaner, saving few space for px (yes it matter!) and easier to navigate.

So this are something that i would like to see.
But i understand if these are  not on the priority list, thanks for developing a great software.
I use it everyday, i rec it to my friends.Have a nice day

**Comment by jarun** [comment]
Please read the idea behind `nnn` - https://github.com/jarun/nnn/wiki/nnn-design-considerations

`nnn` is maintained lean so it can perform on devices like the Pi or the Termux environment on Android. `nnn` is not meant for fancy stuff, you get only what you need.

Coming to your proposals:

- if you are looking for an icon for mkv, perhaps you should try filtering with the string `mkv` and you will find all mkv files in the directory. That's much faster than rendering lots of icons each time.
- try the light view for more space

`nnn` wraps at column length. I think the issue of multiple lines is with codepoints used in Chinese (?). In the `redraw()` funciton we call `printptr` (`printent_long()`) with number of columns. That in turn calls `unescape()` with the number of columns. I think that's where the calculation is going wrong for CJK.

Can you please send me some empty files with the filenames you are having and I can try to wrap the names so they fit in a single line.

**Comment by ahloiscreamo** [comment]
Hi there,
Thanks for the output.
I read it and i respected the design ideology and its limitation for a reason.

I see ,
the filtering search help a lot on searching the file format and vice versa, it's just it required more action for me (providing me being lazy typist) but i can see that as a solution, or maybe i can make a script myself to make nnn support for the mentioned devicon/mime if i have free time.

Sorry for being unclear, i mean i viewed on light view* but i put the screenshot of default view.
Yes you were right, the Korean Hangul letter actually* take a lot of space.
example filenames-
[KoreanHangul.TXT](https://github.com/jarun/nnn/files/2852539/KoreanHangul.TXT)

you can tell me should you need anything more

**Comment by jarun** [comment]
Thanks for the filenames. I will reproduce the issue and try to fix it.

**Comment by ahloiscreamo** [comment]
Thanks you very much, really appreciate!

**Comment by jarun** [comment]
Yes, I can reproduce it. :+1:

**Comment by jarun** [comment]
This should be fixed on master. Please confirm.

**Comment by ahloiscreamo** [comment]
Wow,
That was crazy fast.
i will compile the master tomorrow, (midnight, about to go to bed)
i use the version from official fedora repo,Had to remove that first.
so i think i need a time to search for dependency and stuff.
I will be back to confirm again, goodnight.

**Comment by jarun** [comment]
Sounds good! :+1:

**Comment by ahloiscreamo** [comment]
Hi
I have compile the master and im thrilled to the issues has been fixed!
everything look cleaner and tidy now,

![screenshot from 2019-02-12 13-53-47](https://user-images.githubusercontent.com/9318372/52614839-f845ad00-2ecd-11e9-8a4e-6d9a6d5a92d6.png)

Thanks for the work!

**Comment by jarun** [comment]
Awesome! Thanks for confirming!

**Comment by ruizone** [comment]
测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试.txt       
 Long file name is displayed incorrectly.

**Comment by jarun** [comment]
Can you please raise a new issue

**Comment by ruizone** [comment]
Ok, already submitted
