### ISSUE TITLE
Config option to make "cd on exit" the default?

### ISSUE THREAD

**Issue by klieret** [jarun/nnn#209]
Hi,

I really love nnn. Just one question: Could there be an option to make nnn always cd on exit? So that ``q`` and ``Q`` would also run cd and not just ``Ctrl+G``?
For me it's confusing to end up in a different directory after leaving nnn, when accidentally quitting via ``q`` (plus ``q`` is just the nicer shortcut and ``Ctrl+G`` feels a bit clumsy to me).

Of course I would also understand if you would like to avoid adding more configuration though :) 

Cheers,
Kilian

**Comment by jarun** [comment]
I'll see what I can do.

**Comment by jarun** [comment]
I checked the possibility. Configuration is not the problem, we can have values 1 and 2. The problem is, to support this I have to add checks in 2 unrelated cases and then align the flow: normal quit, quit context.

We have `^G` for the purpose, let's stick to it. Remember `G for Go`.

**Comment by klieret** [comment]
Too bad, but thanks for considering it :)
