### ISSUE TITLE
[Bug] Invisible Icon Files on Mac Not Displayed

### ISSUE THREAD

**Issue by niklasbogensperger** [jarun/nnn#21]
In folders for which a custom icon is set, the `Icon\r` / `Icon?` / `Icon^M^M` file within is not properly displayed. It is accounted for in the total at the bottom but it looks like a blank entry in the list, both with dotfile display on or off.
![nnn](https://cloud.githubusercontent.com/assets/8931810/25629479/e8ef2b20-2f69-11e7-8d51-843991f568cb.jpg)
Moving the cursor down one entry:
![nnn2](https://cloud.githubusercontent.com/assets/8931810/25629485/ee2d256a-2f69-11e7-9ade-8194af482832.jpg)
The entry is invisible both on Mavericks and on latest Sierra.

**Comment by jarun** [comment]
@niklasbogensperger

- are you using v1.0 or master? If you are not on master please test on master.
- can you please share the following details of the file?
  - ls -l
  - stat
  - file

@zmwangx I can't reproduce this on Ubuntu. Can you try this on OS X?

**Comment by zmwangx** [comment]
<img width="235" alt="screen shot 2017-05-02 at 11 08 20 pm" src="https://cloud.githubusercontent.com/assets/4149852/25647007/43644ec4-2f8c-11e7-9561-190ea582737c.png">

That blank line should be a `$'Icon\r'`. The CR is probably printed unquoted, so the line is overwritten.

**Comment by zmwangx** [comment]
By the way, `$'\n'` is also not escaped.

**Comment by jarun** [comment]
Thanks @zmwangx!

**Comment by jarun** [comment]
Strange! I can see both on Ubuntu!

[![visible](https://s16.postimg.org/plfr6nr4z/image.png)](https://s16.postimg.org/plfr6nr4z/image.png)

**Comment by jarun** [comment]
Or, am I using wrong characters/quotes?

**Comment by jarun** [comment]
Did you test with master or rel 1.0?

**Comment by jarun** [comment]
I can confirm I see both the files using master/v1.0.

**Comment by zmwangx** [comment]
> Or, am I using wrong characters/quotes?

By `$'Icon\r'` I mean `Icon<CR>`, i.e.,

```
echo -n $'Icon\r' | xxd
00000000: 4963 6f6e 0d                             Icon.
```

**Comment by jarun** [comment]
OK. Got it! Thanks!

**Comment by jarun** [comment]
Here's what I see on Ubuntu:

```
~/Documents$ touch abc
~/Documents$ mv abc "h
             c"
~/Documents$ ls
h?c
~/Documents$ n
~/Documents$ touch bn
~/Documents$ mv bn "
             "
~/Documents$ ls
?  h?c
~/Documents$ ll
total 0
-rw-rw-r-- 1 apj apj 0 May  3 11:10 ?
-rw-rw-r-- 1 apj apj 0 May  3 11:09 h?c
```

I think nnn is behaving correctly *though not visually pleasing* ;). The character `\r` is non-printable itself. Do you guys think I should parse the strings and replace the escape chars with `?` when printing?

**Comment by zmwangx** [comment]
I would either use `?` or `\r`/`\n`.

**Comment by zmwangx** [comment]
`\r`/`\n` is more reasonable because `\x1b` is not printed as `?`, but rather, `\x1b`.

**Comment by jarun** [comment]
You mean two characters? Which would also lead to moving the rest of the chars following it...

how about only handling `\r` and `\n` and replacing with `?`?

**Comment by jarun** [comment]
I think I'll have to handle [this](https://en.wikipedia.org/wiki/Escape_sequences_in_C#Table_of_escape_sequences) case by case.

**Comment by zmwangx** [comment]
I didn't read the code but what's the problem with replacing them with two characters? Allocating another buffer? I mean, however non-printable characters are currently escaped, you can do this the same way, no?

**Comment by jarun** [comment]
> Allocating another buffer?

Yes, I would like to avoid that.

**Comment by zmwangx** [comment]
Uh, okay, I made a mistake in my previous test and thought non-printable characters are currently escaped as hex. Apparently not.

**Comment by zmwangx** [comment]
Still, `BEL` is currently printed as `^G`, `ESC` is currently printed as `^[`, etc., so it's not consistent.

**Comment by jarun** [comment]
Are you on zsh or bash? If you mean `\a` by `BEL` I am seeing a `?` on bash

**Comment by jarun** [comment]
```
apj @ apj-VirtualBox  ~/Documents
└─ $ ▶ touch $'Icon\r'
apj @ apj-VirtualBox  ~/Documents
└─ $ ▶ la
?  ab  h?c  Icon?
apj @ apj-VirtualBox  ~/Documents
└─ $ ▶ touch $'Icon\a'
apj @ apj-VirtualBox  ~/Documents
└─ $ ▶ la
?  ab  h?c  Icon?  Icon?
apj @ apj-VirtualBox  ~/Documents
└─ $ ▶ touch $'Icon\e'
apj @ apj-VirtualBox  ~/Documents
└─ $ ▶ ls
?  ab  h?c  Icon?  Icon?  Icon?
```

**Comment by jarun** [comment]
hex works fine. `\x55` becomes `U`.

```
apj @ apj-VirtualBox  ~/Documents
└─ $ ▶ touch $'Icon\x55'
apj @ apj-VirtualBox  ~/Documents
└─ $ ▶ ls
?  ab  h?c  Icon?  Icon?  Icon?  IconU
apj @ apj-VirtualBox  ~/Documents
```

**Comment by jarun** [comment]
> Still, `BEL` is currently printed as `^G`, `ESC` is currently printed as `^[`, etc., so it's not consistent.

So this was from nnn. Sorry, i was testing on bash to understand the *standard* behaviour.

**Comment by jarun** [comment]
I think we can simply follow the behaviour in bash. I'll handle it tonight. ;)

**Comment by zmwangx** [comment]
Bash has no builtin file listing facilities. If you mean ls, it's not that simple. The default behavior of coreutils ls(1) changed in 8.25, where the default quoting style became `shell` when stdout is a tty, so by default `$'Icon\r'` is printed as `'Icon'$'\r'`. You apparently don't want that. Judging from your transcripts, you're either using 8.24 or earlier, or your ls is aliased with `--quoting-style=literal`. But there are other equally valid and more informative quoting styles, e.g., `escape`, where `'$'Icon\r'` would be `Icon\r`, `$'1\a2'` would be `1\a2`, etc (basically, ANSI-C quoting without the quotes).

**Comment by jarun** [comment]
Yes, it would be `ls`.

> But there are other equally valid and more informative quoting styles

As I mentioned earlier, I don't want to allocate an additional buffer, copy all following chars (which I might have to do multiple times to multiple escapes in the same name) and finally break NAME_MAX length at extremes.

**Comment by jarun** [comment]
Please test with master. This would be gone.

**Comment by jarun** [comment]
@zmwangx if you are interested in refining it, please feel free to do so. I forgot we do the conversion only for the files we show in a go (max - number of rows in the terminal). I also had to use 2 additional buffers because we do not want to break a code point. The only part worth mentioning here is we didn't have to check each character because all but `ESC` fall in a range.

**Comment by zmwangx** [comment]
> we didn't have to check each character because all but ESC fall in a range.
>
>     if ((*buf >= '\a' && *buf <= '\r') || *buf == '\e')

Actually, that's not true. The full set of control characters is `00`–`1F` plus `7F`.

**Comment by jarun** [comment]
Right, but I'ld like to wait till I encounter those in a practical case.

**Comment by zmwangx** [comment]
Well, since you set out to replicate `ls --quoting-style=literal`, you can just do

```
if ((*buf >= '\x01' && *buf <= '\x1f') || *buf == '\x7f')
```

and call it a day. FWIW I've never seen ESC in a filename either, except by mistake.

**Comment by jarun** [comment]
So as of now, only the escape chars.

**Comment by zmwangx** [comment]
Okay.

**Comment by jarun** [comment]
`ls --quoting-style=literal`

you just forced me into doing it! ;)

**Comment by zmwangx** [comment]
As I said, I always preferred --quoting-style=escape.

Wait, tbh, I don't give a shit. I don't use stupid characters in filenames :)

**Comment by jarun** [comment]
Unfortunately, OS X uses. Or, was it a custom icon name? ;)

**Comment by niklasbogensperger** [comment]
Just for the record, it's working now for me with master.
Thanks!

> Wait, tbh, I don't give a shit. I don't use stupid characters in filenames :)

Tell that to the people making macOS :D

**Comment by zmwangx** [comment]
> Or, was it a custom icon name? ;)

If you want to set a custom icon for a directory, yes, you need a stupid `$'Icon\r'`.

**Comment by jarun** [comment]
> If you want to set a custom icon for a directory, yes, you need a stupid $'Icon\r'.

Bad design on someone's part I'ld say.

**Comment by jarun** [comment]
Thanks guys! We're good anyway! ;)

**Comment by jarun** [comment]
BTW, is it merely a co-incidence the fix went in the [420](https://en.wikipedia.org/wiki/420_(cannabis_culture))<sup>th</sup> commit?

**Comment by zmwangx** [comment]
> Bad design on someone's part I'ld say.

It's very rare so hardly an issue. The format of that file is poorly documented so most developers don't know how to make one even if they want to (I happen to be one of the small subset of power users / developers who actually looked into this format). Hidden by default too so most people never notice it. Besides, I'm doubtful that a central registry is better suited for this purpose. How would you allow a custom icon for any directory, that is persisted across duplication, network shares, etc.? Directories can't have resource forks AFAIK so you have to use a file inside.

If you want to see an example of an actual fucked up design in macOS's file browser, google `.DS_Store`.

**Comment by jarun** [comment]
> network shares

Would it work if the dir is mounted remotely on another OS?

**Comment by zmwangx** [comment]
> Would it work if the dir is mounted remotely on another OS?

If the other OS implements the feature. Most likely not Is custom icons for directories even a thing on Linux? I'd assume not since there are a gazillion file managers/browsers.

**Comment by zmwangx** [comment]
Okay, apparently it actually is a thing.

**Comment by jarun** [comment]
Yes, Ubuntu supports custom icons but I believe it's limited to the running system.

**Comment by zmwangx** [comment]
And I would assume custom icons of Nautilus do not work in other file managers.

**Comment by jarun** [comment]
I'll check it out tomorrow. Not having Nautilus in my system. ;)

**Comment by zmwangx** [comment]
Isn't Nautilus the default? Anyway, I don't use Ubuntu Desktop.

**Comment by jarun** [comment]
I use Voyager (XFCE based), Thunar is the default.

**Comment by jarun** [comment]
Yes, Thunar doesn't see Nautilus custom icon. :)
