### ISSUE TITLE
wiki  "Cygwin instructions" : add to install packages "libreadline-devel"

### ISSUE THREAD

**Issue by Viharrai** [jarun/nnn#212]
`libreadline-devel` is also build dependency. After that it builds and works like magic. Thanks

**Comment by jarun** [comment]
I've added it. Thanks for the heads-up!

Note that you can drop the dependency now using `make norl`.

**Comment by jarun** [comment]
@Viharrai would you be interested in adding the package `nnn` to Cygwin?

Packaging docs: https://cygwin.com/packaging-contributors-guide.html

**Comment by jarun** [comment]
`nnn` is now available on Cygwin: https://www.cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Fnnn%2Fnnn-4.6-1&grep=nnn
