### ISSUE TITLE
Progress bar for copying and moving processes would be very useful

### ISSUE THREAD

**Issue by ceylanb** [jarun/nnn#214]
I can't see the status of copying process. It would be very useful if it is possible to see status of a process.

**Comment by jarun** [comment]
`nnn` uses the standard cp, mv, rm commands which do not have this provision.

**Comment by jarun** [comment]
Reopening as I am thinking of making use of the patched [advcpmv](https://github.com/atdt/advcpmv).

**Comment by jarun** [comment]
Now you should be able to see the progress of cp and mv on Linux. You will need advcpmv. The instructions are here: https://github.com/jarun/nnn/wiki/How-to#show-cp-mv-progress

**Comment by jarun** [comment]
On BSD or macOS, just press <kbd>^T</kbd>.

**Comment by vaygr** [comment]
I'm thinking of instead of patching coreutils, maybe https://github.com/Xfennec/progress could be reused?

**Comment by jarun** [comment]
There's progress, there's rsync... but the patched `cp` and `mv` seemed to be the fastest option. So I decided to stick to it.

**Comment by vaygr** [comment]
Oh I think the major problem with this approach is that very few people will be patching one of the core system packages on their systems, rebuilding them and re-installing properly via rpm/apt/etc. It's not even like recompiling suckless tools.

It's a major invasion in the ecosystem, which also breaks integrity of the packages if done incorrectly, so it raises the bar pretty high in terms of flexibility.

**Comment by jarun** [comment]
There's some effort going on here: https://github.com/rurban/advcpmv to trim the cruft and submit it upstream. cp and mv are so basic there's no substitute.

**Comment by vaygr** [comment]
Yeah, that's good to know. However I'm sure it'll take year(s) before it gets its way to stable branches of various distributions, so I think that'd slow down this feature expansion in nnn _by a lot_.

**Comment by jarun** [comment]
OK.
