### ISSUE TITLE
Go to directory 

### ISSUE THREAD

**Issue by amanjitsk** [jarun/nnn#215]
Hi, 
Is there something like a "Go to directory" functionality whereby one can jumpy to a given directory (by entering the path to it via a prompt for ex). I do know there is a "Go to pinned directory" and bookmark feature but I was looking for something more general.
Thanks,
Amanjit

**Comment by jarun** [comment]
There was but the feature was removed. Turns out users didn't even notice as navigation is handled by `nnn` already.

**Comment by yanway** [comment]
Sorry for commenting on a resolved issue.
I really wish we had this feature. Sometimes I really want to move to a specific directory at once (especially when launching from GUI).
I just wanted to ask, is there absolutely no chance this is going to get reimplemented?

**Comment by jarun** [comment]
Use bookmarks. Do you see an issue there?

**Comment by jarun** [comment]
To elaborate a little more on this for people who may visit this thread:

One would `cd` using a relative path or from `/` whichever is easier. `nnn` now has a shortcut to visit root directly and the user can navigate from there. In fact, in _navigate_as_you_type_ mode the user has to use fewer or around the number number of keystrokes to reach a directory.

I removed the `cd` support as I am trying to get people more and more accustomed to the `nnn` way of navigating. Having a utility to navigate and then using `cd` kind of defeats the purpose.

**Comment by yanway** [comment]
Thanks for your reply. Sorry I haven't noticed.
OK that is very convincing.
I'll try to get used to _nav_as_you_type_ mode.
Thank you.
