### ISSUE TITLE
Ubuntu PPA not updated

### ISSUE THREAD

**Issue by superDuperCyberTechno** [jarun/nnn#216]
[It seems woefully outdated, no?](https://launchpad.net/~twodopeshaggy/+archive/ubuntu/jarun/)

**Comment by jarun** [comment]
The maintainer is gone. It's time to remove the link I guess.

**Comment by superDuperCyberTechno** [comment]
Roger that. Too bad, I really prefer PPA's to manually installing .debs.

**Comment by jarun** [comment]
or from the standard channels.

**Comment by superDuperCyberTechno** [comment]
Yeah, but as of the latest release (18.10) nnn is only version 1.9 which isn't compatible with nnn.vim.
