### ISSUE TITLE
Dated version of nnn on Ubuntu 18.04

### ISSUE THREAD

**Issue by deadpyxel** [jarun/nnn#217]
I just installed `nnn` to give it a go as I am trying to live more on the terminal.

I followed some of Luke Smith's video about the keybindings and the possible configurations, but didn't set anything custom yet.

Thing is, I can't select and copy/paste/move anything, even as I just installed it. I tried some restarts, purges and reinstall, but nothing worked. Most of the other functions I tried(like opening files, navigate-as-you-type, etc) worked as intended. I also tried to check if there was a new keybinding that I wasn't aware, and looked in the `?` menu, but didn't find any keys for selecting and moving/pasting as you can see in the screenshot below:

![test](https://user-images.githubusercontent.com/8644691/53587977-8aa2ad80-3b6a-11e9-8139-bdd6e7447d84.png)

I am not launching `nnn`with the `n` shortcut since system didn't set it up. The command I used to install it was `sudo apt install nnn`.

I am using Ubuntu 18.04.2 LTS, with `zsh` as my terminal using the oh-my-zsh stuff.

If there's any more info you need for a traceback, or if I am doing something wrong, please let me know.
Thanks in advance.

**Comment by deadpyxel** [comment]
Update: Looks like the version in the repository is outdated, installing from the .deb in releases page worked.

Not sure if I should close this issue or not, so I'll let the repo owner decide.

**Comment by jarun** [comment]
Yes, this is a very old version. You can use the generated package attached in the latest release.

@szlin is there a way to get the latest version on Ubuntu 18.04 channel?

**Comment by szlin** [comment]
@jarun ah, I just got back from a business trip.

Unfortunately, the answer is NO.

The version of nnn in 18.04 is 1.7[1], but there is no newer version of nnn in 18.04-backports archive[2]. Moreover, I don't have the permission to upload or backport packages in Ubuntu.

I suggest that he may add newer archive URL into the source list (e.g., 18.10 or Debian SID), or use the deb here directly.

[1] https://packages.ubuntu.com/search?suite=bionic&searchon=names&keywords=nnn
[2] https://packages.ubuntu.com/search?suite=bionic-backports&searchon=names&keywords=nnn

**Comment by jarun** [comment]
Thanks for the help Lin!
