### ISSUE TITLE
nnn ported to MacPorts

### ISSUE THREAD

**Issue by ParityError** [jarun/nnn#218]
I just wanted to let you know `nnn` has been ported to work on `macOS` via **[`MacPorts`](https://www.macports.org/ports.php?by=name&substr=nnn)** .

To install (sudo might be required):
```
$ port install nnn
```
Version check:
```
$ nnn -v
2.3
```
~ cheers!

**Comment by jarun** [comment]
Thank you so much for the note! I have added it to the packager matrix.
