### ISSUE TITLE
nnn gets screwed up if editor is suspended and resumed

### ISSUE THREAD

**Issue by bruce-hill** [jarun/nnn#219]
Steps to reproduce:

1. Launch `nnn`
2. From within `nnn`, open a file in a console editor like `vim`
3. Suspend the editor process to access the shell (ctrl+z for me)
4. Resume the editor process (the `fg` command for me)
5. Quit the editor normally

After this, `nnn` no longer renders properly. The same problems don't occur if `nnn` *itself* is suspended, only if the editor (or pager) launched by `nnn` is suspended. I'm not sure exactly why this happens, but it seems like all of the ncurses state gets lost in this process (e.g. `noecho()` and `curs_set(0)`). Using ctrl+z to drop from the editor into the shell is a very common part of my workflow, so fixing this case would be very helpful for me!

**Comment by jarun** [comment]
I can reproduce it but I need someone with good curses knowledge to fix it. Really not sure what's going on.

Could you try running exitcurses and initcurses before and after (respectively) spawning the utility?

**Comment by bruce-hill** [comment]
`spawn()` already calls `exitcurses()` before launching the editor process, but if I call `exitcurses()` and `initcurses()` after the child process exits, then the issue is fixed:

```
@@ -1019,8 +1019,11 @@ static void spawn(const char *file, const char *arg1, const char *arg2, const ch
                                DPRINTF_D(status);

                DPRINTF_D(pid);
-               if (flag & F_NORMAL)
+               if (flag & F_NORMAL) {
+                       exitcurses();
+                       initcurses();
                        refresh();
+               }
        }
```
I tried doing just `initcurses()` before, but it looks calling `exitcurses()` after the child process exits is necessary?

**Comment by jarun** [comment]
Let me try it out. A few mins please.

**Comment by jarun** [comment]
Please try the following patch:

```
src/nnn.c b/src/nnn.c
index f8021fd..7f33c58 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -976,11 +976,11 @@ static void spawn(const char *file, const char *arg1, const char *arg2, const ch
                arg2 = tmp;
        }
 
-       if (flag & F_NORMAL)
-               exitcurses();
-
        pid = fork();
        if (pid == 0) {
+               if (flag & F_NORMAL)
+                       exitcurses();
+
                if (dir != NULL)
                        status = chdir(dir);
 
@@ -1017,8 +1017,11 @@ static void spawn(const char *file, const char *arg1, const char *arg2, const ch
                                DPRINTF_D(status);
 
                DPRINTF_D(pid);
-               if (flag & F_NORMAL)
+               if (flag & F_NORMAL) {
+                       exitcurses();
+                       initcurses();
                        refresh();
+               }
        }
 }
```

**Comment by bruce-hill** [comment]
That works for me. Thanks for the fast response!

**Comment by jarun** [comment]
No problem! Thanks for confirming!

**Comment by jarun** [comment]
With our earlier patch I noticed an issue: if you spawn a shell and run some commands, when you exit `nnn` the prompt _jumps back_ to the point where you spawned the shell. So you are back at an earlier line.

To avoid this I have added commit 035512e3126aa7ae4f8b0d874e95e3bf6cf863dc. With this I see the editor resumes after `fg` but you have to press an extra `Enter` after closing it because the program blocks. This `Enter` opens the file again. Cumbersome, but better than a broken window I guess.

**Comment by jarun** [comment]
To be more clearer, I am pressing `Enter` here (after closing the window the first time):

```
~/G/nnn$ fg
Send job 2, “nnn -il $argv” to foreground
```

**Comment by jarun** [comment]
I believe this is now fixed for good (including the side-effect). Please test and confirm.

**Comment by bruce-hill** [comment]
Everything works correctly for me with the current version 👍

**Comment by jarun** [comment]
OK. You tested master, right?

**Comment by bruce-hill** [comment]
Yeah, the version with `refresh(); exitcurses(); fflush(stdout); initcurses();`

**Comment by jarun** [comment]
Awesome! Thanks for confirming!
