### ISSUE TITLE
cd on quit not working . .

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [jarun/nnn#22]
. . on Mint 18.1 x64 Cinnamon, using nnn 1.0-3.

I did jump through the necessary hoops, to wit: added the code to my bash.rc file (and indeed I tried it in a user rc file and a system one); invokved nnn not with `nnn` but with `n`; started a new terminal. Also, I tried using nnn's `cd` command rather than just navigating folders. But when I exit the program, my terminal remains in the folder it started.

**Comment by jarun** [comment]
You mean `~/.bashrc` right?
Is bash your default shell (try `echo $SHELL) in the new shell)?

I am using Ubuntu myself and it's working fine. I'm afraid you have to debug it yourself. You can start with adding and echo in the function to print something (just before the line `. $NNN_TMPFILE`). Does the `/tmp/nnn` file exist?

**Comment by jarun** [comment]
1. Copy the full content [here](https://github.com/jarun/nnn/blob/master/misc/quitcd/quitcd.bash) to your `$HOME/bashrc` assuming you are using bash.

2. Open a new bash shell. Start nnn. Navigate to somewhere else.

3. Press `Q` to quitcd. Note it's a capital Q.

**Comment by ACinnamonUserInUK** [comment]
Thanks for the reply.

    ~ $ echo $SHELL
    /bin/bash

> You mean |~/.bashrc| right?

I use /etc/bash.bashrc, so that the stuff in it applies to all my user
accounts. When putting the code in there did nothing, I moved the code
to ~/.bashrc. Still nothing!

The /tmp/nnn file does *not* exist.

The echo works.

**Comment by jarun** [comment]
> The echo works.

Then please comment out the line starting with `rm` and check the contents of `/tmp/nnn`.

**Comment by jarun** [comment]
It should have something like

`cd "/home/apj/Downloads/keysniffer"`

**Comment by ACinnamonUserInUK** [comment]
1: I don't think I am happy doing that.

3: capital 'Q' doesn't do anything, whether or not I've pressed 'c' (to
use the cd) function beforehand. And having to remember to use a capital
letter - this reminds of the widely joked-about difficulty of exiting
vim. Also, just what is the bashrc code meant to enable? Exiting to
where one has navigated to, via nn, using *any method*, or rather
exiting to where one got to using, only, nn's 'cd' method?

/tmp/nnn is (still) empty/non-existent.

I am afraid I don't think I can be bothered with this. Sorry.

**Comment by jarun** [comment]
> 1: I don't think I am happy doing that.

I mentioned the steps here. Didn't ask you to copy the contents of your .bashrc on a public page. If you check carefully, the *here* jumps to [this link](https://github.com/jarun/nnn/blob/master/misc/quitcd/quitcd.bash).

**Comment by jarun** [comment]
> 3: capital 'Q' doesn't do anything,

You are on v1.0. The feature is in master. That's why it's not working.

**Comment by RaoOfPhysics** [comment]
Hello. I'm using nnn v1.1 on macOS 10.12.5. I've copied the `quitcd.bash` contents into my .bashrc and have the alias set up for `n`. However, pressing `Q` does not cd into the directory I had navigated to. I would be grateful for any pointers.

I can confirm that `tmp/nnn` exists and `echo $SHELL` gives `/bin/bash`.

**Comment by jarun** [comment]
Please share the contents of `/tmp/nnn`.

**Comment by jarun** [comment]
In fact, if everything works properly, `/tmp/nnn` shouldn't exist. The script removes it once it changes the directory, which leads me to infer the script in your `~/.bashrc` is not even invoked. Did you use `n` to start the utility?

**Comment by RaoOfPhysics** [comment]
Hmm. Indeed, I haven't commented out `rm $NNN_TMPFILE` in .bashrc.

Anyway, here's the output: `cd "/Users/[my-username]/GitHub"`, which was the last directory I was in when I typed `Q`.

I did use `n` to start it, having set the alias to `nnn -d`.

**Comment by jarun** [comment]
> Hmm. Indeed, I haven't commented out rm $NNN_TMPFILE in .bashrc.

You shouldn't either. I believe it's more of a setup issue than a problem in the script. Please debug yourself. Maybe start with running the commands in the script and see if they work. Then add some echoes etc.?

**Comment by RaoOfPhysics** [comment]
I'm not proficient enough, but I'll give it a go when I have some time. For now, thank you for writing a wonderful tool and for your prompt feedback.

**Comment by Hibou57** [comment]
The links given leads to a 404 error page :(

**Comment by Hibou57** [comment]
@RaoOfPhysics, that a snippet you have to copy/paste in your shell initialisation script. There is one for Bash, Fish and Zsh, depending on the shell you use. Look at the link in my previous message.

I just tested with Zsh (copy/paste of `quitcd.zsh` and it works fine.

**Comment by jarun** [comment]
Thanks for the link update.

**Comment by RaoOfPhysics** [comment]
Thanks for pinging me, @Hibou57! To confirm, do I copy the contents of `quitcd.bash` (I'm using BASH) into my `.bashrc` file on macOS?

I've done so, saved the file, spawned a new shell, used `n` to navitage to `/Users/[my-username]/GitHub` and when I hit `Q` (capital Q), it brings me back to `$HOME`.

Also, `tmp/nnn` exists and shows `cd "/Users/[my-username]/GitHub"`, so I'm guessing @jarun's original point about the script not being called by my `.bashrc`. Will have to investigate, I guess. :)

**Comment by jarun** [comment]
From my .bashrc:

```
export NNN_TMPFILE="/tmp/nnn"

n()
{
    nnn "$@"

    if [ -f $NNN_TMPFILE ]; then
        . $NNN_TMPFILE
        rm $NNN_TMPFILE
    fi
}
```

And you should start nnn as `n`. It works without any issues.

**Comment by jarun** [comment]
> I did use n to start it, having set the alias to nnn -d

You can remove the alias now. `-d` is removed as detail view is the default mode.

**Comment by Hibou57** [comment]
@RaoOfPhysics , yes, for the first question.

For the rest, I don’t know, it looks strange.

A simple test:  just add something like this at the end of your `.bashrc`:

    echo "Hello"

Does it makes it displays “Hello” when you start a new shell? If no, then your `.bashrc` is not loaded. If yes, then it should work and I don’t see where the issue is.

**Comment by RaoOfPhysics** [comment]
I removed the alias and it worked! Thank you, @jarun and @Hibou57! :D

**Comment by jarun** [comment]
Awesome!

**Comment by sirolf2009** [comment]
Just ran into the same issue, but I'm using the fish shell instead. I had to run these commands:
```fish
set -u NNN_TMPFILE "/tmp/nnn"
export NNN_TMPFILE
```
Then run `funced n` and enter this:
```fish
function n
        nnn $argv
        if test -e $NNN_TMPFILE
                . $NNN_TMPFILE
                rm $NNN_TMPFILE
        end
end
```
Finally run `funcsave n` and launch nnn by using `n` instead of `nnn`

**Comment by jarun** [comment]
OK, so it works for you now? I use fish too!

**Comment by sirolf2009** [comment]
Yeah it works for me now. And fish is awesome! The autocomplete based on your command history is just the greatest thing ever.

**Comment by Mihajlo-Stefanovic** [comment]
Hey, i'm using version 1.7, followed the instructions on the [wiki](https://github.com/jarun/nnn/wiki/Basic-use-cases#configure-cd-on-quit) but couldn't get this to work on Ubuntu, bash shell. However after using `export NNN_TMPFILE="/tmp/nnn"` as suggested here, instead of `export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"` it was fixed. Is this just configuration on my machine that is affecting this?

**Comment by jarun** [comment]
We are at v3.1 now. Please use the latest version. The instructions correspond to the latest version.
