### ISSUE TITLE
Is it possible to 'duplicate' a file in the current directory?

### ISSUE THREAD

**Issue by simonsmith** [jarun/nnn#221]
Hey,

I'm essentially looking for a way to perform `cp someFile.js newName.js`. I couldn't see it in the documentation

Thanks!

**Comment by jarun** [comment]
`nnn` uses `cp` (as I didn't want to re-write a time-tested utility) in the background so you can't overwrite the file if it exists. I can make your use case work with the single file rename option but tomorrow someone may request for the operation in bulk and that can't be supported without changing the flow significantly.

So you have two options to do this:

1. If this is a non-frequent operation, use the prompt - select -> `ncp` helps (https://github.com/jarun/nnn/wiki/How-to#grab-selection-manually)
2. If this is a frequently used bulk operation, have a script (for bulk, again, use `ncp` to get selection). If it's a single file operation `nnn` passes the currently selected file name to the script as first argument.

If you prefer the script way kindly consider sharing it in the [user-scripts](https://github.com/jarun/nnn/tree/master/user-scripts).

**Comment by jarun** [comment]
Also, in case someone gets back `--backup` option, it's not available in BSD and OS X. So far I have maintained the commands such that they work out of the box on all supported platforms.

**Comment by jarun** [comment]
@simonsmith duplicate option in available in `nnn` now (`^R` or `F2`).

**Comment by sukima** [comment]
For those confused by @jarun answer as it is non-obvious.

1. Press <kbd>^R</kbd> on a single file/dir
2. Press <kbd>Enter</kbd> (yes rename to the same name it currently is)
3. nnn will notice the oddity of renaming to itself and instead ask for an alternative name to copy it to.

**Comment by jarun** [comment]
See https://github.com/jarun/nnn/wiki/Basic-use-cases#duplicate-file

**Comment by sukima** [comment]
Oof. Yeah I search that wiki for like an hour. No idea why I couldn't see that section. 🤷‍♀
