### ISSUE TITLE
issue with `Delete entry` function

### ISSUE THREAD

**Issue by g00dy22** [jarun/nnn#223]
Program version: [5d9bfed](https://github.com/jarun/nnn/commit/5d9bfed5a3d0a2bbc74696db318bf49a04609f9d)

In some cases program tries to execute `rm -frNAVIGATION a↑ k Up PgUp ^U Scroll up a↓ j Down PgDn ^D Scroll down a← h Parent dir ~ Go HOME 8↵ → l Open file/dir & Start dir 4Home g ^A First entry - Last visited dir 5End G ^E Last entry . Toggle show hidden c/ Filter Ins ^T Toggle nav-as-you-type cb Pin current dir ^B Go to pinned dir 7Tab ^I Next context d Toggle detail view 9, ^/ Leader key N LeadN Enter context N aEsc Exit prompt ^L Redraw/clear prompt b^G Quit and cd q Quit context 9Q ^Q Quit ? Help, config 1FILES b^O Open with... n Create new/link cD File details ^R Rename entry 5⎵ ^K / Y Select entry/all r Batch rename 9K ^Y Toggle selection y List selection cP Copy selection X Delete selection cV Move selection ^X Delete entry cf Create archive m M Brief/full mediainfo b^F Extract archive F List archive ce Edit in EDITOR p Open in PAGER 1ORDER TOGGLES b^J Disk usage S Apparent du b^W Random s Size t Time modified 1MISC 9! ^] Spawn SHELL C Execute entry 9R ^V Run/pick script L Lock terminal b^P Prompt ^N Note /mnt/data/download/zlib_1.2.11-2_mips_24kc` instead of plain `rm -fr /mnt/data/download/zlib_1.2.11-2_mips_24kc`.

So probably **path** argument became corrupted with **helpstr** at some point.

**Comment by g00dy22** [comment]
How to reproduce:

1. start nnn
2. browse to some path you want to remove
3. open help `?`
4. close help `q`
5. press `^X`
6. Press `y` in force prompt
7. Press `!` to look why file still in place
8. See an error
    rm: invalid option -- 'N'
    Try 'rm --help' for more information.

**Comment by jarun** [comment]
The change is reverted. Please try master.

**Comment by jarun** [comment]
I can reproduce this on master as well. Taking a look.

**Comment by jarun** [comment]
This should be fixed now. Please confirm.

**Comment by g00dy22** [comment]
Confirmed. Issue is gone
