### ISSUE TITLE
open file will generate defunct process

### ISSUE THREAD

**Issue by vincascm** [jarun/nnn#227]
open file will generate `defunct` process, version v2.3

**Comment by jarun** [comment]
Please provide some more details. What type of file, what is your desktop opener, where do you see the defunct process. A one-liner doesn't convey much info enough.

**Comment by vincascm** [comment]
@jarun use default config,open a pdf file, and opener is xdg-open,mupdf is pdf viewer, a item`[xdg-open] <defunct>` will be in `ps aux` list.
set `NNN_OPENER` to a shell script, the same situation.

**Comment by jarun** [comment]
OS and DE? Also please share the xdg-open version?

**Comment by jarun** [comment]
I can repro.

**Comment by jarun** [comment]
I had to revert this patch due to the issue explained in commit 4f15fb765affbdc436ac99e04478084fc4172159.

**Comment by jarun** [comment]
Fixed at commit e2d37632eaa9599c344851cfeb9b77851cd97281.
