### ISSUE TITLE
ctrl-y suspends nnn

### ISSUE THREAD

**Issue by ldelossa** [jarun/nnn#228]
When pressing ctrl-Y to start a selection nnn is suspended. I'm using zsh. This does not happen in any other application such as neovim or vim. Looks like ctrl-Y is a bash signal for delayed suspend.

**Comment by jarun** [comment]
This is documented in the readme: https://github.com/jarun/nnn#bsd-terminal-issue

**Comment by ldelossa** [comment]
I see, but K is not a working key binding on 2.3 for me

**Comment by jarun** [comment]
Because of the issue with <kbd>^Y</kbd>, <kbd>K</kbd> was added in v2.4: https://github.com/jarun/nnn/releases/tag/v2.4

**Comment by ldelossa** [comment]
Thank you! Thought 2.3 was latest. I use Brew

**Comment by sukima** [comment]
Confirmed, the brew version is broken. Considering this is a MacOS problem and Brew is for MacOS their formula should be updated!

**Comment by ldelossa** [comment]
Yeah I just installed from source. Not bad

**Comment by jarun** [comment]
Homebrew formula for `nnn` shows v2.4: https://formulae.brew.sh/formula/nnn

Are you guys telling me that's not working as expected?

**Comment by ldelossa** [comment]
Haven’t tried since installing from source

**Comment by jarun** [comment]
OK. It would be great if you can confirm once. Would help other users on Mac. I don't use mac myself.

**Comment by sukima** [comment]
@jarun You are correct. I must have fat fingered my `brew upgrade`. Working now! Thank you!

**Comment by jarun** [comment]
No problem!
