### ISSUE TITLE
Extension-less files not supported?

### ISSUE THREAD

**Issue by kaushalmodi** [jarun/nnn#23]
When I hit Return on files like CHANGELOG or Makefile, I get "No file association".

- Should such files be attempted to be opened as plain text?
- Or may be a check should be made if a file is plain text (something [like this][1]?)
  - I don't know how that would be done in a C code, but something like that should be available.

[1]: http://stackoverflow.com/a/567782/1219634

**Comment by jarun** [comment]
Are you on v1.1 (released today)?

Which opener variable did you define? We do [detect](https://github.com/jarun/nnn/blob/master/nnn.c#L1601) and attempt to open plaintext files in EDITOR (fallback vi). But that works only if NNN_OPENER is not used. I don't have NNN_OPENER and it's working for me right now.

**Comment by kaushalmodi** [comment]
I have none of the NNN_* env vars defined. I get the same behavior on the v1.1 release too.

```
> echo $NNN_OPENER
NNN_OPENER: Undefined variable.
> echo $EDITOR
emacsclient
```

If it matters, I am using `tcsh` shell.  I can easily get that "No association" message by launching `nnn` in this repo root, navigating to the `CHANGELOG` file and hitting <kbd>RET</kbd>.

**Comment by jarun** [comment]
What's the output of `file -b CHANGELOG`?

**Comment by kaushalmodi** [comment]
> What's the output of file -b CHANGELOG?

That's it! It outputs `ASCII English text`, not `ASCII text`.

**Comment by kaushalmodi** [comment]
This is not a good fix, but I tested this out and it works:

```
diff --git a/nnn.c b/nnn.c
index 110495e..e6b8d2b 100644
--- a/nnn.c
+++ b/nnn.c
@@ -1598,7 +1598,7 @@ nochange:
 				if (get_output(cmd, MAX_CMD_LEN) == NULL)
 					continue;
 
-				if (strstr(cmd, "ASCII text") != NULL) {
+				if (strstr(cmd, "ASCII English text") != NULL) {
 					exitcurses();
 					run = xgetenv("EDITOR", "emacsclient");
 					spawn(run, newpath, NULL, 0);
```

**Comment by kaushalmodi** [comment]
Also I found the use of PAGER there more intuitive than EDITOR ( https://github.com/kaushalmodi/nnn/commit/05d76410ff26558ccd0eec92e31c0c16ca562c5b ). If I wanted to edit the file, I would have hit the `e` binding.

**Comment by jarun** [comment]
I would have to look into the magic numbers and see if I can do anything better than this.

> If I wanted to edit the file, I would have hit the `e` binding

I don't thinks this is too relevant here. The keybind here is `Enter` and I don't see a reason to open a text file in read-only mode by default.

**Comment by olethanh** [comment]
You can use the "-i or --mime" option of  `file` which return the mime type, which  should be easier to parse and not depends on locales

>      -i, --mime
>              Causes the file command to output mime type strings rather than the more traditional human readable ones.  Thus it may say ‘text/plain; charset=us-ascii’ rather than “ASCII text”.
>

**Comment by jarun** [comment]
@olethanh yes, that'ld be nice! I'll push it in.

**Comment by jarun** [comment]
@kaushalmodi @olethanh please test with the fix and confirm everything works as expected. Thanks!

**Comment by kaushalmodi** [comment]
Thanks! I confirm this fix.
