### ISSUE TITLE
Terminal locks after a few minutes

### ISSUE THREAD

**Issue by juacq97** [jarun/nnn#230]
If I leave the terminal open with `nnn` for about 15 minutes, then the message `The pts/0 is now locked by user` appears and I can't return to `nnn`, I need to close the window and reopen again.

I'm thinking it's more of a feature than a bug, but it's a little annoying let the terminal open and when you need it, it's locked. There's any way to change that? I'm ussing `bspwm` and `termite` but I tried with `urxvt` and the same happens. Thanks!

**Comment by jarun** [comment]
Press `?` to open the help and settings screen. What is the value of `NNN_IDLE_TIMEOUT`?

**Comment by juacq97** [comment]
> What is the value of NNN_IDLE_TIMEOUT?

I have `NNN_IDLE_TIMEOUT: 900` I need to put this value to 0?

**Comment by jarun** [comment]
If you don't want to lock the terminal, don't even export it to reduce one config variable.
