### ISSUE TITLE
Feature request: don't block nnn after opening a pdf?

### ISSUE THREAD

**Issue by TimB87** [jarun/nnn#231]
Hi @jarun ,
so I tried this with a source build and recent environment using termite and a patched version of st using zsh and zathura as my pdf viewer.

Right now when I open a pdf file, nnn gets locked. No key presses are accepted until zathura is closed.
When I navigate to a dir that has some pdf files in it, I would maybe want to open more then just one. Or I may want to switch to another nnn workspace to work on a NOTES.md / document.tex with vim, but right now, I can't. Is this intended or can this be changed?

Thanks!

Edit: it's even better:
After submitting this issue I closed my spawned zathura after having typed "enter" a couple of times in it. These commands got chained, and it opened a couple zathura sessions in a row, one after another :)

**Comment by jarun** [comment]
What is your desktop opener?

**Comment by jarun** [comment]
And OS too.

**Comment by TimB87** [comment]
I use CRUX 3.4 and xdg-open.

**Comment by jarun** [comment]
I am also using xdg-open on Ubuntu. What's your version?

What happens if you open a file directly from cmdline using xdg-open? Does it start in the background (so you can use the prompt without waiting to close) or stays at the prompt?

**Comment by TimB87** [comment]
I use the latest xdg-open, version 1.1.3.
Interesting, I didn't check that. It opens lynx.. sorry then, I thought it was nnn!

**Comment by jarun** [comment]
Awesome! Please raise a PR with distro details. You need to link.

Are you saying the xdg-open problem is not a nnn issue?

**Comment by TimB87** [comment]
Will have to check about xdg-open, will report back later today.

About the PR: will do.

**Comment by jarun** [comment]
Thank you!

**Comment by TimB87** [comment]
So, I was able to check and it seems that xdg-open uses ~/.config/mimelist.apps AND ~/.local/share/applications/mimelist.apps for user settings.. I was unaware of the first tbh but it seems to be the better way, so I nuked the latter.

Now, xdg-open path/to/file.pdf opens zathura directly. Still, nnn shows the same behavior. BUT xdg-open stays as a foreground process in the terminal - is this the same for you?

**Comment by jarun** [comment]
When you run `xdg-open some.pdf` from the cmdline does xdg-open exit immediately so you can run the next cmd? On Ubuntu it exits immediately.

Also, on Ubuntu xdg-open is called from a wrapper. I don't have the laptop handy.

**Comment by TimB87** [comment]
xdg-open does not exit immediately and I can't run the next command.
/usr/bin/xdg-open is a shell script here too, though, this one: http://sprunge.us/evKb8B

**Comment by jarun** [comment]
> xdg-open does not exit immediately and I can't run the next command.

That's the problem. In Ubuntu it exits immediately.

**Comment by TimB87** [comment]
Weird, it does the same using xterm + bash. So this seems to be unrelated, shall we close this or do you have a sparkling idea for me? :) 

Thanks a lot for the help so far! Greatly appreciated!

**Comment by jarun** [comment]
I think I will add a config option to issue the default opener in background instead of waiting for users facing this. As _it appears_ that `nnn` blocks users would run away.

You'll have to test the change and confirm. Give me a few hours.

**Comment by TimB87** [comment]
Sounds great, sure, will do - no hurry :)

**Comment by TimB87** [comment]
Can confirm that this is working! :+1: Thanks a lot, @jarun !

**Comment by ahloiscreamo** [comment]
HI, 
i can confirmed , the issues affected me too. (Fedora 29/ xdg-open)
The latest commit fix it, cheers!

**Comment by jarun** [comment]
Awesome!
