### ISSUE TITLE
Launcher (=) is not working

### ISSUE THREAD

**Issue by pat-s** [jarun/nnn#232]
The new launcher shortcut (=) is not working for me.

`fzy` is installed and works with the user-script.

**Comment by rimmington** [comment]
Is `nlaunch` in your `$PATH`? I put it in my user scripts directory at first, but that doesn't work.

**Comment by jarun** [comment]
@rimmington is right! Please read the documentation.

**Comment by pat-s** [comment]
Thanks guys, I only read the release notes and not the README. Maybe add it to the release notes as well?

Thanks for the great project. Loving `nnn` so far. I also like projects with responsive maintainers :)

**Comment by jarun** [comment]
Have fun! Consider donating a little if your budget permits! ;)
