### ISSUE TITLE
Instructions for creating a symbolic link

### ISSUE THREAD

**Issue by pat-s** [jarun/nnn#234]
Might be obvious but it is not documented anywhere.

1. Select the file(s) you want to symlink
2. Go to target directory
3. Press `n` and choose `@` for symlink

**Comment by jarun** [comment]
Please add this in the hacking `nnn` wiki - https://github.com/jarun/nnn/wiki/hacking-nnn

**Comment by jarun** [comment]
Oh, we don't need it. `?` shows the shortcut as <kbd>n</kbd>. And from there the flow is kind of guided.

**Comment by pat-s** [comment]
> Oh, we don't need it. ? shows the shortcut as n. And from there the flow is kind of guided

Kind of but it is not completely obvious ;) So I thought I just post it here. Some people might profit from it..

**Comment by jarun** [comment]
Then please add it to the wiki where people can easily find it.

**Comment by jarun** [comment]
Also, please use the term `link`. Both sym and hard links can be created.

**Comment by pat-s** [comment]
Alright. Can you make the wiki editable?

**Comment by jarun** [comment]
I have to search the option... I thought it was editable for all be default.
I will add the changes sometime tonight.

**Comment by jarun** [comment]
Added in the wiki: https://github.com/jarun/nnn/wiki/hacking-nnn#creating-links

Thanks for bringing it up.

**Comment by jarun** [comment]
I found the setting as well. The wiki is now editable for all.
