### ISSUE TITLE
Instructions for centOS

### ISSUE THREAD

**Issue by pat-s** [jarun/nnn#235]
To get the latest `nnn` on CentOS one needs to enable `epel-testing`.

Maybe you could also list CentOS more prominently in the list of supported distros :)

`# yum --enablerepo=epel-testing install nnn`

https://pkgs.org/download/nnn gives a nice overview.

**Comment by jarun** [comment]
Please raise a PR directly for minor stuff.

**Comment by jarun** [comment]
I think I missed the PR was never raised. Added it now.
