### ISSUE TITLE
How do I move files between directories?

### ISSUE THREAD

**Issue by alxpettit** [jarun/nnn#238]
I've read the man page and the `README.md`, and I know how to select files and how to apply actions to file selections like cut & copy. But after that, how do I paste the files in a new location?

**Comment by jarun** [comment]
The workflow is:

- Select files
- Go to target directory
- Press <kbd>P</kbd> to _copy_ selection to new location
- Press <kbd>V</kbd> to _move_ selection to new location

**Comment by jarun** [comment]
Please refer to the program help where it's documented.

**Comment by alxpettit** [comment]
Are you talking about the man page? I did look at that before. :/

Re-reading the `SELECTION MODE` section, I can see how it tries to explain this, but it really wasn't clear to me at all given that it doesn't follow the workflow of what I'm used to. Anyway, thanks for answering! Hopefully anyone who's confused will find this thread useful.

**Comment by jarun** [comment]
You'll find the shortcuts here: https://github.com/jarun/nnn#keyboard-shortcuts

or in the in-program help.

The workflow is explained here: https://github.com/jarun/nnn#selection

It's true `nnn` workflows are different in some cases. If you think the workflow is not very clear can you raise a PR that adds more clarity?
