### ISSUE TITLE
Doesn't dettach when using kitty terminal

### ISSUE THREAD

**Issue by qazip** [jarun/nnn#240]
#### Environment details (Put `x` in the checkbox along with the information)

[x ] Operating System: Arch
[x] Desktop Environment: i3wm
[x ] Terminal Emulator: kitty
[x] Shell: zsh
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I can't close nnn after opening a video with mpv in the [kitty](https://github.com/kovidgoyal/kitty/) terminal. It works fine in other terminals but not in kitty. So, browse to an .mkv file, open it and try to close nnn. It doesn't work while the opened program is running.

**Comment by jarun** [comment]
Are you saying in the same environment it works with other terminal emulators? Then why is it a `nnn` issue?

**Comment by qazip** [comment]
Yes, using tilix for example, works exactly as expected.

**Comment by jarun** [comment]
Then please raise the issue on kitty.

**Comment by jarun** [comment]
BTW, install and try once with xfce4-terminal or gnome-terminal. They are much more standards-compliant.

**Comment by jarun** [comment]
Also, does `NNN_OPENER_DETACH=1` help? Though setting it in your config may give problems with tilix.

**Comment by jarun** [comment]
Also, do you specify `NNN_OPENER`?

**Comment by qazip** [comment]
`NNN_OPENER_DETACH=1` does not help. I do not specify `NNN_OPENER`.

**Comment by jarun** [comment]
take a look at issue https://github.com/jarun/nnn/issues/231.

`xdg-open` is the default opener. What happens when you run `xdg-open file.pdf` directly from kitty terminal? Does it exit and you can re-use the prompt or it blocks?

**Comment by jarun** [comment]
Or, in your case try an mkv file.

**Comment by qazip** [comment]
It opens but does not detach. Something is wrong though, tilix is also behaving like kitty now. Alacritty is also behaving like that.

When you open an mkv file, does it detach from terminal? Can you close nnn and the file continues playing?

**Comment by jarun** [comment]
> When you open an mkv file, does it detach from terminal? Can you close nnn and the file continues playing?

Yes, of course. For me, even when I issue `xdg-open` from the terminal prompt it detaches.

I am on Xubuntu 18.04.

**Comment by qazip** [comment]
See my EDIT2 above.

**Comment by jarun** [comment]
And yes, even from within `nnn` it's the same behaviour. It detaches. And I don't have `NNN_OPENER_DETACH=1` set.

**Comment by jarun** [comment]
Try master.

**Comment by jarun** [comment]
I have confirmed on my DE it's not a kitty problem. It's because the opener behaves differently in different platforms. I believe the new config var will fix this.
