### ISSUE TITLE
cp and mv does not work: xargs issue

### ISSUE THREAD

**Issue by matecrn** [jarun/nnn#241]
For some reason `nnn` does not want to move or copy files. It works just fine with `sudo nnn` though.

This is what I got when attempting to copy or move the same file:
```
xargs: cpg: No such file or directory
xargs: mvg: No such file or directory
```

I'm not sure if this is just an `OpenRC` problem, as I have been having permission setting issues with it. However, this output displays nothing about permissions, but it seems to work with `sudo` so it may very well be.

---

#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Parabola w/ OpenRC
[x] Desktop Environment: i3-gaps
[x] Terminal Emulator: urxvt
[x] Shell: fish
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. Install Parabola with OpenRC
2. Run nnn as a normal user
3. attempt to copy or move file
4. Nothing happens
5. Exit nnn and see output

**Comment by jarun** [comment]
Do you have `NNN_OPS_PROG` set?

If not, there was a regression in master last night. Please update master (I fixed an hour back) and try again.

**Comment by matecrn** [comment]
Yep, I had it set to 1. I then tried 0 and then I turned it off completely.

Unsetting it worked, thanks.

**Comment by pat-s** [comment]
FYI the error also occurs for me when `advcpmv` is missing, even if `NNN_OPS_PROG = 0`. Maybe because `coreutils` was missing, which got installed as a dep by `advcpmv`.

**Comment by jarun** [comment]
This should be fixed on master. Please confirm.

**Comment by pat-s** [comment]
Jup, works now.

**Comment by jarun** [comment]
Thanks for the confirmation!
