### ISSUE TITLE
Getting back to the genuine view of a directory after filtering

### ISSUE THREAD

**Issue by faxotherapy** [jarun/nnn#242]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: MacOS Mojave
[x] Desktop Environment: Aqua, Water, River, etc. Possibly one of them.
[x] Terminal Emulator: Terminal app.
[x] Shell: Zsh
[ ] Custom desktop opener (if applicable):
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
No issue, but only a simple question. When I press `/` and type `\.mp4`, then `ESC` key I only see the list of MP4 files residing in the directory. That is expected. Now, how can I revert back to the genuine view of that directory, thus with all files listed?

Thanks for your answer. Thanks again a lot for your work.

**Comment by jarun** [comment]
Please use <kbd>^L</kbd> to redraw.

In fact you can also skip the <kbd>Esc<kbd> in that case. <kbd>Esc</kbd> just exits the prompt.
