### ISSUE TITLE
Cannot be set as the default file manager for GUI software

### ISSUE THREAD

**Issue by imaojun** [jarun/nnn#243]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System:
Manjaro i3wm 4.19.32-1-MANJARO
- [x] Desktop Environment:
Bspwm
- [x]  Terminal Emulator:
urxvt
- [x]  Shell:
zsh
- [x]  Custom desktop opener (if applicable):
xdg-open
- [x]  Issue exists on `nnn` master
Cannot be set as the default file manager for GUI software.
I set all of default file manager to be `nnn` 
```
exo-preferred-applications -c
# then set
urxvt -c nnn "%s"
# or
/usr/bin/nnn "%s"
```
 and
```
mimeopen -d /home
#  choose
nnn
```
Example:
Chromium  Version 73.0.3683.86 (Official Build) Arch Linux (64-bit)  
When I Clicked:
Download -->> Show in folder,
```
“Failed to execute default File Manager: Input/output error”
```
I found`exo-preferred-applications -c` the format `%s` to be at the beginning of `file:///`.

`nnn` does not support file paths beginning with File. I can't use nnn as my default file manager. I later used `double commander` as my GUI graphics manager, which works when I try to open the file directory.
#### Exact steps to reproduce the issue
When I try to open the file directory in the GUi software (Chromium，shutter screenshot, etc..)
But, when I use `ranger` as the default file manager, this works.
Thanks.

**Comment by jarun** [comment]
I will check this.

**Comment by jarun** [comment]
I am on XFCE4, and When I try with ranger, I get:

    ~/G/nnn$ xdg-open ~/Downloads
    ~/G/nnn$ Error: Must run ranger from terminal

However, I will make the change to identify files starting with `file://`.

**Comment by jarun** [comment]
Please test with latest master. Now, if I run `nnn file:////home, it opens the directory.

**Comment by jarun** [comment]
I could make it to work as my default file manager on xfce4 as well. Will update the steps soon.

**Comment by jarun** [comment]
I have added a wiki page to setup `nnn` as the default file manager - https://github.com/jarun/nnn/wiki/nnn-as-default-file-manager

Can you please test this and confirm if it works? If you think something is missing OR something else works feel free to update the wiki page. It's editable for all now.

**Comment by imaojun** [comment]
@jarun :raised_hands:COOL. It now works as a default file manager In `Archlinux/Manjaro` with `Bspwm` and `Urxvt`.

**Comment by jarun** [comment]
Thank you so much for confirming. If your budget spares, do consider donating a small amount.

**Comment by jarun** [comment]
Latest master has more changes to handle files as well. Also, the scripts have been updated to pass the list of arguments to `nnn`.
