### ISSUE TITLE
Easy bookmarks

### ISSUE THREAD

**Issue by dessalines** [jarun/nnn#246]
I love nnn, but bookmarks seem needlessly difficult right now, and it'd be nice to do everything within the app.

Maybe something like:

 `Leader + bm` - Goes to a bookmark screen, where you can view, goto, and remove bookmarks.

Quick actions:

 `Leader + ba` - adds a bookmark, returns a message with that bookmarks index
 `Leader + br` - removes a bookmark
 `Leader + bg[NUM]` - Quick goes to a bookmark

**Comment by jarun** [comment]
There's no plan to have a separate config file for `nnn`. So we depend on exported variables and the responsibility of creating/modifying the bookmarks in the shell's rc file lies with the user.

I have tried to clarify setting up bookmarks as much as possible in the documentation. Please let me know if there's anything that's can still be improved.

**Comment by dessalines** [comment]
There's a deeply embedded folder I need to get to frequently. How do I do that, step by step?

**Comment by jarun** [comment]
The steps are here: https://github.com/jarun/nnn/wiki/hacking-nnn#add-bookmarks

Let's say you want to bookmark `/home/vaio/GitHub/nnn/scripts/test/outdir/cage/lion` and set the key as `l`.

So you append to the list of existing bookmarks in the example above and the new bookmark string would become:

    export NNN_BMS='d:~/Documents;u:/home/user/Cam Uploads;D:~/Downloads/;l:/home/vaio/GitHub/nnn/scripts/test/outdir/cage/lion'

**Comment by dessalines** [comment]
Thanks, that's actually not too bad. It might be good to add a goto bookmark section in the `?` help menu, I didn't see it there and had to go to the main page to figure out its `leader+bmark key`.
