### ISSUE TITLE
How to reverse selection?

### ISSUE THREAD

**Issue by faxotherapy** [jarun/nnn#247]
#### Environment details (Put `x` in the checkbox along with the information)

[ ] Operating System: Mojave
[ ] Desktop Environment:
[ ] Terminal Emulator: Terminal
[ ] Shell: Zsh
[ ] Custom desktop opener (if applicable):
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Not an issue, but only asking to select, for example, 8 out of 10 items. I'd like to select the 2 items I don't want, then reverse selection with a shortcut to get the eight selected instead.

An alternative could be selecting all 10 items with `Y`, then unselecting 2 items, but I did not find the trick to unselect 2 items while the whole list of 10 remains selected.

Thanks for your help.

**Comment by jarun** [comment]
There is no way to unselect. Manipulating the copy buffer this way is costly. Say you have selected a 1000 files and then you want to unselect 3. The only option is to do this in 2 steps - 1. run complete path matches in the buffer and 2. when a match is found, re-adjust (move rest of buffer up). Both are costly and needs quality time to implement.

This applies to your alternative approach too. It's easy to throw in a key to append to the selection (done in a selection mode) buffer, but searching it and removing a path isn't.

I can see how it can be a bother when the number of files to be selected is high, but how about this alternative workflow (using the same example I took above): create a dir `abc` and move the 3 files to it. Then select the rest 997 together. And if you have such a use case then there a high probability those three files never belonged with the rest 997 in the first place i.e. they could have been organized in a different directory.

**Comment by jarun** [comment]
@faxotherapy I came across this thread which searching something.  You can invert selection in `nnn` now.
