### ISSUE TITLE
unable to "make"

### ISSUE THREAD

**Issue by ramsonline** [jarun/nnn#249]
Hi! i just heard about nnn yesterday and so i wanted to try it by myself.
I cloned the current master and tried to build it on my Pi1.

When i simply enter the created nnn folder and tried the "make" command i get the following error: `make: Nothing to be done for 'all'.`

I am actually not a real developer but i saw that the Makefile has something like a "debug" parameter. 
With "make debug" it actually worked (with a few warnings).

**Comment by anders-dc** [comment]
I realized this too, as the default 'all' target is empty. You can compile the `nnn` executable with `make nnn`, however.

**Comment by jarun** [comment]
I removed the target few days back as debug was not installing. I will place it back.
