### ISSUE TITLE
Custom terminal colours are reset after certain actions on Kitty

### ISSUE THREAD

**Issue by lyneca** [jarun/nnn#252]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Arch Linux
- [x] Desktop Environment: `i3-gaps`
- [x] Terminal Emulator: `kitty`
- [x] Shell: `zsh`
- [ ] Custom desktop opener (if applicable):
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Open normally in `kitty`, press `?` to show the help, then `q` twice to exit. All custom terminal colours set (in this case with `pywal`) will be cleared.

This seems to happen whenever a pager is opened - e.g. with `p`, the help file, or with `D` file info. My `$PAGER` is set to `less`, but the same happens without setting `$PAGER`.

**Comment by jarun** [comment]
I use neither of these - kitty/pywal. So need someone to pitch in to fix this.

For showing in pager we call `spawn()` with flag `F_NORMAL`. If you see, first we call `exitcurses()` [https://github.com/jarun/nnn/blob/master/src/nnn.c#L1003] but later we don't call `initcurses()` [https://github.com/jarun/nnn/blob/master/src/nnn.c#L1026].

`initcurses()` does a lot of setup work - https://github.com/jarun/nnn/blob/master/src/nnn.c#L850. One of those is `start_color()` for example. See if calling any of these function after we close the pager and get back into `nnn` helps.

**Comment by dylanaraps** [comment]
This occurs when a terminal program does a `reset` of the terminal state instead of a regular `clear`. `pywal` modifies the terminal's color-scheme through escape sequences. A `reset` undoes pywal's modification.

Nothing can be done on `pywal`'s or the terminal emulator's end.

**Comment by jarun** [comment]
@lyneca from the `endwin()` manpage:

```
A program should always call endwin before exiting or escaping from curses mode temporarily. This routine restores tty modes, moves the cursor to the lower left-hand corner of the screen and resets the terminal into the proper non-visual mode. Calling refresh or doupdate after a temporary escape causes the program to resume visual mode.
```

I have pushed commit 892f5bedee023bf7d3c9b0e2a3f959ad969c6e6a which does this verbatim. Please see if this fixes the problem for you.

BTW, do you see the issue if you spawn a new terminal (<kbd>!</kbd>) and return back to `nnn`?

**Comment by jarun** [comment]
I think the problem will persist because `endwin()` resets the screen. And `nnn` can't call `clear()` instead because it breaks `nnn` interface when you re-enter it from the spawned child. As I cited above, the recommended way to temporarily get out of the curses mode is `endwin()`. So I don't think I have a solution to the problem.

The utility you are using does a temporary modification to the terminal's color output. I think you would be able to reproduce the issue even if you issue the `reset` command in the terminal.

**Comment by jarun** [comment]
For future reference, `googler` found me this: https://github.com/dylanaraps/pywal/issues/313.

**Comment by vizs** [comment]
If you don't mind me asking, what is `googler`? Never heard about it before. Is that a new search engine?

**Comment by jarun** [comment]
Here you go: [googler](https://github.com/jarun/googler)
