### ISSUE TITLE
mouse click stops working after opening a few media files with double click

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#257]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Xubuntu 18.04
[x] Desktop Environment: XFCE4
[x] Terminal Emulator: st/xfce4-terminal
[x] Shell: fish
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

- Run `nnn -isl`
- Click on a few (2/3) media files to open in SMPlayer
- Now single click or double click doesn't work anymore

**Comment by jarun** [comment]
@bruce-hill can you please take a look into this?

**Comment by bruce-hill** [comment]
I'm not seeing the issue on OSX in iTerm (fish shell). I can test later on Arch with st. My guess is it has to do with the terminal emulator. It might be fixable by switching from BUTTON1_CLICKED to BUTTON1_RELEASED, but then nnn would have to track time since last click to detect double clicks.

**Comment by jarun** [comment]
I am thinking if it's related to the mouse position calculation. Sometimes I am noticing some other file getting opened.

**Comment by jarun** [comment]
Also note that you should use xlines and xcols.

**Comment by jarun** [comment]
I am planning to make a release tomorrow. Kindly prioritize this one.

**Comment by jarun** [comment]
Please test the patch, specially in scenarios where the number of files are more than the screen capacity and you are in a _page_ other than the first one.

**Comment by jarun** [comment]
In addition, would it be possible for you to add mouse scroll support?

**Comment by jarun** [comment]
Another valuable addition would be, if you click on a dir in the absolute path in the first line, cd to that dir. I think we can have all of these in the nest release, where we can take our time to stabilize and we can also come up with more interesting use cases for the mouse.

**Comment by bruce-hill** [comment]
> Please test the patch, specially in scenarios where the number of files are more than the screen capacity and you are in a _page_ other than the first one.

The new version does not correctly handle clicking below the bottom half of the screen when there is more than a screenful of files. My logic was basically: calculate the index of the file at the top of the screen (`r = MIN(MAX(0, cur-((xlines-4)>>1)), ndents-(xlines-4))`), then add the mouse click's y-offset (`r += event.y-2`), and ignore the click if it goes past the last file. This version works (with a `#define MAX` similar to `MIN`):

    r = MIN(MAX(0, cur-((xlines-4)>>1)), ndents-(xlines-4));
    r += event.y - 2;
    if (r >= ndents)
        goto nochange;
    cur = r;

> In addition, would it be possible for you to add mouse scroll support?

Unfortunately, ncurses version <=5 doesn't support the scroll wheel. If you wanted to support it, it would need to be `#ifdef`'d on the ncurses version. For ncurses 6+, I think it's just BUTTON4_PRESSED and BUTTON5_PRESSED events, which is not too hard. I'm not sure how much rewriting this would require, but I think it would be nice if nnn had more sophisticated scrolloff logic, like vim has (you can move the cursor without scrolling, until it gets within N lines of the bottom, and you can scroll without moving the cursor, until the cursor gets within N lines of the edge of the window).

> Another valuable addition would be, if you click on a dir in the absolute path in the first line, cd to that dir. I think we can have all of these in the nest release, where we can take our time to stabilize and we can also come up with more interesting use cases for the mouse.

That would be cool. I'm not sure how that would work with extra long path names though. The other things I could think of:

- Having a description column ("date modified", "filename", etc.), and clicking on the column label would sort by that column (like most GUI file browsers)
- Clicking on the far left character could toggle file selection for the clicked file.

There's not very much on screen to click on, so there aren't really that many mouse use-cases.

**Comment by jarun** [comment]
> The new version does not correctly handle clicking below the bottom half of the screen when there is more than a screenful of files.

Can you explain a bit more? Clicking on empty area or cling on a file?

Also, can you raise a PR for the new version with MAX? Then I can test it out.

**Comment by bruce-hill** [comment]
> Can you explain a bit more? Clicking on empty area or cling on a file?

If the screen is 30 rows tall, and there are 100 files in a directory, clicking on the 99th file will cause a segfault (or any of the last HEIGHT/2 files).

> Also, can you raise a PR for the new version with MAX? Then I can test it out.

https://github.com/jarun/nnn/pull/258
