### ISSUE TITLE
"The missing terminal file browser for X" is misleading

### ISSUE THREAD

**Issue by Keith-S-Thompson** [jarun/nnn#262]
The man page and several other files refer to `nnn` as "The missing terminal file browser for X".

The most obvious interpretation is that "X" refers to the X11 window system. I suggest changing "for X" to something else, or perhaps just dropping it. Perhaps "The missing file browser for terminals", or just "The missing terminal file browser".

Affected files:
* `README.md`
* `nnn.1`
* `packagecore.yaml`
* `src/nnn.c`

**Comment by jarun** [comment]
> The most obvious interpretation is that "X" refers to the X11 window system.

That's what it meant when it started. It's a terminal file browser that integrates very well with X11. It's a fun way to say X11 should have come with a terminal file browser like `nnn`.

Follows homebrew tagline - "The missing package manager for macOS (or Linux)".

How about - `The missing terminal file browser for the desktop`?

**Comment by Keith-S-Thompson** [comment]
Hmm.

I don't see how it integrates with X11 -- other than the fact that you can run it in a terminal that might be running under X11. It's a terminal program, not an X11 program, and it would work just as well on a Linux console or an old-style VT100 terminal.

Nautilus is integrated with X11; it won't run if `$DISPLAY` isn't set.

Calling it "... for X" could discourage someone (like me) who's looking for something that runs in a plain-text terminal.

**Comment by jarun** [comment]
I think you are missing the part  that the tagline was added for pure fun and it is not to be taken for the literal meaning.
