### ISSUE TITLE
Proposal: simplified file selection

### ISSUE THREAD

**Issue by bruce-hill** [jarun/nnn#263]
Right now, selecting files in nnn is a bit confusing, and there's a different code path and key bindings for selecting one vs. selecting many files. I've been tinkering around and came up with a prototype where file selection works as follows:

- Press `<space>` to toggle the selection state of the file under the cursor, or click on the selection indicator area of a file (leftmost character) to toggle its selection state
- Press `^a` to select all files in the current window (or if they're all already selected, deselect them)
- Press `<Esc>` to deselect all selected files across all folders
- Press `J`/`K` (uppercase) to move the cursor and apply the selection state at the old cursor position to the new cursor position like smearing paint (useful for quickly selecting a range of files: `<space>JJJ`). Maybe some equivalent binding for PgDn/PgUp and Home/End?
- File selection would be persistent across directories and contexts like it is now, but visually rendered everywhere too. When navigating into a new directory or switching contexts, scan the copy buffer for file names to properly set their selection state in the flag bits.
- Moving, deleting, or copying files would clear the file selection. Maybe copy should not clear the selection?
- I also swapped out the "+" indicator in favor of a colored block (a space character with a yellow background), which is a lot more visually distinct.

As well as being a lot more intuitive (for me, at least), my prototype is also a bit less code overall, which is nice. I'd like to get feedback before cleaning up my code and submitting a pull request. Would this be a welcome change? Is there some use case I'm not considering?

**Comment by jarun** [comment]
> toggle the selection state of the file under the cursor

How are you planning to achieve this, algorithmically?

> Press J/K (uppercase) to move the cursor and apply the selection state at the old cursor position

This may be useful

> When navigating into a new directory or switching contexts, scan the copy buffer for file names to properly set their selection state in the flag bits

This isn't done today because when you have selected a 1000 files this would take a lot of time to parse in the worst case. Please keep in mind that `nnn` should remain usable on low-power low-freq devices

> Moving, deleting, or copying files would clear the file selection

Not necessary, one may still want to list the files (s)he selected earlier

> I also swapped out the "+" indicator

Due to our event registration (and as I explained why we don't parse the selection list) sometimes the `+` is shown for a short while. Showing in color doesn't help with that. The intended way to view the selection is the selection list.

**Comment by bruce-hill** [comment]
Re: efficiency, the current prototype implementation just checks the `FILE_COPIED` bits and either appends the filename to `pcopybuf` or scans through `pcopybuf` looking for the filename and shifts the memory over to delete it. (It also does a simple scan to set the copy bit when changing directories) There are a lot of ways to speed this up, like coalescing removals, or using a simple hash table to store which inodes are selected, so I'm not too worried about making a performant version, as long as the core idea is acceptable.

> Not necessary, one may still want to list the files (s)he selected earlier

I think it would be better (and pretty easy) to have this as separate functionality from the list of currently selected files. A common use case might look like: select a few files, delete them, select a few more files, try to move them (but fail because the deleted files are still "selected" even though they don't exist). To me, that's very confusing. With copying, it's not as confusing, because the copied files are still visibly selected in their original location, and doing another action with a recently copied file is valid, unlike doing something with a recently deleted file.

**Comment by jarun** [comment]
> so I'm not too worried about making a performant version

You should be. The list can have ten thousand files and in the worst case a path can be 4K in length. Searching this list for that 4K and then doing a `memmove()` on a Pi would not be performant.

> There are a lot of ways to speed this up, like coalescing removals, or using a simple hash table to store which inodes are selected

All of this is book-keeping for stuff that we don't really need right now. With thousands of files the hash table size wouldn't be insignificant anymore.

As long as there is no pressing need for this, let's focus on stuff that adds more value to the utility.

**Comment by staeff777** [comment]
I'm sorry if you have already solved this issue (e.g. with this file picker mode maybe?), I found this issue by searching for how to toggle selections.

> How are you planning to achieve this, algorithmically?
I might have a small suggestion:
If the selection file is kept in alphabetical sorted order, you can access paths in O(log n) comparisons using a binary search.
To keep the selection list sorted, each file has to be also inserted using a binary search. 
For 1000 files you'd need at max 10 comparisons.

**Comment by jarun** [comment]
`nnn` supports selection from multiple directories. There can be files with the same name in different directories.

**Comment by staeff777** [comment]
If you compare the absolute filepaths, there is no problem except the comparison length of the path itself. I assume that this would still be fast.

**Comment by jarun** [comment]
> I assume that this would still be fast.

Absolute file paths can be 4K in length and if we have a 1000 of them it would no longer remain fast.

If you are really interested, check out commit 547d87bfc2caf276dd1bcb943677a0ca306c602d.

**Comment by staeff777** [comment]
The inode solution is quite clever. Nonetheless, a sorted insert is still fast enough, since  The 1000 will be reduced to 10 using a binary search. 

I did a test: 
Create a file with 160 000 Files using their complete path.
```
> cd /usr
> find "$PWD" -type f > /tmp/filelist.txt
> wc -l /tmp/filelist.txt
161092 /tmp/filelist.txt
```

shuffle the list, and then sort it
```
> shuf /tmp/filelist.txt > /tmp/shuffledlist.txt
>  time sort /tmp/shuffledlist.txt  > /tmp/sortedfilelist.txt
1.93user 0.02system 0:01.08elapsed 180%CPU (0avgtext+0avgdata 22296maxresident)k
```
initially, I wanted to just sort 1000 files, but the time was not measurable. 
This example was just to measure, how long a complete sort would take.

Now we add just one single line, into the sorted filelist, at the alphabetically correct position:
```
> time echo /usr/local/include/mpif-c-constants-decl.h | sort -m /tmp/sortedfilelist.txt - > /tmp/mergesort.txt
0.00user 0.00system 0:00.00elapsed 100%CPU (0avgtext+0avgdata 1980maxresident)
```
Sorting in a new line into a 160K line sorted file, is again extremely fast.

**Comment by jarun** [comment]
The memory usage would increase by 4K * 1000 which is approx. 4M right?

I think we will have to think of something else. The inode implementation is O(1). Can you please think of something in that line? I am also exploring on this.

**Comment by staeff777** [comment]
You don't need to read the whole file. If you know the linecount, you just take the middle line as a start for the [binary search](https://www.geeksforgeeks.org/binary-search/). 
Then the take the next line e.g. at position 3/4 and so on. For 1000 files you just need to access 10 lines at max.

**Comment by jarun** [comment]
> You don't need to read the whole file.

I think we should think of a way to make this work before writing to a file.

**Comment by jarun** [comment]
There would be issues with filename with newline chars if we write to a file and then try to manipulate it. I don't want to introduce that.

**Comment by jarun** [comment]
One correction. The file write happens later in `endselection()`. In `appendfpath()` we write to the buffer.

**Comment by staeff777** [comment]
You could use this aproach to find the line number at which the new file should be inserted. Then make a line by line copy and insert the new line at the corresponding line number.

The line by line copy might be a bottleneck, but I don't believe that.
