### ISSUE TITLE
Unable to delete files

### ISSUE THREAD

**Issue by Houkime** [jarun/nnn#264]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Arch Linux (Linux 5.0.13 kernel)
[x] Desktop Environment: dwm
[x] Terminal Emulator: termite
[x] Shell: bash
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

## Steps

* As a non-root user in a bash shell:

```
sudo pacman -S readline ncurses (you may also need base-devel for making stuff)
git clone https://github.com/jarun/nnn
cd nnn
make
touch filename
./nnn
```
* navigate to filename
* X

## Result

(on master) "check selection file permission"

## Note

Other FMs (namely ranger and pcmanfm) delete stuff just fine.

**Comment by jarun** [comment]
What's the output for `ls -l filename`?

For me it's:

```
$ ls -l filename
-rw-rw-r-- 1 vaio vaio 0 May 16 18:50 filename
```

and deletion works fine.

**Comment by jarun** [comment]
Ah OK. The shortcut to delete the current file is <kbd>^X</kbd>.

<kbd>X</kbd> is to delete selection.

**Comment by jarun** [comment]
I have added a patch for a more meaningful error message. Thanks for reporting the issue.

**Comment by Houkime** [comment]
Stupid me. Thanks. This should be better.

**Comment by jarun** [comment]
No problem! Don't forget to award a star if you like the utility! ;)
