### ISSUE TITLE
How to quit nnn and open shell in the selected directory?

### ISSUE THREAD

**Issue by impascal** [jarun/nnn#266]
[x] Operating System: Arch Linux
[x] Desktop Environment: i3-gaps (wm)
[x] Terminal Emulator: st (suckless terminal)
[x] Shell: bash
[ ] Custom desktop opener (if applicable): N/A
[ ] Issue exists on `nnn` master

I tried with ^G but it doesn't work: it only quit nnn.

**Comment by jarun** [comment]
See https://github.com/jarun/nnn/wiki/hacking-nnn#cd-on-quit.
