### ISSUE TITLE
Startup failure on non-existing ~/.config

### ISSUE THREAD

**Issue by vaygr** [jarun/nnn#268]
Didn't check on Linux, but on OpenBSD **v2.5** fails to start with this:

```text
# nnn 
4308: No such file or directory
```

if `~/.config` has not been created before.

#### Environment details

- [x] Operating System: OpenBSD
- [ ] Desktop Environment:
- [ ] Terminal Emulator:
- [x] Shell: ksh
- [ ] Custom desktop opener (if applicable):
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. make sure `~/.config` doesn't exist (e.g. `mv ~/.config ~/.config.orig`)
2. run `nnn`

**Comment by jarun** [comment]
Yes, `nnn` doesn't attempt to create the config directory. My understanding was `nnn` wouldn't be the first utility to use the dir. Do you see it as a fatal issue? Otherwise, we can add the patch for next release.

**Comment by jarun** [comment]
Also, at least for this release the installer script can create the directory if it doesn't exist.

**Comment by jarun** [comment]
We will redact this release. Thanks for the reporting this.

**Comment by jarun** [comment]
Fixed at commit b767d3335c8a624867dcd69bf41c3e522608c0d8.

**Comment by vaygr** [comment]
Awesome. Yeah, any installation/packaging procedure should avoid touching local configuration and it's usually discouraged. Unless it's global configuration in `/etc`, `/usr`, `/var`, `/opt`, etc.

**Comment by jarun** [comment]
I wanted to avoid that but as we saw on a fresh system it's unavoidable. But it's a fallback so we are good.
