### ISSUE TITLE
Odd behavior when opening files w/ xdg-open

### ISSUE THREAD

**Issue by rslindee** [jarun/nnn#269]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Arch
[x] Desktop Environment: bswpm
[x] Terminal Emulator: st
[x] Shell: zsh
[x] Custom desktop opener (if applicable): xdg-open
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
-Clone and build ("make debug") nnn 2.5
-Run "./nnn"
-Attempt to "open" README.md by highlighting and pressing "l" key
-Observe README.md opens in my web browser
-Quit out of nnn and instead run "xdg-open README.md"
-Observe README.md opens in vim, as expected

Also, when I attempt to open another file which does not have an xdg-open rule specified:
-Run "./nnn"
-Attempt to "open" CHANGELOG by highlighting and pressing "l" key
-Nothing happens, but now keyboard inputs to terminal pane running nnn are extremely slow (it seems as if every other keypress registers). This persists even after I exit nnn(!) until I kill the current terminal process.
-When I kill the terminal pane/process, I observe that suddenly the CHANGELOG file opens in my browser

[nnndbg.log](https://github.com/jarun/nnn/files/3225346/nnndbg.log)

**Comment by jarun** [comment]
Have you set `NNN_USE_EDITOR`?

I can see from the debug log that `nnn` uses `xdg-open` as the opener. I am not sure why `xdg-open` behaves differently in the 2 scenarios.

> Observe README.md opens in vim, as expected

Is it vim or gvim? How did you config `xdg-open` to open a file in `vim`?

**Comment by jarun** [comment]
I asked the `xdg-open` + `vim` config because `nnn` expects `xdg-open` to use GUI apps rather than terminal ones. That might be causing this problem.

You can also try setting `NNN_USE_EDITOR=1`.

**Comment by rslindee** [comment]
> Have you set `NNN_USE_EDITOR`?

Nope. Setting this to "1" appears to resolve the issue! Thank you.

> I can see from the debug log that `nnn` uses `xdg-open` as the opener. I am not sure why `xdg-open` behaves differently in the 2 scenarios.
> 
> > Observe README.md opens in vim, as expected
> 
> Is it vim or gvim? How did you config `xdg-open` to open a file in `vim`?

This was using vim.

Indeed, I think the xdg-open attempting to open terminal applications appears to be problematic. Why it is any different than calling "xdg-open file-i-typically-open-in-vim.txt" from the terminal is another issue.

Thank you for the quick resolution! I think I'm good from here.

**Comment by jarun** [comment]
My pleasure! Do award a star if you like the project.
