### ISSUE TITLE
[Feature Request] Keep vidir as an optional dependency

### ISSUE THREAD

**Issue by auFighil1** [jarun/nnn#270]
In a simple way, just revert the 'r' behaviour to the previous one if vidir is installed on the machine. My whole nnn usage has grown around vidir.

**Comment by jarun** [comment]
We have incorporated the functionality of `vidir` as a native feature. What's missing?

**Comment by auFighil1** [comment]
line numbers assigned to files, the relative path, file and empty folder deletion on line deletion.

**Comment by jarun** [comment]
It's true deletion is not supported, the reason being `nnn` natively supports deletion (relevant dev discussion [here](https://github.com/jarun/nnn/issues/213#issuecomment-492877827)).

The line numbers in vidir were specifically for deletion.

Relative path: I need to test if it's working or not. On a different machine now.

**Comment by auFighil1** [comment]
I know that nnn now natively supports deletion. My issue is that I now have to exit the editor. File manipulation now is somewhat incomplete. You can now only move and rename files in the editor. You could also make the same argument for the paths, ex. 'you don't really need paths since moving files is now implemented in nnn'.

**Comment by jarun** [comment]
Relative path works as expected. I tried to move a file using relating path and it worked.

**Comment by jarun** [comment]
You can just add a plugin to invoke `vidir` if you have a heavy use-case around it.

**Comment by auFighil1** [comment]
I've been using nnn ever since vidir got in. I cannot rebind 'r' without a patch. I'll have to press 'R' and then select the plugin everytime.

**Comment by jarun** [comment]
I am not asking you to have a new key to use vidir. The key for invoking plugins is a generic one. I I go by your argument no one would use plugins.

And the plugin framework was designed for user-specific extensions.

I hope you understand that if I support `vidir` I have to maintain some additional piece of code and also document the behavior both of which I want to avoid. Please get accustomed to the new key for plugin. I think you will need it more than you think going forward (not just for `vidir`).
