### ISSUE TITLE
Long file name is displayed incorrectly!

### ISSUE THREAD

**Issue by ruizone** [jarun/nnn#273]
测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试测试.txt
Long file name is displayed incorrectly. My test platform is termux

**Comment by ruizone** [comment]
https://www.dropbox.com/s/wnu4j3g0ur1jts9/TIM%E5%9B%BE%E7%89%8720190531185952.png?dl=0

**Comment by jarun** [comment]
ok, the status bar one.

**Comment by ruizone** [comment]
In the case of many files, it is very troublesome to select this file.

**Comment by ruizone** [comment]
The file name is not truncated and will cause the rename to fail.

**Comment by jarun** [comment]
what's your version of nnn?

**Comment by ruizone** [comment]
https://www.dropbox.com/s/w925f6zkbyfm1a9/TIM%E5%9B%BE%E7%89%8720190531191118.png?dl=0    The version I am using is 2.5

**Comment by ruizone** [comment]
https://www.dropbox.com/s/s2gv3gmzyvjry4q/TIM%E5%9B%BE%E7%89%8720190531193613.png?dl=0
Move the cursor up and down. The panel displays an error.

**Comment by jarun** [comment]
@ruizone the issue is [`wcswidth`](http://man7.org/linux/man-pages/man3/wcswidth.3.html) returns wrong length. It depends on locale. See the notes section:

```
NOTES         top
       The behavior of wcswidth() depends on the LC_CTYPE category of the
       current locale.
```



It seems Termux doesn't have locale support.

Please refer to https://github.com/termux/termux-packages/issues/2796#issuecomment-424589888

@fornwall does this still hold?

**Comment by jarun** [comment]
I also confirmed that this doesn't happen if I use a long file name with English characters only.

**Comment by fornwall** [comment]
@jarun It's true that `wcwidth()` and related functions does not work on Android prior to Android 9.0.

However, Termux has a `libandroid-support` library adding that function that programs can link against. I've enabled that for nnn (in version `2.5-2` of the package), so it should now work.

@ruizone Run `pkg up` to update and test again!

**Comment by jarun** [comment]
@fornwall I have tested it and this is fixed now! Thank you so much!

**Comment by ruizone** [comment]
@fornwall   The problem has been fixed very well. Thank you.
