### ISSUE TITLE
^P <Enter> cause Segmentation fault

### ISSUE THREAD

**Issue by ada-43** [jarun/nnn#274]
### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: devuan ascii
[x] Desktop Environment: xfce
[x] Terminal Emulator: tilda
[x] Shell: bash
[x] Custom desktop opener (if applicable): xdg-open
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. press ^P
2. press Enter

[nnndbg.log](https://github.com/jarun/nnn/files/3242863/nnndbg.log)

**Comment by jarun** [comment]
Please test master and confirm the patch works.

**Comment by ada-43** [comment]
Works fine, thank you.
