### ISSUE TITLE
black screen on start, can't kill by kill -9

### ISSUE THREAD

**Issue by valerijerlychenkov** [jarun/nnn#275]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Linux 5.0.13-arch1-1-ARCH x86_64
[x] Desktop Environment: awesome wm
[x] Terminal Emulator: urxvt (TERM = rxvt-unicode-256color)
[x] Shell: zsh 5.7.1 (x86_64-pc-linux-gnu)
[ ] Custom desktop opener (if applicable):
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
just start nnn as regular user

what I get:
black screen
no reaction on any keys

nnn totally ignore sudo kill -9

**Comment by jarun** [comment]
Logs please.

**Comment by jarun** [comment]
Can you please let us know the problem? It may help users who face the issue later.

**Comment by valerijerlychenkov** [comment]
On my machine after I start nnn
 `ls` stop working just freeze
strace -fp <pid> show nothing

after reboot nnn work's fine

how I can run nnn in debug mode next time?

**Comment by jarun** [comment]
Please check the wiki page on debugging `nnn`.
