### ISSUE TITLE
Segmentation fault after certain file appears

### ISSUE THREAD

**Issue by ada-43** [jarun/nnn#276]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: devuan ascii
[x] Desktop Environment: xfce
[x] Terminal Emulator: tilda
[x] Shell: bash
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. mkdir dir1
2. cd dir1
3. mkdir dir2
4. touch dir2/'01 - привет'
5. nnn
6. 2 (open context 2)
7. →(go to dir2)
8. ⎵ (select our file)
9. ←(go to dir1)
10. P (copy selection)
11. 1 (switch to context 1 in dir1)
12. Segmentation fault after 3 seconds.

**Comment by jarun** [comment]
Thanks! I will check this out.

**Comment by jarun** [comment]
Please test the patch and confirm the issue is indeed fixed.

**Comment by ada-43** [comment]
The issue is fixed. Thank you.
