### ISSUE TITLE
Build fails on NetBSD 7.1 due to missing set_escdelay

### ISSUE THREAD

**Issue by sjmulder** [jarun/nnn#277]
#### Environment details (Put `x` in the checkbox along with the information)

[ ] Operating System: NetBSD 7.1 (older but still maintained)
[ ] Desktop Environment: n/a
[ ] Terminal Emulator: n/a
[ ] Shell: sh
[ ] Custom desktop opener (if applicable): n/a
[ ] Issue exists on `nnn` master: unknown

#### Exact steps to reproduce the issue

1. Bootstrap pkgsrc on NetBSD 7.1
2. `cd sysutils/nnn; make`

```
gcc -I/usr/include -O2 -D_FORTIFY_SOURCE=2 -I/usr/include -Wall -Wextra -Wno-unused-parameter   -L/usr/lib -Wl,-R/usr/lib -Wl,-R/usr/pkg/lib -o nnn src/nnn.c -lcurses -lreadline
src/nnn.c: In function 'initcurses':
src/nnn.c:921:2: warning: implicit declaration of function 'set_escdelay' [-Wimplicit-function-declaration]
  set_escdelay(25);
```

I'll look into this properly later. Could be pkgsrc issue (matter of tweaking dependencies), or perhaps there's a better workaround.

**Comment by jarun** [comment]
I guess dep issue. We have [set_escdelay](https://linux.die.net/man/3/set_escdelay). Maybe a older version of `ncursesw` library?

**Comment by sjmulder** [comment]
Or a built in one that doesn't have it, but I'll have a look and try to come up with a good fix.

**Comment by jarun** [comment]
> Or a built in one that doesn't have it

In that case we should add the correct library from the repos as a dependency. I faced this on Termux for `nnn` before... not with a library but with `wget`. ;)

**Comment by sjmulder** [comment]
After some testing this does appear to be specific to NetBSD 7's older curses implementation. On other platforms, including NetBSD 8, OpenBSD and macOS the built in (wide) curses suffices so I've updated the package like so:

```diff
 USE_CURSES=	wide
+
+INCOMPAT_CURSES+=	NetBSD-[0-7].*-*
```

Now it'll use whatever wide curses library is available on every platform except NetBSD 7 where it'll avoid the built in one (and go for ncursesw).

This isn't a problem with nnn so I'll close this issue.

**Comment by jarun** [comment]
Thank you!
