### ISSUE TITLE
Build fails on SmartOS with various errors

### ISSUE THREAD

**Issue by sjmulder** [jarun/nnn#278]
#### Environment details (Put `x` in the checkbox along with the information)

[ ] Operating System: SmartOS
[ ] Desktop Environment: none
[ ] Terminal Emulator: n/a
[ ] Shell: unknown
[ ] Custom desktop opener (if applicable): n/a
[ ] Issue exists on `nnn` master: unknown

#### Exact steps to reproduce the issue

1. Bootstrap pkgsrc on SmartOS
2. `cd sysutils/nnn; make`

(A regular build may do but I haven't tested)

Full build logs: 
 - http://us-east.manta.joyent.com/pkgsrc/public/reports/upstream-trunk32/20190604.2010/nnn-2.5/build.log
 - http://us-east.manta.joyent.com/pkgsrc/public/reports/upstream-trunk32/20190610.2010/nnn-2.5/build.log
 - http://us-east.manta.joyent.com/pkgsrc/public/reports/upstream-trunk64/20190605.0210/nnn-2.5/build.log
 - http://us-east.manta.joyent.com/pkgsrc/public/reports/upstream-trunk64/20190611.0210/nnn-2.5/build.log

I'll start chipping away at these when I get SmartOS set up.

**Comment by jarun** [comment]
@sjmulder any update on this? It's been a while.

**Comment by sjmulder** [comment]
It’s a bit of a different kind of OS for me – haven’t got any experience with Solaris either. I’ll get there eventually but if you want to clear up your issues backlog feel free to close this.

**Comment by jarun** [comment]
I see. Yes, I'll close it in that case. Please raise a PR when you are done.

**Comment by jarun** [comment]
@sjmulder any update on this?

**Comment by sjmulder** [comment]
No, haven't worked on this yet.

**Comment by jarun** [comment]
No problem! Just checking out.
