### ISSUE TITLE
sshfs mount options

### ISSUE THREAD

**Issue by pat-s** [jarun/nnn#283]
Would be great if there could be an NNN env var which supports this. Thanks upfront!

**Comment by jarun** [comment]
Could you please raise a PR?

**Comment by pat-s** [comment]
No C exp but I'll see what I can do.

**Comment by pat-s** [comment]
Ok, I defined the env var and tried to pass it to

https://github.com/jarun/nnn/blob/c0bd33e3f61d0142ab66321c8bebf0a2ed5ec245/src/nnn.c#L2577-L2581

...but I just have no clue what I am actually doing here and how to check for the correctness of the options.

I guess that would be a quick one for you. 
Patiently waiting :) 

The initial motivation for the feature was [this option](https://superuser.com/a/197611/656138).

**Comment by jarun** [comment]
You can specify the option in the .ssh/config file. See https://unix.stackexchange.com/questions/50705/specifying-ciphers-and-protocol-2-in-ssh-config.

Please let me know if that solves your problem.

**Comment by pat-s** [comment]
Works, thanks! I assumed that this should be possible but wasn't successful in my research. Sorry for stealing your time...

**Comment by jarun** [comment]
No problem!
