### ISSUE TITLE
use force? [y|Y] is bad UX

### ISSUE THREAD

**Issue by Ordoviz** [jarun/nnn#287]
#### Environment details

[x] Issue exists on `nnn` master (not tested but I assume that)

#### Exact steps to reproduce the issue

Create a dummy file and press ^X. The prompt `use force? [y|Y]` appears. This is bad for several reasons:

- What action will be forced?
- It looks like y is the default option because it is uppercase. However, pressing Enter takes the user just to the next prompt on the command line.
- The user can choose between y and y. This makes no sense.

Better would be: `Delete <filename>? [y|N]`
Even better would be: `Deleted 1 file(s). Press u to undo` See [Never Use a Warning When you Mean Undo](https://alistapart.com/article/neveruseawarning/)

This could be implemented by delaying the actual deletion until the user performs the next action. Then the message disappears and the file gets actually deleted.

**Comment by jarun** [comment]
> This could be implemented by delaying the actual deletion until the user performs the next action.

File is not deleted before user provides input.

> Better would be: Delete <filename>? [y|N]

This is not to confirm delete, this is to confirm if the force option `-f` should be used with `rm`.

Also I want to convey this: Press `y` or `Y` to force, anything else to go interactive. I want to be as precise as possible so I have to use minimum number of characters. Let me know how you would do that.

**Comment by jarun** [comment]
I have changed the prompt to a more meaningful one

**Comment by Ordoviz** [comment]
OK, now I understand why the prompt looks like that. But I still think that it _should not_ be like that.

**Comment by jarun** [comment]
See the new one,

**Comment by Ordoviz** [comment]
The new prompt fixes some problems with the old one but it doesn’t fix this issue.

I think we should separate between deleting one entry and deleting multiple entries. For multiple entries going interactively can make sense to verify what will be deleted – for one entry it doesn’t. I would suggest:

**one entry:**
- message: `Deleted <entry name>. Press U to undo`

**multiple entries:**
- prompt: `Delete with force? [Y|n]` (where y is the default option)
- message: `Deleted <number> entries. Press U to undo`

The message remains until another key is pressed.

Or, if you don’t like the undo approach:

**one entry:**
- prompt: `Delete <entry name>? [y|N]`

**multiple entries:**
- prompt: `Delete with force? [y|N]` (where n is the default option)

**Comment by jarun** [comment]
I don't think you understand how `rm` works right now. There is no `undo`.

Also, at this point I can't spend so much effort into cosmetic stuff like differentiating between one file and multiple files.

**Comment by jarun** [comment]
I think the latest prompts are quite reasonable where we convey _press y or Y to confirm, anything else cancels the operation`.

If we show `y/N` or `Y/n` how do we convey `Y` also confirms? I am mentioning again and again the cancels means _everything other than_ `y/Y` and `N` is just one of those characters. Why do we have to show `N` in all prompts when _anything other than `y/Y` cancels_?

Do you realize that there is no standard to show these prompts? What may look reasonable to you may not be reasonable to me. Let's move on from this y/Y/n/N thing.

**Comment by Ordoviz** [comment]
Yeah, the “undo” is more like a “cancel”. I didn’t say that would be easy to do so I understand if that’s not a priority right now.

I think it’s important to indicate what pressing Enter will do (and y/N is a nice way to do that). I also don’t know why anyone would press shift+y when y is so much easier.

That’s all I had to say. Do whatever you prefer. I think we should end the discussion here.

**Comment by jarun** [comment]
> I also don’t know why anyone would press shift+y when y is so much easier.

Not on the smartphone. If someone enables uppercase for `X` (to remove files), it's easier for her to press `Y` in the prompt. So I treat `y` or `Y` as equivalent.

> I think we should end the discussion here.

Yep! I'm having a tough week already and I find it more and more hectic to keep maintaining open source software. No one contributes, lots of people have problems with lots of stuff...

Anyway, no hard feelings. I had tried to explain the current way of handling this as much as possible. I really don't have any bandwidth left to cater to these anymore.
