### ISSUE TITLE
quit and cd under fish shell

### ISSUE THREAD

**Issue by dangerware** [jarun/nnn#289]
It looks to me that in order for the `NNN_TMPFILE` variable to be available for the `nnn` process under the current fish session, one must `--export` it. I only got "quit and cd" working after doing this. Otherwise `nnn` would complain about it being missing when I `^G`.

So [instead of](https://github.com/jarun/nnn/blob/42a5479fa8e66be2c550f64572c2befd8653bc8d/misc/quitcd/quitcd.fish#L9):
```fish
nnn $argv
set NNN_TMPFILE ~/.config/nnn/.lastd
```
It should be:
```fish
set --export NNN_TMPFILE ~/.config/nnn/.lastd
nnn $argv
```

It must also be set before running the `nnn` child process.
Check the `-x` and `--export` switches on [`set` documentation](https://fishshell.com/docs/current/commands.html#set).

I'm more than happy to submit a PR if the authors find it OK.

#### Environment details
[x] Operating System: macOS 10.13.6 (High Sierra)
[x] Desktop Environment: Finder
[x] Terminal Emulator: iTerm2 (v3.2.9)
[x] Shell: fish (v3.0.2)
[ ] Issue exists on `nnn` master (haven't tested)

**Comment by UnicodeAlt255** [comment]
I just checked how I had it setup in my fish config, it looks like I changed `set NNN_TMPFILE` to `set -x NNN_TMPFILE` a long time ago. I can confirm this works on the latest commit of master as of typing.

**Comment by jarun** [comment]
Please test this on master. `nnn` now writes to `${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd` always and doesn't depend on the environment variable.

See commit fa4f082ac0d1789b10c7b8465c43aa083a5d82d6.

With this in place, I don't think we would need `set -x ...` anymore. This will be available in the next release.

**Comment by dangerware** [comment]
Thank you, @jarun. I'll test later and share what I've found, but that commit is clear enough for me. I'm going to close this for now, since I can always reopen if something's not working.

**Comment by jarun** [comment]
:+1:
