### ISSUE TITLE
xreadline behaves unexpectedly for some characters

### ISSUE THREAD

**Issue by tonimctoni** [jarun/nnn#290]
To reproduce:
- Have a file named "äbc.txt"
- Rename to "a.txt" with nnn

This problem arises when there is at least one wchar_t character that translates to more than one char character.

In xreadline
at wcstombs(g_buf, buf, ++len);
*++len* contains the length of the string in *buf* including the \x00 character at the end. If the wchar_t string in *buf* translates to a longer string in char, this longer string will be truncated to *++len*, which erases the \x00 character at the end.

I suggest replacing *wcstombs(g_buf, buf, ++len);* with *wcstombs(g_buf, buf, CMD_LEN_MAX);*, since wcstombs stops when encountering a \x00, so limiting the length when there is memory space to spare is overkill. I would further suggest that when the length of CMD_LEN_MAX is reached, to add a \x00 character at CMD_LEN_MAX to avoid undefined behaviour for long strings.

Furthermore, I think there might be a problem at *memmove(buf + pos + 1, buf + pos, (len - pos) << 2);*, since the length of wchar_t seems to not be defined in the standard, and could be less than four bytes in some implementations. Maybe replacing *(len - pos) << 2* with (len - pos)*sizeof(wchar_t) would be prudent.

**Comment by jarun** [comment]
The code has changed in master. Please take a look. Please test in master too.

I can't reproduce the issue in master. Are you able to reproduce in master?

> If the wchar_t string in buf translates to a longer string in char

Which translates to - there is a n-byte whar_t char which translates to a n+ byte char string. Which one?

> I would further suggest that when the length of CMD_LEN_MAX is reached, to add a \x00 character at CMD_LEN_MAX to avoid undefined behaviour for long strings.

It's already guarded at:

    if (pos < CMD_LEN_MAX - 1) {
        memmove(buf + pos + 1, buf + pos, (len - pos) << 2);

> since the length of wchar_t seems to not be defined in the standard

:+1:

**Comment by tonimctoni** [comment]
Thank you for the changes. I am sorry to bother you any further.

> > I would further suggest that when the length of CMD_LEN_MAX is reached, to add a \x00 character at CMD_LEN_MAX to avoid undefined behaviour for long strings.
> 
> It's already guarded at:
> 
> ```
> if (pos < CMD_LEN_MAX - 1) {
>     memmove(buf + pos + 1, buf + pos, (len - pos) << 2);
> ```

This guaranties that the string in *buf* stays within bounds with space to spare for the trailing \x00. However, *wcstombs(g_buf, buf, CMD_LEN_MAX);* may attempt to write into *g_buf* a string that is longer than the one in *buf*, which, if *CMD_LEN_MAX* is exceeded, will be truncated and not null-terminated.

**Comment by jarun** [comment]
You are right. I missed this earlier. Will fix. Thanks for being patient with me.

**Comment by jarun** [comment]
From `man wcstombs`,

```
size_t wcstombs(char *dest, const wchar_t *src, size_t n);
...
At most n bytes are written to dest.
```

So I think we are good if we do a

```
wcstombs(g_buf, buf, CMD_LEN_MAX - 1);
g_buf[CMD_LEN_MAX - 1] = '\0';
```
