### ISSUE TITLE
sshfs mount options, redux

### ISSUE THREAD

**Issue by xorander00** [jarun/nnn#291]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: FreeBSD 12.0-RELEASE-p6
[x] Desktop Environment: KDE/Plasma
[x] Terminal Emulator: Suckless Terminal
[x] Shell: ZSH
[x] Custom desktop opener (if applicable): N/A
[x] Issue exists on `nnn` master: #283

#### Exact steps to reproduce the issue

Trying to figure out how to specify SSHFS-specific options.  Issue #283 involved specifying an option for the ssh client.  However, arguments such as "-o idmap=user" cannot easily be specified in ~/.ssh/config since they're sshfs-specific (ssh client will complain).  ProxyCommand could probably be used to shoehorn the option into the command, but that's pretty hacky (assuming it could be done).  
  
If I can find the time in the near-term, I'll implement it myself and submit the PR.  I wanted to check here first though to see if there's an already-existing option that I might have missed.

**Comment by xorander00** [comment]
So I just tried doing it really quick and ran into some hurdles.  Unfortunately, I don't have the time do fix it up, but I'll see if I can come back to it in a couple of weeks.  What I found was as follows...  
  
- Adding NNN_* variables should probably be refactored to be easier.  Currently, it seems to be taking a preprocessor constant and using it as an index into a static array of strings for the environment variable name.  There's a Linux-specific ifdef block that conditionally adds a variable, which then causes the compiler to get confused because of the mismatched constant index ordinal.  I'm not exactly sure why it's all being done this way to begin with (I'm probably missing something), but it should probably be refactored into a cleaner method.  
  
- spawn() seems to be limited to two arguments, which won't work in this case.  I tried to snprintf an args string and then spawn "sh", "-c", args.  That failed however because I couldn't pass "-i" into sh in the hopes that it would load the required environment for it to work.  The fix for this seems to be to refactor the spawn() function to be a bit more flexible.  I could be missing something though as to why the function is limited to two arguments.  
  
- Other than that, everything else seemed to work fine.  I almost got it there, but just got stuck at spawning the process.  I did verify that sshfs and my environment was working properly, which it was.  
  
Anyway, that's the current status.  For now, I'm just going to manually use sshfs in another terminal before/while using nnn.  If anyone has any additional comments/feedback/pointers, please feel free to comment here.  Thanks!

**Comment by jarun** [comment]
You can pass multiple args to spawn. There's a flag to specify the first arg is a combo.

**Comment by xorander00** [comment]
@jarun So just pass the F_MULTI flag & then "sshfs" as the file, arg1 holding the full arguments string, & NULL for arg2?

**Comment by jarun** [comment]
I think so. Please refer to other places where we use F_MULTI now. I am not at my laptop now.

**Comment by jarun** [comment]
If you pass `F_MULTI` it means the first argument file is a combination of args e.g. `ls -l -t -r filename`. The limit is 7 agrs. In brief, you can pass the complete command.

**Comment by jarun** [comment]
Note that you can still pass arg1 and arg2 separately.

**Comment by jarun** [comment]
> Adding NNN_* variables

Since SSH is not a regular use case of many, I would suggest you add a new env var and call getenv() before issuing the ssh command.

**Comment by xorander00** [comment]
> If you pass F_MULTI it means the first argument file is a combination of args e.g. ls -l -t -r filename. The limit is 7 agrs. In brief, you can pass the complete command.  
  
> Note that you can still pass arg1 and arg2 separately.  
  
Does the 7 argument limit include the string passed into the file parameter, or is that total?  (I'd check the source to see the implementation, but can't currently)  
  
> Since SSH is not a regular use case of many, I would suggest you use a new env var and call getenv() before issuing the ssh command.  
  
Makes sense.  That's actually what I have implemented currently.  I first tried to add the \#define constant for the new environment variable, but because of the aforementioned indexing issue due to the \#ifdef linux, I just used a string in the sshfs_mount function body (for now).  
  
The potential issue with the arguments limit is that sshfs could feasibly cause the argument count to go over that limit.  It's not an issue for me, but just something to keep in mind for the future.  Either way, it's a moot point since it doesn't get much use.  
  
If you would like, I can fix up my code, test it, and submit a PR later.  If there's not much interest, then I won't worry about it.  
  
Thanks for the project, keep up the good work! :)

**Comment by jarun** [comment]
> Note that you can still pass arg1 and arg2 separately

I got this wrong last time. You can't.

> Does the 7 argument limit include the string passed into the file parameter

Total 10. FIlename, arg1, arg2, NULL make 4. So you have 6 params to pass. The code has a check to ensure the params are within the count.

Do you need more than 6?

**Comment by jarun** [comment]
If you need more, increase `EXEC_ARGS_MAX` (but keep it within a sane limit).

**Comment by xorander00** [comment]
For me, I don't think more than 6 is necessary.  I'm just contemplating for others that might use more than 6.  
  
The final command that I end up invoking is: "sshfs USER@HOSTNAME:. /path/to/mount/at -o reconnect -o idmap=user -o cache_timeout=3600"  
  
Those -o arguments can be collapsed into a comma-separated list, of course.  Also, some options that are not sshfs-specific (e.g. -o compression=yes -o ServerAliveInterval=10) are specified in ~/.ssh/config.  
  
It's not an issue for me, just exploring different approaches for implementation.

**Comment by jarun** [comment]
I think we should document this along with the limit and we should make it as compact as possible so other users can take a clue from the example.

Can you share your sample env variable?

What I thought we are going to do is: use the settings in `~/.ssh/config` and add what's passed by the env var on top of that. Are you following that or are you passing a complete sshfs command in the env variable?

**Comment by xorander00** [comment]
Essentially, I made changes to sshfs_mount:  
  
```c
// tmp was being killed for some reason, so I copied it for now.
char host[strlen(tmp)];
memset(host, '\0', sizeof(host));  // Probably not needed, but meh for now.
strcpy(host, tmp);   // Bad practice, change to strncpy or some variant.

// ...

char *opts = getenv("NNN_SSHFS_OPTIONS");
int spawnres = 1;

if (opts) {
   char args[strlen(host) + strlen(newpath) + strlen(opts) + 64];  // TODO: String length calc was wrong, fix this and remove the + 64
   memset(args, '\0', sizeof(args));  // Probably not needed.
   snprintf(args, sizeof(args), "'sshfs %s: %s %s'", host, newpath, opts);
   printf("%s", args);  // Not sure what the debugging facilities are, so using this for now.
   spawnres = spawn("sh", "-c", args, NULL, F_NORMAL);
} else {
   /* Convert "Host" to "Host:" */
   r = strlen(tmp);
   tmp[r] = ':';
   tmp[r + 1] = '\0';

   /* Connect to remote */
   spawnres = spawn("sshfs", tmp, newpath, NULL, F_NORMAL);
}

if (spawnres) {
   printwait("mount failed", presel);
   return FALSE;
}
```  
  
It's something like that anyway.  I just did a quick copy+paste.  I tried a few different approaches for the spawn() call.  "sh -c '...'", "sshfs", etc.

**Comment by jarun** [comment]
Can you give me a sample `NNN_SSHFS_OPTIONS` and a sample comma-separated list of args?

**Comment by jarun** [comment]
In addition to my last question, please confirm is the following syntax works:

    sshfs [options] [user@]host:[dir] mountpoint
Note that options is just after `sshfs`.

**Comment by xorander00** [comment]
> Can you give me a sample NNN_SSHFS_OPTIONS and a sample comma-separated list of args?  
  
Posted above in an above comment, but didn't wrap in a code block: ```sshfs USER@HOSTNAME:. /path/to/mount/at -o reconnect -o idmap=user -o cache_timeout=3600```  
  
I originally had the options coming before the remote host & local mountpoint arguments.  However, the [man page](https://www.freebsd.org/cgi/man.cgi?query=sshfs) (for both FreeBSD and Arch Linux), shows the options come after the remote host & local mountpoint arguments.  That does make it a bit easier since there can only be a single remote and a single local mountpoint.

**Comment by xorander00** [comment]
> Note that options is just after sshfs.  
  
Oh, I forgot to add that putting the options just after "sshfs", but before the remote host, does work.  However, I would prefer to follow the actual docs and intent of the app, even if it works the other way.

**Comment by jarun** [comment]
So NNN_SSHFS_OPTIONS is the complete command and not just the options?

Are the switches optional or positional? Do the docs clarify? If they are optional they can go anywhere I think.

**Comment by jarun** [comment]
And I don't see the comma separated example. I would like to have this as simplified as possible.

**Comment by xorander00** [comment]
Yeah, I was just doing a single string to make it easier & then go back later and revise it to break out into individual strings if necessary.  
  
The switches are optional, but if they exist, I think they need to go before the remote host argument.  
  
Comma-separated version of the above would be: ```-o reconnect,idmap=user,cache_timeout=3600```  
  
However, I'm not sure that imposing that requirement on the user would be ideal.  In this case, I don't think it even really matters since it's all basically going in as a single string, minus the executable name.

**Comment by jarun** [comment]
In your example, you are getting opts:

    char *opts = getenv("NNN_SSHFS_OPTIONS");

>  In this case, I don't think it even really matters

It does. We should avoid `sh -c` as much as possible. That's also the reason I would love to keep the number of params minimal.

Question:

If you have an entry for the host in `~/.ssh/config` and you pass additional options using the current mechanism, do all of them take effect? I am asking because you are using `user@hostname`. Can you have the user set in the config file, remove from the string and give it a try with the other options in the string?

I want to be 200% certain the options in the env var adds to the config file set options. The config file should not get ignored.

**Comment by jarun** [comment]
In addition, if the options do not depend on the position we have a simple solution:

Append comma-separated opts (to keep the number of args limited to 6) to the string `sshfs` and call `spawn()` with `F_MULTI`.

The position of the options can be after `sshfs`. Please see: https://wiki.archlinux.org/index.php/SSHFS

and the following line:

    Note: When providing more than one option for sshfs, they must be comma separated. Like so: 'sshfs -o sshfs_debug,IdentityFile=</path/to/key> user@server ...')

**Comment by jarun** [comment]
So if we have the following:

    export NNN_SSHFS_OPTS='sshfs -o reconnect,idmap=user,cache_timeout=3600'
we can simply call `spawn()` with this as first argument and `F_MULTI` leaving the rest intact. Can you test and confirm if this works with the entry for the host in `~/.ssh/config`?

**Comment by xorander00** [comment]
Sorry, been busy.  I can check this out sometime this week.
