### ISSUE TITLE
QuitCD for bash does not work since scripts where moved to misc

### ISSUE THREAD

**Issue by ppk42** [jarun/nnn#292]
FYI: Possibly error / typo in quitcd.bash

I copied the n() function that's implemented in the file ./misc/quitcd/quitcd.bash into a bash and  ran the function afterwards. nnn started but it did not quit after changing to another folder and pressing ^G. I saw a message "cd to ....".  

I recognized that, in the function the NNN_TMPFILE variable was reset after the call of the nnn executable. That makes no sense to me. 

In older versions of quitcd.bash there was an export NNN_TMPFILE=.... at the beginning of the file outside of the function. That makes sense to me.

The git history of the file is strange. The diff tool claims that the file was only moved to a new folder (misc) but there would be no other changes, but the last and the current version of the file obviously are different if you compare them by looking into both of them. (I'm not a github wizzard, so it's my fault possibly)

I don't know why these changes were implemented, so I can not give you a general solution (pull request).  I personally use the last version of the script, which works.

**Comment by jarun** [comment]
Use the last version of the script with master. We do not need to export anymore as nnn writes to a fixed file now.

**Comment by neowit** [comment]
Sorry to resurect this closed issue but the conclusion that `export NNN_TMPFILE` is no longer necessary may not be entirely accurate.

I am using ubuntu-18.04/bash under WSL (Windows Subsystem for Linux) on Windows 10 Pro.
`nnn` version 2.5 and latest version of [quitcd.bash](https://github.com/jarun/nnn/blob/master/misc/quitcd/quitcd.bash) added at the end of my ~/.bashrc


With `export NNN_TMPFILE` (in line 140 of my .bashrc, see screenshot below) **commented out** - i start nnn via `$ n`, navigate to a folder and press Ctrl+G. This results in `nnn` complaining with `set NNN_TMPFILE`

here is the relavant part of `.bashrc`
![image](https://user-images.githubusercontent.com/552057/60119400-415c1680-9776-11e9-95a1-c84e79c4a279.png)

here is what I get when press Ctrl+G
![image](https://user-images.githubusercontent.com/552057/60119259-e88c7e00-9775-11e9-8b3b-f1481f6d4a1d.png)

With `export NNN_TMPFILE` (in line 140 of my .bashrc shown above) uncommented - Ctrl+G works as expected

PS: this is my first comment in this repo and I just wanted to say that `nnn` is awesome. Thank you @jarun

**Comment by jarun** [comment]
Please try master. The latest quitcd scripts are compatible with master and not v2.5.

**Comment by neowit** [comment]
> The latest quitcd scripts are compatible with master and not v2.5.

Did not realise that. Thank you for the clarification.
