### ISSUE TITLE
File ownership

### ISSUE THREAD

**Issue by powelleric** [jarun/nnn#293]
Is there a way to show the file owner and group?

**Comment by jarun** [comment]
Use file details: <kbd>D</kbd>

**Comment by xtradev** [comment]
The details view in nnn 3.0-1 shows file time, permissions, size, and name; no owner or group. Can nnn be configured to show these details?

**Comment by jarun** [comment]
Please see https://github.com/jarun/nnn/issues/448#issuecomment-580953263 for the reason. Your use case is a bulk comparison. There is a plugin to show this in bulk for all the files in the dir.

**Comment by xtradev** [comment]
Thank you. Also owner and group for a file can be seen in a separate view by pressing `f`.

**Comment by jarun** [comment]
Yes, that's another way.
