### ISSUE TITLE
Commit 46aa0ad breaks single-click selection

### ISSUE THREAD

**Issue by eugene55** [jarun/nnn#314]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Archlinux Linux zotac 5.2.5-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 31 08:30:34 UTC 2019 x86_64 GNU/Linux
[x] Desktop Environment: dwm
[x] Terminal Emulator: alacritty, st
[x] Shell: bash
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
* Single click on any file list entry. There is no visible feedback -- ISSUE
* Press Ctrl + L to repaint. Selection appears

**Comment by jarun** [comment]
Commit 46aa0ad.

**Comment by jarun** [comment]
Thank you for reporting this issue. Please test the patch and confirm it works.

**Comment by eugene55** [comment]
Confirmed. Issue is fixed
