### ISSUE TITLE
img and video thumbnails

### ISSUE THREAD

**Issue by eirenicon** [jarun/nnn#317]
I am running 2.6.1 on MX Linux 18.3 (Debian 9 based) in bspwm current release. 
`[code]
System:    Host: mark-dell Kernel: 5.1.11-antix.1-amd64-smp x86_64 bits: 64 compiler: gcc v: 6.3.0 
           Desktop: bspwm 0.9.2 Distro: MX-18.3_x64 Continuum Feb 9  2019 base: Debian GNU/Linux 9 (stretch) 
Machine:   Type: Laptop System: Dell product: Latitude E5470 v: N/A serial: <filter> 
           Mobo: Dell model: N/A serial: <filter> UEFI [Legacy]: Dell v: 1.18.6 date: 12/08/2017 
Battery:   ID-1: BAT0 charge: 40.4 Wh condition: 45.1/62.0 Wh (73%) model: LGC-LGC4.20 DELL HK6DV status: Unknown 
CPU:       Topology: Dual Core model: Intel Core i5-6300U bits: 64 type: MT MCP arch: Skylake rev: 3 
           L2 cache: 3072 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 19968 
           Speed: 1744 MHz min/max: 400/3000 MHz Core speeds (MHz): 1: 2900 2: 2902 3: 2900 4: 2903 
Graphics:  Device-1: Intel HD Graphics 520 vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 
           Display: x11 server: X.Org 1.19.2 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 520 (Skylake GT2) v: 4.5 Mesa 18.3.2 direct render: Yes 
Audio:     Device-1: Intel Sunrise Point-LP HD Audio vendor: Dell driver: snd_hda_intel v: kernel bus ID: 00:1f.3 
           Sound Server: ALSA v: k5.1.11-antix.1-amd64-smp 
Network:   Device-1: Intel Ethernet I219-LM vendor: Dell driver: e1000e v: 3.2.6-k port: f040 bus ID: 00:1f.6 
           IF: eth0 state: down mac: <filter> 
           Device-2: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter vendor: Dell driver: ath10k_pci 
           v: kernel port: f040 bus ID: 01:00.0 
           IF: wlan0 state: up mac: <filter> 
           Device-3: Atheros type: USB driver: btusb bus ID: 1-8:5 
Drives:    Local Storage: total: 1008.18 GiB used: 588.08 GiB (58.3%) 
           ID-1: /dev/mmcblk0 model: SD32G size: 30.09 GiB 
           ID-2: /dev/sda vendor: Crucial model: CT1050MX300SSD4 size: 978.09 GiB temp: 32 C 
RAID:      Hardware-1: Intel 82801 Mobile SATA Controller [RAID mode] driver: ahci v: 3.0 bus ID: 00:17.0 
Partition: ID-1: / size: 952.05 GiB used: 588.08 GiB (61.8%) fs: ext4 dev: /dev/sda1 
           ID-2: swap-1 size: 9.81 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda2 
Sensors:   System Temperatures: cpu: 66.0 C mobo: 47.0 C sodimm: 38.0 C 
           Fan Speeds (RPM): cpu: 2525 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/antix.list 
           1: deb http://la.mxrepo.com/antix/stretch stretch main
           Active apt repos in: /etc/apt/sources.list.d/debian-stable-updates.list 
           1: deb http://ftp.us.debian.org/debian/ stretch-updates main contrib non-free
           Active apt repos in: /etc/apt/sources.list.d/debian.list 
           1: deb http://ftp.us.debian.org/debian/ stretch main contrib non-free
           2: deb http://security.debian.org/ stretch/updates main contrib non-free
           Active apt repos in: /etc/apt/sources.list.d/megasync.list 
           1: deb https://mega.nz/linux/MEGAsync/Debian_9.0/ ./
           Active apt repos in: /etc/apt/sources.list.d/mx.list 
           1: deb http://mxrepo.com/mx/repo/ stretch main non-free
           Active apt repos in: /etc/apt/sources.list.d/skype-stable.list 
           1: deb [arch=amd64] https://repo.skype.com/deb stable main
           No active apt repos in: /etc/apt/sources.list.d/various.list 
           No active apt repos in: /etc/apt/sources.list.d/virtualbox.org.list 
Info:      Processes: 179 Uptime: 2h 32m Memory: 23.22 GiB used: 1.78 GiB (7.7%) Init: SysVinit runlevel: 5 
           Compilers: gcc: 6.3.0 Shell: bash v: 4.4.12 inxi: 3.0.33 
[/code]
`
I am able to view image thumbnails, but each image I have to access directly and it opens a 'feh' image.  Is that the functionality as designed/ implemented? If so, okay.

As for viedeos, I get no thumbnails and whenever I select a video, the system attempts to use ffmpeg to convert the files (mp3 or wav have been tested).

I'm probably doing something wrong but I have no idea what that might be.

**Comment by 0xACE** [comment]
Your message is difficult to comprehend. I interpret it as:

1. You are able to view thumbnails for images (I'm guessing you are using `sxiv` or some `sixel` based alternative)
2. When you open the image it opens in `feh`
3. If you are using `sxiv` or `sixel` to view thumbnails. I'm not sure any of those tools supports thumbnails for videos.

To address your problems:

1. I guess there isn't a issue here. (If you want to see thumbnails you can use `sxiv` or `sixel`)
2. `nnn` most likely uses `xdg-open` to open files on your pc. If you don't want to use `feh` to open your images you need to change the default for `xdg-open` (I can't help with it as I find `xdg-query` very annoying to use) (Or you could set the environment variable `NNN_OPENER`)
3. Video thumbnails doesn't exist for `sxiv` or `sixel` as far as I know. But there could be scripts out there that handle these types of things.

Also note your problem seems to be a support issue and not really a "problem" per se for the program.

**Comment by jarun** [comment]
If you open the image directly within `nnn` it will open in your default file manager.

In-terminal view/thumbnails of images is supported through plugins. To summarize , you have the following plugins:

- `viuimg` - view images in the terminal
- `thumb` - shouw thumbnails in the terminal using lsix

There's also the `sxiv` plugin. Using `sxiv` you can see thumbnails.

**Comment by jarun** [comment]
Closing the issue with the above information.
