### ISSUE TITLE
Hindi translation

### ISSUE THREAD

**Issue by nimeshneema** [jarun/nnn#318]
I came across this post on Reddit India:

- https://www.reddit.com/r/india/comments/cnx0q7/help_with_documentation_in_hindi_for_open_source/

I can contribute my knowledge and time to help with Hindi translation. Let me know how to get started.

**Comment by jarun** [comment]
Please feel free to pick up any utility (`ddgr` or `Buku` would be good to start with). Let me know which one you want to start with and I will add you as a collaborator to the project. You can create a new Wiki page for the project and start.

**Comment by jarun** [comment]
Thanks a lot for responding. I wasn't very sure anyone would want to contribute.

Also, feel free to take your time. We are not on a deadline.

**Comment by nimeshneema** [comment]
Sure. Give me some time to go through the utilities and pick one.

**Comment by jarun** [comment]
I am closing the defect. Please pick a project and we can continue the discussion in the ToDo list.

**Comment by jarun** [comment]
Are you still interested in doing this?

**Comment by nimeshneema** [comment]
Yes. I got occupied elsewhere and was not able to take a look. Let me get started.

**Comment by nimeshneema** [comment]
@jarun I'd like to get started. Is there a private channel/medium to communicate?

**Comment by jarun** [comment]
Sure! We can discuss here. I am re-opening the issue. Public discussions would help people interested in this.

**Comment by jarun** [comment]
You can also ping me at https://gitter.im/jarun/nnn

**Comment by jarun** [comment]
Gitter is fine.
