### ISSUE TITLE
nnn blocks when opening a file

### ISSUE THREAD

**Issue by AcarBurak** [jarun/nnn#319]
> I wish I could open a file and still be able to use nnn or close nnn without closing a file.

_Originally posted by @Rahi374 in https://github.com/jarun/nnn/issues/1#issuecomment-330132574_

I still have this issue on Arch/Fluxbox (v. 2.5) with both mimeopen and xdg-open.

**Comment by jarun** [comment]
`nnn` uses the above flags:

    /* Invoke desktop opener as last resort */
    spawn(opener, newpath, NULL, NULL, F_NOTRACE | F_NOWAIT);

And I can't reproduce this on Ubuntu with `xdg-open`. So I can't add any patch for it.

**Comment by AcarBurak** [comment]
I've read a discussion about an env variable, NNN_NOWAIT, but seemingly it's been dropped. Would you consider it again if it's a solution?

**Comment by jarun** [comment]
It's already there by default: https://github.com/jarun/nnn/blob/master/src/nnn.c#L3608

So we need to know why this is happening. If you see the current code, `nnn` doesn't wait for the forked process if the `F_NOWAIT` flag is passed.

**Comment by jarun** [comment]
Do you have `NNN_USE_EDITOR` in your environment variables?

**Comment by jarun** [comment]
And is it happening for all files or only text files?

**Comment by AcarBurak** [comment]
Yes, I have.

It seems to occur only with geany (geany with session).

**Comment by jarun** [comment]
> It seems to occur only with geany (geany with session).

I don't use Geany. I have mousepad and it works just fine. I don't think I can help here. Doesn't look like an `nnn` issue. Please try to debug yourself.

**Comment by 0xACE** [comment]
@AcarBurak could you provide what exactly you are trying to do?

If you open a CLI tool it will most likely be run on top of `nnn`, I guess there isn't much to do about this other than spawning it in another shell or introducing another "run and exit" feature.

If it's a GUI app it shouldn't be a problem. One guess I have is that the first `geany` session remains in a CLI mode or maybe `geany` does this everytime? What happeens if you `geany myfile.c` will it block your terminal?

It doesn't seem to be a `nnn` issue so far...

**Comment by 0xACE** [comment]
Btw incase `geany` is blocking 1 trick I commonly do which I can share with you is:

`export PATH=~/pre-bin:$PATH:~/bin`

Usually I put my scripts in `~/bin`, but sometimes I want to overwrite some other programs. For example I like to run `feh` with special flags so i created `~/pre-bin` like so:

```
#!/usr/bin/env sh
/usr/bin/feh --zoom-max "$@"
```

So now when I open a image in `feh` it runs with my parameters. My point is, what happens if you add a `&` to `~/pre-bin/geany`:

```
#!/usr/bin/env sh
/usr/bin/geany "$@" &
```
