### ISSUE TITLE
Symlink to directory moved to where it points when name isn't changed when using batch rename

### ISSUE THREAD

**Issue by KlzXS** [jarun/nnn#320]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Arch Linux 5.1.12-arch1-1-ARCH #1 SMP PREEMPT Wed Jun 19 09:16:00 UTC 2019 x86_64 GNU/Linux
[ ] Desktop Environment:
[ ] Terminal Emulator:
[x] Shell: bash, zsh
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

- Open nnn
- Enter batch rename while selecting at least one symlink pointing to a directory
- Leave the name of the symlink unchanged, saving or discarding changes to other names
- Symlink is now moved to where it was pointing
Happens as a result of `mv`-ing a symlink into inself. Symlinks pointing to files aren't affected.

**Comment by 0xACE** [comment]
btw @jarun I think this is partly related to the time I broke my `$HOMEDIR` when i accidentally started a `batch-rename`

**Comment by jarun** [comment]
At least on Ubuntu I'm not able to reproduce this. @0xACE do you see this on Arch Linux?

**Comment by jarun** [comment]
OK. I can now.

**Comment by jarun** [comment]
Please test the patch and confirm it works.

**Comment by KlzXS** [comment]
It doesn't work. Still moves the symlink to where it's pointing if there doesn't already exist a file with the same name.
