### ISSUE TITLE
v2.6 - Broken search

### ISSUE THREAD

**Issue by rufusshrestha** [jarun/nnn#323]
#### Environment details (Put `x` in the checkbox along with the information)

[ ] Operating System: Ubuntu 16.04 LTS
[ ] Desktop Environment: Unity
[ ] Terminal Emulator: Terminal
[ ] Shell: zsh, bash
[ ] Custom desktop opener (if applicable):
[ ] Issue exists on `nnn` master v2.6

#### Exact steps to reproduce the issue

nnn -d
/ (to search)
type something to see UI broken (bottom half of the UI shows files)

![image](https://user-images.githubusercontent.com/25457508/62945681-91746280-be22-11e9-844e-859461f64355.png)

**Comment by jarun** [comment]
I am unable to reproduce this issue on v2.6. Can you confirm if master and v2.5 has this problem?

Is there a segfault? Is this happening in any directory or just this directory? That can tell us if there's any _special_ file that's leading to this problem.

**Comment by jarun** [comment]
And what's `uni`? Do not use abbreviations others may not understand.

**Comment by rufusshrestha** [comment]
HI Jarun,

Sorry, I think we should close this case as its limited to my terminal:
I'm using Byobu with tmux and Guake on zsh with oh-my-zsh

Appears something else is interfering.

Native terminal seems fine.

**Comment by jarun** [comment]
Thanks for confirming.
