### ISSUE TITLE
Plugin submission: Organize

### ISSUE THREAD

**Issue by th3lusive** [jarun/nnn#326]
I would like to contribute a small script that I made whch would arrange files based on their file type into folder categories.

Demo:
![Before](https://i.imgur.com/zKJS3S8.png)

![After](https://i.imgur.com/jS3MBue.png)

Code:
https://gitlab.com/snippets/1887030

EDIT:

```sh
#!/bin/sh
# organize - Place files into folder categories
organize() {
    case "$(file -biL "$1")" in
        *video*)
            [ ! -d "Videos" ] && mkdir "Videos"
            mv "$1" "Videos/$1"
            printf "Moved %s to Videos\n" "$1" ;;

        *audio*)
            [ ! -d "Audio" ] && mkdir "Audio"
            mv "$1" "Audio/$1"
            printf "Moved %s to Audio\n" "$1" ;;

        *image*)
            [ ! -d "Images" ] && mkdir "Images"
            mv "$1" "Images/$1"
            printf "Moved %s to Images\n" "$1" ;;

        *pdf*|*document*)
            [ ! -d "Documents" ] && mkdir "Documents"
            mv "$1" "Documents/$1"
            printf "Moved %s to Documents\n" "$1" ;;

        *text*)
            [ ! -d "Plaintext" ] && mkdir "Plaintext"
            mv "$1" "Plaintext/$1"
            printf "Moved %s to Plaintext\n" "$1" ;;

        *tar*|*xz*|*compress*|*7z*|*rar*|*zip*)
            [ ! -d "Compressed" ] && mkdir "Compressed"
            mv "$1" "Compressed/$1"
            printf "Moved %s to Compressed\n" "$1" ;;

        *binary*)
            [ ! -d "Binaries" ] && mkdir "Binaries"
            mv "$1" "Binaries/$1"
            printf "Moved %s to Binaries\n" "$1" ;;
    esac
}

main() {
    for file in *
    do
        organize "$file"
    done
}

main "$@"

```

**Comment by jarun** [comment]
@th3lusive thanks for sharing. Can you please paste the script here?

@KlzXS can you please review the script?

**Comment by jarun** [comment]
@th3lusive here's a sample plugin you can follow and update your script:

https://github.com/jarun/nnn/blob/master/plugins/vidthumb

To elaborate, I am looking for a snippet that's ready to submit so we can pick and drop it in the plugin directory.

**Comment by KlzXS** [comment]
@th3lusive You may want to change the script so it doesn't try to move the folders around. On the first run with no folders it work fine, don't know if you sorted gzip and bzip2 into compressed on purpose or accident though. On the second run it moved all folders into Binaries.

Also change the shebang to `#!/usr/bin/env sh`

**Comment by th3lusive** [comment]
@KlzXS Thank you for reviewing my script. I updated it to check that its a file first before it is moved and also changed the shebang. Also, gzip and bzip2 were intented to go into compressed. Is that classification correct? 

@jarun Confirmed that it works fine when run from the plugins folder.

[Updated snippet](https://gitlab.com/snippets/1887030).

```sh
#!/usr/bin/env sh
# Description: Place files into folder categories
#
# Shell: POSIX compliant
# Author: th3lusive

organize() {
    case "$(file -biL "$1")" in
        *video*)
            [ ! -d "Videos" ] && mkdir "Videos"
            mv "$1" "Videos/$1"
            printf "Moved %s to Videos\n" "$1" ;;

        *audio*)
            [ ! -d "Audio" ] && mkdir "Audio"
            mv "$1" "Audio/$1"
            printf "Moved %s to Audio\n" "$1" ;;

        *image*)
            [ ! -d "Images" ] && mkdir "Images"
            mv "$1" "Images/$1"
            printf "Moved %s to Images\n" "$1" ;;

        *pdf*|*document*)
            [ ! -d "Documents" ] && mkdir "Documents"
            mv "$1" "Documents/$1"
            printf "Moved %s to Documents\n" "$1" ;;

        *text*)
            [ ! -d "Plaintext" ] && mkdir "Plaintext"
            mv "$1" "Plaintext/$1"
            printf "Moved %s to Plaintext\n" "$1" ;;

        *tar*|*xz*|*compress*|*7z*|*rar*|*zip*)
            [ ! -d "Compressed" ] && mkdir "Compressed"
            mv "$1" "Compressed/$1"
            printf "Moved %s to Compressed\n" "$1" ;;

        *binary*)
            [ ! -d "Binaries" ] && mkdir "Binaries"
            mv "$1" "Binaries/$1"
            printf "Moved %s to Binaries\n" "$1" ;;
    esac
}

main() {
    for file in *
    do
        [ -f "$file" ] && organize "$file"
    done
}

main "$@"

```

**Comment by KlzXS** [comment]
Now it does what is says it should.

@th3lusive I ask about gzip and bzip2 because I saw that they weren't on the list but I guess zip was. I don't know what you classify epub as but the script puts it in compressed since its mime is application/epub+zip. I have no preference either way on this, I would just like to make sure you know that.

**Comment by jarun** [comment]
> # Description: Place files into folder categories

Can we change it to:

    # Description: Organize files into directories by category

Also, can we change

    [ ! -d "Compressed" ] && mkdir "Compressed"
    mv "$1" "Compressed/$1"
    printf "Moved %s to Compressed\n" "$1" ;;

to

    [ ! -d "Archives" ] && mkdir "Archives"
    mv "$1" "Archives/$1"
    printf "Moved %s to Archives\n" "$1" ;;

**Comment by th3lusive** [comment]
@KlzXS  I added epub, as well ass, djvu and comic book files to the Documents directory.

@jarun This naming does seem much more appropriate.

Please see changes below :)

[Updated Snippets](https://gitlab.com/snippets/1887030)

```sh
#!/usr/bin/env sh

# Description: Organize files in directories by category
#
# Shell: POSIX compliant
# Author: th3lusive

organize() {
    case "$(file -biL "$1")" in
        *video*)
            [ ! -d "Videos" ] && mkdir "Videos"
            mv "$1" "Videos/$1"
            printf "Moved %s to Videos\n" "$1" ;;

        *audio*) [ ! -d "Audio" ] && mkdir "Audio"
            mv "$1" "Audio/$1"
            printf "Moved %s to Audio\n" "$1" ;;

        *image*)
            [ ! -d "Images" ] && mkdir "Images"
            mv "$1" "Images/$1"
            printf "Moved %s to Images\n" "$1" ;;

        *pdf*|*document*|*epub*|*djvu*|*cb*)
            [ ! -d "Documents" ] && mkdir "Documents"
            mv "$1" "Documents/$1"
            printf "Moved %s to Documents\n" "$1" ;;

        *text*)
            [ ! -d "Plaintext" ] && mkdir "Plaintext"
            mv "$1" "Plaintext/$1"
            printf "Moved %s to Plaintext\n" "$1" ;;

        *tar*|*xz*|*compress*|*7z*|*rar*|*zip*)
            [ ! -d "Archives" ] && mkdir "Archives"
            mv "$1" "Archives/$1"
            printf "Moved %s to Archives\n" "$1" ;;

        *binary*)
            [ ! -d "Binaries" ] && mkdir "Binaries"
            mv "$1" "Binaries/$1"
            printf "Moved %s to Binaries\n" "$1" ;;
    esac
}

main() {
    for file in *
    do
       [ -f "$file" ] && organize "$file"
    done
}

main "$@"

```

**Comment by jarun** [comment]
Also, instead of repeating the directory names (with the chance of spelling mistakes), can we use variables like - VID, AUD, IMG, DOC, TXT, ARC, BIN? I think that would be visibly clearer too.

**Comment by jarun** [comment]
I think we can skip the variables for dir thing.

**Comment by jarun** [comment]
The plugin `organize` is in at commit b9530a5ce0eb727ec9833259f6b939de84d65a7c.
