### ISSUE TITLE
Checksum plugin: read command doesn't wait for input

### ISSUE THREAD

**Issue by eugene55** [jarun/nnn#328]
#### Environment details (Put `x` in the checkbox along with the information)

[ ] Operating System:
[ ] Desktop Environment:
[ ] Terminal Emulator:
[x] Shell: dash
[ ] Custom desktop opener (if applicable):
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Open any checksum file with checksum plugin.
See error in shell: `checksum: 52: read: arg count`

Addition of argument to read command, as describer here: `stackoverflow.com/questions/15744421/read-command-doesnt-wait-for-input` fixes the issue for dash

**Comment by KlzXS** [comment]
@jarun the script is full of probelms.

- Not all systems have `md5sum` and such, some BSDs go without the `sum` part
- It's not POSIX compliant, `xargs` doesn't support `-i`
-  This issues with `read`

@eugene55 feel free to rewrite the script to fix some of these issues. It if works submit a PR. This is not an issue on most Linux distros so people won't be in a hurry to fix it.

**Comment by jarun** [comment]
@eugene55 kindly fix the problems and submit a PR.

**Comment by jarun** [comment]
@KlzXS & @eugene55 

> Not all systems have md5sum and such, some BSDs go without the sum part

Scripts are there for users to modify and use for their needs. They are indicative. If the system doesn't have a utility, they'll have to modify accordingly. The `Deps` column in the plugin table is specifically for that. This isn't our problem to solve.

> It's not POSIX compliant, xargs doesn't support -i

This needs to be fixed.

> This issues with read

This needs to be fixed.

Also, please wrap this up as soon as possible.

**Comment by eugene55** [comment]
Sure thing. I can work on a thing on a weekend

**Comment by jarun** [comment]
Cool! We'll wait for the PR. Thank you!

**Comment by jarun** [comment]
The patch seemed a minor one so I took care of it.

@KlzXS please review the patch.
