### ISSUE TITLE
Add option to set pager

### ISSUE THREAD

**Issue by NightMachinary** [jarun/nnn#331]
I have set `LESS` to `-RiNF`, which makes `less` close itself if the output is less than one screen. I need a way to define the pager manually for nnn, sth like `--pager="more"`.

**Comment by jarun** [comment]
export PAGER='less -RiNF'

**Comment by lsnch** [comment]
Is there a way to set it to `bat` only for the `p` button? `alias nnn="PAGER=bat nnn"` works, but subshells inherit that environment as well (which screws up man pager, for one).

**Comment by annagrram** [comment]
You can use NNN_PLUG to define a keybinding to a plugin that opens a file with `bat`.
