### ISSUE TITLE
Progress bar macOS

### ISSUE THREAD

**Issue by jhsta** [jarun/nnn#333]
It seems on macOS `^T` doesn't work to show progress bar when moving files. Now it toogle nav-as-you-type. Is option to show progress bar was removed from nnn?

**Comment by 0xACE** [comment]
I don't have a mac so I can't try it out.

But 1 question I have for you: Are you hitting `^T` while the file is being copied/moved? because afaik, thats the only time you can click it

**Comment by jarun** [comment]
0xACE is correct. In `nnn` `^T` is mapped to toggle _nav-as-you-type_. You'll have to press `^T` while cp/mv is in progress to see the progress of the operation.

**Comment by jarun** [comment]
Closing the issue as the use case is clarified.
