### ISSUE TITLE
Standard SI/IEC units?

### ISSUE THREAD

**Issue by lpar** [jarun/nnn#340]
Any chance of an option to use and display [standard SI/NIST/IEC units](https://en.wikipedia.org/wiki/Binary_prefix)?

**Comment by jarun** [comment]
`nnn` follows only the binary (IEC) standard. So the initials letters you see represent the respective prefixes.

**Comment by lpar** [comment]
That's confusing because the abbreviated prefix is a valid prefix for a different value. I'd like the prefix shown to match the actual value.

**Comment by jarun** [comment]
I'd like to have more space for the filename than trivia. I will document this.

**Comment by lpar** [comment]
Then why not use base-10 units, since those are what disks are measured in anyway by the manufacturers?

(I don't care which units are used, I just want them indicated accurately.)

**Comment by jarun** [comment]
I think the middle ground is we simply state that `nnn` follows JEDEC which uses the _prefix symbols K, M, G and T in the binary sense_.

**Comment by lpar** [comment]
"NOTE 2 The definitions of kilo, giga, and mega based on powers of two are included only to reflect common usage. IEEE/ASTM SI 10‑1997 states "This practice frequently leads to confusion and is deprecated." — [JEDEC](https://www.jedec.org/standards-documents/dictionary/terms/mega-m-prefix-units-semiconductor-storage-capacity)

**Comment by jarun** [comment]
What's shown in `nnn` is the same as `ls` default. Here's an excerpt from the `ls` manpage:

```
The SIZE argument is an  integer  and  optional  unit  (example:  10K  is  10*1024).  Units  are
       K,M,G,T,P,E,Z,Y (powers of 1024) or KB,MB,... (powers of 1000). Binary prefixes can be used, too: KiB=K, MiB=M, and so on.
```

All users of `ls` understand this nomenclature. `nnn` follows the same.

If you have an issue with that, please have your own fork.
