### ISSUE TITLE
Recently opened documents ?

### ISSUE THREAD

**Issue by amanjitsk** [jarun/nnn#341]
How about a recently opened documents feature as in more traditional gui-based file managers like nautilus ? Documents opened from `nnn` do not seem to store history in some applications such as zathura, so it would be nice if something like this would be possible (via a plugin potentially) ?

Thanks,
Amanjit

**Comment by jarun** [comment]
> do not seem to store history

@amanjitsk none of @jarun's projects store user history or track them. However, this can be done easily.

`nnn` uses `xdg-open` (or the default opener in you DE) which in all probability would be a script. Full-time `nnn` users can always write a wrapper over `xdg-open` or `mimeopen` to _optionally_ store the path in a user-specific file and have a plugin to feed the list to `fzy` and open those (again, with `xdg-open` without using the option to store the path).
