### ISSUE TITLE
Cant install nnn_2.7-1_ubuntu18.04.amd64.deb on Ubuntu 19.04

### ISSUE THREAD

**Issue by mayowa** [jarun/nnn#346]
#### Environment details (Put `x` in the checkbox along with the information)

[X] Operating System: Ubuntu 19.04
[X] Desktop Environment: Gnome 3.32.1
[] Terminal Emulator:
[ ] Shell:
[ ] Custom desktop opener (if applicable):
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
```
sudo dpkg -i ~/Downloads/nnn_2.7-1_ubuntu18.04.amd64.deb

dpkg: dependency problems prevent configuration of nnn:
 nnn depends on libreadline7; however:
  Package libreadline7 is not installed.

dpkg: error processing package nnn (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 nnn
```
I've tried to install libreadline7 but its not available in the repos for 19.04

Thanks

**Comment by mayowa** [comment]
I was able to compile form source. Should I close this issue?

**Comment by jarun** [comment]
We have auto-generation enabeld only for LTS releases of Ubuntu. SO 19.04 is not added in the matrix.

Closing the issue.

BTW, if possible please share the commands to compile from source on 19.0 here for future reference.

**Comment by mayowa** [comment]
I didn't do anything special. I followed the instructions from https://github.com/jarun/nnn#from-source.
The only issue was for some strange reason I had to purge libncursesw5-dev & apt install --fix-broken before reinstalling it.
