### ISSUE TITLE
first impression as a new user

### ISSUE THREAD

**Issue by sucrecacao** [jarun/nnn#349]
#### Environment details (Put `x` in the checkbox along with the information)

[x ] Operating System: debian
[ x] Desktop Environment: i3
[x ] Terminal Emulator: gnome-terminal
[x] Shell: bash
[ ] Custom desktop opener (if applicable):
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

fresh install of nnn by adding new ppa repo.

first I want to say that is very hard for a beginer to read the doc, most usefull info ( like all the keybinding ) are not in the begining, no quickstart tutorial . The context feature is weird:
The first time I tab it will ask me if I want to create new context, then tab will switch between context. But how can I create a new context now ? 
I would expect space to also unselect selected files and if I select two files and switch context, the files are not selected any more which feels weird.

Anyway, I wanted to share that the first step with it can be a bit painfull but the software looks very nice and I can wait to understanding it well :) <3

**Comment by jarun** [comment]
> most usefull info ( like all the keybinding ) are not in the begining, no quickstart tutorial
> But how can I create a new context now ?

which doc did you refer to? I think you missed the project README.

> if I select two files and switch context, the files are not selected any more which feels weird

Yes, they can be retained if `nnn` keeps a snapshot of the directory in memory or does string matching for all files everytime you open a directory. To do those it would have to sacrifice on performance and/or resource usage.

> I wanted to share that the first step with it can be a bit painful

`nnn` is not like traditional file managers. If you are finding it painful to use I would suggest you use a traditional one where the workflows would be familiar without any surprises.
