### ISSUE TITLE
Add setting to change default for exiting back to nnn working directory

### ISSUE THREAD

**Issue by Sevensidedmarble** [jarun/nnn#350]
We had this discussion on Reddit a few days ago. I think it'd be great to be able to have a setting so we could set whether we want the *default* behaviour when exiting the shell to be changing to nnn's current directory. This is almost exclusively what I use ranger for so it'd be cool to see this in nnn.

**Comment by Sevensidedmarble** [comment]
@jarun if this isn't too hard I wouldn't mind trying to help out with it, I haven't had a ton of Go experience and I'd like to practice more.

**Comment by jarun** [comment]
@0xACE @KlzXS this is about honoring `NNN_TMPFILE` always if it is set. Should we make it the default behavior or have a config for it?

**Comment by KlzXS** [comment]
I see no reason not to make it the default, if you're copying things over into your shell config you probably want it to be the default behavior.

**Comment by jarun** [comment]
And what if a user who has this setting wants to quit and end-up in the initial directory? That flexibility will be lost.

@Sevensidedmarble say you have 3 contexts open. Currently `q` is the key to close a context. I don't want to change that binding. However, I can change the behavior so when you press `q` `q` `q`, you'll end up in the working directory. Is that acceptable?

Of course, if you press `Q` or `^Q` or `^G` also you'll end up in the working directory.

**Comment by KlzXS** [comment]
Wouldn't that add an extra delay when exiting for people who don't want to use that feature?

**Comment by jarun** [comment]
> Wouldn't that

Which one?

**Comment by KlzXS** [comment]
Triple pressing q. You would need to add a delay to allow the user to enter it multiple times. I just don't know how noticable that would be.

**Comment by jarun** [comment]
No. You don't need to press thrice all the time. `q` is to quit the current context. So I was citing en example where 3 contexts are open. `q` closes a context so user has to press `q` thrice in this example. If there's only one context, pressing `q` once with quit to current directory (as per proposed behavior).

**Comment by jarun** [comment]
All I am trying to convey is - we will change the directory where you end up after you quit `nnn`, but we will not change the behaviour associated with the keybind.

**Comment by KlzXS** [comment]
Ok, I don't use this and instead just drop into the shell so I'll leave it to you to figure out what should be done. All I want is to be able to quit nnn without dropping into the current directory.

**Comment by jarun** [comment]
> All I want is to be able to quit nnn without dropping into the current directory.

You start in dir `x` and navigate to dir `y`. Now if you quit `nnn` do you want to drop in `x` or `y`?

@Sevensidedmarble wants to drop in `y`.

**Comment by KlzXS** [comment]
I want to stay in `x`.

**Comment by jarun** [comment]
OK. I think I have found a easy way to achieve both.

**Comment by jarun** [comment]
Please test the patch.

`nnn` now has an additional check for `NNN_TMPFILE`. If set, it will write the last working dir to `.lastd` file.

To return to initial dir on quit, export `NNN_TMPFILE` after the call to `nnn`.

**Comment by KlzXS** [comment]
Confirming that it works.

**Comment by jarun** [comment]
Thanks!

**Comment by 0xACE** [comment]
I have spent 10 minutes reading the patch and trying to figure it out... What exactly have you changed?

It doesn't seem personally important to me, but if you want me to review it I have to understand it... Otherwise it's safe to ignore it for now...

**Comment by jarun** [comment]
Ignore for now! It's pretty simple but means a lot for people who like to drop in the final dir.
