### ISSUE TITLE
New file interface is inconvenient on narrow screens

### ISSUE THREAD

**Issue by s-mage** [jarun/nnn#351]
#### Environment details (Put `x` in the checkbox along with the information)

[ v ] Operating System: macOS
[ ] Desktop Environment:
[ v ] Terminal Emulator: iterm2
[ v ] Shell: bash
[ ] Custom desktop opener (if applicable):
[ v ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Open nnn on a narrow screen (20% or screen in vim in my case, but it's the same in plain terminal, I checked), click `n` to create new file. Start to type file name.

<img width="401" alt="Screenshot 2019-10-11 at 13 03 00" src="https://user-images.githubusercontent.com/2388396/66647917-7c515f80-ec2a-11e9-98d5-1650f8704964.png">

When space ends, nothing happens. I can type, but I can't see what am I typing.

I'd like the line to move left when I type, so I could see what am I entering.

**Comment by jarun** [comment]
I have made changes to shorten the prompt for new file/dir to just "name: ".
If that's not sufficient, please raise a PR for this.
