### ISSUE TITLE
Update SESSIONS_VERSION to 1 before next release

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#365]
See title.

**Comment by jarun** [comment]
Note 2: dependency on `findutils` for `xargs` removed. Notify maintainers.

**Comment by jarun** [comment]
@annagrram can you please locally test and confirm when we bump the session version, users who have already created sessions with master have their sessions working?

**Comment by annagrram** [comment]
Without testing I can say it won't work by design

**Comment by jarun** [comment]
OK, I see why in the code. But why don't we attempt backward compatibility?

**Comment by annagrram** [comment]
We can try, but it requires a bit more design, work, checks and headaches :P

**Comment by jarun** [comment]
I understand. Let's do one thing. Can we have an extra byte in the header start that holds the number of items stored? That way we will have some info later on how many items we need to load. Now if we retain the order of store and load we will always remain backward and forward compatible even if we extend the number of items we store later.

**Comment by jarun** [comment]
Rather than the number of items stored I should call it the number of items intended for storing... because sometimes the strings can be NULL and we will have no data for it other than lenth info (that it's 0).

**Comment by jarun** [comment]
@annagrram I think we are OK with what we have, even if it's hard. The bottleneck is settings, if we change flags, it wouldn't work.

**Comment by annagrram** [comment]
Yeah.
There are ways to make structs extendable and therefore backward compatible, but they are either non-standard or ugly.

**Comment by jarun** [comment]
:(

**Comment by jarun** [comment]
Added this in the ToDo list.

**Comment by maximbaz** [comment]
> Note 2: dependency on findutils for xargs removed. Notify maintainers.

I see `xargs` being used in `src/nnn.c`, what did you mean by this?

By the way, I maintain the package for Arch Linux now, if you keep a list of maintainers somewhere make sure to add me in 😉

**Comment by jarun** [comment]
> I see xargs being used in src/nnn.c, what did you mean by this?

`xargs` has multiple sources - GNU xargs, BSD xargs, Busybox xargs other independent POSIX xargs. Now even the most minimal `xargs` would work with `nnn`.

> if you keep a list of maintainers somewhere make sure to add me in

Sure! You'll get the notis I send on new releases.
