### ISSUE TITLE
`show_help` problems in the BSDs

### ISSUE THREAD

**Issue by annagrram** [jarun/nnn#366]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: FreeBSD 12.0-RELEASE-p10 / OpenBSD 6.6
[ ] Desktop Environment:
[ ] Terminal Emulator:
[x] Shell: tcsh / ksh
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

The arrow symbols in `show_help` don't display correctly on FreeBSD and OpenBSD ttys, which also result in a warning when trying to open the help that the tmp file might be binary and asks if we are sure we want to open it.
Moreover, in FreeBSD, for some reason, the `fortune` binary exists in the base install but no fortunes are installed, so combined with the problem above, we are also presented with an error from the invocation of `fortune`

**Comment by jarun** [comment]
@annagrram 

> Moreover, in FreeBSD, for some reason, the fortune binary exists in the base install but no fortunes are installed, so combined with the problem above, we are also presented with an error from the invocation of fortune

Is there an easy way to detect that no fortunes are installed? I would really love to have this.

**Comment by jarun** [comment]
How about having a program switch to make it conditional (disabled by default)?

**Comment by jarun** [comment]
Added optional fortune in commit 54d25807999282bf1d6ed282be3f38efcdf5bad0.

**Comment by annagrram** [comment]
> @annagrram
> 
> > Moreover, in FreeBSD, for some reason, the fortune binary exists in the base install but no fortunes are installed, so combined with the problem above, we are also presented with an error from the invocation of fortune
> 
> Is there an easy way to detect that no fortunes are installed? I would really love to have this.

No idea.
I can check if you'd like.
Or does your commit already takes care of it?

**Comment by jarun** [comment]
> Or does your commit already takes care of it?

It does! :+1:
