### ISSUE TITLE
What's the ^ key?

### ISSUE THREAD

**Issue by alexx-oo** [jarun/nnn#367]
Sorry for this stupid question. But I didn't find ^ symbol works. For example, ^G to quit,  I press shift + 6 (so that it is ^) and then G( shift + g to ensure it is uppercase). The result is to go the last entry which is G function not ^G function.

May I know how to press the ^  with other keys?

Many thanks!

**Comment by annagrram** [comment]
^G means Ctrl+G :)

**Comment by alexx-oo** [comment]
Got it, It works! Thanks!

**Comment by jarun** [comment]
For reference: https://en.wikipedia.org/wiki/Control_key#Notation
