### ISSUE TITLE
Checksum (plugin) for directory

### ISSUE THREAD

**Issue by aryadovoy** [jarun/nnn#369]
Could you add this option? It's useful for checking, when you're copying lots of files in folders.
Thanks.

**Comment by jarun** [comment]
Please elaborate.

**Comment by jarun** [comment]
The `checksum` plugin works with selection already. So you need to press `a` to select all files in dir and run the plugin.

**Comment by jarun** [comment]
If you are interested, please extend the plugin to calculate the checksum of all the files in a hovered directory of selected directory.

**Comment by jarun** [comment]
@KlzXS adding you as well.

**Comment by aryadovoy** [comment]
> The `checksum` plugin works with selection already. So you need to press `a` to select all files in dir and run the plugin.

When you have lots of folders and subfolders, it isn't easy to select all files of folder.

**Comment by jarun** [comment]
Please test the updated plugin and confirm it works as expected.

Note that the changes don't apply to directories in a selection.

**Comment by KlzXS** [comment]
I would love to test this new plugin, but I can't run any plugins. Starting with 60dac94 when I try to run a plugin it just erases the thing at the bottom (are we calling it a status bar?), and stays that way until a valid keybind is pressed.

I'll look into it tomorrow, just letting you know of this potential issue.

**Comment by jarun** [comment]
> when I try to run a plugin

please provide some more details. I'm not seeing this.

**Comment by aryadovoy** [comment]
> Please test the updated plugin and confirm it works as expected.
> 
> Note that the changes don't apply to directories in a selection.

Hah, I've checked.  I got checksum for each file, but didn't for whole directory.

**Comment by jarun** [comment]
Is checksum calculated for a directory?

```
$ md5sum nnn
md5sum: nnn: Is a directory
```

**Comment by aryadovoy** [comment]
> Is checksum calculated for a directory?
> 
> ```
> $ md5sum nnn
> md5sum: nnn: Is a directory
> ```
No, that is the question. :)
I used `find . -name '*' -exec cat {} \; 2>/dev/null | md5sum`, but I got different results on different devices for one dir.

**Comment by jarun** [comment]
Are the results different for individual files? Where's this _directory issue_ coming form?

**Comment by aryadovoy** [comment]
No, for files everything's OK.
I needed to check, that all files from Android device was copied to debian server, so I tried to use checksum for whole directory. Now I'm installing nnn on termux for getting list of checksums and after that I'll compare 2 checksum files.

**Comment by jarun** [comment]
I see. Please debug yourself and raise a PR to patch the script _if you find any issues_. This is quite generic and I can't spend any more time on this.

**Comment by aryadovoy** [comment]
Ok, thanks!
But now plugin is better, than yesterday version. :)

**Comment by aryadovoy** [comment]
Actually, checksum plugin doesn't work on Termux. :(

**Comment by jarun** [comment]
- which checksum did you try?
- are the deps installed?
- do you see any error message?

**Comment by aryadovoy** [comment]
I used plugin and nothig was happened, so I couldn't choose type of checksum.
What deps? I install from repo and copy plugins in `~/.config/nnn`, checked by `R`-key — correct.
No, just refreshing screen.

**Comment by jarun** [comment]
Plugins should be in `~/.config/nnn/plugins`.

**Comment by aryadovoy** [comment]
Yes, I copied `plugins` dir, so they are there.

**Comment by jarun** [comment]
Do you see the plugins when you press `R`?

**Comment by jarun** [comment]
I use the Termux environment myself and I can't reproduce it.

**Comment by aryadovoy** [comment]
I uploaded video: https://youtu.be/87W0bLOyqWM

**Comment by jarun** [comment]
I can't figure the problem from the video. Are you on master or v2.7 released?

@annagrram does this look related to https://github.com/jarun/nnn/pull/368?

@0xACE any ideas?

**Comment by jarun** [comment]
@aryadovoy can you go to your plugins directory, run the following commands and share the output?

- `pwd`
- `ls`

**Comment by aryadovoy** [comment]
`~/.config/nnn/plugins  pwd
/data/data/com.termux/files/home/.config/nnn/plugins
 ~/.config/nnn/plugins  ls
README.md  fzy-open   kdeconnect  nwal        readit     uidgid
boom       getplugs   mediainf    oldbigfile  ringtone   upgrade
checksum   gutenread  moclyrics   organize    splitjoin  vidthumb
drag-file  hexview    mocplay     pastebin    suedit     viuimg
drop-file  imgresize  ndiff       pdfview     sxiv
dups       imgur      nmount      picker      thumb
fzcd       ipinfo     notes       pywal       transfer`

**Comment by jarun** [comment]
@aryadovoy Are you on master or v2.7 released?

**Comment by jarun** [comment]
If you have installed `nnn` using apt-get you are on v2.7. If you have cloned the project from GitHib and compiled it then you are on master.

**Comment by jarun** [comment]
Looks like you are on v2.7 from the help screen.

**Comment by aryadovoy** [comment]
> @aryadovoy Are you on master or v2.7 released?

No, I couldn't `make` master on Termux like debian making, I installed from repo.

**Comment by jarun** [comment]
I installed v2.7 from the repo and can't reproduce the issue.

Please try to compile master in debug mode (instructions in README). We can then see if the logs show the correct location of plugins dir. That seems like the only option now.

**Comment by jarun** [comment]
Also, one more clarification I need. Are you facing problem with `R` key? Or are you facing problem with directly running the checksum plugin?

Please explain your procedure step by step.

**Comment by jarun** [comment]
I tried the following:

Hovered on a directory -> Pressed `^V` -> hovered on plugin `checksum` and pressed `Enter` -> Entered `m` at prompt.

The checksum was generated correctly.

**Comment by jarun** [comment]
I also tried the following:

`export NNN_PLUG='c:checksum'`

Hovered on a directory -> Pressed `:c` -> Entered `m` at checksum prompt (for md5).

This also worked correctly.

Is any other plugin working for you?

**Comment by aryadovoy** [comment]
I tried both ways, but nothing.
Debug mode:
![Screenshot_20191101-215532__01](https://user-images.githubusercontent.com/26593349/68045270-867af100-fcf2-11e9-9587-5536d2762833.jpg)
And didn't try another plugins.

**Comment by 0xACE** [comment]
you are missing clang or some buildtool i guess

**Comment by aryadovoy** [comment]
> you are missing clang or some buildtool i guess
Yeah, you're right.
I installed master, but nothing was changed.

**Comment by jarun** [comment]
Please share the debug log.

**Comment by annagrram** [comment]
> @annagrram does this look related to #368?

Sorry. I missed that until now.
I don't think it's related especially if he works on v2.7 :).

@aryadovoy, Just to make sure, how did you install the plugins and what is the output of `ls -l` in the plugins directory?

**Comment by jarun** [comment]
He shared the output in an earlier response.

**Comment by annagrram** [comment]
> He shared the output in an earlier response.

Of `ls` not `ls -l`.
I suspect he installed the plugins in a way that removed the executable permission of the file.

**Comment by jarun** [comment]
From the video it looked like the plugins are not even listed. Which is why I ruled out the not-executable file possibility.

**Comment by aryadovoy** [comment]
Yeah, you're right. I changed permissions and now it works! But it strange, cause I use `curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh` for install.

**Comment by jarun** [comment]
I have updated the docs to emphasize on the executable aspect.
