### ISSUE TITLE
setup_config doesn't setup paths properly

### ISSUE THREAD

**Issue by KlzXS** [jarun/nnn#373]
#### Environment details (Put `x` in the checkbox along with the information)

[ ] Operating System:
[ ] Desktop Environment:
[ ] Terminal Emulator:
[ ] Shell:
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Debug output:
```
VERSION=2.7
home=/home/[user]
xdgcfg=/home/[user]/.config
cfgdir=/home/[user]/.config
cfgdir=/home/[user]/.config
plugindir=/home/[user]/.config
cfgdir=/home/[user]/.config
sessiondir=/home/[user]/.config
cfgdir=/home/[user]/.config
g_selpath=/home/[user]/.config/.selection
opener=xdg-open
getenv(envs[VISUAL])=vim
getenv(envs[EDITOR])=vim
editor=vim
pager=less
shell=/bin/bash
getenv("PWD")=/home/[user]/nnn
idletimeout=0
ts2.tv_nsec - ts1.tv_nsec=141156
```

Obviously `plugindir` and `sessiondir` don't point to the correct path.
It's a problem with how the strings are copied, where instead of getting `/home/[user]/.config/nnn/plugins` I get `/home/[user]/.config\0/nnn/plugins`. There is an extra `\0`! 

This problem was introduced with 60dac94a5e3727d7c8bf0f02f3d6f8b53f8d1d02 where some offsets were changed by 1 in `setup_config()`.

**Comment by annagrram** [comment]
😫 This function and all of its hardcoded magic numbers is a headache.
I'll try to take a look at it later today if no one else beats me to it.

**Comment by jarun** [comment]
Please use macros for the path lengths. When I implemented it I didn't expect the function to change so much.

As for the issue, it may be related to the fact that xstrlcpy returns the length including NULL. Please check.

**Comment by jarun** [comment]
Happens only if `XDG_CONFIG_HOME` is defined.

**Comment by KlzXS** [comment]
This still needs to be fixed.

**Comment by jarun** [comment]
I have added additional comments beside the hacky numbers to indicate what we are doing. I will try to simplify at some point.
