### ISSUE TITLE
Filename handler bug

### ISSUE THREAD

**Issue by combucho** [jarun/nnn#376]
NNN can't open pdf with zathura-mupdf while filename consists with one or more Cyrillic symbols.

#### Environment details (Put `x` in the checkbox along with the information)

[x ] Operating System: Archlinux
[x] Desktop Environment: i3
[x] Terminal Emulator: Termite
[x] Shell: zsh
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
File *example.pdf* normally opens via NNN. Rename *example.pdf*
```bash
cp ./example.pdf ./ййй.pdf
```
Open it with zathura and it works.
```bash
zathura ./ййй.pdf
```
Try to open it via nnn - not works.

**Comment by jarun** [comment]
hi, I'm not keeping well. I will take some time to get to this.

Anyone else is more than welcome to check it out in the meantime.

**Comment by jarun** [comment]
I just tried this and the file opens correctly for me. 

What's your locale setting?

Did you try master? I added a patch recently in this flow.

**Comment by combucho** [comment]
```bash
~ locale          
LANG=ru_RU.UTF-8
LC_CTYPE=ru_RU.UTF-8
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE=ru_RU.UTF-8
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=

~ localectl status
   System Locale: LANG=ru_RU.UTF-8
       VC Keymap: ru
      X11 Layout: us,ru
     X11 Variant: ,
```

I used 2.7-1 version from archlinux community repo. Build date 10 oct 2019. 23:03:29.

Now I trying master from gihub, still not working. :(

**Comment by 0xACE** [comment]
I just want to confirm, `nnn` is successfully opening `./ййй.pdf`.

Meaning, it's most likely your machine that is setup in correctly.

Try putting this:
```
#!/usr/bin/env bash
echo -n "[ "
for arg in "$@"; do
            echo -n "{$arg} "
    done
    echo "]"
```
somewhere in the `$PATH` before your pdf viewer, you could for example: `export PATH="~/pre-bin:$PATH"` and save that script as `~/pre-bin/mupdf`

and see how the arguments got split...

**Comment by jarun** [comment]
Which opener do you use? `nnn` invokes the desktop opener to open files. Also, are you able to open the file correctly while navigating from `nnn`?

**Comment by combucho** [comment]
You are right. It's not `nnn` problem, but It's related to environment localization or smth. Filename parameter is passed in an unreadable form. `file://~/Ð¹Ð¹Ð¹.pdf`

Thus, I changed `zathura` to `evince` in `~/.config/mimeapps.list` with same issue,  then checked desktop entries at `/usr/share/applications/` and changed applications exec key from `%U` to `%F` according to freedesktop spec. 

Now it works. Thanks a lot for your advises.
