### ISSUE TITLE
Reverse file name order

### ISSUE THREAD

**Issue by QasimK** [jarun/nnn#377]
As I understand the default ordering of `nnn` is by file name, A -> Z. Is there any way to reverse the order, i.e. Z -> A?

I have tried searching help, man page, and the GitHub issues, readme and wiki, but cannot find any mention of reversing the order.

Is this possible? Is this documented anywhere?

**Comment by 0xACE** [comment]
Unfortunately, there isn't. The reasoning behind why it wasn't implemented was that you could simply scroll to the end of the list and see the reverse order... There is a key to jump to the first file which i think is mapped to `,'` which will help if you are looking for the last directory...

(too lazy to type it out, I hope you can figure it out based on my description.)

**Comment by jarun** [comment]
@0xACE has explained it correctly.

**Comment by QasimK** [comment]
Thanks for the explanation. I suppose I can live with scanning up the file list :smiley:
