### ISSUE TITLE
Sync subshell PWD to nnn

### ISSUE THREAD

**Issue by z0rc** [jarun/nnn#380]
Midnight Commander has a nice default feature: mc's subshell current working directory is kept in sync with mc itself. For example, you start mc, switch to subshell, cd to another directory in subshell and exit back to mc, the mc will be in that directory.

mc does this by default, no user configuration needed. It archives this by adding precmd function to the subshell, which sends pwd updates back to mc. See implementation details at https://github.com/MidnightCommander/mc/blob/master/src/subshell/common.c#L810.

It would be nice for nnn to implement this feature.

**Comment by jarun** [comment]
Sorry, no plans to interpret shell commands run by user.

**Comment by annagrram** [comment]
@z0rc You can write a plugin that does just that and let the plugin change the directory in nnn.

**Comment by z0rc** [comment]
@annagrram Is there a way to change dir in running nnn from other process?

**Comment by annagrram** [comment]
> @annagrram Is there a way to change dir in running nnn from other process?

Yes. It's new in master and should be released in the next version.
You can read about it [here](https://github.com/jarun/nnn/blob/master/plugins/README.md)

**Comment by jarun** [comment]
@annagrram just wondering if the _Controlling nnn's active directory_ section should go to the wiki. What do you say?

**Comment by annagrram** [comment]
Well, it's tightly coupled with the plugins' mechanism, so plugin knowledge is mandatory in order to achieve this, but I guess it can't hurt to put it there as well.

**Comment by jarun** [comment]
Maybe add a small subsection in the wiki and link the plugin readme from there. So it would be available to people exploring the wiki.

**Comment by jarun** [comment]
We have a solution in #860.
