### ISSUE TITLE
Files deletion with a single keybind ?

### ISSUE THREAD

**Issue by jediafr** [jarun/nnn#390]
#### Environment details (Put `x` in the checkbox along with the information)

[x ] Operating System: manjaro
[x] Desktop Environment: Kde
[x] Terminal Emulator: terminator
[x] Shell:bash

#### Exact steps to reproduce the issue

Hi i've discovered your program through YT.

After installation, i cant delete files straight (pressing shift+X) , i have to select the file first with space bar then confirm each deletion by pressing Y.
Is there a way to delete with a single keybind  (without having to confirm) ?

**Comment by KlzXS** [comment]
You can delete a single files or directory you are hovering over by pressing `^X` (that is `Ctrl-X`). If you want to delete more files at once you have to select all of them, you can use `m` for range selection. You will always be asked if you wish to forcibly remove files.

**Comment by jarun** [comment]
Link to the relevant docs: https://github.com/jarun/nnn/wiki#selection
