### ISSUE TITLE
Not writing to NNN_TMPFILE

### ISSUE THREAD

**Issue by x0054** [jarun/nnn#391]
Hi,

I have `nnn` compile from source on fresh Ubuntu 19.04 VM. I am trying to use the cd on exit feature, however, there appears to be an issue with writing to the temp file.

```
$ export NNN_TMPFILE="/tmp/nnntest"
$ nnn    // press Q or ^G to quit
$ cat /tmp/nnntest
> cat: /tmp/nnntest: No such file or directory
```

I thought that maybe it can't write to the file for some reason.

```
$ touch /tmp/nnntest
$ chmod 777 /tmp/nnntest
$ export NNN_TMPFILE=/tmp/nnntest
$ echo $NNN_TMPFILE
> /tmp/nnntest
$ nnn     // press ^G or Q to quit (I tried both)
$ cat $NNN_TMPFILE
>            // Nothing, the file is empty
```

I don't understand what's wrong. It appears to work for everyone else, but I cannot get it working at all :( I am reluctant to call it a bug, but not sure what else to try.

**Comment by x0054** [comment]
After compiling in debugging mode and playing around a bit I figured out that `nnn` stores the last dir in `~/.config/nnn/.lastd`. However, this means that it's ignoring the NNN_TMPFILE environment variable.

**Comment by 0xACE** [comment]
I don't have time to check on this until sunday or monday night (maybe even tuesday) (but at least until wednesday)....

i did quickly search for `NNN_TMPFILE` in the source code and it only appears in https://github.com/jarun/nnn/blob/3b42b6fc42ce762ebb7fdb9849b8c5a48b88d02f/src/nnn.c#L5305 , and `write_lastdir` doesn't seem to reference it either...

**Comment by jarun** [comment]
> However, this means that it's ignoring the NNN_TMPFILE environment variable.

Yes, `NNN_TMPFILE` is fixed for a few releases already. Now it's just an indication to `nnn` whether to quit on CD or not. The exposed env vars are here: https://github.com/jarun/nnn#usage

I'll update the script to indicate this.
