### ISSUE TITLE
Tiny issue list

### ISSUE THREAD

**Issue by Brixy** [jarun/nnn#394]
```
version: 2.8
MacOS Catalina
also tested master branch: yes
```

Thank you very much for the super-cool 2.8 version.

I noticed a few things.

# 1

It is possible to double-select items after using `K` to edit the selection and accidentally delete deselected files.

**Steps to reproduce:**

- `a`
- `K` (remove one item)
- `a`
- unselect one item using `space`
- `X` will *delete* the item we unselected in the step before.

# 2

After using `K` the `+` symbol gets lost.

# 3

It seems to be only possible the archive the current file.

**Steps to reproduce:**

- Select two or more files/folders
- `f`
- press `s` for “selection”
- Enter name and confirm

Only the current file will be archived.

# 4

This may be a setup issue: But for me `set NNN_TRASH 1` (using fish shell) does not work. I also tested it with ZSH. `trash` is installed.

---

I am a (passionate nnn) user, not a programmer. So excuse me if my list above does not make sense ;-)

**Comment by jarun** [comment]
Thank you for the tests and your time. I will take a look once I am back at my workstation.

**Comment by KlzXS** [comment]
### 1:
I'm unable to reproduce this and I think I don't fully get which files you're selecting and deselecting.

### 2:
This is the intended behavior. The `+` is there only until the selection is used, edited or the directory has changed.

### 3:
I can reproduce this. I'll submit a PR.

### 4:
I don't have trash setup. Someone else should take a look.

**Comment by maximbaz** [comment]
### 1:

I can reproduce it but I think it's by design. Let me first clarify repro steps:

```
$ mkdir -p /tmp/test
$ cd /tmp/test
$ touch {1,2,3}
$ nnn
```

* `a`
* `K` - delete `/tmp/test/2`, save and exit
* `a`
    * currently if you press `K`, selection will contain `1,3,1,2,3`, but @Brixy expected to see `1,2,3` here.
* Move cursor to `3` and press `Space` to unselect it.
* Press `X`
    * @Brixy expected that only `1` and `2` will get removed, but in fact we issue removal command for `1,3,1,2`.

I say it's by design because it's the same scenario as moving between folders, once selection is flushed to the file (read: once `+` icons disappear), all new selections will _append_ to it, until you clear selection with `mm`.

### 4:

This definitely works for me on zsh.

**Comment by jarun** [comment]
1 and 2 are by design. Once you flush, you indicate you are OK with the files you have already selected. You also lose the `+` which means you can't deselect anymore. I will update the docs to add some more clarity but it's already there.

4 is not an issue for me.

**Comment by jarun** [comment]
BTW, 3 is in master now.

**Comment by jarun** [comment]
I have updated the docs.

@Brixy please read https://github.com/jarun/nnn/wiki#selection for more details on the behaviour.

**Comment by Brixy** [comment]
Thank you very much, guys.

I figured **1** had to be that way. So thank you for updating the docs and adressing **3.**

**Comment by jarun** [comment]
Enjoy!
