### ISSUE TITLE
`ctrl-l` does not clear prompt after typing `n` to create a file or directory.

### ISSUE THREAD

**Issue by yxchng** [jarun/nnn#395]
#### Environment details (Put `x` in the checkbox along with the information)

[ ] Operating System: Ubuntu 18.04
[ ] Desktop Environment: 
[ ] Terminal Emulator: 
[ ] Shell: gnome terminal
[ ] Custom desktop opener (if applicable):
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
`ctrl-l` does not clear prompt after typing `n` to create a file or directory. It requires me to press `enter` as well before prompt is cleared. 

I am not sure if this is the expected behavior. If so, why? I would expect prompt to be cleared without needing to press `enter` after pressing `ctrl-l`

**Comment by jarun** [comment]
Can't reproduce this with master. Please try with release v2.8.

**Comment by yxchng** [comment]
@jarun thanks. it works now in v2.8. i was using an old version install using `apt` on ubuntu.
