### ISSUE TITLE
How to open file in new tab or new window?

### ISSUE THREAD

**Issue by yxchng** [jarun/nnn#397]
How to open file in new tab or new window? Or is it not supported?

**Comment by 0xACE** [comment]
?? you can duplicate the current context by clicking `1`, `2`, `3` or `4`. and then do as you like from that context.

But `nnn` is not a terminal multiplexer...

**Comment by jarun** [comment]
Try the plugin fzcd. We can have something like it to open a dir in new tab. Please see if you can raise a PR.

**Comment by jarun** [comment]
@yxchng this will only be for dirs. `nnn` is not a mime opener. To open a file detached, please visit the Wiki section on how to open text files in a new window.

@annagrram would it be possible for you to add a quick plugin for this (open the selected dir (in any) in next available free context (or fail, if there's none)? It would be great if we can have this in v2.8.1.

**Comment by jarun** [comment]
But not a must as we can add plugins anytime.

**Comment by jarun** [comment]
@yxchng when we create a new context, we copy the earlier one. What's stopping you from entering the directory in the next context?

Also, your use case is covered by `fzcd` already. Not just a child dir, you can open any dir in the subtree or parent dir of any file in the subtree with it.
