### ISSUE TITLE
Insta-quit

### ISSUE THREAD

**Issue by urosk** [jarun/nnn#402]
Would it be possible to add a command which allows the user to quit without confirmation. Or remove the confirmation altogether from SEL_QUIT.

Use case: I start nnn with a session with 4 pre-opened contexts. So to quit I need to either qqqq or qy, which are both more effort than I'd like :/

For now I just commented out the code which requests confirmation in my build.

**Comment by jarun** [comment]
I can see why it can be annoying. I will add a switch to do this.

**Comment by jarun** [comment]
Should be fixed now. Please confirm.

**Comment by urosk** [comment]
Works perfectly 👍
