### ISSUE TITLE
Ability to omit trash when removing files

### ISSUE THREAD

**Issue by maximbaz** [jarun/nnn#404]
I generally like the integration with `trash-cli`, however I sometimes lack the ability to purge the file immediately, i.e. remove it completely instead of moving to the trash bin.

The reasons could be that it's a sensitive file, or it's a large file and I'm trying to free up disk space, and recently I found that quite often I need to remove the file from trash manually right after removing the file via `nnn`.

Another example would be if you have a partition that doesn't have `.Trash` directory (for whatever reason, maybe you don't want to trash anything on that drive), and in this case there would be no way to remove the file from within `nnn`.

It can't be a startup CLI flag (because I don't know at the moment of launching `nnn` if I would want to trash or purge files), I feel like it should be a new shortcut, but then it's unclear what would the shortcut do for people who don't use `trash-cli`... What do you think?

**Comment by jarun** [comment]
@maximbaz we don't want to have a specific shortcut for loosely coupled utilities as we don't want to advertise them as direct dependencies. We will need 2 additional shortcuts to satisfy this request - delete file to trash, delete file directly. delete selection to trash, delete selection directly.

We can't keep adding trivial functionality and additional shortcuts for every other thing. If you need trash, stick to trash; if you are confident enough to use `rm -rf` directly, use that. Personally I'd never used a trash over the past decade and `nnn` has a double check to ensure I don;t accidentally delete something. I think that's enough.

**Comment by jarun** [comment]
BTW, it's very easy to add a plugin that can do both. Try that instead.

**Comment by maximbaz** [comment]
Fair points, and I agree about plugin, that is probably the easiest solution indeed 👍
