### ISSUE TITLE
Show indicator of pending input in status bar

### ISSUE THREAD

**Issue by maximbaz** [jarun/nnn#405]
Some commands require pressing two keys, and I think it would make sense to let `nnn` show in status bar if `nnn` is waiting for the _second_ keypress, because the meaning of this second keypress depends on whether `nnn` is listening on a key to finish some action.

For example, `;` marks the start of selecting a plugin, and the next keypress will select the plugin. If you have a plugin that say jumps to a different directory on `j`, pressing `j` after `;` will not move your cursor down, but will move you to a completely different directory. Right now just by looking at `nnn` window you don't know what the next `j` keypress will do, will it move your cursor down or will it execute a plugin. It would be nice if there was some indicator, some `[plugin]` perhaps, showing that the next keypress determines which plugin to run.

A good example perhaps would be the `m` keypress. The first time you press `m` you mark the start of selection (and in status bar `[0:]` becomes `[1:]`), and a second `m` keypress finishes it. So if you see `[1:]`, you know that the next `m` will finish a selection. Except this also is not perfect, because if you already have a selection, in the status bar you will see `[1:4]`, and even after you press `m` one more time to start the selection again, status bar will continue showing `[1:4]`. 

This could be improved as well I think, maybe the second number could become `*` after you pressed `m` for the first time, because technically we don't know the number of selected files until user finishes the selection?

So the very first `m` will change from `[0:]` to `[1:*]`, the second `m` changes to `[1:3]`, the third `m` changes to `[1:*]`, the fourth `m` changes to `[1:6]` and so forth?

**Comment by jarun** [comment]
> If you have a plugin that say jumps to a different directory on j, pressing j after ;

There's no way someone can press `;` without understanding what it does. Why would you press `;` and then press `j` thinking it will go to next entry? If you have added a plugin with `j` in your rc file you know very well what the sequence `;j` does.

> Right now just by looking at nnn window you don't know what the next j keypress will do

But if I pressed a `;` just now I should remember that.

> So the very first m will change from [0:] to [1:*], the second m changes to [1:3], the third m changes to [1:*], the fourth m changes to [1:6] and so forth?

We do show a popup that says "range selection on". Do you want the code to become a spaghetti?

**Comment by jarun** [comment]
In a user can't remember what he is doing a fraction of a second back, trust me, `nnn` is not for him/her. We are not writing this for him/her.

**Comment by jarun** [comment]
BTW, could you test the haiku port from https://github.com/jarun/nnn/pull/403?

**Comment by maximbaz** [comment]
:)

I don't think the code would become spaghetti if we add a little bit of consistency in UI 🙂 I suppose there is a flag somewhere already that remembers that `;` was pressed and that the next keypress will behave differently, it's a matter of reading that flag as well when drawing status bar?

It could be a typo simply, e.g. a user accidentally hitting `;` instead of `'` (because they are next to each other on `en-us` keyboard). Just an idea 🤷‍♂ 

> We do show a popup that says "range selection on".

The popup is a hack and it will not be necessary at all if status bar would be consistent, if you see `[1:*]`, you _know_ you are in range selection mode, you don't need a flashing message in the prompt to say the same 😉 

> BTW, could you test the haiku port from #403?

Oh I'm not familiar with haiku at all, sorry 😞

**Comment by jarun** [comment]
> I suppose there is a flag somewhere already that remembers that ; was pressed

No, when you press `;` the control goes to the lead key handling, there is no redraw.

> It could be a typo simply

Yes, it could be but as I mentioned above, we do not redraw in the lead key handler.

> The popup is a hack and it will not be necessary at all if status bar would be consistent

We can do this. Please raise a PR.

**Comment by jarun** [comment]
I think both are doable easily. Raise the PR.

Also, when you think of an issue, also think from code perspective how to fix it. So see it from this angle - if I want to do this what do I need to do. And when you add the issue, please add the technical details of the fix.

I need contributors to be more proactive with these. I sound bitter because I returned home half an hour back and then I see UI problems. I am a hardware guy and don't really understand UI very much. Then I think - why do people need everything simplified this much?

You may suggest I take rest and look at it. But I am looking at your issue while eating because I need to sit with my son to help in his studies. And then I have to tend to office work till midnight. I'll again get up at 7 and drive my family to their school and workplace then go to my office. That's my life.

So you see, I need much more from you guys when you see there's a problem. Help yourselves, by more specific and speak code.

**Comment by jarun** [comment]
When you raise the ER, please test both the normal mode and navigate-as-you-type modes.

**Comment by jarun** [comment]
> Oh I'm not familiar with haiku at all, sorry

Neither is @annagrram! ;)

Just download the ISO, set up a VM and boot into another *nux-ish OS. You'll know what to do past that. And if you need help, please check with @annagrram.

BTW, @annagrram I'll be visiting my hometown in Christmas and New Year for 2 weeks so I can test this. I have downloaded the ISO a few days back.

**Comment by 0xACE** [comment]
> There's no way someone can press `;` without understanding what it does. Why would you press `;` and then press `j` thinking it will go to next entry?

I would like to point out that a it is not about knowing wether you pressed it or not, it's about clarity. I frequently run into this issue on touch-devices and poor keyboards.

But it honestly doesn't bother me enough to do something about it... I more frequently stumble on prompts that appear on the bottom left though. (mounting `sshfs` comes to mind atm, but its probably just muscle memory causing this)

**Comment by jarun** [comment]
@maximbaz for the first issue (leader key), call a printprompt what whatever you want to show and let's see.

Please add this in the same PR.

**Comment by jarun** [comment]
After a leader key, we either switch dirs or contexts or at least redraw. So the msg in the prompt will be gone.

Exceptions:
- if you press a bookmark key where the bookmark destination is the same as current dir. You need to clearprompt() here.
- bookmark destination cannot be accessed. Add a printwait() with "MSG_ACCESS" in this case. it is missing today.

**Comment by annagrram** [comment]
> Neither is @annagrram! ;)

True.

> Just download the ISO, set up a VM and boot into another *nux-ish OS. You'll know what to do past that. And if you need help, please check with @annagrram.

After that, in order to build, you need 2 prerequisites that don't come out-of-the-box.
Just:
`pkgman install readline_devel ncurses6_devel`

> BTW, @annagrram I'll be visiting my hometown in Christmas and New Year for 2 weeks so I can test this. I have downloaded the ISO a few days back.

I'll be on vacation for the entire Christmas week, so not sure I'll be available. Surely not for coding.
