### ISSUE TITLE
Help screen is hard for perception

### ISSUE THREAD

**Issue by tim77** [jarun/nnn#407]
#### BUG REPORTS

Hello. This help screen [1] is hard for perception. Would be nice to move second block to right a little bit. Also would be nice to colorize hotkeys for better readability. 

#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Fedora
[x] Desktop Environment: i3wm/GNOME
[x] Terminal Emulator: gnome-terminal/alacritty
[x] Shell: fish

![DeepinScreenshot_select-area_20191216192531](https://user-images.githubusercontent.com/5614476/70928816-7ae15080-203a-11ea-87d0-8e2c2bc0cc80.png)

**Comment by jarun** [comment]
Take a look at master. I recently cleaned it up a bit. Let me know if you have some suggestions to move around the entries further without having to shift a full column (that would add a number of bytes).

**Comment by tim77** [comment]
Version from master [2] looks definitely better. But TBH still think that nice to have colorized or bold hotkeys for better distinguish. Maybe this would be enough without shift a full column.

[2]
![DeepinScreenshot_select-area_20191216213416](https://user-images.githubusercontent.com/5614476/70937483-082da080-204d-11ea-9769-88226b1d962e.png)

**Comment by maximbaz** [comment]
@jarun have you considered using `\t` to shift column? If you just go with a simple way of adding a new column of `\t` chars, it would at least not grow the binary by that much as it would if you added a column of say 8 spaces.

If the size is still a concern, you could expand `\t` yourself (say to `8` spaces) (so that `\t` has a predictable width, not dependent on users' PAGER) in `show_help()`, replacing the existing alignment with spaces - this way, you would actually _decrease_ the current binary size by quite a few bytes I think.

**Comment by maximbaz** [comment]
I completely agree that the current help is not very readable, most of all I dislike that different lines have different number of columns (most have two, but some have three).

**Comment by ignatenkobrain** [comment]
You can use libsmartcols (from util-linux) to make proper table printing...

https://karelzak.blogspot.com/2014/05/libsmartcols-pretty-output-for-everyone.html

**Comment by maximbaz** [comment]
Maybe a silly idea, but it was easy to implement, and imho already helps a lot, and also doesn't increase the binary size which seems to be a concern. https://github.com/jarun/nnn/pull/408

**Comment by jarun** [comment]
> You can use libsmartcols (from util-linux) to make proper table printing...

No new deps please.

**Comment by jarun** [comment]
> Maybe a silly idea, but it was easy to implement, and imho already helps a lot, and also doesn't increase the binary size which seems to be a concern.

Yeah, binary size is the main concern. People use `nnn` in custom initrds which are in MBs. So we are very particular about even byte-size gains.

**Comment by jarun** [comment]
Closed at commit f10481e93e3cd043c6314bdc343843764d380f24.
