### ISSUE TITLE
Reduce false positives in nav-as-you-type mode

### ISSUE THREAD

**Issue by maximbaz** [jarun/nnn#412]
I use `nav-as-you-type` with `-t` flag because I experience too many false positives where I enter I directories I don't want to enter because I type too fast, but I think we can improve the mode so that `-t` flag will not be needed.

First, an example of what I mean:

Start in `navtest` dir:

```
navtest
├── hom
└── hub
    ├── nnn
    └── uber
```

Suppose you want to go to `hub/nnn/`. Launch `nnn -i`. You see `hom` and `hub`. I want to go to `hub`, and because I type fast without looking at keyboard, I type all 3 letters `hub` very quickly with almost no delay.

Expected: I enter `hub` directory and see `nnn` and `uber`.

Actual: I enter `hub` directory (because of `hu`) **and** I enter `uber` directory (because of `b`).

What I think will tremendously improve experience is if once a directory is matched, we should swallow all the next keypresses that happen within the next 100-200ms or so. 

So if in the example above, if I see `hom` and `hub`, if I instantly type `hub`, once the directory `hub` is matched after I typed `hu`, because I pressed `b` almost instantly it should be ignored by nnn and I should remain in `hub` folder.

Does it make sense?

I am happy to try to implement this, but I don't really know how, any hints are appreciated.

**Comment by jarun** [comment]
We can't have keypresses vanish. This is a case of correct behaviour against user experience. In my case I use nav as you type like shortcuts. Yes, there are a few times I have faced what you are saying but that is max one extra level of depth and I could press left to jump back easily. If you face thos frequently, I would suggest you have a local copy.

**Comment by maximbaz** [comment]
> We can't have keypresses vanish

Do you think there is some limitation that will physically not allows us to implement this in any way?

I feel if this is done properly, we will not harm anyone's user experience, but will only improve it by reducing these false positives when you must click "left".

If you have an idea how this can be implemented, can you give me some hints? Maybe I can convince you that this is awesome idea after I have a working prototype 😉 😉

**Comment by jarun** [comment]
What do you men by false positive? Aren't you getting correct matches against what you type? I think you are trying to tune the program based on your expectation. When I see what you think is false, I immediately know there were unique matches in the path. Next time I m careful or I get to typing the correct sequence once I enter the path  few times. It looks like you are trying to enter unvisited paths and expecting the program to cover up because you are not aware of the unique paths.

**Comment by jarun** [comment]
The person who knows the path in your example will actually press `hun` and with the changes you are suggesting he might have to press n multiple times. So what you are suggesting actually breaks a correct behaviour.

**Comment by jarun** [comment]
> because I type fast without looking at keyboard

You need to look at the monitor.

**Comment by jarun** [comment]
> Expected: I enter hub directory and see nnn and uber.

This is a wrong expectation. Auto-dir select works on unique paths, that's the definition.

**Comment by jarun** [comment]
BTW, I had also thought of this before, when I started using this feature, but I refrained from breaking the correct behaviour because of the reasons above. And there's also a switch to disable auto dir select. You can use that.

**Comment by maximbaz** [comment]
> The person who knows the path in your example will actually press `hun`

Not really, because this is very much dependent on the contents of all directories, as new folders appear and disappear the "unique" key changes.

Imagine I remove `hom` folder. Then `hun` will lead me to `hub/uber`, a completely different folder!

This feature is not helping productivity, but asking users to slow down, type veeeeeeeeeeeeryyyyyyyyy sloooooooooooooowlyyyyyyyyyyy, check what happens on the screen after every single keypress, because you never know when it will jump - and what I have in mind to suggest is a feature that speeds user up, not slows them down, allows to keep typing fast and yet lead to where they want to go.

Suppose I don't know by heart my folder structures. `nnn` presents me with folders in the current dir. To be most productive, I only need to glance the folder name that I'm looking for, and then type its name. Right now I need to find the folder name, then start very carefully typing this name, letter by letter, waiting until I finally get inside that folder.

I don't think it's wrong to expect a productivity boost from this app? 😉 

----

I thought of another idea, maybe this will be simpler to implement? Instead of swallowing letters after the match has been found, what if we buffer users' keypresses, and do the match only after say 100-200ms passed since the last keypress? This will maybe even help performance on very slow devices, we don't need to match on every keypress, we throttle the match to run it _at most_ every 100-200ms.

What do you think of this? Easier to implement? Can you give me some suggestions?

I still believe that once you see the result you will like it 😄

**Comment by jarun** [comment]
> but asking users to slow down, type veeeeeeeeeeeeryyyyyyyyy sloooooooooooooowlyyyyyyyyyyy

Please don't bring in your personal perspectives to defect discussions. I type pretty fast myself and I do not have any issue with this feature.

> I still believe that once you see the result you will like it

No, in this case i don't really want to complicate a simple, we-defined behaviour. I am ending this discussion from my side here.

If anyone else in the team wants to discuss this, please go ahead.

**Comment by jarun** [comment]
BTW, you asked about the implementation. Just follow the `cfg.autoselect` variable.

You can implement it if you want and demo but I am almost 100% sure I will not agree to breaking it. And why I am resisting more is I don't want the team to waste time on trivia when we can actually work on much more important stuff.

**Comment by jarun** [comment]
In case you are not checking the Haiku OS porting or the binary size thing, see if you can work on controlling the stdin and stdout of a plugin. That way we can show an image in an external image viewer and press next next next to navigate images in a dir. This is a simple example but there can be many applications of this.

I think we can have a 2-ended pipe in run_selected_plugin() to achieve this.

**Comment by maximbaz** [comment]
> And why I am resisting more is I don't want the team to waste time on trivia when we can actually work on much more important stuff.

Oh but this is fun, it gives a chance to test some assumptions that might bring some serious usability improvements!

But in this case you were 100% right 😄 I implemented a prototype, it turned out to be easier that I expected... and it's not really usable at all, not as what I had in my mind originally.

It turns out to be nearly impossible to find a delay that would both be invisible to the eye and yet that would capture all the mistyped letters. As soon as I make it catch enough of extra letters, my eye notices a delay, and it is very annoying.

So in fact I think for me personally `-t` is still the best option.

Thanks for your comments though, even though the idea failed, now I'm happy that I got to try it and I saw it with my own eyes that is was not good.

**Comment by jarun** [comment]
> and it's not really usable at all

because the same precision doesn't work for everyone. there's a theory that the typing speed of people don't vary much over years and some security measures can actually use that.

**Comment by jarun** [comment]
> Oh but this is fun

Yes, another kid I work with doing his PhD in Princeton thinks the same way. I still think his academics is much more important than spending time on open source projects. So I try to get only quality time from you guys.
