### ISSUE TITLE
Change `l` to pick file when in picker mode instead of open.

### ISSUE THREAD

**Issue by hsanson** [jarun/nnn#413]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System:  Linux
[x] Desktop Environment: Kde Neon
[x] Terminal Emulator: Konsole
[x] Shell: Bash
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

When using nnn in picker mode pressing `l` in a file opens it instead of picking it. This causes problem in the (neo)vim plugin when navigating to select a file pressing `l` and at the end opens another instance of vim instead of opening the file in the current buffer.

**Comment by jarun** [comment]
That's the desired behaviour: https://github.com/mcchrish/nnn.vim#usage

The code follows: https://github.com/jarun/nnn/blob/master/src/nnn.c#L4433

This is the way for someone to open `nnn` within an already open `vim` instance and play a file.

Adding @mcchrish for his opinion.

**Comment by hsanson** [comment]
If this is expected behavior then please ignore and close this issue. It felt like a bug to me since `l`, `Right`, and `Enter` do the same thing in normal mode but not in picker mode. Also other plugins (e.g. vim-ranger) behave the way I expected this to work, that is, open the file within (neo)vim when pressing `l` or `Right` after selecting it.

Since there is already a ^O action for `Open with` I would prefer `l`, `Right`, and `Enter` to do the same thing in picker mode.

**Comment by jarun** [comment]
Yes, we want to keep the functionality of the file manager easily available. Maybe we should clarify that int he document.

**Comment by jarun** [comment]
Updated the document at https://github.com/mcchrish/nnn.vim/commit/cf64e72709aea280c560cc36f9187c8fa90552fe.
