### ISSUE TITLE
Improvements for distribution

### ISSUE THREAD

**Issue by maximbaz** [jarun/nnn#416]
Since I'm also a packager, I'd like to suggest some improvements for the Makefile and distribution practices in general 🙂 

1. I can see you PGP sign your commits, would you consider providing signatures (`*.sig`) for release assets? That way users can have more trust that application sources did come from you. For Arch Linux specifically I would only want the signature for the source tarball file, since that's what I use to compile the app.

    ![image](https://user-images.githubusercontent.com/1177900/71216048-a02fc200-22b9-11ea-9bd7-c4b32b3191b0.png)

    I can see you create releases using Circle CI, and you probably wouldn't want to upload your private key to them, so I imagine this is something you would have to do locally. I can take care of everything, update Makefile, so all you would have to do is to run `make sign` on each release and upload the resulting `*.sig` file(s) to Github, question is if you would agree to provide PGP signatures?

2. `make dist` is preparing tarball based on the current folder, a better way of doing so is to let `git` prepare the tarball itself. First, you tag the repo with `$VERSION` (say it is `v2.8.1` tag), and then run the following command to generate the tarball:

    ```
    git archive -o nnn-$(VERSION).tar.gz --format tar.gz --prefix=nnn-$(VERSION)/ $(VERSION)
    ```

    This generates tarball that is guaranteed to be based on a git tag (more trustworthy as no chance for accidentally packaging files with local changes), and it is guaranteed to be bit by bit identical to the archive that Github prepares for you in this link:

    ![image](https://user-images.githubusercontent.com/1177900/71216048-a02fc200-22b9-11ea-9bd7-c4b32b3191b0.png)

    In fact, I think there is no reason to provide your custom tarball at all, just let everyone download the tarball already prepared by Github!

    This is needed if you will agree to provide PGP signatures, then you can do the following in `make sign`:

    ```
    git archive -o nnn-$(VERSION).tar.gz --format tar.gz --prefix=nnn-$(VERSION)/ $(VERSION)
    gpg --detach-sign nnn-$(VERSION).tar.gz
    rm -f nnn-$(VERSION).tar.gz
    ```

**Comment by jarun** [comment]
Yes, both of these are quality improvements. Please go ahead!

**Comment by jarun** [comment]
Closing the issue as most of the discussion is happening in the PR.
