### ISSUE TITLE
error: use of undeclared identifier 'CLOCK_REALTIME'

### ISSUE THREAD

**Issue by heptathlon** [jarun/nnn#419]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: MacOS 10.11

#### Exact steps to reproduce the issue

```sh
brew install nnn

==> Downloading https://github.com/jarun/nnn/archive/v2.8.1.tar.gz
==> Downloading from https://codeload.github.com/jarun/nnn/tar.gz/v2.8.1
######################################################################## 100.0%
==> make install PREFIX=/usr/local/Cellar/nnn/2.8.1
Last 15 lines from /Users/Leon/Library/Logs/Homebrew/nnn/01.make:
2019-12-24 01:10:12 +0100

make
install
PREFIX=/usr/local/Cellar/nnn/2.8.1

/bin/sh: pkg-config: command not found
/bin/sh: pkg-config: command not found
clang  -Wall -Wextra -O3   -o nnn src/nnn.c -lreadline -lncurses
src/nnn.c:4352:9: error: use of undeclared identifier 'CLOCK_REALTIME'
                                    CLOCK_REALTIME,
                                    ^
1 error generated.
make: *** [nnn] Error 1
```

**Comment by 0xACE** [comment]
I'm not familiar with your machine setup. My man-page for `time.h` states:

>All  implementations support the system-wide real-time clock, which is identified by `CLOCK_REALTIME`.

Anyhow, afaik: most of the `nnn` devs are busy during the holidays. If it's urgent you can try to patch every occurance of `clock_gettime()` with what is done here: https://gist.github.com/jbenet/1087739

**Comment by jarun** [comment]
1. We do compile `nnn` on macOS on Travis for every commit.
2. MacOS 10.11 is unsupported.

From https://en.wikipedia.org/wiki/OS_X_El_Capitan:

"Support status
--
Unsupported.  Extended support ended in September 2018. iTunes terminated as well.  (iTunes is replaced by separate apps in macOS Catalina, like iOS and  iPadOS.)."

@heptathlon please upgrade to the latest supported release of macOS.
