### ISSUE TITLE
Not showing big files

### ISSUE THREAD

**Issue by goberghen** [jarun/nnn#42]
Hello. I am using **Debian Unstable i386**. For some reason nnn do not show big files (1.5G is ok, but ≈4G and more is not). I thought it may be some ntfs issue, but it's not. 
I can see these files with `ls` and `ncdu`, picture below.
![bwa](https://0x0.st/hQ_.png)

**Comment by jarun** [comment]
I will check this. Thank you for the report.

**Comment by jarun** [comment]
Ahh, i386.

**Comment by jarun** [comment]
Can you please test if the following patch crashes at one of the files not shown?

```
diff --git a/nnn.c b/nnn.c
index 8eda2b3..b94ca40 100644
--- a/nnn.c
+++ b/nnn.c
@@ -1784,9 +1784,10 @@ dentfill(char *path, struct entry **dents,
                        if ((namep[0] == '.' && (namep[1] == '\0' || (namep[1] == '.' && namep[2] == '\0'))))
                                continue;
 
-                       if (fstatat(fd, namep, &sb, AT_SYMLINK_NOFOLLOW)
-                                       == -1)
-                               continue;
+                       if (fstatat(fd, namep, &sb, AT_SYMLINK_NOFOLLOW) == -1) {
+                               DPRINTF_S(namep);
+                               errexit();
+                       }
 
                        if (S_ISDIR(sb.st_mode)) {
                                if (sb_path.st_dev == sb.st_dev) {
@@ -1816,7 +1817,7 @@ dentfill(char *path, struct entry **dents,
 
                if (fstatat(fd, namep, &sb, AT_SYMLINK_NOFOLLOW) == -1) {
                        DPRINTF_S(namep);
-                       continue;
+                       errexit();
                }
 
                if (n == total_dents) {
```

**Comment by jarun** [comment]
If it does, I believe we have to use stat64 versions instead of stat if the platform is i386.

**Comment by goberghen** [comment]
Yes, it crashes.
`line 1820: (75) Value too large for defined data type`

**Comment by jarun** [comment]
Yes, that's because of the limitation of `stat` on i386. We have to use stat64 or something.

**Comment by jarun** [comment]
Now, please remove the older patch and try the following:

```
diff --git a/nnn.c b/nnn.c
index 8eda2b3..dc679fb 100644
--- a/nnn.c
+++ b/nnn.c
@@ -22,6 +22,17 @@
 #define LINUX_INOTIFY
 #endif
 #include <sys/resource.h>
+#ifdef __linux__
+#ifndef __USE_LARGEFILE64
+#define __USE_LARGEFILE64 1
+#endif
+#ifndef _LARGEFILE_SOURCE
+#define _LARGEFILE_SOURCE 1
+#endif
+#ifndef _LARGEFILE64_SOURCE
+#define _LARGEFILE64_SOURCE 1
+#endif
+#endif
 #include <sys/stat.h>
 #include <sys/statvfs.h>
 #if defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__) || defined(__APPLE__)
```

**Comment by goberghen** [comment]
Still no changes.

**Comment by jarun** [comment]
OK. I think it's better to run it on a VM and test. It will take some time.

BTW, is there any specific reason you are running a 32-bit OS? I am also considering explicitly removing support for 32-bit because most people use 64-bit nowadays.

**Comment by goberghen** [comment]
I'm too lazy to reinstall my OS, it works for many years and I don't have any problems with it (at least with PAE kernel).
At the same time, for some other computers 64-bit OS is not an option. I'm talking about some old **fun-boxes** that still can be used. I think `nnn` would be a great thing for those machines (nnn + tty = ♥).

**Comment by jarun** [comment]
Major distros like Arch and Fedora are phasing out 32-bit support. My problem is, I can't test and support newer changes on i386, both due to time and resource crunch. I'll probably add this fix and then call it a day for i386.

**Comment by goberghen** [comment]
> Major distros like Arch and Fedora are phasing out 32-bit support.

Well, they're have poor non-amd64 architectures support in general. Fortunately it's not an issue in Debian.
>My problem is, I can't test and support newer changes on i386, both due to time and resource crunch. I'll probably add this fix and then call it a day for i386.
Thank you. That would be great. And I doubt there will be more problems with i386 support.

**Comment by jarun** [comment]
Can you try the following Makefile patch:

```
diff --git a/Makefile b/Makefile
index d281d0c..f83e8c9 100644
--- a/Makefile
+++ b/Makefile
@@ -3,7 +3,7 @@ VERSION = 1.4
 PREFIX ?= /usr/local
 MANPREFIX = $(PREFIX)/share/man
 
-CFLAGS += -O2 -Wall -Wextra -Wno-unused-parameter
+CFLAGS += -O2 -Wall -Wextra -Wno-unused-parameter -D_FILE_OFFSET_BITS=64
 LDLIBS = -lreadline
 
 ifeq ($(shell pkg-config ncursesw && echo 1),1)
```

As per [this thread](https://stackoverflow.com/questions/3221113/off-t-without-d-file-offset-bits-64-on-a-file-2gb) it should do the trick.

**Comment by goberghen** [comment]
With or without previous `nnn.c` patch?

**Comment by jarun** [comment]
Without the previous patch.

**Comment by jarun** [comment]
And if the Makefile patch works, try this one (without the Makefile patch):

```
diff --git a/nnn.c b/nnn.c
index 8eda2b3..7a6c357 100644
--- a/nnn.c
+++ b/nnn.c
@@ -22,6 +22,9 @@
 #define LINUX_INOTIFY
 #endif
 #include <sys/resource.h>
+#ifdef __i386__
+#define FILE_OFFSET_BITS 64
+#endif
 #include <sys/stat.h>
 #include <sys/statvfs.h>
 #if defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__) || defined(__APPLE__)
```

**Comment by goberghen** [comment]
`Makefile` patch works, but `nnn.c` patch doesn't

**Comment by jarun** [comment]
Which compiler are you using?

**Comment by goberghen** [comment]
What do you mean?
Maybe I should change `#ifdef __i386__` to `#ifdef __i686__` in the last patch?

**Comment by jarun** [comment]
Sure! Try it out!

**Comment by jarun** [comment]
Otherwise, please move those 3 lines to the top. Just not sure if inotify.h includes stat.h internally.

**Comment by goberghen** [comment]
No, i686 doesn't work either.

**Comment by goberghen** [comment]
> Otherwise, please move those 3 lines to the top. Just not sure if inotify.h includes stat.h internally.

Ok.

**Comment by goberghen** [comment]
Moving those lines doesn't helped.

**Comment by jarun** [comment]
Try this:

```
diff --git a/nnn.c b/nnn.c
index 8eda2b3..cfbbc54 100644
--- a/nnn.c
+++ b/nnn.c
@@ -22,6 +22,9 @@
 #define LINUX_INOTIFY
 #endif
 #include <sys/resource.h>
+#ifdef __i386__
+#define _FILE_OFFSET_BITS 64
+#endif
 #include <sys/stat.h>
 #include <sys/statvfs.h>
 #if defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__) || defined(__APPLE__)
```

**Comment by goberghen** [comment]
No result.

**Comment by goberghen** [comment]
I'll try with i686.

**Comment by jarun** [comment]
Also, please move it to the top and try.

**Comment by goberghen** [comment]
Works now!
```
#ifdef __i686__
#define _FILE_OFFSET_BITS 64
#endif
```
on top before
`#ifdef __linux__`

**Comment by jarun** [comment]
OK

**Comment by jarun** [comment]
Wait a little.

**Comment by jarun** [comment]
Try the following:

```
diff --git a/nnn.c b/nnn.c
index 8eda2b3..fc893a2 100644
--- a/nnn.c
+++ b/nnn.c
@@ -18,6 +18,9 @@
  */
 
 #ifdef __linux__
+#ifdef __i686__
+#define _FILE_OFFSET_BITS 64
+#endif
 #include <sys/inotify.h>
 #define LINUX_INOTIFY
 #endif
```

I am trying to limit this as Linux-only till I get reports from other platforms.

**Comment by goberghen** [comment]
Works too.

**Comment by jarun** [comment]
Awesome!
I'll push the patch soon!

**Comment by jarun** [comment]
Thanks a lot for your help!

**Comment by goberghen** [comment]
Thank you.
*By the way,* `#ifdef __i386__` *works too, so maybe it's better to prefer 386 over 686.*

**Comment by jarun** [comment]
OK. I've changed to i386.
