### ISSUE TITLE
Wide-character support not available with ncurses on all systems

### ISSUE THREAD

**Issue by KlzXS** [jarun/nnn#421]
In short, installing libncurses doesn't always provide wide-character support, and so compilation fails. If that's the case you need to install libncursesw and than has a separate header. In my case I needed to `#include <ncursesw/curses.h>`

This is something we should consider. Sorry for the potential sloppy writing I stayed up late beating my head around this way longer than I should have.

**Comment by jarun** [comment]
> installing libncurses doesn't always provide wide-character support

That's correct. Even on Ubuntu which I use does have both the versions. On macOS, however, ncurses provides both. `pkg-config` in the Makefile handles this. This is also in sync with our compilation instructions: https://github.com/jarun/nnn#from-source

TBH, distros should ship only the latest libs.

**Comment by jarun** [comment]
Also, it's not really our problem. In the dependencies section we also mention that a curses library with wide char support is required: https://github.com/jarun/nnn#library-dependencies

So closing this.

**Comment by KlzXS** [comment]
I just hadn't noticed that this is the case. I wish it wasn't this way, but oh well.
