### ISSUE TITLE
Remove some error messages

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#424]
@maximbaz I am thinking of removing some of the invalid keys, 0 selected messages. The more you use the keys the more they seem counter-productive.

For 0 selected, it's evident from the status bar.

For invalid, no change in the context should indicate that.

Can you please raise a PR and we can start with it and see where we end up?

I am actually working on simplification of workflows for the next release.

**Comment by jarun** [comment]
Once this is done, the next item I have in mind is to reduce the number of `goto nochange` branches in `browse()` in favour of bool checks and a single jump. I already eliminated a few in the recent comments.

**Comment by maximbaz** [comment]
How do we draw a line, which error message needs to be shown, and which needs to be silently ignored? For most errors I guess, they are evident because the intended action didn't happen.

**Comment by jarun** [comment]
I think so too! Start with something and we'll review and revisit.

**Comment by jarun** [comment]
The 0 selected are actually fine because without them there will be no visual change and the user may think nothing happened. The case with invalid key is different though. There is a visual change.

**Comment by jarun** [comment]
There's one more thing... in some cases we can skip redraws() due to break/continue by just a clearprompt().

BTW, I am working on these now.

**Comment by jarun** [comment]
I think we can ignore this exercise. `clearprompt()` can't be an alternative in all cases because `printmsg()` and the next `nextsel()` are intelligent enough to show the filter symbol if _nav-as-you-type_ is on, else the file details in the status bar. Just a clear prompt is kind of bland. ;)
