### ISSUE TITLE
Monitor directory changes with filtering enabled

### ISSUE THREAD

**Issue by vaygr** [jarun/nnn#43]
It doesn't seem to work as of **1.4**. Should it?

Steps to reproduce:

1. Run nnn
2. Use a filter, e.g. against `.png` files
3. Open one file
4. Delete the file from within picture viewer
5. Close picture viewer
6. Scroll down to the file you've just deleted and try to open it

What's expected:

1. The file disappeared from the filtered list

**Comment by jarun** [comment]
It's as per the design: https://github.com/jarun/nnn/wiki/nnn-design-considerations.

**Comment by vaygr** [comment]
Missed that, thanks!

**Comment by jarun** [comment]
No problem! Thanks for using nnn.
