### ISSUE TITLE
How to use ueberzug instead of w3m for image previews?

### ISSUE THREAD

**Issue by Kabouik** [jarun/nnn#430]
Is that possible? Not really an issue, perhaps more of a feature request (unless already doable), but I described my environment below.

#### Environment details
[x] Operating System: Ubuntu 18.04 as chroot from SailfishOS
[x] Desktop Environment: xfce4
[x] Terminal Emulator: tilix
[x] Shell: bash
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

**Comment by Kabouik** [comment]
Sorry I thought image preview was possible with w3m but could not find this information again, I believe I mixed up information I read on different cli-tools lately.

**Comment by jarun** [comment]
@Kabouik previews are available in master.
