### ISSUE TITLE
Only 15 keybinds are working for plugins

### ISSUE THREAD

**Issue by denis-khizhniak** [jarun/nnn#434]
#### Environment details (Put `x` in the checkbox along with the information)

[x ] Operating System: Linux
[x] Desktop Environment: n/a, Windows Manager: bspwm
[x ] Terminal Emulator: urxvt
[x] Shell: bash
[x] Custom desktop opener (if applicable): n/a
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. Assign more than 15 keys for executing plugins in the shell startup file (e.g. _~/.bashrc_).
2. After that if you go to the help page inside nnn, you'll see that the end is concatenated (in the example below the last line: `u: dups;v:vidthumb;w:wall;x:exetoggle`).

Example:
```
PLUGIN KEYS
 b: oldbigfile
 c: chksum
 d: diffs
 e: suedit
 g: _git log
 h: treeview
 i: imgsxiv
 j: fzcd
 k: -_fuser -kiv *
 l: uidgid
 o: fzopen
 p: pdfview
 r: renamer
 s: splitjoin
 u: dups;v:vidthumb;w:wall;x:exetoggle
```
Below is the corresponding part from my _.bashrc_ file:
```
export NNN_PLUG="b:oldbigfile;\
 12 c:chksum;\
 13 d:diffs;\
 14 e:suedit;\
 15 g:_git log;\
 16 h:treeview;\
 17 i:imgsxiv;\
 18 j:fzcd;\
 19 k:-_fuser -kiv $nnn*;\
 20 l:uidgid;\
 21 o:fzopen;\
 22 p:pdfview;\
 23 r:renamer;\
 24 s:splitjoin;\
 25 u:dups;\
 26 v:vidthumb;\
 27 w:wall;\
 28 x:exetoggle"
```

The keys in the concatenated part are not working. e.g. I can't toggle executable status by hitting `xx`, or `;x`.

I didn't check, but the same problem could be applicable for NNN_BMS keybindings.

**Comment by jarun** [comment]
The limit is [documented](https://github.com/jarun/nnn/wiki/Usage#configuration) and should be reasonable enough for regular users.

If you need more than 15 plugins and 10 bookmarks it means you are smart enough to compile the program yourself.

**Comment by jarun** [comment]
@denis-khizhniak we received some more requests to lift the limit on bookmarks and plugin keys. So the limit is not gone due to public demand. :+1:

**Comment by jarun** [comment]
This is on master. Please test and confirm.
