### ISSUE TITLE
Fail to open directory in GUI file manager - NNN_DE_FILE_MANAGER 

### ISSUE THREAD

**Issue by bullfrogj** [jarun/nnn#437]
###  Environment details (Put `x` in the checkbox along with the information)

[ X] Operating System: Debian 9.11
[X ] Desktop Environment: xfce
[X ] Terminal Emulator:xfce4-terminal
[X ] Shell: bash
[ ] Custom desktop opener (if applicable):
[X ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Clone latest 1b252b6 commitment
Compile with 'make 0_DEBUG=1'
Insert into ~/.bashrc 'export NNN_DE_FILE_MANAGER=thunar'
Run nnn, highlight a directory, press 'o' and it will ask for an application to open instead of just opening up thunar.  If I type in thunar, enter, then 'g' for GUI, enter, then it will open. This is too many keystrokes.  I also put an alias in .bashrc for t = thunar and using the alias t didn't work (trying to reduce keystrokes).  So it doesn't recognize alias and I swear I read somewhere that it would.

I also tried apt-get install nnn  (version 2.8.1-1) with same result (except pressing 'o' on a folder didn't do anything what-so-ever (CTRL+O would bring up the dialog to manually input in thunar.

Several of the various reviews in README state the usage of NNN_DE_FILE_MANAGER to highlight a folder, press 'o' and it will open it in the GUI file manager.  I couldn't see if this was removed although I do see there were some discussions about not implementing a GUI file manager for a CLI file manager.

**Comment by jarun** [comment]
I think you are on a very old version. Currently there is no such configuration option: https://github.com/jarun/nnn/wiki/Usage#configuration

What you want to do now is use the "launch app" shortcut (`=`) and type thunar.

You can also have a custom shortcut to run a command like plugin. See the plugin documentation: https://github.com/jarun/nnn/tree/master/plugins#running-commands-as-plugin

**Comment by jarun** [comment]
You can have: `t:-_thunar*` and then press `;` followed by `t` to run thunar.

**Comment by bullfrogj** [comment]
> You can have: `t:-_thunar*` and then press `;` followed by `t` to run thunar.

Hrmmm, i tried that.   in ~/.bashrc
`export NNN_PLUG='t:-_thunar*'`
then source ~/.bashrc
then nnn
press ? in nnn and it does show it as PLUGIN KEYS  "t:  -_thunar*"

I go to a folder, press `;` followed by `t` and it does nothing.

Version 2.8.1

(by the way, thank you so much for the quick response.  awesome project!)

**Comment by jarun** [comment]
Because `-` and `*` are not available in v2.8.1: https://github.com/jarun/nnn/tree/v2.8.1/plugins

So it should be: export NNN_PLUG='t:_thunar'.

> by the way, thank you so much for the quick response.

You are welcome!

> awesome project!

Award a star then! ;)

**Comment by bullfrogj** [comment]
Works!  It does say "Press ENTER to continue" after opening thunar in that folder.  Not a big deal, just requires pressing enter (or unless I close that thunar instance).  

Starred!

**Comment by jarun** [comment]
>  It does say "Press ENTER to continue" after opening thunar in that folder.

That can be suppressed on master as I mentioned. Please hold on till the next release.
