### ISSUE TITLE
Some issues with batch renaming

### ISSUE THREAD

**Issue by Brixy** [jarun/nnn#451]
```
nnn 2.9
iTerm2
MacOS Catalina
```

Thanks a lot for version 2.9. It has excellent functionalities and sans shortcuts.

I noticed some little things:

- If you try to open a file with a gui (`o` with `g`ui) although you mean a `c`li, nnn and the current tab of the terminal do not react properly any more (tested with iTerm2).
- When you batch rename files in (n)vim using `r` although nothing was selected beforehand, renaming has no effect.
- Same thing happens when you select files, then press `r`ename but choose `c`current.
- When renaming fails and you then press `e` to show selected files the cli is shown instead of the message `0 selected`.
- Very general: It is sometimes hard to tell whether `ESC` closes a view or whether you need to enter `:q`.

Thank you very much.

**Comment by jarun** [comment]
> If you try to open a file with a gui (o with gui) although you mean a cli

Sorry, I do not understand what you mean.

> When you batch rename files in (n)vim using r although nothing was selected beforehand, renaming has no effect.

Do you mean `nnn` doesn't open the files in the directory in your EDITOR or that editing and renaming the files do not result in actually renaming them.

> Same thing happens when you select files, then press rename but choose ccurrent.

Steps please! How did you select? After pressing `r` what did you press?

> When renaming fails and you then press e to show selected files the cli is shown instead of the message 0 selected.

Do you have any files in selection? Are all the problems with (n)vim? Can you try `vim` as EDITOR?

> It is sometimes hard to tell whether ESC closes a view or whether you need to enter :q

There is no _view_ in `nnn` and there is no `:q` shortcut. To quit a context press, `q`. See help. `Esc` does not close a context. It exits the filter mode without refreshing the view.

**Comment by jarun** [comment]
I wanted to install nvim myself to try these. But:

```
$ sudo apt install nvim                              
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package nvim
~/GitHub/nnn$ sudo apt install neovim
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libjemalloc1 libjs-sphinxdoc libjs-underscore libluajit-5.1-2 libluajit-5.1-common libmsgpackc2
  libtermkey1 libunibilium4 libuv1 libvterm0 neovim-runtime python-concurrent.futures python-greenlet
  python-msgpack python-neovim python-six python-trollius python3-greenlet python3-msgpack python3-neovim
Suggested packages:
  vim-scripts python-greenlet-doc python-greenlet-dev python-greenlet-dbg python3-greenlet-dbg
The following NEW packages will be installed:
  libjemalloc1 libjs-sphinxdoc libjs-underscore libluajit-5.1-2 libluajit-5.1-common libmsgpackc2
  libtermkey1 libunibilium4 libuv1 libvterm0 neovim neovim-runtime python-concurrent.futures
  python-greenlet python-msgpack python-neovim python-six python-trollius python3-greenlet
  python3-msgpack python3-neovim
0 upgraded, 21 newly installed, 0 to remove and 0 not upgraded.
Need to get 5,117 kB of archives.
After this operation, 23.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] n
```

I have `vim` installed and `nvim` was supposed to be a better replacement! I can't litter my system with all this garbage.

**Comment by jarun** [comment]
Please share the output of:

```
echo $VISUAL
echo $EDITOR
echo $NNN_USE_EDITOR
```

**Comment by Brixy** [comment]
> Please share the output of:
> 
> ```
> echo $VISUAL
> echo $EDITOR
> echo $NNN_USE_EDITOR
> ```

echo $VISUAL (empty)
echo $EDITOR: nvim
echo $NNN_USE_EDITOR (empty)

**Comment by Brixy** [comment]
>> If you try to open a file with a gui (o with gui) although you mean a cli

> Sorry, I do not understand what you mean.

- ‘hover’ a .txt file
- press `o`
- “Open with:” `nvim`
- “'c'li / 'g'ui?” `g` (which is wrong)
- current tab of your terminal becomes very slow and does not react properly any more.

**Comment by Brixy** [comment]
>> When you batch rename files in (n)vim using r although nothing was selected beforehand, renaming has no effect.

> Do you mean nnn doesn't open the files in the directory in your EDITOR or that editing and renaming the files do not result in actually renaming them.

- `mm` to deselect everything
- `r`
- nvim then shows the content of the current folder (including folders)
- rename some files and folders
- `:wq`
- no files were renamed

**Comment by Brixy** [comment]
>> Same thing happens when you select files, then press rename but choose current.

> Steps please! How did you select? After pressing r what did you press?

- `space` to select a file/multiple files
- `r`
- choose `c` for current
- nvim then shows the content of the current folder (including folders)
- rename some files and folders
- `:wq`
- no files were renamed

**Comment by Brixy** [comment]
>> When renaming fails and you then press e to show selected files the cli is shown instead of the message 0 selected.

> Do you have any files in selection? Are all the problems with (n)vim? Can you try vim as EDITOR?

It seems that when renaming fails nothing is selected. Sorry, I am not sure here.

**Comment by Brixy** [comment]
>> It is sometimes hard to tell whether ESC closes a view or whether you need to enter :q

> There is no view in nnn and there is no :q shortcut. To quit a context press, q. See help. Esc does not close a context. It exits the filter mode without refreshing the view.

Ok. Your explanation makes it clear to me.

**Comment by 0xACE** [comment]
> * ‘hover’ a .txt file
> 
> * press `o`
> 
> * “Open with:” `nvim`
> 
> * “'c'li / 'g'ui?” `g` (which is wrong)
> 
> * current tab of your terminal becomes very slow and does not react properly any more.

Opening a cli program as gui  causes issues, don't do that.

>Ok. Your explanation makes it clear to me.

It's unclear to me. Is the problem with renaming resolved for you now?

**Comment by Brixy** [comment]
> It's unclear to me. Is the problem with renaming resolved for you now?

Not really. I just don’t/can’t rename files and folders the way described above.

When you press `r` although nothing was selected nnn

- should either fail with something like “0 files selected. Nothing to rename.” or
- allow renaming as all files names of the current folder are shown in vim.

Sorry—I have not the correct technical vocabulary.

**Comment by jarun** [comment]
Try this:

    export NNN_USE_EDITOR=1

**Comment by jarun** [comment]
> “'c'li / 'g'ui?” g (which is wrong)
> current tab of your terminal becomes very slow and does not react properly any more.

CLI and GUI apps **MUST BE** handled differently. nvim is a cli app. Why do you even expect it will be handled correctly if you select `g`? It's not a bug. And if you say I pressed by mistake, well `nnn` is not responsible for fixing your mistake in this case because it doesn't know how to do that.

**Comment by jarun** [comment]
Try renaming the dir contents with `vim`.

**Comment by jarun** [comment]
When you press r although nothing was selected nnn

- should either fail with something like “0 files selected. Nothing to rename.” or
- allow renaming as all files names of the current folder are shown in vim.

If you do not have any files selected then the files in directory should be edited. From your description it seems that happens. But after you save the file nothing gets renamed.

Did you add new files or remove any?

**Comment by jarun** [comment]
@KlzXS if the files are listed and could be edited and saved, I have a hunch that batchrenamecmd may not be working on macOS. Can you take a look when @Brixy is back with more details?

**Comment by Brixy** [comment]
> Try this:
> 
> ```
> export NNN_USE_EDITOR=1
> ```

Now there is an error message when I try to batch rename things without selection: “failed!”

**Comment by Brixy** [comment]
> CLI and GUI apps MUST BE handled differently.

That’s absolutely clear and I don’t expect it to work. Yet, I just tested it and noticed that the terminal radically slows down. So it might be an issue for users who mix it up.

**Comment by jarun** [comment]
Please get master. Add the following patch:

```diff
diff --git a/src/nnn.c b/src/nnn.c
index 039d88c..83a8f11 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -1651,8 +1651,10 @@ static bool batch_rename(const char *path)
 
        /* Reopen file descriptor to get updated contents */
        fd2 = open(g_tmpfpath, O_RDONLY);
-       if (fd2 == -1)
+       if (fd2 == -1) {
+               DPRINTF_S(g_tmpfpath);
                goto finish;
+       }
 
        lines = lines_in_file(fd2, buf, sizeof(buf));
        DPRINTF_U(count);
```

Compile in debug mode:

    make debug

Run the workflow and share the logs from `/tmp/nnndbg` (or from the current directory).

**Comment by Brixy** [comment]
I was only able to apply the patch manually.

`make debug` does not work:

> cc -DDBGMODE -g -Wall -Wextra -O3   -o nnn src/nnn.c -lrt -lreadline -lncurses
ld: library not found for -lrt
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [nnn] Error 1

Nothing is written to `/tmp/nnndbg`.

Yet, `make` does work.

**Comment by jarun** [comment]
I thunk on OSX you'll have to install some library. But was this batch rename dir entries working for you in v2.8?

**Comment by jarun** [comment]
Add the following patch to Makefile and try to `make debug`:

```diff
diff --git a/Makefile b/Makefile
index 6043572..44849a6 100644
--- a/Makefile
+++ b/Makefile
@@ -28,7 +28,6 @@ endif
 ifeq ($(O_DEBUG),1)
        CPPFLAGS += -DDBGMODE
        CFLAGS += -g
-       LDLIBS += -lrt
 endif
 
 ifeq ($(O_NORL),1)
```

**Comment by jarun** [comment]
@annagrram @maximbaz @0xACE @KlzXS does anyone have a mac? Can you guys please try it out?

@zmwangx looks like this is a batch rename entries in current dir issue exclusively on macOS? Would it be possible for you to try it once?

Steps:

```
- export NNN_USE_EDITOR=1
- export VISUAL=vim
- run nnn
- press r
- rename some files (do not add or delete any)
- wq
- see if the files are renamed
```

**Comment by jarun** [comment]
@kjnez @detunized @serverhiccups @maximilianschmitt @jessemillar @weatherbell @Jackymancs4 @orf @kajka @niklasbogensperger @ahmedelgabri @pat-s @shuizhongyueming @danielb2 @ParityError @ldelossa @sukima @faxotherapy @dangerware @relapi @jhsta @s-mage @heptathlon 

Looks like we are in a situation here. None in the team uses macOS and we need help in figuring this problem. Can you guys help up out?

Many thanks in advance!

**Comment by kjnez** [comment]
Tested using nnn 2.9, on MacOS Catalina via iTerm2, and it seems to be working.

**Comment by kjnez** [comment]
> @annagrram @maximbaz @0xACE @KlzXS does anyone have a mac? Can you guys please try it out?
> 
> @zmwangx looks like this _batch rename entries in current dir_ issue is seen exclusively on macOS. Would it be possible for you to try it once?
> 
> Steps:
> 
> ```
> - export NNN_USE_EDITOR=1
> - export VISUAL=vim
> - run nnn
> - press r
> - rename some files (do not add or delete any)
> - :wq
> - see if the files are renamed
> ```
Tested using nnn 2.9, on MacOS Catalina via iTerm2, and it seems to be working.

**Comment by jarun** [comment]
Thanks @kjnez! I am assuming you are on v2.9 or master where this is reported.

@Brixy looks like there is no issue with the `xargs` options which I was suspecting. Looks more of a local or config issue to me. I remember I had a problem once with executing commands in `/tmp` as it was mouted as tmpfs...

Please add some debug logs and see where is fails. Start with the basics... are you able to open text files in `vim` and so on...

**Comment by jarun** [comment]
I closed the issue because we addressed your other concerns and we have no way to figure this out without being able to reproduce. Please let us know if you have a way to reproduce the issue 100% on all systems.

**Comment by dangerware** [comment]
> @annagrram @maximbaz @0xACE @KlzXS does anyone have a mac? Can you guys please try it out?
> 
> @zmwangx looks like this _batch rename entries in current dir_ issue is seen exclusively on macOS. Would it be possible for you to try it once?
> 
> Steps:
> 
> ```
> - export NNN_USE_EDITOR=1
> - export VISUAL=vim
> - run nnn
> - press r
> - rename some files (do not add or delete any)
> - :wq
> - see if the files are renamed
> ```

It's working for me too.
- nnn v2.9
- macOS Mojave 10.14.6
- iTerm2 v3.3.7
- Fish shell v3.0.2.

**Comment by jarun** [comment]
Thanks @dangerware for confirming!

**Comment by zmwangx** [comment]
Sorry for the late reply. I can't reproduce. I also grokked the code, `batchrenamecmd` looks pretty portable to me, should work on both GNU userland and BSD userland. Moreover, I can't seem to find a code path that would spawn editor and *then* print `MSG_FAILED`; the only possible return value of `batch_rename` after spawning the editor seems to be `true`, so even if there's something funny with the shell script it shouldn't print "failed".

**Comment by zmwangx** [comment]
> Moreover, I can't seem to find a code path that would spawn editor and then print MSG_FAILED

Oh never mind the nonsense, I clearly overlooked the effect of the `goto finish` lines. So either the tmpfile can't be opened after editing, or the editing process changed the line count.

**Comment by jarun** [comment]
Thanks a lot @zmwangx!

**Comment by Brixy** [comment]
Sorry for my late reply.

Thank you very much, guys, for your efforts!
