### ISSUE TITLE
Undefined clock_gettime() on CentOS 6

### ISSUE THREAD

**Issue by sjmulder** [jarun/nnn#453]
When built on CentOS 6:

```
cc -I/usr/pkg/include -D_XOPEN_SOURCE_EXTENDED=1 -I/usr/pkg/include/ncurses -pipe -O2 -pipe -O2 -D_FORTIFY_SOURCE=2 -I/usr/pkg/include -D_XOPEN_SOURCE_EXTENDED=1 -I/usr/pkg/include/ncurses -Wall -Wextra   -L/usr/pkg/lib -Wl,-R/usr/pkg/lib -o nnn src/nnn.c -lreadline -lncursesw
/tmp/ccCwUFuM.o: In function `browse':
nnn.c:(.text+0x5430): undefined reference to `clock_gettime'
```

This can be fixed by adding `-lrt`, which that glibc version's man page says is required for the clock functions. I'll send a PR shortly.

**Comment by jarun** [comment]
Thanks! Please raise the PR.

**Comment by jarun** [comment]
Closed as we do not have to support distros which have several newer releases available.

**Comment by sjmulder** [comment]
It's still under support. It still gets updated. We support it in pkgsrc. It's a small fix (needs an if-not-Darwin though).

**Comment by jarun** [comment]
> We support it in pkgsrc

I see.

> needs an if-not-Darwin though

where? In your PR I don't see this.

**Comment by jarun** [comment]
My problem is - to support a older library we can't add a library dependency in Makefile for all other distros where it's redundant.

**Comment by jarun** [comment]
Why don't you patch the Makefile downstream specifically for CentOS 6? Newer distros do note require `-lrt` and I have a problem adding a library dependency for this.

**Comment by jarun** [comment]
In fact LDLIBS is additive. I tried the following:

    export LDLIBS=-lrt
    make
    cc  -Wall -Wextra -O3 -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw  -o nnn src/nnn.c -lrt -lreadline -lncursesw -ltinfo

as you see, -lrt is picked.

**Comment by sjmulder** [comment]
> where? In your PR I don't see this.

Haven't done it yet; at work.

>  add a library dependency

librt is part of GNU libc

> In fact LDLIBS is additive

Yeah it is.
___

This thing does show how unportable plain Makefiles are without some sort of feature-detecting configure system. It's whack-a-mole.

**Comment by jarun** [comment]
> librt is part of GNU libc

How about clang or musl? Would this explicit linkage work? I think having `-lrt` pre-added in LDLIBS is a better option.

**Comment by sjmulder** [comment]
> How about clang

Compiler is separate from libc. Musl ships librt. The curiosity really is that Darwin doesn't.

One can't be completely watertight without a configure script, but I think linking librt on Linux (and Linux only) comes closest.

**Comment by jarun** [comment]
> One can't be completely watertight without a configure script, but I think linking librt on Linux (and Linux only) comes closest.

Done!

**Comment by sjmulder** [comment]
> > One can't be completely watertight without a configure script, but I think linking librt on Linux (and Linux only) comes closest.
> 
> Done!

Sorry, where? This isn't happening now.

**Comment by jarun** [comment]
I meant I concur with what you said. However, this case of CentOS 6 I would prefer you set LDLIBS to -lrt before calling `make` for `nnn`.

**Comment by jarun** [comment]
Out of all distro releases so far only CentOS 6 needs -lrt. We can make an exception I guess OR a patch for Makefile.

**Comment by sjmulder** [comment]
Ok, cool :)

**Comment by jarun** [comment]
> Oh, sure. I don't think it hurts to link librt on Linux, but if you'd rather not that's all for you to decide

@sjmulder if you take a look at this conversation this is the third time I am saying that I would prefer this to be handled downstream. A possible approach is to have `-lrt` in `$LDLIBS`.

`-lrt` is required specifically for a very old distro release CentOS 6. I do not want to add `-lrt` in Makefile for all other distros _where it is not required_, whether it hurts or not is a different thing.

That's also the reason I closed this defect earlier as I do not want to keep a defect open where there are no expected code changes in `nnn`.

Am I missing something?

**Comment by sjmulder** [comment]
I'm literally saying that if you prefer to not do it in the Makefile then I'm happy with that, there's nothing to argue about I think.

**Comment by jarun** [comment]
Ok. We were both saying the same thing.
