### ISSUE TITLE
[Feature request] Allow running command (Ctrl+S) on current selection or file/folder under current cursor position

### ISSUE THREAD

**Issue by Kabouik** [jarun/nnn#456]
Unless I missed it, running a command from `nnn` using `Ctrl+S` ignores the current selection or file currently highlighted. It would be very useful to allow using arguments like `$1` to run the command on the highlighted file.

For instance, I have a script that uploads images to 0x0.st and expects a file name as argument. To use it with the Nautilus scripts feature, I just had to add `$1` in the script to make it recognize the current selection and use it as file name, therefore the script automatically runs on the current file and uploads it. I think it could be useful for many commands and scripts, like `ffsend` to mention just one, and it would be worth adding a way to output the selection as argument for commands run from `nnn`.

#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Xubuntu 18.04 ran from chroot in SailfishOS
[x] Desktop Environment: xfce4
[x] Terminal Emulator: Tilix
[x] Shell: Bash
[ ] Custom desktop opener (if applicable):
[ ] Issue exists on `nnn` master

**Comment by KlzXS** [comment]
The currently hovered over entry is available as `$nnn` and the selection can be found as a `\0` separated list in `$XDG_CONFIG_HOME/nnn/.selection` or `$HOME/.config/nnn/.selection` depending on how you have your environment variables set.

**Comment by jarun** [comment]
All this info is available in the Wiki: https://github.com/jarun/nnn/wiki

**Comment by Kabouik** [comment]
Somehow this does not seem to work for me, `$nnn` seems to be empty. But surely I did something wrong because I noticed I have no `~/nnn` or `~/.config/nnn` directories. This is nnn 2.2., which I think I installed using `apt`. I'll look into it later, I am running out of battery right now.

**Comment by jarun** [comment]
> This is nnn 2.2

Use v2.9 or master.

**Comment by Kabouik** [comment]
Oh excellent, thanks, I have no idea my version was so different. Everything changed, even keybindings, and `$nnn` works now. Sorry for the noise.
