### ISSUE TITLE
using old style pager and editor

### ISSUE THREAD

**Issue by mutable-dan** [jarun/nnn#462]
question:
I've tried many options and can not recreate some of the older functionality where you could just press p or e to get the pager or vim.

is it possbile to do w/o plugins?

thanks

**Comment by jarun** [comment]
Please see issue #446.

We have revived `e` and it will be back in next release. However, to use PAGER you will have to use the _run cmd as plugin_ method. Examples: https://github.com/jarun/nnn/tree/master/plugins#some-useful-key-command-examples

**Comment by mutable-dan** [comment]
nice, thx

**Comment by artkpv** [comment]
Finally, found this. Had this issue also
