### ISSUE TITLE
Selected "+" disappear on redraw

### ISSUE THREAD

**Issue by Eluminae** [jarun/nnn#464]
Hello there,
I love nnn but I got an annoying issue, 

All is in the title.
Which is really an issue on wm as i3/sway when opening file will redimension window and force redraw.

**Comment by 0xACE** [comment]
I'm not sure what `SEL_SEL` is doing to disable redrawing. So I can't comment on a solution atm.

**Comment by jarun** [comment]
@Eluminae 

nnn version? opener?

I do see this when I open a file in a new tab or a cli app which forces a redraw. However not when the file opens in a GUI app like smplayer.

Workflow wise, I think it makes sense to complete your selection before opening a file. At least to me it doesn't seem _annoying_.

**Comment by jarun** [comment]
I closed the issue as this cannot be handled smply. Say you have a filter applied. You have some files selected. When the reload happens, the dir contents are re-read and everything it listed. So the only way to re-select is to match every path entry in selection with every file path being loaded.

Note that we also allow cross-dir and cross-context selection which is the real cause we don't want to do this extra processing. That's a massive improvement on any other file manager you may have used so far and we want to have that feature. So probably see if you can change the habit of opening files when selecting. As I mentioned, for me this occurs only when I use open text file in new tab. The other case (open in a cli app) is in fact, obvious so I won't say it's an issue.

**Comment by Eluminae** [comment]
> nnn version? opener?

Master build, and I'm opening images with feh.

* When browsing folder images named as "20200207070648.jpg"
* I open this image
* I close feh
* I press space to select the image
* I open the next image
* I close feh and my other selected images indicator disappeared.

I do not want to delete files when I'm not sure if I miss click somewhere.
So this workflow cannot be done with nnn which I regret.

I'm totally aware of the global selection feature which is awesome. I definitely would like the "match path in selection list when drawing" fix. This would be awesome when browsing back and forward and listing again the selected files.

**Comment by Eluminae** [comment]
Where is the "list selected path" feature?

**Comment by Eluminae** [comment]
I'm sorry but I think it miss something. Browsing trigger redraw and this prevent the user to know which file is selected. I cannot trust nnn when I'm cleaning, moving, deleting files. I got no way to know what I'm doing. Some weeks ago I just throw away a tons of files by error. I had to go in my backups to retrieve them.

**Comment by jarun** [comment]
> I cannot trust nnn when I'm cleaning, moving, deleting files.

Files you have selected so far will be cleaned, moved or deleted.

If your workflow involves this refresh frequently, use the list and edit selection feature before running an operation involving selection. On master, it's the key `E`.

**Comment by Eluminae** [comment]
> On master, it's the key `E`.

Oh right! Amazing. This will help me a lot. ty ! :)

**Comment by jarun** [comment]
Have fun!

**Comment by 0xACE** [comment]
@Eluminae just a tip, mind you, and only for a minute:

1. `sxiv -o * > markedfiles`
2. hit `ENTER` to see thumbnails
3. inspect your images and mark them with `right click` or `m` (A small tick appears for the marked images)

for further tricks read `man sxiv` or look around. If you insist on `feh` I know something similiar can be done there too, but you'd have to read `man feh` as I don't remember it by heart.

**Alternatively** if you insist: make the terminal window `float` or w/e your window manager calls it...

**Comment by Eluminae** [comment]
> 1. `sxiv -o * > markedfiles`
> 2. hit `ENTER` to see thumbnails
> 3. inspect your images and mark them with `right click` or `m` (A small tick appears for the marked images)

Amazing! Really cool. Thanks a lot for the tip

> If you insist on `feh` I know something similiar can be done

I'd have a look later. This could be cool too

**Comment by jarun** [comment]
@Eluminae I noticed something interesting today. Reminded me of your issue. Can you confirm if the following works for you?

- set [`nuke`](https://github.com/jarun/nnn/blob/master/plugins/nuke) as your opener (see in-file instructions)
- install [`viu`](https://github.com/atanunq/viu)

Note: `nuke` uses `viu` as the default image viewer.

With this, can you confirm if selection and viewing works together for you? For me it works using xfce4-terminal on XFCE. The selections stay and I can view the images in the terminal. If it works for you as well, we will document this as the standard procedure.

**Comment by Eluminae** [comment]
> With this, can you confirm if selection and viewing works together for you?

Yes it works :)

**Comment by jarun** [comment]
Awesome!

**Comment by Eluminae** [comment]
Nuke seems an interesting script but I do not recommend hard coding
apps preference. I should recommend using mailcap as file seeing and
editing tool. run-mailcap is what I use atm and it made me the happier
person ever. Maybe nnn should recommend a basic .mailcap ?

**Comment by jarun** [comment]
`nuke` is a sample. From the description:

```
Description: Sample script to play files in apps by file type or mime
```

Can you share your sample config file for mailcap? I would like to try it out.

**Comment by jarun** [comment]
I took a look at the manpage. Even with metamail you have to specify the app which is to be used to open a mime type.

**Comment by Eluminae** [comment]
> Can you share your sample config file for mailcap? I would like to try it out.

Yup, you can find mine at https://hg.sr.ht/~reedwade/dotfiles/browse/default/.mailcap
This is not perfect atm, I add missing mime types over time

**Comment by Eluminae** [comment]
> I took a look at the manpage. Even with metamail you have to specify the app which is to be used to open a mime type.

What do you mean?

**Comment by jarun** [comment]
I mean the config file requires one to specify the mime-app pair...

**Comment by Eluminae** [comment]
In fact, I think the -c parameter solved my problem with feh too :)

**Comment by jarun** [comment]
Cool!

**Comment by jarun** [comment]
@Eluminae persistent selection marker is on master now and will be available in the next release. So you shouldn't need any additional hacks. Probably you can try it and confirm.
