### ISSUE TITLE
Odd behavior when canceling search and changing sort

### ISSUE THREAD

**Issue by AN3223** [jarun/nnn#467]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: void linux
[x] Desktop Environment: sway
[x] Terminal Emulator: alacritty
[x] Shell: busybox ash
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master: yes

#### Exact steps to reproduce the issue
1. Search for something, i.e. /nnn
2. Cancel search with ESC
3. Clear screen with ^L
4. Toggle sort time with tt (also occurs when sorting by extension/version/size)

#### Expected behavior:

Should just sort the files currently being displayed.

#### Actual behavior

The canceled search is performed again prior to the files being sorted.

**Comment by 0xACE** [comment]
Haha, the past few weeks I was thinking it was my local branch that was causing this issue locally... This problem has been around since either december or early january, I can't remember anymore.

Nice find!

**Comment by jarun** [comment]
> Clear screen with ^L

All the directory contents will be reloaded at this step.
^L is not to clear screen, it's a full redraw when you are not at a prompt. AND if you are at a prompt it will only clear the prompt but won't reload dir contents.

Please refer to the program help.

The workflow should be:

1. Search for something, i.e. /nnn
2. Cancel search with ESC
3. Toggle sort time with tt (also occurs when sorting by extension/version/size)

**Comment by AN3223** [comment]
> > Clear screen with ^L
>
> All the directory contents will be reloaded at this step.
> ^L is not to clear screen, it's a full redraw when you are not at a prompt. AND if you are at a prompt it will only clear the prompt but won't reload dir contents.

You're right. I meant to say redraw instead of clear.

> The workflow should be:
>
> 1. Search for something, i.e. /nnn
> 2. Cancel search with ESC
> 3. Toggle sort time with tt (also occurs when sorting by extension/version/size)

The problem is that this provides the same result. The desired behavior
is to sort the contents of a directory, not to sort the results of a
search. Am I missing something here?

**Comment by jarun** [comment]
I am on master. With just the 3 steps I do not see the complete directory reloaded.

Can you please test on master?

**Comment by jarun** [comment]
> Should just sort the files currently being displayed.

This is exactly what I see on master.

> Cancel search with ESC
> The canceled search is performed again prior to the files being sorted.

Oh, your expectation is wrong. I would suggest you to read help and documentation in Wiki. `Esc` exits the filter prompt. It doesn't cancel/clear the filter.

To actually clear the filter:

when your filter shows `/nnn`, press `^L`.

**Comment by jarun** [comment]
Please test with commit eaba594a9e713b35eafd1e71ac82f9fc0fb42585.

Now if you run your original steps, when you press `^L` in the 3rd step, the filter will be cleared. In your 4th step you should see the full dir contents sorted (the filter will not be applied).

**Comment by AN3223** [comment]
> Please test with commit eaba594a9e713b35eafd1e71ac82f9fc0fb42585.
>
> Now if you run your original steps, when you press `^L` in the 3rd step, the filter will be cleared. In your 4th step you should see the full dir contents sorted (the filter will not be applied).

Yes, this is now the behavior that I expect.

**Comment by jarun** [comment]
Thanks for the defect report!
