### ISSUE TITLE
Doesn't work via cron

### ISSUE THREAD

**Issue by aryadovoy** [jarun/nnn#468]
I started tmux-session with `nnn` by `cron`, but result is `sh: command not found: nnn` or `zsh: command not found: nnn` (depends on shell). Another apps work fine.

`crontab -e -u aryadovoy`:
```
SHELL=/usr/bin/zsh

@reboot /home/aryadovoy/startup.sh
```
`startup.sh`:
```
#!/bin/bash

source /home/aryadovoy/.zshrc
source /home/aryadovoy/.profile

tmux new-session -d -s main
tmux send-keys 'nnn' C-m
tmux detach
```

v2.9

**Comment by jarun** [comment]
What is the output of

    type nnn

**Comment by aryadovoy** [comment]
> What is the output of
> 
> ```
> type nnn
> ```

`nnn not found`
But I can start it by `/usr/local/bin/nnn` or from outside of cron-tmux-session.

**Comment by jarun** [comment]
Probably `/usr/local/bin/` is not in your PATH. What is the output of:

    echo $PATH

**Comment by aryadovoy** [comment]
> Probably `/usr/local/bin/` is not in your PATH

Yes, you're right. The PATH is different from `cron`.  Thanks!

**Comment by jarun** [comment]
You can add `/usr/local/bin/` to `PATH` and try: https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path

BTW, when you like a project, consider awarding a star. People spending their free time on the project feel good.
