### ISSUE TITLE
Using the -p option: the focus doesn't move automatically to next file after selection

### ISSUE THREAD

**Issue by timonson** [jarun/nnn#470]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Arch
[x] Desktop Environment: i3
[x] Terminal Emulator: termite
[x] Shell: bash
Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. Enter nnn via `nnn -p -`
2. Press the `space` key while the focus is on an arbitrary file

**Expected behavior:**
nnn selects the file and the focus goes to the next file below the selected file.

**Actual behavior:**
nnn selects the file and the focus stays at the selected file.

**Comment by jarun** [comment]
This is intentional. Pressing `Enter` on a file in the picker mode _picks_ the file and exits `nnn`.

`nnn.vim` uses this feature: https://github.com/mcchrish/nnn.vim#usage

The workflow cannot be disturbed.

**Comment by NovaDev94** [comment]
@jarun Sorry but I just stumbled upon this, it's fairly annoying cuz I got used to Space selecting and going to next line. And I don't understand how keeping the normal Space behavior gonna mess up nnn.vim either (I'm using it).

**Comment by jarun** [comment]
Say you want to pick only a single file and use space on it. With auto-proceed enabled the next file is hovered. If you accidentally press Enter, both the files are picked. And generally in picker mode people choose a single file.
