### ISSUE TITLE
Slow context switch when using MTP

### ISSUE THREAD

**Issue by raaffaaeell** [jarun/nnn#471]
[ ] Operating System: FEDORA 30
[ ] Desktop Environment: i3
[ ] Terminal Emulator: KITTY
[ ] Shell: BASH
[X] Issue exists on `nnn` master

More like a question.

I understand that browsing cellphone can be a bit slower, but right now when trying to use more than one context, it always hangs when going back to the one on the mtp folder. Is this behaviour expected ?

Using 2 nnns kind works, I can select in one and paste in the other that is already in the mtp folder, but would be nice using only one window

**Comment by KlzXS** [comment]
Each time you switch back to a context we get a new listing of files in the directory and that is, as you said, slow. There isn't much we can do about this.

My advice to you would be to try and not cause unnecessary refreshes. You can also use a terminal multiplexer to have two `nnn`s in the same window if you want.

https://github.com/jarun/nnn/wiki#dual-pane

**Comment by jarun** [comment]
I use the following procedure myself to connect to my mobile: https://gist.github.com/jarun/660fd1d5e79e1a4038de8ba5f2e1a513

It's should be faster depending on your device capabilities.

**Comment by jarun** [comment]
Ahh OK. Forget what I said. @KlzXS is right.

**Comment by raaffaaeell** [comment]
Ah thanks for the clarification, I was just looking to confirm it. Cause I have an external hd and the first time I want to look at the downloads folder it takes a while, but after it loaded it's fast, but I figured it should have something to do with it being MTP, like it doesnt "save" the state.

Thanks for the clarification
