### ISSUE TITLE
Static binary release archive faulty

### ISSUE THREAD

**Issue by tommyalatalo** [jarun/nnn#474]
There is something wrong with the static binary release archive "nnn-3.0-static-3.0.x86-64.tar.gz".
On opening this I get an error from my archive manager `"not in gzip format"`.

In a terminal it works to run `tar -xvf nnn-3.0-static-3.0.x86-64.tar.gz`, but I'm assuming it's doing some kind fallback because loading the archive with zinit also throws the "not in gzip format" error.

The packaging of this archive needs another look.

**Comment by jarun** [comment]
I will re-upload the package as well.

**Comment by jarun** [comment]
All good!
