### ISSUE TITLE
Feature request: NNN_OPTIONS variable

### ISSUE THREAD

**Issue by uffejakobsen** [jarun/nnn#475]
Feature request: NNN_OPTIONS variable

Hi,
It would be nice if nnn had support for a variable (NNN_OPTIONS)
This would - if set - specify the (default) command line options to nnn 

just with simple letters - much like the LESS env var works

**Comment by jarun** [comment]
But why can't you use an alias?

**Comment by jarun** [comment]
I feel aliases are handier. We try to have as few config env vars in `nnn` as possible.

**Comment by uffejakobsen** [comment]
Long story
I work at a lot of different systems using SSH
SSH can allow certain env vars (restricted through patterns) to be exported from the client to the server. 
Allowing all env vars named NNN_* actually saves me a lot of work keeping configurations in sync on all systems - and in this scenario an env var with default nnn options would be handy.

**Comment by jarun** [comment]
Thanks for explaining. Please raise a PR in that case.

**Comment by uffejakobsen** [comment]
Well - I actually sent you a pull request with my suggestion on how to add the NNN_OPTS feature :-)

**Comment by uffejakobsen** [comment]
Solved by #476 - thanks :+1:

**Comment by jarun** [comment]
Do award a star to the project if you feel it's worth.
