### ISSUE TITLE
shortcut with 'alt' as modifier key

### ISSUE THREAD

**Issue by plejzner** [jarun/nnn#479]
Hi, thanks for this little software gem :)

I would like to define keyboard shortcuts with 'alt' as modifier key. Is it possible? There is no example in nnn.h i could copy..

**Comment by jarun** [comment]
We've explored this before and it seemed like there's no portable way to do this: https://stackoverflow.com/questions/406933/how-to-intercept-special-alt-ctrl-key-press

**Comment by jarun** [comment]
But do feel free to explore if you can find a way. It would help!

**Comment by jarun** [comment]
Recently we have added support for handling Alt combinations as plugins.
