### ISSUE TITLE
Selection becomes invisible in certain situations

### ISSUE THREAD

**Issue by foxcpp** [jarun/nnn#480]
#### Environment details

[x] Operating System: Linux
[x] Desktop Environment: sway
[x] Terminal Emulator: [termite](https://github.com/thestinger/termite/)
[x] Shell: fish
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

##### Case 1

1. Launch nnn
2. Select some files by pressing Space
3. Switch to the second context
4. Switch back to the first context
5. Notice missing `+` characters next to selected files
6. Observe that the selection is still here by pressing `E`

**Comment by jarun** [comment]
This is expected. Please see the wiki section on selection: https://github.com/jarun/nnn/wiki#selection

**Comment by jarun** [comment]
Also, the `E` keybind is provided for editing a selection after you lose the `+`. The reason the `+` disappears is `nnn` supports selection across dirs and contexts (which is probably not available in any other FM I am aware of) and it supports selecting thousands of files. We do not want to match dir contents with every selected file while loading a dir.

**Comment by jarun** [comment]
@foxcpp persistent selection marker is on master now and will be available in the next release. Try it out!
