### ISSUE TITLE
Why not support Windows?

### ISSUE THREAD

**Issue by jiangjianshan** [jarun/nnn#481]
Hello,
     I'm ready to use nnn.vim from https://github.com/mcchrish/nnn.vim. But it said must install nnn first. I have found nnn seems not support Windows. It is possible to implement it?

**Comment by jarun** [comment]
Hi,

`nnn` uses ncursesw which doesn't work on Windows _directly_. I myself have to use Windows due to professional reasons and I use `nnn` and `nnn.vim` on WSL. `nnn` works in the Cygwin env as well.
