### ISSUE TITLE
^G causes crash

### ISSUE THREAD

**Issue by ada-43** [jarun/nnn#486]
[x] Issue exists on `nnn` master

^G causes crash "free(): invalid pointer".

Regression was introduced 2020-03-01 in commit a54a23eae53f024b1ae5fbebaa4567d167ca8884 "Minor refactor"
```
-	cfgdir = (char *)malloc(len);
+	cfgdir = (char *)malloc(len - 9); /* Subtract length of sessions */
```

**Comment by jarun** [comment]
@ada-43 can you please confirm if this is fixed in commit d97d1522694684fc86af8e553c55b10b6321b7b7?

**Comment by ada-43** [comment]
Issue is not fixed.
`(len - 8)` crashes.
`(len - 3)` crashes too.
`(len - 2)` apparently ok.

**Comment by jarun** [comment]
Thanks for testing ti! I have reverted the change.
