### ISSUE TITLE
batchrenamer issues

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#489]
I integrated the plugin with the following patch:

```diff
diff --git a/plugins/README.md b/plugins/README.md
index b93fbf5..0728fbf 100644
--- a/plugins/README.md
+++ b/plugins/README.md
@@ -27,6 +27,7 @@ Plugins are installed to `${XDG_CONFIG_HOME:-$HOME/.config}/nnn/plugins`.
 | Plugin (a-z) | Description | Lang | Deps |
 | --- | --- | --- | --- |
 | autojump | Navigate to dir/path (**autojump stores navigation patterns**) | sh | autojump |
+| batchrename | Batch file renamer | sh | mktemp |
 | boom | Play random music from dir | sh | [moc](http://moc.daper.net/) |
 | dups | List non-empty duplicate files in current dir | sh | find, md5sum,<br>sort uniq xargs |
 | chksum | Create and verify checksums | sh | md5sum,<br>sha256sum |
diff --git a/src/nnn.c b/src/nnn.c
index 9633c46..c490e22 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -428,6 +428,7 @@ static uchar g_states;
 #define UTIL_FZY 16
 #define UTIL_NTFY 17
 #define UTIL_CBCP 18
+#define UTIL_BATCHRENAME 19
 
 /* Utilities to open files, run actions */
 static char * const utils[] = {
@@ -466,6 +467,7 @@ static char * const utils[] = {
 	"fzy",
 	".ntfy",
 	".cbcp",
+	"batchrename",
 };
 
 /* Common strings */
@@ -608,16 +610,13 @@ static char mv[] = "mv -i";
 /* Patterns */
 #define P_CPMVFMT 0
 #define P_CPMVRNM 1
-#define P_BATCHRNM 2
-#define P_ARCHIVE 3
-#define P_REPLACE 4
+#define P_ARCHIVE 2
+#define P_REPLACE 3
 
 static const char * const patterns[] = {
 	"sed -i 's|^\\(\\(.*/\\)\\(.*\\)$\\)|#\\1\\n\\3|' %s",
 	"sed 's|^\\([^#][^/]\\?.*\\)$|%s/\\1|;s|^#\\(/.*\\)$|\\1|' "
 		"%s | tr '\\n' '\\0' | xargs -0 -n2 sh -c '%s \"$0\" \"$@\" < /dev/tty'",
-	"paste -d'\n' %s %s | sed 'N; /^\\(.*\\)\\n\\1$/!p;d' | "
-		"tr '\n' '\\0' | xargs -0 -n2 mv 2>/dev/null",
 	"\\.(bz|bz2|gz|tar|taz|tbz|tbz2|tgz|z|zip)$",
 	"sed -i 's|^%s\\(.*\\)$|%s\\1|' %s",
 };
@@ -676,7 +675,7 @@ static void move_cursor(int target, int ignore_scrolloff);
 static inline bool getutil(char *util);
 static size_t mkpath(const char *dir, const char *name, char *out);
 static char *xgetenv(const char *name, char *fallback);
-static void plugscript(const char *plugin, char *newpath, uchar flags);
+static void plugscript(const char *plugin, char *newpath, const char *path, uchar flags);
 
 /* Functions */
 
@@ -1840,78 +1839,6 @@ static bool cpmvrm_selection(enum action sel, char *path, int *presel)
 	return TRUE;
 }
 
-static bool batch_rename(const char *path)
-{
-	int fd1, fd2, i;
-	uint count = 0, lines = 0;
-	bool dir = FALSE, ret = FALSE;
-	char foriginal[TMP_LEN_MAX] = {0};
-	char buf[sizeof(patterns[P_BATCHRNM]) + (PATH_MAX << 1)];
-
-	i = get_cur_or_sel();
-	if (!i)
-		return ret;
-
-	if (i == 'c') { /* Rename entries in current dir */
-		selbufpos = 0;
-		dir = TRUE;
-	}
-
-	fd1 = create_tmp_file();
-	if (fd1 == -1)
-		return ret;
-
-	xstrlcpy(foriginal, g_tmpfpath, strlen(g_tmpfpath)+1);
-
-	fd2 = create_tmp_file();
-	if (fd2 == -1) {
-		unlink(foriginal);
-		close(fd1);
-		return ret;
-	}
-
-	if (dir)
-		for (i = 0; i < ndents; ++i)
-			appendfpath(dents[i].name, NAME_MAX);
-
-	seltofile(fd1, &count);
-	seltofile(fd2, NULL);
-	close(fd2);
-
-	if (dir) /* Don't retain dir entries in selection */
-		selbufpos = 0;
-
-	spawn((cfg.waitedit ? enveditor : editor), g_tmpfpath, NULL, path, F_CLI);
-
-	/* Reopen file descriptor to get updated contents */
-	fd2 = open(g_tmpfpath, O_RDONLY);
-	if (fd2 == -1)
-		goto finish;
-
-	lines = lines_in_file(fd2, buf, sizeof(buf));
-	DPRINTF_U(count);
-	DPRINTF_U(lines);
-	if (!lines || (count != lines)) {
-		DPRINTF_S("cannot delete files");
-		goto finish;
-	}
-
-	snprintf(buf, sizeof(buf), patterns[P_BATCHRNM], foriginal, g_tmpfpath);
-	spawn(utils[UTIL_SH_EXEC], buf, NULL, path, F_CLI);
-	ret = TRUE;
-
-finish:
-	if (fd1 >= 0)
-		close(fd1);
-	unlink(foriginal);
-
-	if (fd2 >= 0)
-		close(fd2);
-	unlink(g_tmpfpath);
-
-	return ret;
-}
-
 static void get_archive_cmd(char *cmd, char *archive)
 {
 	uchar i = 3;
@@ -4201,11 +4128,11 @@ static bool run_selected_plugin(char **path, const char *file, char *newpath, ch
 	return TRUE;
 }
 
-static void plugscript(const char *plugin, char *newpath, uchar flags)
+static void plugscript(const char *plugin, char *newpath, const char *path, uchar flags)
 {
 	mkpath(plugindir, plugin, newpath);
 	if (!access(newpath, X_OK))
-		spawn(newpath, NULL, NULL, NULL, flags);
+		spawn(newpath, NULL, NULL, path, flags);
 }
 
 static void launch_app(const char *path, char *newpath)
@@ -5590,11 +5517,7 @@ nochange:
 				break;
 			case SEL_RENAMEMUL:
 				endselection();
-
-				if (!batch_rename(path)) {
-					printwait(messages[MSG_FAILED], &presel);
-					goto nochange;
-				}
+				plugscript(utils[UTIL_BATCHRENAME], newpath, path, F_CLI);
 				refresh = TRUE;
 				break;
 			case SEL_HELP:
@@ -5647,7 +5570,7 @@ nochange:
 			}
 
 			if (cfg.x11)
-				plugscript(utils[UTIL_CBCP], newpath, F_NOWAIT | F_NOTRACE);
+				plugscript(utils[UTIL_CBCP], newpath, NULL, F_NOWAIT | F_NOTRACE);
 
 			if (!nselected)
 				unlink(selpath);
@@ -5723,7 +5646,7 @@ nochange:
 
 			writesel(pselbuf, selbufpos - 1); /* Truncate NULL from end */
 			if (cfg.x11)
-				plugscript(utils[UTIL_CBCP], newpath, F_NOWAIT | F_NOTRACE);
+				plugscript(utils[UTIL_CBCP], newpath, NULL, F_NOWAIT | F_NOTRACE);
 			continue;
 		case SEL_SELEDIT:
 			r = editselection();
@@ -5732,7 +5655,7 @@ nochange:
 				printwait(messages[r], &presel);
 			} else {
 				if (cfg.x11)
-					plugscript(utils[UTIL_CBCP], newpath, F_NOWAIT | F_NOTRACE);
+					plugscript(utils[UTIL_CBCP], newpath, NULL, F_NOWAIT | F_NOTRACE);
 				cfg.filtermode ?  presel = FILTER : statusbar(path);
 			}
 			goto nochange;
@@ -5778,7 +5701,7 @@ nochange:
 
 			/* Show notification on operation complete */
 			if (cfg.x11)
-				plugscript(utils[UTIL_NTFY], newpath, F_NOWAIT | F_NOTRACE);
+				plugscript(utils[UTIL_NTFY], newpath, NULL, F_NOWAIT | F_NOTRACE);
 
 			if (ndents)
 				copycurname();
```

Now I enter the `nnn/misc` dir and edit as below:

```sh
1 ../auto-completion
2 ./haiku1
3 ./natool
4 ./packagecore
5 ./quitcd1
6 ./test
```

and get the following output:

```
$ n
1 files (  4.0 KiB) copied in 0.0 seconds (573.0 KiB/s).
Rename 'c'urrent / 's'election? c
'./auto-completion' -> '../auto-completion'
sed: -e expression #1, char 31: unknown option to `s'
sed: -e expression #1, char 31: unknown option to `s'
sed: -e expression #1, char 31: unknown option to `s'
sed: -e expression #1, char 31: unknown option to `s'
sed: -e expression #1, char 31: unknown option to `s'
sed: -e expression #1, char 31: unknown option to `s'
'./auto-completion' => '../auto-completion'
/home/vaio/.config/nnn/plugins/batchrename: unknown item number 2
/home/vaio/.config/nnn/plugins/batchrename: unknown item number 3
/home/vaio/.config/nnn/plugins/batchrename: unknown item number 4
/home/vaio/.config/nnn/plugins/batchrename: unknown item number 5
/home/vaio/.config/nnn/plugins/batchrename: unknown item number 6
```

`auto-completion` is moved to the parent dir as exptected. But `haiku` and `quitcd` remain unchanged.

@KlzXS please take a look.

@0xACE and @maximbaz we will keep this issue open for a while to fix `batchrenamer` issues.

**Comment by KlzXS** [comment]
Try it now, it should work as expected.

**Comment by jarun** [comment]
Where's the change?

**Comment by KlzXS** [comment]
Ohh... You merged the thing. My bad.

**Comment by KlzXS** [comment]
I opened a PR with the fix.

**Comment by jarun** [comment]
No problem! I'll commit the changes to invoke tke plugin if available and we can all test the plugin using the diff from PR #490.

**Comment by jarun** [comment]
@KlzXS with latest changes...

I have `te st1` within `nnn` dir.

I edited as:

    10 misc/test1
to move the dir under `misc`. I get the following error:

    /home/vaio/.config/nnn/plugins/batchrename: ./test1 does not exit

**Comment by jarun** [comment]
In fact I can't move `te st1` to `test` as well.

**Comment by jarun** [comment]
Works fine for me so far.

@0xACE and @maximbaz can you guys try the latest version?

**Comment by maximbaz** [comment]
Just tried, seems to work fine for me too - although I'll prefer to keep using the built-in version of the rename functionality, I don't feel missing any functionality that can be compensated by manually managing a separate rename plugin 🙂

**Comment by jarun** [comment]
> although I'll prefer to keep using the built-in version of the rename functionality

If the plugin is available, it will be used, else the in-built functionality. This is in commit f527dd1c6a6f2065ce9cdfb4337399021265631f.

For most users simple use-cases may suffice, but I've seen myself use-cases which need more powerful handling.

**Comment by jarun** [comment]
@KlzXS even if I don't change anything, something takes time if I run the script in my home dir. Is it due to the sorting? Can you check if the timing can be improved a bit?

**Comment by jarun** [comment]
In `/usr/bin` it takes more than 8/9 minutes! I have 1703 entries. I had to ^C when the CPU started noising...

I don't see any such lag with `vidir`.

Are we using the sorted intermediate file approach or doing the sorting in memory? Also post-edit do we sort using `sort` or something else?

**Comment by KlzXS** [comment]
I'll see what I can do about that, but I'm not really optimistic. The main thing I have my eyes set on would be all the "array" operations. Since POSIX shell doesn't support arrays (besides the arguments array) you have to use some hacks to get around that.

**Comment by jarun** [comment]
How about converting it to bash?

**Comment by KlzXS** [comment]
Maybe. I'd have to try it first.

**Comment by jarun** [comment]
Sure! Just check it out!

**Comment by jarun** [comment]
Instead of arrays (I am assuming this is indeed the use case), can we save the edited file in another sorted file and read-in the lines from original file and match?

So from original file, read first line and entry number should be 1. From second file read a line, if entry number is 1 match the names and rename if required.
Say the entry number in second file is 3. Then delete entries 1 and 2 from original file and go to entry number 3...

**Comment by KlzXS** [comment]
> Say the entry number in second file is 3. Then delete entries 1 and 2 from original file and go to entry number 3...

That could mean 2 and 3 were swapped, we don't know. Or 2 could be missing entirely meaning we should delete it.

Even then there are cases where the original values need to be modified, such as when the parent directory got moved and the child should be renamed as well.

I'll see what works best.

**Comment by jarun** [comment]
> That could mean 2 and 3 were swapped, we don't know. Or 2 could be missing entirely meaning we should delete it.

We have already sorted and stored in the file after user edited. It can't be swapped.

> Even then there are cases where the original values need to be modified, such as when the parent directory got moved and the child should be renamed as well.

Maybe just see what vidir does in this case.

**Comment by KlzXS** [comment]
> Maybe just see what vidir does in this case.

That is handles like vidir.

> We have already sorted and stored in the file after user edited. It can't be swapped.

We don't currently sort the user edited file.

**Comment by KlzXS** [comment]
> How about converting it to bash?

Bash works wonders. The whole `/usr/bin`, where I have 4000 entries, can be opened and closed (without edits) in a fraction of a second.

> Instead of arrays (I am assuming this is indeed the use case), can we save the edited file in another sorted file and read-in the lines from original file and match?

There seems to be a problem where I can't write the original file quick enough, so it reports invalid numbers.

Do you want me to PR the bash version?

**Comment by jarun** [comment]
> Bash works wonders

Cool!

> Do you want me to PR the bash version?

Sure thing!

**Comment by jarun** [comment]
Probably we should also rename the plugin to indicate it's an internal one. Maybe `.nren`. At a point I considered making this mechanism as the fallback in `renamer` but I believe we have a much better standalone solution that doesn't need the user to go through installation woes.

**Comment by jarun** [comment]
> Maybe .nren.

Or `.nmv` perhaps...

**Comment by KlzXS** [comment]
Right. Just let me handle some edge cases and I'll submit it.

**Comment by jarun** [comment]
Take your time! I am locked indoor with family due to the current situation. Wishing things get back to normal every moment.

**Comment by KlzXS** [comment]
Checkout #495.

**Comment by jarun** [comment]
My earlier tests passed in flying colors! Merged.

**Comment by jarun** [comment]
This works well so far. I am closing the issue. If we find anything else we'll raise a new one.
