### ISSUE TITLE
`=` Launch app question

### ISSUE THREAD

**Issue by vijaygopal1234** [jarun/nnn#492]
https://github.com/jarun/nnn/blob/f527dd1c6a6f2065ce9cdfb4337399021265631f/src/nnn.c#L4235

I'm assuming `=` keybind is meant to start GUI programs. Why does it provide a "0" as an argument to the program? Am I using it wrong? Typing `=nautilus<Enter>` (or with dolphin) results in them opening with an error.

Additionally, I think some of the documentation is rather cryptic and requires me to look into the source code or use prior knowledge to make an inference. Are you open to contributions on that end? Examples include (m to select a range of files, double press m to clear), toggle proceed on open, etc.

**Comment by jarun** [comment]
> Typing =nautilus<Enter> (or with dolphin) results in them opening with an error

I think you don't have plugins installed. Please confirm if commit 02754205a295bbd57872be9a41df57f1a8289325 fixes the issue.

> I think some of the documentation is rather cryptic and requires me to look into the source code

Please visit the wiki. Your specific workflow is explained here: https://github.com/jarun/nnn/wiki#selection

**Comment by vijaygopal1234** [comment]
That seems to fix the error. Could you clarify what the intended use case of `=` is? It doesn't seem to change the `$PWD` or anything, just a generic GUI app launcher?

Regarding the link to the wiki, I did see it and I get it now! That was more of a comment for beginners, the man page and the help page descriptions for specific features are rather vague and difficult to understand. Rather than `launch app` maybe call it `launch GUI app`?

**Comment by jarun** [comment]
> It doesn't seem to change the $PWD or anything, just a generic GUI app launcher?

The 4th param to spawn is the path. And it's a GUI app launcher.

> That was more of a comment for beginners, the man page and the help page descriptions for specific features are rather vague and difficult to understand

Advanced usage if `nnn` is not possible without going through the Wiki. There are reasons we have to keep the help concise.

> Rather than launch app maybe call it launch GUI app?

The feature list does say `Launch GUI apps`. Again, we want to keep the in-program help concise.

**Comment by vijaygopal1234** [comment]
That's fair. Thank you for nnn!
