### ISSUE TITLE
The selection mark(s) (+) disappear after visting a directory

### ISSUE THREAD

**Issue by daniel-vera-g** [jarun/nnn#493]
[x] Operating System: Ubuntu 18.04.4 LTS
[x] Desktop Environment: GNOME 3
[x] Terminal Emulator: gnome-terminal
[x] Shell: zsh
[x] Custom desktop opener (if applicable): -
[x] Issue exists on `nnn` master: v3.0

#### Exact steps to reproduce the issue

1. Open `nnn`
2. Mark file(s)
3. Navigate directory
4. Go back to directory where selected file(s) live

https://asciinema.org/a/u6xKqescFI7dAkofp2mWe9Tn9

As you can see, the `+` marks do not show up after visiting the directory, but the file(s) are still selected and can f.ex be moved.

**Comment by 0xACE** [comment]
`nnn` doesn't support "remarking" items after the display has been manipulated.

Atm there are no plans to support it either because it comes at great cost to the simplicity of the source code.

This topic has been handled multiple times in these issues.

**Comment by daniel-vera-g** [comment]
> `nnn` doesn't support "remarking" items after the display has been manipulated.
> 
> Atm there are no plans to support it either because it comes at great cost to the simplicity of the source code.
> 
> This topic has been handled multiple times in these issues.

Ok. It's just confusing if you come back and cannot remember which files you marked. But if this has already been discussed, I should probably accept it.
Sorry for this "new" issue, but did not found related issues.

**Comment by 0xACE** [comment]
Well my branch is different from the official one, but there is a key you can hit to preview the selected file in a editable buffer... The previous discussions go over these things...

Also, do other file managers list what files you marked when you leave the view?

I have previously had plans on implementing extra features into `nnn`. One of which was to handle "remarking" files. But really, imho `nnn` has been working perfectly fine as is for a couple of months now. Therefore I no longer see the need of expanding extras onto what I consider to be a working product.

Anyhow feel free to close this issue when you are ready.

**Comment by jarun** [comment]
You don't have to remember. You can press `E` to view (and/or edit) the list of already selected files anytime).

**Comment by jarun** [comment]
@daniel-vera-g persistent selection marker is on master now and will be available in the next release. Try it out!
