### ISSUE TITLE
Feature request: no-history mode

### ISSUE THREAD

**Issue by zoxves** [jarun/nnn#496]
Is there any plans for no-history mode that leaves no traces in .config/nnn after exit? Could be implemented through command line argument.

**Comment by jarun** [comment]
What do you mean by _history_? If it's the .history file, either

- compile `nnn` with `O_NORL=1`, or
- use a shell function to remove it manunally after running `nnn`

The second way can also be used to remove any other files you don't want to retain.

**Comment by zoxves** [comment]
You mean recompile it without readline completely to get rid of one history-writing string?
Deleting it through script is a bit weird, I don't want it to be written in the first place, isn't "minimize read/writes" one of design goals?
I would try to do PR if it could be accepted.

**Comment by jarun** [comment]
You have a valid point. I have disabled history file usage by default. User has to use option `-f` now to use it.

**Comment by zoxves** [comment]
Oh, so quick. I've just baked PR, but I guess it's history now.
Thank you.

**Comment by jarun** [comment]
You are welcome!
