### ISSUE TITLE
Create command doesn't work on OpenBSD

### ISSUE THREAD

**Issue by vaygr** [jarun/nnn#50]
Recently added create command (`n`) results in the following error message:

> No traversal delimiter allowed

**Comment by jarun** [comment]
You cna't use delims like `/` or `\` while creating a new file/dir (as designed).
- Are you able to create files/dirs without these chars?
- Or nothing works?

**Comment by jarun** [comment]
Resolved at https://github.com/jarun/nnn/commit/8959a5b57dd75a0a0402fedd7a3705146631d419.

**Comment by vaygr** [comment]
Yeah, on Linux it worked perfectly fine, on OpenBSD it didn't at all. Turns out `basename()` implementation was slightly different there.

**Comment by jarun** [comment]
Got it! We have a native implementation on (x)dirname() sans this handicap but I never cared to extend it to basename().
