### ISSUE TITLE
Installed nnn but can seem to find it

### ISSUE THREAD

**Issue by SecretAgentAgentX** [jarun/nnn#500]
vvv

**Comment by jarun** [comment]
I can't understand the issue. There's just vvv in description.

**Comment by leovilok** [comment]
From the description before editing, I think he is looking for nnn in the KDE menu.
If you want that you'll have to make a `.desktop` file (you can copy [`ranger.desktop`](https://github.com/ranger/ranger/blob/master/doc/ranger.desktop) and replace `ranger` with `nnn` everywhere) and put it in `~/.local/share/applications` (or even `/usr/share/applications`).

**Comment by leovilok** [comment]
@SecretAgentAgentX try using [this .desktop file](https://github.com/leovilok/nnn/blob/desktop/nnn.desktop)

**Comment by 0xACE** [comment]
His link is broken, but this one works: https://github.com/leovilok/nnn/blob/desktop/misc/nnn.desktop
