### ISSUE TITLE
navigate-as-you-type issues

### ISSUE THREAD

**Issue by ghistes** [jarun/nnn#503]
[x ] Operating System: Linux (Debian testing)
[x] Desktop Environment: i3
[x] Terminal Emulator: tmux with urxvt 
[x] Shell: bash
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master: yes

#### Exact steps to reproduce the issue

When pressing "?" it says "^N  Nav-as-you-type toggle", which I interpret as Control-n toggels this feature. But when I start nnn and press Control-n nothing seems to happen.

When I start nnn in my home-directory via "nnn -n" I get an indication (or so I suppose) that navigate-as-you-type is active as it displays a "/" at the bottom.

In my home there are directories "test" and "Templates". When I enter "tes", it displays only these two directories, however it does not change into "test" as I would expect it to ("tes" does not match "Templates" and uniquely identifies "test"). Only after entering "test" does it cd into the "test"-directory.

It may very well be that I don't understand how this feature is supposed to work, but this is not intuitive to me.

**Comment by fes111-7** [comment]
> ("tes" does not match "Templates" and uniquely identifies "test")

I think "tes" is also matching the last three characters of "Templates".

**Comment by jarun** [comment]
> But when I start nnn and press Control-n nothing seems to happen.

You should see the `/` appear in the status bar.

> "test" and "Templates"

@fes111-7 explained it right.
