### ISSUE TITLE
nnn messes up my terminal-settings

### ISSUE THREAD

**Issue by ghistes** [jarun/nnn#504]
[ ] Operating System: Debian testing
[] Desktop Environment: i3
[ ] Terminal Emulator: tmux in urxvt
[ ] Shell: bash
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I have just compiled the current master and though I cannot give exact steps nnn frequently messes up my terminal so that after quitting nnn the terminal becomes unusable.

This did not happen when I last looked at it a few weeks back.

**Comment by KlzXS** [comment]
What do you mean it becomes unstable? Is it the thing where keypresses are seemingly swallowed into the void?

**Comment by 0xACE** [comment]
I'm guessing weird unicode has been involved or his `PS1` needs to be looked at + his terminal may be misbehaving (misrepresented termcap?)...

**Comment by jarun** [comment]
What's your `$VISUAL`, and `$EDITOR`?
Do you have vi installed?
Are you using `nnn -e`? Otherwise which options do you use for `nnn`?

Also, if you run copy, move, delete etc. the prints will be on the prompt after you quit `nnn`.

So be very specific about what you ran.

**Comment by ghistes** [comment]
Sorry I cannot be more specifc, I will try to experiment and find a way to reproduce it. 

What I see is that often after quitting nnn my terminal seems to swallow keypresses. I had a case where "c" would no longer work at all. Or a case where only every second (or so) "a" would work.

my $VISUAL is empty and $EDITOR is set to "vim". I have been running nnn only without any switches or with "-n" only.

**Comment by jarun** [comment]
Do you have `NNN_OPENER` set?

**Comment by jarun** [comment]
Throwing some more questions if it helps:

Does your text files open in vim or a GUI editor?
Did this happen after opening a file? If yes, what type of file?
Is mouse enabled? Did you click on the terminal by any chance?
Were you in a filtered view?

**Comment by jarun** [comment]
And lastly, get master again. I had been experimenting a lot the last couple of nights and something may have broken.

**Comment by ghistes** [comment]
NNN_OPENER is not set. 
My text-files open in vim.
I was not in a filtered view and I did not use the mouse.
I usually quit nnn by pressing "q" (only one context active).

I will try the current master again and report back.

**Comment by ghistes** [comment]
The problem seems to persist.
I have run the current master without arguments, opened two pdf files, deleted a file and opened a text-file in vim. Then I quit nnn by pressing "q".
Now terminal swallows key-strokes.

**Comment by jarun** [comment]
> deleted a file

How? `^X` followed by `y`?

> opened a text-file in vim

How? Using `^O` or or by pressing `e` on the file?

Can you compile `nnn` from source in [with debugging enabled](https://github.com/jarun/nnn/wiki/Developer-guides#debugging-nnn) and share the debug log?

You also have a quick way to check which commit broke it using `tig`. Go down from master 10 commits at a time till v3.0 and see which commit broke it.

I am not on i3. And I am unable to repro this on XFCE yet.

**Comment by KlzXS** [comment]
@jarun I am able to reproduce this at will. Just try opening a file with a cli-only tool in gui mode and you'll lose keypresses. The same also happens for me for some files, I'm not sure which but it seems to be mime types which don't have an opener set, not sure.

I know you are not supposed to do that, but that's how you get it to misbehave.

I think this has exists since I began using `nnn`. I just checked and sure there it is in 5dba524. Maybe even earlier.

**Comment by jarun** [comment]
@ghistes I think I could repro this now. It happens when you try to open a CLI utility in GUI mode.

I think what you need is to use the new option `-e`. It replaces the earlier option `NNN_USE_EDITOR`. See the quickstart section: https://github.com/jarun/nnn#quickstart

Also, please try to be more specific in ater defect reports. Specially keystrokes.

**Comment by jarun** [comment]
> Just try opening a file with a cli-only tool in gui mode

See my last comment. Yes, you can't do this.

> I know you are not supposed to do that, but that's how you get it to misbehave.

There's no solution to this without remembering the name of every binary already existing and going to be created and whether it's CLI or GUI.

**Comment by jarun** [comment]
I have invested a lot of effort into this issue to think the scenarios and repro. If you think it's worth, consider starring the project. That's the least users can do. ;)
