### ISSUE TITLE
nnn opens Vim in the background

### ISSUE THREAD

**Issue by iio7** [jarun/nnn#509]
I have `export NNN_USE_EDITOR=1` in my `.bashrc` and both `export EDITOR="nvim"` and `export VISUAL="nvim"` and this works well in both Ranger and Midnight Commander.

However, when I use nnn and place try to open a normal text file like `.txt` or `.md`, nnn opens the file in Neovim, but in the background. I have to open another terminal and then kill Neovim.

I am using nnn version 3.0.

**Comment by jarun** [comment]
The option is frozen as `NNN_OPENER`. See https://github.com/jarun/nnn/wiki/Usage#configuration

**Comment by iio7** [comment]
That has got nothing to do with it.

If nnn is started with the '-e' option it works, but isn't this supposed to be the default once EDITOR is set?

**Comment by jarun** [comment]
> That has got nothing to do with it.

Right, I confused with the earlier `NNN_USE_OPENER`.

> isn't this supposed to be the default once EDITOR is set?

No it's not to ensure `xdg-open` works without any issues for newbies.

**Comment by iio7** [comment]
`xdg-open` works just fine. nnn on the other hand cannot use Neovim without the `-e` option.

**Comment by 0xACE** [comment]
I'm not up to date with the current `master` branch, but I just compiled it to see, and it seems like you can utilize the `e` key to edit files...

**Comment by jarun** [comment]
> xdg-open works just fine. nnn on the other hand cannot use Neovim without the -e option.

That's how it's supposed to be. From the program help:

    -e      text in $VISUAL/$EDITOR/vi

**Comment by jarun** [comment]
It's in the quickstart section as well: https://github.com/jarun/nnn#quickstart

In brief: If you want to use `xdg-open` to handle ALL types of files, n need to export anything or use any flag. if you want text files to be handled in the terminal, use the program option `-e`.
