### ISSUE TITLE
NNNLVL increments on every shell invocation

### ISSUE THREAD

**Issue by eugene55** [jarun/nnn#510]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Arch Linux latest
[ ] Desktop Environment:
[ ] Terminal Emulator:
[x] Shell: bash
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. Start nnn, open help `?`. NNNLVL does not set
2. Open shell `!`, close shell.
3. Open help `?`. NNNLVL: 1
4. Open shell `!`, close shell.
5. Open help `?`. NNNLVL: 2

**Comment by jarun** [comment]
Thanks for the report! Please confirm if the patch works as expected.

**Comment by eugene55** [comment]
Confirmed. Now it works as it should. Thanks
