### ISSUE TITLE
Nnn treats long strings pasted into Filter as action keys

### ISSUE THREAD

**Issue by eugene55** [jarun/nnn#511]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Arch latest
[ ] Desktop Environment:
[x] Terminal Emulator: st
[x] Shell: bash
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. Open nnn, navigate to `/tmp`
2. Start Filter `/`
3. Paste long string `---------------------------------------------------` as filter expression
4. See how nnn navigated up to root dir

**Comment by KlzXS** [comment]
I can reproduce this. It's not the parent directory that it pushes you to, it's the previously accessed directory.

**Comment by jarun** [comment]
This can only happen in navigate as you type mode due to special keys at empty filter prompt. See here: https://github.com/jarun/nnn/wiki#filters

This is extremely handy for people who use _nav-as-you-type_ all the time. But I think we can throw in a switch to disable these special keys. However, I would still keep `?`, `/` and `:` as special keys.

@KlzXS do you think these should be disabled by default? And the new program option would enable these?

**Comment by eugene55** [comment]
But why it switched to _nav-as-you-type_ mode @jarun ? I don't have this option enabled.

**Comment by KlzXS** [comment]
It seems that email reply didn't reach through the ether. So this is what I wrote:

>I can't be sure now, but I believe I didn't have nas-as-you-type enabled. I never use that.
>But I was still able to change directory, and also with some weird lorem ipsum create a garbage directory.
>
>I think we should disable executing actions after pasting text into filter. It seems it could activate unwanted actions. If this is at all possible that is.

**Comment by jarun** [comment]
I've thrown in a patch that will show a forced delayed msg. The best we can do.

**Comment by eugene55** [comment]
This fix does not do much in case of pasting text. It just tries to explain user why things are messed. And in unfortunate scenarios it still can do damage.

**Comment by jarun** [comment]
1. We can't have an unlimited filter (max has to be 255 chars but you can copy a linger string)
2. When you cross the limit we have to fail so we do not overrun the buffer
3. We can't chew _any_ extra character after showing an error msg

**Comment by eugene55** [comment]
How about option to detect paste scenario and switch logic to consume full string before any action?

**Comment by KlzXS** [comment]
> detect paste scenario

How do you detect a paste?

**Comment by jarun** [comment]
How do we consume the full string? It's continuous input. The buffer size is exceeded. So we show the error and continue interpreting the rest of the characters as input. It's as good as you typing characters after exceeding the limit. The program has no way to know you have pasted a bunch of characters. And even if it does, it cannot interpret them differently. It's just a stream of characters to the program.

**Comment by eugene55** [comment]
>  typing characters
can we calculate speed of typing? for pasting/automated typing it will be distinguishable against human input

**Comment by jarun** [comment]
You were right. My initial thought process was to notify the user for which I had to exit the filter prompt. But now I have changed the implementation to ignore any additional input as long as the filter is in effect.

**Comment by eugene55** [comment]
It's much better now, with 46f1788

**Comment by jarun** [comment]
:+1:

Once again, thanks for reporting the issue!
