### ISSUE TITLE
Unable to install 3.0 .deb on Pop!_OS 19.10

### ISSUE THREAD

**Issue by rcrx** [jarun/nnn#512]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Pop!_OS 19.10
[x] Desktop Environment: Gnome 3
[x] Terminal Emulator: N/A
[x] Shell: Bash
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Attempt to install with `Eddy` package installer.

# Error message provided:

```
The following packages have unmet dependencies:
  nnn: Depends: libreadline7 but it is not installable
```

I tested the 2.9 package as well with a similar error regarding `libreadline6`.  
It should be noted, however, that I was able to build 3.0 from source, using `libreadline-dev`, without any complications.

**Comment by jarun** [comment]
I see it's an Ubuntu derivative. Please test on the respective Ubuntu release and see if the issue exists.

**Comment by jarun** [comment]
Adding @szlin in case he has something to add.

**Comment by szlin** [comment]
The APT mechanism should install the dependencies correctly; I doubt this issue was caused by a version mismatch, such as install a package that does not exist in current os.
