### ISSUE TITLE
Feature request: Change color of "details" columns

### ISSUE THREAD

**Issue by toddyamakawa** [jarun/nnn#518]
Is it possible to change the color of the details column?

e.g.
`NNN_DETAIL_COLORS=0`

Which would change this:
![image](https://user-images.githubusercontent.com/7848869/79349756-40aa9180-7efc-11ea-829f-3c410a548454.png)

To this (the whole column should be black all the way down unlike my screenshot):
![image](https://user-images.githubusercontent.com/7848869/79349797-4bfdbd00-7efc-11ea-9eee-dd0427e9edbc.png)

**Comment by 0xACE** [comment]
Sure go ahead and patch `printent_long()` to your desire... Other than that you're out of luck. Unlikely this will be supported.

**Comment by jarun** [comment]
With the current implementation, you can use `nnn` in light mode and see the details of the current file far below in the status bar if required.

Many users use the detail mode with time sort enabled (even start with that). For them all columns are equally important. That's the main reason they use the detail mode.
