### ISSUE TITLE
Feature request: 'f' to jump to file/directory with matching letter

### ISSUE THREAD

**Issue by toddyamakawa** [jarun/nnn#519]
I think it would be very useful and intuitive if users could press `f<char>` to jump to the first file or directory that starts with that letter. e.g. `fm` would jump to the first file that matches `/^m/`. This would sort of match the vim equivalent command.

I realize that `f` already displays file information. I would propose to rebind `f` to `i` for **i**nformation.

**Comment by 0xACE** [comment]
Doubt this specific feature will be implemented in `nnn`.

I don't remember if our plugin system supports this, but maybe it does?

**Comment by jarun** [comment]
We currently have `'` to jump to the first file.

We can't rebind `f`, keybinds were frozen in v2.9. I will check how easy it is to support: `'char` combo.

**Comment by jarun** [comment]
But why can't you use the regex filter `^<char>`?

**Comment by jarun** [comment]
> I would propose to rebind f to i for information.

That's very convenient. Now what would happen to `^F` for people who use the `type-to-nav` mode all the time?

**Comment by toddyamakawa** [comment]
> But why can't you use the regex filter `^<char>` to list all files starting with `<char>`?

Is `^` supported with `/`? As soon as I use `/^` I end up with no matches.

**Comment by jarun** [comment]
`/` is string search. You need regex. You can press `/` to switch to regex OR use the program option `-g` t start in regex mode all the time.

**Comment by toddyamakawa** [comment]
> `/` is string search. You need regex. You can press `/` to switch to regex OR use the program option `-g` t start in regex mode all the time.

This works for me. Thanks!

**Comment by jarun** [comment]
Cool!

However, I'll still take a look at the `^<char>` option. Thanks for the suggestion! :+1:

**Comment by toddyamakawa** [comment]
I just noticed commit `37ebf8054f4fd6cde9964557f7fbfb00c8460847` and tried it out. Works great! Thanks for developing such a great tool.

**Comment by jarun** [comment]
Glad to know like it! :+1: 

Yes, it's very useful. Thanks for suggesting!
