### ISSUE TITLE
$NNN_PIPE is empty for running a command as a plugin

### ISSUE THREAD

**Issue by toddyamakawa** [jarun/nnn#523]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Red Hat Enterprise Linux Server release 6.9 (Santiago)
[ ] Desktop Environment:
[x ] Terminal Emulator: gnome-terminal
[x] Shell: `zsh`
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

When I run a command as a plugin, I see that NNN_PIPE is empty.

This my code for `cdhome`:
```
#!/usr/bin/env sh
echo "NNN_PIPE='$NNN_PIPE'"
printf "%s" "0$HOME" > "$NNN_PIPE"
```

This works as expected when `cdhome` goes into my plugin directory:
`NNN_PLUG='c:cdhome'`

This doesn't work even though cdhome is in my path:
`NNN_PLUG='c:_cdhome'`

This is what I see:
`NNN_PIPE=''`

**Comment by 0xACE** [comment]
Excuse my `bashisms` but doesn't `'$NNN_PIPE'` cancel the variable expansion? I.e. I think you should be using regular `"` double quotes

```
$ export myvar="hello"
$ echo "$myvar"
hello
$ echo '$myvar'
$myvar
```

I didn't properly cover your issue, but the problem can be solved by seeing the example plugins and the setup documented in the wiki.

**Comment by toddyamakawa** [comment]
> Excuse my `bashisms` but doesn't `'$NNN_PIPE'` cancel the variable expansion? I.e. I think you should be using regular `"` double quotes

I'm using the exact same script in two different ways. The first way where I add it to the `plugin` directory, everything works as expected. The second way, where I put it in my `$PATH` and call it with `_cdhome`, the `$NNN_PIPE` does not get set. `nnn` is definitely handling these two cases differently.

To answer your quoting question, I like to put single quotes inside of my double quotes. So your example would look like this:
```
$ echo "myvar='$myvar'"
myvar='hello'
```

However, if you don't set `$myvar`, then it looks like this (which is what I'm seeing when I call `cdhome` as a command):
```
$ echo "myvar='$myvar'"
myvar=''
```

Does this make sense? Can try to reproduce this on your end?

**Comment by 0xACE** [comment]
I'm way behind master so I shouldn't be commenting, but a quick grep over the source code mentions `$NNN_PIPE` being set via `run_selected_plugin()`

executing scripts without `run_selected_plugin()` shouldn't set `$NNN_PIPE`, seems like `SEL_PLUGIN` is one way to trigger it.

Sorry that I can't be of help, you are discussing features of `nnn` I setup a very long time ago, and never touched again... jarun tends to be awake around this hour...

But my guess is that you have a miss configured machine or that you are expecting `nnn` to do something it's not meant to do... I'm guessing the answer is in the wiki.

Good night.

**Comment by toddyamakawa** [comment]
> executing scripts without `run_selected_plugin()` shouldn't set `$NNN_PIPE`, seems like `SEL_PLUGIN` is one way to trigger it.

Alright, I think I figured out the problem. Here is the snippet of code:

```
static bool run_selected_plugin(...)
{
	// ...

	// After SEL_PLUGIN, this checks if the first character is an _
	// If I run `cdhome` as a plugin, this is false
	// If I run `cdhome` as a command, this is true
	if (*file == '_')
		return run_cmd_as_plugin(*path, file, runfile);

	// This code only gets executed if I run `cdhome` as a plugin
	if (!(g_states & STATE_PLUGIN_INIT)) {
		// plctrl_init is where $NNN_PIPE gets set
		plctrl_init();
		// The documentation doesn't mention whether $NNN_PIPE can be used in a command
		g_states |= STATE_PLUGIN_INIT;
	}
	// ...
}
```

Hope that makes sense.

**Comment by jarun** [comment]
@toddyamakawa please confirm this is fixed.

**Comment by toddyamakawa** [comment]
@jarun I opened PR #525 that seems to fix the issue. Can you double check I didn't do anything silly and merge it?
