### ISSUE TITLE
Safe session on quitting nnn and resume on next start

### ISSUE THREAD

**Issue by mintelm** [jarun/nnn#526]
Hi,

I'm looking for a way to make my nnn sessions persistent. I know I can safe my session by pressing 's' 's', but I want to know if there is a possibility to automatically safe on quitting nnn and resuming the session on next start?

**Comment by jarun** [comment]
This is a nice feature request. I'll add a patch. :)

**Comment by jarun** [comment]
Please test option `-S` and confirm.

**Comment by jarun** [comment]
Hell! I'm using it in my alias and it's unbelievably awesome!

**Comment by jarun** [comment]
Should `-S` enforce `-Q`?

**Comment by mintelm** [comment]
Wow, that was fast. I'm from Germany so I was asleep .. I just tested it and it works like a charm!

I'm not sure if `-Q` should be enforced. It makes sense to enforce it because the session is saved anyways but not enforcing it leaves the decision to the user which might be preferable.

Another small request would be to make the session only persistent for a vim session though I'm not sure if it's the right place to request this here or rather in the nnn.vim plugin.

Thank you for your help!

**Comment by jarun** [comment]
> It makes sense to enforce it because the session is saved anyways but not enforcing it leaves the decision to the user which might be preferable.

True. I left using `-Q` to the user.

> to make the session only persistent for a vim session

Yes, that's for `nnn.vim`.

**Comment by mintelm** [comment]
Okay, should I write another feature request for that?

**Comment by jarun** [comment]
I think so. It's a new thing for nnn.vim.
