### ISSUE TITLE
simplify file operation commands

### ISSUE THREAD

**Issue by roachsinai** [jarun/nnn#530]
**Is your feature request related to a problem? Please describe.**

For now `nnn` provides `^R` to rename, `p` to Copy sel here, `v` Move sel here, `x` Delete, `n` create, etc.

I think it will be better to porvide a `m` command, trigger `m` will show a menu:

`Action: **N**ew file/directory, **R**ename, **C**opy, **M**ove, **P**aste, **D**elete?`

The input `N` will have behavior same with `n` provided by `nnn` default.

**Additional context**

This will discrease the command we need to memorise, only need to trigger `m`(enu).

**Comment by jarun** [comment]
All of these operations are different. We can't combine them. And if we try it, our internal switch case will become spaghetti. Because these are handled in different cases.

I have the plan to have a cheatsheet in the Wiki to expand the shortcuts os they are easy to memorize. That would help to some extent.

**Comment by roachsinai** [comment]
Yeah, thanks for your work!

**Comment by lawnowner** [comment]
A possible template for a base set of built-in/plugin functionality:

    Go up/down/in/out/top/bottom                              k/j/l/h/g/G
    Scroll up/down                                            Ctrl-{u/d}
    Go to <char>/first file                                   '{<char>/'}
    Visit root/home/last/start directory                      `/~/-/@
    Visit bookmarked directory (NNN_BMS)                      b<key>
    Pin current directory/Go to pinned directory              ,/b,
    Filter entries|cancel filter                              /|Ctrl-l
    Toggle str|regex|case matching in filter prompt           /|\|:
    Toggle continuous navigation mode                         Ctrl-n
    Switch to or create context                               {1-4}
    Switch to next/previous context                           Tab/Shift-Tab
    Quit context/Quit nnn with error code                     q/Q
    ------------------------------------------------------------------------
    Toggle hidden entries                                     .
    Toggle detailed view                                      d
    Show details of current entry                             f
    Toggle executable bit of current entry                    *
    Toggle sorting by mod. time/size/ext./version sort        t{t/s/e/v}
    Toggle allocated/apparent du|Abort du                     t{d/a}|Ctrl-c
    Toggle reverse listing                                    tr
    Show volume space usage and nnn config                    ?
    ------------------------------------------------------------------------
    Create file/directory/sym|hard-links to selected entries  n{f/d/s|h}
    Rename or duplicate current entry/Batch rename            Ctrl-r/r
    Select current/all entries                                Space/a
    Toggle range selection mode                               m
    Edit list of selected entries in editor                   E
    Copy/move selected entries                                p/v
    Copy-as or move-as selected entries                       w
    Delete current or selected entries                        x
    Archive current or selected entries/Archive file ops      z/l{d/x/l/m}
    Open current/selected entries with...                     o/;o
    Open current entry with EDITOR or VISUAL                  e
    Open current/selected entries with gvim                   ;{e/E}
    Open current/all entries with sxiv                        ;{v/V}
    Open current directory in thumbnail view                  ;t
    Run bookmarked plugin (NNN_PLUG)                          ;<key>
    Pick plugin to run on current or selected entries         ;Enter
    Clear/exit nnn prompt                                     Ctrl-{l/[}
    ------------------------------------------------------------------------
    Copy path of current/selected entries                     ;{p/P}
    Copy basename/dirname of current entry                    ;{n/l}
    Show file type specific information                       ;i
    Spawn shell in current directory                          !||Ctrl-]
    Run command at shell prompt                               ]

**Comment by roachsinai** [comment]
@lawnowner Thanks for the list!!

**Comment by jarun** [comment]
In addition, when you press `?`, you get this list: https://github.com/jarun/nnn/wiki/Usage#keyboard-mouse

Try to remember the keys by the functionality e.g., p/^P for co_p_y, v/^V for mo_v_e and so on.

**Comment by roachsinai** [comment]
@jarun Thanks for the tips!

**Comment by jarun** [comment]
No problem! Enjoy `nnn`! :+1:

**Comment by jarun** [comment]
Here's something extra: https://github.com/jarun/nnn/wiki/Usage#graphical-map
