### ISSUE TITLE
The hardware cursor should move to the selected item

### ISSUE THREAD

**Issue by tspivey** [jarun/nnn#534]
**Is your feature request related to a problem? Please describe.**

When nnn starts, the hardware cursor is placed on the status line, and it doesn't move when files are selected.

**Describe the solution you'd like**

I would like the hardware cursor to move to the currently selected file as it changes, along with moving back to the status line when doing an operation such as rename.

**Describe alternatives you've considered**

**Additional context**

While the cursor is hidden, it still has a location. Screen readers and braille displays use it to tell what to focus on.

**Comment by jarun** [comment]
If

1. someone works on this based on a conditional flag
2. There aren't flag checks in every redraw

I can consider this. I will add a line item.

**Comment by jarun** [comment]
@tspivey this feature is added at commit f125802f4f30c5275d4d22b11aba0239f6216d58.
