### ISSUE TITLE
Duplicate paths in selection

### ISSUE THREAD

**Issue by Randoragon** [jarun/nnn#535]
The item selection in nnn visually resets when you change the working directory, but the selected items remain in the `.selection` file. Moreover, they can be selected **again**, which results in duplicates.

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: inux arch 5.6.6-arch1-1
- [x] Desktop Environment: None (i3-wm)
- [x] Terminal Emulator: Termite
- [x] Shell: ZSH
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

The easiest way to illustrate it is by using the `-p -` option, which outputs all the selected paths when quitting nnn (but watching .selection's contents also works):

1. Run `nnn -p -`
2. Select a few paths
3. Go to a different directory and return to the first one.
4. Select the same paths as in step 2
5. Exit with q

You will see the paths you selected get printed twice. This is likely because nnn does not erase the .selection file's contents when changing directories.

#### Possible solutions

1. Allow selecting paths from varying directories (could be a nice feature, but i'm not sure if this wouldn't break something else).
2. Wipe the .selection file's contents on directory change.

**Comment by jarun** [comment]
Please read the selection section in the Wiki thoroughly: https://github.com/jarun/nnn/wiki#selection

**Comment by jarun** [comment]
@Randoragon persistent selection marker is on master now and will be available in the next release. This issue of duplicate entries in selection will also be gone with it. Try it out!
