### ISSUE TITLE
Unintended deletion of file by batch rename

### ISSUE THREAD

**Issue by lawnowner** [jarun/nnn#538]
#### Environment details (Put `x` in the checkbox along with the information)

[ ] Operating System:
[ ] Desktop Environment:
[ ] Terminal Emulator:
[ ] Shell:
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
For the two files `~/somename` and `~/someothername`:

`r` to batch rename using the builtin functionality.

change "somename" to "someothername"
change "someothername" to "someothernameold"

`~/somename` is renamed to `~/someothernameold`, and `~/someothername` is
deleted.

**Comment by KlzXS** [comment]
Be aware that there are some limitations to the bultin implementation: https://github.com/jarun/nnn/wiki/Troubleshooting#batch-rename-limits. This being one of them.

The `.nmv` plugin doesn't have this limitation so use that or work around the limitations of the builtin version.

**Comment by lawnowner** [comment]
> It's single-pass - reads the name/path of files iteratively (from a list of source files) and renames/moves them (as specified in the corresponding line number in a list of renamed/destination files). It doesn't handle deletions or perform any pre-parsing to account for rename loops, swaps, replaces, etc.

I'd suggest adding to the above part that it can result in unintended deletion of files as a security warning, because on contarary to the above paragraph, it does handle deletions in cases like this one.

**Comment by KlzXS** [comment]
I wouldn't call that "handling deletion" as much as it's an unwanted side effect. But you're right a word of warning should be added.

**Comment by jarun** [comment]
The documentation is very clear here: "and renames/moves them (as specified in the corresponding line number in a list of renamed/destination files)". There's nothing to update.
