### ISSUE TITLE
nnn (n³) logo discussion

### ISSUE THREAD

**Issue by leovilok** [jarun/nnn#540]
Here are a few ideas/tries for `nnn`'s logo (n³):
![nnn-logo-ideas](https://user-images.githubusercontent.com/1430862/80529681-17780f80-8998-11ea-9039-dfd128112b3c.png)

Colors are just here to differentiate variations at this point.

Any comment/criticism/new idea is welcome.

**Comment by jarun** [comment]
Second one in the fourth row looks good to me.

**Comment by jarun** [comment]
Can we have an image of the first one in the fourth row without the shadow?

**Comment by leovilok** [comment]
![nnn-logo-ideas-r4c1](https://user-images.githubusercontent.com/1430862/80540380-772ae680-89a9-11ea-913c-f362997921bd.png)
It's similar to the orange one without it's border.

**Comment by jarun** [comment]
Left another suggestion in the discussion room. Only if it's easily doable.

**Comment by leovilok** [comment]
Its easy:
![nnn-logo-ideas-chess](https://user-images.githubusercontent.com/1430862/80542804-ffab8600-89ad-11ea-88be-4ce6228f98a1.png)

**Comment by jarun** [comment]
Wow! All of them look cool!

@maximbaz @KlzXS what do you you think?

**Comment by maximbaz** [comment]
Call me boring, but I personally like the most minimalistic version, an `n³` that isn't embedded into any image or shape.

I have an almost infinite amount of variations of it 😄 

https://fonts.google.com/?preview.text=n%C2%B3&preview.text_type=custom&preview.size=65

**Comment by jarun** [comment]
That's just too many fonts to choose from. ;)

The font used by @leovilok looks good to me.

@maximbaz how does the 5th knight embossed n3 look to you?

**Comment by jarun** [comment]
To me it doesn't look squeezed in and makes a clear impression.

**Comment by maximbaz** [comment]
As said I personally favor the minimalistic version that isn't embodied into anything, but if you like knights, it's fine with me 👍

**Comment by jarun** [comment]
I do see the point of infinite variants. :)

Let's want for more inputs from others.

**Comment by jarun** [comment]
Check out how the n3 looks live in the wiki page: https://github.com/jarun/nnn/wiki

**Comment by jarun** [comment]
@leovilok can we have a single image of the 5th dark knight?

**Comment by leovilok** [comment]
Here is a 128x128px version, but the source is SVG, so I can render it to any resolution.
![nnn-logo-ideas-chess-5](https://user-images.githubusercontent.com/1430862/80546274-87e15980-89b5-11ea-89f5-e3dd9d313bc8.png)

Here are a few more variations on this one:
![nnn-logo-ideas-chess-more5](https://user-images.githubusercontent.com/1430862/80546278-89128680-89b5-11ea-9c2a-b20a981fd5e6.png)

**Comment by jarun** [comment]
I think I now agree with @maximbaz. The n3 is just too simpler, minimal and straight to the point. Can you add https://user-images.githubusercontent.com/1430862/80540380-772ae680-89a9-11ea-913c-f362997921bd.png under misc/logo?

**Comment by jarun** [comment]
@maximbaz while we are at it, shall we also change:

nnn (or n³) is a full-featured terminal file manager.

to

n³ (or nnn) is a full-featured terminal file manager.

?

**Comment by maximbaz** [comment]
I think the "nnn (or n³)" version is better, because when you read the sentence for the first time you pronounce it in your head, and having "nnn" in front sort of teaches you how to spell the project...

If I imagine myself not knowing about this repo, and reading for the first time `nnn (or n³) is a full-featured terminal file manager` I would pronounce in my head "en-en-en (or ... ok, logo I guess) is a full-featured ...", while if I read for the first time `n³ (or nnn) is a full-featured terminal file manager` I would probably pronounce in my head "en... cubic (or en en en?) is a full-featured..."

Don't know if it makes sense what I just wrote 😄

**Comment by jarun** [comment]
Makes sense! @leovilok please raise the PR to add the logo.

**Comment by jarun** [comment]
Closed at #541.

**Comment by jarun** [comment]
@leovilok can we have a larger version of the second one from https://github.com/jarun/nnn/issues/540#issuecomment-620900983?

**Comment by leovilok** [comment]
@jarun:
![nnn-logo-ideas-chess-5 2](https://user-images.githubusercontent.com/1430862/80559229-31881100-89dd-11ea-87c1-990ebb246931.png)

**Comment by jarun** [comment]
Till we decide about it, I am force pushing the last commit out so the tree is clean. We always have the PR to get the earlier logos back.

**Comment by leovilok** [comment]
More horse heads (I thought I posted this yesterday...):
![nnn-logo-ideas-chess-more-horces](https://user-images.githubusercontent.com/1430862/80614098-56f93700-8a3e-11ea-9741-ed43671dffa1.png)

**Comment by leovilok** [comment]
A few facier version of the original (`1a`) one:
![nnn-logo-ideas-chess-n5-fancier](https://user-images.githubusercontent.com/1430862/80625676-dc381800-8a4d-11ea-9bf6-f5220f567823.png)

**Comment by leovilok** [comment]
And with red n³:
![nnn-logo-ideas-chess-5-red](https://user-images.githubusercontent.com/1430862/80627449-3639dd00-8a50-11ea-9afd-03338b719cc8.png)

**Comment by leovilok** [comment]
Before I reraise the PR, I did a few tweaks to 1a: on 2nd column I added a white border so that it still works on black background, on 3rd column I also adjusted margins and pixel grid snaping so that it's sharper when reduced to 32x32px, can I use the 3rd column for everything, or do you still prefer the original?
(click for real size)
![nnn-logo-chess-sizes](https://user-images.githubusercontent.com/1430862/80741740-75346500-8b1a-11ea-8836-1e40af023e3e.png)

Formats I plan to include in the repo:
- Original .svg
- 64x64 png
- 128x128 png
Is it all good for you?

**Comment by toddyamakawa** [comment]
I think I missed some of the discussion of when the logo turned into knights. I agree with @maximbaz. To me the connection between a knight and file manager is not immediately obvious and prefer minimalism. Can someone shed some light on how knights were chosen?

**Comment by 0xACE** [comment]
I'd suggest activating pixel snapping for when publishing graphics.

I have no quick method of testing the logo on a dark background... But right now I feel like the one on the top right... But third column with or without white "strike/margin" (Defer to your best intuition of what looks best in both settings or many environments, but again as said in the chat: it's only ever seen on github).

alternatively if it doesn't seem fine in 32x32 we could have a secondary / minimal logo.

> I think I missed some of the discussion of when the logo turned into knights.

Jarun really likes horses? jk, iirc it had to do with the knight existing as a unicode symbol: `♞`

Afaik it's open for discussion. The knight was chosen because it was the best on proposed of a "non-minimalistic" logo.

With the reasoning of avoiding minimalistic logo being: the goal of the logo was to adhere to pleasing the audience on the github page. After that, you are unlikely to ever see the logo again...


Sorry had to be quick, have to catch up with other tasks now. Peace

**Comment by leovilok** [comment]
I opened #544 , with 3rd column version.

**Comment by leovilok** [comment]
@0xACE on a black bg:
![nnn-logo-chess-sizes-black](https://user-images.githubusercontent.com/1430862/80764614-6614dd80-8b41-11ea-8990-6e4879367ab6.png)

**Comment by 0xACE** [comment]
I'll have to take a look at another time... Though before then. Has anyone considered colours?

Another topic I'd like to bring up is: I recall reading things about avoiding absolute black and absolute white. But I don't recall the reasoning of that...

That being said, I think a black knigt makes sense since it's familiar to us via chess pieces...

**Comment by jarun** [comment]
@toddyamakawa please see the project discussion thread for more details.

In brief: `nnn` is about navigation and the knight has the most unusual move among chess pieces. It's also a horse, which is one of the fastest animals and one of the greatest friends of man. And finally, it's a dark knight.

We are still open for discussion if you have any input.

@0xACE for colors, how does the red on black look? I'm looking at the third one in the third row.

**Comment by jarun** [comment]
@leovilok the white border in https://github.com/jarun/nnn/issues/540#issuecomment-622146849 does add a different dimension to the logos!

**Comment by 0xACE** [comment]
> @0xACE for colors, how does the red on black look? I'm looking at the third one in the third row.

I'm not a fan of the red colour in this case, it doesn't help... The thing i meant with the colours is that it should be tested on something other than `#000000` and `#FFFFFF`, I don't remember why, but I think it's a design "guideline" to "avoid" them for some reason (but I don't remember in what regard this was important if anyone here can remind me, I'd be interested).

Right now the knight is "flat black", if you do shade it, I think it's important that it represents lighting/shading of what it should look like, meaning the anatomy matters, but then I guess it gets too cluttered... (too much to delve into, actually best to sketch with pen and paper and then later play around in illustrator...)

If I ever get my hands on a computer with graphical capabilities, I can tinker with it, but until then I can only be a keyboard warrior.


Of those proposed sofar pr #544 seems best imho.

Way past bed time, good night.

**Comment by jarun** [comment]
I'm good with PR #544 too!

**Comment by leovilok** [comment]
@0xACE Here are a few versions with unpure colors (not pure black/white), I dont remember hearing about this rule, it might just be to be visible on pure black or white backgrounds, which can also be achieved (better) by adding a border.
I also included a try for a more "anatomical" shading.
![nnn-logo-chess-ideas-shades-pale](https://user-images.githubusercontent.com/1430862/80774866-666fa180-8b5e-11ea-9d96-0920e672d6aa.png)

**Comment by jarun** [comment]
The original one looks the best! :+1:

**Comment by leovilok** [comment]
And a few more sublte, but still purely gradient based, shading:
![nnn-logo-chess-ideas-shades2](https://user-images.githubusercontent.com/1430862/80777733-7b503300-8b66-11ea-8d0c-7da9b49f3b51.png)

**Comment by jarun** [comment]
How about the second column, guys?

**Comment by jarun** [comment]
@leovilok can I have a 128*128 single of the second column? I would like to try it on the page.

**Comment by leovilok** [comment]
There:
![nnn-logo-chess-ideas-shades2 2 svg](https://user-images.githubusercontent.com/1430862/80782061-ed2f7900-8b74-11ea-83fa-55a25f237a06.png)

**Comment by jarun** [comment]
This is it! Please update the PR and we are done!

**Comment by leovilok** [comment]
I updated #544

**Comment by jarun** [comment]
Awesome! I think you need to re-raise the desktop icon PR https://github.com/jarun/nnn/pull/542.

**Comment by jarun** [comment]
Closed at #544.
