### ISSUE TITLE
Version sort is broken as of ef159b99850553841ab6d3842e8c7fa6c2096685

### ISSUE THREAD

**Issue by Steap** [jarun/nnn#550]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Debian Sid
[x] Desktop Environment: i3
[x] Terminal Emulator: urxvt
[x] Shell: bash
[x] Custom desktop opener (if applicable): N/A
[x] Program options used: -T v
[x] Configuration options set: None
[x] Issue exists on `nnn` master: yes

I am not using any nnn-related environment variables:
```
$ env | grep NNN
$
```
#### Exact steps to reproduce the issue
```
$ mkdir -p Test/Test_S{1..21}
$ make &&  ./nnn  -T v  ~/Test/
```

The directories previously created are listed as:
![version-sort-1](https://user-images.githubusercontent.com/416834/80926918-7673c500-8d9a-11ea-9be1-290e3f1b72c8.png)

If I hit 'tv' to disable version sort, I get this listing:
![version-sort-2](https://user-images.githubusercontent.com/416834/80926928-8b505880-8d9a-11ea-801d-7b3b7d44cf13.png)

If I hit 'tv' again to enable version sort, I get this listing, different from the previous one:
![version-sort-3](https://user-images.githubusercontent.com/416834/80926937-97d4b100-8d9a-11ea-9587-1903c925a7e9.png)

I bisected the issue and found that commit ef159b99850553841ab6d3842e8c7fa6c2096685 was responsible.

The following partial revert fixes the issue:

```
$ git diff
diff --git a/src/nnn.c b/src/nnn.c
index 5e215d7..706f6bf 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -2135,7 +2135,7 @@ static int xstrverscasecmp(const char * const s1, const char * const s2)
                state += (c1 == '0') + (xisdigit(c1) != 0);
        }
 
-       state = (uchar)result_type[state * 3 + (((c2 == '0') + (xisdigit(c2) != 0)))];
+       state = result_type[state * 3 + (((c2 == '0') + (xisdigit(c2) != 0)))];
 
        switch (state) {
        case VCMP:
```

clang-tidy does not seem to be bothered by this change:

```
$ clang-tidy src/* -- -I/usr/include -I/usr/include/ncursesw
70 warnings generated.
101 warnings generated.
Suppressed 102 warnings (101 in non-user code, 1 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
```

But I guess the cast to uchar was there for a reason.

**Comment by jarun** [comment]
Thank you so much for reporting this critical issue! It's a bad miss from my side.

Can you kindly raise a PR?

**Comment by jarun** [comment]
You may have to `// NOLINT` the line.

**Comment by jarun** [comment]
This is fixed now.
