### ISSUE TITLE
I would like to use a translated Wiki.

### ISSUE THREAD

**Issue by hitsuji-no-shippo** [jarun/nnn#551]
Hi @jarun. I am an English learner. I'm sorry if this sentence is difficult to understand.

I plan to write a post on my blog introducing NNN. The language of the article is Japanese. I want to use a translation of [this wiki](https://github.com/jarun/nnn/wiki) in the article, is that possible?

I will write the license and copyright notice in the article.

**Comment by 0xACE** [comment]
I think that is 100% okay. Go ahead.

**Comment by jarun** [comment]
Of course! Please go ahead. The Wiki si publicly editable so you can create new pages and start from there.

**Comment by jarun** [comment]
@hitsuji-no-shippo we also need to update the Arch Linux Japanese page: https://wiki.archlinux.jp/index.php/Nnn

@0xACE can you please update the Arch Linux English page? That would help @hitsuji-no-shippo as well. We don't have much there. And if you are not sure about anything, please ping me for the latest behaviour.

**Comment by 0xACE** [comment]
> @0xACE can you please update the Arch Linux English page?

I updated it. Although it wasn't much. I just removed some `NNN_*` variables, someone else already updated other details.

**Comment by jarun** [comment]
Thanks @0xACE!

    alias ncp="cat ${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection | tr '\0' '\n'"
this would change a little as we also support `NNN_SEL` now.

**Comment by jarun** [comment]
I've updated it.

@hitsuji-no-shippo I'm closing this issue. Please go ahead with your J-Wiki page!

**Comment by hitsuji-no-shippo** [comment]
Thanks @jarun @0xACE 

I will start to write the introduction post from today. When I'm done posting, I'll update the Archi Linux wiki.
I can only use an hour of my time every day to write the post. Therefore, I don't know now when the Arch linux wiki update will start.

**Comment by jarun** [comment]
:+1:
