### ISSUE TITLE
What is “change directory on exit” supposed to do?

### ISSUE THREAD

**Issue by Hibou57** [jarun/nnn#56]
I naively though (or wish) “change directory on exit” mean if i quit using “Q” then the shell will automatically go the directory I was in with `nnn`, but it does not seems to work.

So I wonder if that’s me not understanding what it means or me not correctly running `nnn`.

By the way, if this is supposed to indeed change the caller shell directory, then I wonder how this can be achieved.

I’m using Nnn 1.5 on Ubuntu Xenial 32 bits.

**Comment by Hibou57** [comment]
Oops, sorry, there already is a closed issue on this: https://github.com/jarun/nnn/issues/22

**Comment by jarun** [comment]
Please go through the Readme.
