### ISSUE TITLE
add mouse scrollwheel multiplier

### ISSUE THREAD

**Issue by deathtrip** [jarun/nnn#564]
**Is your feature request related to a problem? Please describe.**

Currently the mousewheel scrolling speed is not customizable.

**Describe the solution you'd like**

An environment variable for setting a scrollwheel multiplier. When set to 3 for example, each wheel step would scroll 3 entries up/down the list instead of one. 

**Describe alternatives you've considered**

A native scrollbar maybe? However i suspect adding it would be more work than a multiplier.

**Additional context**

Useful for browsing large lists quickly. If the multiplier is too high and you miss the desired file, you can adjust selection with arrow keys.

**Comment by 0xACE** [comment]
If this proposal gets denied, these are the lines you want to change:

https://github.com/jarun/nnn/blob/7718936737a64ded54ccea2910f8d82a61d5f1a2/src/nnn.c#L5398

https://github.com/jarun/nnn/blob/7718936737a64ded54ccea2910f8d82a61d5f1a2/src/nnn.c#L5405

Change the `cur ± 1` part to what you desire.

On my local build i use:
`handle_screen_move(SEL_CTRL_U);` and
`handle_screen_move(SEL_CTRL_D);` instead, which jumps half a screen back/forward.

Good luck.

**Comment by jarun** [comment]
We can have this as a program option, say `-l` (scroll lines).

**Comment by jarun** [comment]
Please confirm if the option `-l` works as expected.

**Comment by deathtrip** [comment]
Just tested with version 3.2, and it works great.
