### ISSUE TITLE
Export cwd

### ISSUE THREAD

**Issue by Nomarian** [jarun/nnn#565]
**Is your feature request related to a problem? Please describe.**

Tmux has the capability to create a new window using the current working directory, that is, /proc/currentprocess/cwd,  However nnn never adjusts cwd which makes this feature not possible.

**Describe the solution you'd like**

IDK C, but being able to execute

    tmux new-window -c "#{pane_current_path}"

should be possible

**Comment by 0xACE** [comment]
Last time I brought this up it was denied.

Though note that you can use a plugin to spawn a new pane for you correctly.

Personally I use this patch:

```
diff --git b/src/nnn.c a/src/nnn.c
index 116d9c3..30750f4 100644
--- b/src/nnn.c
+++ a/src/nnn.c
@@ -5366,6 +5366,7 @@ static bool browse(char *ipath, const char *session)
 		errexit();
 
 begin:
+	chdir(path);
 	/* Can fail when permissions change while browsing.
 	 * It's assumed that path IS a directory when we are here.
 	 */
```

along with some extra tmux hacks...

There might be a chance that i changed something else, but I cba to look through it atm.

Good night and good luck

**Comment by jarun** [comment]
@0xACE do you remember if there's any benefit of not doing this?

**Comment by jarun** [comment]
@KlzXS do you see any issues if we do this?

**Comment by jarun** [comment]
Please test the patch and confirm.

**Comment by Nomarian** [comment]
Patch works. So far no hiccups. lsof -c nnn | grep cwd updates correctly.

**Comment by jarun** [comment]
Awesome! :+1:

**Comment by jarun** [comment]
@0xACE I found our earlier conversation too: https://github.com/jarun/nnn/issues/332#issuecomment-533937941

And now the implementation has changed. Everything works!
