### ISSUE TITLE
Notifications on navigation operations

### ISSUE THREAD

**Issue by Hibou57** [jarun/nnn#566]
**Is your feature request related to a problem? Please describe.**

Not really a problem, but I was wondering if there is a way to be notified each time a navigation operation occurs in `nnn`, like on the ones of arrow keys.

**Describe the solution you'd like**

Each time `nnn` view’s highlighted item changes, ex. move to the next or previous entry, enter a sub‑directory or goes back to the parent directory, there would be some kind of notification about it. The notification could be executing a dedicated command from the plugins directory (ex. a plugin named `on-nav`) which would be automatically executed on each navigation step, or it could be writing to a pipe, ex. when `nnn` highlight switches from “/foo/bar” to “/foo/barz”, then it would write “foo/barz” to the pipe, or may be another kind of notification I have not though about. My guess is that the pipe way would be the best, because it would be the more light one, the less processing consuming one, also, the pipe way would be more general than the command way which imposes restrictions on the possible use cases.

**Describe alternatives you've considered**

Linux specific: with $pid set to `nnn`’s pid, I tried to see if `/proc/$pid/environ` reflects the current highlight in an environment variable, with the hope to poll it, but the environment seems to not change on navigation operation.

**Additional context**

I may be silly, but I wanted to use `nnn` additionally as a navigation widget for some tasks, while still using it the usual way. By the way, if it had a way to be requested at runtime to navigate to some file system item, it would be nice too, but I guess it would involve too much more, would be less simple than notifying it just navigated to some file system item. At least, this would be another reason to favor pipe over command: a pipe may be used for that purpose too: if a string is written to the pipe, then navigate to that string taken to be a path. The string would need to be zero terminated, since although a bad thing, a path may contain an LF or CR character.

If I have enough time for it, I will try the modification I propose and propose a patch if it ends to work (I already patched it a bit for something else, but it is not as a fork).

**Comment by Hibou57** [comment]
Or may be a bidirectional UNIX Domain Socket … I will investigate it …

**Comment by jarun** [comment]
It's available. See `NNN_FIFO` on master and #547.

**Comment by Hibou57** [comment]
Oops, I did not know. Thanks for the hint, will look at it.

**Comment by Hibou57** [comment]
For people who may read this thread: the last of my original message seems handled too, here: https://github.com/jarun/nnn/tree/master/plugins#send-data-to-nnn

**Comment by jarun** [comment]
:+1:
