### ISSUE TITLE
Suggest to favor `xsel` over `xclip`

### ISSUE THREAD

**Issue by Hibou57** [jarun/nnn#567]
This is not really an `nnn` bug, just may make believe it is. It may be nice to add to the documentation: `xclip` seems to have a bug which prevent it to be used to copy the current selection to the clipboard. I initially though it was an `nnn` bug, when in another context, I noticed that is `xclip` which has a bug. Since `xsel` works fine, I was thinking it would be nice to tell about it in the documentation, so people don’t believe the issue come from `nnn`.

**Comment by jarun** [comment]
What's the issue you see? We need some more details.

**Comment by Hibou57** [comment]
The issue is as I said: when using `xclip`, selection does not go to clipboard, while it works when using `xesl`. When the selection does not go to the clipboard, one may wonder why and believe the issue come from `nnn`, while it come from `xclip`. That’s why, I though it would be nice to mention in the documentation, it may not work with `xclip` and if it does not, then `xsel` may be installed instead of `xclip`.

**Comment by jarun** [comment]
In the plugin `.cbcp` we give higher priority to `xsel` than `xclip`. Also, I cannot reproduce this. Both work fine for me. I would avoid documenting an issue which is not very critical to `nnn` and is caused by a third-party utility.

**Comment by Hibou57** [comment]
So may be the issue is specific to my `xclip`. Yes, I agree it is not critical.
