### ISSUE TITLE
Segfault opening a new context on an empty dir

### ISSUE THREAD

**Issue by leovilok** [jarun/nnn#571]
#### Environment details (Put `x` in the checkbox along with the information)

[ ] Operating System: Linux
[ ] Desktop Environment: None
[ ] Terminal Emulator: 
[ ] Shell:
[ ] Custom desktop opener (if applicable):
[x] Program options used: None
[x] Configuration options set: Nothing
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Open `nnn` master on an empty dir

~~~sh
mkdir /tmp/empty
nnn /tmp/empty
~~~

Then press `2` to open context 2.
-> Segfault.

**Comment by 0xACE** [comment]
It's a bit lazy of a commit, but I did it for you. Cheers.

**Comment by leovilok** [comment]
Yeah I was lazy tonight, thank you!

**Comment by jarun** [comment]
I added a guard based on `ndents`.
