### ISSUE TITLE
CLI programs are being opened in the background

### ISSUE THREAD

**Issue by basbebe** [jarun/nnn#573]
I can't say if this is a misconfiguration on my side or a bug.

I have e.g. a shortcut to open [bat](https://github.com/sharkdp/bat): `-_bat       $nnn*`

But the terminal instantly returns to nnn.
After I quit nnn, I see the bat output in the terminal.

**Comment by 0xACE** [comment]
I've got no idea about the plugin prefixes these days, but from my understanding `bat` prints out the content and exits.

What you need is something to retain that information until you press a key or something.

`nnn` takes over because `bat` exited...

try a script with `bat $nnn* && read -n 1 -s -r -p "Press any key to continue"` or `bat $nnn* | less`

(btw not sure if unquoted variable in this case is a good idea, get shellcheck)

**Comment by jarun** [comment]
@0xACE is correct. Drop the `*`. I have updated the documentation to make this clearer.

**Comment by leovilok** [comment]
bat can be forced to use a pager even on small files, use `bat --paging=always $nnn`

**Comment by basbebe** [comment]
It was totally a misconfiguration and had little to do with `nnn`.
Thanks for your support.

I had the following set in my environment (set by zprezto):
```
export LESS='-F -g -i -M -R -S -w -X -z-4'
```

I changed it to
```
export LESS='-g -i -M -R -S -w -z-4'
```
(removed `-X` and `-F`)


The correct bat call seems to be (using it now with nuke for markdown files):
```
bat --color=always --paging=never "${FPATH}" | less -R
```
I use less so the `bat` output isn't put to terminal. Therefore `--paging=never`.

Next step: Find out how to use live preview and / or split the iTerm window.

**Comment by leovilok** [comment]
@basbebe here is a version of our `preview-tui` plugin using `bat`: https://gist.github.com/leovilok/b09de81e30a5a51f5128c71a8b459b25

I'll leave implementing iterm window split version as an exercise :laughing:.

**Comment by jarun** [comment]
@leovilok please add this to the live preview wiki page.

I think it would also be a good idea to have the iterm example.

**Comment by jarun** [comment]
BTW, why can't we add iterm (and kitty, if possible) to preview-tui?

**Comment by leovilok** [comment]
I don't have a mac, so I can't test iterm2 stuff. Besides, contoling panes in iterm2 seems to be done through applescript ... so it's probably harder than tmux/xterm.

It seems easier in kitty with its [remote control capacity](https://sw.kovidgoyal.net/kitty/remote-control.html), but its disabled by default...

**Comment by basbebe** [comment]
iTerm uses a Python API now.
I might try using ‘exa’ instead of ‘tree’ as well.
Maybe last try out [neovim-remote](https://github.com/mhinz/neovim-remote/blob/master/README.md) open files with Neovim in another terminal.

**Comment by jarun** [comment]
@basbebe if you figure out how to do previews feel free to document it here: https://github.com/jarun/nnn/wiki/Live-previews

@leovilok if you figure how to do it with kitty, feel free to update the plugin.

**Comment by leovilok** [comment]
@basbebe unfortunately, `exa -t` seems to wait before it gets the full tree before starting to print, wich make it very slow and quite useless as a previewer on dir containing deep/big hierachy. You could still use `exa -l` mode to preview dirs, or `exa -t -L2` to limit tree level.

@jarun I can prepare a previewer for rust lovers, with `bat`+`exa`+ maybe `hexyl` for binary files, but should it take the shape of an anlternative version of @toddyamakawa's  `preview_cmd.sh`, or an alternative version of `preview-tui` plugin?

Note that I don't use rust hype stuff myself, but I see why people might like them.

**Comment by jarun** [comment]
@leovilok actually I was more interested in the kitty solution (preview in a new pane) rather than the utilities used.

**Comment by akimdi** [comment]
@leovilok   maybe `exa --tree --level=1`

**Comment by basbebe** [comment]
> @basbebe unfortunately, `exa -t` seems to wait before it gets the full tree before starting to print, wich make it very slow and quite useless as a previewer on dir containing deep/big hierachy. You could still use `exa -l` mode to preview dirs, or `exa -t -L2` to limit tree level.

I wasn't aware of that, thanks!

@jarun I don|t know when I will be able to look into it but I will contribute when I figured it out!

**Comment by leovilok** [comment]
@basbebe the new `preview-kitty` plugin uses `bat` and `exa`, so you can use it for inspiration if you like those tools.

**Comment by basbebe** [comment]
@leovilok Thanks, looks great!

**Comment by basbebe** [comment]
Quick update: I shortly looked into splitting windows via iTerm's Python API.
The Plugin then would also have to be written in Python or we would need another Plugin / script for handling the splitting.

iTerm has a really nice tmux Integration which already works and you don‘t need 20 lines of code to split the window.

[Kakoune](https://github.com/mawww/kakoune) uses OSAscript I think to split iTerm windows, maybe I‘ll also look into that.

But I also looked at kitty and it seems really nice so I'll try out that for a while.

I might put the few lines of Python Code or the OSAcode into the wiki the coming days.

Sorry for hijacking the thread.
