### ISSUE TITLE
(minor issue) Fails to start when NNN_FIFO is empty

### ISSUE THREAD

**Issue by Hibou57** [jarun/nnn#575]
#### Environment details (Put `x` in the checkbox along with the information)

[x ] Operating System: Ubuntu 16.04 32bits
[x ] Desktop Environment: none
[x ] Terminal Emulator: gnome-terminal
[x ] Shell: zsh
[x ] Custom desktop opener (if applicable): none
[x ] Program options used: none
[x ] Configuration options set: none
[x ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Usually, when an environment variable is empty, it is taken for being not set, and NNN seems to follow this, except for `NNN_FIFO` which if defined but set to an empty string, prevents NNN from starting.

This is a minor issue.

**Comment by jarun** [comment]
Please confirm this works as expected.

**Comment by Hibou57** [comment]
Yes, it does :)

**Comment by jarun** [comment]
Thank you for reporting this!
