### ISSUE TITLE
alternative xcp

### ISSUE THREAD

**Issue by akimdi** [jarun/nnn#576]
Is it possible to use as an alternative [xcp](https://github.com/tarka/xcp) ?
or nnn always use cp?

it would be useful to do this for those who have SSD with NVMe.

**Comment by jarun** [comment]
From the website:

> xcp is currently beta-level software and almost certainly contains bugs and unexpected or inconsistent behaviour. It probably shouldn't be used for anything critical yet.
> In particular it is likely to thrash on spinning disks as it attempts to gather metadata and perform copies at the same time.

Directory benchmarks are slower.

Even in future we cannot have third-party utilities replace standard ones for data-sensitive operations.
