### ISSUE TITLE
Redraw automatically after exiting filter

### ISSUE THREAD

**Issue by clifordsab** [jarun/nnn#579]
**Is your feature request related to a problem? Please describe.**

While filtering (`/`), exiting (`Esc`) doesn't redraw automatically. The filtered files remain shown instead.

**Describe the solution you'd like**

Pressing `Esc` while on filter mode (`/`) redraws.

**Describe alternatives you've considered**

Manually redraw (`Ctrl + L`).

**Additional context**

https://imgur.com/a/9xs5NpW

**Comment by jarun** [comment]
> While filtering (/), exiting (Esc) doesn't redraw automatically. The filtered files remain shown instead.

That's the intended behaviour. To refresh press `^L`.
