### ISSUE TITLE
Preview a file in $PAGER?

### ISSUE THREAD

**Issue by juacq97** [jarun/nnn#580]
I remember in old versions, there was a keybinding to open files on $PAGER, `C-i` I think. I'm returning to use nnn after a while and now that keybinding is deprecated as far I see. How do I preview a file in a $PAGER? Or I need to write a plugin? Thanks!

**Comment by jarun** [comment]
> Or I need to write a plugin?

Yes, that what you need to do. See https://github.com/jarun/nnn/tree/master/plugins#some-useful-key-command-examples
