### ISSUE TITLE
Installing nnn on the Raspberry Pi

### ISSUE THREAD

**Issue by fes111-7** [jarun/nnn#584]
First of all, thanks for all the work that has gone into `nnn`. I think it is a great tool and I use it widely (and I have donated to its development).

The `nnn` version available as a stable Raspbian package is very out of date (v2.2), which means that the only way to get a recent version of `nnn` is to compile from source. However, the wiki entry to [compile for Pi][1] is not very helpful in that it doesn't actually tell people what to do.

To compile `nnn` v3.1 for a Raspberry Pi Zero W running Buster, I put `nnn-v3.1.tar.gz` on the Pi and then did the following, which seems like standard stuff for Debian-based distros:

#### Install the required dependencies

`sudo apt install pkg-config libncursesw5-dev libreadline-dev`

#### Extract the tarball ready for compilation

`tar -zxvf nnn-v3.1.tar.gz`
`cd nnn-3.1`

#### Compile and install to default directory (/usr/local/bin)

`sudo make strip install`

`nnn` installed with no problems and seems to work perfectly. Marvellous!

I could modify the wiki myself but, before I do so, I thought I should post here in case anybody has any comments or objections.

[1]: https://github.com/jarun/nnn/wiki/Developer-guides#compile-for-pi

**Comment by jarun** [comment]
Thank you for the info!

Please feel free to add it here: https://github.com/jarun/nnn/wiki/Developer-guides#compile-for-pi
