### ISSUE TITLE
Can't make cd on quit work

### ISSUE THREAD

**Issue by lifeBalance** [jarun/nnn#585]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: macOS
[ ] Desktop Environment:
[x] Terminal Emulator: iTerm2
[x] Shell: Bash
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
I installed `nnn` with homebrew and configured **cd on quit** as explained, just copied the function in my Bash configuration, launch a new terminal... and try to exit with `^G` but I exit where I launched nnn. By the way, the variable:
```
$ echo $NNN_TMPFILE
``` 
it does not get set.

**Comment by jarun** [comment]
How do you start `nnn`?

**Comment by jarun** [comment]
Also, please read the notes in the cd on quit script you copied. It will provide some hints. 1000s of `nnn` users use bash/zsh on Mac as of today and cd on quit works. I don't think your version of bash/zsh has anything special. Please debug local config issues yourself.
