### ISSUE TITLE
Pressing '?' won't display help message

### ISSUE THREAD

**Issue by chongchonghe** [jarun/nnn#586]
#### Exact steps to reproduce the issue

Start nnn. Press '?'. It flashes 'sourcing .cshrc' and come back without displaying any help message.

#### Expected behavior 

Display the help messages and wait for `q` to quit to the normal page.

**Comment by jarun** [comment]
Your `PAGER` is not waiting for user input. For me `PAGER` is: `less -Ri` and it works. Please see the Troubleshooting section in the wiki.

Also, please debug local environment issues yourself.
