### ISSUE TITLE
Wrapper script for i3 does not load plugin dependencies

### ISSUE THREAD

**Issue by jame-sparker** [jarun/nnn#589]
I was following the instruction here on using a wrapper to add a keybinding to nnn.
https://github.com/jarun/nnn/wiki/Advanced-use-cases#use-a-wrapper-script-to-export-variables
I have the following line in my i3 config file.
`bindsym $mod+n exec gnome-terminal -- ~/.config/nnn/nwrap`
It loads settings from environmental variables properly, but it fails to run plugins that have dependencies on fzf such as fzopen. I have zshrc file to load fzf.  
Everything works fine only if I open nnn from my terminal.

#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Ubuntu 18.04
[x] Desktop Environment: i3
[x] Terminal Emulator: gnome-terminal
[x] Shell: zsh
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[ ] Issue exists on `nnn` master

**Comment by jarun** [comment]
@toddyamakawa please take a look.

**Comment by 0xACE** [comment]
I'm not entirely sure but I'd argue he would have to do the equivalent of `terminal -e "bash -c ~/.config/nnn/nwrap"` and therefore shouldn't be considered a error on our end. If `zsh` thatkes the `-c` command as `bash` does he should be able to just replace the `terminal` and `bash` command in my example.

This way `bash` or `zsh` handles loading his environment variables... This goes for any program I guess...

**Comment by leovilok** [comment]
I think that it's because `.zshrc` only get loaded in interactive mode (like bash). I think that we have a few examples in the wiki where using `bash -ic nwrap` is advised, you could try:
```
bindsym $mod+n exec gnome-terminal -- zsh -ic ~/.config/nnn/nwrap
```

**Comment by jame-sparker** [comment]
`bindsym $mod+n exec gnome-terminal -- zsh -ic ~/.config/nnn/nwrap`
Immediately closes the terminal.

**Comment by leovilok** [comment]
Maybe this?
~~~
bindsym $mod+n exec gnome-terminal -x zsh -ic ~/.config/nnn/nwrap
~~~
note that I don't use gnome-terminal nor i3, `-x` is from the manual.

**Comment by jame-sparker** [comment]
```
bindsym $mod+n exec gnome-terminal -x zsh -ic ~/.config/nnn/nwrap
```
This immediately closes the teminal as well.
My initial command did not have a problem opening nnn. I think the issues are the things after `--`.

**Comment by leovilok** [comment]
Try using this first line for your nwrap script:
~~~zsh
#!/usr/bin/zsh -i
~~~

**Comment by jame-sparker** [comment]
That worked! Thank you!
