### ISSUE TITLE
Absolute path issue

### ISSUE THREAD

**Issue by kajka** [jarun/nnn#59]
Hi there!

I really like the simplicity of the nnn, but I have a problem with absolute paths. I work on macOS with fish shells.

My configuration file:

~/.config/fish/config.fish
`export NNN_COPIER="copier.sh"`

~/.config/fish/copier.sh
```
#!/bin/sh
greadlink -m $1 | pbcopy
```

<img width="752" alt="2017-11-27 at 08 49 49" src="https://user-images.githubusercontent.com/2843796/33286523-e063c97a-d3b5-11e7-8514-30e2b6e56c56.png">

It looks like the file path to the file was copied correctly (see picture above), but when I press `!` and then the `ctrl-shift-v` shortcut, copied absolute path is not pasted.

Is this nnn error or my configuration?

Regards!

**Comment by jarun** [comment]
What is the pbpaste output?

@zmwangx can you help with this one?

**Comment by zmwangx** [comment]
Easy. I bet $10 on either

- `~/.config/fish` is not in `PATH`; or
- `~/.config/fish/copier.sh` is not executable;

or both.

**Comment by kajka** [comment]
@jarun pbpaste output absolutely nothing 😞:

![nnn](https://user-images.githubusercontent.com/2843796/33316872-c72ccc06-d435-11e7-82a1-90043ce5d9ad.gif)

 @zmwangx Yes, `copier.sh` is executable. Also in ~/.config/fish folder I have some additional files (aliases, fish scripts) added to `config.fish`, so `copier.sh` should be properly loaded.

**Comment by zmwangx** [comment]
`~/.config/fish` is in `PATH`.

**Comment by zmwangx** [comment]
I meant NOT in PATH.

**Comment by kajka** [comment]
Looks like it is:

<img width="932" alt="paths" src="https://user-images.githubusercontent.com/2843796/33318801-545db440-d43c-11e7-8e1f-c5a3f816dfd2.png">

**Comment by zmwangx** [comment]
Then that's weird. Where do I deposit that $10?

**Comment by kajka** [comment]
Hey! There's no need; I just want to find a solution for my problem 😄.

I have tested three different terminal emulators (default macOS, iTerm2, Hyper) and three different shells (fish, zsh, bash). Everywhere I encounter the same issue.

It seems to be a problem that is related to macOS?

---
System Version: macOS 10.12.6 (16G1036)

**Comment by zmwangx** [comment]
> It seems to be a problem that is related to macOS?

Nope, works fine here, and I see no reason why an `execlp` call to such a simple script would fail, given that `copier.sh` is on PATH with executable bit set. I suggest you try the following to make sure:

```fish
$ copier.sh test && pbpaste
# should see "test"
```

```fish
$ export NNN_COPIER="$HOME/copier.sh"
$ nnn
```

**Comment by kajka** [comment]
The script worked fine; it turned out that adding `$HOME` instead of `~` resolved the problem! Strange but it helped o.O ... Anyway, thank you so much for help @zmwangx !

**Comment by jarun** [comment]
Thanks OS X *fanbois* for working it out! ;)
