### ISSUE TITLE
configuring launch plugin

### ISSUE THREAD

**Issue by protrolium** [jarun/nnn#593]
I am at this point [Launch Applications](https://github.com/jarun/nnn/wiki/Basic-use-cases#launch-applications) in the wiki, but I am not sure how to implement

`xfce4-terminal -e "${XDG_CONFIG_HOME:-$HOME/.config}/nnn/plugins/launch`

I am using iTerm2 on macOS High Sierra 10.13.6, and would really like play with launch to see how it works. I have added plugin key `l` to invoke `launch` in ~/.bashrc, but when I try to invoke it on a selection within `nnn` nothing happens after the 'c'li or 'g'ui prompt.

EDIT 1: I also tried using keybind `o` to `open with:` on the currently selected files in `nnn` and I get a `no traversal` returned when using full path to the application.

EDIT 2: Looks like I needed `fzf` to get `launch` working. I still don't fully grasp where to implement: <br>
`xfce4-terminal -e "${XDG_CONFIG_HOME:-$HOME/.config}/nnn/plugins/launch` <br>
but at least I am having ago with `launch` now.

**Comment by jarun** [comment]
Sorry, we do not support debugging plugins outside `nnn`. Those are very basic scripts and if you want to adapt those outside `nnn`, please do it on your own.

To launch an app, type the app name and press `Enter`. You have to mention cli or gui correctly.

**Comment by jarun** [comment]
ignore my previous comment, I missed this is for launch which can be used in a generic way. Here's what I use:

    xfce4-terminal -e /home/vaio/.config/nnn/plugins/launch

Do not use the full path, only GUI executables which are in your $PATH can be launched.
