### ISSUE TITLE
github tagline "file manager for X."

### ISSUE THREAD

**Issue by dmd** [jarun/nnn#596]
The github tagline is "n³ The missing terminal file manager for X." ... but nnn has nothing whatsoever to do with X, as far as I can tell. In fact it specifically *doesn't* use X!

**Comment by jarun** [comment]
> but nnn has nothing whatsoever to do with X

How about excellent integration with GUI apps? ;)

Anyway, see https://github.com/jarun/nnn/issues/262 for more details.
