### ISSUE TITLE
Discussion on nnn first release

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#6]
@zmwangx @shaggytwodope @szlin

I am thinking of making the first release of nnn. As usual, I'ld need your valuable guidance and help. Here are the points/questions I have in mind:

- I am skipping a config file. With the env vars like NNN_OPENER, the fallback, desktop file manager opener (pushed it today) I don't think we really need it. It's as good as having the desktop in the terminal.
- We have `-march=native` in the Makefile. Can we package with this option?
- No auto-generated packages this time. @shaggytwodope already has a ppa and AUR is his forte too.
- @szlin please submit this to Debian.
- @zmwangx please confirm if https://github.com/jarun/nnn/commit/9702abdd81774854540368600ea324af4829941d works on OS X. Would you mind submitting this to Homebrew?
- Shall we start with v1.0?
- Please share anything else that comes to your mind.

You'll find the new features in nnn [here](https://github.com/jarun/nnn#nnn-toppings).

**Comment by shaggytwodope** [comment]
I'm prepared to build ppa and aur pacakge once a release is tagged. I must admit I'm unsure of any effect `march=native` would have on a package. I would have to look into this to a degree. Altho I'm fairly certain for the aur package it's a moot issue since the user compiles it. The ppa however would take some looking into + testing.

**Comment by zmwangx** [comment]
We don't accept projects with fewer than 50 stars, unfortunately.

**Comment by zmwangx** [comment]
I can set up a "tap" (third party package repository) for you if you'd like to. Trivial stuff.

**Comment by jarun** [comment]
Thanks @shaggytwodope, I'll add `Makefile.generic` with `-O2` and `march=native` removed. You can use it for PPA and AUR.

@zmwangx I'll get you 50 stars... Just wait till next release. I'm pretty sure `nnn` would be popular among people who like the convenience of the desktop at the speed of the terminal. ;)

**Comment by zmwangx** [comment]
You can set up a "tap" as I said in the meantime to make it easier for Mac users to install (it's a difference of `brew install jarun/nnn` vs `brew install nnn` when it's accepted into core). That might or might not help you get to 50 stars sooner.

**Comment by jarun** [comment]
> You can set up a "tap" as I said in the meantime to make it easier for Mac users

Only if it doesn't take a lot of your time :)

**Comment by zmwangx** [comment]
As I said it's trivial :) It will be one short Ruby file similar to https://github.com/Homebrew/homebrew-core/blob/master/Formula/googler.rb, and brief instructions in this repo's README (could be as brief as `brew install jarun/nnn` I wrote above).

**Comment by zmwangx** [comment]
I would have to do the same anyway to submit it to homebrew/core.

**Comment by jarun** [comment]
Thanks @zmwangx! Can't thank you enough.

Makefile.generic added at 5df231947392475ced257a6ba5e4cec3c3fbb5a9.

**Comment by jarun** [comment]
v1.0 released!

**Comment by shaggytwodope** [comment]
@jarun aur and ppa package up. working fine for me all around.

**Comment by jarun** [comment]
Myself and @zmwangx are prying you used https://github.com/jarun/nnn/commit/85d7f2762e9fa1bf927955be1dca03e0a3b91aff. ;)

**Comment by zmwangx** [comment]
I'm not prying ;)

**Comment by jarun** [comment]
he is crying probably!

**Comment by jarun** [comment]
Hehehehehe!

**Comment by jarun** [comment]
Basically we changed the release tag 1/2 commits forward. So please make sure you are using the right thing. Sorry @shaggytwodope... we rushed at the last moment.

**Comment by shaggytwodope** [comment]
@jarun I'm aware, caught it during tests on the VM. That hash change during testing... messing with me lol.

**Comment by jarun** [comment]
@zmwangx you are going to get the 50 stars tonight! ;)

**Comment by zmwangx** [comment]
Submitted https://github.com/Homebrew/homebrew-core/pull/12446.

**Comment by jarun** [comment]
Thanks! Just woke up. Great to see both have happened!

**Comment by szlin** [comment]
I had packaged and pushed into Debian archive - experimental. Because Debian 9 is under test with full freeze [1], I will move it to SID afterwards.

ref:
[1]: https://wiki.debian.org/DebianStretch

**Comment by jarun** [comment]
Thanks Lin! :+1:

**Comment by jarun** [comment]
Thanks Lin!
