### ISSUE TITLE
Inconsistency when opening nnn

### ISSUE THREAD

**Issue by axelcalixte** [jarun/nnn#600]
Hello I'm sorry if this issue isn't related to nnn. I figured you might be able to help. 
I was configuring nnn and noticed that launching nnn from my shell normally or by typing "st -e nnn" in dmenu worked but using the keybind I set to "st -e nnn" in dwm doesn't load my configs for colors for example.

Do you have any input on that ?
Thanks in advance

**Comment by jarun** [comment]
Your variables are not exported. Please check this Wiki section: https://github.com/jarun/nnn/wiki/Advanced-use-cases#desktop-integration
