### ISSUE TITLE
escaping single quote characters in filenames when sending selection via lftp

### ISSUE THREAD

**Issue by protrolium** [jarun/nnn#601]
**Environment details (Put x in the checkbox along with the information)**

[x] Operating System: macOS 10.13.6 High Sierra
[ ] Desktop Environment:
[x] Terminal Emulator: iTerm2
[x] Shell: bash
[ ] Custom desktop opener (if applicable):
[x] Issue exists on nnn master

Not sure if anyone else has come up against this issue when sending the contents of ${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection to `lftp` as demonstrated in [Connect to server and and copy selection manually](https://github.com/jarun/nnn/wiki/Advanced-use-cases#connect-to-server-and-and-copy-selection-manually). I have set up the alias `lst` to grab the contents of `.selection` and add to `files.lftp`. Spaces are escaped fine with `xargs -0` but file names that contain a `'` break the transfer as paths can no longer be resolved. I see that files.lftp encloses everything in single quotes.

 Someone I asked for help regarding escaping in the shell suggested a `sed` funtion i.e.
`    function lst {
      sed -E "s/'/\\\'/g; s/(.*)/put '\\0'/;" example_selection
    }`

but I have not been able to implement in order to test.

**Comment by jarun** [comment]
@KlzXS this isn't really an `nnn` issue but is there a solution to escape single quotes in file names easily?

**Comment by jarun** [comment]
@protrolium probably you can refer to the second string in the `patterns` global array in nnn.c, line 638. It has an example use case of sed with xargs. And also try not to have godforsaken characters in your filenames if you can't handle them. There's a mass-rename feature in `nnn` too! ;)
