### ISSUE TITLE
Public Signature Key?

### ISSUE THREAD

**Issue by githububub** [jarun/nnn#602]
Where can we find the public key for BBAD0B2F3093A7C3377A8F6BA75979F35C080412? 
```
$ curl --proto =https --tlsv1.3 https://github.com/jarun.gpg
-----BEGIN PGP PUBLIC KEY BLOCK-----
Note: The keys with the following IDs couldn't be exported and need to be reuploaded C0A712ED95043DCB, A75979F35C080412


=twTO
-----END PGP PUBLIC KEY BLOCK-----~ $
```
Thanks.

**Comment by jarun** [comment]
See if this helps: https://github.com/jarun/nnn/wiki/Developer-guides#verify-sources

If not, @maximbaz can you please take a look?

**Comment by jarun** [comment]
@githububub what's this link? https://github.com/jarun.gpg

Why must it be verifiable?

**Comment by githububub** [comment]
No go. The public key for the private signing key needs to be imported into our personal keychains in order to verify the validity  of the signed source package. That public key does not appear to be published anywhere publicly.

**Comment by jarun** [comment]
> needs to be imported into our personal keychains

What's your personal keychain?

**Comment by githububub** [comment]
A few devs have posted their keys in a similar fashion is why I attempted that method.

**Comment by githububub** [comment]
Personal GnuPG keychain. 
```
$ gpg --verify nnn-3.2.tar.gz.sig nnn-3.2.tar.gz
gpg: Signature made Mon 25 May 2020 05:29:36 PM PDT
gpg:                using RSA key BBAD0B2F3093A7C3377A8F6BA75979F35C080412
gpg: Can't check signature: No public key```

**Comment by jarun** [comment]
I tried the following:

```
1 ~$ gpg --keyserver hkp://keys.gnupg.net --recv-keys C0A712ED95043DCB
gpg: key C0A712ED95043DCB: "Arun Prakash Jana <engineerarun@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
1 ~$ gpg --keyserver hkp://keys.gnupg.net --recv-keys A75979F35C080412
gpg: key A75979F35C080412: 10 signatures not checked due to missing keys
gpg: key A75979F35C080412: "Arun Prakash Jana <engineerarun@gmail.com>" 9 new signatures
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: Total number processed: 1
gpg:         new signatures: 9
```

@maximbaz may be able to help you. He does that verification.

**Comment by githububub** [comment]
Done. Thanks.
