### ISSUE TITLE
terminal messed up

### ISSUE THREAD

**Issue by ghistes** [jarun/nnn#603]
I' just downloaded version 3.2 and compiled it.
Started nnn (without any specific configuration at all), navigated to the Makefile in the directory where I cloned nnn into and pressed Enter. 
Nothing happens, so I press "q" to quit.
Result: Terminal messed up (eg: history no longer accessible by cursor-keys).

**Comment by jarun** [comment]
I can't spend time on this. Someone else has to pitch in.

@ghistes you need to add a lot more info. Config you use, options you use etc.

**Comment by jarun** [comment]
Also @ghistes are you sure it's not #504 again?

**Comment by 0xACE** [comment]
I'm not sure what happens when vanilla `nnn` opens files these days. But do other files open as expected when you press `enter`?

**Comment by jarun** [comment]
If I start `nnn` without any config:

    nnn
When I hit Enter on Makefile, it opens in mousepad (as expected, xdg-open in play).

@ghistes what is your default opener?

For me it's `xdg-open` so if I try

    xdg-open Makefile
it opens in mousepad and for `nnn` also it opens in mousepad.

Try the following from the terminal command prompt:

    your_opener Makefile
and see what it opens the file in. If it opens in your $EDITOR (vim or something else cli), you have to use the option `-e`.

**Comment by jarun** [comment]
I am closing this issue. I think it's pretty basic. Read the Quickstart again: https://github.com/jarun/nnn#quickstart

**Comment by jarun** [comment]
@ghistes is the issue resolved?
