### ISSUE TITLE
Why would I use nnn over other file managers?

### ISSUE THREAD

**Issue by Wuzado** [jarun/nnn#604]
Hi,

just wondering: why would I want to use nnn over, let's say, Midnight Commander, ranger or similar file managers on modern devices? For example, mc seems a lot more advanced and with more features.

I'm not saying that this project is bad, in fact, I'm quite interested, but how does it compare to other actively developed projects? Might be worth adding a section about it in your wiki/docs :smile:

**Comment by jarun** [comment]
Use the one that suits you best.

**Comment by 0xACE** [comment]
Hey,

Most of the devs are busy atm and responding to this post would require a massive time effort. I'll try to keep myself short.

**1.** ~~sanic~~... nnn is fast, it is noticable on slow or old machines.
![image](https://user-images.githubusercontent.com/1482942/83259373-74d5cb00-a1a7-11ea-8dd3-8c7ad8e5b31c.png)
**2.** It is customize-able via a simple yet powerful plugin system.
![2020-05-29_15-23-58](https://user-images.githubusercontent.com/1482942/83264997-6c35c280-a1b0-11ea-9f5f-5517f153c4f7.gif)
The gif is showing `nnn` previewing videos I have custimized it to:
1. jump 10% into the video (ignores hollywood logos and instantly gives you the context)
2. starts with 0% volume when you start the `preview-plugin` but it will memorize the volume for the session
3. I don't like `nnn` previewing into directories of non visual-data, so I only preview thumbnails of visual data, or if it only contains 1 movie, then it previews the movie as described in a and b.

**3.** There are more features but I have allotted too much time for this single post.

You shouldn't need more than that in a file browser, and if you do, just see point 2, adjust it to your needs.

Maybe in the future it gets more powerful if we give plugins control over what `nnn` displays, but as I said the devs are busy...

**Comment by leovilok** [comment]
@0xACE Is your preview plugin public? does it work with unpatched `nnn`? (Is it Mob Psycho 100? I need to watch this show...)

**Comment by jarun** [comment]
I agree! @0xACE this needs to go public! :+1:

**Comment by 0xACE** [comment]
> @0xACE Is your preview plugin public?

It is actually your plugin, but I changed some of the `MIME` cases.

>does it work with unpatched `nnn`?

Yes, but I had to get a `mpv` plugin that memorizes volume control, and applied the volume memorization to a profile.

in `preview-tabbed`:
`jq -c '.volume=0'  ~/.mpv/persistent_config.json | sponge ~/.mpv/persistent_config.json` was added to the top.

`/usr/bin/mpv --profile=preview --start=15% --force-window=immediate --loop-file --wid="$XID" "$FILE"` was put on for audio and video

`sxiv -t` launches in thumbnail mode. There is more work to be done for this, but I haven't put that on my priority yet.

and `~/.mpv/config`
```
[preview]
script-opts-add=persist_properties-properties=volume
```
see https://github.com/d87/mpv-persist-properties

> (Is it Mob Psycho 100? I need to watch this show...)

Haha, I recommend it.

> I agree! @0xACE this needs to go public! +1

Yeah, but atm it's using a lot of personalization.

Once my schedule cools down I'll get back on this topic. But for the impatient I've supplied the necessary info above.

Cheers

**Comment by jarun** [comment]
Do you have a larger version of the gif? I think it would make a great header for our Live Previews page.

**Comment by 0xACE** [comment]
> Do you have a larger version of the gif? I think it would make a great header for our Live Previews page.

I do have it as a 720p mp4. this one was small enough to not piss people off... github doesnt allow drag and drop of videos onto here...

Problem is, I have no where to upload media...

**Comment by Wuzado** [comment]
Thanks for the replies, especially thank you @0xACE !

These are really valid points, and I love the plugin you made! Not sure if nnn will become my daily driver, but I wish you the best!
