### ISSUE TITLE
-std=c11 required?

### ISSUE THREAD

**Issue by sjmulder** [jarun/nnn#605]
What's the idea behind `-std=c11`? Is it for future use? The current code works with `-std=c99` too. I noticed it was added with the use of `memccpy()` but as far as I can tell that's a POSIX thing.

I'm not here to argue against or for C11 usage, just wondering why the flag was added at this point. It broke a build on CentOS 6, which isn't a big deal, but I was surprised to see that `-std=c99` worked just as well.

**Comment by jarun** [comment]
Without it `restrict` is not identified on CentOS.

**Comment by sjmulder** [comment]
Ah, but `restrict` is in C99 as well. Hence with `-std=c99` it builds fine on CentOS 6, 7, 8.

**Comment by jarun** [comment]
Yes, it's there in C99 as well. I chose to select the newer (and presumably better) spec.

Are you seeing any issues, in case?

**Comment by sjmulder** [comment]
Fair enough! For me it's just a build failure on CentOS 6 when using the system compiler. It's easily worked around for now by using `-std=c99` on GCC <4.8. When that's not sufficient a dependency on a newer GCC can be added to the package. No big deal.

**Comment by jarun** [comment]
Got it! Isn't CentOS 6 EOL?

**Comment by sjmulder** [comment]
Wouldn't be surprised but as long as my VM works and it's not too much effort I'll keep it building, especially since Joyent still seems to be providing el6 binary packages from pkgsrc.

**Comment by jarun** [comment]
Okk.
