### ISSUE TITLE
Idea: Kakoune Integration

### ISSUE THREAD

**Issue by basbebe** [jarun/nnn#609]
This is merely an idea and maybe something I will contribute to the wiki or a plugin in the coming weeks (or someone else who has a better idea).

I really like [Kakoune Editor](https://github.com/mawww/kakoune). It is rather simple and lean and I like it‘s design philosophy by haven’t everything easily integrated by external Posix-compliant tools.

It has sessions you can create and connect to.

So it could be great to work as a detached editor.

And using tmux or kitty (trying out the latter at the moment), nnn could be a great filemanager for kak.

**Comment by jarun** [comment]
Good to know about kakoune editor. Do we need anything special from `nnn`? I would assume it would work like any other editor. If it works in the CLI mode users can just set $EDITOR/$VISUAL to kakuone and we should be good to go. I would like to refrain from documenting anything very specific to a particular utility other than if it's a widely used a vim OR there's a known issue.

Of course, feel free to add a plugin if it needs a complex setup or config.

Alos, in general, please discuss these initiatives in the ToDo list. This is not a defect per se.
