### ISSUE TITLE
Update to 3.2 broke NNN_PIPE export in environment

### ISSUE THREAD

**Issue by anddam** [jarun/nnn#611]
The update to 3.2 broke the export of `NNN_PIPE` to plugins. In my case fzcd stopped changing the current directory.

I can build 3.1 and confirm that a shell spawn with `!` has

```
$ env | grep NNN
NNNLVL=1
NNN_PLUG=c:fzcd;
NNN_PIPE=/tmp/nnn-pipe.4582
```

whereas running the same on 3.2 (binary package from Void Linux but the source is built unmodified)

```
$ env | grep NNN
NNNLVL=1
NNN_PLUG=c:fzcd;
```

#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Void Linux
[ ] Desktop Environment:
[x] Terminal Emulator: st
[x] Shell: bash
[ ] Custom desktop opener (if applicable):
[x] Program options used: `NNN_PLUG=c:fzcd;`
[ ] Configuration options set:
[] Issue exists on `nnn` master: 

#### Exact steps to reproduce the issue

- Build 3.2
- run it
- start a shell with `!`
- type `env | grep NNN`

**Comment by jarun** [comment]
Yes. We have a specicifation in place now for plugins to talk back to `nnn`: https://github.com/jarun/nnn/tree/master/plugins#send-data-to-nnn

This was necessary to improve the communication between `nnn` and the plugins. Please update the plugins and they will work again.

**Comment by jarun** [comment]
I will update the public release notes with this information.

**Comment by anddam** [comment]
> Yes. We have a specicifation in place now for plugins to talk back to `nnn`: https://github.com/jarun/nnn/tree/master/plugins#send-data-to-nnn

Took me a while to figure, the change you were pointing to was the opcode addition to nnn_cd shell function. Env variable `NNN_PIPE` is still supposed to be there but it was not shown in my shell since it is exported once any plugin has been run, I probably tried to get it in a 3.2 spawned shell before trying to run a plugin.

I would expect a protocol change breaking plugins to be a major release update, i.e. no plugin breakage from 3.1 to 3.2, but I figure as long it's documented it is good to go.

Thanks for the prompt answer.
