### ISSUE TITLE
Can't get preview to work

### ISSUE THREAD

**Issue by kuntau** [jarun/nnn#617]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: MacOS 10.14.6
[ ] Desktop Environment:
[x] Terminal Emulator: iTerm2
[x] Shell: zsh
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[x] Issue exists on `nnn` master

```sh
NNN_PLUG=f:fzcd;o:fzopen;z:fzz;d:diffs;t:treeview;v:preview-tui
NNN_FIFO=/tmp/nnn.fifo
TMUX v3.1b
nnn v3.2
```
Maybe I'm just dumb, but I can't get the preview to work.

1. I hover on file
2. Press `;`
3. Press `v`
4. `nnn` just flickered but nothing show.. what did I miss? 🤔

Please help. Thank you

**Comment by jarun** [comment]
Did you run tmux first and then start nnn from within?

**Comment by kuntau** [comment]
Run tmux first

**Comment by jarun** [comment]
What is the output of `tmux -V`?

**Comment by kuntau** [comment]
tmux 3.1b

**Comment by jarun** [comment]
Also, please try the following patch:

```
diff --git a/plugins/preview-tui b/plugins/preview-tui
index 7872b07..e467236 100755
--- a/plugins/preview-tui
+++ b/plugins/preview-tui
@@ -73,7 +73,7 @@ if [ "$PREVIEW_MODE" ] ; then
     exit 0
 fi
 
-if [ -e "${TMUX%%,*}" ] && [ "$(tmux -V | cut -c6)" -eq 3 ] ; then
+if [ -e "${TMUX%%,*}" ] ; then
     tmux split-window -e "NNN_FIFO=$NNN_FIFO" -e "PREVIEW_MODE=1" -dh "$0" "$1"
 else
     PREVIEW_MODE=1 $TERMINAL -e "$0" "$1" &
```

**Comment by jarun** [comment]
Forget the patch in that case. The issue is somewhere else.

**Comment by jarun** [comment]
Try the following:

1. tmux
2. nnn -a
3. `;` followed by `v`

What do you see?

**Comment by jarun** [comment]
I need fast follow-up here. Don't have a lot of time in hand. Plugins are indicative. In most cases we request users to modify and suit themselves. I am offering some help here because it's a very new plugin.

**Comment by kuntau** [comment]
ok so I fcked up.. for some reason the `preview` plugin wasn't there when I first install.

Now that it's there I got some error
```
terminals database is inaccessible
tput: unknown terminal "tmux-256color"
tput: unknown terminal "tmux-256color"
head: illegal line count -- -1
```

**Comment by jarun** [comment]
Try:

echo $TERM

**Comment by kuntau** [comment]
I think there should be some check whether the plugin exist when invoked. There was no error.

**Comment by kuntau** [comment]
```
echo $TERM
xterm-256color
```

**Comment by jarun** [comment]
> I think there should be some check whether the plugin exist when invoked

We can't do that. The mechanism works not only for plugins but also for running commands as plugins. So if you don't install a plugin and try to run it, `nnn` would try to run it. As long as `nnn` does not crash, I don't see a problem.

I have the same: `xterm-256color`.

I think it has to do something with some stray `tput` command you have somewhere. Definitely not an `nnn` issue. Please solve local environment issues yourself.

**Comment by jarun** [comment]
Try google. I found this: https://superuser.com/questions/319912/i-cant-clear-the-terminal-in-mac-os-x-lion-terminals-database-is-inaccessibl

**Comment by leovilok** [comment]
It seems that you don't have a `terminfo` entry for `tmux-256color`, try running the `tput` command in tmux, you probably already see the error message. This is not related to `nnn`, but if it's the default on MacOS we'll have to write a workaround (we use `tput`, from ncurses, to get the terminal's row/columns). But I think that the issue is with your system because without a working terminfo for tmux, no ncurse based terminal app should work well.

**Comment by kuntau** [comment]
@leovilok apparently `nnn` don't like `tmux-256color` so I've changed all back to `xterm-256color`. Solved

**Comment by leovilok** [comment]
Well we don't do anything directly with $TERM, we just use `tput` (part of ncurses) in a few plugins ... but good to know it fixes it for you.

**Comment by Kabouik** [comment]
On Sailfish OS, I observe the same flickering behaviour @kuntau reported. That's with  `nnn -a` after running `tmux`.

```
# nnn
export NNN_COLORS='4321'
export NNN_PLUG='t:preview-tui;v:_viu $nnn'
export NNN_FIFO='/tmp/nnn.fifo'

tmux next-3.2
nnn 3.2
xterm-256color using havoc terminal (but same issue in other terminals that use xterm or screen)
```

The plugin works out of the box on my computer with git `nnn`, Tilix and `tmux` 3.1b, so I suppose I might just be missing a dependency or something. I tried changing `$TERMINAL` in the script but that will open a new terminal for previews instead of the pane preview.

**Comment by jarun** [comment]
The problem is `tmux next-3.2`. The check we have currently is:

    "$(tmux -V | cut -c6)" -eq 3

which fails. I also compiled tmux from source and faced this problem. You can hack the code to change the version to "3.2". That's what I did.

**Comment by Kabouik** [comment]
Excellent, thanks! For testing, I just removed the version check you quoted from `preview-tui` and that works. In my case it might be easier to do just that instead of changing the version `tmux` reports.

**Comment by jarun** [comment]
@leovilok and @KlzXS any way to make the check more accurate?

**Comment by jarun** [comment]
Maybe check if next is present?

**Comment by Kabouik** [comment]
For the record, works pretty well on the phone (and from SSH too of course): https://asciinema.org/a/336296

I am happy.

I get these weird warnings with `tree`, but I suspect it's due to the fact that I had to use Node.js `tree-cli` instead of the usual `tree`.

**Comment by kuntau** [comment]
> @leovilok and @KlzXS any way to make the check more accurate?

@jarun I use my modified version with this regex.. so far it worked on all tmux version variations

```sh
TMUX_VERSION=$(tmux -V | sed -En "s/^tmux[^0-9]+([0-9]+(.[0-9]+)?).*/\1/p")

if [ -e "${TMUX%%,*}" ] && [ "$(echo "$TMUX_VERSION >= 3.1" | bc)" = 1 ] ; then
....
```

**Comment by jarun** [comment]
@Kabouik we are going to link it from the wiki or plugins doc. Is that fine?

@kuntau please raise the PR.

**Comment by Kabouik** [comment]
@jarun The asciinema cast, you mean? If so, wait, I'll make a better version with true colors enabled (`viu` previews were rendered without true colors in `tmux`).

**Comment by jarun** [comment]
Yes, the asciinema cast. A better version would be great! Thanks a lot in advance!

**Comment by Kabouik** [comment]
Here is the new one: https://asciinema.org/a/r3cDlyp2UZ0kLbO5GavPGcM8z

I improved the description a little, and it now shows contexts in action as well as text preview. The `viu` previews looked better on the phone, `asciinema`'s conversion degraded them.

**Comment by leovilok** [comment]
@Kabouik it's a shame that you have those "Terminated ..." messages, try this replacement:
~~~diff
-kill %- %+ 2>/dev/null
+kill %- %+ 2>/dev/null && wait %- %+ 2>/dev/null
~~~

@kuntau this might be a bit simpler, but not v4.0 proof:
~~~sh
if [ -e "${TMUX%%,*}" ] && tmux -V | grep -q '[ -]3\.' ; then
~~~

**Comment by Kabouik** [comment]
Awesome, that improves it a lot @leovilok! The warnings still show up if I scroll too fast, I'm guessing it happens when I hover a new directory while the previous was still being fetched. If that's not easily flexible, I am happy to make another cast now, otherwise we can try to fix that too.

**Comment by jarun** [comment]
@leovilok I made it future version proof to version 9. See commit 56eea7e195e98eedca374cfc24cc43afe73d43db. Should give us a lot of time. ;)

**Comment by Kabouik** [comment]
Nice @jarun.

> I'm guessing it happens when I hover a new directory while the previous was still being fetched
Note this also causes issues with `viu` because if you scroll very fast (using key repeat on `DownArrow`), `viu` will not skip files you did not stop onto, but instead queue all of them before rendering the file you actually wanted to target. I think it would be good to implement a way to interrupt a preview still loading when another one is triggered on another file. When the previewer is not instantaneous (heavy work or old machine), this would likely solve the issues such as those detailed here for `tree-cli` and `viu`.

**Comment by leovilok** [comment]
@Kabouik interrupting is already implemented, just use `viu "$1" &` instead of `viu "$1"`.

**Comment by Kabouik** [comment]
Thanks all for your help. All issues fixed, so here is a clean cast for the wiki or the plugin page: https://asciinema.org/a/336439

**Comment by jarun** [comment]
Thanks for the cast!

**Comment by jarun** [comment]
Its live: https://github.com/jarun/nnn/blob/master/plugins/README.md

**Comment by Kabouik** [comment]
Nice. I tried to make a .svg out of it so you could embed the animation in the readme (it's not obvious that there is an animation if you click on it), but so far it's [not working](https://github.com/marionebl/svg-term-cli/issues/62).

I'll post an update here with the file when/if I succeed.

**Comment by leovilok** [comment]
It might be easier to turn it into a .gif?

**Comment by jarun** [comment]
Even the asciicast is fine.

**Comment by Kabouik** [comment]
> @leovilok I made it future version proof to version 9. See commit [56eea7e](https://github.com/jarun/nnn/commit/56eea7e195e98eedca374cfc24cc43afe73d43db). By the time tmux reaches v9 we can remove the check. ;)

Does it work with tmux versions containing a letter too?

```
kabouik@xiaomimi-solus ~ $ tmux -V
tmux 3.1b
kabouik@xiaomimi-solus ~ $ tmux -V | grep -q '[ -][3456789]\.'
kabouik@xiaomimi-solus ~ $ 
```

As a result the plugin tries to run `xterm` on this machine. Again I can just remove the version check manually since I know I use a version >3.0, but just wanted to report this corner case.

**Comment by jarun** [comment]
@leovilok help!!!!!!!!!!!!!!!!!!!! Guys can't you google search and raise a PR? Because if I want to fix it I'll do that.

**Comment by leovilok** [comment]
@Kabouik it works:
~~~
$ check () { printf '"%s": ' "$1" ; echo "$1" | grep -q '[ -][3456789]\.' && echo true || echo false; }
$ check "$(tmux -V)"
"tmux 3.1b": true
$ check "tmux 2.3.1b"
"tmux 2.3.1b": false
$ check "tmux next-3.0"
"tmux next-3.0": true
$ check "tmux next-4.1"
"tmux next-4.1": true
$ check "tmux 2.27-3"
"tmux 2.27-3": false
$ check "tmux sdfghjk 3.42.3.1.4"
"tmux sdfghjk 3.42.3.1.4": true
~~~

**Comment by Kabouik** [comment]
Sorry jarun, regex is out of reach for me so I did try to fix it myself using some doc, but didn't succeed Turns out the issue was probably somewhere else anyway given what leovilok just showed (thanks by the way).

**Comment by Kabouik** [comment]
> Nice. I tried to make a .svg out of it so you could embed the animation in the readme (it's not obvious that there is an animation if you click on it), but so far it's [not working](https://github.com/marionebl/svg-term-cli/issues/62).
> 
> I'll post an update here with the file when/if I succeed.

I finally managed to convert it to .svg for automatic animation without going to asciinema.com, but the file is a bit large (6 MB), which might be inconvenient for small connections so maybe it's not a good idea anyway. I just wanted to update this post as I said I would, though. In any case, svg or not, I will try to make another asciicast in the future if you think that could be useful, now that `preview-tui` has been significantly improved in the past few days.

[asciicast-nnn.zip](https://github.com/jarun/nnn/files/4776872/asciicast-nnn.zip)

**Comment by jarun** [comment]
> In any case, svg or not, I will try to make another asciicast in the future if you think that could be useful

That's a good idea. We can have a demo of the latest features, probably with better image rendering etc.
