### ISSUE TITLE
clarification on the use of `-E`

### ISSUE THREAD

**Issue by basbebe** [jarun/nnn#620]
I' sorry but I think I don't understand when I would use the `-E`-Option.  
It seems to me that when I use `-c` and `nuke`, it would open textfiles with $EDITOR anyway.  
Would I use it only when I have another opener selected?  
Or does it only affect the `e` shortcut?

**Comment by jarun** [comment]
Please refer to: https://github.com/jarun/nnn/wiki/Basic-use-cases#detached-text

Specially the note that starts with "IMPORTANT".

**Comment by basbebe** [comment]
Thanks, I think I got it now.

Wouldn’t it make sense then to have nuke check vor $VISUAL by default (or with $gui enabled)?

**Comment by jarun** [comment]
> Wouldn’t it make sense then to have nuke check vor $VISUAL by default (or with $gui enabled)?

The header of `nuke` starts with:

    Description: Sample script to play files in apps by file type or mime

It's a _sample_. Applies to every plugin.

I think everyone who uses nuke will modify it to use their own programs. So when you start using it, please customize it as per your needs.

**Comment by basbebe** [comment]
Probably, yes.
Thanks!
