### ISSUE TITLE
arm and aarch releases with statically linked dependencies

### ISSUE THREAD

**Issue by Kabouik** [jarun/nnn#623]
**Is your feature request related to a problem? Please describe.**

I see that there are releases with statically linked dependencies, which can be very convenient on some systems. However there are no arm or aarch releases. Would that be feasible or are there dependencies missing on these architectures? 

**Describe alternatives you've considered**

I've considered building on device, and will look into it if releases with statically linked dependencies cannot be offered in more architectures.

**Additional context**

I think it would be nice for some single board computers or even mobile phones featuring a hardware keyboard (in my case, F(x)tec Pro¹ running SailfishOS).

**Comment by jarun** [comment]
I think cross-compiling for arm and aarch should be possible to do this on CiscleCI. But I can't spend time on it. If you are interested, please try it and raise a PR. Otherwise I can add this as a line item.

**Comment by Kabouik** [comment]
Thanks for the quick answer jarun. There's hope then, I was afraid some missing libraries would end the discussion.

I don't know CircleCI. I will have a look at it but I'm not sure how far I can get. You should know that I'm not developer, I just use `nnn` because I like the kind of workflow it allows.

**Comment by jarun** [comment]
I think you'll have to download the source of the libs and cross-compile them too.

> You should know that I'm not developer

In that case it's simpler for you to follow the [instructions](https://github.com/jarun/nnn/wiki/Developer-guides#static-compilation) in the Wiki and compile it locally on your Pi or Android. I will add a line item and close this issue.

**Comment by jarun** [comment]
Added as a line item in the ToDo list.

**Comment by Kabouik** [comment]
Thanks. When this is available, if I have you approval, I would be happy to package that into .rpm for easier distribution among Sailfish OS users using the community-driven store. It's a small community but there would be some people interested in `nnn`.

First, I'll try to compile on device in the next few days.

**Comment by Kabouik** [comment]
Well. Turns out we have the two dependencies main dependencies in the official repo in SFOS, so I could git clone `nnn` and compile it directly using `make strip install`, no need to build libraries first. Static binaries would still be a plus for other OSes if that's not too much work,

**Comment by jarun** [comment]
> If I have you approval, I would be happy to package that into .rpm for easier distribution among Sailfish OS users using the community-driven store.

Of course! We are happy to have `nnn` available for users as easily as possible.

> I could git clone nnn and compile it directly using make strip install, no need to build libraries first.

That's good news. I think even on Alpine it's pretty straight. My point was on cross-compiling. I am not sure if CircleCi provides distro images with arm or arch architecture.

**Comment by Kabouik** [comment]
While starting to write the .spec file, I noticed in your .yaml that you summarize nnn as `The missing terminal file manager for X`. Is this reference to X still valid? It seems that nnn works fine on a pure Wayland system too, no?

**Comment by jarun** [comment]
When we started there was X. Just live with it. ;)

**Comment by Kabouik** [comment]
Thanks, I was just curious!

**Comment by jarun** [comment]
No problem! You are not the first one to ask. But I do enjoy the satire in the tagline.

**Comment by Kabouik** [comment]
For reference: https://openrepos.net/content/kabouik/nnn

Now I'm wondering which plugins would work on SFOS. Sadly I don't think we have any terminal supporting sixel for image preview.

**Comment by jarun** [comment]
viu would be it. But in general we do not suggest shipping plugins because they have third-party dependencies themselves. The best option is for the user to download and setup.

**Comment by Kabouik** [comment]
I'll look into viu, thanks. I totally agree, I won't ship plugins with the package.

**Comment by jarun** [comment]
Can you please add it here along with the unlisted ones (expand to see them): https://github.com/jarun/nnn/wiki/Usage#installation

Alternatively, you can consider adding SailfishOS to repology.

**Comment by jarun** [comment]
I have updated the listing to alphabetical order. Also removed the reference to the app because users are supposed to know the package manager app on the distro they use.

**Comment by githububub** [comment]
Raspbian Stable users will appreciate this (last I checked a few weeks back, nnn from the official repos was at 2.x)...

**Comment by jarun** [comment]
Guys, we have a line item in ToDo list and no one is picking it up. Does that ring a bell?

I don't need it because I can compile directly on my boards and phone. Please refrain from leaving notes about something that's already added as a line item. I have to read hundreds of mails/comments in the morning and if I can save 2 minutes not re-reading known stuff that helps.

**Comment by jarun** [comment]
> (last I checked a few weeks back, nnn from the official repos was at 2.x)...

Did you check Raspbian Testing version on repology? It's on 3.2. Why do I have to look that up for you and leave a note so the next reader doesn't get wrong info?

**Comment by jarun** [comment]
The latest releases have moved to OBS and we generate both arm and aarch binaries. If you need anything extra there, please pitch in without any further notes. ;)
