### ISSUE TITLE
Handle 'No space left on device' for mv and cp

### ISSUE THREAD

**Issue by 0xACE** [jarun/nnn#624]
Moving a file to a drive that is full results in parts of the file being copied and not displaying any error.

For the end user it looks like everything went fine, except for these details:

1. the `destination` file is the wrong size (very difficult to determine if you are unlucky)
2. the `destination` file may not inherit the same fACL
3. `source` file still exists. (it was very tempting to delete it)

This almost caused me to delete the `source` file when i browsed back to the source directory.

I'm glad I didn't delete it.

I tried re-executing the transfier, yielding the same result. I didn't realise the problem until I manually went to the terminal and executed `mv source destination`, that's where I saw the error message.

I was missing 8mb on the destination drive, hence I had difficulty discerning the error from `nnn`.

Posted it here in case you have any opinion on this problem, not sure what to do about it atm.

**Comment by jarun** [comment]
cp and mv are run in the interactive mode. The problem is the program is failing silently in this case.

I think we can add an option to wait after cp and mv so the user can read the results. Probably a switch to pass `F_CONFIRM`.

**Comment by 0xACE** [comment]
I don't know atm.

It's not an emergency.

I just wanted to put it out there in hope that another mind also thinks about it until we find a good solution...

**Comment by jarun** [comment]
@0xACE please confirm if this waits for user input when the error occurs. I think this is the best we can do to notify the user.

**Comment by 0xACE** [comment]
Works on `cp` and `mv`.

a slight annoyance is that it gets cluttered with text from `mvg` but that can very well be a environment issue on my end...

Consider the problem solved. thanks.
