### ISSUE TITLE
Preview images using an image to ascii tool

### ISSUE THREAD

**Issue by Kabouik** [jarun/nnn#628]
**Is your feature request related to a problem? Please describe.**

Some systems have no terminals with sixel support or any other ways of displaying images. That includes old systems, but also those whose native software ecosystem may not be big, or simply terminals that are meant to be minimal.

**Describe the solution you'd like**

I was wondering if any image to ascii tool is known to work with nnn already (I didn't find anything in past issues), or planned. Something like the [AA-project](http://aa-project.sourceforge.net/gallery/) for instance; but there may be alternatives. I find the result surprisingly good:

![](http://aa-project.sourceforge.net/gallery/krizik.png)

**Describe alternatives you've considered**

I considered plugins in the plugins page but I think they all depend on terminal sixel capability.

**Additional context**

On the one hand, I admit this would probably not be useful to many users and this could just be a gadget. However, on the other hand, this would make nnn able to preview images in any terminal, even antique or minimal. I don't know much about other terminal file browsers, nnn being the first one I adopted, but I believe ranger has something like that.

The accuracy of the conversion shown above is already plenty enough to sort images and find a particular image in a long file list.

**Comment by Kabouik** [comment]
I see now that you recommended `viu` in another issue, I missed it. I will check it out. Ascii might still be useful for terminal with base colours, but I understand that makes it even more of a corner case.

**Comment by jarun** [comment]
> I was wondering if any image to ascii tool is known to work with nnn already (I didn't find anything in past issues), or planned. Something like the AA-project for instance; but there may be alternatives.

The plugins are example scripts. user preferences differ widely. So we encourage users to use their favourite tools in the plugins instead of us adding some utilities beforehand. Still there is some deviation for nuke but that's very well-documented.

**Comment by leovilok** [comment]
There are a ton of image to text tools, you can uncomment the example provided in `preview-tui`: https://github.com/jarun/nnn/blob/master/plugins/preview-tui#L73
and replace it with any one.

**Comment by Kabouik** [comment]
Thanks. Interesting, I just downloaded all plugins 2 hours ago using the script recommended on the plugin page, but I do not have this latest version (the commented line is not here for instance). I'll try it.

**Comment by leovilok** [comment]
Hum you're right, and live preview is less usefull on mobile OS I guess ...
But `preview-tui` works with tmux too, I don't know how well it's supported in these environments.

**Comment by Kabouik** [comment]
I have packaged the latest tmux version just two days ago for SailfishOS so that shouldn't be an issue, I think xterm will be the problem. 

Live preview would be very useful for me here because I use SFOS on a phone with a slider keyboard, and the preview would go very well with my 0x0 upload script to select the image I want before uploading it.

**Comment by leovilok** [comment]
If you use tmux, you don't need xterm. Other dependencies are listed in the plugin, but they can be replaced.

**Comment by 0xACE** [comment]
Graphical preview could be done on android, I'd suggest you retro fit mupdf and mpv to handle this for you, not sure about text but that one should be easier then the others.


maybe a browser handles all scenarios... 
![devs-these-days](https://user-images.githubusercontent.com/1482942/83748225-64af6700-a651-11ea-86cc-3c157e1972fa.jpg)
