### ISSUE TITLE
Cannot make a simple plugin work

### ISSUE THREAD

**Issue by benoit-combes** [jarun/nnn#640]
Dear developers,  

First ! thanks for `nnn` ! and sorry if this is not the good place for my problem:

I am using the latest version of the available `nnn` binary (3.2,  for ubuntu 18.*) and do not manage to use plugins. More specifically, while putting in my bashrc:
```
export NNN_BMS='h:~/;t:~/Downloads
export NNN_PLUG='g:_ls'
```
and typing in nnn (I get the 'plugin keys:' prompt after ';')
```
;g
```
I get 
```
invalid key
```

I am sure that the .bashrc file is loaded because the bookmark stuff is working. Have you any idea of why this is not working ?

**Comment by jarun** [comment]
That's really strange. I checked out v3.2, added _only_ the NNN_PLUG you have and it works. Tried both bash and zsh.

There' something else at play here. Can you check what the help screen (press `?`) shows?

BTW, your NNN_BMS is incorrect - the single quote at the end is missing.

**Comment by benoit-combes** [comment]
That's for your input and sorry for my question : I didn't realise that, as nnn uses the env variables, I had to reload the .bashrs and not just to relaunch nnn.... Thanks again and sorry.

**Comment by jarun** [comment]
No problem! Hope you find `nnn` useful.
