### ISSUE TITLE
Close preview windows when edit file

### ISSUE THREAD

**Issue by theblackturtle** [jarun/nnn#653]
Hi, I think the preview windows should be close when you edit the file and reopen the preview window when exiting the editor (like vifm).

**Comment by leovilok** [comment]
The preview window is an external plugin, and don't have a way to know what happens in `nnn` (except what files are hovered). So we can't have this for now, as it would require changing the way `nnn` comunicates with plugins.

Of course, you can manually close the preview window (e.g. <kbd>Ctrl</kbd>+<kbd>c</kbd> in the preview window should work in `preview-tui`).

**Comment by theblackturtle** [comment]
@leovilok Thanks for response. I think preview features should build in `nnn` because it is one of the core of the file manager. That make the file manager more useful.

**Comment by jarun** [comment]
> I think preview features should build in nnn because it is one of the core of the file manager.

Going by your preferences I don't think `nnn` is the right file manager for you. You already have found one that works as you expect. So stick to it or search more and find a suitable one. There are tons of file managers out there.

**Comment by jarun** [comment]
Though it may not align with your expectations from a useful file manager - you can edit and preview at the same time with `nnn`. Pressing `Esc` on the entry will refresh the preview. So you can edit and preview side by side. This is on master.
