### ISSUE TITLE
Show git changes

### ISSUE THREAD

**Issue by amitlevy21** [jarun/nnn#654]
Hi, 
I have opened the same issue in https://github.com/mcchrish/nnn.vim/issues/64 but was asked to ask this feature here.

**Is your feature request related to a problem? Please describe.**

When I change a file in vim, it would be nice if I could see which files were lastly modified since last commit.

**Describe the solution you'd like**

Basicly i'm looking for something like [this](https://github.com/Xuyuanp/nerdtree-git-plugin) for nnn.vim.

**Describe alternatives you've considered**

I'm not sure what else I can do besides asking nicely from the developers to implement this.

Thank you for considering this.

**Comment by jarun** [comment]
`nnn` s a general purpose file manager and there are no plans to have git integration. The best you can have is to use sort by modification time.

**Comment by akimdi** [comment]
@amitlevy21   
use https://github.com/SpaceVim/SpaceVim

**Comment by jarun** [comment]
This is now available as user patch `gitstatus`: https://github.com/jarun/nnn/tree/master/patches
