### ISSUE TITLE
Resizing a window for a TUI app called through NNN_PLUG results in immediate termination of application

### ISSUE THREAD

**Issue by githububub** [jarun/nnn#656]
Release and 4b4bf6c. Not sure if this is intended behavior, or whether the issue is Wayland or sway specific as I do not have a box with X on hand at the moment.

Arch + sway + alacritty
Debian 10 Testing + sway + alacritty

Repro:
1. Set arbitrary `e:-_nano $nnn*;`
2. Launch nano from plugin
3. nano is launched as expected; no issues with use
4. Move and/or resize window containing nnn/nano
5. nano exists and window either corrupts and/or returns `[server exited unexpectedly]`

At this point, the screen is unable to be redrawn with ^L. Issue occurs with tmux/vim/kakoune/kibi/et al. The expecation is that moving/resizing the window will also redraw and resize its contents as seen when the same applications listed above are launched through  _o ^O  Open with..._

**Comment by jarun** [comment]
@leovilok @toddyamakawa @marioortizmanero please take a look.

**Comment by jarun** [comment]
I could repro this with vim and a text file as plugin. Perhaps the child is not handling SIGWINCH?

@leovilok please check f we need to add something here.

**Comment by leovilok** [comment]
I can reproduce, I'll look into it.

**Comment by leovilok** [comment]
@jarun @githububub  #659 should fix this

**Comment by githububub** [comment]
A-OK on my end for the past two hours...
