### ISSUE TITLE
Allow interrupting a long read process

### ISSUE THREAD

**Issue by braykov** [jarun/nnn#657]
**Is your feature request related to a problem? Please describe.**

Yes, when I navigate to locations which are physically on a network and it takes a long time, nnn does not allow me to interrupt the directory read process.
I would expect to be able to navigate with `h` - to go back to parent, or `q` to close this context or `^Q` to close all of nnn, or `TAB` to move to another context while this one continues to read.
None of these are possible.

**Describe the solution you'd like**

I jsut have to wait.

**Describe alternatives you've considered**

When reading a directory contents takes time, I would expect:
- to see a message like "please wait..."
- to be able to use any of the above keys to escape the situation of waiting

**Additional context**

My case is with nnn running on Ubuntu in WSL1. I have a mapped network drive with fstab.
Even in Windows reading the file list in some places there is long.

**Consider contributing**

I guess this would involve an architectural modification, such as, multitasking.

**Comment by jarun** [comment]
> `^Q` to close all of nnn

Have an alias to `killall -9 nnn` (probably add a keybind also) so `nnn` can gracefully exit.
