### ISSUE TITLE
Create multiple directories and files

### ISSUE THREAD

**Issue by gandhiShepard** [jarun/nnn#658]
**Is your feature request related to a problem? Please describe.**
This is related to a convince problem. I often need to create sibling directories and or files.

**Describe the solution you'd like**
It would be awesome if NNN could allow for sibling directory and file creation. So, after pressing `n` and choosing `d` sibling directories could be created by typing something like this `dir1, dir2, dir3`.

And for files, after pressing  `n` and then `f`, typing `file1.txt, file2.md, file3.ex` to create multiple sibling files. 

NNN has been a joy to use. This is my only pain point.  Thanks for this file manager! Be well in these crazy times!

**Comment by KlzXS** [comment]
If this is something we implement I think it is better to open `$EDITOR` and allow you to type the name of each entry on a separate line. That's at the same time more readable and practical.

I'll make a PR for this and notify you when it's in.

**Comment by 0xACE** [comment]
*cough* plugin-system-may-also-appropriate-for-this *cough*

**Comment by jarun** [comment]
@KlzXS Adding a plugin may be a better option (done the same way - spawn editor and use the input). There was another request for this. It would be good to avoid having a new workflow just for this.

**Comment by KlzXS** [comment]
The new plugin is at #662.
