### ISSUE TITLE
Keyboard interrupts do not work when using -s

### ISSUE THREAD

**Issue by orf** [jarun/nnn#66]
If you run `nnn -s`, you cannot use ctrl+c to terminate `nnn` when it is calculating the sizes (on MacOS at least). This ias annoying if you're running it over a huge directory and wish to terminate it.

**Comment by jarun** [comment]
But you can't exit nnn using `Ctrl-C` in normal mode either!

To exit immediately in `navigate-as-you-type` mode, press `Ctrl-Q`.
