### ISSUE TITLE
Some files display as grayed out

### ISSUE THREAD

**Issue by serpent-code** [jarun/nnn#661]
Hello.

Thanks a lot for this amazing piece of software. I've been using nnn for about a year and love many things about it. Multi level filtering is absolutely killer, among other things.

Just a quick question:

Since one of the recent updates some files (or directories) are displayed as grayed out, as shown in this screenshot:

![nnn_Screenshot_2020-06-15_02-44-55](https://user-images.githubusercontent.com/59209771/85080503-980bfd00-b1de-11ea-8bf0-792347f8455e.png)

Interestingly they are still grayed out in NO_COLOR mode when all other coloring is disabled.

I've tried to reason about the basis of what files are grayed out and what files aren't. Date modified/accessed, file size, links, permissions, owner... But none of these seem to make a difference.

I've read the wiki and man pages and couldn't find anything related to this. In fact wiki Home page under design says 4- Only directories in color, no icons. Hm..

So what are these? Any way to disable them but keep using my NNN_COLORS?

I have not opened a bug report issue, because honestly I don't know if it's a bug or an intended feature. Although indeed odd. At any rate here's my environment:

#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Manjaro Linux 20.0.3
[x] Desktop Environment: xfce 4.14
[x] Terminal Emulator: They seem to show up in Alacritty and xfce terminal, but not in st.
[x] Shell: Tried bash and zsh. Files are grayed out in both, directories are only grayed out in zsh.
[ ] Custom desktop opener (if applicable):
[x] Program options used: none, -T, -d, etc
[x] Configuration options set: Tried disabling NNN_COLORS and enabling NO_COLOR
[x] Issue exists on `nnn` master: haven't tried building from master. I'm using nnn v 3.2

#### Exact steps to reproduce the issue
Just opening nnn and browsing normally.

**Comment by 0xACE** [comment]
Since I'm not on master, I'm not sure if this has changed...

but iirc the code responsible for changing color on items had some obscure if statement regarding `BOLD` and what not...

If anyone is taking care of this look at the `printent()` functions...

**Comment by jarun** [comment]
> I've read the wiki and man pages and couldn't find anything related to this

All links are greyed out. Symlinks have @ after them. 
Here's the wiki section: https://github.com/jarun/nnn/wiki/Usage#file-indicators

We work in 8-bit mode and we have to indicate links some way. So this was the way. This has nothing to do with NNN_COLORS.

**Comment by toddyamakawa** [comment]
Interesting, there must be something wrong with my terminal emulator. I see `A_DIM` is supposed to be set for symlinks in nnn, but I still see white.

**Comment by jarun** [comment]
I see them greyed out in xfce4-terminal and xterm. I think dim indicates they will be greyed out.

**Comment by toddyamakawa** [comment]
Maybe my version of `xterm` is just way too old.

```
$> xterm -v
X.Org 7.6.0(295)
```

**Comment by serpent-code** [comment]
Thanks for all the replies and clarifying that.
