### ISSUE TITLE
File and directory lists are not dynamically refreshed for sshfs mounts

### ISSUE THREAD

**Issue by Kabouik** [jarun/nnn#663]
[x] Operating System: Solus
[x] Desktop Environment: i3wm
[x] Terminal Emulator: Tilix
[x] Shell: bash
[x] Program options used: `nnn -arAS -P t "$@"`
[x] Configuration options set: 
```
export NNN_COLORS='4321'
export NNN_PLUG='t:preview-tui;v:_viu $nnn;b:nbak;0:0x0;d:dragdrop;r:renamer;x:remove'
export NNN_FIFO='/tmp/nnn.fifo'
export NNN_TRASH=1
export NNN_ARCHIVE="\\.(7z|bz2|gz|tar|tgz|zip)$"
export NNN_SSHFS="sshfs -o reconnect,idmap=user,cache_timeout=3600"
```
[x] Issue exists on `nnn` master: yes

#### Exact steps to reproduce the issue
When mounting a remote with `sshfs` and creating or deleting files directly on the remote (not from within the local `nnn` session), the changes are not dynamically refreshed inside the local `nnn` session, even after leaving and re-entering the directories, or redrawing with `^L`. Unmounting and remounting successfully refreshed the content. 

I noticed that when compiling and packaging things on my phone from ssh, and seeing no change at all in the corresponding remote mount in `nnn`. Is that a `sshfs` limitation or is there anything `nnn` can do about it?

**Comment by leovilok** [comment]
On linux, `nnn` uses `inotify` to trigger dir refresh, which is not supported by `sshfs`. So this is not our bug, please see:
https://github.com/libfuse/sshfs/issues/155
