### ISSUE TITLE
nnn won't differ symlinks colors in suckless st

### ISSUE THREAD

**Issue by rmwalk** [jarun/nnn#667]
Hi. Not sure if it is really a bug, but the context colors are the same for files and symlinks in st. I've been using alacritty for quite some time and had st as my backup terminal but never really ran nnn in st, only in alacritty. Today I decided to make st my default terminal and noticed that there's no difference between said colors, whilst in alacritty I can see the different colors for files and symlinks. Note that I've installed other file managers to see if it was a problem with st and the colors are the same only in nnn. I've also made a clean st build in case it could be some patch related issue, but nothing changes. Is there some way to fix it?

![nnn](https://user-images.githubusercontent.com/62305685/85617558-d61d7c80-b635-11ea-8472-4b928dbdf6ac.png)

The left-hand side one is st, the right-hand side one is alacritty.

**Comment by KlzXS** [comment]
I'm also using st and for me symlink colors are displayed fine. I also installed a clean version from AUR and it works there too.

Which version of `nnn` are you using, is it from master?

**Comment by rmwalk** [comment]
I'm using the version from the void repo, but I just clean built from master and still have the same result.

**Comment by serpent-code** [comment]
They also don't show up for me in st. But I use Alacritty mainly.

Just replying to mention that as Jarun explained [here](https://github.com/jarun/nnn/issues/661#issuecomment-646386610) , grayed out files are not technically symlinks. They could be hard links if they don't have @ at the end.

> All links are greyed out. Symlinks have @ after them.

**Comment by rmwalk** [comment]
I understand, but those are symlinks. In fact, the blue directories are symlinks I just created from my dotfiles directory just to compare with alacritty.

**Comment by leovilok** [comment]
The "dim" (or "faint") character attribute is supported in st: http://git.suckless.org/st/file/x.c.html#l1413
Run this in st:
~~~sh
echo "\033[0mnormal \033[2mfaint"
~~~
In the output, the second word should be darker.

**Comment by rmwalk** [comment]
> Run this in st:
> 
> ```shell
> echo "\033[0mnormal \033[2mfaint"
> ```

It works when running in st, but in nnn it doesn't seem to work

**Comment by rmwalk** [comment]
Guess I've found out what was causing it. I had to add the `export TERM=xterm-256color` variable in my .zshenv. After doing it the colors are shown as they're supposed to be. Never needed to export it before and alacritty was behaving as expected so I guess I missed that.

**Comment by rmwalk** [comment]
nope, apparently it did not change permanently. I've ran some tests but exporting TERM is not the best choice, and even then it didn't work for the folders link colors, only for files.

**Comment by leovilok** [comment]
You have a bad `st` entry in your termio db.

**Comment by rmwalk** [comment]
> You have a bad `st` entry in your terminfo db.

How could I fix it?

**Comment by KlzXS** [comment]
> Some _random program_ complains that st is unknown/not recognised/unsupported/whatever!
>
> It means that st doesn’t have any terminfo entry on your system. Chances are
> you did not `make install`. If you just want to test it without installing it,
> you can manually run `tic -sx st.info`.

From `st` FAQ.

**Comment by leovilok** [comment]
Actually I have the same issue with my `st` even though I have the right terminfo.
You can run `infocmp st-256color | grep 'dim='`, this should output a line containing `dim=\E[2m`.

**Comment by rmwalk** [comment]
> Chances are
> you did not `make install`. If you just want to test it without installing it,
> you can manually run `tic -sx st.info`

Yep I saw that when I reinstalled it but I did use make install.

> You can run infocmp st-256color | grep 'dim=', this should output a line containing dim=\E[2m

It does:
` $ infocmp st-256color | grep 'dim='
        cvvis=\E[?25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,`

**Comment by KlzXS** [comment]
So we all did the same thing and the command above returns the same thing (the whole line) and yet only I can see the color properly?

**Comment by leovilok** [comment]
Yes

**Comment by rmwalk** [comment]
Yep

**Comment by KlzXS** [comment]
> Yes

Well that's lovely. Could it be `ncurses` misbehaving? Also my `$TERM` is `st-256color`. You mentioned `xterm-256color` above.

**Comment by rmwalk** [comment]
> mentioned `xterm-256color` above

I tried with st-256color but nothing changed, when I tried with xterm I could differ the links only on files, not directories. I don't even have xterm installed, not sure why I tried it though and why it change the colors of the file links.

**Comment by leovilok** [comment]
Yes, this seems like an issue in the st terminfo entry. In st (from master), `$TERM` is `st-256color`, and A_DIM doesn't work. Manually setting `$TERM` to `xterm-256color` makes it work.

**Comment by rmwalk** [comment]
@leovilok Do the colors of the symlinked direcotries change for you as well? For me it only changes the colors for the files.

**Comment by leovilok** [comment]
@rmwalk running with `TERM=xterm-256color nnn`, `A_DIM` works for files, dirs, and file details (in detail mode).

**Comment by rmwalk** [comment]
@leovilok oh yes, it does make it work!

**Comment by leovilok** [comment]
Anyways, it looks like it's an issue with the default st terminfo entry.

**Comment by KlzXS** [comment]
Seems like it. Closing the issue then.
