### ISSUE TITLE
fzopen macos support

### ISSUE THREAD

**Issue by rkulla** [jarun/nnn#669]
Currently typing `Return` doesn't open files from fzopen on Macs.  

A possible solution is to add a condition that checks if the output of `uname` is Darwin and then check for `case *regular*` instead of `*text*`   and use `open` instead of `xdg-open`.

Sorry I didn't have time to write a PR but just wanted to mention this as I just came across it.

**Comment by iressa** [comment]
I believe this is already the case, if I'm not mistaken. Have you tried using a debugger?

`static char * const utils[] = {
#ifdef __APPLE__
        "/usr/bin/open",`

**Comment by rkulla** [comment]
I was referring to the `fzopen` shell script, not the nnn binary.

**Comment by jarun** [comment]
I'm afraid you'll have to raise a PR for this. None of the devs are on macOS.

Also, plugins are indicative as they can be modified easily. We expect users to modify and use them according to their needs and environment.
