### ISSUE TITLE
[q] hook to execute a command on chdir

### ISSUE THREAD

**Issue by utrack** [jarun/nnn#671]
Hi, thank you for an awesome tool! I've just migrated to it from an array of custom shell scripts :)

It works great so far, but I've stumbled upon a problem: I'm using fzf+[fasd](https://github.com/clvv/fasd) to jump around directories quickly. [This](https://github.com/utrack/dotfiles/blob/master/nnn/.config/nnn/plugins/fzfasd) script works well with existing `fasd` database, however `nnn` doesn't fill it up with newly visited directories.

Is there any way to make `nnn` run a custom hook (`fasd -A (dir)`) each time I visit a directory?

**Comment by 0xACE** [comment]
Not sure about only on folder changes, but at least have a look at the `plugins/preview-*` scripts if this is that urgent to you...

**Comment by jarun** [comment]
> Is there any way to make nnn run a custom hook (fasd -A (dir)) each time I visit a directory?

You can read `NNN_FIFO`. It will have each hovered path name. Your script should track the change in the parent directory path and add it to fasd.

If you want your own FIFO, new directories are loaded in `dentfill()`. Look for the call to that function to write to your custom FIFO.
