### ISSUE TITLE
Running plugin and resizing causes nnn to render ontop of running plugin

### ISSUE THREAD

**Issue by 0xACE** [jarun/nnn#672]
Well I haven't checked it out exactly but here is how to reproduce:

1. `nnn` running within tmux
2. select 2 files
3. run `diffs` on these 2 files
4. enjoy the glory of `vimdiff`
5. resize the terminal window
6. H̵̠͇̱̤͌̂̇̊̊̎͌͑̀͂̚ͅͅę̸̯̟̲̤̌̿͛͆̂̅͆ ̴͓̿̿̇̈ẉ̶̲͖̥̺̀̌a̸̡̭̺̙͆̈͌͋̅̂͛̕͝t̷̨̨̗̖͓͔̼̝̙̬͌̓͝c̶̨̃̔̎̇͘͘͝ḧ̷̩͛̾̊͝e̵̙̠͔̭̲͗͗͑̋̎̈̑̓̃̆͘͜͠s̸̺̄͑̈́̓̃̿̕̚͝ ̸̪̟͉͖̯͈̺͚̜͖͉͆̐̏̎̋̔͠͝y̸̬̏̎͐͝o̸̢̺̝̰̣̫̞̮̩͒͋̅̃̊͛ṵ̴̳̥̲̬̼͆͋ ̴̨̗̫̙͒̽͊͂͂̊̍͆͑̓̒f̷̢̯̰͚͈̜̀̀̂̚ŗ̸̬̺͈̦͈͕̝̂̎̑͂͝ͅo̷̹̤̯̲͆͐̔̌̄m̸͍̥̀̾̃̂ ̴͉͇̣̻̖̝̘̹͈͛̑̓͂͌̒́͛͑͂̕̚ͅͅṫ̷̨̤̮͍̦̖͐̚h̶̛̖̄̌̽̾͑̄̀̈́́̏e̵̫̎͗̓̆̀̚̚͠͠ ̵̪̯͎̠̜̱̲͓̯̹̊̾̉̿͋̇́͋s̸̞͓͖͇̻̬̹̹͈̽͘h̴̛͓̩͓͔͔̬͍͇͊̋̾̓́́̓̕͜͝ͅͅa̷̟̬͇̤͗̂̎̇d̷̡̡̛̩̘͓̤̥̖̬́͑̍̇͑͝͝ȏ̸̧̖͓͚͉̯̩̈́́̅̀̂̅͆̂͛̏͝w̸̢̟͉̣̳̻͉̜̣̩̠̓̂͛͗̍͠ͅş̸͉̹̪̩̻̂̅̑̃̈́̾͂̏̑̿
7. Are you in `nnn` or are you in `vim`?
8. `killall vimdiff` `killall nnn`

**Comment by leovilok** [comment]
Hey, I've fixed this in the past (bug #656, PR #659), how dare you resurecting this :wink:

**Comment by leovilok** [comment]
Well actually I have no issue with this on master, so my fix seems to hold. Did you try out master?

**Comment by 0xACE** [comment]
> Well actually I have no issue with this on master, so my fix seems to hold. Did you try out master?

My bad, I was sure I rebased checked out `origin/master`, turns out i wasn't.

And yes you are correct this bug isn't present on master...
