### ISSUE TITLE
Maybe can use pv?

### ISSUE THREAD

**Issue by akimdi** [jarun/nnn#676]
like this 
```tar -czvf - . | pv -s $(du -sb | grep -o '[0-9]*') > out.tar```

https://www.ivarch.com/programs/pv.shtml

**Comment by KlzXS** [comment]
You can create a plugin which would execute a pipeline on your selection, current dir, or whatever else you'd like it to execute on.

You can read the wiki and use one of the existing plugins as an example for your custom one. Plugins are intended for such personalized use cases.

**Comment by leovilok** [comment]
And if you want to show builtin cp/mv progress, see [this wiki page](https://github.com/jarun/nnn/wiki/Advanced-use-cases#cp-mv-progress).

**Comment by akimdi** [comment]
> You can create a plugin which would execute a pipeline on your selection, current dir, or whatever else you'd like it to execute on.
> 
> You can read the wiki and use one of the existing plugins as an example for your custom one. Plugins are intended for such personalized use cases.

A plugin can be created but isn't it easier to click ```z```

**Comment by akimdi** [comment]
> And if you want to show builtin cp/mv progress, see [this wiki page](https://github.com/jarun/nnn/wiki/Advanced-use-cases#cp-mv-progress).

I am not an expert in information security, but using this patch is not safe, therefore it was not accepted in GNU Coreutils.
This has already been discussed earlier.

**Comment by jarun** [comment]
In that case please modify/write your own way. We do not have the bandwidth for this ATM. Also, we are not planning to use this technique.
