### ISSUE TITLE
[help] custom configuration for file opener without xdg-open

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [jarun/nnn#677]
Hi, I am using sway on 5.7.7-arch1-1, and I wish to find another way for file opening without xdg-open.

I found that for some basic configurations to set the default applications via [arch wiki environment variables](https://wiki.archlinux.org/index.php/Environment_variables#Default_programs).

However, for some files such as .pdf, it would be work very well.

Therefore, I would like to ask if any configurations can be done for nnn for file opening.

**Comment by 0xACE** [comment]
> However, for some files such as .pdf, it would be work very well.

I can't seem to find references to `*.pdf` in that article you linked, did you actually mean that `*.pdf` are not working well?

Essentially, if you don't have `xdg-open` in your environment, you will have to supplement a replacement.

`nnn` provides a `plugin` that you can download called `nuke`, apparently you can set it up to your liking all I know about nuke is it's probably documented in the wiki https://github.com/jarun/nnn/wiki .

Someone from the team usually answers within 24h. Can't help much more atm as I only have access to a cellphone, cheers

**Comment by Kabouik** [comment]
Not directly configured inside nnn, but I'm using handlr (installed with `cargo install handlr`, and I made a bash script in `/usr/local/bin/xdg-open` which just contains `handlr open "$@"`. It takes precedence over `/usr/bin/xdg-open`. Works well so far, and it also supports multiple applications for one file type, with a `rofi` selector.

**Comment by jarun** [comment]
There are plenty of options. You can also take a look at `nuke`, sample file handler: https://github.com/jarun/nnn/blob/master/plugins/nuke

**Comment by leovilok** [comment]
Stock `xdg-open` is a mess, that's why there are a ton a drop-in [replacements](https://wiki.archlinux.org/index.php/Default_applications#Resource_openers) (most can replace the `/usr/bin/xdg-open` executable, and thus get used by `nnn` without configuring anything).

**Comment by Inc0ns1st3nt** [comment]
[nuke](https://github.com/jarun/nnn/blob/master/plugins/nuke) seems like a great substitute for `xdg-ope#
