### ISSUE TITLE
Can't install plugins in termux

### ISSUE THREAD

**Issue by arnauldb** [jarun/nnn#680]
Hello,
I installed nnn using termux (pkg) on my phone. I am trying to install plugins using:
`curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh`
but received a message stating nnn is not installed.
What can be wrong?
Thank you.

**Comment by 0xACE** [comment]
from what i can tell it runs `which nnn` to see if `nnn` is installed.

what happens when you write `which nnn` in termux?

**Comment by arnauldb** [comment]
> what happens when you write which nnn in termux?

/data/data/com.termux/files/usr/bin/nnn

**Comment by arnauldb** [comment]
The problem was solved installing "debianutils", plugins successfully installed. Thank you.

**Comment by jarun** [comment]
Thanks for the confirmation.
