### ISSUE TITLE
"/dev/tty: Permission denied" when copying or moving

### ISSUE THREAD

**Issue by dkabus** [jarun/nnn#681]
#### Environment details

[x] Operating System: Arch Linux
[x] Desktop Environment: `dwm`
[x] Terminal Emulator: `st`
[x] Shell: `bash`
[x] Custom desktop opener (if applicable): default (`xdg-open`)
[x] Program options used: none
[x] Configuration options set: none
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Select any file with `Space`.
Enter another directory.
Paste with `p` or move with `v`.

Error message:
```
/path/to/myfile.ext: /dev/tty: Permission denied.
```

#### Possible reason

Running `tty` outputs `/dev/pts/1`, so `nnn` is running in a pseudoterminal.
Meanwhile, `nnn` tries to read from `/dev/tty`.
The permissions are:
```
0 crw--w---- 1 root tty 5, 0 Jul 17 20:20 /dev/tty
0 crw--w---- 1 myusername tty 136, 1 Jul 17 20:32 /dev/pts/1
```

#### Bugfix
A solution would be to replace all calls of `/dev/tty` by whatever device is output by `tty`.
Or simply:
```
diff --git a/src/nnn.c b/src/nnn.c
index c5ab000..527f5ca 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -661,7 +661,7 @@ static const char * const toks[] = {
 static const char * const patterns[] = {
        "sed -i 's|^\\(\\(.*/\\)\\(.*\\)$\\)|#\\1\\n\\3|' %s",
        "sed 's|^\\([^#/][^/]\\?.*\\)$|%s/\\1|;s|^#\\(/.*\\)$|\\1|' "
-               "%s | tr '\\n' '\\0' | xargs -0 -n2 sh -c '%s \"$0\" \"$@\" < /dev/tty'",
+               "%s | tr '\\n' '\\0' | xargs -0 -n2 sh -c '%s \"$0\" \"$@\"'",
        "\\.(bz|bz2|gz|tar|taz|tbz|tbz2|tgz|z|zip)$",
        "sed -i 's|^%s\\(.*\\)$|%s\\1|' %s",
 };

 static void opstr(char *buf, char *op)
 {
-       snprintf(buf, CMD_LEN_MAX, "xargs -0 sh -c '%s \"$0\" \"$@\" . < /dev/tty' < %s",
+       snprintf(buf, CMD_LEN_MAX, "xargs -0 sh -c '%s \"$0\" \"$@\" .' < %s",
                 op, selpath);
 }

@@ -1820,7 +1820,7 @@ static bool rmmulstr(char *buf)
                if (!r)
                        return FALSE;

-               snprintf(buf, CMD_LEN_MAX, "xargs -0 sh -c 'rm -%cr \"$0\" \"$@\" < /dev/tty' < %s",
+               snprintf(buf, CMD_LEN_MAX, "xargs -0 sh -c 'rm -%cr \"$0\" \"$@\"' < %s",
                         r, selpath);
        }
```

**Comment by KlzXS** [comment]
The redirect is needed for the shell to stay interactive. I never had problems with 'permission denied' even when running inside tmux.

**Comment by KlzXS** [comment]
From https://linux.die.net/man/4/tty

> The file /dev/tty is a character file with major number 5 and minor number 0, usually of mode 0666 and owner.group root.tty. It is a synonym for the controlling terminal of a process, if any.

**Comment by dkabus** [comment]
I figured it out. There was an issue with my `getty` setup...
Everything works perfectly in `nnn` now. Thanks!
