### ISSUE TITLE
Is there really no way to delete a folder with a lot of files in few key presses?

### ISSUE THREAD

**Issue by DoTheEvo** [jarun/nnn#683]
I spent some time googling and reading, but there seems to be no way unless I am going in to reading about some patches...

I just want to make sure, if I am using nnn correctly and it is expected of me to exit my file manafer to delete directories in console or to get asked about descending in to directory on every single file in the directory.

That is how nnn is purposely designed.

**Comment by KlzXS** [comment]
The right way to remove a directory, empty or full, is to select it with `space`, press `x`, then `s` which will delete it along with the redt of your selection.

Or you could hover over it and press `x` then `c` to remove just it.

I am not sure what question you are refering to.

**Comment by DoTheEvo** [comment]
Ok, found the issue as I was writing out all the steps I needed to do during delete

for me it is 

- `space` to select directory
- `x` to start the delete process
- `s` to apply it for selected
- `Enter` because I get question: `rm -rf 1 file(s) [Esc cancels]`

well that was wrong, it wanted 'y' to delete it, enter throws me in to console and asks me about every damn file

**Comment by KlzXS** [comment]
Well that's a feature for extra carefull people :)

**Comment by DoTheEvo** [comment]
well, enter might not want to do that thing but yeah,
`y` for confirmation is fine
