### ISSUE TITLE
indicator to show whether viewing hidden files or not

### ISSUE THREAD

**Issue by unknowledgeable** [jarun/nnn#685]
I'm finding myself having to go back and forth between directories to see whether I'm showing hidden files or not. It's a very minor issue but what do you think about having some sort of indicator that shows whether they're being viewed or not?

Maybe just a `.` or `[.]` somewhere along the bottom that appears and disappears?

**Comment by jarun** [comment]
I chose to use `H` as dot may be difficult to see. Please confirm the patch works as intended.

**Comment by unknowledgeable** [comment]
Apologies but I think that's a bit beyond me! Thanks though, loving nnn!
