### ISSUE TITLE
new way to selecting things

### ISSUE THREAD

**Issue by Miquoyi** [jarun/nnn#687]
nnn could have a different way of selecting things, instead of press space and it will flip selection of the current thing and go to the next file and wait there or keep doing it till the end, space could select the current thing and don't move if you just tap at it, or select it and stay on the same item(but without blinking as it happens when you are at the last one) and be ready to move based on the keypress, selecting the things in its path, could be with the "j" and "k" keys, or going to the top/bottom with g/G, or even with a search(idk about this one), or remember the first one and apply to everyone (being select or unselect). there are a lot of ways.

And the code could have a option to unselect all like it has for selecting all "a"

**Comment by KlzXS** [comment]
You can select a range of file by pressing `m` moving to the end of range (either up or down the file list) and pressing `m` again. If you press `m` twice on the same file it will clear the seleoction.

If you want the cursor not to move after selecting it should be a simple patch. I'm on mobile so I don't have the code handy to paste it here.

**Comment by Miquoyi** [comment]
Oh dude thanks for the reply, I probably just rushed through the help page and pressed "m", nothing happened and thought that it was an useless thing or a broken shortcut, I'm kinda new to this part of linux of having more cli things than gui(just went from plasma to dwm today), gonna read with more cautiousness next time :)
