### ISSUE TITLE
"cd on quit" not working using (n)vim's nnn plugin

### ISSUE THREAD

**Issue by mroavi** [jarun/nnn#689]
**Is your feature request related to a problem? Please describe.**

If  `NNN_TMPFILE` is set, then the file *~/.config/nnn/.lastd* should be written on exit as described in jarun/nnn#350 (comment) and implemented in jarun/nnn@d1d491c. This is not working when using the (n)vim's nnn plugin.

I browsed through the code and this looks to be a design decision:
```c
...
			/* CD on Quit */
			/* In vim picker mode, clear selection and exit */
			/* Picker mode: reset buffer or clear file */
			if (sel == SEL_QUITCD || getenv("NNN_TMPFILE"))
				g_state.picker ? selbufpos = 0 : write_lastdir(path);
			return sel == SEL_QUITFAIL ? EXIT_FAILURE : EXIT_SUCCESS;

...
```

**Describe the solution you'd like**

I want the *quit on cd* functionality while using vim's nnn plugin. To implement this, the *~/.config/nnn/.lastd* needs to be written by *nnn* also when exiting the vim plugin.

**Comment by jarun** [comment]
Yes, it is blocked by design. How does it help practically? You are opening `nnn` within `vim`. Even if you have cd on quit, you will ot exit vim when you quit. Can you please explain your use-case?

**Comment by mroavi** [comment]
Vim provides built-in commands to print or change the *current working directory* without needing to exit vim. For example, you can run `:cd ~` to change to your home directory or `:pwd` to print the current working directory. The *nnn* (n)vim plugin could serve as a much faster alternative to change the `current working directory` without needing to exit vim. In my case, I want to take advantage of the `fzz` plugin to quickly change directories using `nnn` within vim. Somebody else raised an issue with the same interest: https://github.com/mcchrish/nnn.vim/issues/57.

I already have a working version. I had to modify both your `nnn` source code and the `nnn` vim plugin. @mcchrish agrees that this would be a neat feature to add (https://github.com/mcchrish/nnn.vim/issues/57).

**Comment by jarun** [comment]
Thanks a lot for clarifying! Please raise a PR.
