### ISSUE TITLE
Show output of archive feature

### ISSUE THREAD

**Issue by sirovstrukelj** [jarun/nnn#691]
Hi, I was archiving some data and when I deleted the folder I actually saw that the folder was not archived properly. It was 0 bytes big and I was not sure why. Then after some fiddling, I manage to see the stdout of nnn (the output of the archiver command) and saw it exited with a nonzero exit code. 

Now I cant reproduce it anymore, but I was more wondering how can one see the output of the archive command because when it finishes it switches back to the nnn file manager right away without seeing if there were any errors at the end. I checked the wiki but did not see how to display the buffer.

**Comment by jarun** [comment]
Which utility are you using to archive?

**Comment by jarun** [comment]
Sorry, you mentioned that you could see the output. Yes, the output is not purged. You can see the output later by pressing `!` or `^]`.

I am thinking we can also add some other safeguards:

- check the exit status from th utility and fail if it is non-zero
- we check if output file is accessible or not, we can instead check if output file is zero bytes

**Comment by jarun** [comment]
After weighing the pros and cons, it appears showing the output is the best option indeed. Please confirm if the changes work as expected.
