### ISSUE TITLE
cbcp plugin throws an error

### ISSUE THREAD

**Issue by lifeBalance** [jarun/nnn#695]
#465 ## Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Linux
[bspwm] Desktop Environment:
[x] Terminal Emulator: Alacritty
[x] Shell: Bash
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
I installed the plugins as described here: https://github.com/jarun/nnn/tree/master/plugins#installing-plugins

* Added this line to my .bashrc:
```
export NNN_PLUG='k:cbcp'
```
* Added the `-x` option to the nnn call in my `quitcd.bash_zsh` script
When I launch `nnn` (n + Enter) I try to copy with ``; + k`` and when I quit, I get the error:
```
$HOME/.config/nnn/plugins/cbcp: line 31: $HOME/.config/nnn/.selection: No such file or directory
```
Nothing gets copied to the clipboard. I have xclip on my system.

**Comment by KlzXS** [comment]
You might be misunderstanding what the plugin does. It doesn't copy the hovered path to clipboard, it copies the selection.
You need to first select some files (with space) and then you can copy it to clipboard.

**Comment by lifeBalance** [comment]
Oooh, that explains a lot. Thanks.
