### ISSUE TITLE
Instructions on how to set up cp progress are unclear

### ISSUE THREAD

**Issue by wAuner** [jarun/nnn#699]
I want to set tup the cp and mv progress and I've followed all the instructions. It works when I invoke it manually but currently not when I copy something with nnn.
What do I need to do to get it working in nnn? The wiki just says `Use the relevant program option to show the progress of the operations.`
What is the relevant program option? Would be great if the wiki could be a bit more detailed here.
I've copied the files as `cpg/mvg` and also created an alias for both like `alias cp=cpg -g`.

**Comment by KlzXS** [comment]
From the [wiki](https://github.com/jarun/nnn/wiki/Usage#program-options):

> -r use advcpmv patched cp, mv

**Comment by wAuner** [comment]
Thanks. Would be nice to mention it directly under that section or provide a link.
