### ISSUE TITLE
Set up Homebrew tap

### ISSUE THREAD

**Issue by zmwangx** [jarun/nnn#7]
To set up a [Homebrew tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md), create a repository at jarun/homebrew-nnn, place the single file `nnn.rb` in it:

```rb
class Nnn < Formula
  desc "Free, fast, friendly file browser"
  homepage "https://github.com/jarun/nnn"
  url "https://github.com/jarun/nnn/archive/v1.0.tar.gz"
  sha256 "dd33f1001a87a427f10b6468db7dcba0bdc19643f121dbf6bb8655d5f2d3bac5"

  def install
    # Remove when Makefile is fixed
    inreplace "Makefile", "$(PREFIX)/man", "$(PREFIX)/share/man"
    system "make", "install", "PREFIX=#{prefix}"
  end

  test do
    touch "foobar"
    # Testing this curses app requires a pty
    require "pty"
    PTY.spawn(bin/"nnn") do |r, w, pid|
      w.write "q"
      assert_match "foobar", r.read
    end
  end
end

```

add an optional README if you want to, but Homebrew/Linuxbrew users who just do

```
brew install jarun/nnn
```

won't see the README.

**Comment by zmwangx** [comment]
By the way, currently the man page is installed into `$(PREFIX)/man`, when `$(PREFIX)/share/man` is more appropriate.

**Comment by jarun** [comment]
I can still remove the tag and make the changes. We haven't posted it anywhere yet.

**Comment by zmwangx** [comment]
Sure.

**Comment by jarun** [comment]
I'll add the instruction to the README for nnn.

**Comment by jarun** [comment]
PS https://github.com/jarun/homebrew-nnn

**Comment by zmwangx** [comment]
Cool. Just remember to update the checksum and remove the `inreplace` if you ever decide to retag.

**Comment by jarun** [comment]
All done at https://github.com/jarun/nnn/commit/85d7f2762e9fa1bf927955be1dca03e0a3b91aff.

**Comment by zmwangx** [comment]
LGTM.
