### ISSUE TITLE
Allow background copy and moving

### ISSUE THREAD

**Issue by gianfrappe** [jarun/nnn#701]
**Is your feature request related to a problem? Please describe.**

I would like copy and moving to happen in the background, without the terminal haven't to wait for it to finish.
I tried `advcp` with [this](https://aur.archlinux.org/packages/advcp/) package and using the `-rx` options.
I now view the progress bar, but the copy still happens in the foreground and I don't receive any notification on completion.
In my current setup, using `notify-send` from the terminal show a notification as it should be, so I'm not sure why it does not work in `nnn`

**Describe the solution you'd like**

Just enabling background copy/move

**Describe alternatives you've considered**

Spawn a new terminal instance with show the progress bar, while the original one still run

**Comment by jarun** [comment]
> I don't receive any notification on completion

Use the program option `-x` (see Wiki for more details). If `-x` is not working, it's probably a local issue. Please fix that.

> Just enabling background copy/move

No, it's not that simple to manage background processes. users may quit in the meantime as well. No plans to support this.
