### ISSUE TITLE
(help) please!

### ISSUE THREAD

**Issue by 5c0tt-b0t** [jarun/nnn#702]
hi, thank you do much for best file manager in the world!!
I want to download and try plugins, how?
I have downloaded all the plugins first, then I read "plugins" but no explanation there, should these go In my bashrc like other variables or a in: ~/.config/nnn.
Thank you so much for you time & efforts!
Im sure your busy enough without idiots like me! :)

**Comment by jarun** [comment]
Please follow the instructions here: https://github.com/jarun/nnn/tree/master/plugins#installing-plugins

**Comment by jarun** [comment]
and here: https://github.com/jarun/nnn/tree/master/plugins#invoking-a-plugin
