### ISSUE TITLE
NNN opens empty files by their relative path

### ISSUE THREAD

**Issue by rachied** [jarun/nnn#704]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: MacOS
[x] Desktop Environment:Aqua
[x] Terminal Emulator: Kitty
[x] Shell: ZSH
[x] Program options used: -e
[x] Configuration options set: ewrap / custom script
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I've been trying to get nnn to open text files by opening them in vim in a new terminal pane. Kitty terminal has a cli you can use to pass scripts/jobs to. I can do that with the following command:

```kitty @ launch vim [file]```

I put the above in a script called 'kvim'
When setting $VISUAL to 'kvim', all is well within nnn and it opens text files nicely in a split pane. However, when I create a brand new (and thus empty) file within nnn and I press 'e' to edit, it invokes kvim with only a relative path. This results in vim creating another new file with this name, this time in my Home directory, or whatever most recent working directory Kitty found.

I have tested this by replacing kvim with something that logs the output

```#!/usr/bin/env sh
echo "vim \"$*\"" >> ~/dev/scriptlog
```

And then I tried a normal text file, and then a newly created one. It gave a relative path for the second one.

```
vim "/Users/me/dev/tex-documents/reddit/notes.log"
vim "yabber"
```

**Comment by jarun** [comment]
Please confirm the patch works as expected.

**Comment by rachied** [comment]
It does indeed work.

**Comment by jarun** [comment]
Thanks for the confirmation!
