### ISSUE TITLE
(Feature Request) Command to set default text editor / split screen

### ISSUE THREAD

**Issue by danrobi11** [jarun/nnn#706]
Hello
Just learned about nnn and I like it, its a great file manager.
Im used to micro and tilde text editor. Would be nice to have a quick command to set default text editor. 
How can I set default to my text editor?
Also I see a screenshot with split screen but I cant find any command, is there any?
Thank you much for nnn

**Comment by jarun** [comment]
> Im used to micro and tilde text editor. Would be nice to have a quick command to set default text editor.

Set `$EDITOR` to any editor of your choice. You can have a wrapper to `nnn` that sets `$EDITOR` instead of changing it in the rc file.

> Also I see a screenshot with split screen but I cant find any command, is there any?

The split screen screenshot is using dvtm. You can use tmux/kitty/tilix/terminator too. BTW, did you try pressing `TAB` in nnn? I don't think you'll need a split screen when you get used to that.

**Comment by danrobi11** [comment]
Ok fair enough, tab does the job.

However, im clueless when comes to this: 'Set $EDITOR to any editor of your choice. You can have a wrapper to nnn that sets $EDITOR instead of changing it in the rc file'

Also, I cant find any config file, thats unfortunate, everything else pretty straightforward with nnn. Deal breaker for me :(

**Comment by jarun** [comment]
A function like:

```
n ()
{
    export EDITOR=vim
    export PAGER='less -Ri'
    export NNN_COLORS='#5251d0be;2341'`

    nnn -cdEFnQrux
}
```

More examples [here](https://github.com/jarun/nnn/tree/master/misc/quitcd).

> I cant find any config file

Your shells rc file is your config file. `nnn` has too  few configs to be set to warrant a config file. And a presistent session file works as a config file in several cases too!

**Comment by danrobi11** [comment]
Thank you for the support. I've tried the example you gave me above and that makes open nnn automatically everytime I open my terminal. I know nothing about bash scripting and I've already took enough of your time. 
I do suggest tho a command in '?' that would prompt for users to type the name of their editor of choice or to add the path e.g. /usr/bin/micro  
This is the only not user-friendly thing with https://github.com/jarun/nnn/issues/629#issuecomment-675888958 
Other than these nnn is very simple to use.
Thanks again. I'll keep an eye on new release ;)

**Comment by jarun** [comment]
> I've tried the example you gave me above and that makes open nnn automatically everytime

You have to place it as a function. But anyway, you can also copy the following lines in a file and call it `n` and invoke it:

```
#!/usr/bin/env sh

export EDITOR=vim
export PAGER='less -Ri'
export NNN_COLORS='#5251d0be;2341'`

nnn -cdEFnQrux
```

Then:

    chmod +x n

> I do suggest tho a command in '?' that would prompt for users to type the name of their editor of choice or to add the path e.g. /usr/bin/micro

I can't add a redundant feature because you aren't able to export `$EDITOR`.

Please learn more about using the cmdline and environment variables. It's not that difficult and there are many good tutorials.

**Comment by danrobi11** [comment]
Well, I had no clue, sry for the trouble. Thanks again.
Im gona leave this here in case someone else would need it.
https://askubuntu.com/questions/432524/how-do-i-find-and-set-my-editor-environment-variable
