### ISSUE TITLE
Not showing colors when xterm-256color is set

### ISSUE THREAD

**Issue by asgeo1** [jarun/nnn#709]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: OSX 10.15.6
[ ] Desktop Environment:
[x] Terminal Emulator: Kitty 0.18.3
[x] Shell: Fish 3.1.2
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I'm not getting any colors when using `nnn` on my system when `$TERM` is set to either `xterm-256color` or `screen-256color`. Which is strange, because other programs like `ls`, `git` etc all show colors fine.

When I set `$TERM` to `xterm-kitty`, colors *do* work with `nnn`. Which is great! That mostly fixes it for me.

However, some programs and tools like to set their own `$TERM` value to `xterm-256color` or `screen-256color` (e.g. Neovim, `tmux` etc), and so colors will not work when using `nnn` in those cases.

And I guess, I just don't get why the colors wouldn't work with `xterm-256color`, since I assume many people are using that without issue.    It's just odd that with that setting, other programs can display colors fine, but it's just `nnn` that has the problem.

I have tried other terminals, such as iTerm2 and they have the same issue, but I don't have any fallback because `xterm-kitty` obviously only works with Kitty.

 Is my `xterm-256color` borked, or is this an issue with nnn ?   Any ideas?

Thanks!

**Comment by 0xACE** [comment]
I ran this on `master`:
```
make
TERM=xterm-256color ./nnn
```
And it works.

I'm guessing your termcap is not installed correctly.

Hopefully someone can help you with your environment, I'm going to bed, good night.

**Comment by asgeo1** [comment]
`master` does not work for me. Something must be screwed up with it. I guess I just don't understand why `nnn` would be the only program having trouble displaying colors though.

**Comment by jarun** [comment]
We don't read `xterm-256color`. At least my setup works without it. I am not sure if we should read it.

Please ensure you set `NNN_COLORS` correctly and are on v3.4 or master.

**Comment by jarun** [comment]
I do see an issue that [setting 256 colors for tmux](https://unix.stackexchange.com/questions/1045/getting-256-colors-to-work-in-tmux) and opening nnn in tmux doesn't show the colors.

**Comment by jarun** [comment]
However, that's within xterm. I see no issues in opening nnn in the terminal.

**Comment by jarun** [comment]
More info from tmux angle:

```
1 ~/GitHub/nnn$ TERM=xterm-256color tmux
2 ~/GitHub/nnn$ tput colors
8
```

**Comment by jarun** [comment]
I believe that's a local issue on my setup as I custom-compiled tmux.

**Comment by 0xACE** [comment]
We use `attron()` to set colors, maybe `nnn` is affected because of your version of `*curses`

**Comment by jarun** [comment]
Possible. I didn't really dive much into it as I have a custom tmux installed (which I never use).

**Comment by asgeo1** [comment]
Yes, definitely using `3.4` and have `set -x NNN_COLORS '4231'` in my `config.fish`

I use tmux too, and it tends to overwrite `$TERM` with its own value that breaks colors in a number of programs I find.

Usually `set -g default-terminal "screen-256color"` in `.tmux.conf` is what I set, and that works to give colors to all my programs (except `nnn`).  So I've been using `set -g default-terminal "xterm-kitty"` instead, which seems to be the only value that will work for `nnn`.

I tried following the instructions on [here](https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95) to rebuild my `xterm-256color` terminfo, but it didn't seem to make any difference.

I have `ncurses` 5.7, not sure if that is good or bad.

```
tic -V
ncurses 5.7.20081102
```

**Comment by jarun** [comment]
Try ncurses 6+.

**Comment by asgeo1** [comment]
Hmm, seems quite difficult to use a different version of ncurses after reading discussion on it [here](https://github.com/tmux/tmux/issues/1584#issuecomment-466378606).

It seems I do have homebrew ncurses 6.2 installed already, but it's not used by the system, just for other homebrew packages to build against. And 6.2 would clash with the older OSX version of `tic` installed, which needs to match.

Seems a bit of a rabbit hole. I don't want to waste anyone's time, I'm happy enough to use `xterm-kitty` and not worry about why `xterm-256color` isn't working.

Thanks for your help :-)

**Comment by jarun** [comment]
> and not worry about why xterm-256color isn't working.

Good thinking! It's not worth the time.
