### ISSUE TITLE
there is no place for subpixel in image

### ISSUE THREAD

**Issue by 532910** [jarun/nnn#710]
The current screenshots looks so rainbow-awful, so I even don't thought to try it.

**Comment by jarun** [comment]
Then don't enable it. We wouldn't hold you accountable for that. ;)

**Comment by 532910** [comment]
Have you seen your screenshot on screens with other pixel order? Have you tried to rotate your own?

**Comment by 0xACE** [comment]
> Then don't enable colors and icons. We wouldn't hold you accountable for that. ;)

He is referring how the font is rendered in the screenshots. I don't know why he is expressing himself this way though... This is sort of related to the previous discussion where I gave examples from `/r/unixporn`

![cap](https://user-images.githubusercontent.com/1482942/90760930-24679880-e2d2-11ea-9df7-2a55cd74caff.png)
`picture on repo` vs `screenshot of asciinema`

close up on example of issue (4x zoom):
![cap](https://user-images.githubusercontent.com/1482942/90762255-45c98400-e2d4-11ea-9fad-81f50eb83037.png)


I don't like messing with fonts in linux, but I remember it was a pain to get the rendering working better than default... Even after all that messing around it still doesn't work perfectly...

**Comment by 532910** [comment]
What way exactly? This is just a user experience, and not my own. Screenshots are intended to make the first impression, this one says "just don't even think about installing me".

**Comment by jarun** [comment]
Does the image in the repo show properly? It should because it is a PNG.

We can remove the link to the asciicast.

**Comment by jarun** [comment]
Speaking of the images on the readme render correctly on Linux, Windows and Android.

**Comment by jarun** [comment]
If you have issues with the fonts in the asciicast, please talk to the asciiinema team.

Also, there is a note below the asciicast about the icons.

**Comment by 532910** [comment]
> Does the image in the repo show properly?

NO!

> It should because it is a PNG.

It must not.

Do you know what subpixel is? Do you know, that different monitors has different subpixel order? Have you even thought that subpixel order will differ for the same monitor on rotation?

**Comment by 532910** [comment]
Asciinema rendering looks fine.

The only two issues with asciinema i see is:
1. icons are shown as squares
2. keystrokes are not displayed

**Comment by jarun** [comment]
> Go practice your attitude and sarcasm in your own projects.

I see you don't have any other than some forks. Thought so. In that case.. charity begins at home.

**Comment by jarun** [comment]
> so I even don't thought to try it.

Your loss. Not our problem.

**Comment by 0xACE** [comment]
> What way exactly?

The general population aren't aware of the fault you are pointing out, thus this thread is ambiguous. The presentation from you is also condescending. Why would you notify 109 people like this?

An internal conversation has been had regarding this topic. Among the developers in the `nnn` team I guess at least three of us understand what you are referring to. Coverage of this topic from the dev team has been lacking for various reasons. I have plans to mitigate this, but this will be done after I fix more important things.

If you take such pride in spazzing out over screenshots of open source terminal programs: How about providing a better screenshot? That is if you have worked out font rendering on your machines...

The only thing stopping you from providing better documentation is you. Pull requests are welcome.

If your only concern was that we should improve the presentation, be aware that your proposal has been noted and will be dealt in the future.

Have a good day :D
