### ISSUE TITLE
Docs unclear on 2-digit hex codes

### ISSUE THREAD

**Issue by snide** [jarun/nnn#716]
Sorry for the likely basic question. I'm reading the docs around configuration and can't for the life of me figure out how a 2-digit hex code works.

[From the configuration docs](https://github.com/jarun/nnn/wiki/Usage#configuration)

> Specify file-specific colors with xterm 256 color codes (2 hex symbols per color)

Which links to [this page](https://jonasjacek.github.io/colors/). I don't see any two-color hexes listed, and despite some searching can't figure out how to generate them. Random codes I put it do change the configuration, but I'm still unclear where I'd get a 2 digit hex from (usually I see 3 or 6 digits, and the single digit terminal schema used for `NNN_COLORS` is different).

**Comment by jarun** [comment]
Updated the docs to use _numbers_ instead of _codes_. Use the hex value of the Xterm color numbers (shown in decimal in the external link).

**Comment by protrolium** [comment]
I was having a similar conundrum as @snide, I don't see any decimal in the external link that you mentioned, or any further way to determine the 2 hex symbol based off of Xterm color number. Using `00` to overwrite for now.

**Comment by 0xACE** [comment]
![cap](https://user-images.githubusercontent.com/1482942/93023779-e6b01400-f5e0-11ea-9bfd-acc314067919.png)

**Comment by jarun** [comment]
Thanks @0xACE! I will link it from the config page.

**Comment by jarun** [comment]
Wow! You already took care of it! Thank you @0xACE!

**Comment by protrolium** [comment]
@0xACE bless you!
