### ISSUE TITLE
Colors are weird when TERM is set to alacritty

### ISSUE THREAD

**Issue by billop** [jarun/nnn#720]
### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: NixOS 20.03
[x] Desktop Environment: Sway
[x] Terminal Emulator: Alacritty
[x] Shell: Fish
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[x] Configuration options set: `set -x NNN_COLORS '4215'`
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Run nnn v3.4 on alacritty, colors will not match the terminal colors.

Run with `env TERM=xterm nnn` and colors will be back to normal.

Noticed this issue after upgrading nnn today.

**Comment by jarun** [comment]
v3.4 has support for file-specific colors which work fine on several terminal emulators. If this is specific to alacritty, I am not sure if we will be able to help you. Probably contact the alacritty team and if there's any generic change that's required in `nnn`, we'll fix that.

The other option for you would be to fallback to the older colorscheme using option `-C`.

**Comment by billop** [comment]
Thanks for pointing out the `-C` option, will be using that from now on.

**Comment by jarun** [comment]
No problem!

**Comment by pricheal** [comment]
Just want to point out, I use the base16-shell scripts to set my shells ANSI colors so I also use the -C flag now to make sure that works. Thanks for including the -C flag

**Comment by jarun** [comment]
Just for the record, I don't see any such issues with the newer colorscheme (`TERM=xterm-256color`).

![](https://i.imgur.com/qT3wnBR.jpg)
