### ISSUE TITLE
preview-tabbed

### ISSUE THREAD

**Issue by cdarkly** [jarun/nnn#723]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Debian Testing
[x] Desktop Environment: Spectrwm
[x] Terminal Emulator: Xterm
[x] Shell: Bash
[ ] Custom desktop opener (if applicable):
[x ] Program options used: ca
[ ] Configuration options set:
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

This issue is related to using the "preview-tabbed" plugin. All dependencies are installed and everything appears to work without any problems. However, the problem becomes apparent after quitting "nnn" and viewing what processes remain active.

To reproduce this:

1. Start nnn
2. Lanuch 'preview-tabbed' plugin
3. Press q to quit nnn
4. Run 'ps aux' at the command prompt.

You will then see that some processes generated by 'preview-tabbed' are still running and did not exit or get killed properly.

1. 'nnn' itself is gone
2. 'tabbed' is gone
3. BUT, last "VIEWERPID" is still running.

The fix for this could be to add a second kill command for "VIEWERPID" outside of the while loop.

while read -r FILE ; do
   ....
done
kill "$VIEWERPID"
kill "$TABBEDPID"

Also, is there any way to stop the preview-tabbed plugin with CTRL-C without quitting nnn and have all running child processes terminated?

**Comment by jarun** [comment]
Closed at #725.
