### ISSUE TITLE
Dependencies libncursesw5 ERROR

### ISSUE THREAD

**Issue by exa18** [jarun/nnn#724]
If it looks like a local environment issue, please try to debug yourself. Debugging local setup issues is not our top priority.

If you are looking for a new feature or program option, ensure you have the correct version with the feature installed. Refer to the release notes to confirm.

Before opening an issue, please try to reproduce on latest master. The bug you noticed might have already been fixed.

Useful links:

- compile `nnn` from source - https://github.com/jarun/nnn#from-source
- debugging `nnn` - https://github.com/jarun/nnn/wiki/debugging-nnn

If the issue can be reproduced on master, log it.

Please provide the environment details. **If that's missing, the issue will be closed without any cited reason.**

If we need more information and there is no communication from the bug reporter within 7 days from the date of request, we will close the issue. If you have relevant information, resume discussion any time.

--- PLEASE DELETE THIS LINE AND EVERYTHING ABOVE ---

#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Debian 10
[ ] Desktop Environment: -
[x] Terminal Emulator: ssh
[x] Shell: bash
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[x] Configuration options set: OMV 5.x
[x] Issue exists on `nnn` master : latest deb

#### Exact steps to reproduce the issue
Try: sudo dpkg -i nnn*
then -> sudo apt install libncursesw5

I got allready installed version 6 of this lib

**Comment by jarun** [comment]
@szlin please take a look.

**Comment by jarun** [comment]
OK, now I saw you are installing the auto-generated package.

Which one is installed by default on Debian 10: ncursesw v5 or v6?

**Comment by szlin** [comment]
// I didn't receive the notification email somehow.

Hi @jarun 
The version of libncurses-dev in Debian 10 is v6 [1].

[1] https://packages.debian.org/buster/libncurses-dev

**Comment by jarun** [comment]
Thanks Lin! I updated the auto package generation deps.

**Comment by szlin** [comment]
@jarun I see. Feel free to ping me via email or private message in case this awkward issue happened again :-)

**Comment by jarun** [comment]
Sure Lin!
