### ISSUE TITLE
Support for .hidden file

### ISSUE THREAD

**Issue by ndalliard** [jarun/nnn#726]
In [GNOME's file manager](https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory#GNOME) filenames listed in a `.hidden` file are viewed as dotfiles.

In my case the Tor browser creates a folder in my home directory and I am unable to set another path. Would be great, if I could add the folder into a `.hidden` file and it won't be displayed by default.

**Comment by jarun** [comment]
I am not sure if there is a standard that says files in .hidden should be hidden. Also if Tor, which is all about anonymity, is creating a directory visible to everyone, please raise an issue on that project.

Finally, nnn keeps configs minimal and there's no config file as we do not want to read a file from disk at every startup for performance and unnecessary disk IO. Reading a file on  entering a dir and matching against each file is out of question.
