### ISSUE TITLE
Move and rename fails with macOS built-in sed

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jarun/nnn#728]
First, thanks for making such a great tool. It's completely replaced vifm for me (especially thanks to the excellent Vim integration) and it works well on macOS.

I did run into a problem using select + `w` to move / copy and rename files on macOS. The problem appears to be due to the built-in version of `sed` that macOS uses by default. Installing `gnu-sed` via homebrew and aliasing it to `sed` solves the problem completely. 

#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: macOS
[x] Desktop Environment: n/a
[x] Terminal Emulator: Alacritty (also tested on Terminal.app)
[x] Shell: zsh (also tested on bash)
[x] Custom desktop opener (if applicable): n/a
[x] Program options used: none
[x] Configuration options set: none
[x] Issue exists on `nnn` master: yes

#### Exact steps to reproduce the issue
1. Install nnn via homebrew (`brew install nnn --HEAD`)
2. Create a new file (`touch testfile.txt`) or use an existing file
3. Start nnn with `nnn` and select any file / directory with `space`
4. Trigger the `w` command and choose `(c)p` or `(m)v`
5. Edit filename / directory in $EDITOR (I tested `vim`, `nvim`, and `nano`) and save

nnn will show a `failed!` mesage and doesn't do anything further with the selected file. After exiting, my command line shows the following message:

`sed: 1: "/tmp/.nnneEWjIN": invalid command code .` 

As mentioned, installing and configuring my shell to use `gnu-sed` solves the issue completely. I'm not familiar enough with `sed` to debug this issue myself, but I think it'd be really helpful for other macOS users if they knew `gnu-sed` is required for this feature to work (or if the issue itself could be fixed).

**Comment by jarun** [comment]
We would like to use the built-in sed command.
@KlzXS can you please take a look?

**Comment by KlzXS** [comment]
I would very much like to, but I don't have macOS. I think I was careful not to include anything not in POSIX.

I'll check everything once more.

**Comment by jarun** [comment]
@KlzXS use https://github.com/fastai/fastmac/ to access a macOS shell. It works, I confirmed.

To install `nnn`, run brew install `nnn`.

**Comment by KlzXS** [comment]
The problem with built-in `sed` is that `-i` option takes an additional argument (an extension for the backup file), which gnu's sed can't take. We can work around that.

The bigger problem is that it doesn't work nice with newlines. In `P_CPMVFMT` we need to insert a newline and there doesn't seem to be a nice, non-shell-dependent way of doing it. I tried [ANSI-C Quoting](https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html) because that should work, but it just gave me more errors.

I say we update the dependencies with gnu sed.

**Comment by jarun** [comment]
Sure! No need to work with crippled sw.

**Comment by jarun** [comment]
@jose-elias-alvarez can you please update our Homebrew recipe to add this dependency?

**Comment by jarun** [comment]
The formula file is here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/nnn.rb

**Comment by jose-elias-alvarez** [comment]
Thanks for the attention on this. 

I updated and tested the formula locally, but Homebrew doesn't automatically symlink `gnu-sed` to `sed` on install. It adds it to $PATH as `gsed` to avoid conflicts and leaves the option to override built-in `sed` to the user, which seems to be common behavior when overriding built-ins. 

This means that adding the dependency alone isn't enough to solve the issue, I'm afraid (unless I'm deeply misunderstanding the situation).

**Comment by jarun** [comment]
My understanding is, we need to do 2 things:

- use gsed instead of sed on macOS
- update the recipe on Homebrew

@jose-elias-alvarez is that correct?

**Comment by jose-elias-alvarez** [comment]
That's right. That'll allow macOS users to use move and rename just by running `brew install nnn`.

**Comment by jarun** [comment]
Can you please confirm if the patch works fine for you with _gsed_?

If it does, please update the recipe on Homebrew.

**Comment by jose-elias-alvarez** [comment]
Confirmed working! I'll update the Homebrew recipe shortly.

**Comment by jarun** [comment]
Awesome!
