### ISSUE TITLE
Show directory size in detailed view

### ISSUE THREAD

**Issue by gunar** [jarun/nnn#729]
**Is your feature request related to a problem? Please describe.**

I need to find which files are wasting disk space so I can delete them.

**Describe the solution you'd like**

A plugin(?) so that in the detailed view the size of all the contents of a directory is displayed right next to its name (like `du` does).

**Describe alternatives you've considered**

I'm currently using `du` but its not as interactive as `nnn`.

**Additional context**

![image](https://user-images.githubusercontent.com/7684574/93075531-d601ab80-f67d-11ea-8e58-8e65f8475868.png)

**Comment by 0xACE** [comment]
hit `td` or `ts`.

Tbh i would highly recommend `ncdu` if your goal is to clear out your storage devices.

**Comment by gunar** [comment]
Thank you so much!

**Comment by jarun** [comment]
> Tbh i would highly recommend ncdu if your goal is to clear out your storage devices.

@0xACE what limitation do you see with nnn? Why does a nnn user have to use another utility when du analysis is available?

**Comment by 0xACE** [comment]
Mostly that `ncdu` remembers the diskusage of each folder.

Iirc, in my experience `nnn` likes to frequently rescan every directory.
