### ISSUE TITLE
Unable to escape rename file

### ISSUE THREAD

**Issue by e4nQJnE8** [jarun/nnn#73]
I tried to rename a file with ```^r```. I pressed backspace key and it produces an ```^?``` character instead of deleting, so I wanted to cancel renaming, but was unable to. Can we get a feature to cancel renaming with ESC key for example?

**Comment by jarun** [comment]
You can always press `^L` to clear the rename/new prompt. Then press `Enter` to cancel the operation. It's documented in help (`?`).

**Comment by e4nQJnE8** [comment]
I see, it works nicely. I read the documentation, but didn't understand that part.

**Comment by jarun** [comment]
There's also this: https://github.com/jarun/nnn#filters

**Comment by e4nQJnE8** [comment]
Yeah, I saw that, but the part I didn't understand (or connect in my mind) that I can use ```^L``` and then ```Enter``` to cancel the action. It makes sense now.

**Comment by jarun** [comment]
Okk. Have fun with nnn! It's terribly smooth, isn't it? ;)

**Comment by e4nQJnE8** [comment]
It is excellent! :)

**Comment by jarun** [comment]
I have updated the doc now. Thanks for bringing this to notice.
