### ISSUE TITLE
Open in PAGER, edit in EDITOR

### ISSUE THREAD

**Issue by 6arms1leg** [jarun/nnn#730]
Hello everyone,

first of all, thanks for this great application!  I just found it and absolutely love it (before I was using MC).

There seems to be quite some confusion about opening a text file in `$PAGER` or `$EDITOR` (i.e., #331, #446, #462, #580) and I am confused as well.

I would like to *open* (preview) text files in a pager and *edit* them in an editor.  Referencing nnn's help screen, that translates to the follwing keybindings:
* `return`/`l` key to *open* (preview)
* `e` key to *edit*

Consulting nnn's man page, this should be possible via `VISUAL="less" EDITOR="vim" nnn -eE`.  However, pressing `e` also opens the text file in Less.  From what I can see in the source code, `$VISUAL` and `$EDITOR` are coupled.

The best I could do so far is defining a plugin with `NNN_PLUG="e:-_vim $nnn" VISUAL="less" nnn -e`.  However, it is not the same (requires additionally pressing `;`).

Is there an easy way to exactly achieve above behavior?

Related side question: 
The man page mentions the `$PAGER` environment variable.  However, it seems not to be used anywhere.  How do I make use of the `$PAGER` environment variable in nnn?

Many thanks for your help!

**Comment by jarun** [comment]
> The best I could do so far is defining a plugin with NNN_PLUG="e:-_vim $nnn" VISUAL="less" nnn -e. However, it is not the same (requires additionally pressing ;).

The discussion in #580 aligns with this. To open in PAGER you need to run a cmd as plugin and attach a keybind to it, specifically the example `p:-_less -iR $nnn*`. BTW, to run (cmd as) plugin you can also use `Alt` instead of `;`.

If you see `nnn` help, `e` is described as `e  Edit in EDITOR`. There should not be any confusion.

If you want `return` \ `l` to open through PAGER (not all files should be opened _in PAGER_ though e.g. multimedia files), you can see this example: https://github.com/jarun/nnn/wiki/Advanced-use-cases#pager-as-opener

`nnn` uses PAGER internally, e.g. to show the help page.

**Comment by 6arms1leg** [comment]
Thanks for your quick response.

> The discussion in #580 aligns with this. To open in PAGER you need to run a cmd as plugin and attach a keybind to it, specifically the example p:-_less -iR $nnn*. BTW, to run (cmd as) plugin you can also use Alt instead of ;.

That's what I used before. Somehow I overlooked the option of using the `alt` key, though. That really speeds things up.

> If you see nnn help, e is described as e Edit in EDITOR. There should not be any confusion.

Well, if I run `VISUAL="less" EDITOR="vim" nnn -eE`, I would expect nnn to *open* (`return`/`l` key) files in `$VISUAL` and *edit* (`e` key) in `$EDITOR`. But `$VISUAL` takes precedence if both are set.
But never mind, with your answer (see below) you made me reconsider my desired nnn behavior.

> [...] not all files should be opened in PAGER though e.g. multimedia files [...]

You are right. I probably should reconsider my desired nnn behavior.

> nnn uses PAGER internally, e.g. to show the help page.

Ah right, that makes sense!

Again, thanks for your time! I really appreciate it.

**Comment by 6arms1leg** [comment]
@jarun, I think the man page descriptions for the `-e` and `-E` flags do not match nnn's behavior. I updated my previous comment.

**Comment by 6arms1leg** [comment]
I took the time to have a look at the source code and dared to create a tiny PR, see #733.
Now, pressing `e` actually "[e]dit[s] in EDITOR" (as stated on the help screen), instead of `$VISUAL`.

**Comment by jarun** [comment]
We do not want e to edit in EDITOR. If VISUAL is available that should be used. You can search and find the relevant defect. See the install deps as well (the last entry). The best we can do is change EDITOR to editor in help.

**Comment by 6arms1leg** [comment]
I see. Well, sorry for the noise then. Thanks for your time.
I find the help screen text quite misleading then.
