### ISSUE TITLE
Hardware cursor moves to wrong line

### ISSUE THREAD

**Issue by tspivey** [jarun/nnn#735]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Ubuntu 20.04
[X] Desktop Environment: none
[x] Terminal Emulator: PuTTY 0.74, 30 rows by 120 columns
[X] Shell: bash
[ ] Custom desktop opener (if applicable):
[x] Program options used: -w
[ ] Configuration options set:
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
```
mkdir tmp
cd tmp
for i in {1..100};do touch $i;done
nnn -w
```
Files 1 through 26 are shown, and the hardware cursor is on 1. Scroll down with the down arrow; all goes well until I get to file 24 and the list scrolls.
When I hit 24, the cursor sits on 25, while 24 is selected. After that, the hardware cursor and the selected file don't match.

**Comment by jarun** [comment]
@iressa can you please take a look?

**Comment by jarun** [comment]
Please confirm if the patch works as expected.

**Comment by tspivey** [comment]
It's working so far. Thanks!
