### ISSUE TITLE
Make an introduction video for nnn plugins

### ISSUE THREAD

**Issue by snide** [jarun/nnn#736]
@jarun I'll get one made within the next day or two. The outline will be as follows:

1. General overview of the system, showing various plugins.
2. How configs are handled through global env vars.
3. How to compile nnn with icons
3. How to make your own plugin

Yell if there is anything specific you'd like to see.

**Comment by jarun** [comment]
Looks good to me.

@0xACE @KlzXS @leovilok please suggest if you have anything.

**Comment by jarun** [comment]
Please note that it should be "introduction to nnn _plugins_". I feel plugins are one area users, specially newbies can make use of some good visual aid with examples.

**Comment by snide** [comment]
@jarun Started work on this today, but noticed compiling with master seems to bust for me. I hadn't tested your addition on my PR and admittedly I switched to a new laptop so I might be missing a core dependency. Any ideas?

![image](https://user-images.githubusercontent.com/324519/94285141-2c85aa00-ff08-11ea-8ebb-328fddedc4ad.png)

I'll try to get this up today if I can get local compiles running.

**Comment by jarun** [comment]
On which OS are you? At least on Linux, *BSD and Unix `getcwd(char *buf, size_t size)` allocates the memory if `buf` is NULL.

**Comment by snide** [comment]
Arch Linux.

**Comment by jarun** [comment]
Please test with commit 55f2a0823a2dea256d24707fdcf44cdf7d6c5670.

**Comment by 0xACE** [comment]
> @jarun Started work on this today, but noticed compiling with master seems to bust for me. I hadn't tested your addition on my PR and admittedly I switched to a new laptop so I might be missing a core dependency. Any ideas?
> 
> ![image](https://user-images.githubusercontent.com/324519/94285141-2c85aa00-ff08-11ea-8ebb-328fddedc4ad.png)
> 
> I'll try to get this up today if I can get local compiles running.

I've been getting those warnings myself, thought it was one of my patches, but I just looked at `master` and they are there too. The one in your screenshot is a false positive warning and is safe to ignore. `nnn` should work as normal.

Though jarun's new patch removes the warning message all together.

**Comment by snide** [comment]
Yep. Can confirm this works. Also noticed the actual compiled error I had was not related to this but a bum UTF setting. As soon as the kids end their playdate (too much noise!) I'll get this done today. Thanks for the help folks.

**Comment by snide** [comment]
https://youtu.be/-knZwdd1ScU

Here you go. Tried to show off as much as a could. If this works I'll make the video more public and close out this ticket.

**Comment by jarun** [comment]
This is super-cool! :+1: :heart: 

Please raise a PR to add this to the project README. That would be greatly helpful for new users.

**Comment by jarun** [comment]
An image like asciinema with a play button would be great. Also, please use a befitting caption.

**Comment by 0xACE** [comment]
> https://youtu.be/-knZwdd1ScU
> 
> Here you go. Tried to show off as much as a could. If this works I'll make the video more public and close out this ticket.

I like the video, it's is a complete walkthrough of the setup process if you ask me. Infact it was so good I followed along it to rip the `NNN_FCOLOR` as I cba to read the official docs :D

Regarding your `;u` plugin I would recommend you change the if-block where you copy the file into:
```
    cp "$1" "$HOME/davecloud/in" && exit 0
```

In linux `exit 0` commonly means "SUCCESS", anything other than `exit 0` is considered some kind of error/problem indication.

and putting it as `&& exit 0` makes it so that if you actually get an error, the script will not exit at that point and it will bring you to `read -r _`. Thus prompting the user, giving you a chance to read any potential error message `cp` may print.

Also in bash it's important to use quotes.

Good job ! I have missed you and I look forward to seeing more content from you :) _(given that you choose to continue)_

**Comment by snide** [comment]
@jarun Can do. Do you still want the other vids up there? I don't really care, just asking so I know how to rearrange the page.

@0xACE Thanks for the tip. I'm only play a programmer on Github, mostly I'm a designer, so I appreciate the help. One thing I was curious about was seeing if I could get the `imageview` plugin for `nnn` to take the marks from `sxiv` and pipe them back to nnn as selections. It looked like `sxiv` could do input/output, but I wasn't sure if `nnn` could read it out somehow. I may see if I can figure that out next, but yeah, happy to keep contributing in the limited way I can as a designer. I need to a do a follow up on the icons PR to clean up some of the icons with weird spacing.

**Comment by jarun** [comment]
We will link those in a section below. This will be the new front video as it is up to date.

**Comment by leovilok** [comment]
@snide congrats for the video.

> if I could get the imageview plugin for nnn to take the marks from sxiv and pipe them back to nnn as selections

It's possible, I tried it out a bit, you'll need this helper fonction:
~~~sh
tosel() {
    while read -r path ; do
        abspath "$path"
    done | tr '\n' '\0' | head -c -1 > ${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection
}
~~~
and you'll need to add the `-o` option to sxiv invocations, and feed the output to this `tosel`, e.g.:
~~~diff
-sxiv -qt "$1" >/dev/null 2>&1 &
+sxiv -qto "$1" 2>/dev/null | tosel &
~~~

Note that:
1. `sxiv` output marked files on exit, so you need to quit it to update dthe selection
2. this doesn't check if the selection is empty, so this clears the selection on each `imgview` invocation even if no file is marked

**Comment by jarun** [comment]
@snide we need to move fast with the video. I think your and my timelines seldom overlap so please share a cover image for the video (something with an asciinema-like arrow on it as I requested earlier) and I will set it in the project readme for the larger audience.

**Comment by snide** [comment]
![Frame 1 (1)](https://user-images.githubusercontent.com/324519/94587860-062d7a80-0238-11eb-99b1-a9c9f0c32ac2.png)

**Comment by jarun** [comment]
Awesome! Thank you so much!

**Comment by snide** [comment]
Closing the issue. I'll leave the readme to you. I made the video public on youtube, which exists at the same URL posted above.

**Comment by jarun** [comment]
I am setting it up right now! ;)

**Comment by jarun** [comment]
it's up! Check it out guys!

Do let me know if you want any adjustments.
