### ISSUE TITLE
Fuzzy search based bookmark

### ISSUE THREAD

**Issue by quantum-booty** [jarun/nnn#737]
The bookmark plugin uses shortcuts + a letter, but it gets confusing when there are many shortcuts or duplicate first letters, e.g. vim and virtualenv.
I think a fuzzy search based bookmark would be more accessible to users:
Add a key, string path to config: 'vim' : 'path/to/vim'
Press b to bring up search menu
type vim
select and press enter

**Comment by 0xACE** [comment]
https://github.com/jarun/nnn/blob/master/plugins/bookmarks

**Comment by jarun** [comment]
@0xACE beat me to it by 12 mins. Closing the issue as we already have it.

**Comment by jarun** [comment]
@quantum-booty symlinked bookmarks is now implemented in the core program. Will be available on the next release.
