### ISSUE TITLE
nnn help not persist on screen

### ISSUE THREAD

**Issue by kuntau** [jarun/nnn#738]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Ubuntu server 20.04
[ ] Desktop Environment:
[x] Terminal Emulator: tmux
[x] Shell: zsh
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[x] Configuration options set:
```
NNN_FIFO=/tmp/nnn.fifo
NNN_PLUG=f:fzcd;o:fzopen;z:fzz;d:diffs;t:treeview;v:preview-tui;h:fzhist;c:chksum
```
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I found out on tall screen, the nnn help _page_ invoked by `?` Only appear briefly and appear after I exit nnn

Without tmux, the page didn't appear at all.

See screencast

[![asciicast](https://asciinema.org/a/4bx8aae9Hqu3crobF11FTXGp5.svg)](https://asciinema.org/a/4bx8aae9Hqu3crobF11FTXGp5)

**Comment by 0xACE** [comment]
I'm not on master so I'm not sure if changes has been applied recently. but what is you `$PAGER` set to? `?` displays the help information via your `$PAGER`, my guess is your pager is set to close immediately if the output finishes before the end of the screen

**Comment by jarun** [comment]
Please check if you are facing this documented issue in the Troubleshooting section: https://github.com/jarun/nnn/wiki/Troubleshooting#help-not-showing

**Comment by kuntau** [comment]
Thanks guys. I didn't know the help page is using less 😅
