### ISSUE TITLE
Support `gio trash`?

### ISSUE THREAD

**Issue by rieje** [jarun/nnn#740]
Looking at using trash with nnn, seems like it uses `trash-cli`. This was not clear with `man nnn`:

`NNN_TRASH`: 

    trash (instead of delete) files to desktop Trash.

It would be nice if `gio trash` is supported as well (it follows the same FreeDesktop.org Trash specification). Personally, I use it instead of trash-cli to avoid an additional dependency (`gio trash` is provided by `gvfs-mtp` which is needed for modern Android devices for file managers).

**Comment by jarun** [comment]
`nnn` uses `trash-cli`. Dependencies are not listed in the man age. Here's the relevant Wiki section: https://github.com/jarun/nnn/wiki/Usage#dependencies

> Personally, I use it instead of trash-cli

Please raise a PR. It would be a good addition. If you can make it soon, we can have it in the next release.

**Comment by jarun** [comment]
Please confirm that the patch works as expected.
Please test with single as well as multiple file deletion.

**Comment by rieje** [comment]
Works as expected for both, thanks!
