### ISSUE TITLE
Moving and copying looks for "mvg" and "cpg"

### ISSUE THREAD

**Issue by Kratacoa** [jarun/nnn#746]
#### Environment details (Put `x` in the checkbox along with the information)

[x ] Operating System: Void Linux, musl version
[x] Desktop Environment: none
[x ] Terminal Emulator: Kitty
[x ] Shell: Fish
[ ] Custom desktop opener (if applicable):
[x ] Program options used: aeEnrx
[ ] Configuration options set:
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Select a file with `Space`, then either`^C` or `^V`, or go through the same motions with `c` and `w`.
It displays either that `cpg` or `mvg` is not found.

**Comment by 0xACE** [comment]
I'm not familiar with `master` bindings, but sounds like you enforced `nnn` to use `mvg` and `cpg` which shows a progress bar for `mv` and `cp` processes. Look at the arguments you give `nnn`, one of them invokes `mvg`/`cpg`.

As of last 3 weeks-ish it has been having issues with `sshfs` mounts so I've been avoiding it.

**Comment by jarun** [comment]
@Kratacoa please remove the option `-r` from your `nnn` alias.

**Comment by Kratacoa** [comment]
> @Kratacoa please remove the option -r from your nnn alias.

Yep, that was it. Sorry for carelesness 😪

> EDIT: on second thought, doesn't nnn check if mvg/cpg actually exists when you enforce them?
Doesn't do it on my computer :/
