### ISSUE TITLE
(question) Can I have 'nnn' use the 16 colours set in by my terminal?

### ISSUE THREAD

**Issue by 5c0tt-b0t** [jarun/nnn#749]
Hi! Thank you so much for this amazing file manager! and also your other projects like buku etc etc.
I was wondering... I have a beautiful theme already and I would like to use it in 'nnn' too, Is this possible? can it respect the base 16 colours?
If not, how would I make a theme for nnn?
I have searched for themes abd found none, but I have seen on Reddit/UnixPorn etc some nicely themed setups.
If its not possible to use 16 colour and it is possible to theme...I would like to bring GruvBox, Nord & Dracula to 'nnn' as plugins.

**Comment by 0xACE** [comment]
https://user-images.githubusercontent.com/1482942/93023823-46a6ba80-f5e1-11ea-9ea3-6a3c757704f4.png

i guess they describe the 16 first colors?

infact what the colors do in chat chart is totally up to your terminal

**Comment by jarun** [comment]
Use the config options `NNN_COLORS` and `NNN-FCOLORS`: https://github.com/jarun/nnn/wiki/Usage#configuration

You are probably interested in the hex notation for `NNN_COLORS`.

**Comment by leovilok** [comment]
If you use colors from '0' to 'f' (16 first color registers), I guess it should use your theme's 16 colors.

**Comment by pricheal** [comment]
Isn't this what `nnn -C` is for?
