### ISSUE TITLE
How to use unmount keybind?

### ISSUE THREAD

**Issue by anton-rs** [jarun/nnn#750]
When I press 'u' it says 'remote name ('-' for hovered):
What I should insert there?

I mount my USB drive using Udiskie.

**Comment by jarun** [comment]
The unmount option is for remote and archive mountpoints. I have updated the help. Generally you should use the same program to mount and unmount. In `nnn` you can mount on demand using the plugin `nmount`.

**Comment by jarun** [comment]
Additional reading: https://github.com/jarun/nnn/wiki/Basic-use-cases#unmount-remotes
