### ISSUE TITLE
Colors broken in 3.4.1

### ISSUE THREAD

**Issue by chungktran** [jarun/nnn#751]
[x] Operating System: Windows 10
[ ] Desktop Environment:
[x] Terminal Emulator: wsltty
[x] Shell: zsh/fish
[ ] Custom desktop opener (if applicable):
[ ] Program options used: 
[x] Configuration options set: `export NNN_COLORS='4521'; export NNN_OPENER=$HOME/.bin/nuke`
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Release 3.4.1 broke color. Please see attached screenshot. Reverted to 3.3 and color works fine.
Version: 3.4.1
![nnn](https://user-images.githubusercontent.com/49414458/95409849-97fc4e00-08f0-11eb-920d-253d82b58d91.png)

Version: 3.3
![nnn3 3](https://user-images.githubusercontent.com/49414458/95410006-df82da00-08f0-11eb-922a-0ab772adb37a.png)

**Comment by jarun** [comment]
That's the new colorscheme (refer to the docs). Use option `-C` for earlier colorscheme.
