### ISSUE TITLE
Going to shell from inside nnn clutters my $COMMAND_PROMPT

### ISSUE THREAD

**Issue by tobip** [jarun/nnn#752]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Manjaro ARM
[x] Desktop Environment: Sway
[x] Terminal Emulator: Termite
[x] Shell: Bash
[ ] Custom desktop opener (if applicable): 
[ ] Program options used:
[ ] Configuration options set:
[] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
When I go to shell from inside `nnn` using `!` it will refill my `$COMMAND_PROMPT` kind of messing it up.

1. I open a terminal
2. `nnn`
3. `!`
--> $COMMAND_PROMPT ist broken.

```
 ~  $  echo $PROMPT_COMMAND
history -a; history -n; _update_ps1; printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"; (_z --add "$(command pwd -P 2>/dev/null)" 2>/dev/null &)
 ~  $  nnn
 ~  $  echo $PROMPT_COMMAND
history -a; history -n; history -a; history -n; _update_ps1; printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"; (_z --add "$(command pwd -P 2>/dev/null)" 2>/dev/null &); printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"
```

**Comment by 0xACE** [comment]
cba to read and do a proper comparison, but it seems like something in your environment is appending extra details each time your shell environment is loaded.

**Comment by tobip** [comment]
Well yes, as far as I can tell at least my ~/.bashrc gets reloaded everytime I go to shell from inside nnn.
I don't know if this is expected behavior?

At least I can manually alter my .bashrc to avoid double-changing environment variables.

**Comment by jarun** [comment]
We just do a `spawn(shell, NULL, NULL, F_CLI);` where `shell` is `$SHELL`.

**Comment by jarun** [comment]
So I guess you run bash within bash you may see the same result.

**Comment by 0xACE** [comment]
@tobip 

I mean that somewhere in your expansion tree of `~/.bash_profile`, `$PROMPT_COMMAND` adding the data to the existing `$PROMPT_COMMAND`

Correct:
```
export $PROMPT_COMMAND="fresh new prompt"
```

Incorrect:
```
export $PROMPT_COMMAND="$PROMPT_COMMAND not really fresh as it's appending to whats there"
```

I may be wrong and I'm really just guessing, would probably be easy to try it for yourself by typing `bash` within your `bash` shell and see if the same error appears. (finished writing and saw that jarun mentions this aswell)

**Comment by jarun** [comment]
Closing this as `nnn` doesn't access random environment variables.

**Comment by tobip** [comment]
Yes you were right, in my `~/.bashrc` and at another place I wasn't able to find yet there are commands that add stuff to `$PROMPT_COMMAND`, without checking if this has already be done. 
Thanks anyways for taking your time!
