### ISSUE TITLE
when using nnn to mount test.zip  error says "missing util" ..could it say what util is missing ? 

### ISSUE THREAD

**Issue by maxandersen** [jarun/nnn#753]
--- PLEASE DELETE THIS LINE AND EVERYTHING ABOVE ---

#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: osx
[x] Desktop Environment: osx
[x] Terminal Emulator: iterm2
[x] Shell: zsh
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

nnn in directory with a .zip file, press enter and press 'm' when asked if want to mount.

**Comment by jarun** [comment]
Please refer to the docs, the list of deps in particular: https://github.com/jarun/nnn/wiki/Usage#dependencies

It would be `archivemount` in your case.

**Comment by jarun** [comment]
I have added the fix to show the missing utility name. Please test and confirm.

**Comment by maxandersen** [comment]
I don't have a setup to easily build/run it but will try as soon as available.

btw. I searched high and low in docs and never would have found the "Usage dependencies" unless you just pointed me to it. Maybe put this more front and center on readme file ? 

thanks for the pointers - definitely helped!

**Comment by jarun** [comment]
> Maybe put this more front and center on readme file ?

I understand you have missed it. For serious nnn users I would suggest going through the right side bar. It's there. Searching doesn't help as there are multiple pages. I'll now link the deps from Quickstart section.
