### ISSUE TITLE
Support switching context while extracting

### ISSUE THREAD

**Issue by warmos** [jarun/nnn#754]
Hello,
It can be useful, if you could change the context while you are extracting some 10GB+ file to avoid running another instance of nnn. Just an idea
Thanks

**Comment by jarun** [comment]
Please use a multiplexer for this purpose: https://github.com/jarun/nnn/wiki#dual-pane
We mentioned dvtm because it is very lightweight.

There are many reasons things can go wrong when utilities are run in the background and the user has no way to know about it.

**Comment by jarun** [comment]
Few examples:

- we run most of these in interactive mode for safety, so there can be prompts before completion
- things can fail, say. running on low disk space
- new bugs to fix where user force quits

I don't see any ROI in spending time to support and handle these.
