### ISSUE TITLE
cygwin support?

### ISSUE THREAD

**Issue by krishnakumarg1984** [jarun/nnn#757]
In the `README.md`, it is claimed that 

>It runs smoothly on the Pi, Termux (Android), Linux, macOS, BSD, Haiku, **Cygwin**, WSL, across DEs and GUI utilities or a strictly CLI environment.

However, I don't see any cygwin package for `nnn`. So, is the above claim true? If not, can you either support `cygwin` or remove `cygwin` from that sentence in the project's readme file?

**Comment by jarun** [comment]
I think we already discussed similar things in #146 and #148.

A project doesn't need to have a package to be able to run on a particular platform as it can be compiled on that.

Feel free to port `nnn` to Cygwin and maintain the package there.

**Comment by jarun** [comment]
`nnn` is now available on Cygwin: https://www.cygwin.com/cgi-bin2/package-cat.cgi?file=x86_64%2Fnnn%2Fnnn-4.6-1&grep=nnn
