### ISSUE TITLE
How to disable icons by default?

### ISSUE THREAD

**Issue by ProgrammingLife** [jarun/nnn#758]
I've downloaded and installed the latest version of NNN and it runs with icons. My terminal can't display icons so I wanna turn this feature off. How can I do it?

**Comment by jarun** [comment]
You have to give some more details like OS etc. There are some auto-generated packages for every release. If you are lucky, you might get something for you distro. If not, compile from source. Refer to the documentation in Wiki for instructions.

**Comment by ProgrammingLife** [comment]
@jarun I'm compiling it from the source. What should I do to turn icons off in that case?

**Comment by jarun** [comment]
Default compile. Icons are compile-in features: https://github.com/jarun/nnn/wiki/Developer-guides#compile-in-icons-in-terminal

**Comment by jarun** [comment]
Do spend some time reading the docs. We had spent ours writing it so that we do not have to re-iterate the same info again and again.
