### ISSUE TITLE
nnn's ! command doesn't work properly with kitty (--cwd=current)

### ISSUE THREAD

**Issue by Kratacoa** [jarun/nnn#759]
#### Issue
When I navigate to a directory in nnn, exit it with ! and open another window with `launch --cwd=current` (which is the command for `kitty` that allows to open a new window inside the previous directory), it opens inside home directory.  
Actually, after doing such an action, even if i cd outside, it keeps opening inside the home directory.  
[According to kitty's author](https://github.com/kovidgoyal/kitty/issues/3024#issuecomment-707242405), this is because `nnn` doesn't set the shell as the active process for the terminal device.  
Kitty uses the current directory of the active foreground child process associated with the terminal device in the active window.

#### Environment details (Put `x` in the checkbox along with the information) 

[x] Operating System: Void Linux, musl version
[ ] Desktop Environment:
[x] Terminal Emulator: kitty
[x] Shell: fish
[ ] Custom desktop opener (if applicable):
[x] Program options used: aeEnx
[ ] Configuration options set:
[x] Issue exists on `nnn` master

**Comment by jarun** [comment]
`!` does not exit `nnn`, it spawns a shell in the current dir. (In case you want to setup cd on quit, visit the quickstart section.)

We took care of the chdir() thing in https://github.com/jarun/nnn/commit/cfd4a6659623014243696812daba254dd3116e12.

Even if I spawn a shell within nnn and open thunar, I see it opening in the spawned directory:

![](https://i.imgur.com/tGiB7V0.png)

It's possible I don't quite understand what you are talking about. In that case, leaving it open for others to pitch in.

**Comment by jarun** [comment]
I also see:

```
2 ~/GitHub/nnn/src$ pwd
/home/vaio/GitHub/nnn/src
2 ~/GitHub/nnn/src$ echo $PWD  
/home/vaio/GitHub/nnn/src
```

So the current working directory is set correctly within the spawned shell. I am not sure why any other elaborate mechanism is required for any other subsequent processing to understand which location should be opened in the next window.

**Comment by jarun** [comment]
I tried a similar test by opening another tab in xfce4-terminal and I see it opens in home. So I think this is the problem you wanted to mention.

**Comment by 0xACE** [comment]
> I tried a similar test by opening another tab in xfce4-terminal and I see it opens in home. So I think this is the problem you wanted to mention.

Afaik this happens because the terminal itself reports it as it's own `cwd` and not the process that is running in the foreground. I have a similiar situation with `st` and `tmux`, just never bothered caring for it... The author in the other thread mentioned `vim` working properly, though I see the same issue with `vim`.... alas I'm not familiar with `launch --cwd=current` so I can't investigate at this time...

**Comment by jarun** [comment]
@KlzXS @leovilok please see if this can be resolved easily ([without forking](https://stackoverflow.com/questions/51697742/how-do-i-make-a-background-process-block-for-input-a-la-the-shells-bg-command) and all... I guess this has to do with tcsetpgrp and tcgetpgrp).

Otherwise I am fine with not fixing it and moving on. We can't keep forking as if we have unlimited resource.

**Comment by leovilok** [comment]
Why not simply use `--cwd=$PWD`?

**Comment by leovilok** [comment]
I guess you're right about `tcsetpgrp`, but we wouldn't even need to set it to the subshell PID: setting it to the PID of `nnn`¹ should be enough, as we already do `chdir()`.

¹: well after calling `setpgid(getpid(), 0)` to create the new process group.

**Comment by jarun** [comment]
@leovilok can you please raise the PR? I experimented with similar which didn't work with xfce4-terminal. Maybe I missed something.

**Comment by jarun** [comment]
Ignore the earlier comment. Tested with kitty. Works fine.

**Comment by jarun** [comment]
@Kratacoa please confirm that the patch works as expected for you.

**Comment by Kratacoa** [comment]
Nope, I'm afraid it doesn't work.  
I've compiled the main branch as of the latest commit.  
How can I provide some useful information?

**Comment by jarun** [comment]
The way I tested this is:

- add the following on kitty config to map <kbd>F2</kbd> to open new tab: `map f2 launch --cwd=current`
- run `nnn`
- navigate to a different directory
- press <kbd>!</kbd>
- press <kbd>F2</kbd>

**Comment by Kratacoa** [comment]
Yeah, my setup is pretty much the same. Cannot reproduce the correct behaviour.
Although, now it does work properly when I open a window while *inside* nnn.

**Comment by jarun** [comment]
I just tested with `kitty-0.19.1` and it works for me there as well. Sorry but I can't spend more time on this.

**Comment by jarun** [comment]
My complete kitty config for reference:

```
allow_remote_control yes 
font_size 8.0 
map f2 launch --cwd=current
```

**Comment by jarun** [comment]
For future reference. The equivalent in `xfce4-terminal` is `xfce4-terminal --tab --working-directory=$PWD`

**Comment by jarun** [comment]
Reopening as we had to revert the patch due to side-effects. Feel free to pitch in.

**Comment by leovilok** [comment]
We might want to reset the terminal process group on exit to what it was before.

**Comment by jarun** [comment]
Please try it out and please confirm with @Kratacoa.

Also, please confirm #763 is not reopened in the workflow.

**Comment by jarun** [comment]
@leovilok in case you might not have noticed, please feel free to experiment with this. I did try what you suggested but it didn't work. Very much possible I made a mistake somewhere.

**Comment by leovilok** [comment]
@jarun I had noticed, but my interest was quite low, and I finally forgot about this. Note that I never tested anything in this issue, every suggestion I made came from the docs or other discussion I read on the web. But I'm still unsure about how/when `getpgid`/`setpgid` *should* be used (except for kitty). I don't know how other TUI programs use it, I've not seen source code with these functions (except kitty source).

**Comment by jarun** [comment]
No problem! I will leave it open. I assumed you have more clarity on this.

**Comment by jarun** [comment]
This is open for a while and I don't see anyone picking it up.

Closing the issue and adding a line item in the ToDo list for the same.

**Comment by jarun** [comment]
@Kratacoa now we have a solution to get the `nnn` cwd: https://github.com/jarun/nnn/wiki/Troubleshooting#new-windowpane-using-cwd

**Comment by jarun** [comment]
We also suggested an easy solution for this [here](https://github.com/kovidgoyal/kitty/issues/3024#issuecomment-930329239) using OSC 7 but it wasn't preferred.
