### ISSUE TITLE
nnn icons missing with tmux

### ISSUE THREAD

**Issue by aintyourcat** [jarun/nnn#767]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Void Linux
[ ] Desktop Environment:
[x] Terminal Emulator: st
[x] Shell: bash
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
This is nnn on st:
![10-26-2020_09:07:55](https://user-images.githubusercontent.com/66950307/97096659-e441df00-16a1-11eb-9daa-1eca8e3d3fa1.png)
This is nnn on tmux on st:
![10-26-2020_09:08:18](https://user-images.githubusercontent.com/66950307/97096660-e6a43900-16a1-11eb-927a-219296c6a50e.png)
What I've tried:
1. Exporting these env: 
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8
2. Ran tmux with the -u flag: tmux -u
3. Changing the term into alacritty and kitty

**Comment by 0xACE** [comment]
I dont have the icon fonts installed so I cant really help much. But are you sure you are loading the exact same version of `nnn` in tmux?

Because it shouldn't matter to `nnn`. `nnn` is blind and just dumps the exact same text afaik.

**Comment by aintyourcat** [comment]
Sure, I only have 1 version of nnn installed

**Comment by jarun** [comment]
I can repro this. The reason is tmux runs n 8-color mode (at least that's what is the value of COLORS when I run nnn in debug mode and see the logs):

```
 ln 1702: COLORS=8
 ln 1703: COLOR_PAIRS=64
```

**Comment by aintyourcat** [comment]
Thanks! Fixed it by adding: set -g default-terminal "screen-256color" on tmux configuration file.

**Comment by jarun** [comment]
Awesome! Thank you for the solution. Will add it to the docs.

**Comment by jarun** [comment]
Added here: https://github.com/jarun/nnn/wiki/Troubleshooting#tmux-configuration
