### ISSUE TITLE
Children processes are decoupled from the owner shell

### ISSUE THREAD

**Issue by 0xACE** [jarun/nnn#770]
Hey, I'm tired so I'll keep this short:

Example:

opening a image with `nnn`, results in `xdg-open` spawning the image viewer. When you go to your favorite process monitor, you can see that in the tree of processes, that the spawned version of `xdg-open` isn't a child of `nnn`...

on my pc it spawns under a new branch under:

```
init 
├─ sh /usr/bin/xdg-open very-cool-image.tga
│  └─ gimp very-cool-image.tga
├─ nnn # nnn who is the original parent is in a seperate branch
```

(tested it in `master`)

I think we shouldn't condone orphaning processes and take responsibility of our children 🙂 :1st_place_medal: 

![cap](https://user-images.githubusercontent.com/1482942/97767974-9b61ae80-1b17-11eb-8dd2-f03add46159c.png)

**Comment by KlzXS** [comment]
This was done on purpose. I think it had something to do with `nnn` going all out on the cpu if you closed a terminal with nested `nnn`s.

`ranger` also opens files like this, I assume other file managers as well, so I don't see why this is an issue.

**Comment by jarun** [comment]
We did it to fix the zombie child-process issue. More details here: https://github.com/jarun/nnn/issues/449

There's no going back. Just close the image viewer when you are done admiring the former POTUS. Given the current situation, many would not even close it or set it as the desktop wallpaper.

**Comment by 0xACE** [comment]
Ah, now when you mention it, I remember... I'm so glad i just asked rather then research it myself, thank you <3

For future reference, it's a problem for me because I needed to make `nnn` "swallow" it's children processes so they "inherit" or take the space `nnn` was using

![inheritance](https://user-images.githubusercontent.com/1482942/97779435-f4602f80-1b75-11eb-8e23-a053993c6262.gif)

the gif shows that `nnn`'s child can't find a X11 windowed parent so it spawns as a orphan (bottom row). Whereas a regular shell spawns the child correctly (top row).

I'll see if I can work around it in a simple manner. Cheers
