### ISSUE TITLE
preview_tui plugin renders unreadable preview when bat is installed

### ISSUE THREAD

**Issue by raghavmallampalli** [jarun/nnn#773]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: WSL2 Ubuntu 18.04
[ ] Desktop Environment:
[x] Terminal Emulator: Windows Terminal Preview + tmux
[x] Shell: zsh
[ ] Custom desktop opener (if applicable):
[x] Program options used: none
[x] Configuration options set:
```sh
export NNN_FCOLORS='c1e2677800609ff7c6d6abd2'
export NNN_PLUG='f:fzfasd;o:fzopen;d:diffs;t:nmount;v:imgview;p:preview-tui'
export NNN_FIFO='/tmp/nnn.fifo'
```
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Compile nnn, download plugins, load preview in tmux split
If `$PAGER` isn't explicitly set to `less -R` in a system with `bat` installed, the preview is filled with Unicode strings that make the output unreadable. The only solution I could come up with was setting `$PAGER` to `less -R` within the `if exists bat` portion of the `preview_tui` plugin.

**Comment by jarun** [comment]
@leovilok can you please take a look?

**Comment by leovilok** [comment]
I'll try to reproduce myself later (though not on Windows), but can you open a file in `bat` in `tmux` outside of `nnn` @raghavmallampalli ? does it show the same issues ?

**Comment by leovilok** [comment]
@raghavmallampalli also, what's your $PAGER set to? If it's set to `less` without the `-R` option that's an issue. I think that we already discussed it for `preview-tui`, maybe we should enforce `less -R`, as other `$PAGER` values would most likely not work.

**Comment by raghavmallampalli** [comment]
Unable to repro outside of nnn. Using `less` and `bat` together on a standard text file works fine, even without the raw flag. I suspect it has something to do with the FIFO, I'm not sure how to use `bat` to page a FIFO (other than just copy pasting the code in preview_tui).

Sorry if I didn't make it clear in the original post, `less` was my pager outside of nnn and setting it to `less -R` in `preview_tui` is what made it work.

**Comment by jarun** [comment]
I tried the following without any changes to any plugin:

    export PAGER='bat --theme zenburn'
    nnn -a

Then `Alt-P` on file nnn.c. It opens in bat and renders correctly.

Can you try this simple thing with ZERO changes in the `preview-tui` plugin? And definitely not with:

> The only solution I could come up with was setting $PAGER to less -R within the if exists bat portion of the preview_tui plugin.

Plugins are indicative examples. With the bandwidth we have, we can't keep supporting users changing the plugins and things going wrong.

**Comment by raghavmallampalli** [comment]
That worked, thank you.

**Comment by jarun** [comment]
You are welcome!

**Comment by dkvasnicka** [comment]
Sorry if this is a dumb question but why can't `bat` executed by `nnn` just respect `BAT_THEME` like "normal" `bat`? Is the env not propagated to the new `tmux` pane?

Also, exporting `PAGER` does not work for me.

**Comment by leovilok** [comment]
@dkvasnicka we don't do anything to BAT_THEME, there must be some issue with your environment.

**Comment by raghavmallampalli** [comment]
@dkvasnicka this is what I did on my terminal:

- Added `export $PAGER='bat --style=plain' to my shell rc
- Killed my tmux server, restarted my shell, started tmux server again

It began working. A screenshot:
![image](https://user-images.githubusercontent.com/49435792/101894113-b1a96280-3bcb-11eb-9ebf-265d9282593b.png)

The `--theme=zenburn flag` is not necessary if you've BAT_THEME in your rc file.

For whatever reason, `export PAGER='bat'; nnn -a` doesn't work if PAGER is not set from the shell rc.
