### ISSUE TITLE
autojump plugin / jump vs autojump

### ISSUE THREAD

**Issue by ralphee** [jarun/nnn#774]
#### Environment details (Put `x` in the checkbox along with the information)

[x ] Operating System: Arch Linux
[x] Desktop Environment: DWM
[x ] Terminal Emulator: st
[ x] Shell: zsh
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[ ] Issue exists on `nnn` master

ref: autojump Plugin -> (https://github.com/gsamokovarov/jump)
using jump I receive the following error "autojump missing"; no issue with autojump (https://github.com/wting/autojump).

**Comment by jarun** [comment]
@snide please take a look.

**Comment by jarun** [comment]
I think you are using the older script. The latest script does not have the message: `autojump missing`.

Also, jump and zoxide are supported on master. You can copy manually and try. But I would suggest you wait for the next release, then update your plugins and give it a try.

**Comment by jarun** [comment]
You can confirm this easily by comparing the autojump plugin in master to your _installed_ copy.

**Comment by ralphee** [comment]
> You can confirm this easily by comparing the autojump plugin in master to your _installed_ copy. I think your installed version would not have jump or zoxide.

confirm working now with updated version. Thxs!

**Comment by mortezadadgar** [comment]
well it's a little strange why getplus doesn't take the latest autojump, maybe the other plu-ins are affected by this bug too

**Comment by jarun** [comment]
No, it's by design. Plugins are bound to their release. Latest plugins changes may not be compatible with the earlier release. Hence it's done that way.
