### ISSUE TITLE
Double/Triple Esc

### ISSUE THREAD

**Issue by jeff-hykin** [jarun/nnn#775]
**Describe the solution you'd like**

When in the normal context (ex: `nnn` with no arguments) when Esc is pressed twice back-to-back, exit as if `q` were pressed.

(I would also be fine if a single press of Esc were to exit like pressing `q`)

**Why? (why not just use q)**

Two cases

Type-to-nav, specifically as a replacement for cd (the `alias n="nnn -Ano"` is wonderful, thank you for those options)
1. `cd ../..`
2. `n Enter ← ← Ctrl+G`
3. `n Enter ← ← Esc q`
4. `n Enter ← ← Esc Esc Esc`

Mac's have terrible Ctrl key placement. There's only one Ctrl key, it's as small as Alt, and its harder to press than tilda, Fn, alt, 6, or eject. On a Mac Ctrl+G is so slow and unreliable (easy to accidentally hit `f` or `h`) that Esc + q is a better option. However, Esc + q is probably the next-most cumbersome key combination (just try it, theres no way to do it quickly). This makes `cd ../..` faster than `n ← ← Ctrl+G`, but only because of the Ctrl. On a mac `n ← ← Esc Esc Esc` is the fastest option on the list by far.

Second case; if a user is spamming the Esc key, its pretty likely want to exit the program. If they're tired and frustrated trying to finish a project, I'm sure they'd appreciate it, and I don't think any other users would complain.

**Describe alternatives you've considered**

1. Installing an extension that has an alternative binding, such as alt+G, that lets me exit quickly
2. Compiling from source and adding the keybinding myself

The reason compiling from source isn't viable for me is that I will be using `nnn` in various environments, like Docker containers, other people's raspberry pi's, and various laptops. A script to automatically call `brew install nnn` or `apt install nnn` and then set an alias is feasible. But having those environments automatically clone the source, edit it, install a compiler, and then compile it (or pre-building and distributing those just for a single key-combination) is infeasible.

**Consider contributing**

I'll be happy to figure out what needs to be modified, and make a PR.
(I just don't want to do that if the feature is just going to be rejected)

**Comment by jarun** [comment]
We had considered this before but the argument from @KlzXS was - it might become an issue for seasoned vim users who press `Esc` frequently to move out of the command mode. And I tend to agree with that argument.

However, I am just wondering that we quit if `Esc` is pressed twice consecutively _only_ when we are out of any filter/status bar edit mode, would that be enough. So if the user is in filter/nav-to-type, he has to press `Esc` once to come out of it, then press `Esc` twice to exit `nnn`.

@KlzXS @0xACE @leovilok please share your opinion.

**Comment by jeff-hykin** [comment]
> if `Esc` is pressed twice consecutively _only_ when we are out of any filter/status bar edit mode

That would be perfect for me.


> We had considered this before but the argument from @KlzXS was - it might become an issue for seasoned vim users who press `Esc` frequently to move out of the command mode. And I tend to agree with that argument.

This makes sense, thanks for explaining.


I'd also be fine with a command line argument for enabling the behavior. Or an option for the enter key, when in type-to-nav, to "open" the folder in command line (by cdquitting back to the command line).

**Comment by jarun** [comment]
Please test master and confirm it works without issues.

**Comment by jeff-hykin** [comment]
Confirmed, thank you @jarun !

**Comment by leovilok** [comment]
I'm not sure about this, I guess we'll see over time.

**Comment by 0xACE** [comment]
I've been away, i tried reading the issue and I don't understand whats going on... Don't think I can try this until I re-merge with master... I'll come back here if I notice a problem though.
