### ISSUE TITLE
nnn icons do not work when compiled with O_ICONS=1 or O_NERD=1

### ISSUE THREAD

**Issue by vide0hanz** [jarun/nnn#776]
Terminal emulator: st
Default font: IBM Plex Mono (tested with others as well)

Hey there, 

This has been bugging me for a while and I cannot for the life of me figure out what I am doing wrong here. I have cloned the nnn repo and run `sudo make O_ICONS=1 clean install` as well as `sudo make O_NERD=1 clean install` but neither method displays any icons on my system.

I've tested with both st and alacritty and have confirmed the fonts are set correctly in their respective configuration files. I'd prefer to use the icons-in-terminal method if possible.

I've done the installation of icons-in-terminal multiple times and followed all of the instructions there to no avail. I can run the script `./print_icons.sh` from the icons-in-terminal source repo just fine and all of the icons output correctly. 

Any ideas? I don't think this is a bug with nnn, but I'm at my wit's end trying to figure this one out. Hoping you can help!

**Comment by jarun** [comment]
I hope you have followed the instructions here: https://github.com/jarun/nnn/wiki/Advanced-use-cases#file-icons

Do you see squares instead of the icons or nothing at all?

The other possibility can be you are running in 8 color mode. What is the output of:

    echo $TERM

You can also compile `nnn` in debug mode and see the value of the following:

```
COLORS
COLOR_PAIRS
```

**Comment by vide0hanz** [comment]
> Do you see squares instead of the icons or nothing at all?

Nothing at all. This happens when compiling with O_ICONS=1 and O_NERD=1, even though I am using a patched nerd font (BlexMono Nerd Font). 

The icons work in other applications, like ranger for example. Again, with the icons-in-terminal method I can successfully run the script to print the icons and they all display correctly there.

I will try some of the other suggestions when I get back to my PC later today and give you an update.

**Comment by jarun** [comment]
Also, make sure you are not running `nnn` with the option `-C`.

**Comment by jarun** [comment]
Also, contents of my `~/.config/fontconfig/conf.d/30-icons.conf`:

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias><family>No font found</family><prefer><family>icons-in-terminal</family></prefer></alias>
  <alias><family>Monospace</family><prefer><family>icons-in-terminal</family></prefer></alias>
</fontconfig>
```

**Comment by vide0hanz** [comment]
Ok, it works, the issue was on my end as I suspected. I must have been running my terminal in 8 color mode via my .zshenv file. I had the line `export TERM='st'` in there, but commenting it out results in `st-256color` output from `echo $TERM`

I had no idea that would make a difference! Thanks for the insight there, I probably never would have thought to check that.

**Comment by jarun** [comment]
Thanks for the update. I'll add this to the Wiki.
