### ISSUE TITLE
Issues with nerd font

### ISSUE THREAD

**Issue by ghistes** [jarun/nnn#780]
Hi,

this is probably just me being stupid, but I just compiled the head with "make O_NERD=1" and installed the Inconsolata nerd font.

I configured the font for my terminal (urxvt) and I am getting icons for most of the files, however:

- I do not an icon for most of the directories (the exceptions are directories named "Templates" and "Videos".
- I do not get an icon for *.txt files

I assume (correctly?) that this is not the expected behaviour.

What could be the problem here?

Many thanks!

**Comment by jarun** [comment]
> I do not an icon for most of the directories

Please check [icons.h](https://github.com/jarun/nnn/blob/74cd15c232ffbe5f77be547abef4ab6ff6b33fcf/src/icons.h#L57). Probably you don't have this icon. You can set a preferred icon (which is available in your system) for directories.

I have [linked](https://github.com/jarun/nnn/wiki/Advanced-use-cases#file-icons) this file in the documentation.

> I do not get an icon for *.txt files

There's no specific icon for text files. We don't want to run `file` on every file when loading.
