### ISSUE TITLE
ueberzug preview?

### ISSUE THREAD

**Issue by ghistes** [jarun/nnn#782]
Hi,

I've just played around a little bit with ueberzug and it seems to works great even with tmux.

Grepping through the plugins I could not find anything - so my question is:

Is there currently a plugin to allow previews with ueberzug and if not is there any deeper technical reason for that or is it just because nobody got around to make one?

Many thanks!

**Comment by jarun** [comment]
@leovilok 

There's no technical reason I am aware of. Feel free to write one, or preferably, add the functionality to preview-tui or preview-tabbed.

**Comment by 0xACE** [comment]
I'm not familiar with `ueberzug`, but I use similiar to preview images with `nnn`, either create a script or change one of the existing ones to use `ueberzug`

**Comment by jarun** [comment]
@ghistes feel free to raise a PR if you are doing this. I will add a line item for this in the ToDo list and close the current issue.

**Comment by leovilok** [comment]
I don't use ueberzug myself, and nobody added support for it in the preview scripts.
It could be added though is seems quite hard to use, and has its own logic that might not easily fit into existing scripts.
Actually, it looks like writing a new preview script around ueberzug would be easier than trying to make it fit :laughing:

**Comment by jarun** [comment]
I have added the line item. Probably it can have its own separate flow in `preview-tui` once detected as available in the system.
