### ISSUE TITLE
For picture preview, consider including code from derasterize or basicidea

### ISSUE THREAD

**Issue by csdvrx** [jarun/nnn#787]
For users without sixel support, you may want to use block rendition from  https://github.com/csdvrx/derasterize

The license is ISC, and the only dependency is imagemagick for converting to a RGB bitmap.

If the license is a problem, also check out basicidea.c from drea8 that's public domain.

Actually, you may want to use both with a compile time flag defaulting to basicidea for a faster rendition, since many people may prefer speed over quality: FYI, on my laptop rendering egret.jpg in fullscreen takes 0.360s with basicidea vs 1.137 with derasterize.

**Comment by jarun** [comment]
Plugins are indicative. So users can use any tool they like.

We already use [viu](https://github.com/atanunq/viu) in plugin imgview to render images in the terminal. It doesn't have any dependencies like imagemagick either.

**Comment by csdvrx** [comment]
About viu: "It uses the Kitty graphics protocol, if supported. If not, lower half blocks (▄ or \u2584) are displayed insread" (sic)

So it's basically like a worse basicidea, but with libjpeg etc.

I would suggest viu to 1) use derasterize, which has a far better quality 2) besides kitty, to support sixel, which are far more common (mintty, mlterm, xterm, ....)

**Comment by jarun** [comment]
What I wanted to convey is - you can replace viu with your preferred viewer.

**Comment by csdvrx** [comment]
I was thinking about the "out-of-the-box" experience, especially on Windows or other OS where compiling non C code may be more of a hassle: a much better quality than viu is possible using just regular C, as you can see in the demos
![demo](https://user-images.githubusercontent.com/49044530/99497221-3ab9da80-293b-11eb-85c6-daf4beabee54.jpg)

Never mind, I can understand how you prefer to keep nnn codebase as small and to the point as possible, which means not including C code that deals with images.

**Comment by jarun** [comment]
Thank you for your understanding! You are right, nnn is primarily targeted for constrained devices so we try to concentrate on file management more.

**Comment by 0xACE** [comment]
> I was thinking about the "out-of-the-box" experience,

It practically is "out-of-the-box" just change the existing plugins...

I copied the provided plugins more than 1 year ago, and I haven't really had to update any of them at all... Meaning: you can copy the plugins and expect them to work for many years
