### ISSUE TITLE
Spawn new terminal in the current directory

### ISSUE THREAD

**Issue by quantum-booty** [jarun/nnn#790]
Is there a plugin that does that? For example, if I am in ~/bin in nnn and I want to spawn a new terminal in the same directory.

**Comment by jarun** [comment]
Press `!`.

Please read the docs. It's in the help screen -> Misc section.

**Comment by quantum-booty** [comment]
Sorry I meant spawning a new instance of terminal in a new window.

**Comment by jarun** [comment]
You can launch apps from nnn too (with a little config, see Wiki) OR run a GUI cmd as plugin.
