### ISSUE TITLE
Why is "No FPU usage" or "all integer maths" a feature?

### ISSUE THREAD

**Issue by odiferousmint** [jarun/nnn#791]
From SO:

> "Thirty years ago, when hardware floating point was relatively rare, very special-purpose fixed-point (or even scaled integer) arithmetic could provide significant gains in performance over doing software-based floating point, but only if the allowable range of values could be efficiently represented with scaled-integer arithmetic (the original Doom used this approach when no coprocessor was available, such as on my 486sx-25 in 1992 - typing this on an overclocked hyperthreaded Core i7 running at 4.0GHz with a GeForce card that has over 1000 independent floating point compute units, it just seems wrong somehow, although I'm not sure which - the 486, or the i7...)."

> "Floating point is more general purpose due to the range of values it can represent, and with it implemented in hardware on both CPUs and GPUs, it beats fixed point in every way, unless you really need more than 80-bit floating point precision at the expense of huge fixed-point sizes and very slow code."

**Comment by jarun** [comment]
Performance: https://github.com/jarun/nnn/pull/84

And that's a weird way to present a question.

**Comment by odiferousmint** [comment]
> And that's a weird way to present a question.

I would rather call it lazy. I do not have the time to sugarcoat the question. According to that SO answer, it should not be much faster if I interpreted it correctly. Did I not interpret it correctly?

**Comment by jarun** [comment]
We have our benchmarks. It's not our job to validate random answers from websites.

**Comment by jarun** [comment]
To exaggerate on the second sentence, we would rather spend time on #786 than on third-party answers somewhere on the web.
