### ISSUE TITLE
How to navigate file system in bash with nnn?

### ISSUE THREAD

**Issue by svladykin** [jarun/nnn#792]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System:Elementary Linux 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[x] Desktop Environment:Pantheon
[x] Terminal Emulator:Elementary Pantheon Terminal
[x] Shell:bash
[ ] Custom desktop opener (if applicable):
[x] Program options used: none
[x] Configuration options set: none
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. Open **nnn** at the current directory **A**
2. Navigate directory structure with arrows in **nnn** to a directory **B**
3. Hit **q** or **Q** to exit **nnn**
4. Expected that the current dir in bash will be **B** but it is still **A**

As far as I see it is possible to spawn a new shell inside of a current dir with **!**, but I don't want to spawn anything, just want to exit nnn at the current directory in my current bash session. Is that possible?

**Comment by jarun** [comment]
Here you go: https://github.com/jarun/nnn/wiki/Basic-use-cases#configure-cd-on-quit

**Comment by jarun** [comment]
Please read the documentation.
