### ISSUE TITLE
Regarding `coolsize.c` benchmark

### ISSUE THREAD

**Issue by odiferousmint** [jarun/nnn#793]
> We have our benchmarks. It's not our job to validate random answers from websites.

Yeah, but ~50% of execution time is spent in `snprintf`. The difference disappears if you get rid of it. Formatting floats is harder, I give you that.

Without `snprintf`:

```
Timing 500000 iterations
F time 0.008712
I time 0.008002
```

This is not exactly a bug, but one should not jump to conclusions without considering the needs, trade-offs, the context, and so forth. In any case, what are you trying to benchmark there? :)

**Comment by jarun** [comment]
I see we are still better off with the I version.

Anyway, here's something based on actual benchmarks: http://nicolas.limare.net/pro/notes/2014/12/12_arit_speed/#index3h1

**Comment by odiferousmint** [comment]
> I see we are still better off with the I version.

Well, it adds more complexity to the code. If you need it, or if the complexity does not make much of a difference, then sure, why not?

**Comment by jarun** [comment]
Yes, this is years old and stable. I don't even remember the last time I looked into it.

**Comment by odiferousmint** [comment]
Fair enough. :)
