### ISSUE TITLE
nnn on Alpine armv7

### ISSUE THREAD

**Issue by laughingbiscuit** [jarun/nnn#795]
First off- thanks for your work on nnn! It has been my daily driver for a while now.

**Is your feature request related to a problem? Please describe.**

`apk add nnn` fails in Alpine on armv7 (e.g. Raspberry Pi). 

A clear and concise description of what the problem is.

NNN is not available for armv7 [here](https://pkgs.alpinelinux.org/packages?name=nnn&branch=v3.12#)

Building from source works fine.

**A clear and concise description of what you want to happen.**

Adding NNN for arm into the Alpine repos. 

A clear and concise description of any alternative solutions or features you've
considered.

1) I have successfully built from source as a workaround.
2) I have considered learning how to contribute to the Alpine repos myself, but assume you have more experience in this.

**Add any other context or screenshots about the feature request here.**

Happy to help in testing or to attempt this myself if you are unable.

Thanks!

**Comment by jarun** [comment]
Sorry, we do not maintain downstream packages for distros. Not sure of @leovilok maintains it. In anu case, find and contact the `nnn` package maintainer for Alpine Linux.

**Comment by laughingbiscuit** [comment]
Not sure why, but the alpine package maintainer is listed as Jakub Jirutka!

src: https://pkgs.alpinelinux.org/package/edge/community/x86/nnn

**Comment by leovilok** [comment]
I don't maintain any package.

**Comment by jarun** [comment]
Then we can't help with this, sorry @laughingbiscuit
