### ISSUE TITLE
Initiating any plugin shortcut fails with "Abort trap: 6"

### ISSUE THREAD

**Issue by happyguy2000** [jarun/nnn#797]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System:        macOS 10.13.6
[ ] Desktop Environment:
[x] Terminal Emulator:        iterm2
[x] Shell:                               bash
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[x] Issue exists on `nnn` master:        yes

#### Exact steps to reproduce the issue

Follow the Plugin installation and Configuration instructions, then type the ';' shortcut followed by any of the plugin keys, say 'f' for finder or 'v' for imgview, the program terminates with this:
    Abort trap: 6

Debug output:

ln 7686: VERSION=3.5
ln 7714: home=/Users/jbokay
ln 7445: cfgpath=/Users/jbokay/.config
ln 7451: cfgpath=/Users/jbokay/.config/nnn
ln 7477: selpath=/Users/jbokay/.config/nnn/.selection
ln 7721: opener=/usr/bin/open
ln 7802: getenv(envs[ENV_VISUAL])=(null)
ln 7803: getenv(envs[ENV_EDITOR])=vim
ln 7804: editor=vim
ln 7808: pager=less
ln 7812: shell=/bin/bash
ln 7814: getenv("PWD")=/Users/jbokay/Downloads/nnn-3.5
ln 1712: COLORS=256
ln 1713: COLOR_PAIRS=32767
ln 4972: __FUNCTION__=dentfill
ln 5209: ts2.tv_nsec - ts1.tv_nsec=272000
ln 5712: __FUNCTION__=redraw
ln 5727: path=/Users/jbokay/Downloads/nnn-3.5
/tmp/nnndbg (END)

**Comment by jarun** [comment]
We have recently fixed #786. Can you please re-confirm this issue exists on master?

Also, if it's still there, please provide the backtrace details as in that defect.

**Comment by happyguy2000** [comment]
Yes! I just cloned master a moment ago, retested, and it works great now. Please forgive my lack of diligence if the fix predated my bug submission. Anyway, thanks for your great work, and impressively timely response. The skill level here is humbling.

**Comment by jarun** [comment]
Thanks for confirming!
