### ISSUE TITLE
A number missing and text shifted to the left in detail mode if date contains non-English characters

### ISSUE THREAD

**Issue by kacperski1** [jarun/nnn#8]
This reason is just a guess but I can't think of anything other than that - if the file modification date contains non-English letters (in this case, "ź") then the year number is missing a character and everything to the right is shifted by one position (in detail mode).
See here (I marked it with a red thingy):
![image](https://cloud.githubusercontent.com/assets/3217745/25043467/8ad1ffec-2120-11e7-80fe-a3b2089732a2.png)

**Comment by jarun** [comment]
You'll have to wait till we support UTF-8 and this gets fixed along with it.

**Comment by jarun** [comment]
Please test the latest master and confirm if it works.

**Comment by kacperski1** [comment]
No change, unfortunately.

**Comment by jarun** [comment]
OK. If possible can you please archive and share any of those files?

**Comment by jarun** [comment]
I think the problem is with a fixed number of columns. I am using 17. I should probably use numbers for the month as well.

**Comment by jarun** [comment]
I can increase the number of columns... But that would make it look too wide for the regular case. Anyway, I'll show the month name as usual in the detail mode. What do you think?

**Comment by jarun** [comment]
Please test the latest master and confirm. This would be gone for good!

NOTE: I could have done a post-formatting like [ls does](https://www.cl.cam.ac.uk/~mgk25/unicode.html#linux) depending on the locale but that would add unnecessary processing just for the formatting. If someone needs the year by name, he could look up the file details anyway.

**Comment by kacperski1** [comment]
Sorry for the late reply. Works perfectly now 👍

**Comment by jarun** [comment]
No problem! My pleasure! Please award a star on GitHub if you like nnn. 50 stars and we can submit it to Homebrew tonight!

**Comment by kacperski1** [comment]
Done :)

**Comment by jarun** [comment]
Thank you so much!
