### ISSUE TITLE
Feature request: status in git repos

### ISSUE THREAD

**Issue by phinzphinz** [jarun/nnn#802]
Thank you for creating nnn!!! 

**Is your feature request related to a problem? Please describe.**

I would like to see at a glance some info when viewing git repos such as uncommitted files etc.

**Describe the solution you'd like**

It would be nice if this could be indicated via symbols/colors, preferably also with a toggle switch as done for the detail view in nnn.

**Describe alternatives you've considered**

Especially since I want to use nnn as a replacement of nerdtree in vim, it would be nice to have similar behaviour like here:
[Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)

**Additional context**

Screenshot from the abohve nerdtree-git-plugin (see git status symbols on the left part of the image)
![grafik](https://user-images.githubusercontent.com/28191932/99957082-67308500-2d87-11eb-9990-f9cd987f6655.png)

**Comment by jarun** [comment]
We can't scan every dir `nnn` loads to show git status. Non-file-management utility-specific stuff goes to plugins. You can easily run `git status` (or any other utility you prefer) using run cmd as plugin.

**Comment by jarun** [comment]
BTW, I personally use an alias:

    alias gc='git status'

Whenever i want to check the git status of the current dir from `nnn`, I press <kbd>]</kbd> for the cmd prompt and type `gs`.

**Comment by phinzphinz** [comment]
I understand. But then I have to do this manually `]gs` in every directory whenever I am interested and it would boost productivity to automatically have such info shown.

> We can't scan every dir nnn loads to show git status.

One does not have to, one could use tricks to make this possible: For example if git reports `not a git repository (or any parent up to mount point /mnt)`, we can use this info to avoid subsequent git calls in paret dirs. And if we have done status for some dir it covers also subdirs. If we save such info in a timed cache I think it would be doable without a severe performance hit. Maybe even we can scan manually for a .git dir whenever entering a directory to keep the info whether we are in a git dir as a state parameter. One would then use inotify for parent directories to keep this state parameter in sync. 

I do not know the details about the concepts I am talking about here, I only read about those things. Do you think what I propose would be possible to do in theory (despite violating against your minimalistic file manager design concept)?

**Comment by jarun** [comment]
> One does not have to, one could use tricks to make this possible: For example if git reports not a git repository (or any parent up to mount point /mnt), we can use this info to avoid subsequent git calls in paret dirs.

Those are simple to write in theory, not so much in actual code. Plus memorization is needed. I am not sure which productivity you are talking about, but I maintain several projects and I never required to run git status in every git directory every time I make changes, neither the need for a lot of colors (text does it when I need it). So no, this isn't coming to `nnn` as a native feature.

> Do you think what I propose would be possible to do in theory (despite violating against your minimalistic file manager design concept)?

I am not sure how much effort it would take. You can give it a try yourself. I think there are some good file managers those support this. You can pick one of those as well.

**Comment by phinzphinz** [comment]
> I am not sure which productivity you are talking about, but I maintain several projects and I never required to run git status in every git directory every time I make changes, neither the need for a lot of colors (text does it when I need it)

Ok that's true. My need mainly arised because I wanted to (ab)use nnn as a replacement for nerdtree with the mentioned git extension to always use the same program (via https://github.com/mcchrish/nnn.vim). There it makes sense to have that feature to directly see the changed files in a toggleable sidebar (similar to vscode). But I agree that in general, one might not need it.

> I am not sure how much effort it would take. You can give it a try yourself.

I think it would be a lot of work. I have looked into the code of nnn a bit. Unfortunately I am no C programmer, only modern C++ (I never use memset or new/malloc). Maybe I will give it a try after my PhD.

**Comment by phinzphinz** [comment]
> I have looked into the code of nnn a bit.

Just a quick note on a warning:
![grafik](https://user-images.githubusercontent.com/28191932/99973355-f6499700-2d9f-11eb-935b-5fdbb847575e.png)

**Comment by 0xACE** [comment]
just chiming in quickly: For a long time I've considered adding support for custom/scriptable columns in `nnn`, but I never decided how to structure it so I suspended that idea indefinitely, and esentially settled that `nnn` is good as is...

Anyhow don't we support lising files via `stdin`? maybe pipe your processed git status into `nnn` if you insist on using `nnn` but honestly `git` from the terminal is good by itself...

> Just a quick note on a warning:

That line is marked with `// NOLINT` What is your comment to that line?

**Comment by jarun** [comment]
@phinzphinz for a context on the NOLINT, see #550.

**Comment by phinzphinz** [comment]
> Anyhow don't we support lising files via stdin? maybe pipe your processed git status into nnn if you insist on using nnn but honestly git from the terminal is good by itself...

I just started with nnn shortly and will look into this. Thanks

> @phinzphinz for a context on the NOLINT, see #550.

From what I read there the `consider casting to 'unsigned char' first` fix proposal caused a bug. Wow.

> That line is marked with // NOLINT What is your comment to that line?

Sorry I didn't know about the existence of // NOLINT. Apparently to suppress warnings... I thought it was some abbrevation of the devs. My YouCompleteMe somehow still says `[bugprone-signed-char-misuse]` but I didn't generate any `compile_commands.json' from the makefile, so it generates these warnings with general complier flags, maybe that's the reason.

**Comment by jarun** [comment]
> From what I read there the consider casting to 'unsigned char' first fix proposal caused a bug. Wow.

The general rule is - take lint warnings with caution. They may be false or lead to unexpected results.

**Comment by jarun** [comment]
This is now available as user patch `gitstatus`: https://github.com/jarun/nnn/tree/master/patches
