### ISSUE TITLE
Progress for cp/mv not working

### ISSUE THREAD

**Issue by kuntau** [jarun/nnn#805]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Ubuntu Server 20.04.1 LTS
[ ] Desktop Environment:
[x] Terminal Emulator: Tmux
[x] Shell: ZSH
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I'm following the wiki instruction https://github.com/jarun/nnn/wiki/Advanced-use-cases#cp-mv-progress

I have both `cp` & `mv` from advcpmv named as `cpg` & `mvg` in `/usr/local/bin` but still no progress show during copy/move operations

I'm not sure if some other option I need to set.

If I use the program directly eg `/usr/local/bin/mvg -g` the progress show just fine

**Comment by jarun** [comment]
You need to use the program option `-r` as well.

**Comment by kuntau** [comment]
Thank you @jarun 

How do I enable it by default? typing `nnn -r` everytime seems like counter productive.

I know I can set an alias but I prefer the nnn way in case I'm calling it from script/etc

**Comment by jarun** [comment]
You can use `NNN_OPTS` for the binary options.
