### ISSUE TITLE
Support tcsh in quitcd

### ISSUE THREAD

**Issue by dertuxmalwieder** [jarun/nnn#806]
The *QuickStart* document says that I should use the `misc/quitcd` scripts for my shell. Not surprisingly (because many people avoid scripting it), the `tcsh` is not supported. I’d like to keep this feature request here so I can remind myself of looking into it some time in the future.

**Comment by jarun** [comment]
Use quitcd.csh from the same location. That's the closest I got with tcsh. If you can improve it, please raise a PR.

**Comment by jarun** [comment]
I have pushed commit b54fc95c43e7485a3e21ab07b20a370f07eb5cfe to remove the obsolete options as well.
