### ISSUE TITLE
How to on/off preview-tui without leaving nnn?

### ISSUE THREAD

**Issue by akimdi** [jarun/nnn#807]
I want to disable the preview-tui when I don't need it.

**Comment by 0xACE** [comment]
Don't think it is supported, you could implement it yourself.

I'm heading to bed so I can't be of help right now.

An idea I'll leave before I go to bed: imagine if you could toggle the `preview-tui` with 1 keystroke from `nnn` 🥲

**Comment by akimdi** [comment]
> An idea I'll leave before I go to bed: imagine if you could toggle the `preview-tui` with 1 keystroke from `nnn` 🥲

it's my dream 😇

**Comment by jarun** [comment]
I am using preview-tui with xterm. I press `^C` on the preview pane and it will close. I press the plugin shortcut again if I need it.

**Comment by leovilok** [comment]
> it's my dream

@akimdi You have the power to make your dreams come true :

1. make a simple plugin that closes the preview window, e.g. run this:
```sh
echo 'kill $(lsof -tac cat "$NNN_FIFO")' > ~/.config/nnn/plugins/close-preview-tui
chmod +x ~/.config/nnn/plugins/close-preview-tui
```
2. add this plugin to a key
```sh
# open preview window with Alt+p , close it with Alt+c
NNN_PLUG='p:preview-tui;c:close-preview-tui' nnn -a
```

(a prettier version is left as an exercise to the reader :stuck_out_tongue: )

**Comment by akimdi** [comment]
> ```shell
> NNN_PLUG='p:preview-tui;c:close-preview-tui' nnn -a
> ```

works fine but not always. 
Thanks :)

**Comment by toddyamakawa** [comment]
I guess the solution would be to create a `toggle-tui-preview` command. All it would have to do is first check whether or not a preview pane is open. If it is open, close it. If it isn't open, open it.

**Comment by luukvbaal** [comment]
You can now toggle `preview-tui(-ext)` with the same key due to
https://github.com/jarun/nnn/blob/b97e2d02ea92c390977a94810b3f0afc076b81a3/plugins/preview-tui-ext#L150
