### ISSUE TITLE
Files with spaces problem, nnn spawns the default browser once the earlier opened file is closed

### ISSUE THREAD

**Issue by denis-khizhniak** [jarun/nnn#808]
#### Environment details (Put `x` in the checkbox along with the information)

[ ] Operating System: Arch Linux
[ ] Desktop Environment: N/A
[ ] Terminal Emulator: urxvt
[ ] Shell: bash
[ ] Custom desktop opener (if applicable): N/A
[ ] Program options used: -xra, also tried without any
[ ] Configuration options set: NNN_BMS, NNN_COLORS, NNN_TRASH, NNN_PLUG, NNN_FALLBACK_OPENER=xdg-open, NNN_ARCHIVE
[ ] Issue exists on `nnn` master: yes

#### Exact steps to reproduce the issue

Dear devs, 

It happens when I open some file (I don't know the full range of problematic ones), for example, a .jpg image the file is opened properly in the image viewer (sxiv in my case) and then close it the same file opens in my default browser which is kinda annoying. 

I tried with the bare nnn without a wrapper script (without any command-line options) and the issue is still there.

**UPD**:
I found another file which opens and closes fine and I figured out the difference that causes the issue. The problematic file contains spaces. Could you please fix this as I would still like to name some of my files using spaces.

**Comment by 0xACE** [comment]
I can't replicate.

Which version are you using?

The other day `python` broke my programs as it always does every 2-4 sub-releases... In my case it broke a couple of my python scripts resulting in `xdg-open` falling back to the `browser`...

**Comment by denis-khizhniak** [comment]
You are right, I've just tried to open from the terminal using xdg-open directly and it behaved the same. Not the nnn issue. I'm closing this bug.
