### ISSUE TITLE
How to add path to zoxide autojump database when using nnn?

### ISSUE THREAD

**Issue by quantum-booty** [jarun/nnn#809]
Currently for the autojump plugin, a path is only added to the zoxide database when I do cds in the terminal shell, and none of the paths in nnn are remembered.

**Comment by 0xACE** [comment]
no idea what `zoxide` is, but it sounds to me that you should be adding a hook into your enviornment to handle this issue.

**Comment by jarun** [comment]
That's corrent. There is no hook in nnn to add a path to a database everytime a dir changes.

**Comment by akimdi** [comment]
@quantum-booty 
Zoxide is very popular. You can do it
`cd dir`
`zoxide add` (or just `z`)
But it seems to me there is a similar plugin, maybe it will suit you.
[https://github.com/jarun/nnn/blob/master/plugins/fzcd](url)
