### ISSUE TITLE
How to overwrite all files in one command?

### ISSUE THREAD

**Issue by midexe6380** [jarun/nnn#810]
![16072943440](https://user-images.githubusercontent.com/65507149/101295280-b5d12b00-382d-11eb-9b3d-d4f305c31708.png)

**Comment by 0xACE** [comment]
before copying/moving/deleting the file it will be asking if it should use `force`, prompting yes there should delete all of the files

**Comment by midexe6380** [comment]
@0xACE   I have no option `force`. How do I activate this option?

**Comment by jarun** [comment]
In the following prompt, press `y`:

    rm -rf 4 file(s)? [Esc cancels]

**Comment by midexe6380** [comment]
@jarun I don't understand you. I can't do that. Help me, please. Here's what I get
[https://youtu.be/eREn8KCeTR8](url)

**Comment by jarun** [comment]
Ok. I got it. We always use interactive mode for cp and mv to be on the safer side. To overwrite without asking you'll have to change the code.

**Comment by midexe6380** [comment]
LOL 😅 you use cp fork with a progress bar. It's not safe at all.

**Comment by jarun** [comment]
It's optional.

**Comment by 0xACE** [comment]
@midexe6380 you are suppose to receive a prompt

`rm -rf current file? [Esc cancels]`

or similiar when you do writing operations onto disks... Are you using `master`?

**Comment by midexe6380** [comment]
@0xACE 


> Are you using `master`?

Yes.



> you are suppose to receive a prompt

I get  [https://youtu.be/eREn8KCeTR8](https://youtu.be/eREn8KCeTR8l)

I thought what could be done ```ya``` (yes all) and replace all files.

**Comment by midexe6380** [comment]
> ```
> rm -rf 4 file(s)? [Esc cancels]
> ```

where did you find this promt?
It feels like we are using different versions of NNN.

**Comment by 0xACE** [comment]
> I get [https://youtu.be/eREn8KCeTR8](https://youtu.be/eREn8KCeTR8l)

I'm not familiar with the `master` ui so I can't even tell what you are doing in that video

> where did you find this promt?
> It feels like we are using different versions of NNN.

That is correct I'm running an outdated personal build of `nnn`

I just tried it out, with copy operation and in my `nnn` it doesn't ask to use force... maybe:

> Ok. I got it. We always use interactive mode for cp and mv to be on the safer side. To overwrite without asking you'll have to change the code.

This is correct and my memory is serving me wrong... (maybe `nnn` asked to use force in the past? i can't remember)

**Comment by midexe6380** [comment]
Probably @jarun removed this great feature.
Don't you want to merge with the master?
I think that many people will be interested in this.

**Comment by jarun** [comment]
We have always used cp and mv in interactive mode as far as I remember. Only rm operations prompt to be forced.

**Comment by jarun** [comment]
Anyway, @midexe6380 this was never there and it is not _useful_ just because it doesn't prompt. It is _dangerous_ to overwrite without confirmation **in general** and hence it was kept as interactive from the beginning. I have already confirmed that in https://github.com/jarun/nnn/issues/810#issuecomment-742974969.

**Comment by jarun** [comment]
if you want to overwrite all the time. replace the `-i` with `-f` in [code](https://github.com/jarun/nnn/blob/fc3a247c317ca414eb5ec23bb24da6735cd91f77/src/nnn.c#L661-L667).

**Comment by midexe6380** [comment]
@jarun 
@0xACE 
Perhaps I put it wrong.
I meant to make a function like ```Apply this action to all files and folders```
Maybe skip or maybe replace.
[https://youtu.be/UohVzLYhlXk](https://youtu.be/UohVzLYhlXk)

**Comment by 0xACE** [comment]
> I meant to make a function like `Apply this action to all files and folders`
> Maybe skip or maybe replace.

Doesn't exist. You could try to make a script for it... For now I don't have a solution for this.
