### ISSUE TITLE
Select matching files

### ISSUE THREAD

**Issue by balazsbotond** [jarun/nnn#811]
First of all, thank you for developing nnn, it's absolutely amazing and no other file managers compare to it imho.

I read the built-in help and most of the wiki but I can't find how to select files matching a glob pattern like "*.txt". How can I do this with nnn?

**Comment by jarun** [comment]
`nnn` supports string and regex matches.

For your case you'll have to use regex patterns: https://github.com/jarun/nnn/wiki/concepts#common-regex-use-cases

**Comment by balazsbotond** [comment]
Thank you!
