### ISSUE TITLE
Selection doesn't get cleared/shown when another action is performed

### ISSUE THREAD

**Issue by rottencandy** [jarun/nnn#812]
If one or more items are selected, and an action is performed(to files not in selection), the selection count is displayed, but the items are no longer selected.

Selecting the previously selected items then increments the count, and causes errors when an action is performed on them.

#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Fedora 33
[ ] Desktop Environment:
[x] Terminal Emulator: st
[x] Shell: bash
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Step 1:
```sh
touch tempfile{1..4}
```

Step 2:
Start nnn

Step 3:
Select files `tempfile1`, `tempfile2`, and `tempfile3` using `^J`

Step 4:
Delete `tempfile4` using `x`

The selection counter at bottom still shows `3`, but the files aren't selected.
If we select the files again, the counter increments.

If we try to move the selected files to another directory or delete them, an error is shown.

**Comment by jarun** [comment]
I have made the change to clear the selection when a single file is deleted. Please test and confirm the patch works as expected.

**Comment by rottencandy** [comment]
Works as expected. Thank you.

**Comment by jarun** [comment]
Thank you for reporting the issue.
