### ISSUE TITLE
Is it possible to make multiple files executable?

### ISSUE THREAD

**Issue by akimdi** [jarun/nnn#813]
Is it possible to make multiple files executable? For example, I am mark multiple files.
```Space```
```Space```
```Space```
```Shift+8```
And all the files that I selected became executable.
It doesn't work like that now.

**Comment by jarun** [comment]
Please write a small plugin that takes selection and does that. There are many plugins you can use as an example.

**Comment by jarun** [comment]
@akimdi I have added the plugin to toggle exe mode for a selection.

**Comment by akimdi** [comment]
Thank you very much. NNN is the best file manager in the galaxy 💪
@jarun  You're doing amazing things.

**Comment by akimdi** [comment]
@jarun  plugin ```togglex``` doesn't work if there are spaces in the file name.

**Comment by jarun** [comment]
Fixed at commit 9946b371777f36d57306da4503a8d73776595a7a.
