### ISSUE TITLE
[Feature request] sftp support

### ISSUE THREAD

**Issue by Soundtoxin** [jarun/nnn#814]
**Is your feature request related to a problem? Please describe.**

I want a way to use nnn's UI for quick one-off remote file transfers, where I don't want to mount anything with sshfs or similar.

**Describe the solution you'd like**

I would like nnn to support sftp and let me switch views between local and remote sides, then select stuff to send either way. A bit like Filezilla.

**Comment by jarun** [comment]
> I don't want to mount anything

> switch views between local and remote sides

Mount in a different context and you'll get both the views.

If you don't want the views, it's just running an sftp command. Use the plugin framework.

You can also automate [lftp transfers](https://github.com/jarun/nnn/wiki/Advanced-use-cases#working-with-lftp) to some extent.

In any case, we will not be able to spend any bandwidth on this as the mount option works best for us.
