### ISSUE TITLE
Hover jumps to top, when deleting hovered and selected file

### ISSUE THREAD

**Issue by dosimple** [jarun/nnn#815]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Debian Testing
- [x] Desktop Environment: i3
- [x] Terminal Emulator: Gnome Terminal
- [x] Program options used: NNN_OPTS=RSou
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

* Select (`spacebar`) a file and hover (`up`) it
* Delete file: `x`, `y`
* Hover jumps to top

Expected behaviour: Hover should jump to next file.

**Comment by jarun** [comment]
This is the expected behaviour with selection delete (against delete hovered file). Selection can be for multiple files in any order and from any directory and we want to keep the implementation simple.
