### ISSUE TITLE
Moving the hover up and down is very slow in gvfs-fuse mounted directory

### ISSUE THREAD

**Issue by dosimple** [jarun/nnn#817]
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Debian Testing
- [x] Desktop Environment: i3
- [x] Terminal Emulator: Gnome Terminal
- [x] Program options used: NNN_OPTS=RSou

#### Exact steps to reproduce the issue

- Mount webdav using `gio mount davs://...`
- Navigate to the `/run/user/xxxx/gvfs/...`
- Move the hover up and down in the directory

Note: Using gio for io may be a good idea in general?

**Comment by jarun** [comment]
For manual mounts, nnn doesn't care about the underlying filesystem and driver. If you want to use another protocol to mount for better performance feel free to use it.
