### ISSUE TITLE
Kitty terminal preview-tui plugin not workin

### ISSUE THREAD

**Issue by nitishvelu** [jarun/nnn#819]
i get this message when i use the plugin 
   ` The layout splits is unknown or disabled
    vsplit is not a valid value for the --location option. Valid values are: neighbor, first, last`

i followed all the instructions on the wiki
apart from that really enjoying nnn

**Comment by jarun** [comment]
Version details missing. We cannot work with this description. Please read the instructions in the defect template and provide the required detail to reopen the issue. We need kitty version too.
