### ISSUE TITLE
Multiline nnn config export

### ISSUE THREAD

**Issue by mortezadadgar** [jarun/nnn#820]
I would like NNN_PLUG or NNN_BMS to be like this so it would be easier to maintain 

```
export NNN_PLUG='
u:getplugs; \
b:bookmarks; \
z:fzcd; \
o:fzopen; \
X:_chmod +x $nnn; \
D:_dust -rb $nnn'
```

but nnn refuses to open up the plugin menu

**Comment by jarun** [comment]
> but nnn refuses to open up the plugin menu

Yes, that can't be changed anymore without breaking the existing config of current users.

**Comment by toddyamakawa** [comment]
Are you just trying to split your plugin commands on multiple lines for readability? Here's how I do it:
https://github.com/toddyamakawa/bin/blob/master/%2Cnnn#L31-L39

**Comment by jarun** [comment]
@tanyaionova can you please add this to the wiki somewhere?

**Comment by tanyaionova** [comment]
@jarun I guess you wanted to mention (at) toddyamakawa

**Comment by toddyamakawa** [comment]
Looks like it's already on the plugin README:

https://github.com/jarun/nnn/blame/master/plugins/README.md#L98

**Comment by jarun** [comment]
It would be good to have the bookmark example in the Wiki config section.
