### ISSUE TITLE
advcpmv / line 1: cpg: not found

### ISSUE THREAD

**Issue by ralphee** [jarun/nnn#823]
when trying to copy file I get `line 1: cpg: command not found`
.zshenv
export NNN_OPTS="UcExr"

**Comment by KlzXS** [comment]
You need to install advcpmv as per https://github.com/jarun/advcpmv.

**Comment by ralphee** [comment]
> You need to install advcpmv as per https://github.com/jarun/advcpmv.

pkg was in the [AUR](https://aur.archlinux.org/packages/advcpmvl)

**Comment by KlzXS** [comment]
I just installed the package from AUR. There is no `cpg` command, the AUR maintainer decided to put the binaries as `advcp` and `advmv` instead of `cpg` and `mvg`.

I would suggest making symlinks for the binaries (`/usr/bin/cpg -> /usr/bin/advcp`).

**Comment by ralphee** [comment]
> I just installed the package from AUR. There is no `cpg` command, the AUR maintainer decided to put the binaries as `advcp` and `advmv` instead of `cpg` and `mvg`.
> 
> I would suggest making symlinks for the binaries (`/usr/bin/cpg -> /usr/bin/advcp`).

yeah no worries....I figured that as soon as i read the instructions /o\

**Comment by KlzXS** [comment]
If you are feeling generous maybe you could contact the maintainer and tell him to also put `cpg` and `mvg` in. It seems this is a fairly new addition to the AUR (Oct 13) with the latest change submitted a week ago.

**Comment by ralphee** [comment]
> If you are feeling generous maybe you could contact the maintainer and tell him to also put `cpg` and `mvg` in. It seems this is a fairly new addition to the AUR (Oct 13) with the latest change submitted a week ago.

already on the case ;)
