### ISSUE TITLE
Disable multiple contexts

### ISSUE THREAD

**Issue by matthewgrossman** [jarun/nnn#824]
**Is your feature request related to a problem? Please describe.**

My usecase for `nnn` takes place inside a multiplexer (neovim/tmux) and I have separate flows setup for handling 2+ "workspaces". I don't need the default 4-contexts provided by nnn and would like to disable them. The advantages I see here include:
- gain a bit of screen real estate
- free up `<Tab>` to rebind to something else

**Describe the solution you'd like**

Ideally, I'd be able to pass a CLI flag to `nnn` which specifies I don't need any contexts (or specify how many I want, which would be `1`)

**Describe alternatives you've considered**

While not ideal, I see [other solutions](https://github.com/jarun/nnn/pull/613) from GH searching that involve passing in this info as compile-time flags

**Additional context**

n/a

**Consider contributing**

if we think its doable, I could take a crack at it. Raising issue first to see if it's a direction the project would even want

**Comment by 0xACE** [comment]
taking a wild guess:
But i think the top row containing "workspace" numbers are sort of hardcoded along with the `CWD`. Iirc the lowest you can set `MAX_CONTEXTS` or w/e it's called is 2.

I would say you are reaching far into the code for little to no results...

**Comment by matthewgrossman** [comment]
Agreed, it's not worth the effort for the minor utility of the feature. I was hoping I missed some config and it would be as easy as [making new tabs in `ranger`](https://gist.github.com/heroheman/aba73e47443340c35526755ef79647eb#tabs) or using single-panel mode in `mc`


closing
