### ISSUE TITLE
Couldn't install the plugins

### ISSUE THREAD

**Issue by jdarias** [jarun/nnn#826]
`nnn` comes with excellent documentation (including a Troubleshooting section). If you have a _How to do x_ question, it may have already been answered. Wiki: https://github.com/jarun/nnn/wiki

If it looks like a local environment issue, please try to debug yourself. Debugging local setup issues is not our top priority.

If you are looking for a new feature or program option, ensure you have the correct version with the feature installed. Refer to the release notes to confirm.

Before opening an issue, please try to reproduce on latest master. The bug you noticed might have already been fixed.

Useful links:

- compile `nnn` from source - https://github.com/jarun/nnn/wiki/Usage#from-source
- debugging `nnn` - https://github.com/jarun/nnn/wiki/Developer-guides#debugging-nnn

If the issue can be reproduced on master, log it.

Please provide the environment details. **If that's missing, the issue will be closed without any cited reason.**

If we need more information and there is no communication from the bug reporter within 7 days from the date of request, we will close the issue. If you have relevant information, resume discussion any time.

--- PLEASE DELETE THIS LINE AND EVERYTHING ABOVE ---

#### Environment details (Put `x` in the checkbox along with the information)

[ x] Operating System: Raspberry pi os
[ ] Desktop Environment:
[ ] Terminal Emulator:
[ ] Shell:
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Tried to install the plugins as instructed with this:

curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh

Got this result:

nnn: invalid option -- 'V'
tar (child): nnn-usage\: nnn [-b key] [-C] [-e] [-i] [-l]\n           [-p file] [-S] [-v] [-h] [PATH]\n\nThe missing terminal file manager for X.\n\npositional args\:\n  PATH   start dir [default\: current dir]\n\noptional args\:\n -b key  bookmark key to open\n -C      disable directory color\n -e      use exiftool instead of mediainfo\n -i      start in navigate-as-you-type mode\n -l      start in light mode\n -p file copy selection to file (stdout if '-')\n -S      start in disk usage analyser mode\n -v      show program version\n -h      show this help\n\nVersion\: 2.2\nLicense\: BSD 2-Clause\nWebpage\: https\://github.com/jarun/nnn.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: Child returned status 2
tar: Error is not recoverable: exiting now
sh: 67: cd: can't cd to nnn-usage: nnn [-b key] [-C] [-e] [-i] [-l]
           [-p file] [-S] [-v] [-h] [PATH]

The missing terminal file manager for X.

positional args:
  PATH   start dir [default: current dir]

optional args:
 -b key  bookmark key to open
 -C      disable directory color
 -e      use exiftool instead of mediainfo
 -i      start in navigate-as-you-type mode
 -l      start in light mode
 -p file copy selection to file (stdout if '-')
 -S      start in disk usage analyser mode
 -v      show program version
 -h      show this help

Version: 2.2
License: BSD 2-Clause
Webpage: https://github.com/jarun/nnn/plugins

**Comment by jarun** [comment]
v2.2 is a very old version of `nnn`. The latest is v3.5. Please get the latest version.

**Comment by jarun** [comment]
Adding @szlin if you need help with how to get the latest on Raspberry Pi OS which is probably a Debian variant. Raspbian testing has the latest v3.5.

**Comment by szlin** [comment]
Hi,

The "bullseye" archive contained the lastest v3.5; you can upgrade Raspberry Pi OS by editing the file /etc/apt/sources.list, 

```
deb http://archive.raspbian.org/raspbian bullseye main contrib non-free
deb-src http://archive.raspbian.org/raspbian bullseye main contrib non-free
```

and issuing below commands

- apt update
- apt upgrade
- apt full-upgrade
