### ISSUE TITLE
Question: nnn over Eternal Terminal in iTerm2 using tmux -CC

### ISSUE THREAD

**Issue by figgis** [jarun/nnn#831]
As the title says, I'm running nnn over Eternal Terminal on my mac to connect to an ubuntu 18.04 sever. Everything is handled thorugh iTerm2 which starts `tmux -CC` which means that all the normal iTerm2 commands to create tabs and split panes works as natively, hiding the tmux-commands.

When running any plugin e.g `mediainf`, a widow/pane flashes for 1/10 of a second and then disappear, making it impossible to see the result. 

I just want to check if nnn is supposed to work using iTerm2 and tmux -CC on the remote host or if this isn't supported.

Using version 3.5. 
TERM=xterm-256color

**Comment by jarun** [comment]
This may not be related to iTerm2 and tmux.

Can you please see: https://github.com/jarun/nnn/wiki/Troubleshooting#help-not-showing

A better way to debug would be to write a plugin that creates a file or something to confirm if the plugin was run. Also, after running the plugin press <kbd>!</kbd> and check if there's some indicative msg in the shell.

**Comment by figgis** [comment]
Thanks. I realized that my `$PAGER` env-variable was unset. After fixing that I get the output in the same window as nnn. Some other plugins till flash for me but I'll debug them on my own :-)
Thanks for the rapid reply.

**Comment by jarun** [comment]
No problem!
