### ISSUE TITLE
Create relative symlink

### ISSUE THREAD

**Issue by hXtreme** [jarun/nnn#838]
**Is your feature request related to a problem? Please describe.**

Currently nnn only creates symlinks with absolute paths, this is not the best thing for removable devices.

**Describe the solution you'd like**

Give the option to create a relative symlink.

Say we want to create a symlink to file A on a removable device with path "/path/to/device/on/machine1/A" to another place on the same device with path "/path/to/device/on/machine1/B". It would be nice to create a symlink that points to path "./A" instead of the absolute path of A on a particular machine.

**Comment by jarun** [comment]
Please feel free to raise a PR.

**Comment by jarun** [comment]
Not using relative paths was a conscious decision with the trivial problem of navigating into long paths into account. It's always possible to organize things breadth-wise then depth-wise. In case you still want it, I believe you'll have to have a minor personal hack for the utility-specific parameters.
