### ISSUE TITLE
Using icons-in-terminal in byobu 

### ISSUE THREAD

**Issue by benoit-combes** [jarun/nnn#841]
Dear nnn Master,

first thanks for developing this gem.

I tried to use the icons-in-terminal option (built from sources). It works like a charm on my terminal (alacritty). However, in practice, my working environment relies on byobu and I did not manage to render the icons when I embend byobu in alacritty. 
I tried to copy the font in (similarly to what proposed for termux in the wiki  (this is maybe a bit naive .... not so confortable with such system related stuffs... ) :
```
~/.byobu/font.ttf
 ```
When running, nnn in this env, it works fine but the icons are not displayed.

If you have any ideas on how to fix this, I will be very glad to know it.

Best regards,
B.

#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: ubuntu
[x] Desktop Environment: dwm
[x] Terminal Emulator: byobu/alacritty
[x] Shell:bash
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[ ] Issue exists on `nnn` master

**Comment by jarun** [comment]
Probably something similar to tmux troubleshooting.

See if anything here helps: https://github.com/jarun/nnn/wiki/Troubleshooting#tmux-configuration

**Comment by benoit-combes** [comment]
Thanks a lot, this indeed solves my issue.
