### ISSUE TITLE
Pressing 'l' (moving right) on a file breaks nnn and shell

### ISSUE THREAD

**Issue by oceanwhit** [jarun/nnn#843]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Artix Linux
[x] Desktop Environment: N/A, xorg-server
[x] Terminal Emulator: alacritty
[x] Shell: sh
[x] Custom desktop opener (if applicable): N/A
[x] Program options used: N/A
[x] Configuration options set: N/A
[x] Issue exists on `nnn` master: yes

#### Exact steps to reproduce the issue
Start nnn.
Hover over a non-directory file.
Press 'l'
Navigation becomes difficult.

This seems to happen when hovering over most files, but not all.
Pressing 'l' multiple times worsens the problem.
This issue does not occur when running nnn in a tty.

**Comment by jarun** [comment]
Your opener is the problem and this may be happening while opening text files.

Please refer to the troubleshooting section: https://github.com/jarun/nnn/wiki/Troubleshooting#wrong-file-opener

**Comment by oceanwhit** [comment]
Thank you.
