### ISSUE TITLE
Most filetype colors are not displayed in a TTY

### ISSUE THREAD

**Issue by itaranto** [jarun/nnn#844]
#### Environment details

- [x] Operating System: Arch Linux
- [x] Desktop Environment: Sway and i3
- [x] Terminal Emulator: Alacritty
- [x] Shell: Fish and Bash
- [ ] Custom desktop opener (if applicable):
- [x] Program options used: None
- [x] Configuration options set: None
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
1. Run `nnn` from a graphical terminal emulator (like Alacritty)
2. Run `nnn` from a TTY
2. Observe the different filetype colors

Result:  
Most filetype colors are not displayed when running in a TTY.
The exceptions are directories (blue) and sym-links (grey).

Tested using version 3.5.

**Comment by jarun** [comment]
The tty supports only 8-bit colors. `nnn` auto-detects and adjusts to that.
