### ISSUE TITLE
How to create a custom plugin from an existing one?

### ISSUE THREAD

**Issue by ThomasBucaioni** [jarun/nnn#845]
Starting from plugin **pdfview**, I made a second one using `mutool` called **mypdfview** (to give a try in keeping both converters). But it doesn't run when calling the plugin, actually, the shortcut doesn't show when pressing `;`

Would it be possible to call plugins from the directory `~/.config/nnn/plugins`?

Maybe it takes to recompile **nnn** with a new list of plugins?

**Comment by KlzXS** [comment]
To add a plugin simply add it to the directory you mentioned (`~/.config/nnn/plugins`) and update the `NNN_PLUG` environment variable.

You can find all the needed info in the [README for plugins](https://github.com/jarun/nnn/blob/master/plugins/README.md).

**Comment by 0xACE** [comment]
also maybe your `mypdfview` needs `chmod +x mypdfview` to be `eXectuable`

without details about the script in particular, i can't tell what's wrong.

**Comment by ThomasBucaioni** [comment]
Maybe I forgot to source my .zshrc, today it all goes well... Otherwise, I had checked the directory and the execution rights. Here is the script (it's almost the original one...):
```
#!/usr/bin/env sh
# Shell: POSIX compliant
# Author: Arun Prakash Jana
if ! [ -z "$1" ]; then
    if [ "$(head -c 4 "$1")" = "%PDF" ]; then
        # Convert using mutool
        file=`basename "$1"`
        txt=/tmp/"$file".txt
        mutool convert -o "$txt" "$1"
        eval $PAGER $txt
        rm "$txt"
    fi
fi
```
Thanks for your help

**Comment by KlzXS** [comment]
> `eval $PAGER $txt`

`"$PAGER" "$txt"`

FTFY don't forget your quotes. And the exec is unnecessary.

**Comment by ThomasBucaioni** [comment]
Cheers, it's corrected

**Comment by jarun** [comment]
In general, it's a good idea to run shellcheck on new scripts.

**Comment by ThomasBucaioni** [comment]
Many times I've heard it but never do... Here is a link, maybe now I'll remember: https://www.shellcheck.net/
