### ISSUE TITLE
Bookmarks - "Directory not accessible"

### ISSUE THREAD

**Issue by dboneham** [jarun/nnn#847]
After pressing "b" to bring up the bookmark keys, and then pressing any of the keys, I get the error "Directory not accessible".

I have the following setting in my ~/.profile, which is sourced in my ~/.zshrc:
export NNN_BMS='d:~/Documents;u:/home/user/Cam Uploads;D:~/Downloads/'

**Comment by KlzXS** [comment]
Your formatting's all messed up, be careful with `~`.

I assume you are using this line from the examples: `export NNN_BMS='d:~/Documents;u:/home/user/Cam Uploads;D:~/Downloads/'`? Are you sure those directories exist on your filesystem?

If they don't exist they can't be accessed :)

**Comment by jarun** [comment]
Please visit the wiki for example and fix the paths.

**Comment by dboneham** [comment]
Hi*,

Some of the bookmarks would have worked. But that was not the issue.

I think the underlying problem was that my "export" statement did not
use double inverted commas. This is what I have now - export
NNN_BMS="m:$HOME/.marks/". Which works. (It addresses a hidden directory
of symlinks, which have been - and continue to be - populated by use of
a zsh plugin called "jump").

Many thanks for your help.

Best wishes,

-- *David*
