### ISSUE TITLE
There's no mouse support

### ISSUE THREAD

**Issue by woky** [jarun/nnn#85]
Just for selecting entries. Even Vim and midnight commander has it. :-)

**Comment by jarun** [comment]
Please go through the [design considerations](https://github.com/jarun/nnn/wiki/nnn-design-considerations). A central idea behind `nnn` is complete freedom from the mouse. Also, it's not vim or mc.

**Comment by woky** [comment]
That's not freedom. That's a keyboard prison.

**Comment by jarun** [comment]
Not really. It's open, GPLv3 and you have the freedom to fork and implement it for yourself as long as you show some respect for what I have done and give me due credit (which doesn't seem to be the case at this point).

You come here and share rhetorics on freedom but in reality you are limited by your dependency on others to provide you stuff you would like to have, for free. Please give it a thought.
