### ISSUE TITLE
Binary for mingw/msys

### ISSUE THREAD

**Issue by AP2008** [jarun/nnn#850]
I tried compiling nnn in mingw. But I got lots of errors (missing files). I would really like to use nnn. Is it possible to provide binaries?

**Comment by KlzXS** [comment]
Have you installed all the [dependencies](https://github.com/jarun/nnn/wiki/Usage#dependencies)? You can try [compiling with cygwin](https://github.com/jarun/nnn/wiki/Developer-guides#compile-on-cygwin).

**Comment by AP2008** [comment]
I installed all the dependencies. I don't want to install cygwin.

**Comment by jarun** [comment]
See #784 as well.

**Comment by AP2008** [comment]
I saw #784 before trying to compile. I also did not find any MSYS2 package for nnn in the official MSYS2 package repo.

**Comment by KlzXS** [comment]
> But I got lots of errors (missing files)

This is quite non-specific but I just remembered one thing. Did you make sure you installed ncursesw (wide character support)?

And if you did check to see what the headers for it are called. I know that on some systems (eg. Ubuntu) you need to include not `ncurses.h` but something a bit different in `src/nnn.c`.

I'd love to give more precise info but it's quite late here.

**Comment by jarun** [comment]
This seems more of a downstream issue. Please get in touch with the maintainers of msys.
