### ISSUE TITLE
Make `NNN_PIPE` available in subshell

### ISSUE THREAD

**Issue by z0rc** [jarun/nnn#860]
Previously at https://github.com/jarun/nnn/issues/380.

**Is your feature request related to a problem? Please describe.**

In order to channel pwd changes from subshell to nnn, there has to be a socket available for this. Consider the following zsh snippet:
```zsh
# Let nnn know about pwd changes
if [[ -v NNNLVL ]]; then
    _nnn_chpwd () {
        print "0c${PWD}" > "${NNN_PIPE}" !&
    }
    add-zsh-hook chpwd _nnn_chpwd
fi
```

**Describe the solution you'd like**

Right now `NNN_PIPE` available only when calling plugins. For better shell integrations I'd like to have the same socket available for subshell spawned by <kbd>!</kbd>.

**Describe alternatives you've considered**

`NNN_FIFO` isn't suitable for sending updates to nnn.

**Comment by jarun** [comment]
@KlzXS can you please take a look?

**Comment by KlzXS** [comment]
I'm sorry, I just got to this. I'll take a look it at it.

**Comment by jarun** [comment]
I could achieve this easily with `bash`.

Added the following in `.bashrc`:

```bash
finish()
{
    if ! [ -z "$NNN_PIPE" ]; then
        echo $PWD
        printf "%s\0" "0c${PWD}" > "${NNN_PIPE}" !&
    fi
}

trap finish EXIT
```

Added a plugin named `shell` and assigned the plugin key <kbd>s</kbd>:

```sh
#!/usr/bin/env sh

# Description: Start an interactive bash shell.
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

bash -i
```

You can try with `zsh` and share if it works.

Closing the issue as we have a solution that does the same thing.

**Comment by jarun** [comment]
And if you want to go the _run cmd as plugin_ way:

`s:_bash -i*`
