### ISSUE TITLE
hotkey suggestion - switch between shell and nnn same key

### ISSUE THREAD

**Issue by DoTheEvo** [jarun/nnn#861]
At the moment I am doing "shift+1" = ! to get to shell, then it is ctrl+d to get back.

Since ^d is not used in nnn, would be kinda cool if it had same functionality as !

Switch there and back becomes much more seamless, effortless ... you feel like you are not even leaving.

**Comment by 0xACE** [comment]
I'd vote no, as `ctrl+d` is commonly defined as something else in terminal environments... you could compile it for your own build...

**Comment by KlzXS** [comment]
> Since ^d is not used in nnn

`^U` and `^D` are used for scrolling.
You can also use `^]` to access the subshell.

You can always change that locally and recompile.

**Comment by DoTheEvo** [comment]
K, just curious. What is your guys workflow getting in and back from shell?

**Comment by 0xACE** [comment]
I commonly use `!`, and `^G` to cd into the directory, but I'm not sure if this is a old config thing, i wouldn't recommend `^G` if you have the option to control it today... and i basically have a `alias n=nnn` (my commandline options decided at compile time). Additionally i have a bash function `c` to jump to `nnn` bookmarks: `c d` jumps to my download folder based on `NNN_BMS`

Other than that I have `"` and `%` which split tmux panes in the current directory, they spawn in shell rather than `nnn`. But sometimes i wonder if it should spawn another `nnn` instead, seeing as I haven't commonly used multiple sessions of `nnn` together I never made the move...

**Comment by KlzXS** [comment]
Like @0xACE said `!` to get in and an alias to shorten the command. I use `^D` to get out but nesting `nnn` several layers deep is not uncommon to me. At the end you just close the terminal and you're done.

I could maybe avoid some of the nesting with fancy cd-on-quit but I've grown acustomed to just doing it that way. Using `nnn` with tmux and nesting is something I can't be bothered to set up so I don't do that, but it should be possible.

**Comment by IulianDita** [comment]
> Other than that I have `"` and `%` which split tmux panes in the current directory, they spawn in shell rather than `nnn`.

How would I do just that, when using `"` and `%` to split tmux with a shell pane in the current nnn directory? I remapped the original `"` and `%` so they are unused now.

**Comment by 0xACE** [comment]
It hasn't been applied upstream. this patch is probably not "proper" but meh it works...

```
diff --git a/src/nnn.c b/src/nnn.c
index d6269ac..574724d 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -7136,6 +7187,25 @@ nochange:
 			}
 
 			return EXIT_FAILURE;
+		case SEL_TWIND: // fall through
+		case SEL_TVERT: // fall through
+		case SEL_THORZ:
+			if (!getenv("TMUX"))
+				break;
+			if (sel == SEL_TVERT) {
+				xstrsncpy(g_buf,"-hc", 4);
+				xstrsncpy(g_buf+3, path, PATH_MAX);
+			} else {
+				xstrsncpy(g_buf,"-c", 3);
+				xstrsncpy(g_buf+2, path, PATH_MAX);
+			}
+			if (sel == SEL_TWIND)
+				spawn("tmux", "new-window", g_buf, F_NORMAL);
+			else
+				spawn("tmux", "split-window", g_buf, F_MULTI | F_NORMAL);
+			break;
 		default:
 			if (xlines != LINES || xcols != COLS)
 				continue;
diff --git a/src/nnn.h b/src/nnn.h
index 1e1e3dd..129d7b5 100644
--- a/src/nnn.h
+++ b/src/nnn.h
@@ -116,6 +117,10 @@ enum action {
 #ifndef NOMOUSE
 	SEL_CLICK,
 #endif
+	SEL_ZEFAST,
+	SEL_TVERT,
+	SEL_THORZ,
+	SEL_TWIND
 };
 
@@ -277,4 +287,8 @@ static struct key bindings[] = {
 #ifndef NOMOUSE
 	{ KEY_MOUSE,      SEL_CLICK },
 #endif
+	{ 's',            SEL_SESSIONS },
+	{ '%',            SEL_TVERT },
+	{ '"',            SEL_THORZ },
+	{ 'N',            SEL_TWIND },
 };
```

Honestly i think its better to use plugins

**Comment by jarun** [comment]
BTW, I use `]` and `$nnn` heavily.

**Comment by Kabouik** [comment]
I also use `!` and `$nnn` heavily. I'm not exactly sure what is the difference between `!` and `]` yet, but I suppose I could use them both, or even `c-g` which I configured but don't really use yet.

I like that `c-d` exits the prompt, but that `c-d` and `c-u` in nnn are used scroll, as this is consistent with keybindings I use in other TUI applications too.  

In my workflow when using both nnn and prompt at the same time, the thing I miss the most with is a way to call `$nnn` from other (pre-existing) terminal windows. 0xACE helped me over Gitter about ways to make this possible, but I haven't had the time to dig it yet (with my limited skills, this is not something I could fix in 5 minutes). There could be issues as to how to interpret `$nnn` when several nnn instances are opened too (which is uncommon in my case, but still).
