### ISSUE TITLE
Disk usage analyse mode doesn't work unless du sorting is turned on

### ISSUE THREAD

**Issue by raghavmallampalli** [jarun/nnn#862]
#### Environment details (Put `x` in the checkbox along with the information)

[ x ] Operating System: Ubuntu 20.04
[ x ] Desktop Environment: GNOME
[ x ] Terminal Emulator: Tilix
[ x ] Shell: zsh
[ ] Custom desktop opener (if applicable):
[ x ] Program options used: -S
[ ] Configuration options set:
[ x ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
Old issues point to the `-S` flag to access disk usage mode. Now, however, `nnn -S` launches persistent session according to man page and `-h`. 

Using the `-Td` flag displays disk usage correctly but I would like to see disk usage without having to sort the files in that method. If this feature existed before and has been removed please edit the wiki and README.md to reflect the fact that there is no vanilla disk usage mode.

**Comment by jarun** [comment]
`nnn -S` is now `nnn -Td`. I don't know what you mean by vanilla. You always had to use an option. Also, it is sorted bu disk usage as earlier. Just check on master.

**Comment by raghavmallampalli** [comment]
I meant that I want to look at the disk usage without sorting by disk usage.
For example, sort by name but display the disk usage.

**Comment by jarun** [comment]
The sort order is fixed for disk usage.
