### ISSUE TITLE
How to use trash-cli instead of rm in fish shell

### ISSUE THREAD

**Issue by bushblade** [jarun/nnn#863]
Hi all, I can't work out how to use trash instead of rm in fish shell.
I have..
```
set -gx NNN_TRASH trash-cli
```
In my fish.config
but nnn still uses rm
`echo $NNN_TRASH` outputs `trash-cli`
What am I doing wrong to get this to work?

**Comment by jarun** [comment]
Look for `NNN_TRASH` in this section: https://github.com/jarun/nnn/wiki/Usage#configuration

**Comment by bushblade** [comment]
Hi @jarun thanks for the reply, yes that is what I was following.
The example looks to be in bash though? 
So I think my
`set -gx NNN_TRASH trash-cli`
Is the fish equivalent, but it does not work.
Is it just a matter of setting that as an env variable or am I missing something?

**Comment by bushblade** [comment]
Ah I figured it out the : in bash is like an else so all I need is..
`set -gx NNN_TRASH 1`
