### ISSUE TITLE
Copy between instances not working

### ISSUE THREAD

**Issue by hankchiutw** [jarun/nnn#864]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: macOS 10.12.6
[ ] Desktop Environment:
[ ] Terminal Emulator:
[x] Shell: fish
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[x] Issue exists on `nnn` master: v3.5

#### Exact steps to reproduce the issue
Install by `brew install --HEAD nnn`.
Follow the comment: https://github.com/jarun/nnn/issues/137#issuecomment-445551723. Specifically:
> in first instance, selected a file with ^K.
> in second instance, used P to paste the file

Are the key bindings removed now? If so, how could I copy files between nnn instances?

**Comment by KlzXS** [comment]
Those are keybinds for on old version. The comment you linked is from 2018.

Use `?` to display the current keybinds. Nowdays the keybinds are considered to be final.

**Comment by hankchiutw** [comment]
Then, my question is how could I copy files between nnn instances?
I have tried:
- in first instance, selected a file with `Space`.
- in second instance, used `p` to paste the file

It just hints `0 selected` in the second instance.

**Comment by KlzXS** [comment]
You are running off master right? I tested it with v3.0 I have lying around and it works fine. I'll test master a bit later.

**Comment by jarun** [comment]
@hankchiutw please test the patch and confirm it works as expected.

**Comment by KlzXS** [comment]
That fixes it on my end. But it brings back the problems from #855 
We need something that will fix both.

**Comment by jarun** [comment]
I added the check for selection file size 0. Please take a look.

**Comment by hankchiutw** [comment]
@jarun With the patch, the file can be copied/moved as expected.
But the moved file is still listed in the first instance unless I invoke redrawing manually(e.g. switch folder and back)

**Comment by jarun** [comment]
That's because we block directory updates while selecting files. Otherwise it may be a bigger issue in the regular case where you are cherry-picking 10 files and suddenly a directory update happens and yu view gets changed.

So please live with it.

**Comment by hankchiutw** [comment]
I see. Thanks for your support!
