### ISSUE TITLE
How to run plugins in the background?

### ISSUE THREAD

**Issue by nemya9066** [jarun/nnn#865]
Hi I have a plugin to open my selection in mpv It works fine problem is if I quit nnn mpv quits as well I don't want that to happen.
I know that to run a cli command in the background all I have to do is add the '|' symbol how to do the same to plugins that live in scripts??

**Comment by jarun** [comment]
I tried the following:

    z:-_|mousepad $nnn
and it works fine with a single file.

For selection I believe you need to use `&`. See the plugin `nuke` for examples.
