### ISSUE TITLE
Bug with selection list

### ISSUE THREAD

**Issue by Freespacer** [jarun/nnn#867]
Hello,

I give this file manager a try and found several little bug with file/directory selection. I checked twice with shipped from distribution and from the master branch of the GitHub repository.

Used Version of nnn is 3.5.

#### Environment details (Put `x` in the checkbox along with the information)

- [X] Operating System: openSUSE Tumbleweed (Rolling release)
- [X] Desktop Environment: KDE Plasma 5.21.1
- [X] Terminal Emulator: Yakuake 20.12.2
- [X] Shell: bash 5.1.4
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [X] Issue exists on `nnn` 

#### Preparation:

1. Go to a directory for testing with your favorite shell
2. Execute following commands to create several files and directories
```
mkdir -p nnntest/dir{1,2,3}
cd nnntest/
echo "content of file1" >file1.txt
echo "content of file2" >file2.txt
echo "content of file3" >file3.txt
echo "content of file11" >dir1/file11.txt
echo "content of file12" >dir1/file12.txt
echo "content of file13" >dir1/file13.txt
echo "content of file21" >dir2/file21.txt
echo "content of file22" >dir2/file22.txt
echo "content of file23" >dir2/file23.txt
```
3. If you are finished, you see this structure:
```
.
├── dir1
│   ├── file11.txt
│   ├── file12.txt
│   └── file13.txt
├── dir2
│   ├── file21.txt
│   ├── file22.txt
│   └── file23.txt
├── dir3
├── file1.txt
├── file2.txt
└── file3.txt
```

##### Bug No 1: Selected file is not marked as selected anymore

1. Go to the root of prepared diretory nnntest/ directory and start `nnn`
2. Selecting the following files:
```
file1.txt
file2.txt
dir1/file11.txt
dir1/file12.txt
```
3. Go back to the root nnntest/ and now you see that the selection of previous files `file1.txt` and `file2.txt` are gone. Missing the + sign in front of the file name.

##### Bug No 2: Selected files exist multiple times

1. Do the steps from **Bug No 1**
2. Selecting the following files again:
```
file1.txt
file2.txt
```
3. Take a look into the selection list with SHIFT + E and you see the files are duplicated.
4. Leave the selection and go to the `dir3/` directory.
5. Move the files into `dir3/` with `v` key and you see warnings from the `mv` command, because the last selected files was not found.

**Comment by KlzXS** [comment]
This is the intended behavior. The selection marker no longer appears after a directory update. The selection is still there, but a marker will not be show. It is possible to select a single file multiple times this way. To unselect a file after the marker is gone either edit the selection with `E` or clear it with `mm`.

We don't intend to change this anytime soon because it is hard to keep track of selection across multiple directories while displaying a marker and allowing for their unselection. There have been some ideas throw around, but nothing stuck.

**Comment by Freespacer** [comment]
Choosing an intended behavior in this case is not so good. Unfortunately, this is a bad user experience. And it is not efficient to check the list again to see if there are duplicate entries. This means that I cannot trust the selection list. In this case the file manager is useless for me at the moment.

Thanks for reading.

**Comment by KlzXS** [comment]
You don't need to worry too much about duplicate entries. It will either fail with an error which you can ignore or it will do the same thing twice.

But fair enought. Glad you gave a try.

**Comment by jarun** [comment]
@Freespacer persistent selection marker is on master now and will be available in the next release. That fixes the issue of duplicate entries too. Try it out!
