### ISSUE TITLE
Details field is blank when using Nerd font icons

### ISSUE THREAD

**Issue by WouterSpekkink** [jarun/nnn#868]
#### Environment details (Put `x` in the checkbox along with the information)

[X] Operating System: ArcoLinux (5.10.20-1-lts kernel)
[X ] Desktop Environment: dwm
[X] Terminal Emulator: st
[X ] Shell: zsh
[ ] Custom desktop opener (if applicable):
[X] Program options used: none
[X] Configuration options set: NNN_FCOLORS, NNN_PLUG, NNN_COLORS
[X] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
I wanted to add icons to nnn, so I cloned the latest version of nnn, installed a patched Nerd Font in my terminal, and built nnn with the Nerd Fonts flag enabled. I got the icons to work (great!), but I noticed that I get a blank space when I toggle the details (d) option. See the screenshot below.

[
![sshot](https://user-images.githubusercontent.com/6826078/110334023-99a67b00-8022-11eb-8edd-8e37b40d6551.png)
](url)

Let me also add a screenshot of nnn being run with the -C flag to demonstrate that the details toggle does work in that case.

![ssh2](https://user-images.githubusercontent.com/6826078/110334637-45e86180-8023-11eb-98b0-454b9e308ee0.png)

I also made a debug version of nnn and compared the debug file produced by running nnn (with icons) with the file produced when running nnn with the -C flag (when I do that, the details toggle functions as normal). I couldn't see anything out of the ordinary, but I added the debug output below just in case.

I checked the troubleshooting section of the wiki, but I couldn't find this issue discussed there. I also hadn't come across an earlier report of this issue.

```
ln __line__: VERSION=3.5
ln __line__: g_tmpfpath=/tmp
ln __line__: tmpfplen=5
ln __line__: home=/home/wouter
ln __line__: xdgcfg=/home/wouter/.config
ln __line__: cfgpath=/home/wouter/.config/nnn
ln __line__: selpath=/home/wouter/.config/nnn/.selection
ln __line__: opener=xdg-open
ln __line__: getenv(envs[ENV_VISUAL])=(null)
ln __line__: getenv(envs[ENV_EDITOR])=nvim
ln __line__: editor=nvim
ln __line__: pager=less
ln __line__: shell=/usr/bin/zsh
ln __line__: getenv("PWD")=/home/wouter/git_packages/nnn
ln __line__: COLORS=256
ln __line__: COLOR_PAIRS=32767
ln __line__: __func__=dentfill
ln __line__: ts2.tv_nsec - ts1.tv_nsec=30820
ln __line__: __func__=redraw
ln __line__: path=/home/wouter/git_packages/nnn
ln __line__: event->wd=0
ln __line__: event->mask=0
ln __line__: "inotify read done"=inotify read done
ln __line__: __func__=redraw
ln __line__: path=/home/wouter/git_packages/nnn
ln __line__: __func__=redraw
ln __line__: path=/home/wouter/git_packages/nnn
```

**Comment by jarun** [comment]
Can you try with default `NNN_FCOLORS`?

**Comment by WouterSpekkink** [comment]
Ha, that's it! Facepalm moment for me. Thank you so much for the quick response!
