### ISSUE TITLE
Include scripts in package

### ISSUE THREAD

**Issue by Jackymancs4** [jarun/nnn#87]
Hello,
in your next release, can you include scripts files (or at least ```scripts/quitcd/quitcd.*```) in the packaged source?

This way it's easier to source directy into the shell an eventually updated version of the script.

My personal usecase is that with homebrew on MacOS, adding ```source $(brew --prefix nnn)/scripts/quitcd/quitcd.bash``` on my ```.bash_profile``` is all it takes to enable the cd on quit feauture.

**Comment by jarun** [comment]
quitcd.bash is indicative. Not all people use bash and not all systems have it. So I have left the 3 files with sample code. But in any case, I can't install a bash script with the package. Sorry about that. Thanks for your understanding.

**Comment by Jackymancs4** [comment]
Well, my idea was to simply replace 
```DISTFILES = nlay nnn.c nnn.h nnn.1 Makefile README.md LICENSE``` 
with 
```DISTFILES = nlay nnn.c nnn.h nnn.1 Makefile README.md LICENSE scripts/quitcd/quitcd.*```
so that they get included in the tar archive,  but I see your point.
Thank you!
