### ISSUE TITLE
How do you open/edit selected files

### ISSUE THREAD

**Issue by medwatt** [jarun/nnn#870]
Pressing `e` will cause the selected file to open in the default editor. Let's say I have more than one file selected and want to open them all as buffers in vim -- how can I do that ?

**Comment by jarun** [comment]
Please see #866 on how to achieve this with plugins.

And also the reason behind not doing so in the main program.

**Comment by medwatt** [comment]
> Please see #866 on how to achieve this with plugins.
> 
> And also the reason behind not doing so in the main program.

Managed to get it to work. I discovered this file manager today and it has exceeded all my expectations. Thanks!
