### ISSUE TITLE
Problem with character encoding in plugin preview-tui

### ISSUE THREAD

**Issue by kaminski** [jarun/nnn#871]
When using the plugin preview-tui the plugin the preview terminal (or tmux pane) opens as expected, however the character coding is messed up, showing characters codes rather than Unicode characters. 

Am I missing a configuration value or could the
re be an accidental conflict? 

I have `bat` installed and from looking into the plugin code I understand it should detect it and use it automatically. 

Any help or hint would be much appreciated. 

Otherwise I'm hooked to `nnn` after a couple of days, fantastic and very smart work!

<img width="847" alt="2021-03-09_11-45-nnn-preview-tui" src="https://user-images.githubusercontent.com/982939/110459224-01190500-80cd-11eb-9277-bac67bfe52a4.png">

**Comment by 0xACE** [comment]
Your shell is not interpreting control codes for w/e reason. You should be able to find the problem within your environment

**Comment by KlzXS** [comment]
`someFile.js` is a regular plaintext file, it normally doesn't contain any ANSI escape codes. You can read more about them [here](https://en.m.wikipedia.org/wiki/ANSI_escape_code).

The preview on the other hand uses them to draw colorful things in the terminal. Some terminals and programs don't support them properly. And it probably isn't the terminal in your case, pretty much all modern ones support them. At least for colors.

**Comment by kaminski** [comment]
Sorry, output of your snippet is

```bash
...% env | grep -i "\(less\|pager\)"

LESSHISTFILE=-
PAGER=less
```

**Comment by leovilok** [comment]
It's definitively an issue about `less` not getting the right options, your output looks exactly like the default output of
```sh
bat ~/code/bat/bat.c --color=always | less
```

**Comment by leovilok** [comment]
A quick fix would be to change your `PAGER` environment variable whereever you define it (maybe ~/.bashrc, ~/.profile, ~/.zhrc, ...) to `export PAGER=less -R`.

**Comment by jarun** [comment]
Closing as this looks resolved.

**Comment by 0xACE** [comment]
@kaminski (and maybe @leovilok):
To avoid future issues: `export LESS='-R'` is what I would recommended over `export PAGER='less -R'`. because most likely your version of `less` supports that env variable to include options, rather than hoping that someone is using `$PAGER` without quotes
