### ISSUE TITLE
How can I modify the fzopen plugin so that NNN_OPENER=nuke is invoked?

### ISSUE THREAD

**Issue by Archangel-Live** [jarun/nnn#872]
I have set environment variable NNN_OPENER to a customized version of nuke and nnn opens everything the way I want it.

Now I'd like to modify the fzopen plugin so that it also invokes nuke. (fzopen calls xdg-open by default)

Here's the fzopen code snippet: 
`        if uname | grep -q "Darwin"; then
            open "$entry" >/dev/null 2>&1
        else
            xdg-open "$entry" >/dev/null 2>&1
        fi
`
Please give me an advice how to invoke nuke instead.

**Comment by jarun** [comment]
See plugin `preview-tabbed` which invokes `nuke`.

**Comment by Archangel-Live** [comment]
Thank you, I've got it. :-)
