### ISSUE TITLE
Go to file directly with fzf instead of directory

### ISSUE THREAD

**Issue by medwatt** [jarun/nnn#876]
I have been using this file manager for a few days now and I like it so much that I have been using it exclusively over my GUI file manager and also in vim. But there is one behaviour that doesn't seem right.

I have tried the `fzcd` plugin, but that takes you to the directory where the file is located, and if there are a lot of files, it would require a second search to get to the file. This seems like unnecessary double work. Is there a way to search for a file using `fzf` or something similar and jump straight to the file instead of the directory where the file is located ?

I have also tried `fzopen` but this opens the file directly. I don't always want to open the file. So, this is also not a solution.

**Comment by jarun** [comment]
It's a very good improvement without losing any functionality.
Please confirm the modified `fzcd` plugin works.

**Comment by medwatt** [comment]
@jarun, thanks for this. It works! Just one last question, if you don't mind: is it possible to disable the page that pops up with the message "Choose context 1-4 (blank for current):" and just go straight to the file in the same context?

**Comment by jarun** [comment]
You can override `CUR_CTX` in the plugins. So add the following in `fzcd` in the ext line after `.nnn-plugin-helper` is sourced.

```
CUR_CTX=1                                                                                              
export CUR_CTX
```

**Comment by jarun** [comment]
All of this is documented: https://github.com/jarun/nnn/tree/master/plugins#send-data-to-nnn

Please read the documentation to save our time.

**Comment by medwatt** [comment]
Thanks once more. I have actually gone through the documentation, but because of the wealth of information, you don't get to remember every little detail. But given that this has become my goto file manager, I will take the time to peruse the documentation more closely.
