### ISSUE TITLE
How can I clear the .selection file from within a plugin

### ISSUE THREAD

**Issue by Archangel-Live** [jarun/nnn#878]
I've written a plugin applying audio-conversions to selected files. 
How can I clear the selection when done? I can read from the .selection file, can I also write to it? Maybe I can remove or clear the random generated tmp-file which I can edit with the _edit selection_ key?. Is there a way to get the name of this tmp-file? Please give me a hint. I could not find an example in any other plugin working with the selection list.

**Comment by jarun** [comment]
More on selection here: https://github.com/jarun/nnn/wiki/concepts#selection

The selection file is cleared after successful plugin invocation. We close the open file descriptors after writing to the file so you can clear it manually. But it won't be very useful I guess.

**Comment by Archangel-Live** [comment]
Thanks for your response. I was familiar with this section of the documentation. I still don't see any possibility of clearing the selection list from within a plugin :-(
But anyway, nnn is the best file manager I ever used!

**Comment by jarun** [comment]
> I still don't see any possibility of clearing the selection list from within a plugin

I am not sure what you mean. You can just clear the selection file from the plugin.

**Comment by jarun** [comment]
There are several ways to do that: https://superuser.com/questions/90008/how-to-clear-the-contents-of-a-file-from-the-command-line

**Comment by Archangel-Live** [comment]
I tried 
echo -n "" > ~/.config/nnn/.selection 

at the end of my plugin. I also tried 
rm  ~/.config/nnn/.selection 

But the selection is not cleared, when I check within nnn I see the selection in a temporary file /tmp/.nnnBnylQN

I would clear this tmp-file, but the filename seems to be random generated and cannot be adressed.

**Comment by jarun** [comment]
That doesn't seem to be the selection file. Are you using `NNN_SEL`?

Also which version of `nnn` are you using?

**Comment by Archangel-Live** [comment]
To read the selection list I do:
selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

and I'm using Freddie :-)

**Comment by jarun** [comment]
The selection file path is shown in the program help at runtime. Please check that.
If you are not able to clear it, that may be a timing issue. But I am not sure why you want to clear it manually.

At least on master I see that the selection is cleared after plugin invocation.

**Comment by Archangel-Live** [comment]
The help says, it's the ......config/nnn/.selection file. 
But this is not a text file, it's a binary. 
And the selection is not cleared even if I delete or clear this ".selection" file from the command line. 
The selection itself still can be seen and edited within nnn with the editor key. Filepath shown is something like this: /tmp/.nnnBnylQN
The last six characters of the filename change with every selection clearence. 

The selection is not cleared after plugin invocation on my side. 
I changed the keybinding for plugins in nnn.h though. I use "," instead of ";"
Maybe the ";" is hard-coded. I have to try this out.

**Comment by KlzXS** [comment]
> And the selection is not cleared even if I delete or clear this ".selection" file from the command line.

From the looks of it you are not running `nnn` from master. It is probably displaying the selection buffer which is not cleared. The clearing of selection (both file and buffer) was implemented recently, a week or two ago.

You can either wait until the next release, which I asume will be soon @jarun, it has been 4 months since the last one, and there are a number of changes and fixes. Or you can compile from master for an immediate fix.

Depending on how fast you distors repos get updated you might want to go ahead with the latter.

**Comment by jarun** [comment]
I will make a release this week.

**Comment by Archangel-Live** [comment]
Thanks for the info, KlzXS and jarun ! 
Great news!!!

I found out something else in the meantime by the way:
Selection is cleared, when I press "," then ENTER, then chose the plugin from the list and ENTER again.
Selection is not cleared when I invoke my plugin by pressing "," followed by my plugin-key "a" 

Strange, but it's okay with me. 

I will update of course!
Keep up the good work, guys. You have the hottest file manager ever!

**Comment by Archangel-Live** [comment]
I can confirm that with the release of "Nina" all issues I had with my plugin are solved! :100:
