### ISSUE TITLE
Copy once and paste multiple times

### ISSUE THREAD

**Issue by idnsunset** [jarun/nnn#879]
**Is your feature request related to a problem? Please describe.**

After each copy operation is done, the selection gets emptied, which means I have to select the same file again to copy it to somewhere else. I would like to select it once and copy it multiple times until a new selection is made, just like in a GUI file manager we can copy a file and paste it everywhere until another file is copied. How can I achieve this with nnn?

**Describe the solution you'd like**

If possible, a special selection or copy shortcut that doesn't empty the selection after copy operation?

**Comment by 0xACE** [comment]
Oh, good idea :)

**Comment by jarun** [comment]
There's a problem with that. `nnn` has a flag - prefer selection over hovered.
Say, you selected some files and copied them. Now you want to remove a single file (the key to remove is the same). `nnn` sees that selection is preferred over hovered and it removes the selection from source. This happened to me as well. So better be safe than sorry.

**Comment by lawnowner** [comment]
It's strange I've never felt it was a missing feature so far.

> @idnsunset: How can I achieve this with nnn?

Copy `$sel` before it gets cleared, and keep it until there is a new selection:

```
sel=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
selmulti=${sel}multi

# Update $selmulti when there is a new selection.
[ -s "$sel" ] && cat "$sel" > "$selmulti"

[ -s "$selmulti" ] && xargs -0 cp -r -t "$(pwd)" < "$selmulti"
```

Start nnn with a function or script to delete (or clear) `$selmulti` when nnn is closed:
```
n () {
  nnn "$@"

  rm -f "${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}multi"
}
```
```
#!/usr/bin/env sh
xterm -e nnn "$@" &
wait
rm -f "${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}multi"
```

Delete (or clear) `$selmulti` manually at runtime with another plugin (e.g. `;c`/`;C`), if necessary.
