### ISSUE TITLE
Keep selection markers staying until emptied

### ISSUE THREAD

**Issue by idnsunset** [jarun/nnn#880]
**Is your feature request related to a problem? Please describe.**

When selecting multiple files from different directories, we select some files in one directory and navigate to another to select more. Sometime we need to navigate back to the previous directory to do a second check to confirm whether we missed some thing or deselect a wrong file, but all selection markers (leading plus sign) are lost (perhaps due to the screen redraw?). 

**Describe the solution you'd like**

I know I could view the `.selection` file but I rather hope that all selection markers keep staying until the current selection gets emptied.

**Comment by KlzXS** [comment]
This has been discussed previously. The reason we don't implement such a thing is because there is no easy, low memory usage way of keeping track of selected files.

I know this is a highly requested feature, but until someone comes up with a good method it will stay this way.
