### ISSUE TITLE
Keeping selection markers across directories

### ISSUE THREAD

**Issue by mdmawat** [jarun/nnn#882]
**Is your feature request related to a problem? Please describe.**

Since nnn supports multiple selections across directories, we may need to pick some files in one directory and navigate to another directory to pick some others, then probably go back to the previous directory to pick more or drop some selected ones. We need an **intuitive** (I know the `.selection` file can always be the last resort) way to keep track of all current selections, but the selection markers (leading plus sign) get lost after switching between directories.

**Describe the solution you'd like**

If technically possible, keep the selection markers showing until a deselection or an operation on the selections is performed.

**Comment by jarun** [comment]
We are already discussing this in the ToDo. Please don't open multiple issues for the same thing. Also, we all know the problem. Share if you have a solution

**Comment by jarun** [comment]
@mdmawat persistent selection marker is on master now and will be available in the next release. Try it out!
