### ISSUE TITLE
cp/mv with plugins (fzcd / autojump)

### ISSUE THREAD

**Issue by ralphee** [jarun/nnn#884]
is there a way to select a file / multiple files; use a plugin to to change directory and cp/mv the selected file(s)? Currently I have to open / switch between tabs to copy / paste

**Comment by KlzXS** [comment]
You can [use plugins to change active directory](https://github.com/jarun/nnn/tree/master/plugins#send-data-to-nnn), use already existing plugins for changing directories (fzcd, fzz), or [use bookmarks](https://github.com/jarun/nnn/wiki/Basic-use-cases#add-bookmarks).

**Comment by ralphee** [comment]
> You can [use plugins to change active directory](https://github.com/jarun/nnn/tree/master/plugins#send-data-to-nnn), use already existing plugins for changing directories (fzcd, fzz), or [use bookmarks](https://github.com/jarun/nnn/wiki/Basic-use-cases#add-bookmarks).

not quite sure i follow; once I have changed directory and try to cp/mv the selected files a msg pops up " 0 selected"

**Comment by KlzXS** [comment]
Duh! Right, my bad, the selection is cleared upon plugin invocation, that's a recent change.

Are bookmarks not enough for your workflow? If not I'm really no sure what to tell you.

Reopening so that someone else can also take a look at this.

**Comment by jarun** [comment]
@KlzXS can you please help me track where we added this?

**Comment by jarun** [comment]
Found it: https://github.com/jarun/nnn/commit/026f76f14cdf6f67d29ed3cfd5804b2e2890bf6f

I think plugins provide a way to change directories easily too. I will revert this.

**Comment by jarun** [comment]
Fixed at ce005ecb2be9f98ebb86547b90930274173daea9.

**Comment by KlzXS** [comment]
I think you should also update the release with this change @jarun

**Comment by jarun** [comment]
I made a hard push. Please update your views.

The next release has to wait. While it's convenient, not everyone uses this mechanism to navigate.

**Comment by jarun** [comment]
@KlzXS you were right. We need to make a release sooner than I would prefer to.

**Comment by jarun** [comment]
Guys, see commit 7f5dbd11e370d3c25bc1bf58618ee2804f9de1c2, now a plugin has to request explicitly to clear the selection. Plugins which operate on the selection know what to do with them afterwards. Other plugins don't need to do anything about the current selection and the selection will not be cleared when they are invoked.
