### ISSUE TITLE
symlinked text files not honoring editor/visual

### ISSUE THREAD

**Issue by mberlinger3** [jarun/nnn#885]
Im not sure if this is as intended but `nnn -e` does not open symlinked files in the editor. It throws the file to xdg-open instead. Is there any fix for this?

**Comment by jarun** [comment]
I can't repro this. There was a reason you have to fill up the template and provide more details.

**Comment by mberlinger3** [comment]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Manjaro
[x] Desktop Environment: KDE
[x] Terminal Emulator: Konsole
[x] Shell: zsh
[ ] Custom desktop opener (if applicable):
[x] Program options used: -e
[ ] Configuration options set:
[ ] Issue exists on `nnn` master

Steps to repro
`echo "Hello, World" >> file.txt`
`ln -s file.txt file2.txt`
`nnn -e` and press enter over file2.txt

**Comment by mberlinger3** [comment]
> I can't repro this. There's a reason you have to fill up the template and provide more details.

See above. Apologies.
