### ISSUE TITLE
fzf  interactive filter with keybindings

### ISSUE THREAD

**Issue by ralphee** [jarun/nnn#886]
#### Environment details (Put `x` in the checkbox along with the information)

[ x] Operating System: Arch Linux
[ x] Desktop Environment: dwm
[ x] Terminal Emulator: st
[ x] Shell: zsh
[ ] Custom desktop opener (if applicable): 
[ x] Program options used:
[ x] Configuration options set:
[ x] Issue exists on `nnn` master 

#### Exact steps to reproduce the issue

I am following this [guide](https://github.com/jarun/nnn/wiki/Advanced-use-cases#desktop-integration) and am experiencing the following : 

launching nnn directly from the terminal my [fzf](https://i.imgur.com/pYPF2aW.png) plugings  display "correctly"ie with an interactive filter

when launching fzf from a [keybinding](https://i.imgur.com/oZz8Jny.png) the interactive filter is not available.

my current [.zshenv](http://ix.io/2T6x) & the modified [script](http://ix.io/2T6z) which was taken from the wiki

<del> 
(on a side note from the example script i omitted the following as this file was not available)
`alias nsel="cat ${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection | tr '\0' '\n'"` </del>

**Comment by jarun** [comment]
I tried the following script (as `fscript.sh`) and launching `fzcd` with keybind <kbd>Alt+F</kbd>. Works fine for me.

```sh
#!/bin/sh                                                                                                  

export NNN_OPENER=/home/vaio/.config/nnn/plugins/nuke
export NNN_BMS="w:~/Downloads;t:~/Downloads/torrents;m:~/Dropbox/Public/Music/;i:~/Videos/MyMDB/images;d:/media;v:~/Videos;n:~/.config/nnn"
export NNN_PLUG='n:-_vim /home/vaio/Dropbox/Public/Docs/Notes/note*;f:fzcd;o:fzopen;p:preview-tui;d:diffs;t:nmount;m:-_mediainf $nnn*;a:-_mocp*;y:-_sync*;g:-_git diff;r:rg;l:moclyrics;1:shell'
export NNN_COLORS='#27760bd0;2134'
export NNN_ARCHIVE="\\.(7z|bz|bz2|deb|gz|iso|rar|rpm|tar|tbz|tbz2|tgz|txz|xz|Z|zip)$"
export NNN_SSHFS='sshfs -o reconnect,auto_cache,follow_symlinks'
export NNN_SEL='/tmp/.sel'
#export NNN_LOCKER=lock


export NNN_TMPFILE=${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd

# Unmask ^Q (if required, see `stty -a`) to Quit nnn
stty -tostop
stty start undef
stty stop undef

nnn -cdDEnQrx $@

if [ -f $NNN_TMPFILE ]; then
    . $NNN_TMPFILE
    rm $NNN_TMPFILE
fi
```

It looks like a local environment issue. Please debug yourself.
