### ISSUE TITLE
Make page up/down compatible with Vim

### ISSUE THREAD

**Issue by salutis** [jarun/nnn#887]
**Is your feature request related to a problem? Please describe.**

As a Vim user, I constantly trip over navigation in `nnn`.

Vim:

<kbd>Control</kbd><kbd>b</kbd> - Move back one full screen
<kbd>Control</kbd><kbd>f</kbd> - Move forward one full screen
<kbd>Control</kbd><kbd>d</kbd> - Move forward 1/2 screen
<kbd>Control</kbd><kbd>u</kbd> - Move back 1/2 screen

`nnn`:

<kbd>Control</kbd><kbd>b</kbd> - _nothing_
<kbd>Control</kbd><kbd>f</kbd> - File details (🤬🤬🤬)
<kbd>Control</kbd><kbd>d</kbd> - Move forward one full screen
<kbd>Control</kbd><kbd>u</kbd> - Move back one full screen

**Describe the solution you'd like**

Unify Vim and `nnn`:

<kbd>Control</kbd><kbd>b</kbd> - Move back one full screen
<kbd>Control</kbd><kbd>f</kbd> - Move forward one full screen
<kbd>Control</kbd><kbd>d</kbd> - Move forward 1/2 screen
<kbd>Control</kbd><kbd>u</kbd> - Move back 1/2 screen

We would need to remap File Details to something new.

**Comment by KlzXS** [comment]
This has been discussed before, we don't intend to implement vim-like keybinds. In fact, we don't plan on changing any keybinds.

You rebind them yourself and change the amount by which the screen is moved by changing the relevant code. Keybinds are defined in `src/nnn.h` and screen move is handled by `handle_screen_move()` in `src/nnn.c`.

**Comment by salutis** [comment]
@KlzXS 

> In fact, we don't plan on changing any keybinds.

I did not know the keybindings are “set in stone” at this point. Thank you for letting me know. As a new `nnn` user who is evaluating the program, I find _Help_ (<kbd>?</kbd>) a bit chaotic and keybinding close to consistent (with `vim`, `more`/`less`, ...) but not really.
