### ISSUE TITLE
issue with yesterday's commit "Revert clear selection on plugin invocation"

### ISSUE THREAD

**Issue by Archangel-Live** [jarun/nnn#889]
This issue is only in master since yesterday, not in latest release.

I made an audioconversion plugin converting nnn-selected SOURCE-files to TARGET-files. (i.e. file.flac --> file.mp3)

When I now (after successful run of my plugin) try to delete the TARGET file, nnn deletes the SOURCE file instead (SOURCE is still selected and nnn doesn't ask if I want to delete 'c'urrent / 's'el? )

**Comment by jarun** [comment]
> The problem is what people expect to happen to selection on plugin invocation.

Not really. With the reversal of clear selection on plugin invocation it's fixed that the selection will stay intact after plugin invocation. Here the user wants to deletethe hovered file rather than the selection. Delete is disruptive and hence the problem.

We can't add a new key at this phase of the project. So the user doesn't have a straightforward way to delete the current file.

**Comment by Archangel-Live** [comment]
I agree with jarun. This "selection over current" behaviour by default is not so good in the first place. It happens more than once that I select a file, forget about having selected it, moving around and hover over another file I want to delete. nnn then deletes the selected file instead. Thats mischievous :-)

**Comment by jarun** [comment]
It takes a little time to get accustomed to. But given that many users are already familiar with the behaviour for a long time, the removal has been a blunder. We had an option, those who don's want an extra question (and are careful enough) could just disable it.

**Comment by Archangel-Live** [comment]
Many new users of nnn will be repelled by this behaviour when it's the default. You'll get a flood of bug reports, I'm sure.
As an option with a start parameter: very good.  Let the users decide.

**Comment by jarun** [comment]
Fixed at 93ca773c594f3f1da81f8ccba3766184b982d35d.

**Comment by lawnowner** [comment]
> I agree with jarun. This "selection over current" behaviour by default is not so good in the first place. It happens more than once that I select a file, forget about having selected it, moving around and hover over another file I want to delete. nnn then deletes the selected file instead. Thats mischievous :-)

@Archangel-Live @jarun @KlzXS Note that if you still want to clear the selection file from within a plugin, the result will be more confusing for you this time :] Using the `-u` option to prefer the selection over the current entry, and clearing the selection file within a plugin for safety against accidental deletions after the plugin invocation will still, despite the selection file's being empty after the plugin invocation, **(1)** prompt for the deletion of the recently selected files if you press `x`, e.g. `rm -rf 3 files?`; **(2)** try to copy the recently selected files (and fail) if you press `p`; **(3)** show the recently selected files if you press `E` to edit the selection. So, currently, the selection file can be cleared  as a precaution by a user who prefer `-u`, but it causes anomalies after the plugin invocation.

**Comment by Archangel-Live** [comment]
@lawnowner 
As far as I searched, there is no plugin available which does clear the selection. Can you please tell me how I can clear the selction from within a plugin?

I tried
echo -n "" > ~/.config/nnn/.selection

at the end of my plugin. I also tried
rm ~/.config/nnn/.selection

But the selection is not cleared, when I check within nnn I see the selection in a temporary file /tmp/.nnnBnylQN

I would clear this tmp-file, but the filename seems to be random generated and cannot be adressed.

**Comment by lawnowner** [comment]
@Archangel-Live jarun already answered that: https://github.com/jarun/nnn/issues/878#issuecomment-798962730

It can be cleared with `echo` or `>` anywhere in the script, or with `trap` to `EXIT` at the start so that it is cleared even if the plugin quits unexpectedly:

```
sel=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
trap '> "$sel"' EXIT
```
The file with the randomized name `.nnnXXXXXX` isn't the selection file but a temporary file used to store changes to be applied to the selection file. Currently, if the selection file is cleared within a plugin, the temporary file that will be displayed with `E` will keep listing the entries that don't exist in the selection file.

**Comment by Archangel-Live** [comment]
Thank you very much for this clarification, @lawnowner . 
The trap to EXIT also works! 
I can reproduce the confusing results you describe after this plugin interaction but at least I understand this behaviour now. 
Anyway, your trap tip is very useful for me. Now I can run my plugin several times on different selections without converting the already processed files all over again. :+1:

**Comment by jarun** [comment]
> and clearing the selection file within a plugin for safety against accidental deletions after the plugin invocation

This is user modified behaviour. If you are modifying a plugin you know what you are doing. And we always prompt before we delete, so you cannot accidentally delete anything.

**Comment by mlaparie** [comment]
> And we always prompt before we delete, so you cannot accidentally delete anything.

Sorry to hijack this issue but I missed that change. At some point `nnn` could delete with `x` or `^+x` without confirmation if I remember correctly. I'm now using modified configuration and sources to use `trash-cli`, remove `x`, and a custom plugin to use `rm -i` on another keybind. Is that all unnecessary now?

**Comment by Kabouik** [comment]
> And we always prompt before we delete, so you cannot accidentally delete anything.

Sorry to hijack this issue but I missed that change. At some point `nnn` could delete with `x` or `^+x` without confirmation if I remember correctly. I'm now using modified configuration and sources to use `trash-cli`, remove `x`, and a custom plugin to use `rm -i` on another keybind. Is that all unnecessary now?

**Comment by jarun** [comment]
@Kabouik Please check the current behaviour. It will remain unchanged. I don't remember the history just like you.

**Comment by jarun** [comment]
@Archangel-Live 

> nnn then deletes the selected file instead.

Just to put things straight - it didn't occur to me earlier that we show a prompt before we delete. So no, it's not a direct deletion.

**Comment by lawnowner** [comment]
> And we always prompt before we delete, so you cannot accidentally delete anything.

Accidentally deleting selected files while trying to delete a single entry isn't that far-fetched despite the prompt. If it happened to yourself (https://github.com/jarun/nnn/issues/879#issuecomment-799459424), my guess would be you couldn't be alone. Personally, it doesn't make a difference to me either way.

**Comment by jarun** [comment]
I also mentioned that I got accustomed to `-u` over months. Also, now I read my prompts.

**Comment by jarun** [comment]
@KlzXS exploring a solution for this, what if we clear the solution in all cases other than opcode `c`? And only if `selbufpos` is non-zero (to ensure we don't erase the selection from another running instance)?

**Comment by KlzXS** [comment]
So you're saying we only clear the buffer, and don't touch the file. And we do that for every operation except "Connect remote"?

I'm sorry, I'm a bit lost. In the last 2 days there have been like 10 issues opened. What will this solve and who will this change make happy?

**Comment by jarun** [comment]
No, I am saying we clear the file only if the buffer is non-empty (because the buffer is always written to the file before plugin invocation).

This will ensure the selection will not be cleared for users who use plugins to cd. maybe we should not clear for all cases where the plugin writes something back to `NNN_PIPE`. Because even in case of listing, if there's a selection, the user may want it to be retained as listing doesn't have to do anything with the selection.

**Comment by jarun** [comment]
Please check the patch.

**Comment by lawnowner** [comment]
@jarun The commit related to the plugin invocation looks to be working well. The commit related to symlink targets on the status bar are garbled, even more so after `f`.

**Comment by jarun** [comment]
Do you see `...` or `-> `?

**Comment by lawnowner** [comment]
Yes `[...-> ...]`, e.g. `[...scriptsds( 1000/     ctd)]` after `f` instead of `[...scripts]`.

**Comment by jarun** [comment]
Can you check on master now? It should be fixed.

**Comment by Archangel-Live** [comment]
Thank you very much, @jarun . You nailed it!! Everything is working perfectly now :+1:

**Comment by jarun** [comment]
Guys, see commit 7f5dbd11e370d3c25bc1bf58618ee2804f9de1c2, now a plugin has to request explicitly to clear the selection. Plugins which operate on the selection know what to do with them afterwards. Other plugins don't need to do anything about the current selection and the selection will not be cleared when they are invoked.

**Comment by Archangel-Live** [comment]
I just compiled master and modified my plugin according to your examples. But the selection is not cleared. 
Please try and check mocplay, it doesn't clear selection either.

**Comment by jarun** [comment]
Did you install the latest plugins using `getplugs master`?

Also, if a plugin works on the hovered file, it should not send a clear selection request.

**Comment by Archangel-Live** [comment]
Sorry, jarun. This was my fault. I just discovered that the package manager of Arch Linux did not overwrite the old nnn bin file. I had to delete it manually. 
After I reinstalled the new nnn master everything works now !!!  It's Perfect! Thank you very much :+1:

**Comment by jarun** [comment]
My pleasure. Thanks for pursuing this. I think we have the best solution now as the plugin which wors on the selection should take the responsibility depending on its workflow. And we do not need to disturb the other plugins either!
