### ISSUE TITLE
New error when trying to launch

### ISSUE THREAD

**Issue by Freaksed** [jarun/nnn#892]
#### Environment details (Put `x` in the checkbox along with the information)

[x ] Operating System: Windows 10
[x ] Desktop Environment: Windows
[x ] Terminal Emulator: cmder
[x ] Shell: WSL
[ ] Custom desktop opener (if applicable):
[x ] Program options used: -e
[x ] Configuration options set:export NNN_PLUG='f:finder;o:fzopen;p:mocplay;d:diffs;t:nmount;v:imgview'
export NNN_FCOLORS='c1e2e62e216033f7c6d6abc4'
alias nnn 'nnn -e'
set --export NNN_FIFO '/tmp/nnn.fifo'
export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
[x ] Issue exists on `nnn` master

Updated to ubuntu 20.04. It worked a couple of times and then started showing this message and not launching
"nnn: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory"
This is happening on 2 separate computers

**Comment by KlzXS** [comment]
Newest verion of readline available in Ubuntu 20.04 repos is 8. Older Ubuntu repos have older versions. Your local copy of `nnn` was linked with version 7 so when you updated it it broke.

To fix the issue recompile.
