### ISSUE TITLE
Show destinations for symbolic links

### ISSUE THREAD

**Issue by salutis** [jarun/nnn#893]
**Is your feature request related to a problem? Please describe.**

I am probably missing something because this is super-basic. How can I see where a symlink points in `nnn`? The standard mode does not tell me. The _Detail mode_ (<kbd>d</kbd>) does not tell me. The _File details_ view (<kbd>f</kbd>) do not tell me. Ideally, I would like to see `a -> b` in the list.

**Describe the solution you'd like**

Old:
```
APEX Calculus.bib@
APEX Calculus.pdf@
```

New:
```
APEX Calculus.bib@ -> Hartman+2018.bib
APEX Calculus.pdf@ -> Hartman+2018.pdf
```

**Screenshots**

`nnn`

<img width="945" alt="s1" src="https://user-images.githubusercontent.com/1158274/111617666-b3468000-87e3-11eb-8370-b5a58b62dbb4.png">

`ls -l`

<img width="975" alt="s2" src="https://user-images.githubusercontent.com/1158274/111617693-ba6d8e00-87e3-11eb-9ff9-331b2ed023fe.png">

**Comment by 0xACE** [comment]
Are you sure `f` doesn't view the symlink? it does on my build

**Comment by Kabouik** [comment]
It does on mine too, though an indication when `d` details are enabled could be useful too (but I'm not sure I would always want it, especially for long paths).

**Comment by salutis** [comment]
macOS 11.2.3 (20D91), `nnn` v3.5

<img width="1280" alt="a1" src="https://user-images.githubusercontent.com/1158274/111641518-8737f880-87fd-11eb-9ff3-d3c3aa1c508b.png">

<img width="1280" alt="a2" src="https://user-images.githubusercontent.com/1158274/111641534-8bfcac80-87fd-11eb-8067-227823634327.png">

**Comment by KlzXS** [comment]
It seems this is due to a difference in `stat` between linux and macOS. There is a way to print with a custom format.

**Comment by salutis** [comment]
> @Kabouik […] an indication when `d` details are enabled could be useful too […]

This would be _really_ useful for my workflow.

**Comment by jarun** [comment]
Please test the patch. Now you can hover on the file and see the symlink target in the statusbar.

**Comment by jarun** [comment]
@salutis I have made one more improvement to show the number of links and inode number of hard links in the statusbar in 9f0a37425578bde8e448c14de54743b95c6da618.

**Comment by salutis** [comment]
@jarun Amazing work!
