### ISSUE TITLE
Is it possible to do recursive search from current dir?

### ISSUE THREAD

**Issue by pvonmoradi** [jarun/nnn#894]
NNN has a filter functionality. It searches files and dirs already visible in current dir. How to do a "recursive search" from current dir?  
Like finding a file in a dir deeply rooted in current dir.
```
a/ -> b/ -> no1.c
a/ -> c/ -> d/ -> yes.c
e/ -> no2.c
no3.c
```
Like when NNN is in the base dir, if I do a filter, I can only filter for `a/`, `e/`, and `no3.c` but I want to be able to search for `yes.c` and `cd` there (aka `d/`).

**Comment by jarun** [comment]
Please use the plugins `fzcd` and/or `fzopen`.
