### ISSUE TITLE
Is it possible to **not** auto-return to type-to-nav mode after quitting from it?

### ISSUE THREAD

**Issue by pvonmoradi** [jarun/nnn#897]
I'm using `nnn -nA`. It starts the nnn in type-to-nav mode and works fine.
But then, when I use arrow keys or simply escape this mode (by hitting escape), upon traversing to a different directory, it opens it in type-to-nav mode *again* (despite me deliberately quitting from it by hitting escape).
Now it seems it does exit from this mode properly if ^N is hit. Is it possible to make it so that if we go out of this mode with any means (like Escape or using arrow keys), it does not return to this mode again? (so we should hit ^N again to activate it). 
I think the way it behaves currently is a bit paradoxical in terms of UX because actually there are two distinct ways to quit this mode and one of them *auto-returns the mode back*.

**Comment by jarun** [comment]
From the program help:

```
Esc  Exit prompt
^N  Toggle type-to-nav
```

Use <kbd>^N</kbd> to toggle.
