### ISSUE TITLE
Size is not showing correctly

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#90]
Steps to reproduce:

1. Create the file:

       fallocate -l 154140260 out.file
3. Check the file size in `nnn`:

       2018-03-04 22:02 146.100M  out.file
3. Check the file size in v1.7:

       2018-03-04 22:02  147.00M  out.file

154140260 / (1024*1024) = 146.999607

So `147.00M` is the correct approximate size.

The regression was introduced by 7be0726164442a83f47e5a9a0cdf2db343832d23.

**Comment by jarun** [comment]
@arsv please take a look.

**Comment by arsv** [comment]
Yeah, my bad. Carry is not handled properly when rounding.

https://github.com/jarun/nnn/pull/91
