### ISSUE TITLE
`picker` plugin broken with latest "show path in terminal" feature

### ISSUE THREAD

**Issue by amanjitsk** [jarun/nnn#918]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Ubuntu 20.04 LTS
[x] Desktop Environment: BSPWM
[x] Terminal Emulator: st/kitty
[x] Shell: zsh
[x] Custom desktop opener (if applicable): nuke
[x] Program options used: NNN_OPTS=cCdEfHorQSUx
[x] Configuration options set:
```
NNN_OPENER=/home/amanjitsk/.config/nnn/plugins/nuke
NNN_BMS=b:/home/amanjitsk/.cache/nnn/bookmarks;c:/home/amanjitsk/.config;C:/home/amanjitsk/.cache;d:~/Desktop;D:~/Downloads;g:/home/amanjitsk;l:/home/amanjitsk/.local;m:/home/amanjitsk/.config/nnn/mounts;M:/media;n:/home/amanjitsk/.config/nnn/plugins;p:/home/amanjitsk/pkgs;P:~/Pictures;r:/run/user/1000;s:/home/amanjitsk/.config/scripts;t:/home/amanjitsk/.local/share/Trash;T:/tmp;x:/home/amanjitsk/.config/texmf/tex/latex/local;z:/home/amanjitsk/.config/zsh;Z:/home/amanjitsk/.config/zsh/.zinit/plugins
NNN_SEL=/home/amanjitsk/.config/nnn/selection
NNN_TRASH=1
NNN_COLORS=42564256
NNN_PLUG=a:arxiv;b:bookmarks;B:papis-open;c:fzcd;d:diffs;D:dragdrop;e:fzedit;E:suedit;f:finder;g:_lazygit*;h:fzhist;i:imgview;I:imgviu;k:pskill;l:symlinks;L:_clear*;n:notes;o:fzopen;p:_pager $nnn*;P:present;r:renamer;s:substitute;t:trashcli;u:downloader;U:upload;w:wall;y:yank;z:fzz;`:fzplug;;:preview;=:execute;/:fzgrep;?:fzgrep-all;]:spawncwd;
NNN_ARCHIVE=\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$
NNN_OPTS=cCdEfHorQSUx
NNN_FIFO=/run/user/1000/nnn.fifo
NNN_LOCKER=ytop -bs
```
[x] Issue exists on `nnn` master: Yes

#### Exact steps to reproduce the issue

`cat $(picker)` results in a failure with one or more files (with multiple files, 
only the first result is corrupted). I think this has to do with the latest "show path in 
terminal" feature that somehow is output by the `picker` plugin.

![image](https://user-images.githubusercontent.com/12499495/112505004-be109000-8d62-11eb-8ef6-ca2b6cd4b82c.png)

**Comment by jarun** [comment]
@amanjitsk can you please confirm if this is fixed with the patch?

**Comment by amanjitsk** [comment]
nice that fixed it! Thanks for the quick response!
