### ISSUE TITLE
How to delete file, folder

### ISSUE THREAD

**Issue by thevan96** [jarun/nnn#933]
I'm try delete file but not wrong.
![Screen Shot 2021-04-04 at 11 12 53 PM](https://user-images.githubusercontent.com/47932916/113514889-4977f580-959b-11eb-82c3-c475fb7b839e.png)

**Comment by jarun** [comment]
You'll have to install `trash-cli` - https://github.com/jarun/nnn/wiki/Usage#dependencies

**Comment by thevan96** [comment]
I set NNN_TRASH = 1 => trashcli
![Screen Shot 2021-04-05 at 1 44 14 PM](https://user-images.githubusercontent.com/47932916/113545784-0490a500-9615-11eb-966e-d5009e24ac7c.png)
If i use x => nothing
If i use space -> x -> error
![Screen Shot 2021-04-05 at 1 46 06 PM](https://user-images.githubusercontent.com/47932916/113545939-47eb1380-9615-11eb-89f7-9641015ce141.png)

**Comment by jarun** [comment]
What is the output of:

    which trash-put
