### ISSUE TITLE
Default light colorscheme

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#937]
The default `NNN_COLORS` and `NNN_FCOLORS` ([configuration details](https://github.com/jarun/nnn/wiki/Usage#configuration)) are suitable for dark backgrounds.

It would be great to have a default light colorscheme for users who are accustomed to lighter terminal colors.

If you have a suggestion, please share the config values, the light terminal theme name with an image in this thread.

A good start may be a popular terminal theme like Solarized Light.

**Comment by akimdi** [comment]
i love this theme https://github.com/morhetz/gruvbox

this popular theme is also used by the maintainer nnn in ArchLinux (gruvbox dark)
https://archlinux.org/packages/community/x86_64/nnn

**Comment by jarun** [comment]
@akimdi can you please share a screenshot and the values of the configuration settings?

**Comment by akimdi** [comment]
[.zshrc](https://gist.github.com/akimdi/58d1b1772580f37dc02b5ee65d393ada)
[.Xresources](https://gist.github.com/akimdi/7fbdd88824b51312cdbece285eab8483)
[kitty.conf](https://gist.github.com/akimdi/6e2a5108e5856bf520d065aa2d0d4c8a)

[Terminess Nerd Font](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Terminus/font-info.md)

![1619460006](https://user-images.githubusercontent.com/6793168/116159478-fe17b980-a6f8-11eb-95f8-8ab64c665023.png)
![1619459020](https://user-images.githubusercontent.com/6793168/116159480-ff48e680-a6f8-11eb-9a47-ce774ea91508.png)
![1619459025](https://user-images.githubusercontent.com/6793168/116159481-ffe17d00-a6f8-11eb-9a26-f53cd793d1ca.png)
![1619459040](https://user-images.githubusercontent.com/6793168/116159486-ffe17d00-a6f8-11eb-915a-9077d62048eb.png)
![1619459075](https://user-images.githubusercontent.com/6793168/116159488-007a1380-a6f9-11eb-99eb-d5967c496cf1.png)

**Comment by akimdi** [comment]
![1619478489](https://user-images.githubusercontent.com/6793168/116162040-a2036400-a6fd-11eb-9123-78c29a117e2b.png)

**Comment by jarun** [comment]
Thank you so much! This appears to be a dark colorscheme right?

**Comment by jarun** [comment]
@akimdi can you add it here? https://github.com/jarun/nnn/wiki/Themes

I am closing this thread as there is no light colorscheme in a month.

**Comment by akimdi** [comment]
@jarun 
Due to illness, I don't feel well, so now I rarely reply to messages. Excuse me.
I will definitely add a light theme.

**Comment by jarun** [comment]
Get well soon!

**Comment by akimdi** [comment]
Thank you 😊️

**Comment by mizlan** [comment]
I can take a shot at this. One question I have is, since `nnn` by default uses the terminal ANSI colors, would it be odd for there to be a custom light palette but not a custom dark palette?

**Comment by jarun** [comment]
The default we have is appropriate for dark terminals if that's what you are asking.

If you are suggesting we should have both the light and dark variants for a theme - yes, that makes sense.

**Comment by jarun** [comment]
BTW, this can wait. I am more concerned about the outstanding `nnn.vim` issues. So feel free to prioritize those.
