### ISSUE TITLE
Is there any way to open dir via ssh?

### ISSUE THREAD

**Issue by knevcher** [jarun/nnn#94]

**Comment by jarun** [comment]
You have to connect to the remote system over SSH, run `nnn` and open the dir. There is no provision to open remote directories directly.

**Comment by knevcher** [comment]
I would like to copy remote file line with scp (emacs dired-mode could do it and mc as I know too).

**Comment by jarun** [comment]
Right now no plans to do that. If you are interested feel free to raise a PR.

**Comment by jarun** [comment]
I am adding an item in ToDo list for this.

**Comment by markroxor** [comment]
For the bystanders, here is a hack using VIM -  
* Install [nerdtree](https://github.com/scrooloose/nerdtree) and then -
* `vim scp://uname@server_ip//path_to_dir`
![Screenshot 2019-06-27 at 10 52 10 AM](https://user-images.githubusercontent.com/11366315/60238974-bee46b80-98c9-11e9-81d7-c18be373eba0.png)

**Comment by jarun** [comment]
We are supporting sshfs now. So you can mount remotes and copy files to and fro.
