### ISSUE TITLE
macOS disk usage of directory does not make sense

### ISSUE THREAD

**Issue by usualwitch** [jarun/nnn#940]
On macOS, nnn's detailed view is like

<img width="345" alt="image" src="https://user-images.githubusercontent.com/47266849/114138077-ada20d00-993f-11eb-91f8-abfd9a8b3f71.png">

All directories display a meaningless size, while the expected behavior is to show the sum of the file sizes inside the directory. This makes nnn hard to use for disk usage analysis on macOS. 

This issue has been posted here: https://github.com/jarun/nnn/issues/729 But the additional info in that issue does not seem to get a response.

**Comment by jarun** [comment]
You are not in `du` mode.
In regular mode, the sizes shows are the size taken by the directory meta-information and same as `ls` output:

```
$ /bin/ls -lh --group-directories-first
total 9.4M
drwxrwxr-x 14 vaio vaio  12K Mar 27 02:11  Amrita
drwxrwxr-x  2 vaio vaio 4.0K Feb 20 11:19  Desktop
drwxr-xr-x 18 vaio vaio 4.0K Apr  2 11:48  Documents
drwxr-xr-x  6 vaio vaio  64K Apr  8 01:26  Downloads
drwxrwxr-x  4 vaio vaio 4.0K Jan 21 14:04  Dropbox
drwxrwxr-x 36 vaio vaio 4.0K Apr  8 07:41  GitHub
drwxrwxr-x 11 vaio vaio 4.0K Apr  8 01:56  Music
drwxr-xr-x  3 vaio vaio  20K Mar  5 22:23  Pictures
drwxr-xr-x  6 vaio vaio  12K Apr  9 11:42  Videos
```
