### ISSUE TITLE
`du` mode on macOS version Big Sur 11.2.3 shows directory size as 0B

### ISSUE THREAD

**Issue by usualwitch** [jarun/nnn#941]
Thanks for the quick reply! I searched for the disk usage mode and find

```
- persistent session option `-S` [for disk usage, run `nnn -T d` (see help)]
```

in the change log. However when I use `nnn -T d`, the directory sizes are all 0B. I am using the most recent version installed via brew on macOS.

<img width="338" alt="image" src="https://user-images.githubusercontent.com/47266849/114142911-11c7cf80-9946-11eb-81e9-8f916d1d62c2.png">

**Comment by jarun** [comment]
What is your `nnn` version? Try `nnn -h`.

**Comment by usualwitch** [comment]
It's v3.6

**Comment by luukvbaal** [comment]
Could not reproduce on [OSX-KVM](https://github.com/kholia/OSX-KVM):
![image](https://user-images.githubusercontent.com/31730729/114170128-c1934200-9932-11eb-8f7e-b6658c399b5e.png)

Does `du -hd1` show the different sizes?

**Comment by usualwitch** [comment]
> Could not reproduce on [OSX-KVM](https://github.com/kholia/OSX-KVM):
> ![image](https://user-images.githubusercontent.com/31730729/114170128-c1934200-9932-11eb-8f7e-b6658c399b5e.png)
> 
> Does `du -hd1` show the different sizes?

`du -hd1` gives correct results, not 0B.

My macOS version is Big Sur 11.2.3

**Comment by jarun** [comment]
What happens if you try it at runtime i.e., start `nnn` and then do `^T`->`d`?

**Comment by usualwitch** [comment]
> What happens if you try it at runtime i.e., start `nnn` and then do `^T`->`d`?

<img width="354" alt="image" src="https://user-images.githubusercontent.com/47266849/114259063-cffa6000-99fd-11eb-9e0d-4a1cc809a851.png">

It's still 0B.

**Comment by jarun** [comment]
I don't have a mac, so I tried this using [fastmac](https://github.com/fastai/fastmac). It works as expected.

```
>2021-04-05 00:55  755  42.896G  Library/
 2021-04-05 01:10  755   5.620G  hostedtoolcache/
 2021-04-08 07:05  755  196.38M  runners/
 2021-04-10 09:28  755    9.06M  work/
 2019-10-11 11:28  700    6.96M  Pictures/
 2019-10-18 09:48  700      12K  Movies/
 2021-03-08 19:32  700       8K  Desktop/
 2021-03-08 19:30  700       8K  Downloads/
 2018-01-05 12:39  755       0B  Documents/
 2019-08-20 17:20  700       0B  Music/
 2021-04-05 01:15  644      32K  systeminfo.md
 2021-04-04 21:11  644       4K  imagedata.json
 2021-04-05 01:15  644       4K  systeminfo.txt
```

If you can [debug](https://github.com/jarun/nnn/wiki/Developer-guides#debugging-nnn) the issue with prints, please give it a try.

**Comment by jarun** [comment]
Does it seem like it's calculating anything? Or do you get this result instantly?

**Comment by jarun** [comment]
There was a macOS specific fix recently (commit fddc5086ddb8cb20209f22dbd0fa34ed6c1092e5) where there was an issue with data type overflow.

What is the output of `du -hd1`?

**Comment by usualwitch** [comment]
> There was a macOS specific fix recently (commit [fddc508](https://github.com/jarun/nnn/commit/fddc5086ddb8cb20209f22dbd0fa34ed6c1092e5)) where there was an issue with data type overflow.
> 
> What is the output of `du -hd1`?

`du -hd1` calculates and outputs the results one by one. It took quite some time. nnn du mode displays 0B result instantly without triggering calculation.

**Comment by usualwitch** [comment]
> I don't have a mac, so I tried this using [fastmac](https://github.com/fastai/fastmac). It works as expected.
> 
> ```
> >2021-04-05 00:55  755  42.896G  Library/
>  2021-04-05 01:10  755   5.620G  hostedtoolcache/
>  2021-04-08 07:05  755  196.38M  runners/
>  2021-04-10 09:28  755    9.06M  work/
>  2019-10-11 11:28  700    6.96M  Pictures/
>  2019-10-18 09:48  700      12K  Movies/
>  2021-03-08 19:32  700       8K  Desktop/
>  2021-03-08 19:30  700       8K  Downloads/
>  2018-01-05 12:39  755       0B  Documents/
>  2019-08-20 17:20  700       0B  Music/
>  2021-04-05 01:15  644      32K  systeminfo.md
>  2021-04-04 21:11  644       4K  imagedata.json
>  2021-04-05 01:15  644       4K  systeminfo.txt
> ```
> 
> If you can [debug](https://github.com/jarun/nnn/wiki/Developer-guides#debugging-nnn) the issue with prints, please give it a try.

I executed `./nnn` and typed `^T D` to enter du mode.

Here are the debug output lines that seem to be working incorrectly.

```
ln __line__: __func__=dentfill
ln __line__: ts2.tv_nsec - ts1.tv_nsec=156000
ln __line__: __func__=redraw
ln __line__: path=/Users/yuanwei/repos/nnn
ln __line__: __func__=dentfill
ln __line__: "nftw failed"=nftw failed
ln __line__: "nftw failed"=nftw failed
ln __line__: "nftw failed"=nftw failed
ln __line__: "nftw failed"=nftw failed
ln __line__: "nftw failed"=nftw failed
ln __line__: "nftw failed"=nftw failed
ln __line__: "nftw failed"=nftw failed
ln __line__: ts2.tv_nsec - ts1.tv_nsec=1181000
ln __line__: __func__=redraw
```

**Comment by jarun** [comment]
As you will see int he code we use the following flags:

```
       FTW_MOUNT
              If set, stay within the same filesystem (i.e., do not cross mount points).

       FTW_PHYS
              If  set,  do not follow symbolic links.  (This is what you want.)  If not set, symbolic links are
              followed, but no file is reported twice.

              If FTW_PHYS is not set, but FTW_DEPTH is set, then the function fn() is never called for a direc‐
              tory that would be a descendant of itself.
```

Are these regular directories or mountpoints/symlinks?

Also, please try with open_max set to 64 once to ensure that's the problem.

**Comment by usualwitch** [comment]
> As you will see in the code we use the following flags:
> 
> ```
>        FTW_MOUNT
>               If set, stay within the same filesystem (i.e., do not cross mount points).
> 
>        FTW_PHYS
>               If  set,  do not follow symbolic links.  (This is what you want.)  If not set, symbolic links are
>               followed, but no file is reported twice.
> 
>               If FTW_PHYS is not set, but FTW_DEPTH is set, then the function fn() is never called for a direc‐
>               tory that would be a descendant of itself.
> ```
> 
> Are these regular directories or mountpoints/symlinks?
> 
> Also, please try with open_max set to 64 once to ensure that's the problem.

Yes, that's the problem. I changed the return value of `max_openfds` to 64 and now it's working correctly!

**Comment by jarun** [comment]
Can you please add some prints in `max_openfds()` and get the value of `rl.rlim_cur` and `rl.rlim_max`?
We can't blindly hard code it to 64 as it is an important optimization. We have to arrive at some decent value.

**Comment by usualwitch** [comment]
> Can you please add some prints in `max_openfds()` and get the value of `rl.rlim_cur` and `rl.rlim_max`?
> We can't blindly hard code it to 64 as it is an important optimization. We have to arrive at some decent value.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/47266849/114275975-3495d900-9a57-11eb-94bf-d8a6118dc57d.png">

This is the result, super huge.

**Comment by jarun** [comment]
Awesome! For macOS we will not touch rlimit.

**Comment by jarun** [comment]
From macOS man page: https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/nftw.3.html

```
     int
     nftw(const char *path,
         int (*fn)(const char *, const struct stat *ptr, int flag, struct FTW *),
         int depth, int flags);
```

`depth` is of type `int` and INT_MAX is 2147483647 which cannot accommodate that huge value. This appears broken on macOS.

I also see contradictory documentation on depth:

```
The depth argument specifies the maximum number of file descriptors to
     keep open while traversing the tree.  It has no effect in this implemen-tation. implementation.
     tation.

```

then,

```
ERRORS
...
In addition, either function may fail and set errno as
     follows:

     [EINVAL]           The depth argument is less than 1 or greater than
                        OPEN_MAX.
```

then,

```
BUGS
     The depth argument is currently ignored.
```

However, if `depth` is ignored we should not have any issues. I don't know if the documnetation is the most recent. Can you check the `nftw` man page on your installed and help us?

Also, please print and share the value of `FOPEN_MAX`.

**Comment by usualwitch** [comment]
The doc is the same on mac, confusing indeed.

I got `FOPEN_MAX = 20` when I run nnn.

**Comment by jarun** [comment]
That's too low. How about `OPEN_MAX`?

**Comment by jarun** [comment]
I get `OPEN_MAX` as 10240 on fastmac.

```
$ sw_vers -productVersion
10.15.7
```

Please confirm the number from your version.

**Comment by jarun** [comment]
Please confirm the patch works.

PS: please confirm the value of `OPEN_MAX` still.

**Comment by jarun** [comment]
@usualwitch we can use your hep to fix the Homebrew script test to pass https://github.com/Homebrew/homebrew-core/pull/75096.
