### ISSUE TITLE
Close CMD prompt on Ctrl + D

### ISSUE THREAD

**Issue by GeorgVIII** [jarun/nnn#943]
**Is your feature request related to a problem? Please describe.**

Currently when you open Cmd prompt on ], it asks you to press Enter after each executed command. But if you instead accidentally press Ctrl + D with intention to close it, nnn will just hang, and you will have to terminate it with kill.

**Describe the solution you'd like**

It would be nice, if nnn would just close Cmd prompt when it received EOF with Ctrl + D.

**Comment by jarun** [comment]
Please test on master. I can press `^D` and quit the cmd prompt.

**Comment by GeorgVIII** [comment]
I just cloned and build the latest source, it is still there.

Maybe I described my problem poorly, to reproduce it i type the sequence "]lsENTER^D", i.e. I press ^D when the prompt asks to press ENTER to continue.

I run Artix linux with all latest upgrades.

**Comment by jarun** [comment]
> I press ^D when the prompt asks to press ENTER to continue.

The prompt didn't ask you to press `^D`, right? So please press `Enter` now that you have read the prompt and know the behaviour. We do not have the time to spend on working on this trivia and ensure it works both in the readline and native cases. Thanks!

**Comment by GeorgVIII** [comment]
Pressing `^D` is a rather automatic thing, but thank you for your time.

**Comment by jarun** [comment]
Thanks for your understanding.

**Comment by jarun** [comment]
@GeorgVIII please check commit c37bc90918336028897afdd5a6e2e642ba6cb570.

You should be able to get past both the `'Enter' to continue` and the prompt with <kbd>^D</kbd>.

This is one of those cases where we need time to get to the correct solution.
We don't always have ready solutions for these tiny little things and looking up in the web doesn't really help. As you'll see in this case, it's really a very simple approach that's too hard to find.
