### ISSUE TITLE
How to set a default pdf viewer?

### ISSUE THREAD

**Issue by ThomasBucaioni** [jarun/nnn#947]
It's certainly not a new feature, but I didn't manage to find the answer in the documentation

**Comment by luukvbaal** [comment]
From the man page: 
"uses `xdg-open` (on Linux), `open(1)` (on macOS), `cygstart` on (Cygwin) and `open` on (Haiku) as the desktop opener. It's also possible to specify a custom opener. See ENVIRONMENT section."

It's also mentioned in the wiki [here](https://github.com/jarun/nnn/wiki/Usage), setting the default pdf viewer would entail configuring the default opener.

**Comment by ThomasBucaioni** [comment]
> uses `xdg-open` (on Linux)

Not used to `xdg-open`, thank you

**Comment by luukvbaal** [comment]
If you have a different opener you are used to you can configure `nnn` to use that with the `NNN_OPENER` environment variable.

**Comment by ThomasBucaioni** [comment]
It's fixed: in my `~/.config/mimeapps.list` I added 
```
application/pdf=org.pwmt.zathura-pdf-poppler.desktop
```
under the `[Default Applications]` and that's it. Thanks for the `xdg-open` discovery, I think I'm going to make a bit of cleaning down there...
