### ISSUE TITLE
Unable to delete files

### ISSUE THREAD

**Issue by sierra1bravo** [jarun/nnn#948]
Hi

Although nnn appears to be rich in features, I'm unable to delete, copy or move files. The shift commands do not work for me (I'm using Ubuntu 18.04). What's wrong?

s1b

**Comment by jarun** [comment]
There are no shift commands. `^` stands for the `Ctrl` key.

**Comment by sierra1bravo** [comment]
Hi

Thanks. Can you pls point me to the documentation page that has the delete
command?



s1b

**Comment by jarun** [comment]
Press `?` in `nnn`.

Quickstart: https://github.com/jarun/nnn#quickstart
Wiki: https://github.com/jarun/nnn/wiki
