### ISSUE TITLE
ICONLOOKUP not work in preview-tui-ext

### ISSUE THREAD

**Issue by pooh2pooh** [jarun/nnn#950]
Hi!

I can't turn on the icons in the plugin preview-tui-ext, I made export ICONLOOKUP=1 and export FZF_DEFAULT-OPTS="--ansi" and install fzf

Terminal: kitty

**Comment by luukvbaal** [comment]
The `iconlookup` script uses nerd font icons by default, are you using a patched nerd font in your terminal?

**Comment by pooh2pooh** [comment]
Yes. If you run: ls | iconlookup | fzf

**Comment by luukvbaal** [comment]
Is `.iconlookup` present in your `nnn` plugin directory? That's where `preview-tui-ext` looks for the iconlookup script, not in your `PATH`.

**Comment by luukvbaal** [comment]
Not sure how you are exporting `ICONLOOKUP` but please check if #951 fixes it for you.

**Comment by pooh2pooh** [comment]
.iconslookup file is in the plugins folder,
there are no errors,
export ICONLOOKUP in the .zshenv and terminal

updated preview-tui-ext also does not show icons :(

Screenshots:
https://d.poohprod.ru/2021-04-20_285x101.png
https://d.poohprod.ru/2021-04-20_607x166.png

**Comment by luukvbaal** [comment]
Hmm I don't know. Can you confirm whether its entering the `ICONLOOKUP` if statement by changing
`tree -L 1 --dirsfirst -F --noreport -i | head -n "$((lines - 3))" | "$(dirname "$0")"/.iconlookup -l "$cols" -B "$BSTR" -b " "` to e.g. `echo test`.

**Comment by pooh2pooh** [comment]
after installing tree everything worked! thanks :)

**Comment by jarun** [comment]
@pooh2pooh is `tree` mentioned in the list of dependencies in `preview-tui-ext`?

**Comment by luukvbaal** [comment]
It's listed as one of three possible dependencies(`tree`, `exa` or `ls`), I'll make a PR to prepend icons to `exa` and `ls` output as well since both support the `-F` flag for indicators.

**Comment by jarun** [comment]
OK.
