### ISSUE TITLE
custom indicator in detail mode

### ISSUE THREAD

**Issue by spareslant** [jarun/nnn#952]
**Is your feature request related to a problem? Please describe.**

I want to change the indicator in detailed mode. At the moment only two options are available.
'>' and '▒'

**Describe the solution you'd like**

A compile time or run-time option to change the indicator.

**Describe alternatives you've considered**

**Additional context**

**Consider contributing**

Please consider contributing the feature back to `nnn`.

Feel free to discuss in the ToDo list thread. We are more than happy to help.

**Comment by jarun** [comment]
Please change the code [here](https://github.com/jarun/nnn/blob/c49f24c696f1983c121c0c785e108c753dde8970/src/nnn.c#L3739-L3742) with your preferred indicator and compile it yourself. We don't want to add code to support another indicator.

**Comment by spareslant** [comment]
Thanks,  this worked. But unfortunately ACS characters list does not have many options. I ended up using ACS_DIAMOND. 
For those looking for the list,  here is the link http://melvilletheatre.com/articles/ncurses-extended-characters/index.html

**Comment by luukvbaal** [comment]
@spareslant do realize you are not restricted to the characters listed in that chart, `addch()` supports any character you can think of. You could even use `addstr()` for multibyte characters e.g. nerd font glyphs.

**Comment by spareslant** [comment]
awesome @luukvbaal . Thanks for this tip :)
