### ISSUE TITLE
Fuzzy Search and Preview 

### ISSUE THREAD

**Issue by ldelossa** [jarun/nnn#956]
**Is your feature request related to a problem? Please describe.**

Nope.

**Describe the solution you'd like**

Close this is you feel this is not good for nnn.

I use fzf for fuzzy searching and file preview. 

I use NNN for tree representation of  file system, when I need to understand hierarchy. 

If NNN grew a method to fuzzy search for directories from the root of $(pwd) this would mean I can get rid of FZF. 

File preview is nice to have, but not a big lose. I'd like to stop using fzf and just use NNN if possible.

**Comment by data-man** [comment]
> If NNN grew a method to fuzzy search for directories

I hope https://github.com/jhawthorn/fzy or https://github.com/forrestthewoods/lib_fts sources can be helpful.

**Comment by jarun** [comment]
Sorry, no bandwidth to rebuild the wheel. The fxf integration as a plugin is seamless.

**Comment by ldelossa** [comment]
Understood. I wasn't actually aware of this plugin, ill take a look.
