### ISSUE TITLE
Get the selected file for live preview to work with a MS Window previewer

### ISSUE THREAD

**Issue by jtourlamain** [jarun/nnn#959]
**Is your feature request related to a problem? Please describe.**

I can't get the live preview to work on WSL2 running on MS Windows.
On windows I use quicklook from https://github.com/QL-Win/QuickLook to preview my files. I would like to do the same from nnn running in WSL2. 

**Describe the solution you'd like**

If a hook is available that provides the file name and path every time the selection changes a bridge script can be executed to preview the file in the quicklook app. A bridge with quicklook exists so you can call a cli command to change the file in the preview window (https://github.com/QL-Win/QuickLook/wiki/Integration-and-Development)
The selected path in nnn can be found in the .lastd file, but I can't find the filename that is currently selected in nnn. If I cat the fifo file. nothing can be seen (I guess I don't understand how it works). 

Opening files in MS Windows apps works via a command plugin ```-_cmd.exe /C start $nnn*``` but that principle doesn't fit for a live preview.

Alternative:
The live view solutions with tmux works on windows terminal for text files.

**Comment by luukvbaal** [comment]
See if #960 works for you. I'm not familiar with `QuickLook` and I'm not quite sure what's the point of the `Bridge.exe` but this seems to work fine.

**Comment by jarun** [comment]
Closed at #960.
