### ISSUE TITLE
ability to start  nnn with preset contexts

### ISSUE THREAD

**Issue by shedali** [jarun/nnn#962]
happy fourth birthday nnn!

nnn ~/myfolder launches nnn at position of first argument. Then every context begins at the same position.

It would be cool to set context positions on lauch as additional arguments like:

nnn ~/folder1 ~/folder2 ~/folder3 ~/folder4

**Comment by jarun** [comment]
Please use sessions and persistent sessions.

Having to type the full path of multiple directories when you start `nnn` each time defeats the purpose of having `nnn`. ;)

You should just fire `nnn`, <kbd>Tab</kbd> to open a new context and navigate to another directory in the new context.
