### ISSUE TITLE
feature requests (and PR's) for gpg* plugins

### ISSUE THREAD

**Issue by sudomain** [jarun/nnn#964]
Thank you for developing `nnn`. Here are a few things I think can improve the gpg plugins:

Suggestions for both gpge and gpgd:
1. better handling of invalid input. These `else`s allow the user to input nonsense such as:
`(s)ymmetric, (a)symmetric? [default=a] g
(s)election/(c)urrent? [default=c] i`

And the defaults will be used. Don't get me wrong, I like the default options, but I think an error should be printed if a wrong letter is chosen. These are the `else`s:
https://github.com/jarun/nnn/blob/b0a985bca863da88eb27ac0f6f8f6eab6cec36e9/plugins/gpge#L18
https://github.com/jarun/nnn/blob/b0a985bca863da88eb27ac0f6f8f6eab6cec36e9/plugins/gpge#L24
https://github.com/jarun/nnn/blob/b0a985bca863da88eb27ac0f6f8f6eab6cec36e9/plugins/gpgd#L17

Suggestions for just gpgd:

2. an option to pipe a decrypted textfile to PAGER rather than writing to a file

3. don't add the .dec extension when decrypting. I'm not sure what the use of the extension is.

4. a solution or at least a friendlier error message when decrypting with a private key that is still 'locked' (the key has a passphrase and it hasn't been supplied) 

Suggestion for a single unified plugin gpg[e|d]:
 
5. I think a single plugin for both encrypting and decrypting could be beneficial. It could automatically detect if the selected file(s) are already encrypted/decrypted and choose to do the correct* thing (decrypting encrypted files and encrypting plain files). An error would happen if the selection contains a mix of encrypted and decrypted files. This makes an assumption that the user wouldn't want to encrypt an already encrypted file.

I'm willing to work on PR's for suggestions that are approved.

**Comment by jarun** [comment]
@KlzXS please have a look.

**Comment by KlzXS** [comment]
1. Other plugins we have also do it that way. I think we should be consistent.
2. This is mostly fine. It would require another prompt and the default should be write to file. The only potential issue is piping binary data to `$PAGER`. 
3. What would you do then? You can't output it back to the same filename. Remove the (.gpg) extension? What if the file doesn't have any? You posed it as a problem, yet provided no alternative.
4. Doesn't `gpg` itself handle this with an appropriate error message?
5. > It could automatically detect if the selected file(s) are already encrypted/decrypted

Is there a good way of doing this that doesn't require reading the files more than necessary?

> An error would happen if the selection contains a mix of encrypted and decrypted files.

You just said that it should detect the status of the file and choose the appropriate option, why the error now?

I don't think it would be a great idea to merge them. I don't see how that improves the user experience. If anything it would break any existing ones.

**Comment by KlzXS** [comment]
To add for 2. There would also need to be a delimiter between the contents of the files, obviously.

**Comment by akimdi** [comment]
can sequoia be added as an alternative?
https://archlinux.org/packages/community/x86_64/sequoia

**Comment by sudomain** [comment]
1. Fair.

2. (I don't have further comment. this is put here because GH markdown messes with the numbering of the list, please ignore)

3. >What would you do then? You can't output it back to the same filename. Remove the (.gpg) extension? What if the file doesn't have any?

Now I understand what it's for. I was focused on the fact that `gpge` always creates files with the .gpg extension, I hadn't considered that alternative. Nevertheless what if we did both: 
If it doesn't have the .gpg extension, then se current behavior of making .dec files. If a file has the .gpg extension, I would output the decrypted file to the same name without the extension. Gpg will prevent accidental overwriting in both cases.

4. If my key is locked, I get the following error  which seems a bit cryptic (pardon the pun):
`gpg: public key decryption failed: Not a typewriter
gpg: decryption failed: No secret key`
This is because gpg is trying to prompt for the password while nnn is in the foreground. Maybe print something like 
`your private key is locked and can't be unlocked in nnn, please unlock it before attempting to decrypt`

5. > Is there a good way of doing this that doesn't require reading the files more than necessary?

Parse the output of `file`? This would be independent of whether a file has the .gpg extension:
`$ file myfile
myfile: PGP RSA encrypted session key - keyid:`

> You just said that it should detect the status of the file and choose the appropriate option, why the error now?

I phrased this poorly. Sorry. 

If we're working with a single file (current), the plugin could intelligently choose to encrypt or decrypt based on if the file is already encrypted. 

If we're working with multiple files in the selection:
* if the files are all encrypted, then decrypt them. 
* If the files are all not encrypted, then encrypt them
* if the selection contains a mix of encrypted and decrypted files, then the error would occur.

**Comment by luukvbaal** [comment]
> If my key is locked, I get the following error  which seems a bit cryptic (pardon the pun):
>    `gpg: public key decryption failed: Not a typewriter gpg: decryption failed: No secret key`
>    This is because gpg is trying to prompt for the password while nnn is in the foreground. Maybe print something like

Are you talking about a tty environment? If you're in a graphical environment you should be getting a [`pinentry`](https://wiki.archlinux.org/index.php/GnuPG#pinentry) prompt if your key is locked.

**Comment by sudomain** [comment]
> Are you talking about a tty environment?
yup. Vanilla Termux

**Comment by luukvbaal** [comment]
Try `gpg --pinentry-mode loopback`

**Comment by luukvbaal** [comment]
Works for me, might as well be default for the plugins since `nnn` is a terminal program anyways.

**Comment by KlzXS** [comment]
3. Seems reasonable. See if you can squeeze it into the pipeline while keeping it a pipeline.
4. I see you are in a middle of a discussion and also github formatting.
5. I still fail to see why the error. If you can tell me for each file from the selection if it is encrypted or not then why don't you choose the appropriate option for each one individually? But in that case prompts get awkward.

On the other hand, you would have to go through all the files, check that they are intended for the same operation, then prompt and then do the work.

Maybe it's just me, but I really don't see merging these two as a good thing. I'm done thinking about the merge for a bit, the more I think about it the more I have to say and there is a long day ahead of me tomorrow. Instead I would like to hear how others feel about it.

**Comment by jarun** [comment]
@sudomain there's no point in merging these 2 now. They are already installed for many users who may not even notice OR get confused. For the other improvements, please go by the suggestions from @KlzXS.

**Comment by jarun** [comment]
I am closing this because I prefer to haev these discussions in the ToDo list rather than in one issue for each feature suggestion/improvement.
