### ISSUE TITLE
Consider adding a manual for nlay

### ISSUE THREAD

**Issue by Dridi** [jarun/nnn#97]
Following #96 but with a SHOULD item this time from Fedora packaging guidelines, it would be noice to document all installed programs or scripts in the default PATH.

**Comment by jarun** [comment]
Done! I'll do it by next release. Keeping the defect open till then.

**Comment by Dridi** [comment]
Thanks for both #96 and this!

**Comment by jarun** [comment]
My pleasure!

**Comment by jarun** [comment]
Had some time this evening. :)
