### ISSUE TITLE
Swapping names when batch renaming files deletes one of the files

### ISSUE THREAD

**Issue by Cephian** [jarun/nnn#971]
#### Environment details

[X] Operating System: Arch Linux 5.11.16
[X] Desktop Environment: None/DWM
[X] Terminal Emulator: st
[X] Shell: Bash
[X] Custom desktop opener (if applicable): Not sure what this means but probably N/A
[X] Program options used: None
[X] Configuration options set: None
[X] Issue exists on `nnn` master: Yes

#### Exact steps to reproduce the issue

I did the following on a clean ENV in bash with the latest master.
Inside of an empty folder:
1) `echo a > a.txt`
2) `echo b > b.txt`
3) Open `nnn`, hit 'r' to batch rename
4) Swap names of `a.txt` and `b.txt`

EXPECTATION: We have a file `a.txt` containing 'b', and `b.txt` containing 'a'.
RESULT: We have a file `a.txt` containing 'a'. The contents of `b.txt` have been lost.

**Comment by jarun** [comment]
Do you have plugins installed?

Otherwise please see - https://github.com/jarun/nnn/wiki/Troubleshooting#default-batch-rename-limits

**Comment by KlzXS** [comment]
See https://github.com/jarun/nnn/wiki/Troubleshooting#default-batch-rename-limits.

**Comment by jarun** [comment]
@KlzXS can we make the `mv` in `batchrenamecmd` interactive? I think that would help us confirm the overwrites.

**Comment by KlzXS** [comment]
I guess. Yes.

**Comment by KlzXS** [comment]
>  can we make the mv in batchrenamecmd interactive

Check out #979
