### ISSUE TITLE
Populating selection with `x2sel` plugin

### ISSUE THREAD

**Issue by amanjitsk** [jarun/nnn#976]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Ubuntu 20.04 LTS
[x] Desktop Environment: BSPWM
[x] Terminal Emulator: st and kitty
[x] Shell: zsh
[x] Custom desktop opener (if applicable): nuke
[x] Program options used:

```bash
export NNN_ARCHIVE="\\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$"
export NNN_OPENER="$XDG_CONFIG_HOME"/nnn/plugins/nuke
export NNN_TRASH=1
export NNN_COLORS="42564256"
export NNN_LOCKER="ytop -bs"
export NNN_FIFO="$XDG_RUNTIME_DIR/nnn.fifo"
export NNN_SEL="$XDG_CONFIG_HOME/nnn/selection"
```

[x] Configuration options set: `export NNN_OPTS="cCdEfHorQSUx"`
[x] Issue exists on `nnn` master: yes

#### Exact steps to reproduce the issue

When I populate the selection via the `x2sel` plugin, I notice some inconsistent
behavior with regards to working with this selection. For example, if I use the
`x2sel` plugin to populate a couple of paths into selection, and then press `E`
(for editing selection), I no longer get the editor open, but instead just get
the selection printed out (the selection populated with `x2sel` that is).

This can be inconvenient when for ex. I select a bunch of files, but then I run some
plugin which silently clears out the selection. Since I have the `-x` option
set, I have the selections copied to clipboard and I can quickly repopulate it
using `x2sel`. But then I can no longer edit this selection using `E`. 

Furthermore, when the selection is done using `x2sel`, I no longer see the
prompt `'c'urrent / 's'el ?` when trying to delete/trash this selection using
`x`. This also seems inconsistent and throws me off when I think I will be
getting a prompt confirming deleting the selection or currently hovered path.
Fortunately, the move and copy operations still work with selections via
`x2sel`.

To complicate things further, when I ordinarily select some files with `Space`
or `^J`, and then call the `x2sel` plugin, what I expect is some sort of merge
operation, which appends to the selection (if not already selected). But the
`x2sel` plugin has no effect in such a scenario (when pressing `E` after, I only
see the files selected with `Space`/`^J` in the editor).

I don't know if this has already been documented somewhere, but hopefully it can
be a quick fix to make this selection behavior of `x2sel` consistent with the
other ways of selecting (`Space`/`^J`/ selection range with `m`). Thanks again
for this super useful piece of software.

Amanjit

**Comment by jarun** [comment]
@amanjitsk these are basic scripts. Please go through your issues one by one and try to fix them. And then raise a PR. Personally I don't have the time to check these basic stuff. If someone else is interested, they can have a look.

**Comment by amanjitsk** [comment]
Noted/ I agree its pretty basic, but that is exactly why I don't have much to work with.
The script is pretty clear in what its supposed to be doing, issue is that `nnn` seems to be ignoring
(null-delimited) paths which are manually appended to the selection file `NNN_SEL`. Anyways, I'll 
look into it more.

**Comment by jarun** [comment]
> I no longer get the editor open, but instead just get
the selection printed out (the selection populated with x2sel that is).

Yes, when the local buffer is empty that means your selection is from another instance or from X. So it's just listed without any option to edit. The idea is - you should be fixing your selection from the source.

> Furthermore, when the selection is done using x2sel, I no longer see the
prompt 'c'urrent / 's'el ?

See if you are using the option `-u`. Also check if `rm` tries to delete the current file or the selection. From the code it looks like it will try to delete the current file.

> what I expect is some sort of merge
operation

No we don't merge selection from 2 different sources. Each source is independent and so is each selection process.

**Comment by amanjitsk** [comment]
> See if you are using the option -u. Also check if rm tries to delete the current file or the selection. From the code it looks like it will try to delete the current file.

I am not using the `-u` option, but yes it just deletes the current file.

> Yes, when the local buffer is empty that means your selection is from another instance or from X. So it's just listed without any option to edit. The idea is - you should be fixing your selection from the source.

Ah I see, that design choice makes more sense now that you explained it. Thanks!

**Comment by jarun** [comment]
> but yes it just deletes the current file.

This is a case we need to handle.

**Comment by jarun** [comment]
Please confirm that the patch works as intended and deletes the selection when selection is chosen and current file when current is chosen.

This was a very good issue and I've fixed it in one place. Thanks for being patient!

**Comment by amanjitsk** [comment]
> deletes the selection when selection is chosen and current file when current is chosen

Nicee, I can confirm this is now fixed.
Thanks for the quick response, y'all are awesome maintainers!
