### ISSUE TITLE
7469: Read-only file system

### ISSUE THREAD

**Issue by Moldytzu** [jarun/nnn#986]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Linux 4.16.3
[ ] Desktop Environment:
[x] Terminal Emulator: Linux's tty0 (no gui)
[x] Shell: busybox's ash
[ ] Custom desktop opener (if applicable):
[x] Program options used: none
[ ] Configuration options set:
[x] Issue exists on `nnn` master: yes

#### Exact steps to reproduce the issue
NOTE: I'm doing a custom linux distro and i'm booting off of a dvd
Compile using
`make O_NOMOUSE=1 O_NORL=1 O_NOBATCH=1 O_NOFIFO=1 O_NOSSN=1 O_NOUG=1 O_NOLOC=1 O_NOX11=1 PREFIX=customdistro-rootfspath/usr/local`
then do `make install` and then run with `nnn`, an error pops up saying "7469: Read-only file system"

**Comment by KlzXS** [comment]
> NOTE: I'm doing a custom linux distro and i'm booting off of a dvd

First off, if you are using a custom distro, especially if it's not publicly available, don't expect people to really care about the issue. Just a general tip.

Now, I see you said you're booting for a DVD. Potentially it mounted the filesystem as ro. You should really check how `/` and `/usr` are mounted and if you can change the mount option.

But if you are booting from a live DVD why would you want to install `nnn`? If you don't have some persistent data on some drive it's useless. It'll be wiped as soon as the power's out.

More info would be needed.

**Comment by Moldytzu** [comment]
I want it to be a linux rescue disk, so if your linux instalation gets corrupted and you can't boot into it you can use it, and I want a small and cool terminal file manager

**Comment by KlzXS** [comment]
I see. That is useful, but I think it's done a bit differently. Of course, I know nothing about creating a linux image, but I think you would need to include the compiled binary with the rest of the stuff and then compile it all into an image.

In any case I'm closing this issue as it's not a problem with `nnn`, but rather a problem of building an image with `nnn` included.

**Comment by jarun** [comment]
Please check the source code of `nnn` for your instalaltion. The error that you get is from `xerror()` which prints the line number. So my guess is some function call fails and most probably it is at line number 7469 in nnn.c.

See if it is `xdiraccess()` -> `opendir()`.

**Comment by jarun** [comment]
`man errno` shows `EROFS           Read-only filesystem (POSIX.1-2001).`

**Comment by jarun** [comment]
So my best guess is `nnn` tried to write to a file on a read-only filesystem. This is inline with the analysis from @KlzXS.
