### ISSUE TITLE
nnn does not cleanup mount points on exit

### ISSUE THREAD

**Issue by heroin-moose** [jarun/nnn#990]
#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: Arch Linux
[x] Desktop Environment: None
[x] Terminal Emulator: alacritty
[x] Shell: zsh
[x] Custom desktop opener (if applicable): no
[x] Program options used: none
[x] Configuration options set: none 
[x] Issue exists on `nnn` master: yes

#### Exact steps to reproduce the issue

1. Install archivemount
2. Mount some tar archive in nnn
3. Exit nnn

In `~/.config/nnn/mounts/` you'll see a mounted archive that will not go away unless you manually call umount.

**Comment by jarun** [comment]
When you mount an archive/remote manually from bash, do you see it unmounted when you close the terminal? ;)

There is no magic with `nnn` mountpoints and `nnn` can't decide if you will access them after quitting `nnn` or not. So you'll have to unmount manually or from `nnn` using <kbd>u</kbd>.
