### ISSUE TITLE
Type-to-nav question

### ISSUE THREAD

**Issue by uffejakobsen** [jarun/nnn#991]
Given the addditional special keys at empty filter prompt

how do you search for something that starts with a dot ?

example:
.profile

nnn 4.0 (@archlinux)

**Comment by luukvbaal** [comment]
You can type <kbd>\\.</kbd> with the regex filter enabled. Not being able to type <kbd>.</kbd> with the regular filter is probably intended behavior although I'm not sure about that.

**Comment by jarun** [comment]
Yes, a <kbd>.</kbd> at the empty filter prompt is re-used to toggle hidden. Use the regex alternative.

It's in the man page as well as in the wiki: https://github.com/jarun/nnn/wiki/concepts#filters
