### ISSUE TITLE
Question: nnn leaves zombies while running plugins

### ISSUE THREAD

**Issue by GeorgVIII** [jarun/nnn#999]
I noticed that each time i run plugin in nnn it creates zombie nnn child processes.
It happens both with plugins which run in background, such as
``` sh
#!/bin/sh
nohup zathura "$1" >/dev/null 2>&1 &
```
and foreground plugins, such as
``` sh
#!/bin/sh
less -S "$1"
```
After each plugin call nnn gets new child zombie, which will remain till death of the main nnn process.
![exmpl](https://user-images.githubusercontent.com/52504534/117978697-d486a100-b33a-11eb-9252-ffef8fb2b426.png)
This also happens with `imgview` with `NNN_PLUG='i:imgview'`.

**Thus question**: Is that intented?

I hope i'm not being too stupid, but i didn't manage to find an answer or a similar question myself.

**Comment by KlzXS** [comment]
> Thus question: Is that intented?
No. Good catch.

#1000 addresses this.

**Comment by jarun** [comment]
Haha! A good 1000th one @KlzXS! Love it that it comes from you! :+1:

**Comment by jarun** [comment]
@KlzXS I still see the zombie process with this. I tried the plugin:

```
#!/bin/sh
less -S "$1"
```

**Comment by jarun** [comment]
Note that we have a 3-level fork here. Also, a previous discussion here on opening files: https://github.com/jarun/nnn/issues/449

It it's not straight I will take the same stand - just live with it.

**Comment by jarun** [comment]
Sorry! It's fixed!!!
I forgot to copy the binary to bin dir.

**Comment by KlzXS** [comment]
You scared me with that zombie for a moment 😄

**Comment by jarun** [comment]
LOL! :dancing_men:

**Comment by GeorgVIII** [comment]
Thank you for your work!
